### ISSUE TITLE
Search not working

### ISSUE THREAD

**Issue by kandev** [janeczku/calibre-web#1001]
Anything I search returns the following error:

Internal Server Error
500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2446, in wsgi_app response = self.full_dispatch_request()
File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1951, in full_dispatch_request rv = self.handle_user_exception(e)
File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1820, in handle_user_exception reraise(exc_type, exc_value, tb)
File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1949, in full_dispatch_request rv = self.dispatch_request()
File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1935, in dispatch_request return self.view_functions[rule.endpoint](**req.view_args)
File "/opt/calibre-web/cps/web.py", line 146, in decorated_view return login_required(func)(*args, **kwargs)
File "/usr/local/lib/python2.7/dist-packages/flask_login/utils.py", line 261, in decorated_view return func(*args, **kwargs)
File "/opt/calibre-web/cps/web.py", line 792, in search entries = get_search_results(term)
File "/opt/calibre-web/cps/helper.py", line 744, in get_search_results func.lower(db.Books.title).ilike("%" + term + "%")
File "/opt/calibre-web/vendor/sqlalchemy/orm/query.py", line 3174, in all return list(self)
File "/opt/calibre-web/vendor/sqlalchemy/orm/query.py", line 3330, in __iter__ return self._execute_and_instances(context)
File "/opt/calibre-web/vendor/sqlalchemy/orm/query.py", line 3355, in _execute_and_instances result = conn.execute(querycontext.statement, self._params)
File "/opt/calibre-web/vendor/sqlalchemy/engine/base.py", line 988, in execute return meth(self, multiparams, params)
File "/opt/calibre-web/vendor/sqlalchemy/sql/elements.py", line 287, in _execute_on_connection return connection._execute_clauseelement(self, multiparams, params)
File "/opt/calibre-web/vendor/sqlalchemy/engine/base.py", line 1107, in _execute_clauseelement distilled_params,
File "/opt/calibre-web/vendor/sqlalchemy/engine/base.py", line 1248, in _execute_context e, statement, parameters, cursor, context
File "/opt/calibre-web/vendor/sqlalchemy/engine/base.py", line 1466, in _handle_dbapi_exception util.raise_from_cause(sqlalchemy_exception, exc_info)
File "/opt/calibre-web/vendor/sqlalchemy/util/compat.py", line 398, in raise_from_cause reraise(type(exception), exception, tb=exc_tb, cause=cause)
File "/opt/calibre-web/vendor/sqlalchemy/engine/base.py", line 1244, in _execute_context cursor, statement, parameters, context
File "/opt/calibre-web/vendor/sqlalchemy/engine/default.py", line 552, in do_execute cursor.execute(statement, parameters)
Please report this issue with all related information: Create issue
Back to home

The log file shows (searching for "test"):

[2019-08-06 08:12:47,871] ERROR {cps:1891} Exception on /search [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/calibre-web/cps/web.py", line 146, in decorated_view
    return login_required(func)(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/opt/calibre-web/cps/web.py", line 792, in search
    entries = get_search_results(term)
  File "/opt/calibre-web/cps/helper.py", line 744, in get_search_results
    func.lower(db.Books.title).ilike("%" + term + "%")
  File "/opt/calibre-web/vendor/sqlalchemy/orm/query.py", line 3174, in all
    return list(self)
  File "/opt/calibre-web/vendor/sqlalchemy/orm/query.py", line 3330, in __iter__
    return self._execute_and_instances(context)
  File "/opt/calibre-web/vendor/sqlalchemy/orm/query.py", line 3355, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/opt/calibre-web/vendor/sqlalchemy/engine/base.py", line 988, in execute
    return meth(self, multiparams, params)
  File "/opt/calibre-web/vendor/sqlalchemy/sql/elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/opt/calibre-web/vendor/sqlalchemy/engine/base.py", line 1107, in _execute_clauseelement
    distilled_params,
  File "/opt/calibre-web/vendor/sqlalchemy/engine/base.py", line 1248, in _execute_context
    e, statement, parameters, cursor, context
  File "/opt/calibre-web/vendor/sqlalchemy/engine/base.py", line 1466, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/opt/calibre-web/vendor/sqlalchemy/util/compat.py", line 398, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/opt/calibre-web/vendor/sqlalchemy/engine/base.py", line 1244, in _execute_context
    cursor, statement, parameters, context
  File "/opt/calibre-web/vendor/sqlalchemy/engine/default.py", line 552, in do_execute
    cursor.execute(statement, parameters)
OperationalError: (sqlite3.OperationalError) user-defined function raised exception
[SQL: SELECT books.id AS books_id, books.title AS books_title, books.sort AS books_sort, books.author_sort AS books_author_sort, books.timestamp AS books_timestamp, books.pubdate AS books_pubdate, books.series_index AS books_series_index, books.last_modified AS books_last_modified, books.path AS books_path, books.has_cover AS books_has_cover, books.uuid AS books_uuid
FROM books
WHERE 1 = 1 AND ((EXISTS (SELECT 1
FROM books_tags_link, tags
WHERE books.id = books_tags_link.book AND tags.id = books_tags_link.tag AND lower(lower(tags.name)) LIKE lower(?))) OR (EXISTS (SELECT 1
FROM books_series_link, series
WHERE books.id = books_series_link.book AND series.id = books_series_link.series AND lower(lower(series.name)) LIKE lower(?))) OR (EXISTS (SELECT 1
FROM books_authors_link, authors
WHERE books.id = books_authors_link.book AND authors.id = books_authors_link.author AND (EXISTS (SELECT 1
FROM books_authors_link, authors
WHERE books.id = books_authors_link.book AND authors.id = books_authors_link.author AND lower(lower(authors.name)) LIKE lower(?))))) OR (EXISTS (SELECT 1
FROM books_publishers_link, publishers
WHERE books.id = books_publishers_link.book AND publishers.id = books_publishers_link.publisher AND lower(lower(publishers.name)) LIKE lower(?))) OR lower(lower(books.title)) LIKE lower(?))]
[parameters: (u'%test%', u'%test%', u'%test%', u'%test%', u'%test%')]
(Background on this error at: http://sqlalche.me/e/e3q8)

**Comment by izenn** [comment]
I also am having this issue

**Comment by OzzieIsaacs** [comment]
You should install unidecode, like listed in the requirements.txt.

I added a fix, so search is working again without it (but it's still not the recommended way)

**Comment by wwek** [comment]
I also am having this issue
