### ISSUE TITLE
ModuleNotFoundError: No module named 'pysqlite2'

### ISSUE THREAD

**Issue by lucker999** [janeczku/calibre-web#1055]
Hi, I try to start the calibre-web, but get an error:

```
# python /usr/local/calibre-web/cps.py
Traceback (most recent call last):
  File "/usr/local/calibre-web/vendor/sqlalchemy/dialects/sqlite/pysqlite.py", line 400, in dbapi
    from pysqlite2 import dbapi2 as sqlite
ModuleNotFoundError: No module named 'pysqlite2'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/calibre-web/cps.py", line 34, in <module>
    from cps import create_app
  File "/usr/local/calibre-web/cps/__init__.py", line 66, in <module>
    ub.init_db(cli.settingspath)
  File "/usr/local/calibre-web/cps/ub.py", line 473, in init_db
    engine = create_engine(u'sqlite:///{0}'.format(app_db_path), echo=False)
  File "/usr/local/calibre-web/vendor/sqlalchemy/engine/__init__.py", line 479, in create_engine
    return strategy.create(*args, **kwargs)
  File "/usr/local/calibre-web/vendor/sqlalchemy/engine/strategies.py", line 87, in create
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "/usr/local/calibre-web/vendor/sqlalchemy/dialects/sqlite/pysqlite.py", line 405, in dbapi
    raise e
  File "/usr/local/calibre-web/vendor/sqlalchemy/dialects/sqlite/pysqlite.py", line 403, in dbapi
    from sqlite3 import dbapi2 as sqlite  # try 2.5+ stdlib name.
  File "/usr/local/lib/python3.6/sqlite3/__init__.py", line 23, in <module>
    from sqlite3.dbapi2 import *
  File "/usr/local/lib/python3.6/sqlite3/dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ModuleNotFoundError: No module named '_sqlite3'
```
FreeBSD-12.0, installation in a jail. 
Python 3.6
All fresh installed (the most current versions)

Any thoughts?

**Comment by lucker999** [comment]
Re-build sqlite3 with python3.6 as [suggested on the freebsd forum](https://forums.freebsd.org/threads/sqlite3-on-python3-fails.53114/post-298287) didn't help. The issue still there.

**Comment by lucker999** [comment]
Nevermind, sorry. I should instal `py36-sqlite3` as well. Then the error is gone.

Also, FYI, please do not update pip in command line (as I did), because the calibre-web installer strictly requires the certain version.
```
pip-3.6 install --target vendor -r requirements.txt
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.VersionConflict: (pip 19.2.3 (/usr/local/lib/python3.6/site-packages), Requirement.parse('pip==19.1.1'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/pip-3.6", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3250, in <module>
    @_call_aside
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3234, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3263, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 585, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 598, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'pip==19.1.1' distribution was not found and is required by the application
```
Once again, sorry. Please close the issue.
