### ISSUE TITLE
Deleted a book and cannot reupload it.

### ISSUE THREAD

**Issue by stefmitropoulos** [janeczku/calibre-web#1060]
Hello people. 

I deleted a book from my collection and then tried to upload a different version of it. The upload finished but when it switched to processing, i got the following error:

```
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN"> <title>500 Internal Server Error</title>
```

In the logs, I get :

```
[2019-10-09 19:38:19,096] ERROR in app: Exception on /upload [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/app/calibre-web/cps/web.py", line 349, in decorated_view
    return login_required(func)(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/app/calibre-web/cps/web.py", line 495, in inner
    return f(*args, **kwargs)
  File "/app/calibre-web/cps/web.py", line 3769, in upload
    if request.method == 'POST' and 'btn-upload' in request.files:
    self._load_form_data()
  File "/usr/local/lib/python2.7/dist-packages/flask/wrappers.py", line 88, in _load_form_data
    RequestBase._load_form_data(self)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/wrappers/base_request.py", line 318, in _load_form_data
    self._get_stream_for_parsing(), mimetype, content_length, options
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/formparser.py", line 232, in parse
    return parse_func(self, stream, mimetype, content_length, options)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/formparser.py", line 131, in wrapper
    return f(self, stream, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/formparser.py", line 253, in _parse_multipart
    form, files = parser.parse(stream, boundary, content_length)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/formparser.py", line 584, in parse
    return self.cls(form), self.cls(files)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/datastructures.py", line 420, in __init__
    for key, value in mapping or ():
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/formparser.py", line 582, in <genexpr>
    form = (p[1] for p in formstream if p[0] == "form")
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/formparser.py", line 555, in parse_parts
    _write(ell)
  File "/usr/lib/python2.7/tempfile.py", line 626, in write
    rv = file.write(s)
IOError: [Errno 28] No space left on device
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/__init__.py", line 892, in emit
    self.flush()
  File "/usr/lib/python2.7/logging/__init__.py", line 852, in flush
    self.stream.flush()
IOError: [Errno 28] No space left on device
Logged from file app.py, line 1891
::ffff:172.18.0.1 - - [2019-10-09 19:38:19] "POST /calibre-web/upload HTTP/1.0" 500 444 1.492612
```

I am on CentOS 7 and run calibreweb on a docker container.

I notice the error [Errno 28], thought my disks are far from full (the volume i am mounting has 1T left). I tried to upload another book and it uploaded fine with no problem whatsoever.

A second run produced this in the logs:

```
[2019-10-09 19:47:28,590] ERROR in app: Exception on /upload [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/app/calibre-web/cps/web.py", line 349, in decorated_view
    return login_required(func)(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/app/calibre-web/cps/web.py", line 495, in inner
    return f(*args, **kwargs)
  File "/app/calibre-web/cps/web.py", line 3785, in upload
    meta = uploader.upload(requested_file)
  File "/app/calibre-web/cps/uploader.py", line 44, in upload
::ffff:172.18.0.1 - - [2019-10-09 19:47:28] "POST /calibre-web/upload HTTP/1.0" 500 444 2.258519
```

Any ideas?

**Comment by OzzieIsaacs** [comment]
Sorry for the late reply. Error 28 means indead no space left, I have no idea, why this error should come, if the disk isn't full. I can't reproduce this one.
You are using the version 0.6.4 i guess? Is it possible to update calibre-web within the container?

The error message is not very helpful (which is not your fault), the real cause e.g. IOError, TypeError or whatever is missing. I can only say the code line is the line saving the file to the disk. One reason could be, you are not allowed to write to the tempfolder (but this should not occur on a tested docker container)
