### ISSUE TITLE
Installation failed, Tornado version issue

### ISSUE THREAD

**Issue by n3ssi3** [janeczku/calibre-web#1070]
```
➜  calibre-web git:(master) python cps.py
Traceback (most recent call last):
  File "cps.py", line 34, in <module>
    from cps import create_app
  File "/Applications/calibre-web/cps/__init__.py", line 38, in <module>
    from .server import WebServer
  File "/Applications/calibre-web/cps/server.py", line 33, in <module>
    from tornado.wsgi import WSGIContainer
  File "/Applications/calibre-web/vendor/tornado/wsgi.py", line 51
    def to_wsgi_str(s: bytes) -> str:
                     ^
SyntaxError: invalid syntax
```

I just downloaded the latest master and followed the installation.

MacOS 10.13.6
Python 2.7.10
tornado-6.0.3.dist-info

**Works when tornado is fixed to v5.1**

**Comment by OzzieIsaacs** [comment]
Correct. Tornado is no longer python 2 compatible.
