### ISSUE TITLE
Error 500 on newly installed calibre-web on Ubuntu 16.04

### ISSUE THREAD

**Issue by benzoto** [janeczku/calibre-web#1106]
Any ideas why this error is popping up? I've checked for such issues before with older versions.

Internal Server Error
500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
```
File "/home/muser/calibre-web/vendor/flask/app.py", line 2446, in wsgi_app response = self.full_dispatch_request()
File "/home/muser/calibre-web/vendor/flask/app.py", line 1951, in full_dispatch_request rv = self.handle_user_exception(e)
File "/home/muser/calibre-web/vendor/flask/app.py", line 1820, in handle_user_exception reraise(exc_type, exc_value, tb)
File "/home/muser/calibre-web/vendor/flask/_compat.py", line 39, in reraise raise value
File "/home/muser/calibre-web/vendor/flask/app.py", line 1949, in full_dispatch_request rv = self.dispatch_request()
File "/home/muser/calibre-web/vendor/flask/app.py", line 1935, in dispatch_request return self.view_functions[rule.endpoint](**req.view_args)
File "/home/muser/calibre-web/cps/web.py", line 147, in decorated_view return login_required(func)(*args, **kwargs)
File "/home/muser/calibre-web/vendor/flask_login/utils.py", line 261, in decorated_view return func(*args, **kwargs)
File "/home/muser/calibre-web/cps/web.py", line 457, in index entries, random, pagination = fill_indexpage(page, db.Books, True, [db.Books.timestamp.desc()])
File "/home/muser/calibre-web/cps/helper.py", line 709, in fill_indexpage randm = db.session.query(db.Books).filter(common_filters())\
```

**Comment by benzoto** [comment]
And this is happening if I manually create metadata.db file and point to it. Without this, I can't setup any Location of the DB, as it is not automatically creating the file or not recognizing properly the file structure.
The Calibre-web is installed under /home/user/calibre-web
I'm trying to add the following database location: /home/user/calibre-web/Books but it is not working

**Comment by OzzieIsaacs** [comment]
Could you please check the logfile. The posted error message is truncated, the final part is the important one.
Please post it here. Which version are you using (I guess you are not using docker?). Which python version 2/3 are you using?

**Comment by benzoto** [comment]
Thx for the quick reply. I followed the installation instructions in the Quick Start section in git. I have both Python 2.8 and Python 3.5 The whole calibre-web.log attached below
AttributeError: 'NoneType' object has no attribute 'query'
[2019-12-12 15:40:50,000] ERROR {cps:1891} Exception on / [GET]
Traceback (most recent call last):
  File "/home/muser/calibre-web/vendor/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/muser/calibre-web/vendor/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/muser/calibre-web/vendor/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/muser/calibre-web/vendor/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/muser/calibre-web/vendor/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/muser/calibre-web/vendor/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/muser/calibre-web/cps/web.py", line 147, in decorated_view
    return login_required(func)(*args, **kwargs)
  File "/home/muser/calibre-web/vendor/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/muser/calibre-web/cps/web.py", line 457, in index
    entries, random, pagination = fill_indexpage(page, db.Books, True, [db.Books.timestamp.desc()])
  File "/home/muser/calibre-web/cps/helper.py", line 709, in fill_indexpage
    randm = db.session.query(db.Books).filter(common_filters())\
AttributeError: 'NoneType' object has no attribute 'query'
[2019-12-12 15:42:13,456] ERROR {cps:1891} Exception on / [GET]
Traceback (most recent call last):
  File "/home/muser/calibre-web/vendor/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/muser/calibre-web/vendor/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/muser/calibre-web/vendor/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/muser/calibre-web/vendor/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/muser/calibre-web/vendor/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/muser/calibre-web/vendor/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/muser/calibre-web/cps/web.py", line 147, in decorated_view
    return login_required(func)(*args, **kwargs)
  File "/home/muser/calibre-web/vendor/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/muser/calibre-web/cps/web.py", line 457, in index
    entries, random, pagination = fill_indexpage(page, db.Books, True, [db.Books.timestamp.desc()])
  File "/home/muser/calibre-web/cps/helper.py", line 709, in fill_indexpage
    randm = db.session.query(db.Books).filter(common_filters())\
AttributeError: 'NoneType' object has no attribute 'query'
[2019-12-12 15:42:29,305] ERROR {cps:1891} Exception on / [GET]
Traceback (most recent call last):
  File "/home/muser/calibre-web/vendor/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/muser/calibre-web/vendor/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/muser/calibre-web/vendor/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/muser/calibre-web/vendor/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/muser/calibre-web/vendor/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/muser/calibre-web/vendor/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/muser/calibre-web/cps/web.py", line 147, in decorated_view
    return login_required(func)(*args, **kwargs)
  File "/home/muser/calibre-web/vendor/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/muser/calibre-web/cps/web.py", line 457, in index
    entries, random, pagination = fill_indexpage(page, db.Books, True, [db.Books.timestamp.desc()])
  File "/home/muser/calibre-web/cps/helper.py", line 709, in fill_indexpage
    randm = db.session.query(db.Books).filter(common_filters())\
AttributeError: 'NoneType' object has no attribute 'query'
[2019-12-12 15:42:33,712] ERROR {cps:1891} Exception on / [GET]
Traceback (most recent call last):
  File "/home/muser/calibre-web/vendor/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/muser/calibre-web/vendor/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/muser/calibre-web/vendor/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/muser/calibre-web/vendor/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/muser/calibre-web/vendor/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/muser/calibre-web/vendor/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/muser/calibre-web/cps/web.py", line 147, in decorated_view
    return login_required(func)(*args, **kwargs)
  File "/home/muser/calibre-web/vendor/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/muser/calibre-web/cps/web.py", line 457, in index
    entries, random, pagination = fill_indexpage(page, db.Books, True, [db.Books.timestamp.desc()])
  File "/home/muser/calibre-web/cps/helper.py", line 709, in fill_indexpage
    randm = db.session.query(db.Books).filter(common_filters())\
AttributeError: 'NoneType' object has no attribute 'query'
[2019-12-12 15:42:35,831] ERROR {cps:1891} Exception on / [GET]
Traceback (most recent call last):
  File "/home/muser/calibre-web/vendor/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/muser/calibre-web/vendor/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/muser/calibre-web/vendor/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/muser/calibre-web/vendor/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/muser/calibre-web/vendor/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/muser/calibre-web/vendor/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/muser/calibre-web/cps/web.py", line 147, in decorated_view
    return login_required(func)(*args, **kwargs)
  File "/home/muser/calibre-web/vendor/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/muser/calibre-web/cps/web.py", line 457, in index
    entries, random, pagination = fill_indexpage(page, db.Books, True, [db.Books.timestamp.desc()])
  File "/home/muser/calibre-web/cps/helper.py", line 709, in fill_indexpage
    randm = db.session.query(db.Books).filter(common_filters())\
AttributeError: 'NoneType' object has no attribute 'query'
[2019-12-12 15:42:39,183]  INFO {cps.server:194} webserver stop (restart=False)
[2019-12-12 15:44:29,317]  INFO {cps.server:179} Performing shutdown of Calibre-Web
[2019-12-12 15:44:29,664] ERROR {asyncio:1148} Task was destroyed but it is pending!
task: <Task pending coro=<HTTP1ServerConnection._server_request_loop() running at /usr/local/lib/python3.5/dist-packages/tornado/http1connection.py:817> wait_for=<Future pending cb=[Task._wakeup()]> cb=[IOLoop.add_future.<locals>.<lambda>() at /usr/local/lib/python3.5/dist-packages/tornado/ioloop.py:690]>
[2019-12-12 15:44:29,665] ERROR {asyncio:1148} Task was destroyed but it is pending!
task: <Task pending coro=<HTTP1ServerConnection._server_request_loop() running at /usr/local/lib/python3.5/dist-packages/tornado/http1connection.py:817> wait_for=<Future pending cb=[Task._wakeup()]> cb=[IOLoop.add_future.<locals>.<lambda>() at /usr/local/lib/python3.5/dist-packages/tornado/ioloop.py:690]>
[2019-12-12 15:44:58,849]  INFO {cps:89} Starting Calibre Web...
[2019-12-12 15:44:58,852]  WARN {cps.config_sql:259} invalidating configuration
[2019-12-12 15:44:59,108]  INFO {cps.server:152} Starting Tornado server on :8083
[2019-12-12 15:45:16,362]  WARN {cps.config_sql:259} invalidating configuration
[2019-12-12 15:45:29,380]  WARN {cps.config_sql:259} invalidating configuration
[2019-12-12 16:16:51,536]  WARN {cps.config_sql:259} invalidating configuration
[2019-12-12 16:24:11,842]  WARN {cps.config_sql:259} invalidating configuration
[2019-12-12 16:24:31,052]  WARN {cps.config_sql:259} invalidating configuration
[2019-12-12 16:24:42,936]  WARN {cps.config_sql:259} invalidating configuration
[2019-12-12 16:24:52,943]  WARN {cps.config_sql:259} invalidating configuration
[2019-12-12 16:25:02,799]  WARN {cps.config_sql:259} invalidating configuration
[2019-12-12 16:25:13,487]  WARN {cps.config_sql:259} invalidating configuration
[2019-12-12 16:56:10,444]  INFO {cps:89} Starting Calibre Web...
[2019-12-12 16:56:10,446]  WARN {cps.config_sql:259} invalidating configuration
[2019-12-12 16:56:10,697]  INFO {cps.server:152} Starting Tornado server on :8083
[2019-12-12 16:56:10,700] ERROR {cps.server:172} Error starting server: [Errno 98] Address already in use
[2019-12-12 16:56:53,516]  WARN {cps.config_sql:259} invalidating configuration
[2019-12-12 16:57:07,738]  WARN {cps.config_sql:259} invalidating configuration

**Comment by OzzieIsaacs** [comment]
I'm having the feeling you just created a empty file named metadata.db and pointed to it. 
This is not how it works, you should create this file with calibre (https://calibre-ebook.com/download). 

I will implement a check, that the metadata.db file can't be empty.

**Comment by benzoto** [comment]
The thing is that i've tried creating the metadata.db by myself but obviously it didn't worked hence i've removed it. The folder that i've created was /Books in the /home/user/calibre-web/Books as it was not created automatically nor the metadata.db
However, even without the empty metadata.db the GUI Setup Database location configuration does not accept anything I try to add, no matter the permissions. I've checked the calibre installation but I wanted to install the calibre-web, not sure what the difference is though

**Comment by OzzieIsaacs** [comment]
Just install calibre on any computer you want. Start it once, create a library at any location you want. Close calibre, deinstall calibre, take the metadata.db copy it to any folder you want, start calibre-web, enter the path for the metadata.db file in calibre web, and be happy (worked for me always).
The metadata.db file calibre creates, is a sqllite database (with the right table names and structure), this one is used by calibre-web.

**Comment by OzzieIsaacs** [comment]
I don't know the contents of this metadata.db, maybe you can use it. (https://github.com/kovidgoyal/calibre/blob/master/src/calibre/db/tests/metadata.db)

**Comment by benzoto** [comment]
It worked, btw. I can access it without issues copying this metadata.db that you've shared.
THANK YOU :)

A side question, how can I add/map a NW local drive with eBooks as default Location so that Calibre can recognize the library? Sorry if I'm being stupid but i could not find that...

**Comment by OzzieIsaacs** [comment]
Stupid question back: What is a "NW local drive"? 
Calibre has a sqlite database (metadata.db) on the top of its folder structure. All books are stored in folders with authors names and under the authors name every book has a seperate folder with the title of the book. To make calibre aware of this books you have to add the books in the calibre app or via upload in calibre-web

**Comment by benzoto** [comment]
I'm so sorry, I've missed the "/" NW or Local Drive, I've tried upload but it is not allowing me to add a folder but book by book, which is too much manual effort :)

**Comment by OzzieIsaacs** [comment]
You should be able to add books via calibre desktop app in seperate folders ( I think this was a setting in the adding book section seperate book per folder or all books in one folder (default)). 
One idea would be search all book formats and copy all books to a single folder and add it via calibre (if there are many books >100, I recommend using the desktop app and not calibre-web

**Comment by OzzieIsaacs** [comment]
As the inital problem is solved, I will close the issue.
