### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by cwilcoxc** [janeczku/calibre-web#1121]
I'm receiving an internal server error after adding a large number of new books to my calibre database. It's been about 6 hours since uploading the books and the error has not gone away.

`500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
`

The command line reads:
`File "/usr/lib/python2.7/site-packages/flask/app.py", line 2446, in wsgi_app response = self.full_dispatch_request()
File "/usr/lib/python2.7/site-packages/flask/app.py", line 1951, in full_dispatch_request rv = self.handle_user_exception(e)
File "/usr/lib/python2.7/site-packages/flask/app.py", line 1820, in handle_user_exception reraise(exc_type, exc_value, tb)
File "/usr/lib/python2.7/site-packages/flask/app.py", line 1949, in full_dispatch_request rv = self.dispatch_request()
File "/usr/lib/python2.7/site-packages/flask/app.py", line 1935, in dispatch_request return self.view_functions[rule.endpoint](**req.view_args)
File "/calibre-web/app/cps/web.py", line 146, in decorated_view return login_required(func)(*args, **kwargs)
File "/usr/lib/python2.7/site-packages/flask_login/utils.py", line 261, in decorated_view return func(*args, **kwargs)
File "/calibre-web/app/cps/web.py", line 464, in index entries, random, pagination = fill_indexpage(page, db.Books, True, [db.Books.timestamp.desc()])
File "/calibre-web/app/cps/helper.py", line 733, in fill_indexpage len(db.session.query(database).filter(db_filter).filter(common_filters()).all()))
File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 3211, in all return list(self)
File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 3367, in __iter__ return self._execute_and_instances(context)
File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 3392, in _execute_and_instances result = conn.execute(querycontext.statement, self._params)
File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 982, in execute return meth(self, multiparams, params)
File "/usr/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 287, in _execute_on_connection return connection._execute_clauseelement(self, multiparams, params)
File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1101, in _execute_clauseelement distilled_params,
File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1250, in _execute_context e, statement, parameters, cursor, context
File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1476, in _handle_dbapi_exception util.raise_from_cause(sqlalchemy_exception, exc_info)
File "/usr/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 398, in raise_from_cause reraise(type(exception), exception, tb=exc_tb, cause=cause)
File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1246, in _execute_context cursor, statement, parameters, context
File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 581, in do_execute cursor.execute(statement, parameters)`

I am running on Ubuntu 18.04.3 LTS in docker. I was logged in as admin.

I'm a bit of a noob to this - only setting it up for the first time so any detailed advice about location of files to edit would be appreciated.

Thanks in advance for support.

**Comment by OzzieIsaacs** [comment]
Please restart the application. 
I don‘t know what caused the problem, but currently the database can‘t accessed anymore.

**Comment by cwilcoxc** [comment]
Thanks for the swift response.

Calibre-web has reloaded but has not updated with the books which were recently loaded successfully into the calibrebd.

I had initially tested the calibre library with 1 book which is still showing in calibre-web, but the remaining 300 are not displaying for some bizarre reason.

I have attempted to reconnect to calibrebd, but no joy. These are the logs:

`[2019-12-31 13:08:35,129] ERROR {cps:1891} Exception on / [GET]
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/calibre-web/app/cps/web.py", line 146, in decorated_view
    return login_required(func)(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/calibre-web/app/cps/web.py", line 464, in index
    entries, random, pagination = fill_indexpage(page, db.Books, True, [db.Books.timestamp.desc()])
  File "/calibre-web/app/cps/helper.py", line 733, in fill_indexpage
    len(db.session.query(database).filter(db_filter).filter(common_filters()).all()))
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 3211, in all
    return list(self)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 3367, in __iter__
    return self._execute_and_instances(context)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 3392, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 982, in execute
    return meth(self, multiparams, params)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1101, in _execute_clauseelement
    distilled_params,
  File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1250, in _execute_context
    e, statement, parameters, cursor, context
  File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1476, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 398, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1246, in _execute_context
    cursor, statement, parameters, context
  File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 581, in do_execute
    cursor.execute(statement, parameters)
DatabaseError: (sqlite3.DatabaseError) database disk image is malformed
[SQL: SELECT books.id AS books_id, books.title AS books_title, books.sort AS books_sort, books.author_sort AS books_author_sort, books.timestamp AS books_timestamp, books.pubdate AS books_pubdate, books.series_index AS books_series_index, books.last_modified AS books_last_modified, books.path AS books_path, books.has_cover AS books_has_cover, books.uuid AS books_uuid 
FROM books 
WHERE NOT (EXISTS (SELECT 1 
FROM books_tags_link, tags 
WHERE books.id = books_tags_link.book AND tags.id = books_tags_link.tag AND tags.name IN (?)))]
[parameters: (u'',)]
(Background on this error at: http://sqlalche.me/e/4xp6)
[2019-12-31 13:11:08,288]  INFO {cps:89} Starting Calibre Web...
[2019-12-31 13:11:26,370]  INFO {cps:89} Starting Calibre Web...
[2019-12-31 13:11:42,649]  INFO {cps:89} Starting Calibre Web...
[2019-12-31 13:11:58,690]  INFO {cps:89} Starting Calibre Web...
[2019-12-31 13:12:14,116]  INFO {cps:89} Starting Calibre Web...
[2019-12-31 13:12:31,320]  INFO {cps:89} Starting Calibre Web...
[2019-12-31 13:12:46,872]  INFO {cps:89} Starting Calibre Web...
[2019-12-31 13:13:02,624]  INFO {cps:89} Starting Calibre Web...
[2019-12-31 13:13:24,622]  INFO {cps:89} Starting Calibre Web...
[2019-12-31 13:14:00,866]  INFO {cps:89} Starting Calibre Web...
[2019-12-31 13:15:02,647]  INFO {cps:89} Starting Calibre Web...
[2019-12-31 13:16:09,747]  INFO {cps:89} Starting Calibre Web...
[2019-12-31 13:21:49,693]  INFO {cps:89} Starting Calibre Web...
[2019-12-31 13:21:58,678]  INFO {cps:89} Starting Calibre Web...
[2019-12-31 13:21:58,858]  INFO {cps.server:140} Starting Gevent server on [::]:8083
[2019-12-31 13:25:36,180]  WARN {cps.admin:97} reconnecting to calibre database`

**Comment by cwilcoxc** [comment]
Looks like a calibrebd error - I'll close this down.

**Comment by OzzieIsaacs** [comment]
Okay, than we are in little trouble.

> DatabaseError: (sqlite3.DatabaseError) database disk image is malformed
The database is broken.

**Comment by OzzieIsaacs** [comment]
You are right. It‘s best to start over again

**Comment by cwilcoxc** [comment]
Cheers - I'll try adding a few books at a time, rather than 1500 in one go (it only managed 300 before apparently crashing...)

**Comment by OzzieIsaacs** [comment]
There are at least two restrictions in uploading many books. One is the upload file size limit of the server (200mb, I think) the other one is the connection timeout ( I don‘t know the exact value). It‘s better to add this amount of files via the desktop app, or via little pieces as you already realized.
But it should not crash the database, I will have a look at it.

**Comment by OzzieIsaacs** [comment]
I managed about 90-100 books in one go without a problem several times.

**Comment by cwilcoxc** [comment]
OK that's good to know. The calibre database is now crashing when I add 5-6 books, so I think the problem is a little deeper than connection timeouts. Error reads:
`calibre, version 4.7.0
ERROR: Unhandled exception: <b>CorruptError</b>:CorruptError: database disk image is malformed

calibre 4.7  embedded-python: True is64bit: True
Linux-4.15.0-72-generic-x86_64-with-debian-buster-sid Linux ('64bit', '')
('Linux', '4.15.0-72-generic', '#81-Ubuntu SMP Tue Nov 26 12:20:02 UTC 2019')
Python 2.7.16
Linux: ('debian', 'buster/sid', '')
Interface language: None
Traceback (most recent call last):
  File "site-packages/calibre/gui2/actions/choose_library.py", line 504, in restore_database
  File "site-packages/calibre/gui2/ui.py", line 718, in library_moved
  File "site-packages/calibre/db/legacy.py", line 82, in __init__
  File "site-packages/calibre/db/legacy.py", line 47, in create_backend
  File "site-packages/calibre/db/backend.py", line 401, in __init__
  File "site-packages/calibre/db/backend.py", line 1150, in user_version
  File "site-packages/calibre/db/backend.py", line 865, in conn
  File "site-packages/calibre/db/backend.py", line 294, in __init__
  File "site-packages/calibre/db/backend.py", line 338, in execute
  File "src/cursor.c", line 1019, in APSWCursor_execute.sqlite3_prepare
  File "src/statementcache.c", line 386, in sqlite3_prepare
CorruptError: CorruptError: database disk image is malformed
`

Fully appreciate your help! I know this is not calibre-web causing this issue...

**Comment by OzzieIsaacs** [comment]
From your error message I read you tried to add the books via calibre itself? Did you stop calibre-web during this task (for me this is working, and I don‘t play with calibre-web during the books adding)
Is the calibre you used for adding the one from the docker container, or is it installed ‚normally‘ on the computer?

**Comment by OzzieIsaacs** [comment]
Which docker container are you using, the technosoft one, or the linuxserver one?
I do not maintain the docker container, so if it‘s related to the docker container I can‘t help any further.

**Comment by cwilcoxc** [comment]
I'm using the technosoft2000 container - looking at what's going on, I think calibre-web is behaving perfectly well - it's calibre which is having issues with the corrupting database and causing calibre-web to produce errors. Thanks for your help though.
