### ISSUE TITLE
500 Internal Server Error on random books

### ISSUE THREAD

**Issue by InterCast** [janeczku/calibre-web#114]
I'm on Windows Server 2012R2, and newest commit. 
After updating to newest commit, from I get a status 500 on random pages / books. Others work just fine.
This is what happens:

```
[2017-02-16 20:45:14,815] ERROR in app: Exception on /book/4231 [GET]
Traceback (most recent call last):
  File "C:\CalibreWeb\vendor\flask\app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\CalibreWeb\vendor\flask\app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\CalibreWeb\vendor\flask\app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\CalibreWeb\vendor\flask\app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\CalibreWeb\vendor\flask\app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\CalibreWeb\vendor\flask_login.py", line 792, in decorated_view
    return func(*args, **kwargs)
  File "C:\CalibreWeb\cps\web.py", line 979, in show_book
    title=entries.title, books_shelfs=book_in_shelfs)
  File "C:\CalibreWeb\cps\web.py", line 421, in render_title_template
    return render_template(instance=config.config_calibre_web_title, *args, **kw
args)
  File "C:\CalibreWeb\vendor\flask\templating.py", line 134, in render_template
    context, ctx.app)
  File "C:\CalibreWeb\vendor\flask\templating.py", line 116, in _render
    rv = template.render(context)
  File "C:\CalibreWeb\vendor\jinja2\environment.py", line 989, in render
    return self.environment.handle_exception(exc_info, True)
  File "C:\CalibreWeb\vendor\jinja2\environment.py", line 754, in handle_excepti
on
    reraise(exc_type, exc_value, tb)
  File "C:\CalibreWeb\cps\templates\detail.html", line 1, in top-level template
code
    {% extends "layout.html" %}
  File "C:\CalibreWeb\cps\templates\layout.html", line 162, in top-level templat
e code
    {% block body %}{% endblock %}
  File "C:\CalibreWeb\cps\templates\detail.html", line 74, in block "body"
    <p>{{_('Publishing date')}}: {{entry.pubdate|formatdate}} </p>
  File "C:\CalibreWeb\cps\web.py", line 286, in formatdate
    formatdate = datetime.datetime.strptime(conformed_timestamp[:-5], "%Y%m%d %H
%M%S")
  File "C:\Python27\lib\_strptime.py", line 328, in _strptime
    data_string[found.end():])
ValueError: unconverted data remains: .272000
ERROR:cps.web:Exception on /book/4231 [GET]
Traceback (most recent call last):
  File "C:\CalibreWeb\vendor\flask\app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\CalibreWeb\vendor\flask\app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\CalibreWeb\vendor\flask\app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\CalibreWeb\vendor\flask\app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\CalibreWeb\vendor\flask\app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\CalibreWeb\vendor\flask_login.py", line 792, in decorated_view
    return func(*args, **kwargs)
  File "C:\CalibreWeb\cps\web.py", line 979, in show_book
    title=entries.title, books_shelfs=book_in_shelfs)
  File "C:\CalibreWeb\cps\web.py", line 421, in render_title_template
    return render_template(instance=config.config_calibre_web_title, *args, **kw
args)
  File "C:\CalibreWeb\vendor\flask\templating.py", line 134, in render_template
    context, ctx.app)
  File "C:\CalibreWeb\vendor\flask\templating.py", line 116, in _render
    rv = template.render(context)
  File "C:\CalibreWeb\vendor\jinja2\environment.py", line 989, in render
    return self.environment.handle_exception(exc_info, True)
  File "C:\CalibreWeb\vendor\jinja2\environment.py", line 754, in handle_excepti
on
    reraise(exc_type, exc_value, tb)
  File "C:\CalibreWeb\cps\templates\detail.html", line 1, in top-level template
code
    {% extends "layout.html" %}
  File "C:\CalibreWeb\cps\templates\layout.html", line 162, in top-level templat
e code
    {% block body %}{% endblock %}
  File "C:\CalibreWeb\cps\templates\detail.html", line 74, in block "body"
    <p>{{_('Publishing date')}}: {{entry.pubdate|formatdate}} </p>
  File "C:\CalibreWeb\cps\web.py", line 286, in formatdate
    formatdate = datetime.datetime.strptime(conformed_timestamp[:-5], "%Y%m%d %H
%M%S")
  File "C:\Python27\lib\_strptime.py", line 328, in _strptime
    data_string[found.end():])
ValueError: unconverted data remains: .272000
```

**Comment by OzzieIsaacs** [comment]
Should work now (your timestamps for publishing date had millisonds which none of the entries in my database had, so the code was not prepared for that)

**Comment by InterCast** [comment]
Thanks for the quick response. Works like a charm!
