### ISSUE TITLE
binascii.Error: Incorrect padding when using auth proxy such as Keycloak

### ISSUE THREAD

**Issue by cclloyd** [janeczku/calibre-web#1140]
I'm uisng Calibre-Web behind Keycloak gatekeeper, as I do with most of my services.  When I try to visit the site, it redirects to keycloak then back to calibre-web.  But it throws a 500 error, something about not being able to decode the headers. 

    ::ffff:127.0.0.1 - - [2020-01-13 00:35:06] "GET / HTTP/1.1" 500 411 0.022512
    ::ffff:127.0.0.1 - - [2020-01-13 00:35:06] "GET /favicon.ico HTTP/1.1" 200 61965 0.013293
    [2020-01-13 00:36:20,018] ERROR in app: Exception on / [GET]
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2446, in wsgi_app
        response = self.full_dispatch_request()
      File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1951, in full_dispatch_request
        rv = self.handle_user_exception(e)
      File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1820, in handle_user_exception
        reraise(exc_type, exc_value, tb)
      File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 39, in reraise
        raise value
      File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1949, in full_dispatch_request
        rv = self.dispatch_request()
      File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1935, in dispatch_request
        return self.view_functions[rule.endpoint](**req.view_args)
      File "/app/calibre-web/cps/web.py", line 349, in decorated_view
        return login_required(func)(*args, **kwargs)
      File "/usr/local/lib/python3.6/dist-packages/flask_login/utils.py", line 259, in decorated_view
        elif not current_user.is_authenticated:
      File "/usr/local/lib/python3.6/dist-packages/werkzeug/local.py", line 348, in __getattr__
        return getattr(self._get_current_object(), name)
      File "/usr/local/lib/python3.6/dist-packages/werkzeug/local.py", line 307, in _get_current_object
        return self.__local()
      File "/usr/local/lib/python3.6/dist-packages/flask_login/utils.py", line 26, in <lambda>
        current_user = LocalProxy(lambda: _get_user())
      File "/usr/local/lib/python3.6/dist-packages/flask_login/utils.py", line 335, in _get_user
        current_app.login_manager._load_user()
      File "/usr/local/lib/python3.6/dist-packages/flask_login/login_manager.py", line 357, in _load_user
        return self._load_from_header(request.headers[header_name])
      File "/usr/local/lib/python3.6/dist-packages/flask_login/login_manager.py", line 401, in _load_from_header
        user = self.header_callback(header)
      File "/app/calibre-web/cps/web.py", line 255, in load_user_from_header
        header_val = base64.b64decode(header_val).decode('utf-8')
      File "/usr/lib/python3.6/base64.py", line 87, in b64decode
        return binascii.a2b_base64(s)
    binascii.Error: Incorrect padding

The problem is probably related to the cookie passed with the headers.  Other services like radarr/sonarr don't have an issue processing it, but I get the above error with calibre-web when this example token is passed.

 
 
 
 eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJHLWh3TnBtUElTR3F2Q09EeGpkZWdxTE9PbHVvWlBtRU5pajNKTjNxc05zIn0.eyJqdGkiOiJjMjFkYzc2MS00ZTNiLTRlODgtYjBkNC0xZDJiMTBlMWFmZGIiLCJleHAiOjE1Nzg5MDI0MzAsIm5iZiI6MCwiaWF0IjoxNTc4ODk1MjMwLCJpc3MiOiJodHRwczovL2tleWNsb2FrLndoaXRlZmFtaWx5c2VydmVyLmNvbS9hdXRoL3JlYWxtcy9tYXN0ZXIiLCJhdWQiOlsiY2FsaWJyZS13ZWIiLCJhY2NvdW50Il0sInN1YiI6ImM3NWUzZTZjLWRiMDktNDQ0My1iZTI0LTUxYTNhNmM5ZDUwMCIsInR5cCI6IkJlYXJlciIsImF6cCI6ImNhbGlicmUtd2ViIiwiYXV0aF90aW1lIjoxNTc4ODk1MjA1LCJzZXNzaW9uX3N0YXRlIjoiZTEzMjY2YmYtM2I3Ny00MDJlLWJmZDQtMDYzNDA0MjliYTBiIiwiYWNyIjoiMCIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJMREFQIFVzZXIiLCJvZmZsaW5lX2FjY2VzcyIsInVtYV9hdXRob3JpemF0aW9uIiwiTWVkaWEgVXNlciJdfSwicmVzb3VyY2VfYWNjZXNzIjp7ImFjY291bnQiOnsicm9sZXMiOlsibWFuYWdlLWFjY291bnQiLCJtYW5hZ2UtYWNjb3VudC1saW5rcyIsInZpZXctcHJvZmlsZSJdfX0sInNjb3BlIjoib3BlbmlkIHByb2ZpbGUgZW1haWwgY2FsaWJyZS13ZWIiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsIm5hbWUiOiJUZXN0IFRlc3RlcnNvbiIsInByZWZlcnJlZF91c2VybmFtZSI6InRlc3QiLCJnaXZlbl9uYW1lIjoiVGVzdCIsImZhbWlseV9uYW1lIjoiVGVzdGVyc29uIiwiZW1haWwiOiJ0ZXN0QHdoaXRlZmFtaWx5c2VydmVyLmNvbSJ9.OhMWScgnSBkhQ0IThtERBbvGyxfHGK6jPdciLzyHWDqsdd30_-bE9Q9fGNJwn6qv7sbd8Q8YOxPcgOnAl8DXZfTKrvGHEYgOMvAYCZxhFfcpl1isIfeQTf4ayBK1dyTxfB0J1H8OcaRh1a4Oum9crFltDhE0WZtWsM2ZiP2jMyyDfcBz_bOh0db0nUHI0cC-E__Ll6o29WZRhExvMn9S_prbyVZ69dYv9puQjxjhpmbKOIXkGQJ3lVWCp39BHMNtJYx49f1seoDPs-MwlQ8x5PtNjuJoU5graDfg4w44729szgvX6-JRIcAt9rKi8xkPKfIWVvIKFYRMKmJaYxOu3g

Plugging it into base64 decoding says it has invalid characters, but I'm not sure which character.  However, since other services don't have an issue with it, I'm guessing it's something specifically with the base64 decoding process.

**Comment by OzzieIsaacs** [comment]
You are using an "old version", the proxy auth is not included there, and also not the latest fixes for handling encoding problem in the header.
Please update to the newest commit.

**Comment by OzzieIsaacs** [comment]
If you having further questions regarding this request, please feel free to reopen the issue again
