### ISSUE TITLE
doesn't run (wand error?) 

### ISSUE THREAD

**Issue by xinomilo** [janeczku/calibre-web#116]
tried to run it for the first time. forked repo and run cps.py.  output : 
$ python cps.py         
Traceback (most recent call last):
  File "cps.py", line 12, in <module>
    from cps import web
  File "/opt/calibre-web/cps/web.py", line 47, in <module>
    from wand.image import Image
  File "/opt/calibre-web/vendor/wand/image.py", line 21, in <module>
    from .color import Color
  File "/opt/calibre-web/vendor/wand/color.py", line 12, in <module>
    from .version import QUANTUM_DEPTH
  File "/opt/calibre-web/vendor/wand/version.py", line 110, in <module>
    *map(int, MAGICK_RELEASE_DATE_STRING.split('-')))
TypeError: Required argument 'month' (pos 2) not found

maybe it's related to this bug https://github.com/dahlia/wand/issues/310  ? 

thx,

**Comment by OzzieIsaacs** [comment]
It's working for me, but it seems to be the issue descibed from wand. I updated wand to 0.4.4 (the pull request is integrated there). Please try the newest commit.

**Comment by xinomilo** [comment]
thanks, works as expected now, no errors.
