### ISSUE TITLE
Error 500

### ISSUE THREAD

**Issue by Timo1102** [janeczku/calibre-web#117]
Hi, 
when i try to download a epub file, i got this error message. All other things works fine. Have you an idea where the problem is or made I a mistake? 

cps.web:Exception on /download/243/epub [GET]
Traceback (most recent call last):
  File "/root/calibre-web/vendor/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/root/calibre-web/vendor/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/root/calibre-web/vendor/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/root/calibre-web/vendor/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/root/calibre-web/vendor/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/root/calibre-web/vendor/flask_login.py", line 792, in decorated_view
    return func(*args, **kwargs)
  File "/root/calibre-web/cps/web.py", line 322, in inner
    return f(*args, **kwargs)
  File "/root/calibre-web/cps/web.py", line 1240, in get_download_link
    file_name = helper.get_valid_filename(file_name)
  File "/root/calibre-web/cps/helper.py", line 225, in get_valid_filename
    value=value.replace('§','SS')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 0: ordinal not in range(128)
ERROR:tornado.access:500 GET /download/243/epub (192.168.0.14) 136.74ms

**Comment by OzzieIsaacs** [comment]
Should work now

**Comment by Timo1102** [comment]
yes it works now, thanks
