### ISSUE TITLE
Can not start cps.py on newest release

### ISSUE THREAD

**Issue by Clearmist** [janeczku/calibre-web#1170]
Similar to #347 

Release [0.6.5](https://github.com/janeczku/calibre-web/releases/tag/0.6.5) and current master.

Dependencies are installed.

`python cps.py`

### Python 3.7.5
`cat calibre-web.log`

```
  File "/home/username/calibre-web/vendor/flask_login/login_manager.py", line 412, in _load_from_request
    user = self.request_callback(request)
  File "/home/username/calibre-web/cps/web.py", line 129, in load_user_from_request
    user = load_user_from_auth_header(auth_header)
  File "/home/username/calibre-web/cps/web.py", line 150, in load_user_from_auth_header
    header_val = base64.b64decode(header_val).decode('utf-8')
```

### Python 2.7.17
```
  File "cps.py", line 34, in <module>
    from cps import create_app
  File "/home/username/calibre-web/cps/__init__.py", line 38, in <module>
    from .server import WebServer
  File "/home/username/calibre-web/cps/server.py", line 33, in <module>
    from tornado.wsgi import WSGIContainer
  File "/home/username/calibre-web/vendor/tornado/wsgi.py", line 51
    def to_wsgi_str(s: bytes) -> str:
```

This occurs in Firefox. Chrome loads correctly. Perhaps your script is trying to parse the Firefox headers using UTF8 when the headers are not UTF8. Firefox headers:
```
{"Request headers (640 B)":{"RAW_HEADERS_ID":"GET /config HTTP/1.1\r\nHost: REMOVED\r\nUser-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64; rv:68.0) Gecko/20100101 Firefox/68.0\r\nAccept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8\r\nAccept-Language: en-US,en;q=0.5\r\nAccept-Encoding: gzip, deflate, br\r\nAuthorization: Digest username=\"REMOVED\", realm=\"calibre\", nonce=\"REMOVED:REMOVED\", uri=\"/config\", algorithm=MD5, response=\"REMOVED\", qop=auth, nc=000000c9, cnonce=\"REMOVED\"\r\nConnection: keep-alive\r\nUpgrade-Insecure-Requests: 1\r\nCache-Control: max-age=0\r\n\r\n"}}
```

**Comment by OzzieIsaacs** [comment]
Python 2.7: Tornado stopped working on python 2.7 with version 5.0.2 (?), i guess you are having a newer version installed. Python 2.7 is End of life since end of 2019, so our goal should be get it running on python3.
I‘m using firefox reguarly, so it should work.
The error message should continue, there should be at least one more line str has no method decoding, or can‘t decode text blabla at position xy. Could you please check this?

**Comment by OzzieIsaacs** [comment]
The problem is: the header contains an authorization header from calibre. I guess you used calibre with firefox before and didn‘t do this with chrome before. Normally the code shouldn‘t get to the line the code complains about. But anyhow it should work. if I get the complete error code I can fix it quickly.

**Comment by Clearmist** [comment]
@OzzieIsaacs Thank you for a quick reply :) This is the full traceback I found within calibre-web.log. On a fresh installation I'm redirected to /config to complete set up. That is where this error occurs.

You are correct that I had used calibre-server in this same browser.

```
[2020-01-29 18:57:24,909] ERROR {cps:1891} Exception on /config [GET]
Traceback (most recent call last):
  File "/home/username/calibre-web/vendor/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/username/calibre-web/vendor/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/username/calibre-web/vendor/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/username/calibre-web/vendor/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/username/calibre-web/vendor/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/username/calibre-web/vendor/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/username/calibre-web/cps/web.py", line 207, in inner
    return f(*args, **kwargs)
  File "/home/username/calibre-web/cps/admin.py", line 254, in basic_configuration
    logout_user()
  File "/home/username/calibre-web/vendor/flask_login/utils.py", line 190, in logout_user
    user = _get_user()
  File "/home/username/calibre-web/vendor/flask_login/utils.py", line 335, in _get_user
    current_app.login_manager._load_user()
  File "/home/username/calibre-web/vendor/flask_login/login_manager.py", line 355, in _load_user
    return self._load_from_request(request)
  File "/home/username/calibre-web/vendor/flask_login/login_manager.py", line 412, in _load_from_request
	user = self.request_callback(request)
  File "/home/username/calibre-web/cps/web.py", line 129, in load_user_from_request
    user = load_user_from_auth_header(auth_header)
  File "/home/username/calibre-web/cps/web.py", line 150, in load_user_from_auth_header
    header_val = base64.b64decode(header_val).decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb2 in position 3: invalid start byte
```

Your README still references Python 2. The program is working fine with Python 3; like you said it should.
> python 3.x+, (Python 2.7+)
