### ISSUE TITLE
Error when executing python cps.py module babel

### ISSUE THREAD

**Issue by ge2sasag** [janeczku/calibre-web#1195]
Hi,

I couldn't find a similar issue or solution. I followed all the steps correctly but when I run python cps.py I get this:

```
C:\Calibre-web>python cps.py
Traceback (most recent call last):
  File "cps.py", line 34, in <module>
    from cps import create_app
  File "C:\Calibre-web\cps\__init__.py", line 28, in <module>
    from babel import Locale as LC
ModuleNotFoundError: No module named 'babel'
```

Any suggestions?

Thanks!
G

**Comment by OzzieIsaacs** [comment]
It looks like the installation didn't work completly. "Babel" is missing. Could you please try to rerun the pip[3] command and look for errors in the output. I don't know your installation environment, please also make sure that you use the "right" pip command (pip for python2 and pip3 form python3)

**Comment by ge2sasag** [comment]
The active python version is 3.8. Using pip3 for requirements.txt worked now but for optional-requirements.txt there is a problem with gevent (I'm not using --target because it reports errors):

```
C:\Calibre-web>pip3 install -r optional-requirements.txt
Collecting google-api-python-client==1.7.11
  Downloading google-api-python-client-1.7.11.tar.gz (142 kB)
     |████████████████████████████████| 142 kB 1.3 MB/s
Collecting gevent>=1.2.1
  Downloading gevent-1.4.0.tar.gz (5.2 MB)
     |████████████████████████████████| 5.2 MB 6.4 MB/s
    ERROR: Command errored out with exit status 1:
     command: 'c:\python38\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\ge2sa\\AppData\\Local\\Temp\\pip-install-8rfedjm5\\gevent\\setup.py'"'"'; __file__='"'"'C:\\Users\\ge2sa\\AppData\\Local\\Temp\\pip-install-8rfedjm5\\gevent\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\ge2sa\AppData\Local\Temp\pip-install-8rfedjm5\gevent\pip-egg-info'
         cwd: C:\Users\ge2sa\AppData\Local\Temp\pip-install-8rfedjm5\gevent\
    Complete output (114 lines):
    b'N\x00o\x00 \x00s\x00e\x00 \x00e\x00s\x00p\x00e\x00r\x00a\x00b\x00a\x00 \x00C\x00:\x00\\\x00W\x00i\x00n\x00d\x00o\x00w\x00s\x00\\\x00S\x00y\x00s\x00t\x00e\x00m\x003\x002\x00 \x00e\x00n\x00 \x00e\x00s\x00t\x00e\x00 \x00m\x00o\x00m\x00e\x00n\x00t\x00o\x00.\x00\r\x00\n\x00'
    Traceback (most recent call last):
      File "c:\python38\lib\site-packages\setuptools\msvc.py", line 489, in _find_latest_available_vc_ver
        return self.find_available_vc_vers()[-1]
    IndexError: list index out of range

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "c:\python38\lib\site-packages\setuptools\sandbox.py", line 154, in save_modules
        yield saved
      File "c:\python38\lib\site-packages\setuptools\sandbox.py", line 195, in setup_context
        yield
      File "c:\python38\lib\site-packages\setuptools\sandbox.py", line 250, in run_setup
        _execfile(setup_script, ns)
      File "c:\python38\lib\site-packages\setuptools\sandbox.py", line 45, in _execfile
        exec(code, globals, locals)
      File "C:\Users\ge2sa\AppData\Local\Temp\easy_install-poqoq0w7\cffi-1.14.0\setup.py", line 127, in <module>
        HUB_PRIMITIVES = Extension(name="gevent.__hub_primitives",
      File "C:\Users\ge2sa\AppData\Local\Temp\easy_install-poqoq0w7\cffi-1.14.0\setup.py", line 105, in uses_msvc
        include_dirs=include_dirs)
      File "c:\python38\lib\distutils\command\config.py", line 225, in try_compile
        self._compile(body, headers, include_dirs, lang)
      File "c:\python38\lib\distutils\command\config.py", line 132, in _compile
        self.compiler.compile([src], include_dirs=include_dirs)
      File "c:\python38\lib\distutils\_msvccompiler.py", line 360, in compile
        self.initialize()
      File "c:\python38\lib\distutils\_msvccompiler.py", line 253, in initialize
        vc_env = _get_vc_env(plat_spec)
      File "c:\python38\lib\site-packages\setuptools\msvc.py", line 185, in msvc14_get_vc_env
        return EnvironmentInfo(plat_spec, vc_min_ver=14.0).return_env()
      File "c:\python38\lib\site-packages\setuptools\msvc.py", line 843, in __init__
        self.si = SystemInfo(self.ri, vc_ver)
      File "c:\python38\lib\site-packages\setuptools\msvc.py", line 485, in __init__
        self.vc_ver = vc_ver or self._find_latest_available_vc_ver()
      File "c:\python38\lib\site-packages\setuptools\msvc.py", line 492, in _find_latest_available_vc_ver
        raise distutils.errors.DistutilsPlatformError(err)
    distutils.errors.DistutilsPlatformError: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\ge2sa\AppData\Local\Temp\pip-install-8rfedjm5\gevent\setup.py", line 427, in <module>
        run_setup(EXT_MODULES, run_make=_BUILDING)
      File "C:\Users\ge2sa\AppData\Local\Temp\pip-install-8rfedjm5\gevent\setup.py", line 328, in run_setup
        setup(
      File "c:\python38\lib\site-packages\setuptools\__init__.py", line 144, in setup
        _install_setup_requires(attrs)
      File "c:\python38\lib\site-packages\setuptools\__init__.py", line 139, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "c:\python38\lib\site-packages\setuptools\dist.py", line 716, in fetch_build_eggs
        resolved_dists = pkg_resources.working_set.resolve(
      File "c:\python38\lib\site-packages\pkg_resources\__init__.py", line 780, in resolve
        dist = best[req.key] = env.best_match(
      File "c:\python38\lib\site-packages\pkg_resources\__init__.py", line 1065, in best_match
        return self.obtain(req, installer)
      File "c:\python38\lib\site-packages\pkg_resources\__init__.py", line 1077, in obtain
        return installer(requirement)
      File "c:\python38\lib\site-packages\setuptools\dist.py", line 786, in fetch_build_egg
        return cmd.easy_install(req)
      File "c:\python38\lib\site-packages\setuptools\command\easy_install.py", line 679, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "c:\python38\lib\site-packages\setuptools\command\easy_install.py", line 705, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "c:\python38\lib\site-packages\setuptools\command\easy_install.py", line 890, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "c:\python38\lib\site-packages\setuptools\command\easy_install.py", line 1158, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "c:\python38\lib\site-packages\setuptools\command\easy_install.py", line 1144, in run_setup
        run_setup(setup_script, args)
      File "c:\python38\lib\site-packages\setuptools\sandbox.py", line 253, in run_setup
        raise
      File "c:\python38\lib\contextlib.py", line 131, in __exit__
        self.gen.throw(type, value, traceback)
      File "c:\python38\lib\site-packages\setuptools\sandbox.py", line 195, in setup_context
        yield
      File "c:\python38\lib\contextlib.py", line 131, in __exit__
        self.gen.throw(type, value, traceback)
      File "c:\python38\lib\site-packages\setuptools\sandbox.py", line 166, in save_modules
        saved_exc.resume()
      File "c:\python38\lib\site-packages\setuptools\sandbox.py", line 141, in resume
        six.reraise(type, exc, self._tb)
      File "c:\python38\lib\site-packages\setuptools\_vendor\six.py", line 685, in reraise
        raise value.with_traceback(tb)
      File "c:\python38\lib\site-packages\setuptools\sandbox.py", line 154, in save_modules
        yield saved
      File "c:\python38\lib\site-packages\setuptools\sandbox.py", line 195, in setup_context
        yield
      File "c:\python38\lib\site-packages\setuptools\sandbox.py", line 250, in run_setup
        _execfile(setup_script, ns)
      File "c:\python38\lib\site-packages\setuptools\sandbox.py", line 45, in _execfile
        exec(code, globals, locals)
      File "C:\Users\ge2sa\AppData\Local\Temp\easy_install-poqoq0w7\cffi-1.14.0\setup.py", line 127, in <module>
        HUB_PRIMITIVES = Extension(name="gevent.__hub_primitives",
      File "C:\Users\ge2sa\AppData\Local\Temp\easy_install-poqoq0w7\cffi-1.14.0\setup.py", line 105, in uses_msvc
        include_dirs=include_dirs)
      File "c:\python38\lib\distutils\command\config.py", line 225, in try_compile
        self._compile(body, headers, include_dirs, lang)
      File "c:\python38\lib\distutils\command\config.py", line 132, in _compile
        self.compiler.compile([src], include_dirs=include_dirs)
      File "c:\python38\lib\distutils\_msvccompiler.py", line 360, in compile
        self.initialize()
      File "c:\python38\lib\distutils\_msvccompiler.py", line 253, in initialize
        vc_env = _get_vc_env(plat_spec)
      File "c:\python38\lib\site-packages\setuptools\msvc.py", line 185, in msvc14_get_vc_env
        return EnvironmentInfo(plat_spec, vc_min_ver=14.0).return_env()
      File "c:\python38\lib\site-packages\setuptools\msvc.py", line 843, in __init__
        self.si = SystemInfo(self.ri, vc_ver)
      File "c:\python38\lib\site-packages\setuptools\msvc.py", line 485, in __init__
        self.vc_ver = vc_ver or self._find_latest_available_vc_ver()
      File "c:\python38\lib\site-packages\setuptools\msvc.py", line 492, in _find_latest_available_vc_ver
        raise distutils.errors.DistutilsPlatformError(err)
    distutils.errors.DistutilsPlatformError: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by ge2sasag** [comment]
I think it might be something related to python version? the active one is 3.8 but if I check _cffi_backend, it is already satisfied in 3.7

**Comment by ge2sasag** [comment]
I managed to solve the version issue and the optional-requirements file worked without errors. But now again, the cps.py is reporting the same babel error, which was actually fixed before installing the optional-requirements file.... 

Babel is supposed to be there:

```
C:\Calibre-web>pip3 install -r requirements.txt
Requirement already satisfied: Babel>=1.3 in c:\users\ge2sa\appdata\local\packages\pythonsoftwarefoundation.python.3.7_qbz5n2kfra8p0\localcache\local-packages\python37\site-packages (from -r requirements.txt (line 1)) (2.8.0)
Requirement already satisfied: Flask-Babel>=0.11.1 in c:\users\ge2sa\appdata\local\packages\pythonsoftwarefoundation.python.3.7_qbz5n2kfra8p0\localcache\local-packages\python37\site-packages (from -r requirements.txt (line 2)) (1.0.0)
```

**Comment by ge2sasag** [comment]
Ok! it's working if I use `python3 cps.py`

Solved

**Comment by OzzieIsaacs** [comment]
I remember gevent was somehow tricky to install on windows. 
It's just an alternative (instead of tornado from requirements.txt) and recommended for windows, because of performance:
![grafik](https://user-images.githubusercontent.com/6438895/74519539-30832f80-4f16-11ea-93d4-91b5a4b5ba6a.png)
But for me it was never a problem. 
If you delete the gevent line (and also the complete first block) in optional-requirements.txt you can benefit from the other optional features (each block's header tell's you what is it for, if you don't need it, you can delete it) .
