### ISSUE TITLE
Internal Server Error on missing HTTP_REFERER in request upon sending to kindle

### ISSUE THREAD

**Issue by crazybadger** [janeczku/calibre-web#1199]
I'm getting this error message when sending a book from Calibre-web to my Kindle e-mail address, but the books are sending fine.

```
Internal Server Error
500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
Traceback (most recent call last):
File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2446, in wsgi_app
response = self.full_dispatch_request()
File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1951, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1820, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 39, in reraise
raise value
File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1949, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1935, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/usr/local/lib/python3.6/dist-packages/flask_login/utils.py", line 261, in decorated_view
return func(*args, **kwargs)
File "/app/calibre-web/cps/web.py", line 217, in inner
return f(*args, **kwargs)
File "/app/calibre-web/cps/web.py", line 1071, in send_to_kindle
return redirect(request.environ["HTTP_REFERER"])
KeyError: 'HTTP_REFERER'
```

Running Calibre-web in a Docker (19.03.5) container in a ubuntu (18.4.3) VM on FreeNAS 11.2-U7.

Really loving the app having come from calibre-server (3.8) running in a FreeBSD jail 👍

**Comment by OzzieIsaacs** [comment]
Yes, it's indeed a bug, if the referrer is missing (the last page you came from) it throws this error. I fixed it. Depending on which docker you are using, you have to wait for the next release to come, or you can update it with the self updating feature (maybe, I don't know exactly the docker features)

**Comment by crazybadger** [comment]
Thanks for the quick response!  I'm running 0.6.5 using this https://hub.docker.com/r/linuxserver/calibre-web docker image, so will wait for an update.  As I say, not a problem as it still sends the books, just would be nice to not see the error :-)
