### ISSUE TITLE
Layout messed up + about section not loading

### ISSUE THREAD

**Issue by simkin** [janeczku/calibre-web#120]
After pulling the latest build it seems the layout got messed up (single column layout?):
![layout](http://image.prntscr.com/image/36772ae7ca344a9195a36e7c0c1cdfaf.png)
Also, the about link is resulting in an error:
```
[2017-02-21 11:06:45,796] {/opt/calibre-web1/cps/web.py:116} INFO - Starting Calibre Web...
[2017-02-21 11:08:43,980] {/opt/calibre-web/vendor/flask/app.py:1587} ERROR - Exception on /stats [GET]
Traceback (most recent call last):
  File "/opt/calibre-web/vendor/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/calibre-web/vendor/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/calibre-web/vendor/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/calibre-web/vendor/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/calibre-web/vendor/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/calibre-web/vendor/flask_login.py", line 792, in decorated_view
    return func(*args, **kwargs)
  File "/opt/calibre-web1/cps/web.py", line 956, in stats

  File "/opt/calibre-web/vendor/flask/templating.py", line 134, in render_template
    context, ctx.app)
  File "/opt/calibre-web/vendor/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/opt/calibre-web/vendor/jinja2/environment.py", line 989, in render
    return self.environment.handle_exception(exc_info, True)
  File "/opt/calibre-web/vendor/jinja2/environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/calibre-web1/cps/templates/stats.html", line 1, in top-level template code
    {% extends "layout.html" %}
  File "/opt/calibre-web1/cps/templates/layout.html", line 159, in top-level template code
    </ul>
  File "/opt/calibre-web1/cps/templates/stats.html", line 15, in block "body"
    <td>{{versions['PythonVersion']}}</td>
  File "/opt/calibre-web/vendor/jinja2/environment.py", line 389, in getitem
    return obj[argument]
UndefinedError: 'versions' is undefined
```

**Comment by OzzieIsaacs** [comment]
For the layout it seems that you are missing the bootstrap.min.css file (maybe file permission issue). The file was recently moved to : .../cps/static/css/libs/bootstrap.min.css. Could you please check if the file is there and accesible? 
Are you using a reverse proxy?
The versions undefined I can not check now, but in the code it seems everything fine, are you sure that replacing all files (web.py file in this case) did work?

**Comment by simkin** [comment]
I rebooted my machine and it is simply no longer starting up :/ An older version of calibre-web (0.10.6 2014-2016) still works. Also a fresh install is not booting (no error, no lines in --debug mode)

Did you add a specific python dependency maybe?

**Comment by OzzieIsaacs** [comment]
I updated "wand" to 0.4.4 and added "unidecode" as dependency, but if the last one isn't available it shouldn't throw an error. 
What do you mean with --debug mode? 
The code changed recently regarding debug/development mode, to enable the development mode you should change the line 

DEVELOPMENT = False

in file ../cps/ub.py

DEVELOPMENT = True

You are aware that in newer versions the config.ini file is no longer valid and the configuration is done via web-interface on standard port 8083? 
Maybe there is a migration problem of the database. 
Could you please delete the app.db (or rename it to have a backup)? And start it again?

**Comment by simkin** [comment]
I was not aware about the drop of config.ini, sorry for that! Tunneled to 8083 and see the configs page.
