### ISSUE TITLE
Traceback when selecting book after selecting author

### ISSUE THREAD

**Issue by Kendrik01** [janeczku/calibre-web#1203]
I'm just getting calibre-web set up and I've run into the following issue:

**System Info**
Ubuntu 18.04.4 LTS
Python 3.6.9

1) Logged in as admin user
2) Select Authors on side menu
3) Select an Author from list
4) Select a book from the list of books
5) Receive the following traceback:

Traceback (most recent call last):
File "/opt/calibre-web/vendor/flask/app.py", line 2446, in wsgi_app
response = self.full_dispatch_request()
File "/opt/calibre-web/vendor/flask/app.py", line 1951, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/opt/calibre-web/vendor/flask/app.py", line 1820, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/opt/calibre-web/vendor/flask/_compat.py", line 39, in reraise
raise value
File "/opt/calibre-web/vendor/flask/app.py", line 1949, in full_dispatch_request
rv = self.dispatch_request()
File "/opt/calibre-web/vendor/flask/app.py", line 1935, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/opt/calibre-web/cps/web.py", line 166, in decorated_view
return login_required(func)(*args, **kwargs)
File "/opt/calibre-web/vendor/flask_login/utils.py", line 272, in decorated_view
return func(*args, **kwargs)
File "/opt/calibre-web/cps/web.py", line 1471, in show_book
is_xhr=request.is_xhr, title=entries.title, books_shelfs=book_in_shelfs,
File "/opt/calibre-web/vendor/werkzeug/local.py", line 347, in __getattr__
return getattr(self._get_current_object(), name)
AttributeError: 'Request' object has no attribute 'is_xhr'

It requested an issue be submitted, so here I am.

**Comment by OzzieIsaacs** [comment]
Please check #1181
