### ISSUE TITLE
python3 crash with new install while trying to delete a book

### ISSUE THREAD

**Issue by fire1ce** [janeczku/calibre-web#1244]
500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
Traceback (most recent call last):
File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2446, in wsgi_app
response = self.full_dispatch_request()
File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1951, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1820, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 39, in reraise
raise value
File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1949, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1935, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/app/calibre-web/cps/web.py", line 166, in decorated_view
return login_required(func)(*args, **kwargs)
File "/usr/local/lib/python3.6/dist-packages/flask_login/utils.py", line 272, in decorated_view
return func(*args, **kwargs)
File "/app/calibre-web/cps/web.py", line 506, in books_list
order)
File "/app/calibre-web/cps/helper.py", line 773, in fill_indexpage
len(db.session.query(database).filter(db_filter).filter(common_filters()).all()))
File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/query.py", line 3233, in all
return list(self)
File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/query.py", line 3389, in __iter__
return self._execute_and_instances(context)
File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/query.py", line 3411, in _execute_and_instances
querycontext, self._connection_from_session, close_with_result=True
File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/query.py", line 3426, in _get_bind_args
mapper=self._bind_mapper(), clause=querycontext.statement, **kw
File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/query.py", line 3404, in _connection_from_session
conn = self.session.connection(**kw)
File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/session.py", line 1133, in connection
execution_options=execution_options,
File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/session.py", line 1139, in _connection_for_bind
engine, execution_options
File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/session.py", line 408, in _connection_for_bind
self._assert_active()
File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/session.py", line 295, in _assert_active
code="7s2a",
sqlalchemy.exc.InvalidRequestError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: list.remove(x): x not in list (Background on this error at: http://sqlalche.me/e/7s2a)

**Comment by OzzieIsaacs** [comment]
I doublehecked it for me it's working.
The error message indicated the problem happened before and left the database in a intermediate state and now every request fails. 
Please try to reproduce the problem and tell me what exactly you did. 
And please tell me everything, out of the ordinary (operating system, hardware, location of database, ...)

**Comment by fire1ce** [comment]
Well, it took me a while to debug this. It looks like it was a broken DB. i've cleaned all the Database and stared over. For now it looks ok. 

closing
