### ISSUE TITLE
500 internal server error when click on ebook cover

### ISSUE THREAD

**Issue by siwinter** [janeczku/calibre-web#1270]
Congratulation on this great app. But unfortunatly it  doesn't work in my fresh yunohost installation.
I can upload ebooks. Download fails. When I click a book cover, there is either no response at all or a "500 internal server error page" is shown.
Since I don't know where to look, I would be happy to receive any information

My configuration:
Python 2.7.13
OS: yunohost based on Debian 9.11
version 0.96.0~ynh3 (app's webpage shows version 0.6.0

This is my log output:

[2020-03-24 23:37:29,701] ERROR in app: Exception on /book/2 [GET]
Traceback (most recent call last):
  File "/var/www/calibreweb/vendor/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/var/www/calibreweb/vendor/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/var/www/calibreweb/vendor/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/var/www/calibreweb/vendor/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/var/www/calibreweb/vendor/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/var/www/calibreweb/cps/web.py", line 344, in decorated_view
    return login_required(func)(*args, **kwargs)
  File "/var/www/calibreweb/vendor/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/var/www/calibreweb/cps/web.py", line 1592, in show_book
    return render_title_template('detail.html', entry=entries, cc=cc, is_xhr=request.is_xhr,
  File "/var/www/calibreweb/vendor/werkzeug/local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
AttributeError: 'Request' object has no attribute 'is_xhr'
127.0.0.1 - - [2020-03-24 23:37:29] "GET /calibre/book/2 HTTP/1.0" 500 459 0.091086

**Comment by OzzieIsaacs** [comment]
Pleas check the hints in #1181

**Comment by siwinter** [comment]
Thanks for the quick help.
Unfortunately the yunohost installation was frozen at version 0.6.0 due to an LDAP patch.
With your advice, I was able to backport your fix for using werkzeug 1.0.0

But there is still a similar issue when I click on "languages", "publishers" or similar button.
Do You also know a quick solution for that.

Here is the log outpug

Thank you and stay healthy

[2020-03-27 13:44:39,021] ERROR in app: Exception on /language [GET]
Traceback (most recent call last):
  File "/var/www/calibreweb/vendor/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/var/www/calibreweb/vendor/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/var/www/calibreweb/vendor/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/var/www/calibreweb/vendor/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/var/www/calibreweb/vendor/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/var/www/calibreweb/cps/web.py", line 344, in decorated_view
    return login_required(func)(*args, **kwargs)
  File "/var/www/calibreweb/vendor/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/var/www/calibreweb/cps/web.py", line 1454, in language_overview
    'books_languages_link.lang_code').all()
  File "/var/www/calibreweb/vendor/sqlalchemy/orm/query.py", line 3244, in all
    return list(self)
  File "/var/www/calibreweb/vendor/sqlalchemy/orm/query.py", line 3403, in __iter__
    return self._execute_and_instances(context)
  File "/var/www/calibreweb/vendor/sqlalchemy/orm/query.py", line 3428, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/var/www/calibreweb/vendor/sqlalchemy/engine/base.py", line 984, in execute
    return meth(self, multiparams, params)
  File "/var/www/calibreweb/vendor/sqlalchemy/sql/elements.py", line 293, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/var/www/calibreweb/vendor/sqlalchemy/engine/base.py", line 1094, in _execute_clauseelement
    else None,
  File "<string>", line 1, in <lambda>
  File "/var/www/calibreweb/vendor/sqlalchemy/sql/elements.py", line 468, in compile
    return self._compiler(dialect, bind=bind, **kw)
  File "/var/www/calibreweb/vendor/sqlalchemy/sql/elements.py", line 474, in _compiler
    return dialect.statement_compiler(dialect, self, **kw)
  File "/var/www/calibreweb/vendor/sqlalchemy/sql/compiler.py", line 590, in __init__
    Compiled.__init__(self, dialect, statement, **kwargs)
  File "/var/www/calibreweb/vendor/sqlalchemy/sql/compiler.py", line 319, in __init__
    self.string = self.process(self.statement, **compile_kwargs)
  File "/var/www/calibreweb/vendor/sqlalchemy/sql/compiler.py", line 350, in process
    return obj._compiler_dispatch(self, **kwargs)
  File "/var/www/calibreweb/vendor/sqlalchemy/sql/visitors.py", line 95, in _compiler_dispatch
    return meth(self, **kw)
  File "/var/www/calibreweb/vendor/sqlalchemy/sql/compiler.py", line 2162, in visit_select
    text, select, inner_columns, froms, byfrom, kwargs
  File "/var/www/calibreweb/vendor/sqlalchemy/sql/compiler.py", line 2266, in _compose_select_body
    text += self.group_by_clause(select, **kwargs)
  File "/var/www/calibreweb/vendor/sqlalchemy/sql/compiler.py", line 2324, in group_by_clause
    group_by = select._group_by_clause._compiler_dispatch(self, **kw)
  File "/var/www/calibreweb/vendor/sqlalchemy/sql/visitors.py", line 95, in _compiler_dispatch
    return meth(self, **kw)
  File "/var/www/calibreweb/vendor/sqlalchemy/sql/compiler.py", line 1003, in visit_clauselist
    c._compiler_dispatch(self, **kw) for c in clauselist.clauses
  File "/var/www/calibreweb/vendor/sqlalchemy/sql/compiler.py", line 1001, in <genexpr>
    s
  File "/var/www/calibreweb/vendor/sqlalchemy/sql/compiler.py", line 1003, in <genexpr>
    c._compiler_dispatch(self, **kw) for c in clauselist.clauses
  File "/var/www/calibreweb/vendor/sqlalchemy/sql/visitors.py", line 95, in _compiler_dispatch
    return meth(self, **kw)
  File "/var/www/calibreweb/vendor/sqlalchemy/sql/compiler.py", line 802, in visit_textual_label_reference
    err=ke,
  File "/var/www/calibreweb/vendor/sqlalchemy/sql/elements.py", line 4650, in _no_text_coercion
    replace_context=err,
  File "<string>", line 5, in raise_
CompileError: Can't resolve label reference for ORDER BY / GROUP BY / DISTINCT etc. Textual SQL expression 'books_languages_link.lang...' should be explicitly declared as text('books_languages_link.lang...')
127.0.0.1 - - [2020-03-27 13:44:39] "GET /calibre/language HTTP/1.0" 500 444 0.016807

**Comment by OzzieIsaacs** [comment]
I don't understand why you stick on such an old version. 
Looks like you still use 0.6.0. ?There is no need to use LDAP in calibre-web? 

But anyhow, your sqlalchemy version is too new. If you can't downgrade:
Add in web.py on top between the other imports
`from sqlalchemy.sql.expression import text`
change all `group_by('[..text...]')`
to `group_by(text('[..text...]'))`
Replace the [..text...] with the original text. Hope this is understandable.

**Comment by siwinter** [comment]
Thank you very much for the help.
The backport works for me and I made a pull request to make it available in the official yunohost installation script.
 
I set up my small raspberry pi server at home with yunohost.
It is simply very convenient for a beginner like me to administer many server applications with the same tools.
Unfortunately, the maintainer of the calibreweb package at [yunohost](https://github.com/YunoHost-Apps/calibreweb_ynh) has not yet had the time to update his package.
Otherwise I would of course much prefer to use the current version.

Maybe you could find a solution together with the Yunohost team that makes the LDAP patch unnecessary.
The work you all do at yunohost and calibreweb definitely deserves to be appreciated by many users.
Thank you for your commitment and stay healthy.
