### ISSUE TITLE
Unable to access EDIT BASIC CONFIGURATION calibre-web

### ISSUE THREAD

**Issue by yeraycito** [janeczku/calibre-web#1364]
![Screenshot_2020-05-08 BIBLIOTECA HTTP Error (Internal Server Error)](https://user-images.githubusercontent.com/65027248/81442030-20749800-9173-11ea-85ae-86c757dd002d.png)

**Comment by CHBMB** [comment]
@yeraycito I think you're going to need to post a lot more detail about how you've deployed this to get any help.  Post the steps you've followed so far to get to this error.

**Comment by OzzieIsaacs** [comment]
@CHBMB : Thank you for this post. 
I spend so much time in the past to ask users basic thinks about their problem, I'm tiered of doing this. I generated the contribution rules file and a basic issue form to get all the information. And users still just delete it and expect first class support

**Comment by gelsas** [comment]
Is there a GitHub bot which can detect if the issue form was filled out or not. And if not automatically post a message to the issue notifying them it can only be taken care of if they fill out the form correctly

**Comment by yeraycito** [comment]
Sorry. I don't do well with English. Clean installation of linuxserver-calibreweb. First access to the basic program configuration when starting the program without problems. Access to the configuration of the calibreweb interface without problems. When you want to access again to the basic configuration of calibreweb: ERROR

**Comment by yeraycito** [comment]
Installed in a nas by docker:
https://www.qnapclub.es/showthread.php?tid=3048

**Comment by OzzieIsaacs** [comment]
The relevant part of the error message is missing, please paste the complete error message (can also be found in the calibre-web.log file)

**Comment by yeraycito** [comment]
[2020-05-08 19:48:16,558]  INFO {cps:88} Starting Calibre Web...
[2020-05-08 19:48:16,658]  WARN {cps.config_sql:296} invalidating configuration
[2020-05-08 19:48:17,066]  INFO {cps.server:140} Starting Gevent server on [::]:8083
[2020-05-08 19:58:35,591] ERROR {cps:1892} Exception on /admin/config [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.6/dist-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/app/calibre-web/cps/web.py", line 213, in inner
    return f(*args, **kwargs)
  File "/app/calibre-web/cps/admin.py", line 143, in configuration
    return _configuration_result()
  File "/app/calibre-web/cps/admin.py", line 704, in _configuration_result
    title=_(u"Basic Configuration"), page="config")
  File "/app/calibre-web/cps/web.py", line 281, in render_title_template
    *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/usr/local/lib/python3.6/dist-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/usr/local/lib/python3.6/dist-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.6/dist-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/usr/local/lib/python3.6/dist-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/app/calibre-web/cps/templates/config_edit.html", line 1, in top-level template code
    {% extends "layout.html" %}
  File "/app/calibre-web/cps/templates/layout.html", line 153, in top-level template code
    {% block body %}{% endblock %}
  File "/app/calibre-web/cps/templates/config_edit.html", line 300, in block "body"
    <a href="{{prov['obtain_link']}}" target="_blank">{{_('Obtain %(provider)s OAuth Credential', provider=prov['provider_name'])}}</a>
  File "/usr/local/lib/python3.6/dist-packages/jinja2/ext.py", line 144, in _gettext_alias
    return __context.call(__context.resolve("gettext"), *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/jinja2/ext.py", line 156, in gettext
    return rv % variables
  File "/usr/local/lib/python3.6/dist-packages/markupsafe/__init__.py", line 102, in __mod__
    return self.__class__(text_type.__mod__(self, arg))
  File "/usr/local/lib/python3.6/dist-packages/markupsafe/__init__.py", line 301, in __getitem__
    return _MarkupEscapeHelper(self.obj[item], self.escape)
KeyError: 'proveedor'

**Comment by yeraycito** [comment]
[2020-05-09 13:59:42,533] ERROR {cps:1892} Exception on /admin/config [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.6/dist-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/app/calibre-web/cps/web.py", line 213, in inner
    return f(*args, **kwargs)
  File "/app/calibre-web/cps/admin.py", line 143, in configuration
    return _configuration_result()
  File "/app/calibre-web/cps/admin.py", line 704, in _configuration_result
    title=_(u"Basic Configuration"), page="config")
  File "/app/calibre-web/cps/web.py", line 281, in render_title_template
    *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/usr/local/lib/python3.6/dist-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/usr/local/lib/python3.6/dist-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.6/dist-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/usr/local/lib/python3.6/dist-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/app/calibre-web/cps/templates/config_edit.html", line 1, in top-level template code
    {% extends "layout.html" %}
  File "/app/calibre-web/cps/templates/layout.html", line 153, in top-level template code
    {% block body %}{% endblock %}
  File "/app/calibre-web/cps/templates/config_edit.html", line 300, in block "body"
    <a href="{{prov['obtain_link']}}" target="_blank">{{_('Obtain %(provider)s OAuth Credential', provider=prov['provider_name'])}}</a>
  File "/usr/local/lib/python3.6/dist-packages/jinja2/ext.py", line 144, in _gettext_alias
    return __context.call(__context.resolve("gettext"), *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/jinja2/ext.py", line 156, in gettext
    return rv % variables
  File "/usr/local/lib/python3.6/dist-packages/markupsafe/__init__.py", line 102, in __mod__
    return self.__class__(text_type.__mod__(self, arg))
  File "/usr/local/lib/python3.6/dist-packages/markupsafe/__init__.py", line 301, in __getitem__
    return _MarkupEscapeHelper(self.obj[item], self.escape)
KeyError: 'proveedor'

**Comment by OzzieIsaacs** [comment]
It's a bug in the translation, I'll fix it

**Comment by sampleslaya** [comment]
Hello.

I'm having the same problem.

Is there a fix for this?

Thanks in advance.

**Comment by oscargb1** [comment]
I'm having the same problem with the Spanish translation. I can edit the basic configuration changing the language to English, but it would be better if the bug was fixed.

Log:
`[2020-06-03 03:52:53,195] ERROR {cps:1892} Exception on /admin/config [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.6/dist-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/app/calibre-web/cps/web.py", line 213, in inner
    return f(*args, **kwargs)
  File "/app/calibre-web/cps/admin.py", line 143, in configuration
    return _configuration_result()
  File "/app/calibre-web/cps/admin.py", line 704, in _configuration_result
    title=_(u"Basic Configuration"), page="config")
  File "/app/calibre-web/cps/web.py", line 281, in render_title_template
    *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/usr/local/lib/python3.6/dist-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/usr/local/lib/python3.6/dist-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.6/dist-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/usr/local/lib/python3.6/dist-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/app/calibre-web/cps/templates/config_edit.html", line 1, in top-level template code
    {% extends "layout.html" %}
  File "/app/calibre-web/cps/templates/layout.html", line 153, in top-level template code
    {% block body %}{% endblock %}
  File "/app/calibre-web/cps/templates/config_edit.html", line 300, in block "body"
    <a href="{{prov['obtain_link']}}" target="_blank">{{_('Obtain %(provider)s OAuth Credential', provider=prov['provider_name'])}}</a>
  File "/usr/local/lib/python3.6/dist-packages/jinja2/ext.py", line 144, in _gettext_alias
    return __context.call(__context.resolve("gettext"), *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/jinja2/ext.py", line 156, in gettext
    return rv % variables
  File "/usr/local/lib/python3.6/dist-packages/markupsafe/__init__.py", line 102, in __mod__
    return self.__class__(text_type.__mod__(self, arg))
  File "/usr/local/lib/python3.6/dist-packages/markupsafe/__init__.py", line 301, in __getitem__
    return _MarkupEscapeHelper(self.obj[item], self.escape)
KeyError: 'proveedor'`

Running Calibre on Docker on Ubuntu Server 20.04 with linuxserver image. Accessing through Edge Chromium.
