### ISSUE TITLE
Fix 1364 not working ( unable to access edit basic configuration )

### ISSUE THREAD

**Issue by yeraycito** [janeczku/calibre-web#1370]
I have uninstalled and reinstalled linuxserver-calibreweb and the problem persists.

**Comment by yeraycito** [comment]
[2020-05-09 14:46:17,058]  INFO {cps:88} Starting Calibre Web...
[2020-05-09 14:46:17,315]  WARN {cps.config_sql:296} invalidating configuration
[2020-05-09 14:46:17,708]  INFO {cps.server:140} Starting Gevent server on [::]:8083
[2020-05-09 14:52:26,723] ERROR {cps:1892} Exception on /admin/config [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.6/dist-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/app/calibre-web/cps/web.py", line 213, in inner
    return f(*args, **kwargs)
  File "/app/calibre-web/cps/admin.py", line 143, in configuration
    return _configuration_result()
  File "/app/calibre-web/cps/admin.py", line 704, in _configuration_result
    title=_(u"Basic Configuration"), page="config")
  File "/app/calibre-web/cps/web.py", line 281, in render_title_template
    *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/usr/local/lib/python3.6/dist-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/usr/local/lib/python3.6/dist-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.6/dist-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/usr/local/lib/python3.6/dist-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/app/calibre-web/cps/templates/config_edit.html", line 1, in top-level template code
    {% extends "layout.html" %}
  File "/app/calibre-web/cps/templates/layout.html", line 153, in top-level template code
    {% block body %}{% endblock %}
  File "/app/calibre-web/cps/templates/config_edit.html", line 300, in block "body"
    <a href="{{prov['obtain_link']}}" target="_blank">{{_('Obtain %(provider)s OAuth Credential', provider=prov['provider_name'])}}</a>
  File "/usr/local/lib/python3.6/dist-packages/jinja2/ext.py", line 144, in _gettext_alias
    return __context.call(__context.resolve("gettext"), *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/jinja2/ext.py", line 156, in gettext
    return rv % variables
  File "/usr/local/lib/python3.6/dist-packages/markupsafe/__init__.py", line 102, in __mod__
    return self.__class__(text_type.__mod__(self, arg))
  File "/usr/local/lib/python3.6/dist-packages/markupsafe/__init__.py", line 301, in __getitem__
    return _MarkupEscapeHelper(self.obj[item], self.escape)
KeyError: 'proveedor'
[2020-05-09 14:52:37,881] ERROR {cps:1892} Exception on /admin/config [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.6/dist-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/app/calibre-web/cps/web.py", line 213, in inner
    return f(*args, **kwargs)
  File "/app/calibre-web/cps/admin.py", line 143, in configuration
    return _configuration_result()
  File "/app/calibre-web/cps/admin.py", line 704, in _configuration_result
    title=_(u"Basic Configuration"), page="config")
  File "/app/calibre-web/cps/web.py", line 281, in render_title_template
    *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/usr/local/lib/python3.6/dist-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/usr/local/lib/python3.6/dist-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.6/dist-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/usr/local/lib/python3.6/dist-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/app/calibre-web/cps/templates/config_edit.html", line 1, in top-level template code
    {% extends "layout.html" %}
  File "/app/calibre-web/cps/templates/layout.html", line 153, in top-level template code
    {% block body %}{% endblock %}
  File "/app/calibre-web/cps/templates/config_edit.html", line 300, in block "body"
    <a href="{{prov['obtain_link']}}" target="_blank">{{_('Obtain %(provider)s OAuth Credential', provider=prov['provider_name'])}}</a>
  File "/usr/local/lib/python3.6/dist-packages/jinja2/ext.py", line 144, in _gettext_alias
    return __context.call(__context.resolve("gettext"), *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/jinja2/ext.py", line 156, in gettext
    return rv % variables
  File "/usr/local/lib/python3.6/dist-packages/markupsafe/__init__.py", line 102, in __mod__
    return self.__class__(text_type.__mod__(self, arg))
  File "/usr/local/lib/python3.6/dist-packages/markupsafe/__init__.py", line 301, in __getitem__
    return _MarkupEscapeHelper(self.obj[item], self.escape)
KeyError: 'proveedor'
[2020-05-09 14:53:03,176] ERROR {cps:1892} Exception on /admin/config [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.6/dist-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/app/calibre-web/cps/web.py", line 213, in inner
    return f(*args, **kwargs)
  File "/app/calibre-web/cps/admin.py", line 143, in configuration
    return _configuration_result()
  File "/app/calibre-web/cps/admin.py", line 704, in _configuration_result
    title=_(u"Basic Configuration"), page="config")
  File "/app/calibre-web/cps/web.py", line 281, in render_title_template
    *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/usr/local/lib/python3.6/dist-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/usr/local/lib/python3.6/dist-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.6/dist-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/usr/local/lib/python3.6/dist-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/app/calibre-web/cps/templates/config_edit.html", line 1, in top-level template code
    {% extends "layout.html" %}
  File "/app/calibre-web/cps/templates/layout.html", line 153, in top-level template code
    {% block body %}{% endblock %}
  File "/app/calibre-web/cps/templates/config_edit.html", line 300, in block "body"
    <a href="{{prov['obtain_link']}}" target="_blank">{{_('Obtain %(provider)s OAuth Credential', provider=prov['provider_name'])}}</a>
  File "/usr/local/lib/python3.6/dist-packages/jinja2/ext.py", line 144, in _gettext_alias
    return __context.call(__context.resolve("gettext"), *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/jinja2/ext.py", line 156, in gettext
    return rv % variables
  File "/usr/local/lib/python3.6/dist-packages/markupsafe/__init__.py", line 102, in __mod__
    return self.__class__(text_type.__mod__(self, arg))
  File "/usr/local/lib/python3.6/dist-packages/markupsafe/__init__.py", line 301, in __getitem__
    return _MarkupEscapeHelper(self.obj[item], self.escape)
KeyError: 'proveedor'
[2020-05-09 14:55:15,228] ERROR {cps:1892} Exception on /admin/config [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.6/dist-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/app/calibre-web/cps/web.py", line 213, in inner
    return f(*args, **kwargs)
  File "/app/calibre-web/cps/admin.py", line 143, in configuration
    return _configuration_result()
  File "/app/calibre-web/cps/admin.py", line 704, in _configuration_result
    title=_(u"Basic Configuration"), page="config")
  File "/app/calibre-web/cps/web.py", line 281, in render_title_template
    *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/usr/local/lib/python3.6/dist-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/usr/local/lib/python3.6/dist-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.6/dist-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/usr/local/lib/python3.6/dist-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/app/calibre-web/cps/templates/config_edit.html", line 1, in top-level template code
    {% extends "layout.html" %}
  File "/app/calibre-web/cps/templates/layout.html", line 153, in top-level template code
    {% block body %}{% endblock %}
  File "/app/calibre-web/cps/templates/config_edit.html", line 300, in block "body"
    <a href="{{prov['obtain_link']}}" target="_blank">{{_('Obtain %(provider)s OAuth Credential', provider=prov['provider_name'])}}</a>
  File "/usr/local/lib/python3.6/dist-packages/jinja2/ext.py", line 144, in _gettext_alias
    return __context.call(__context.resolve("gettext"), *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/jinja2/ext.py", line 156, in gettext
    return rv % variables
  File "/usr/local/lib/python3.6/dist-packages/markupsafe/__init__.py", line 102, in __mod__
    return self.__class__(text_type.__mod__(self, arg))
  File "/usr/local/lib/python3.6/dist-packages/markupsafe/__init__.py", line 301, in __getitem__
    return _MarkupEscapeHelper(self.obj[item], self.escape)
KeyError: 'proveedor'
[2020-05-09 15:01:03,104] ERROR {cps:1892} Exception on /admin/config [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.6/dist-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/app/calibre-web/cps/web.py", line 213, in inner
    return f(*args, **kwargs)
  File "/app/calibre-web/cps/admin.py", line 143, in configuration
    return _configuration_result()
  File "/app/calibre-web/cps/admin.py", line 704, in _configuration_result
    title=_(u"Basic Configuration"), page="config")
  File "/app/calibre-web/cps/web.py", line 281, in render_title_template
    *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/usr/local/lib/python3.6/dist-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/usr/local/lib/python3.6/dist-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.6/dist-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/usr/local/lib/python3.6/dist-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/app/calibre-web/cps/templates/config_edit.html", line 1, in top-level template code
    {% extends "layout.html" %}
  File "/app/calibre-web/cps/templates/layout.html", line 153, in top-level template code
    {% block body %}{% endblock %}
  File "/app/calibre-web/cps/templates/config_edit.html", line 300, in block "body"
    <a href="{{prov['obtain_link']}}" target="_blank">{{_('Obtain %(provider)s OAuth Credential', provider=prov['provider_name'])}}</a>
  File "/usr/local/lib/python3.6/dist-packages/jinja2/ext.py", line 144, in _gettext_alias
    return __context.call(__context.resolve("gettext"), *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/jinja2/ext.py", line 156, in gettext
    return rv % variables
  File "/usr/local/lib/python3.6/dist-packages/markupsafe/__init__.py", line 102, in __mod__
    return self.__class__(text_type.__mod__(self, arg))
  File "/usr/local/lib/python3.6/dist-packages/markupsafe/__init__.py", line 301, in __getitem__
    return _MarkupEscapeHelper(self.obj[item], self.escape)
KeyError: 'proveedor'

**Comment by CHBMB** [comment]
The container only gets a calibe-web update when @OzzieIsaacs pushes a new version, so until that point the fix won't be integrated.

**Comment by yeraycito** [comment]
Thank you. And how do you know when there's a new version?

**Comment by CHBMB** [comment]
No, it would be @OzzieIsaacs that determines that.

**Comment by OzzieIsaacs** [comment]
Workaround would be change the user language to something else than spanish, doing the config in the basic config page and afterwards switching back. There is nothing else happening beside the error 500, so don't worry if you forget it.
