### ISSUE TITLE
timestamp issue in Kobo Sync process

### ISSUE THREAD

**Issue by FrouxBY** [janeczku/calibre-web#1391]
**Describe the bug/problem**
When trying the Kobo Sync Features, it failed with issues related to timestamp error while getting reading_state of the Kobo. This cause failure of the sync process

**To Reproduce**
I am using technosoft2000 docker image
1. Install optional-requirements.txt `pip install -r optional-requirement.txt` from within the docker container (they are missing with the current build image)
2. Activate Kobo Sync from Calibre Web admin interface
3. update the api endpoint url in .kobo of the Kobo Device
4. Try to synchronise calibre-web library

**Logfile**
calibre-web.log
```
[2020-05-13 09:25:49,687]  INFO {cps.kobo:132} Kobo library sync request received.
[2020-05-13 09:25:49,687] DEBUG {cps.kobo:134} Kobo: Received unproxied request, changed request port to server port
[2020-05-13 09:25:49,737] ERROR {cps:1892} Exception on /kobo/token*******/v1/library/sync [GET]
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/calibre-web/app/cps/kobo_auth.py", line 112, in inner
    return f(*args, **kwargs)
  File "/calibre-web/app/cps/web.py", line 237, in inner
    return f(*args, **kwargs)
  File "/calibre-web/app/cps/kobo.py", line 190, in HandleSyncRequest
    entitlement["ReadingState"] = get_kobo_reading_state_response(book, kobo_reading_state)
  File "/calibre-web/app/cps/kobo.py", line 729, in get_kobo_reading_state_response
    "StatusInfo": get_status_info_response(kobo_reading_state.book_read_link),
  File "/calibre-web/app/cps/kobo.py", line 737, in get_status_info_response
    "LastModified": convert_to_kobo_timestamp_string(book_read.last_modified),
  File "/calibre-web/app/cps/kobo.py", line 124, in convert_to_kobo_timestamp_string
    return timestamp.strftime("%Y-%m-%dT%H:%M:%SZ")
AttributeError: 'NoneType' object has no attribute 'strftime'
```

Here are the access.log:
```
[2020-05-13 09:25:49] "GET /kobo/token*******/v1/library/sync?Filter=ALL&DownloadUrlFilter=Generic,Android&PrioritizeRecentReads=true HTTP/1.1" 500 4605 0.067543
[2020-05-13 09:25:50] "GET /kobo/token*******/v1/initialization HTTP/1.1" 200 8978 0.051700
[2020-05-13 09:25:50] "GET /kobo/token*******/v1/user/profile HTTP/1.1" 200 124 0.018943
[2020-05-13 09:25:51] "GET /kobo/token*******/v1/user/loyalty/benefits HTTP/1.1" 200 124 0.019293
[2020-05-13 09:25:51] "GET /kobo/token*******/v1/analytics/gettests HTTP/1.1" 200 124 0.018958
[2020-05-13 09:25:51] "GET /kobo/token*******/v1/library/sync?Filter=ALL&DownloadUrlFilter=Generic,Android&PrioritizeRecentReads=true HTTP/1.1" 500 4605 0.081135
```
**Expected behavior**
No issue and start of Kobo Synchronisation
.

**Environment (please complete the following information):**
 - OS: Debian Buster
 - Python version 2.7/16
 - Calibre-Web version master on 44d5adc16f4aa3ece7cc5df0e41d39ffcb7b40d6 commit
 - Docker container Technosoft2000
 - Kobo Device: Kobo Libra H20

**Additional context**
 access via Traefik 2 reverse proxy

I don't know if this is an issue of Calibre-web not handling potential missing information on a book, or something else,

Thanks for your help

**Comment by OzzieIsaacs** [comment]
Looks indeed like a bug. From reading the code, I would have suspected that it can not happen, but suprise suprise... The missing information is not in the calibre database, it's in Calibre-Web's own settings database, where the information is missing.

**Comment by OzzieIsaacs** [comment]
The problem "only" occurs if you are having books marked read/unread before upgrading to a version with kobo sync (database migration error). I fixed it in newest master commit. By exchanging the ub.py file in your container it will work (you need to run Calibre-Web once with the changed file to fix the problem)

**Comment by FrouxBY** [comment]
Thanks, it works now !

just for information I had an other issue with books that have series but no serie_index, I have fixed it manually by putting 0 for those, but it could be nice to have this case handled (sometimes books to really have an order in a series), 
finally I have seen the Todo question about check serie_index as integer, but I do have book with float index (1.1, 1.2, etc), so an int check will fail on those

**Comment by OzzieIsaacs** [comment]
I take a look at the series Index problem

**Comment by OzzieIsaacs** [comment]
Empty series-index fields are a bug in Calibre-Web, I opend a new issue for it (#1398). Additionally it's now checked if the series index field is not 0 or empty and replaced with 1. 
Regarding the int() cast: There is an additional field stating float number, so I don't no if number shall be e.g. 1 for an float number 1.5 or also 1.5 (makes both very less sense)
