### ISSUE TITLE
500 Internal Server Error?

### ISSUE THREAD

**Issue by wang745125665** [janeczku/calibre-web#1404]
500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
Traceback (most recent call last):
File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2447, in wsgi_app
response = self.full_dispatch_request()
File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1952, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1821, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 39, in reraise
raise value
File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1950, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1936, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/app/calibre-web/cps/web.py", line 185, in decorated_view
return login_required(func)(*args, **kwargs)
File "/usr/local/lib/python3.6/dist-packages/flask_login/utils.py", line 272, in decorated_view
return func(*args, **kwargs)
File "/app/calibre-web/cps/web.py", line 585, in index
entries, random, pagination = fill_indexpage(page, db.Books, True, [db.Books.timestamp.desc()])
File "/app/calibre-web/cps/helper.py", line 815, in fill_indexpage
return fill_indexpage_with_archived_books(page, database, db_filter, order, False, *join)
File "/app/calibre-web/cps/helper.py", line 820, in fill_indexpage_with_archived_books
randm = db.session.query(db.Books).filter(common_filters(allow_show_archived))\
AttributeError: 'NoneType' object has no attribute 'query'

**Comment by OzzieIsaacs** [comment]
Not enough information: 
https://github.com/janeczku/calibre-web/blob/master/CONTRIBUTING.md
