### ISSUE TITLE
Problem launching the web app 

### ISSUE THREAD

**Issue by rafarq** [janeczku/calibre-web#1406]
**Describe the bug/problem**
The cps.py won’t launch due to three problems. This is my output when launching python cps.py:

Traceback (most recent call last):
  File "cps.py", line 34, in <module>
    from cps import create_app
  File "/home/pi/books/calibre-web-master/cps/__init__.py", line 38, in <module>
    from .server import WebServer
  File "/home/pi/books/calibre-web-master/cps/server.py", line 33, in <module>
    from tornado.wsgi import WSGIContainer
  File "/home/pi/books/calibre-web-master/vendor/tornado/wsgi.py", line 51
    def to_wsgi_str(s: bytes) -> str:
                     ^
SyntaxError: invalid syntax

**Environment (please complete the following information):**
 - OS: Raspbian
 - python2.7
 - Calibre-Web version [e.g. 0.6.5 or master@16.02.20, 19:55 ]: las test as 17/5
 - Docker container [ None/Technosoft2000/Linuxuser]: none
 - Special Hardware [e.g. Rasperry Pi Zero]: raspberry pi 4

**Comment by OzzieIsaacs** [comment]
Please take a look at #1178
