### ISSUE TITLE
Startup crash

### ISSUE THREAD

**Issue by sciurius** [janeczku/calibre-web#1410]
**Describe the bug/problem**
calibre2ops fresh from git (master branch) crashes

**To Reproduce**
1. python cps.py

````
% python cps.py
Traceback (most recent call last):
  File "/home/jv/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1284, in _execute_context
    cursor, statement, parameters, context
  File "/home/jv/.local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 590, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such column: user.mature_content

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "cps.py", line 34, in <module>
    from cps import create_app
  File "/bulk/tmp/calibre-web/cps/__init__.py", line 71, in <module>
    ub.init_db(cli.settingspath)
  File "/bulk/tmp/calibre-web/cps/ub.py", line 663, in init_db
    migrate_Database(session)
  File "/bulk/tmp/calibre-web/cps/ub.py", line 560, in migrate_Database
    if session.query(User).filter(User.role.op('&')(constants.ROLE_ANONYMOUS) == constants.ROLE_ANONYMOUS).first() \
  File "/home/jv/.local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3375, in first
    ret = list(self[0:1])
  File "/home/jv/.local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3149, in __getitem__
    return list(res)
  File "/home/jv/.local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3481, in __iter__
    return self._execute_and_instances(context)
  File "/home/jv/.local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3506, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/home/jv/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1020, in execute
    return meth(self, multiparams, params)
  File "/home/jv/.local/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/jv/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1139, in _execute_clauseelement
    distilled_params,
  File "/home/jv/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1324, in _execute_context
    e, statement, parameters, cursor, context
  File "/home/jv/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1518, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/home/jv/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/home/jv/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1284, in _execute_context
    cursor, statement, parameters, context
  File "/home/jv/.local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 590, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such column: user.mature_content
[SQL: SELECT user.id AS user_id, user.nickname AS user_nickname, user.email AS user_email, user.role AS user_role, user.password AS user_password, user.kindle_mail AS user_kindle_mail, user.locale AS user_locale, user.sidebar_view AS user_sidebar_view, user.default_language AS user_default_language, user.mature_content AS user_mature_content, user.denied_tags AS user_denied_tags, user.allowed_tags AS user_allowed_tags, user.denied_column_value AS user_denied_column_value, user.allowed_column_value AS user_allowed_column_value 
FROM user 
WHERE (user.role & ?) = ?
 LIMIT ? OFFSET ?]
[parameters: (32, 32, 1, 0)]
(Background on this error at: http://sqlalche.me/e/e3q8)
````

**Logfile**
Contains the same error.

**Expected behavior**
Startup.

**Environment (please complete the following information):**
 - OS: Fedora 31
 - Python version: python3.7.7
 - Calibre-Web version: master@2020-05-20 13:30 CET:
 - Docker container: None
 - Browser: N/A

**Comment by Calimerorulez** [comment]
Same here

`[parameters: (32, 32, 1, 0)]

(Background on this error at: http://sqlalche.me/e/e3q8)

Traceback (most recent call last):

  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 1284, in _execute_context

    cursor, statement, parameters, context

  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/default.py", line 590, in do_execute

    cursor.execute(statement, parameters)

sqlite3.OperationalError: no such column: user.mature_content


The above exception was the direct cause of the following exception:


Traceback (most recent call last):

  File "/app/calibre-web/cps.py", line 34, in <module>

    from cps import create_app

  File "/app/calibre-web/cps/__init__.py", line 71, in <module>

    ub.init_db(cli.settingspath)

  File "/app/calibre-web/cps/ub.py", line 663, in init_db

    migrate_Database(session)

  File "/app/calibre-web/cps/ub.py", line 560, in migrate_Database

    if session.query(User).filter(User.role.op('&')(constants.ROLE_ANONYMOUS) == constants.ROLE_ANONYMOUS).first() \

  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/query.py", line 3375, in first

    ret = list(self[0:1])

  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/query.py", line 3149, in __getitem__

    return list(res)

  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/query.py", line 3481, in __iter__

    return self._execute_and_instances(context)

  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/query.py", line 3506, in _execute_and_instances

    result = conn.execute(querycontext.statement, self._params)

  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 1020, in execute

    return meth(self, multiparams, params)

  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection

    return connection._execute_clauseelement(self, multiparams, params)

  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 1139, in _execute_clauseelement

    distilled_params,

  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 1324, in _execute_context

    e, statement, parameters, cursor, context

  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 1518, in _handle_dbapi_exception

    sqlalchemy_exception, with_traceback=exc_info[2], from_=e

  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/util/compat.py", line 178, in raise_

    raise exception

  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 1284, in _execute_context

    cursor, statement, parameters, context

  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/default.py", line 590, in do_execute

    cursor.execute(statement, parameters)

sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such column: user.mature_content

[SQL: SELECT user.id AS user_id, user.nickname AS user_nickname, user.email AS user_email, user.role AS user_role, user.password AS user_password, user.kindle_mail AS user_kindle_mail, user.locale AS user_locale, user.sidebar_view AS user_sidebar_view, user.default_language AS user_default_language, user.mature_content AS user_mature_content, user.denied_tags AS user_denied_tags, user.allowed_tags AS user_allowed_tags, user.denied_column_value AS user_denied_column_value, user.allowed_column_value AS user_allowed_column_value 

FROM user 

WHERE (user.role & ?) = ?

 LIMIT ? OFFSET ?]

[parameters: (32, 32, 1, 0)]

(Background on this error at: http://sqlalche.me/e/e3q8)

Traceback (most recent call last):

  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 1284, in _execute_context

    cursor, statement, parameters, context

  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/default.py", line 590, in do_execute

    cursor.execute(statement, parameters)

sqlite3.OperationalError: no such column: user.mature_content`

**Comment by OzzieIsaacs** [comment]
What happened (in my opinion): You are having a very old settings database (equals old version of calibre-web). Is this possible? In between I created a setting to hide content (mature_content), afterwards I extended this global content hiding system to a system per user base. This made the mature_content setting obsolete.
If I generate new columns I check if the setting exists and if not, the codes adds the settings. In this case, I don't create the setting anymore (as it#s not needed anymore), but I try to migrate from an existing mature_content setting to the user based setting. the setting isn't available -> program crashes.
Workarounds ->
A) downgrade to a version between 0.6.6 and 0.6.0 (strange, all versions since 0.6.0 had the migration code)
B) delete settings database app.db and start with a fresh one

**Comment by sciurius** [comment]
Bingo!
Deleted app.db and it works again.

**Comment by Calimerorulez** [comment]
Well I deleted app.db. Restarted the server, but still the same error.

I’m using my self made docker image, which uses the latest tarball of the source code.

**Comment by OzzieIsaacs** [comment]
@Calimerorulez : You are now getting a different error message, or you deleted the wrong file or having some other sort of caching problem. I'm having automatic tests, which start with a fresh database. 
I did this a hundred times in the past month, deleting the app.db is definitely working to bypass this error message. Other possibility would be going back to 0.6.6 or something below, starting it once and then going to the newest version.
