### ISSUE TITLE
 When uploading additional format i got this error: 500 Internal Server Error

### ISSUE THREAD

**Issue by atomicbeecz** [janeczku/calibre-web#1417]
**Describe the bug/problem**
When you upload additional format to new book or existing book, you get 500 internal server error.

**To Reproduce**
1. Upload new book (for example epub)
2. New book pop-up will appear 
3. Click "upload format" (select another file - for example mobi)
4. Click save

**Another steps**:
If you have already uploaded some book:
1) edit metadata of that book
2) click upload format -> select file
3) click save 
4) got 500 internal server error

What is strange that the additional format is uploaded there....

**Logfile**
Internal Server Error
500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
Traceback (most recent call last):
File "/usr/lib/python2.7/site-packages/flask/app.py", line 2446, in wsgi_app
response = self.full_dispatch_request()
File "/usr/lib/python2.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/lib/python2.7/site-packages/flask/app.py", line 1820, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/usr/lib/python2.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/lib/python2.7/site-packages/flask/app.py", line 1935, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/calibre-web/app/cps/web.py", line 185, in decorated_view
return login_required(func)(*args, **kwargs)
File "/usr/lib/python2.7/site-packages/flask_login/utils.py", line 261, in decorated_view
return func(*args, **kwargs)
File "/calibre-web/app/cps/web.py", line 267, in inner
return f(*args, **kwargs)
File "/calibre-web/app/cps/editbooks.py", line 493, in edit_book
meta = upload_single_file(request, book, book_id)
File "/calibre-web/app/cps/editbooks.py", line 457, in upload_single_file
saved_filename, os.path.splitext(requested_file.filename), config.config_rarfile_location)
TypeError: process() takes exactly 4 arguments (3 given)

**Expected behavior**
Additional format will be uploaded without problem

**Screenshots**

**Environment (please complete the following information):**
 - OS: docker - image: technosoft2000/calibre-web:v1.4.0
 - Python version [e.g. python2.7]
 - Calibre-Web version calibre-web:v1.4.0
 - Docker container technosoft2000
 - Special Hardware N/A
 - Browser Firefox 76.0.1

**Comment by OzzieIsaacs** [comment]
Yes the latest release 0.6.7 has indeed this bug. It's fixed upstream. I'm working hard on doing a new release end of may

**Comment by OzzieIsaacs** [comment]
Release is out, bug should be fixed
