### ISSUE TITLE
Kobo sync bugs

### ISSUE THREAD

**Issue by rolfberkenbosch** [janeczku/calibre-web#1423]
The first sync is working, but the second sync gives errors on the Kobo devices, I have multiple (Kobo Touch, Kobo Aura HD2).

**To Reproduce**
1. Go to 'sync on the kobo

**Logfile**

calibre-web.log:
````
[2020-05-23 21:23:55,212] DEBUG {cps.config_sql:288} _ConfigSQL updating storage
[2020-05-23 21:24:35,769]  INFO {cps.kobo:902} Init
[2020-05-23 21:24:35,770] DEBUG {cps.kobo:917} Kobo: Received unproxied request, changed request port to server port
[2020-05-23 21:24:35,927] DEBUG {cps.kobo:840} Unimplemented User Request received: http://**REDACTED**/kobo/b158cc673c9d2f4d711a62bf1a6eb6ec/v1/user/profile
[2020-05-23 21:24:36,190] DEBUG {cps.kobo:840} Unimplemented User Request received: http://**REDACTED**/kobo/b158cc673c9d2f4d711a62bf1a6eb6ec/v1/user/loyalty/benefits
[2020-05-23 21:24:36,322] DEBUG {cps.kobo:840} Unimplemented User Request received: http://**REDACTED**/kobo/b158cc673c9d2f4d711a62bf1a6eb6ec/v1/analytics/gettests
[2020-05-23 21:24:36,527] ERROR {cps:1892} Exception on /kobo/b158cc673c9d2f4d711a62bf1a6eb6ec/v1/library/sync [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/app/calibre-web/cps/kobo_auth.py", line 112, in inner
    return f(*args, **kwargs)
  File "/app/calibre-web/cps/web.py", line 237, in inner
    return f(*args, **kwargs)
  File "/app/calibre-web/cps/kobo.py", line 131, in HandleSyncRequest
    sync_token = SyncToken.SyncToken.from_headers(request.headers)
  File "/app/calibre-web/cps/services/SyncToken.py", line 135, in from_headers
    tags_last_modified = get_datetime_from_json(data_json, "tags_last_modified")
  File "/app/calibre-web/cps/services/SyncToken.py", line 47, in get_datetime_from_json
    return datetime.utcfromtimestamp(json_object[field_name])
OverflowError: timestamp out of range for platform time_t
```

access.log:

```
::ffff:10.42.1.184 - - [2020-05-23 21:30:22] "GET /kobo/b158cc673c9d2f4d711a62bf1a6eb6ec/v1/initialization HTTP/1.1" 200 8872 0.100218
::ffff:10.42.1.184 - - [2020-05-23 21:30:22] "GET /kobo/b158cc673c9d2f4d711a62bf1a6eb6ec/v1/user/profile HTTP/1.1" 200 124 0.070237
::ffff:10.42.1.184 - - [2020-05-23 21:30:23] "GET /kobo/b158cc673c9d2f4d711a62bf1a6eb6ec/v1/user/loyalty/benefits HTTP/1.1" 200 124 0.053394
::ffff:10.42.1.184 - - [2020-05-23 21:30:23] "POST /kobo/b158cc673c9d2f4d711a62bf1a6eb6ec/v1/analytics/gettests HTTP/1.1" 200 124 0.047810
::ffff:10.42.1.184 - - [2020-05-23 21:30:24] "GET /kobo/b158cc673c9d2f4d711a62bf1a6eb6ec/v1/library/sync?Filter=ALL&DownloadUrlFilter=Generic,Android&PrioritizeRecentReads=true HTTP/1.1" 500 4348 0.105958
```

**Environment (please complete the following information):**
I'm using the latest docker version of linux-server/calibre-web

**Comment by troxology** [comment]
I have the same error, but a slightly different traceback. 

**Device**: 
Kobo Libra H2O

**Steps to reproduce:** 
1) Edit .conf file with kobo sync token
2) Sync
3) Cancel sync because you didn't realize it was syncing several hundred books at once (3 books synced)
4) Sync again = error

**Logfile**:

> [2020-05-26 15:48:32,118] ERROR {flask.app:1761} Exception on /kobo/83540e31f41dde953d259bd6505d47a5/v1/library/sync [GET]
> Traceback (most recent call last):
>   File "/usr/lib/python3/dist-packages/flask/app.py", line 2292, in wsgi_app
>     response = self.full_dispatch_request()
>   File "/usr/lib/python3/dist-packages/flask/app.py", line 1815, in full_dispatch_request
>     rv = self.handle_user_exception(e)
>   File "/usr/lib/python3/dist-packages/flask/app.py", line 1718, in handle_user_exception
>     reraise(exc_type, exc_value, tb)
>   File "/usr/lib/python3/dist-packages/flask/_compat.py", line 35, in reraise
>     raise value
>   File "/usr/lib/python3/dist-packages/flask/app.py", line 1813, in full_dispatch_request
>     rv = self.dispatch_request()
>   File "/usr/lib/python3/dist-packages/flask/app.py", line 1799, in dispatch_request
>     return self.view_functions[rule.endpoint](**req.view_args)
>   File "/home/pi/calibre-web-0.6.7/cps/kobo_auth.py", line 112, in inner
>     return f(*args, **kwargs)
>   File "/home/pi/calibre-web-0.6.7/cps/web.py", line 237, in inner
>     return f(*args, **kwargs)
>   File "/home/pi/calibre-web-0.6.7/cps/kobo.py", line 131, in HandleSyncRequest
>     sync_token = SyncToken.SyncToken.from_headers(request.headers)
>   File "/home/pi/calibre-web-0.6.7/cps/services/SyncToken.py", line 133, in from_headers
>     archive_last_modified = get_datetime_from_json(data_json, "archive_last_modified")
>   File "/home/pi/calibre-web-0.6.7/cps/services/SyncToken.py", line 47, in get_datetime_from_json
>     return datetime.utcfromtimestamp(json_object[field_name])
> OverflowError: timestamp out of range for platform time_t
>

**Comment by LordSushiPhoenix** [comment]
Same behaviour running the latest linuxserver/calibre-web docker image on a raspberry pi 3.

**Steps to reproduce:**

1. Put sync token in `Kobo eReader.conf`
2. Sync  device
3. Sync fails with the following error

```
[2020-05-30 16:39:45,321] ERROR {cps:1892} Exception on /kobo/<removed>/v1/library/sync [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/app/calibre-web/cps/kobo_auth.py", line 112, in inner
    return f(*args, **kwargs)
  File "/app/calibre-web/cps/web.py", line 237, in inner
    return f(*args, **kwargs)
  File "/app/calibre-web/cps/kobo.py", line 131, in HandleSyncRequest
    sync_token = SyncToken.SyncToken.from_headers(request.headers)
  File "/app/calibre-web/cps/services/SyncToken.py", line 133, in from_headers
    archive_last_modified = get_datetime_from_json(data_json, "archive_last_modified")
  File "/app/calibre-web/cps/services/SyncToken.py", line 47, in get_datetime_from_json
    return datetime.utcfromtimestamp(json_object[field_name])
OverflowError: timestamp out of range for platform time_t
```

**Comment by pulitux** [comment]
Same here running last linuxserver/calibre-web image with RPi3b and libreelec 
**Device:** Kobo Aura 
**Steps to reproduce **

1. Put sync token in kobo 
2. Sync successful on first atempt 
3. Add a book to calibre-web 
4. Error trying to sync again 


```
[2020-06-27 18:32:56,397] ERROR {cps:1892} Exception on /kobo/&lt;removed&gt;/v1/library/sync [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/app/calibre-web/cps/kobo_auth.py", line 112, in inner
    return f(*args, **kwargs)
  File "/app/calibre-web/cps/web.py", line 253, in inner
    return f(*args, **kwargs)
  File "/app/calibre-web/cps/kobo.py", line 131, in HandleSyncRequest
    sync_token = SyncToken.SyncToken.from_headers(request.headers)
  File "/app/calibre-web/cps/services/SyncToken.py", line 133, in from_headers
    archive_last_modified = get_datetime_from_json(data_json, "archive_last_modified")
  File "/app/calibre-web/cps/services/SyncToken.py", line 47, in get_datetime_from_json
    return datetime.utcfromtimestamp(json_object[field_name])
OverflowError: timestamp out of range for platform time_t
```

**Comment by OzzieIsaacs** [comment]
Related to #1509.
The OverflowError is thrown during sync on some Linux Systems (my Linux Mint isn't affected) if one of the timestamps is outside range 1970 to 2038). This error is now catched

**Comment by troxology** [comment]
> 
> 
> Related to #1509.
> The OverflowError is thrown during sync on some Linux Systems (my Linux Mint isn't affected) if one of the timestamps is outside range 1970 to 2038). This error is now catched

Awesome, thank you! Works locally for me now.
