### ISSUE TITLE
Server stops after last update

### ISSUE THREAD

**Issue by ElQuimm** [janeczku/calibre-web#1436]
After perform the last update via the update option inside Calibre-web, the application stops

**To Reproduce**
1. Update from 0.68 beta
2. Server don't resart

**Logfile**
Add content of calibre-web.log file or the relevant error, try to reproduce your problem with "debug" log-level to get more output.

**Environment (please complete the following information):**
 - Docker container Technosoft2000 on QNAP

**Additional context**
Log file from QNAP's container station:
[INFO] Launching Calibre-Web ...                                                                                                                                            
Traceback (most recent call last):                                                                                                                                          
  File "/calibre-web/app/cps.py", line 36, in <module>                                                                                                                      
    from cps.opds import opds                                                                                                                                               
  File "/calibre-web/app/cps/opds.py", line 34, in <module>                                                                                                                 
    from .helper import get_download_link, get_book_cover                                                                                                                   
  File "/calibre-web/app/cps/helper.py", line 63, in <module>                                                                                                               
    from . import logger, config, get_locale, db, ub, isoLanguages, worker                                                                                                  
  File "/calibre-web/app/cps/worker.py", line 27, in <module>                                                                                                               
    import queue                                                                                                                                                            
ImportError: No module named queue

Thank you :-)

**Comment by OzzieIsaacs** [comment]
I have an idea for the cause but cannot reproduce the problem. I did a change in the current master branch. After the container is rebuild, we can give it a try.

**Comment by OzzieIsaacs** [comment]
Or to say better: I don't know how you get the newest version, as I'm not the maintainer of the docker project.

**Comment by ElQuimm** [comment]
If you point me to the modified file, I can edit inside of the container and restart them.

**Comment by OzzieIsaacs** [comment]
The file is located in the cps folder of calibre-web. The file name is worker.py. You can find it on github in the same folder. The changed lines are at the very beginning line 27-30, but I think replacing the whole file might be easiest way. Please check read/write permissions and file owner on replacement.
Good luck

**Comment by ElQuimm** [comment]
I give a try :-)

**Comment by ElQuimm** [comment]
I have manualy edited the file inside the container and... work like a charm :-)

Thank you!

**Comment by OzzieIsaacs** [comment]
Awesome
