### ISSUE TITLE
Error LookupError: Couldn't find path to unrar library

### ISSUE THREAD

**Issue by aroundmyroom** [janeczku/calibre-web#1474]
Updated from 0.6.7 to 0.6.8 by web
but all I see in th log is this:

[2020-06-07 15:05:26,760] DEBUG {cps.config_sql:316} _ConfigSQL updating storage

still waiting ..

**Comment by aroundmyroom** [comment]
uhm 
("Couldn't find path to unrar library

python3 cps.py
Traceback (most recent call last):
  File "cps.py", line 39, in <module>
    from cps.about import about
  File "/home/dennis/calibre-web/cps/about.py", line 33, in <module>
    from . import db, calibre_db, converter, uploader, server, isoLanguages, constants
  File "/home/dennis/calibre-web/cps/uploader.py", line 25, in <module>
    from . import logger, comic
  File "/home/dennis/calibre-web/cps/comic.py", line 37, in <module>
    from comicapi.comicarchive import ComicArchive, MetaDataStyle
  File "/home/dennis/calibre-web/vendor/comicapi/comicarchive.py", line 31, in <module>
    from unrar import rarfile
  File "/usr/local/lib/python3.7/dist-packages/unrar/rarfile.py", line 26, in <module>
    from unrar import unrarlib
  File "/usr/local/lib/python3.7/dist-packages/unrar/unrarlib.py", line 57, in <module>
    raise LookupError("Couldn't find path to unrar library.")
LookupError: Couldn't find path to unrar library.

**Comment by OzzieIsaacs** [comment]
Please try updating comicapi to thenewer version which is gien in optional-requirements.txt

**Comment by OzzieIsaacs** [comment]
Other options:
- removing python unrar (if you don't need it for other programms)
- install unrarlib and set environment- variable UNRAR_LIB_PATH

**Comment by aroundmyroom** [comment]
could upgrade from web now perfectly .. !
