### ISSUE TITLE
Reconnect option not working anymore in 0.6.8 ? causing error 500 internal server error

### ISSUE THREAD

**Issue by aroundmyroom** [janeczku/calibre-web#1479]
The /reconnect option was working fine for me to keep Calibre-Web working fine with a NFS share where my books are.

but when I use /reconnect now I get following error:

500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
Traceback (most recent call last):
File "/home/dennis/calibre-web/vendor/flask/app.py", line 2447, in wsgi_app
response = self.full_dispatch_request()
File "/home/dennis/calibre-web/vendor/flask/app.py", line 1952, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/home/dennis/calibre-web/vendor/flask/app.py", line 1821, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/home/dennis/calibre-web/vendor/flask/_compat.py", line 39, in reraise
raise value
File "/home/dennis/calibre-web/vendor/flask/app.py", line 1950, in full_dispatch_request
rv = self.dispatch_request()
File "/home/dennis/calibre-web/vendor/flask/app.py", line 1936, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/home/dennis/calibre-web/cps/web.py", line 989, in reconnect
db.reconnect_db(config, ub.app_DB_path)
AttributeError: module 'cps.db' has no attribute 'reconnect_db'

**Comment by aroundmyroom** [comment]
Update I see it is fixed, but it is not available through the web upgrade ?

**Comment by OzzieIsaacs** [comment]
![grafik](https://user-images.githubusercontent.com/6438895/84112659-7a45d780-aa29-11ea-83d2-d674cc2fc747.png)
You need to switch to "nightly updates" in Basic Configuration to make the update visible

**Comment by aroundmyroom** [comment]
Changing from stable to nightly fixed that issue .. I can keep using my crontab and reconnect the server, this solves the issues with my NFS share where the library is at. ;)
