### ISSUE TITLE
Internal Server Error after Upload of Book

### ISSUE THREAD

**Issue by skillpoint-dev** [janeczku/calibre-web#1499]
**Describe the bug/problem**

After uploading some books I ran suddenly into an error during upload, after that I am not able to open/read books anymore and of course also the upload is not working anymore.

**Logfile**

Internal Server Error
500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
Traceback (most recent call last):
File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2447, in wsgi_app
response = self.full_dispatch_request()
File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1952, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1821, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 39, in reraise
raise value
File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1950, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1936, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/app/calibre-web/cps/web.py", line 201, in decorated_view
return login_required(func)(*args, **kwargs)
File "/usr/local/lib/python3.6/dist-packages/flask_login/utils.py", line 272, in decorated_view
return func(*args, **kwargs)
File "/app/calibre-web/cps/web.py", line 623, in index
entries, random, pagination = calibre_db.fill_indexpage(page, db.Books, True, [db.Books.timestamp.desc()])
File "/app/calibre-web/cps/db.py", line 511, in fill_indexpage
return self.fill_indexpage_with_archived_books(page, database, db_filter, order, False, *join)
File "/app/calibre-web/cps/db.py", line 527, in fill_indexpage_with_archived_books
len(query.all()))
File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/query.py", line 3319, in all
return list(self)
File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/query.py", line 3481, in __iter__
return self._execute_and_instances(context)
File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/query.py", line 3503, in _execute_and_instances
querycontext, self._connection_from_session, close_with_result=True
File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/query.py", line 3518, in _get_bind_args
mapper=self._bind_mapper(), clause=querycontext.statement, **kw
File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/query.py", line 3496, in _connection_from_session
conn = self.session.connection(**kw)
File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/session.py", line 1141, in connection
execution_options=execution_options,
File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/session.py", line 1147, in _connection_for_bind
engine, execution_options
File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/session.py", line 409, in _connection_for_bind
self._assert_active()
File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/session.py", line 296, in _assert_active
code="7s2a",
sqlalchemy.exc.InvalidRequestError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (sqlite3.IntegrityError) UNIQUE constraint failed: books_tags_link.book, books_tags_link.tag
[SQL: INSERT INTO books_tags_link (book, tag) VALUES (?, ?)]
[parameters: ((370, 60), (370, 59), (370, 59))]
(Background on this error at: http://sqlalche.me/e/gkpj) (Background on this error at: http://sqlalche.me/e/7s2a)

**Environment (please complete the following information):**
 - OS: [e.g. Windows 10/raspian] QNAP QTS
 - Python version [e.g. python2.7] 
 - Calibre-Web version [e.g. 0.6.5 or master@16.02.20, 19:55 ]: latest (as of writing this)
 - Docker container [ None/Technosoft2000/Linuxuser]: LinuxServer
 - Special Hardware [e.g. Rasperry Pi Zero] QNAP NAS

**Comment by OzzieIsaacs** [comment]
The errormessage is a consequence of an earlier error. The book no.370 is twice linked to Tag no. 59. please try to start a check library for error maintenance in calibre itself.

**Comment by skillpoint-dev** [comment]
Unfortunately, though giving me access again that yielded no solution since no books are able to be opened anymore. I will go the route of a backup. Thank you anyway.

**Comment by m21020** [comment]
I am also now getting an error after uploading books using Calibre-web.  But I think the error is different.  I can read books, but search (or clicking Advanced Search) will produce an error.  The database opens properly in the Windows Calibre application.  It also finds no errors in the database.  
Should I open a new issue for this?

Internal Server Error
500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
Traceback (most recent call last):
File "/calibre-web/vendor/sqlalchemy/engine/base.py", line 1284, in _execute_context
cursor, statement, parameters, context
File "/calibre-web/vendor/sqlalchemy/engine/default.py", line 590, in do_execute
cursor.execute(statement, parameters)
sqlite3.DatabaseError: database disk image is malformed
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "/calibre-web/vendor/flask/app.py", line 2447, in wsgi_app
response = self.full_dispatch_request()
File "/calibre-web/vendor/flask/app.py", line 1952, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/calibre-web/vendor/flask/app.py", line 1821, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/calibre-web/vendor/flask/_compat.py", line 39, in reraise
raise value
File "/calibre-web/vendor/flask/app.py", line 1950, in full_dispatch_request
rv = self.dispatch_request()
File "/calibre-web/vendor/flask/app.py", line 1936, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/calibre-web/cps/web.py", line 201, in decorated_view
return login_required(func)(*args, **kwargs)
File "/calibre-web/vendor/flask_login/utils.py", line 272, in decorated_view
return func(*args, **kwargs)
File "/calibre-web/cps/web.py", line 1177, in advanced_search
.order_by(db.Data.format).all()
File "/calibre-web/vendor/sqlalchemy/orm/query.py", line 3319, in all
return list(self)
File "/calibre-web/vendor/sqlalchemy/orm/query.py", line 3481, in __iter__
return self._execute_and_instances(context)
File "/calibre-web/vendor/sqlalchemy/orm/query.py", line 3506, in _execute_and_instances
result = conn.execute(querycontext.statement, self._params)
File "/calibre-web/vendor/sqlalchemy/engine/base.py", line 1020, in execute
return meth(self, multiparams, params)
File "/calibre-web/vendor/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
return connection._execute_clauseelement(self, multiparams, params)
File "/calibre-web/vendor/sqlalchemy/engine/base.py", line 1139, in _execute_clauseelement
distilled_params,
File "/calibre-web/vendor/sqlalchemy/engine/base.py", line 1324, in _execute_context
e, statement, parameters, cursor, context
File "/calibre-web/vendor/sqlalchemy/engine/base.py", line 1518, in _handle_dbapi_exception
sqlalchemy_exception, with_traceback=exc_info[2], from_=e
File "/calibre-web/vendor/sqlalchemy/util/compat.py", line 178, in raise_
raise exception
File "/calibre-web/vendor/sqlalchemy/engine/base.py", line 1284, in _execute_context
cursor, statement, parameters, context
File "/calibre-web/vendor/sqlalchemy/engine/default.py", line 590, in do_execute
cursor.execute(statement, parameters)
sqlalchemy.exc.DatabaseError: (sqlite3.DatabaseError) database disk image is malformed
[SQL: SELECT calibre.data.id AS calibre_data_id, calibre.data.book AS calibre_data_book, calibre.data.format AS calibre_data_format, calibre.data.uncompressed_size AS calibre_data_uncompressed_size, calibre.data.name AS calibre_data_name
FROM calibre.data JOIN books ON books.id = calibre.data.book
WHERE 1 = 1 GROUP BY calibre.data.format ORDER BY calibre.data.format]
(Background on this error at: http://sqlalche.me/e/4xp6)

**Comment by skillpoint-dev** [comment]
Yes please. I have just imported a backup and continued from there.
