### ISSUE TITLE
Crash on enabling metadata watch

### ISSUE THREAD

**Issue by HarvsG** [janeczku/calibre-web#1528]
**Describe the bug/problem**
Trying to configure google drive sync in calibre web working on docker

**To Reproduce**
1. Load Calibre Web on docker using the linuxserver.io template
2.  Use this guide to configure google drive https://github.com/janeczku/calibre-web/wiki/Configuration#using-google-drive-integration
3. Authenticate google drive
4. Click enable watch metadata.db
5. See error 

**Logfile**
Add content of calibre-web.log file or the relevant error, try to reproduce your problem with "debug" log-level to get more output.
```
500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
Traceback (most recent call last):
File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2447, in wsgi_app
response = self.full_dispatch_request()
File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1952, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1821, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 39, in reraise
raise value
File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1950, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1936, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/usr/local/lib/python3.6/dist-packages/flask_login/utils.py", line 272, in decorated_view
return func(*args, **kwargs)
File "/app/calibre-web/cps/web.py", line 229, in inner
return f(*args, **kwargs)
File "/app/calibre-web/cps/admin.py", line 144, in configuration
return _configuration_result()
File "/app/calibre-web/cps/admin.py", line 736, in _configuration_result
title=_(u"Basic Configuration"), page="config")
File "/app/calibre-web/cps/web.py", line 297, in render_title_template
*args, **kwargs)
File "/usr/local/lib/python3.6/dist-packages/flask/templating.py", line 140, in render_template
ctx.app,
File "/usr/local/lib/python3.6/dist-packages/flask/templating.py", line 120, in _render
rv = template.render(context)
File "/usr/local/lib/python3.6/dist-packages/jinja2/environment.py", line 1090, in render
self.environment.handle_exception()
File "/usr/local/lib/python3.6/dist-packages/jinja2/environment.py", line 832, in handle_exception
reraise(*rewrite_traceback_stack(source=source))
File "/usr/local/lib/python3.6/dist-packages/jinja2/_compat.py", line 28, in reraise
raise value.with_traceback(tb)
File "/app/calibre-web/cps/templates/config_edit.html", line 1, in top-level template code
{% extends "layout.html" %}
File "/app/calibre-web/cps/templates/layout.html", line 154, in top-level template code
{% block body %}{% endblock %}
File "/app/calibre-web/cps/templates/config_edit.html", line 62, in block "body"
<input type="text" class="form-control" name="config_google_drive_watch_changes_response" id="config_google_drive_watch_changes_response" value="{{ config.config_google_drive_watch_changes_response['id'] }} expires on {{ config.config_google_drive_watch_changes_response['expiration'] | strftime }}" autocomplete="off" disabled="">
File "/app/calibre-web/cps/jinjia.py", line 101, in timestamptodate
int(date)/1000
jinja2.exceptions.UndefinedError: 'str object' has no attribute 'expiration'
```

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: docker on Raspberry Pi OS
 - Calibre-Web version: 0.6.8 
 - Docker container: [Linuxserver]:
 - Special Hardware: [e.g. Rasperry Pi 4 4GB]
 - Browser: [e.g. Chrome 83.0.4103.97]

**Additional context**
Add any other context about the problem here. [e.g. access via reverse proxy, database background sync, special database location]

**Comment by HarvsG** [comment]
related to https://github.com/janeczku/calibre-web/issues/1370?

**Comment by OzzieIsaacs** [comment]
1370 is a problem with wrong translation. This problem is a problem with storing json data in the database as string and you get json were we need a string, or vice versa. I try to take a look at it this weekend

**Comment by OzzieIsaacs** [comment]
Didn't make it last weekend, now I'm away from home, I have to chance to set up google drive, so takes another 3 weeks to check it.

**Comment by maltokyo** [comment]
Seems there are several duplicates, and I am stupid..

Would you have any advice on how to make this work @OzzieIsaacs 
I have exactly the same setup as the original author here, and exactly the same problem.

**Comment by OzzieIsaacs** [comment]
Please update to the newest version, 0.6.9, afterwards it should work.
