### ISSUE TITLE
Password Generation Problem when registering new account

### ISSUE THREAD

**Issue by dhatereki** [janeczku/calibre-web#1529]
Installed version V0.6.8 - Honor on Linux Mint 19.3 XFCE. Latest Calibre Build. 

Error appears whenever someone tries to register a new account with or without email as username. Same error if admin email server is set up or not.

500 Internal Server Error: 

The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

Traceback (most recent call last):
File "/home/talha/Downloads/calibre-web-0.6.8/vendor/flask/app.py", line 2447, in wsgi_app
response = self.full_dispatch_request()
File "/home/talha/Downloads/calibre-web-0.6.8/vendor/flask/app.py", line 1952, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/home/talha/Downloads/calibre-web-0.6.8/vendor/flask/app.py", line 1821, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/home/talha/Downloads/calibre-web-0.6.8/vendor/flask/app.py", line 1950, in full_dispatch_request
rv = self.dispatch_request()
File "/home/talha/Downloads/calibre-web-0.6.8/vendor/flask/app.py", line 1936, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/home/talha/Downloads/calibre-web-0.6.8/cps/web.py", line 1349, in register
password = generate_random_password()
File "/home/talha/Downloads/calibre-web-0.6.8/cps/helper.py", line 469, in generate_random_password
return "".join(s[c % len(s)] for c in os.urandom(passlen))
File "/home/talha/Downloads/calibre-web-0.6.8/cps/helper.py", line 469, in <genexpr>
return "".join(s[c % len(s)] for c in os.urandom(passlen))
TypeError: not all arguments converted during string formatting

**Comment by OzzieIsaacs** [comment]
Was also reported here:  #1507. It's fixed in the master branch, please update to the newest commit (switch to nightly updes and perform the in app update)
