### ISSUE TITLE
Unable to restart application with bad LDAP cert path

### ISSUE THREAD

**Issue by cpoissonnier** [janeczku/calibre-web#1533]
**Describe the bug/problem**
I've been trying to configure LDAP, but I put a bad value in the cert path, tried to restart the application (I use this Docker image: https://hub.docker.com/r/technosoft2000/calibre-web/) and the application fails to start. I think that the issue is not linked to the triggered by the way the Docker image is declared, but if you think that this issue should be created on its repository, let me know !

**To Reproduce**
1. Set a bad LDAP cert path
2. Restart the Docker image

**Logfile**
```
[INFO] Launching Calibre-Web ...
Traceback (most recent call last):
  File "/calibre-web/app/cps.py", line 79, in <module>
    main()
  File "/calibre-web/app/cps.py", line 60, in main
    app = create_app()
  File "/calibre-web/app/cps/__init__.py", line 112, in create_app
    services.ldap.init_app(app, config)
  File "/calibre-web/app/cps/services/simpleldap.py", line 68, in init_app
    _ldap.init_app(app)
  File "/usr/lib/python2.7/site-packages/flask_simpleldap/__init__.py", line 70, in init_app
    current_app.config['LDAP_CERT_PATH'])
  File "/usr/lib/python2.7/site-packages/werkzeug/local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
  File "/usr/lib/python2.7/site-packages/werkzeug/local.py", line 306, in _get_current_object
    return self.__local()
  File "/usr/lib/python2.7/site-packages/flask/globals.py", line 52, in _find_app
    raise RuntimeError(_app_ctx_err_msg)
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
to interface with the current application object in some way. To solve
this, set up an application context with app.app_context().  See the
documentation for more information.
```

**Environment (please complete the following information):**
 - "OS": Docker image
 - Python version: python2.7
 - Calibre-Web version: 93a0217d
 - Docker container: Technosoft2000
 - Special Hardware: -
 - Browser: -

**Comment by OzzieIsaacs** [comment]
Thanks for reporting. The error is catched in the newest commit version. After the docker container is updated, you should be able to use the app. A workaroung would be opening the app.db file with a sqlite database browser and change the ldap_cert_path entry in settings table
