### ISSUE TITLE
Can't update book metadata when using google drive integration

### ISSUE THREAD

**Issue by manualbashing** [janeczku/calibre-web#1546]
Calibre web is working great so far, but I am not able to edit metadata of any books using the UI. The error message displayed in the UI is `"Error editing book, please check logfile for details"`.

Changes in any book's metadata in Calibre Desktop on my client are saved without problem and are sucessfully synced to calibre web using the google drive integration.

**To Reproduce**
1. Go to any book
2. Click on "Edit Metadata"
3. Change any field
4. Click on "Save"
5. See error.

**Logfile**

```
[2020-07-28 08:44:53,899]  INFO {cps.gdrive:135} Change received from gdrive
[2020-07-28 08:44:53,899]  INFO {cps.gdrive:139} Getting change details
[2020-07-28 08:44:55,095] ERROR {cps.worker:225} Redirected but the response is missing a Location: header.
Traceback (most recent call last):
  File "/home/azureuser/calibre-web/cps/worker.py", line 215, in run
    self._convert_any_format()
  File "/home/azureuser/calibre-web/cps/worker.py", line 272, in _convert_any_format
    gdriveutils.updateGdriveCalibreFromLocal()
  File "/home/azureuser/calibre-web/cps/gdriveutils.py", line 500, in updateGdriveCalibreFromLocal
    copyToDrive(Gdrive.Instance().drive, config.config_calibre_dir, False, True)
  File "/home/azureuser/calibre-web/cps/gdriveutils.py", line 361, in copyToDrive
    copyToDrive(drive, f, True, replaceFiles, ignoreFiles, parent, os.path.join(prevDir, uploadFile))
  File "/home/azureuser/calibre-web/cps/gdriveutils.py", line 361, in copyToDrive
    copyToDrive(drive, f, True, replaceFiles, ignoreFiles, parent, os.path.join(prevDir, uploadFile))
  File "/home/azureuser/calibre-web/cps/gdriveutils.py", line 361, in copyToDrive
    copyToDrive(drive, f, True, replaceFiles, ignoreFiles, parent, os.path.join(prevDir, uploadFile))
  [Previous line repeated 1 more time]
  File "/home/azureuser/calibre-web/cps/gdriveutils.py", line 372, in copyToDrive
    driveFile.Upload()
  File "/home/azureuser/.local/lib/python3.6/site-packages/pydrive/files.py", line 285, in Upload
    self._FilesInsert(param=param)
  File "/home/azureuser/.local/lib/python3.6/site-packages/pydrive/auth.py", line 75, in _decorated
    return decoratee(self, *args, **kwargs)
  File "/home/azureuser/.local/lib/python3.6/site-packages/pydrive/files.py", line 369, in _FilesInsert
    http=self.http)
  File "/home/azureuser/.local/lib/python3.6/site-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/home/azureuser/.local/lib/python3.6/site-packages/googleapiclient/http.py", line 827, in execute
    _, body = self.next_chunk(http=http, num_retries=num_retries)
  File "/home/azureuser/.local/lib/python3.6/site-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/home/azureuser/.local/lib/python3.6/site-packages/googleapiclient/http.py", line 988, in next_chunk
    headers=headers)
  File "/home/azureuser/.local/lib/python3.6/site-packages/oauth2client/transport.py", line 175, in new_request
    redirections, connection_type)
  File "/home/azureuser/.local/lib/python3.6/site-packages/oauth2client/transport.py", line 282, in request
    connection_type=connection_type)
  File "/home/azureuser/.local/lib/python3.6/site-packages/httplib2/__init__.py", line 1991, in request
    cachekey,
  File "/home/azureuser/.local/lib/python3.6/site-packages/httplib2/__init__.py", line 1690, in _request
    content,
httplib2.RedirectMissingLocation: Redirected but the response is missing a Location: header.
[2020-07-28 08:53:33,895]  INFO {cps.gdrive:135} Change received from gdrive
[2020-07-28 08:53:33,895]  INFO {cps.gdrive:139} Getting change details
[2020-07-28 08:53:34,127] ERROR {cps.gdriveutils:482} <HttpError 404 when requesting https://www.googleapis.com/drive/v2/changes/174526?alt=json returned "Change not found: 174526">
```

**Expected behavior**
Edits to the metadata of the books in UI are expected to be saved and synced with google drive.

**Screenshots**
![Error message in the UI](https://i.imgur.com/2u8VKVH.png)

**Environment**
 - OS: Ubuntu 18.07 LTS
 - Python version: python3
 - Calibre-Web version: 1a1d105f
 - Docker container: None
 - Special Hardware: Azure VM
 - Browser: Edge Version 84.0.522.44 (Official build) (64-bit)

**Comment by OzzieIsaacs** [comment]
Could you please try to use the latest commit version from this morning I did a lot of changes and merged them to the master branch, the problem could be solved

**Comment by OzzieIsaacs** [comment]
No response for long time
