### ISSUE TITLE
Random errors about tables not existing - narrowed down to CalibreDB thread

### ISSUE THREAD

**Issue by blitzmann** [janeczku/calibre-web#1564]
This is both a bug that I've seen when converting books, but also kind of a development support question as I'm hacking around in the source code to get a better feel for it so that I can perform some customization's.

The bug in question is that I get random errors about `books` or `authors` table not existing when converting formats. This is infrequent, and somewhat hard to reproduce with any sort of consistency unfortunately. There also seems to be two places where it might break: 
1) In the worker thread when calibre-web gets the book (most common) - seems to maybe happen when you try to convert multiple things at a time? 
2) The CalibreDB thread where it tries to add the link to the new format (less common).

Exception from the worker thread:
```
Exception in thread Thread-3:
Traceback (most recent call last):
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\calibre-web2\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1278, in _execute_context
    cursor, statement, parameters, context
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\calibre-web2\venv\lib\site-packages\sqlalchemy\engine\default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such table: books

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\calibre-web2\cps\worker.py", line 216, in run
    self._convert_any_format()
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\calibre-web2\cps\worker.py", line 272, in _convert_any_format
    filename = self._convert_ebook_format()
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\calibre-web2\cps\worker.py", line 298, in _convert_ebook_format
    cur_book = calibre_db.get_book(book_id)
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\calibre-web2\cps\db.py", line 475, in get_book
    return self.session.query(Books).filter(Books.id == book_id).first()
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\calibre-web2\venv\lib\site-packages\sqlalchemy\orm\query.py", line 3397, in first
    ret = list(self[0:1])
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\calibre-web2\venv\lib\site-packages\sqlalchemy\orm\query.py", line 3171, in __getitem__
    return list(res)
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\calibre-web2\venv\lib\site-packages\sqlalchemy\orm\query.py", line 3503, in __iter__
    return self._execute_and_instances(context)
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\calibre-web2\venv\lib\site-packages\sqlalchemy\orm\query.py", line 3528, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\calibre-web2\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1014, in execute
    return meth(self, multiparams, params)
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\calibre-web2\venv\lib\site-packages\sqlalchemy\sql\elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\calibre-web2\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1133, in _execute_clauseelement
    distilled_params,
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\calibre-web2\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1318, in _execute_context
    e, statement, parameters, cursor, context
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\calibre-web2\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1512, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\calibre-web2\venv\lib\site-packages\sqlalchemy\util\compat.py", line 178, in raise_
    raise exception
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\calibre-web2\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1278, in _execute_context
    cursor, statement, parameters, context
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\calibre-web2\venv\lib\site-packages\sqlalchemy\engine\default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: books
[SQL: SELECT books.id AS books_id, books.title AS books_title, books.sort AS books_sort, books.author_sort AS books_author_sort, books.timestamp AS books_timestamp, books.pubdate AS books_pubdate, books.series_index AS books_series_index, books.last_modified AS books_last_modified, books.path AS books_path, books.has_cover AS books_has_cover, books.uuid AS books_uuid, books.isbn AS books_isbn, books.flags AS books_flags 
FROM books 
WHERE books.id = ?
 LIMIT ? OFFSET ?]
[parameters: (2, 1, 0)]
(Background on this error at: http://sqlalche.me/e/13/e3q8)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python36\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\calibre-web2\cps\worker.py", line 229, in run
    self.doLock.release()
RuntimeError: release unlocked lock
```

Exception from the CalibreDB thread:
```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\calibre-web2\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1278, in _execute_context
    cursor, statement, parameters, context
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\calibre-web2\venv\lib\site-packages\sqlalchemy\engine\default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such table: books

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Python36\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\calibre-web2\cps\db.py", line 354, in run
    cur_book = self.session.query(Books).filter(Books.id == i['id']).first()
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\calibre-web2\venv\lib\site-packages\sqlalchemy\orm\query.py", line 3397, in first
    ret = list(self[0:1])
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\calibre-web2\venv\lib\site-packages\sqlalchemy\orm\query.py", line 3171, in __getitem__
    return list(res)
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\calibre-web2\venv\lib\site-packages\sqlalchemy\orm\query.py", line 3503, in __iter__
    return self._execute_and_instances(context)
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\calibre-web2\venv\lib\site-packages\sqlalchemy\orm\query.py", line 3528, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\calibre-web2\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1014, in execute
    return meth(self, multiparams, params)
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\calibre-web2\venv\lib\site-packages\sqlalchemy\sql\elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\calibre-web2\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1133, in _execute_clauseelement
    distilled_params,
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\calibre-web2\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1318, in _execute_context
    e, statement, parameters, cursor, context
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\calibre-web2\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1512, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\calibre-web2\venv\lib\site-packages\sqlalchemy\util\compat.py", line 178, in raise_
    raise exception
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\calibre-web2\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1278, in _execute_context
    cursor, statement, parameters, context
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\calibre-web2\venv\lib\site-packages\sqlalchemy\engine\default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: books
[SQL: SELECT books.id AS books_id, books.title AS books_title, books.sort AS books_sort, books.author_sort AS books_author_sort, books.timestamp AS books_timestamp, books.pubdate AS books_pubdate, books.series_index AS books_series_index, books.last_modified AS books_last_modified, books.path AS books_path, books.has_cover AS books_has_cover, books.uuid AS books_uuid, books.isbn AS books_isbn, books.flags AS books_flags 
FROM books 
WHERE books.id = ?
 LIMIT ? OFFSET ?]
[parameters: (1, 1, 0)]
(Background on this error at: http://sqlalche.me/e/13/e3q8)
```

Having some experience with SQLAlchemy and threading, this screams some sort of concurrency issue. But I've always been at a loss on how to really identify and fix them. 😥

To help test out the CalibreDB thread issue, I have a small commit here:
https://github.com/blitzmann/calibre-web/commit/30d5e300fe0bb50362b93793dd31449b7287131d

This creates a `POST /api/format_test` that can be hit form any decent API testing like Postman. It generates a worker task. That worker task then generates a new format, and sends it off as a DB task. Sometimes it works fine, but sometimes it does show the issue and throws the error above. 

### More extreme example
This one uses the same concepts as the issues above, but seems to produce an error every time. This test actually commits junk data, so be careful if you want to run it :)

https://github.com/blitzmann/calibre-web/commit/636459cf6574d59d96c05375a1cb51f31ae5d0d5

Here I'm attempting to create a new author in the database (using random characters as this is just a test). I have two test APIs - one that uses a worker, that calls a DB task to generate and commit a new author. This seems to fail every time with `no such table: authors`. The other API is the same thing, except it's performed within the application thread, and runs fine. This further points to some sort of concurrency issue.

Please let me know if you have any questions or want to try some things out. I'm keen on getting the threading figured out since my customization will rely on it working reliably :)

**Environment (please complete the following information):**
 - OS: Windows 10
 - Python version: Python 3.6
 - Calibre-Web version: 1a1d105faee147738071bc44cdb577f72d2e4d6c
 - Docker container: None
 - Special Hardware: N/A
 - Browser: Chrome

**Comment by blitzmann** [comment]
Here's some more info. I set SQLAlchemy `echo=True` and then ran the `POST /api/format_test` route. Below shows that the first invocation worked (SQL shows ROLLBACK, but that's because I added that to the DB thread task since I didn't want these tests to be committed), but the second failed and produced the error. 

```2020-08-11 11:54:37,190 INFO sqlalchemy.engine.base.Engine SELECT books.id AS books_id, books.title AS books_title, books.sort AS books_sort, books.author_sort AS books_author_sort, books.timestamp AS books_timestamp, books.pubdate AS books_pubdate, books.series_index AS books_series_index, books.last_modified AS books_last_modified, books.path AS books_path, books.has_cover AS books_has_cover, books.uuid AS books_uuid, books.isbn AS books_isbn, books.flags AS books_flags 
FROM books 
WHERE books.id = ?
 LIMIT ? OFFSET ?
2020-08-11 11:54:37,190 INFO sqlalchemy.engine.base.Engine (1, 1, 0)
2020-08-11 11:54:37,190 INFO sqlalchemy.engine.base.Engine ROLLBACK
Done
2020-08-11 11:54:53,326 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2020-08-11 11:54:53,327 INFO sqlalchemy.engine.base.Engine SELECT books.id AS books_id, books.title AS books_title, books.sort AS books_sort, books.author_sort AS books_author_sort, books.timestamp AS books_timestamp, books.pubdate AS books_pubdate, books.series_index AS books_series_index, books.last_modified AS books_last_modified, books.path AS books_path, books.has_cover AS books_has_cover, books.uuid AS books_uuid, books.isbn AS books_isbn, books.flags AS books_flags 
FROM books 
WHERE books.id = ?
 LIMIT ? OFFSET ?
2020-08-11 11:54:53,327 INFO sqlalchemy.engine.base.Engine (1, 1, 0)
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\calibre-web2\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1278, in _execute_context
    cursor, statement, parameters, context
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\calibre-web2\venv\lib\site-packages\sqlalchemy\engine\default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such table: books

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Python36\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\calibre-web2\cps\db.py", line 354, in run
    cur_book = self.session.query(Books).filter(Books.id == i['id']).first()
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\calibre-web2\venv\lib\site-packages\sqlalchemy\orm\query.py", line 3397, in first
    ret = list(self[0:1])
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\calibre-web2\venv\lib\site-packages\sqlalchemy\orm\query.py", line 3171, in __getitem__
    return list(res)
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\calibre-web2\venv\lib\site-packages\sqlalchemy\orm\query.py", line 3503, in __iter__
    return self._execute_and_instances(context)
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\calibre-web2\venv\lib\site-packages\sqlalchemy\orm\query.py", line 3528, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\calibre-web2\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1014, in execute
    return meth(self, multiparams, params)
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\calibre-web2\venv\lib\site-packages\sqlalchemy\sql\elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\calibre-web2\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1133, in _execute_clauseelement
    distilled_params,
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\calibre-web2\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1318, in _execute_context
    e, statement, parameters, cursor, context
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\calibre-web2\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1512, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\calibre-web2\venv\lib\site-packages\sqlalchemy\util\compat.py", line 178, in raise_
    raise exception
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\calibre-web2\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1278, in _execute_context
    cursor, statement, parameters, context
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\calibre-web2\venv\lib\site-packages\sqlalchemy\engine\default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: books
[SQL: SELECT books.id AS books_id, books.title AS books_title, books.sort AS books_sort, books.author_sort AS books_author_sort, books.timestamp AS books_timestamp, books.pubdate AS books_pubdate, books.series_index AS books_series_index, books.last_modified AS books_last_modified, books.path AS books_path, books.has_cover AS books_has_cover, books.uuid AS books_uuid, books.isbn AS books_isbn, books.flags AS books_flags 
FROM books 
WHERE books.id = ?
 LIMIT ? OFFSET ?]
[parameters: (1, 1, 0)]
(Background on this error at: http://sqlalche.me/e/13/e3q8)
```

I should also mention that when these errors happen, the entire app is then broken and needs to be restarted. This is calibre-web loading after hitting that error:

![image](https://user-images.githubusercontent.com/3904767/89920026-f6939d00-dbc9-11ea-924b-71770e16d53f.png)

```Traceback (most recent call last):
File "C:\Users\holme\Documents\Sync\Git\blitzmann\calibre-web2\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1278, in _execute_context
cursor, statement, parameters, context
File "C:\Users\holme\Documents\Sync\Git\blitzmann\calibre-web2\venv\lib\site-packages\sqlalchemy\engine\default.py", line 593, in do_execute
cursor.execute(statement, parameters)
sqlite3.OperationalError: no such table: books
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "C:\Users\holme\Documents\Sync\Git\blitzmann\calibre-web2\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
response = self.full_dispatch_request()
File "C:\Users\holme\Documents\Sync\Git\blitzmann\calibre-web2\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
rv = self.handle_user_exception(e)
File "C:\Users\holme\Documents\Sync\Git\blitzmann\calibre-web2\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "C:\Users\holme\Documents\Sync\Git\blitzmann\calibre-web2\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
raise value
File "C:\Users\holme\Documents\Sync\Git\blitzmann\calibre-web2\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
rv = self.dispatch_request()
File "C:\Users\holme\Documents\Sync\Git\blitzmann\calibre-web2\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "C:\Users\holme\Documents\Sync\Git\blitzmann\calibre-web2\cps\web.py", line 196, in decorated_view
return login_required(func)(*args, **kwargs)
File "C:\Users\holme\Documents\Sync\Git\blitzmann\calibre-web2\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
return func(*args, **kwargs)
File "C:\Users\holme\Documents\Sync\Git\blitzmann\calibre-web2\cps\web.py", line 620, in index
entries, random, pagination = calibre_db.fill_indexpage(page, db.Books, True, [db.Books.timestamp.desc()])
File "C:\Users\holme\Documents\Sync\Git\blitzmann\calibre-web2\cps\db.py", line 514, in fill_indexpage
return self.fill_indexpage_with_archived_books(page, database, db_filter, order, False, *join)
File "C:\Users\holme\Documents\Sync\Git\blitzmann\calibre-web2\cps\db.py", line 530, in fill_indexpage_with_archived_books
len(query.all()))
File "C:\Users\holme\Documents\Sync\Git\blitzmann\calibre-web2\venv\lib\site-packages\sqlalchemy\orm\query.py", line 3341, in all
return list(self)
File "C:\Users\holme\Documents\Sync\Git\blitzmann\calibre-web2\venv\lib\site-packages\sqlalchemy\orm\query.py", line 3503, in __iter__
return self._execute_and_instances(context)
File "C:\Users\holme\Documents\Sync\Git\blitzmann\calibre-web2\venv\lib\site-packages\sqlalchemy\orm\query.py", line 3528, in _execute_and_instances
result = conn.execute(querycontext.statement, self._params)
File "C:\Users\holme\Documents\Sync\Git\blitzmann\calibre-web2\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1014, in execute
return meth(self, multiparams, params)
File "C:\Users\holme\Documents\Sync\Git\blitzmann\calibre-web2\venv\lib\site-packages\sqlalchemy\sql\elements.py", line 298, in _execute_on_connection
return connection._execute_clauseelement(self, multiparams, params)
File "C:\Users\holme\Documents\Sync\Git\blitzmann\calibre-web2\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1133, in _execute_clauseelement
distilled_params,
File "C:\Users\holme\Documents\Sync\Git\blitzmann\calibre-web2\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1318, in _execute_context
e, statement, parameters, cursor, context
File "C:\Users\holme\Documents\Sync\Git\blitzmann\calibre-web2\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1512, in _handle_dbapi_exception
sqlalchemy_exception, with_traceback=exc_info[2], from_=e
File "C:\Users\holme\Documents\Sync\Git\blitzmann\calibre-web2\venv\lib\site-packages\sqlalchemy\util\compat.py", line 178, in raise_
raise exception
File "C:\Users\holme\Documents\Sync\Git\blitzmann\calibre-web2\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1278, in _execute_context
cursor, statement, parameters, context
File "C:\Users\holme\Documents\Sync\Git\blitzmann\calibre-web2\venv\lib\site-packages\sqlalchemy\engine\default.py", line 593, in do_execute
cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: books
[SQL: SELECT books.id AS books_id, books.title AS books_title, books.sort AS books_sort, books.author_sort AS books_author_sort, books.timestamp AS books_timestamp, books.pubdate AS books_pubdate, books.series_index AS books_series_index, books.last_modified AS books_last_modified, books.path AS books_path, books.has_cover AS books_has_cover, books.uuid AS books_uuid, books.isbn AS books_isbn, books.flags AS books_flags
FROM books
WHERE 1 = 1]
(Background on this error at: http://sqlalche.me/e/13/e3q8)```

Again, shows `books` doesn't exist. It's almost like it loses it's reference to the calibre database randomly when invoking it through the thread and it things it's an empty database

**Comment by blitzmann** [comment]
Huzzah, think I found the issue:

https://docs.sqlalchemy.org/en/13/dialects/sqlite.html#using-a-memory-database-in-multiple-threads

Will make a PR and do some tests on this :)
