### ISSUE TITLE
Last commit broke SQL

### ISSUE THREAD

**Issue by Oreolek** [janeczku/calibre-web#1572]
The last commit 4d44746 broke SQL because it expects the database to support JSON columns. The application can't start now if SQL does not support it.

**Comment by OzzieIsaacs** [comment]
That‘s true, sqlite needs to support JSON datatype, to me it looked not like a big deal, as it was introduced 2015 with SQLite 3.9.0. which version of SQLite you are using?

**Comment by OzzieIsaacs** [comment]
And which distro?

**Comment by Oreolek** [comment]
3.11.0, ubuntu 16.04

**Comment by OzzieIsaacs** [comment]
Could you please provide the errormessage?

**Comment by Oreolek** [comment]
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/sql/type_api.py", line 471, in _cached_result_processor
    return dialect._type_memos[self][coltype]
  File "/usr/lib/python3.5/weakref.py", line 365, in __getitem__
    return self.data[ref(key)]
KeyError: <weakref at 0x7f19abbf3cc8; to 'JSON' at 0x7f19ac7ef630>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "cps.py", line 34, in <module>
    from cps import create_app
  File "/var/www/calibre-web/cps/__init__.py", line 74, in <module>
    config = config_sql.load_configuration(ub.session)
  File "/var/www/calibre-web/cps/config_sql.py", line 396, in load_configuration
    _migrate_database(session)
  File "/var/www/calibre-web/cps/config_sql.py", line 391, in _migrate_database
    _migrate_table(session, _Settings)
  File "/var/www/calibre-web/cps/config_sql.py", line 327, in _migrate_table
    session.query(column).first()
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/orm/query.py", line 2789, in first
    ret = list(self[0:1])
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/orm/query.py", line 2581, in __getitem__
    return list(res)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/orm/query.py", line 2889, in __iter__
    return self._execute_and_instances(context)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/orm/query.py", line 2912, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/base.py", line 948, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/sql/elements.py", line 269, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/base.py", line 1060, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/base.py", line 1215, in _execute_context
    result = context.get_result_proxy()
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/default.py", line 1008, in get_result_proxy
    return result.ResultProxy(self)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/result.py", line 649, in __init__
    self._init_metadata()
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/result.py", line 678, in _init_metadata
    self._metadata = ResultMetaData(self, cursor_description)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/result.py", line 215, in __init__
    num_ctx_cols, cols_are_ordered, textual_ordered)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/result.py", line 379, in _merge_cursor_description
    in enumerate(result_columns)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/result.py", line 378, in <listcomp>
    ) for idx, (key, name, obj, type_)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/default.py", line 971, in get_result_processor
    return type_._cached_result_processor(self.dialect, coltype)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/sql/type_api.py", line 477, in _cached_result_processor
    d[coltype] = rp = d['impl'].result_processor(dialect, coltype)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/sql/sqltypes.py", line 2148, in result_processor
    json_deserializer = dialect._json_deserializer or json.loads
AttributeError: 'SQLiteDialect_pysqlite' object has no attribute '_json_deserializer'
```
