### ISSUE TITLE
Unable to start after latest upgrade

### ISSUE THREAD

**Issue by simkin** [janeczku/calibre-web#159]
> [2017-03-13 10:10:13,366] {/usr/local/lib/python2.7/dist-packages/flask/app.py:1587} ERROR - Exception on / [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/flask_login.py", line 756, in decorated_view
    elif not current_user.is_authenticated():
TypeError: is_authenticated() takes exactly 1 argument (0 given)

**Comment by Kennyl** [comment]
Maybe update setuptools?
I have similar error (not exactly) when my upgrade fail once before.
setuptools>=33.1.1

**Comment by simkin** [comment]
That does not fix it for me, thanks for the suggestion though

**Comment by OzzieIsaacs** [comment]
Could you please verify the version of the installed package flask (>0.11) and flask login (>0.3.2). With one of the last commits, the vendor folder was cleared, so now the installed version of the system is taken, and it seems that this one differs from the recommended one.

**Comment by simkin** [comment]
> Flask==0.11.1
>Flask-Login==0.2.11

After upgrade:
> Flask==0.12
> Flask-Login==0.4.0

Issue resolved :)
