### ISSUE TITLE
Error 500 when clicking a book.

### ISSUE THREAD

**Issue by kendokan** [janeczku/calibre-web#161]
I'm running the docker container version.

```
2017-03-18 01:55:47,946 DEBG 'root' stdout output:
[2017-03-18 01:55:47,938] ERROR in app: Exception on /book/252 [GET]
Traceback (most recent call last):
  File "/opt/app/vendor/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/app/vendor/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/app/vendor/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/app/vendor/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/app/vendor/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/app/vendor/flask_login.py", line 792, in decorated_view
    return func(*args, **kwargs)
  File "/opt/app/cps/web.py", line 1016, in show_book
    @app.route('/category/<int:id>/<int:page>')
  File "/opt/app/cps/web.py", line 424, in render_title_template
    db_filter = db_object.lang_code
  File "/opt/app/vendor/flask/templating.py", line 134, in render_template
    context, ctx.app)
  File "/opt/app/vendor/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/opt/app/vendor/jinja2/environment.py", line 989, in render
    return self.environment.handle_exception(exc_info, True)
  File "/opt/app/vendor/jinja2/environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/app/cps/templates/detail.html", line 1, in top-level template code
    {% extends "layout.html" %}
  File "/opt/app/cps/templates/layout.html", line 164, in top-level template code
    {% block body %}{% endblock %}
  File "/opt/app/cps/templates/detail.html", line 129, in block "body"
    <li><a href="{{ url_for('get_download_link_ext', book_id=entry.id, format=format.format|lower, anyname=entry.id|string+'.'+format.format) }}">{{format.format}}</a></li>
  File "/opt/app/vendor/flask/helpers.py", line 332, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/opt/app/vendor/flask/app.py", line 1811, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/opt/app/vendor/flask/helpers.py", line 322, in url_for
    force_external=external)
  File "/opt/app/vendor/werkzeug/routing.py", line 1758, in build
    raise BuildError(endpoint, values, method, self)
BuildError: Could not build url for endpoint 'get_download_link_ext' with values ['anyname', 'book_id', 'format']. Did you mean 'get_download_link' instead?

```

**Comment by kendokan** [comment]
Disregard, docker issue.
