### ISSUE TITLE
Changing UI Name from 'Calibre-Web' Causes 502 Error

### ISSUE THREAD

**Issue by rlongio** [janeczku/calibre-web#1618]
**Describe the bug/problem**
When trying to change the web display name, regardless of characters or spaces, a 502 error occurs.  Using Apache2 as a reverse proxy.

**To Reproduce**
1. Go to UI Settings.
2. Try to change the Web Display Name from 'Calibre-Web'
3. Save

**Logfile**
[2020-09-15 22:44:21,569]  INFO {cps:98} Starting Calibre Web...
[2020-09-15 22:44:21,636]  INFO {cps.server:156} Starting Tornado server on :8083
[2020-09-15 22:44:44,544] ERROR {cps:1891} Exception on /admin/viewconfig [POST]
Traceback (most recent call last):
  File "/home/calibre/calibre-web/vendor/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/home/calibre/calibre-web/vendor/sqlalchemy/engine/default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
sqlite3.InterfaceError: Error binding parameter 1 - probably unsupported type.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/calibre/calibre-web/vendor/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/calibre/calibre-web/vendor/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/calibre/calibre-web/vendor/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/calibre/calibre-web/vendor/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/calibre/calibre-web/vendor/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/calibre/calibre-web/vendor/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/calibre/calibre-web/vendor/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/calibre/calibre-web/cps/web.py", line 229, in inner
    return f(*args, **kwargs)
  File "/home/calibre/calibre-web/cps/admin.py", line 188, in update_view_configuration
    config.save()
  File "/home/calibre/calibre-web/cps/config_sql.py", line 317, in save
    self._session.merge(s)
  File "/home/calibre/calibre-web/vendor/sqlalchemy/orm/session.py", line 2144, in merge
    self._autoflush()
  File "/home/calibre/calibre-web/vendor/sqlalchemy/orm/session.py", line 1628, in _autoflush
    util.raise_(e, with_traceback=sys.exc_info()[2])
  File "/home/calibre/calibre-web/vendor/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/home/calibre/calibre-web/vendor/sqlalchemy/orm/session.py", line 1617, in _autoflush
    self.flush()
  File "/home/calibre/calibre-web/vendor/sqlalchemy/orm/session.py", line 2523, in flush
    self._flush(objects)
  File "/home/calibre/calibre-web/vendor/sqlalchemy/orm/session.py", line 2664, in _flush
    transaction.rollback(_capture_exception=True)
  File "/home/calibre/calibre-web/vendor/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.raise_(
  File "/home/calibre/calibre-web/vendor/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/home/calibre/calibre-web/vendor/sqlalchemy/orm/session.py", line 2624, in _flush
    flush_context.execute()
  File "/home/calibre/calibre-web/vendor/sqlalchemy/orm/unitofwork.py", line 422, in execute
    rec.execute(self)
  File "/home/calibre/calibre-web/vendor/sqlalchemy/orm/unitofwork.py", line 586, in execute
    persistence.save_obj(
  File "/home/calibre/calibre-web/vendor/sqlalchemy/orm/persistence.py", line 230, in save_obj
    _emit_update_statements(
  File "/home/calibre/calibre-web/vendor/sqlalchemy/orm/persistence.py", line 994, in _emit_update_statements
    c = cached_connections[connection].execute(
  File "/home/calibre/calibre-web/vendor/sqlalchemy/engine/base.py", line 1011, in execute
    return meth(self, multiparams, params)
  File "/home/calibre/calibre-web/vendor/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
![2020-09-15 18_48_55-502 Proxy Error](https://user-images.githubusercontent.com/69773028/93272922-9ec9f200-f784-11ea-9008-2e1d61d839dd.png)
![2020-09-15 18_49_22-Calibre-Web _ UI Configuration](https://user-images.githubusercontent.com/69773028/93272924-a093b580-f784-11ea-9d1c-9e3264e5cf80.png)

**Expected behavior**
The database should save the change.

**Screenshots**

**Environment (please complete the following information):**
 - Ubuntu 20.04 LTS
 - Python version: 3.8.2
 - Calibre-Web version: 0.6.8
 - Linode server
 - Chrome Version 85.0.4183.102 (Official Build) (64-bit)

**Additional context**
Likely the error: 
Traceback (most recent call last):
  File "/home/calibre/calibre-web/vendor/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/home/calibre/calibre-web/vendor/sqlalchemy/engine/default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
sqlite3.InterfaceError: Error binding parameter 1 - probably unsupported type.

**Comment by OzzieIsaacs** [comment]
I can reproduce the behaviour. It's already fixed upstream (can't remember).
Please try updating to the newest nightly version: Go to admin section -> Basic setup -> Server Config -> Update Channel -> Nightly. Save it.
Go to admin section "Check for Update" -> perform update -> Should work

**Comment by OzzieIsaacs** [comment]
Please close the issue if this works for you
