### ISSUE TITLE
Internal 500 error - only from outside network

### ISSUE THREAD

**Issue by lanerobertlane** [janeczku/calibre-web#163]
This looks exactly like what I need. And works fine over a local network. I was wondering if you could help me direct this issue I'm having when using it over the net. 
I'm getting an Internal Server Error when i click the download button, but only via PU.BL.IC.IP:8080/download/etc.../file.mobi. It works fine from 192.168.0.X:8080/download/etc.../file.mobi

here's the error log: 

 ```
[2017-03-21 22:18:44,244] ERROR in app: Exception on /download/6134/mobi/6134.MOBI [GET]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1615, in full_dispatch_request
    return self.finalize_request(rv)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1632, in finalize_request
    response = self.process_response(response)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1858, in process_response
    self.save_session(ctx.session, response)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 924, in save_session
    return self.session_interface.save_session(self, session, response)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/sessions.py", line 366, in save_session
    domain=domain, path=path, secure=secure)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/werkzeug/wrappers.py", line 1056, in set_cookie
    self.headers.add('Set-Cookie', dump_cookie(key,
AttributeError: 'dict' object has no attribute 'add'
ERROR:tornado.access:500 GET /download/6134/mobi/6134.MOBI (pu.bl.ic.ip) 15.73ms
```
I can guess from the log that the issue is somewhere in flask, but as i mentioned it works fine when using the 192.168.0.x:8080 local network. It's only when i'm accessing off the network that i get this error, and only on the download button. I tried rebuilding the calibre database as i saw that fixed an issue.

Flask v0.12, flask login v0.2.0, flash principal v0.4.0, tornado web server v4.4.2

**Comment by OzzieIsaacs** [comment]
Looks like some issue regarding cookies. Could you please check which version "werkzeug" has? (pip show werkzeug should output that on the console)
Are you using calibre-web behind a reverse proxy or is there an other proxy in between?

**Comment by Kennyl** [comment]
I also get this error
last work commit 806cb5d856b05bbb6556f294098186a99554b306
not work after 907a2eca68f5ae703876c858601f5ad9d70db7ad
I am using no proxy  
```python cps.py ```
using localhost:8083

**Comment by OzzieIsaacs** [comment]
Thanks @Kennyl
