### ISSUE TITLE
500 Internal Server Error: when adding Google Drive "watch" of metadata.db

### ISSUE THREAD

**Issue by maltokyo** [janeczku/calibre-web#1636]
Everything until this step went well, but when I tried this: https://github.com/janeczku/calibre-web/wiki/Configuration#google-drive-optional-configuration

I get this error - and it comes back EVERY time that I use the basic config page now (i.e. I cant configure anything anymore):

```
Calibre-Web
Internal Server Error
500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
Traceback (most recent call last):
File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2447, in wsgi_app
response = self.full_dispatch_request()
File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1952, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1821, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 39, in reraise
raise value
File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1950, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1936, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/usr/local/lib/python3.6/dist-packages/flask_login/utils.py", line 272, in decorated_view
return func(*args, **kwargs)
File "/app/calibre-web/cps/web.py", line 229, in inner
return f(*args, **kwargs)
File "/app/calibre-web/cps/admin.py", line 144, in configuration
return _configuration_result()
File "/app/calibre-web/cps/admin.py", line 736, in _configuration_result
title=_(u"Basic Configuration"), page="config")
File "/app/calibre-web/cps/web.py", line 297, in render_title_template
*args, **kwargs)
File "/usr/local/lib/python3.6/dist-packages/flask/templating.py", line 140, in render_template
ctx.app,
File "/usr/local/lib/python3.6/dist-packages/flask/templating.py", line 120, in _render
rv = template.render(context)
File "/usr/local/lib/python3.6/dist-packages/jinja2/environment.py", line 1090, in render
self.environment.handle_exception()
File "/usr/local/lib/python3.6/dist-packages/jinja2/environment.py", line 832, in handle_exception
reraise(*rewrite_traceback_stack(source=source))
File "/usr/local/lib/python3.6/dist-packages/jinja2/_compat.py", line 28, in reraise
raise value.with_traceback(tb)
File "/app/calibre-web/cps/templates/config_edit.html", line 1, in top-level template code
{% extends "layout.html" %}
File "/app/calibre-web/cps/templates/layout.html", line 154, in top-level template code
{% block body %}{% endblock %}
File "/app/calibre-web/cps/templates/config_edit.html", line 62, in block "body"
<input type="text" class="form-control" name="config_google_drive_watch_changes_response" id="config_google_drive_watch_changes_response" value="{{ config.config_google_drive_watch_changes_response['id'] }} expires on {{ config.config_google_drive_watch_changes_response['expiration'] | strftime }}" autocomplete="off" disabled="">
File "/app/calibre-web/cps/jinjia.py", line 101, in timestamptodate
int(date)/1000
jinja2.exceptions.UndefinedError: 'str object' has no attribute 'expiration'
Please report this issue with all related information: Create Issue

```

**Comment by OzzieIsaacs** [comment]
Please fill out the issue form, I can't help you with this less information

**Comment by maltokyo** [comment]
Hi @OzzieIsaacs apologies.
I anyway now saw that mine is a duplicate of https://github.com/janeczku/calibre-web/issues/1532
I will comment there

**Comment by OzzieIsaacs** [comment]
Update to the newest version (from this morning should help)

**Comment by maltokyo** [comment]
ok, thank you, will try!

another duplicate here, where it is actually open https://github.com/janeczku/calibre-web/issues/1528
