### ISSUE TITLE
Error in search functionality

### ISSUE THREAD

**Issue by tomandocubatas** [janeczku/calibre-web#1643]
Hi all, 
I have the following error when i try to search.
Any idea?

> [2020-09-30 10:42:11,158] ERROR {cps:1892} Exception on /search [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
sqlite3.DatabaseError: database disk image is malformed
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/app/calibre-web/cps/web.py", line 197, in decorated_view
    return login_required(func)(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/app/calibre-web/cps/web.py", line 999, in search
    entries = calibre_db.get_search_results(term)
  File "/app/calibre-web/cps/db.py", line 619, in get_search_results
    )).order_by(Books.sort).all()
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/query.py", line 3346, in all
    return list(self)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/query.py", line 3508, in __iter__
    return self._execute_and_instances(context)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/query.py", line 3533, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 1011, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 1130, in _execute_clauseelement
    distilled_params,
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 1317, in _execute_context
    e, statement, parameters, cursor, context
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 1511, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.DatabaseError: (sqlite3.DatabaseError) database disk image is malformed
[SQL: SELECT books.id AS books_id, books.title AS books_title, books.sort AS books_sort, books.author_sort AS books_author_sort, books.timestamp AS books_timestamp, books.pubdate AS books_pubdate, books.series_index AS books_series_index, books.last_modified AS books_last_modified, books.path AS books_path, books.has_cover AS books_has_cover, books.uuid AS books_uuid, books.isbn AS books_isbn, books.flags AS books_flags 
FROM books 
WHERE 1 = 1 AND ((EXISTS (SELECT 1 
FROM books_tags_link, tags 
WHERE books.id = books_tags_link.book AND tags.id = books_tags_link.tag AND lower(lower(tags.name)) LIKE lower(?))) OR (EXISTS (SELECT 1 
FROM books_series_link, series 
WHERE books.id = books_series_link.book AND series.id = books_series_link.series AND lower(lower(series.name)) LIKE lower(?))) OR (EXISTS (SELECT 1 
FROM books_authors_link, authors 
WHERE books.id = books_authors_link.book AND authors.id = books_authors_link.author AND (EXISTS (SELECT 1 
FROM books_authors_link, authors 
WHERE books.id = books_authors_link.book AND authors.id = books_authors_link.author AND lower(lower(authors.name)) LIKE lower(?))) AND (EXISTS (SELECT 1 
FROM books_authors_link, authors 
WHERE books.id = books_authors_link.book AND authors.id = books_authors_link.author AND lower(lower(authors.name)) LIKE lower(?))))) OR (EXISTS (SELECT 1 
FROM books_publishers_link, publishers 
WHERE books.id = books_publishers_link.book AND publishers.id = books_publishers_link.publisher AND lower(lower(publishers.name)) LIKE lower(?))) OR lower(lower(books.title)) LIKE lower(?)) ORDER BY books.sort]
[parameters: ('%el cartero%', '%el cartero%', '%el%', '%cartero%', '%el cartero%', '%el cartero%')]
(Background on this error at: http://sqlalche.me/e/13/4xp6)

**Comment by OzzieIsaacs** [comment]
Your database has a problem, please perform a database check in calibre desktop app

**Comment by tomandocubatas** [comment]
Thanks.
Finally was a error in an index.
Great app!!! Thans for share it and your efftorts.

**Comment by tomandocubatas** [comment]
Thanks.
