### ISSUE TITLE
Crahs after update

### ISSUE THREAD

**Issue by Flo-63** [janeczku/calibre-web#1644]
**Describe the bug/problem**
After updating calibre-web and calibre to latest versions, calibre.-web does not start anymore.

**Environment (please complete the following information):**
 - OS: Debian Strech
 - Python2.7
 - Calibre-Web version: latest

This ist what I get:
Traceback (most recent call last):
  File "cps.py", line 34, in <module>
    from cps import create_app
  File "/var/www/calibre-web/cps/__init__.py", line 74, in <module>
    config = config_sql.load_configuration(ub.session)
  File "/var/www/calibre-web/cps/config_sql.py", line 397, in load_configuration
    _migrate_database(session)
  File "/var/www/calibre-web/cps/config_sql.py", line 392, in _migrate_database
    _migrate_table(session, _Settings)
  File "/var/www/calibre-web/cps/config_sql.py", line 328, in _migrate_table
    session.query(column).first()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2731, in first
    ret = list(self[0:1])
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2523, in __getitem__
    return list(res)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2831, in __iter__
    return self._execute_and_instances(context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2854, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 945, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/elements.py", line 263, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1053, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1204, in _execute_context
    result = context.get_result_proxy()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/default.py", line 877, in get_result_proxy
    return result.ResultProxy(self)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/result.py", line 653, in __init__
    self._init_metadata()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/result.py", line 682, in _init_metadata
    self._metadata = ResultMetaData(self, cursor_description)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/result.py", line 215, in __init__
    num_ctx_cols, cols_are_ordered, textual_ordered)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/result.py", line 379, in _merge_cursor_description
    in enumerate(result_columns)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/default.py", line 840, in get_result_processor
    return type_._cached_result_processor(self.dialect, coltype)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/type_api.py", line 472, in _cached_result_processor
    d[coltype] = rp = d['impl'].result_processor(dialect, coltype)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/sqltypes.py", line 2000, in result_processor
    json_deserializer = dialect._json_deserializer or json.loads
AttributeError: 'SQLiteDialect_pysqlite' object has no attribute '_json_deserializer'

**Comment by OzzieIsaacs** [comment]
Please update sqlalchemy to a version >=1.3.0

**Comment by OzzieIsaacs** [comment]
#1641

**Comment by Flo-63** [comment]
I am on 1.3.19

**Comment by Flo-63** [comment]
Issue seems not to be related to sqlalchemy version - as mentioned, the issue is on my system with sqlalchemy 1.3.19. 
Any advice?

**Comment by OzzieIsaacs** [comment]
I double checked it, the error only occurs with sqlalchemy<1.3.0. 
Are you really sure, the sqlalchemy installation you checked is used for calibre-web (virtual environment, python3 instead of python2, installation in vendor folder of calibre-web, installation in user's home directory instead of global installation)?
How did you install sqlalchemy? 
How did you check the version?

**Comment by Flo-63** [comment]
I am on python 3.5:
# python --version
Python 3.5.3
Installation of sqlalchemy is in /var/www/calibre-web/vendor folder, done via pip3 install --target vendor -r requirements.txt

I found out that app,db seems to cause the issue. When I replace it with a "fresh" one, I'm able to run the service, 
Is there any way to repair / migrate the app.db ?

**Comment by OzzieIsaacs** [comment]
Normally it should migrate itself. You could try to open the file with a database browser like sqlitebrowser. The cause is probably the column "config_google_drive_watch_changes_response" in the settings table. I'm curious what's in there in your database. A "{}" in this field should fix it

**Comment by Flo-63** [comment]
I modified the field according your mail. This fixed to start the service. Before, the field was of type "String" and empty. 
All users are back in the system - but now, the covers are not shown correctly... I can recall that this already happened in the past but I cannot recall how to fix it. Could you please advise?

**Comment by Flo-63** [comment]
Oops. Found it - flask update according #1033
