### ISSUE TITLE
Crash when converting epub to pdf

### ISSUE THREAD

**Issue by gramakri** [janeczku/calibre-web#1657]
**Describe the bug/problem**
I use the alice in wonderland epub from project gutenberg. I started a conversion to PDF. It failed to convert.

**To Reproduce**
1. Import the epub from https://www.gutenberg.org/ebooks/19033 . (epub no images)
2. Convert book format: from epub to pdf
3. The task is stuck
![image](https://user-images.githubusercontent.com/82041/95669080-4b538580-0b31-11eb-9e3a-b319a63bcc95.png)

**Logfile**
```
[2020-10-11 02:43:39,155]  INFO {cps.worker:303} Book id 1 - target format of .pdf does not exist. Moving forward with convert.
[2020-10-11 02:43:39,911] ERROR {cps.worker:225} 'ascii' codec can't decode byte 0xe2 in position 49: ordinal not in range(128)
Traceback (most recent call last):
  File "/app/code/calibre-web/cps/worker.py", line 215, in run
    self._convert_any_format()
  File "/app/code/calibre-web/cps/worker.py", line 269, in _convert_any_format
    filename = self._convert_ebook_format()
  File "/app/code/calibre-web/cps/worker.py", line 316, in _convert_ebook_format
    check, error_message = self._convert_calibre(file_path, format_old_ext, format_new_ext, index)
  File "/app/code/calibre-web/cps/worker.py", line 377, in _convert_calibre
    nextline = p.stdout.readline()
  File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 49: ordinal not in range(128)
```

**Environment (please complete the following information):**
 - OS: Docker (cloudron, don't think it matters?)
 - Python version: [e.g. python3.6]
 - Calibre-Web version: 0.6.9
 - Docker container: https://git.cloudron.io/cloudron/calibre-web-app/Dockerfile
 - Special Hardware: Standard VPS
 - Browser: Chrome and firefox tested but this is some backend error

**Comment by gramakri** [comment]
OK, setting `LC_ALL=C.UTF-8` fixes the problem. Curiously, even though the PDF converts it is not listed in the dropdown of downloadable options. I will open a separate issue maybe (because other formats do appear).
