### ISSUE TITLE
Add book error => language

### ISSUE THREAD

**Issue by hrxfab** [janeczku/calibre-web#1668]
Hi,

When adding some books the import does not work, I have the following error in the logs:

sqlalchemy.exc.ArgumentError: Object <Languages('**fra**')> is not legal as a SQL literal value

I'm running the latest calibre-web version "nightly build" on a docker image.

Here the full log:
``` 
File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/app/calibre-web/cps/web.py", line 202, in decorated_view
    return login_required(func)(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/app/calibre-web/cps/web.py", line 273, in inner
    return f(*args, **kwargs)
  File "/app/calibre-web/cps/editbooks.py", line 838, in upload
    modif_date |= edit_book_languages(meta.languages, db_book, upload=True)
  File "/app/calibre-web/cps/editbooks.py", line 412, in edit_book_languages
    return modify_database_object(input_l, book.languages, db.Languages, calibre_db.session, 'languages')
  File "/app/calibre-web/cps/editbooks.py", line 108, in modify_database_object
    db_element = db_session.query(db_object).filter(db_filter == add_element).first()
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/sql/operators.py", line 365, in __eq__
    return self.operate(eq, other)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/attributes.py", line 219, in operate
    return op(self.comparator, *other, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/sql/operators.py", line 365, in __eq__
    return self.operate(eq, other)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/properties.py", line 367, in operate
    return op(self.__clause_element__(), *other, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/sql/annotation.py", line 104, in __eq__
    return self.__element.__class__.__eq__(self, other)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/sql/operators.py", line 365, in __eq__
    return self.operate(eq, other)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/sql/elements.py", line 762, in operate
    return op(self.comparator, *other, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/sql/operators.py", line 365, in __eq__
    return self.operate(eq, other)
  File "<string>", line 1, in <lambda>
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/sql/type_api.py", line 67, in operate
    return o[0](self.expr, op, *(other + o[1:]), **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/sql/default_comparator.py", line 105, in _boolean_compare
    obj = _check_literal(expr, op, obj)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/sql/default_comparator.py", line 373, in _check_literal
    return expr._bind_param(operator, other, type_=bindparam_type)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/sql/elements.py", line 4255, in _bind_param
    unique=True,
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/sql/elements.py", line 1234, in __init__
    _compared_to_operator, value
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/sql/type_api.py", line 578, in coerce_compared_value
    _coerced_type = _resolve_value_to_type(value)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/sql/sqltypes.py", line 3038, in _resolve_value_to_type
    "Object %r is not legal as a SQL literal value" % value
sqlalchemy.exc.ArgumentError: Object <Languages('fra')> is not legal as a SQL literal value``
```

**Comment by OzzieIsaacs** [comment]
That's sad.

With this very vague information I see no change for fixing the problem. 
If some books are certain special book, you could send me one book via private e-mail.

**Comment by hrxfab** [comment]
Hi, 

I did some additional tests, if i'm switching the interface in english and "Language of Books" as "Show all", the import is working fine.

**Comment by OzzieIsaacs** [comment]
Thank you this sounds better. I'll try to reproduce it with this information

**Comment by tamet83** [comment]
Hi,
I'm not if it is the same error, but I have a similar error when I try to add a new book.
Here is the screenshot of the interface error message:

![Cattura](https://user-images.githubusercontent.com/7949570/97105094-df3c5a00-16b8-11eb-9065-3ffe267a850d.JPG)

And here the relative log:

```
[2020-10-25 10:46:28,076] DEBUG {cps.web:1790} Profile updated
[2020-10-25 10:49:38,136] DEBUG {cps.uploader:208} Temporary file: /tmp/calibre_web/4dd3e50e0199e7fb1d1e7d8b444647c1
[2020-10-25 10:49:38,145] ERROR {cps.helper:394} Rename title from: /tmp/calibre_web/4dd3e50e0199e7fb1d1e7d8b444647c1 to /root/libri/Unknown/cinque-indagini-romane-per-rocco-schiavone (29): [Errno 18] Invalid cross-device link
[2020-10-25 10:49:38,145] DEBUG {cps.helper:395} [Errno 18] Invalid cross-device link
Traceback (most recent call last):
  File "/root/calibre-web/cps/helper.py", line 377, in update_dir_structure_file
    os.path.normcase(os.path.join(new_path, db_filename)))
  File "/usr/lib/python2.7/os.py", line 199, in renames
    rename(old, new)
OSError: [Errno 18] Invalid cross-device link
[2020-10-25 10:49:38,145] ERROR {cps:1892} Exception on /upload [POST]
Traceback (most recent call last):
  File "/root/calibre-web/vendor/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/root/calibre-web/vendor/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/root/calibre-web/vendor/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/root/calibre-web/vendor/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/root/calibre-web/vendor/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/root/calibre-web/cps/web.py", line 202, in decorated_view
    return login_required(func)(*args, **kwargs)
  File "/root/calibre-web/vendor/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/root/calibre-web/cps/web.py", line 273, in inner
    return f(*args, **kwargs)
  File "/root/calibre-web/cps/editbooks.py", line 874, in upload
    copyfile(coverfile, new_coverpath)
  File "/usr/lib/python2.7/shutil.py", line 97, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 2] No such file or directory: u'/root/libri/Unknown/cinque-indagini-romane-per-rocco-schiavone/cover.jpg'

```

I really don't know how to solve this problem.
Thanks in advance for your help

**Comment by OzzieIsaacs** [comment]
It's something different: `OSError: [Errno 18] Invalid cross-device link`. Your database is on a diffrent hdd than your tempfolder (I'm working on this one)

**Comment by tamet83** [comment]
Ok thank you, but the problem started just with the latest release, before it worked perfectly.
I don't know if this info could help you.

**Comment by OzzieIsaacs** [comment]
That's right, I changed something in the background to make it better work with windows, and this is the outcome of it...

**Comment by tamet83** [comment]
If it could be helpfull, these are the latest update that gave me the problem:

![Cattura](https://user-images.githubusercontent.com/7949570/97105677-157bd880-16bd-11eb-8675-e31fe569c42a.JPG)

**Comment by aroundmyroom** [comment]
Yup since latest version I have also this issue now I try to upload books (prior to one of these versions it was working)

Rename title from: '/tmp/calibre_web/f67f6f889056beb74f72e011d858c77a' to '/media/books/Mr X/My Title (1436)' failed with error: [Errno 18] Invalid cross-device link: '/tmp/calibre_web/f67f6f889056beb74f72e011d858c77a' -> '/media/books/Mr X/My Title (1436)/Title.epub'

indeed the /tmp folder is on a linux folder and the /media/books is a NFS share.

this one was also referenced issue @ #1349
