### ISSUE TITLE
Calibre Web Internal server error - Not using Docker.

### ISSUE THREAD

**Issue by essjayaaa** [janeczku/calibre-web#1679]
**Describe the bug/problem**
A clear and concise description of what the bug is. If you are asking for support, please check our [Wiki](https://github.com/janeczku/calibre-web/wiki) if your question is already answered there.

**To Reproduce**

**Logfile**
Add content of calibre-web.log file or the relevant error, try to reproduce your problem with "debug" log-level to get more output.

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. Windows 10/Raspberry Pi OS]
 - Python version: [e.g. python2.7]
 - Calibre-Web version: [e.g. 0.6.8 or 087c4c59 (git rev-parse --short HEAD)]:
 - Docker container: [None/Technosoft2000/Linuxuser]:
 - Special Hardware: [e.g. Rasperry Pi Zero]
 - Browser: [e.g. Chrome 83.0.4103.97, Safari 13.3.7, Firefox 68.0.1 ESR]

**Additional context**
Add any other context about the problem here. [e.g. access via reverse proxy, database background sync, special database location]

**Comment by essjayaaa** [comment]
Sorry missed off the error code.

---------------------------------------------

Traceback (most recent call last):
File "/usr/lib/python2.7/site-packages/flask/app.py", line 2447, in wsgi_app
response = self.full_dispatch_request()
File "/usr/lib/python2.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/lib/python2.7/site-packages/flask/app.py", line 1821, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/usr/lib/python2.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/lib/python2.7/site-packages/flask/app.py", line 1936, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/volume1/web/calibre-web-master/cps/web.py", line 202, in decorated_view
return login_required(func)(*args, **kwargs)
File "/usr/lib/python2.7/site-packages/flask_login/utils.py", line 272, in decorated_view
return func(*args, **kwargs)
File "/volume1/web/calibre-web-master/cps/web.py", line 982, in index
return render_books_list("newest", sort_param, 1, page)
File "/volume1/web/calibre-web-master/cps/web.py", line 684, in render_books_list
entries, random, pagination = calibre_db.fill_indexpage(page, 0, db.Books, True, order)
File "/volume1/web/calibre-web-master/cps/db.py", line 602, in fill_indexpage
return self.fill_indexpage_with_archived_books(page, pagesize, database, db_filter, order, False, *join)
File "/volume1/web/calibre-web-master/cps/db.py", line 620, in fill_indexpage_with_archived_books
len(query.all()))
File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 3346, in all
return list(self)
File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 3508, in __iter__
return self._execute_and_instances(context)
File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 3530, in _execute_and_instances
querycontext, self._connection_from_session, close_with_result=True
File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 3545, in _get_bind_args
mapper=self._bind_mapper(), clause=querycontext.statement, **kw
File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 3523, in _connection_from_session
conn = self.session.connection(**kw)
File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 1141, in connection
execution_options=execution_options,
File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 1147, in _connection_for_bind
engine, execution_options
File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 409, in _connection_for_bind
self._assert_active()
File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 296, in _assert_active
code="7s2a",
InvalidRequestError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)
(sqlite3.OperationalError) attempt to write a readonly database
[SQL: UPDATE authors SET name=? WHERE authors.id = ?]
[parameters: (u'Adam Gibbsons, Dave ; Kubert, Andy ; Kubert', 30)]
(Background on this error at: http://sqlalche.me/e/13/e3q8) (Background on this error at: http://sqlalche.me/e/13/7s2a)

**Comment by wgibcus** [comment]
"attempt to write a readonly database" 
Are the permissions on your database correct (read/write)?

**Comment by OzzieIsaacs** [comment]
The text you get presented on creating a issue is a form which should be filled out,. The pure error message without any context doesn't help me to figure out the problem.
