### ISSUE TITLE
Permission Denied when "Read in browser" is clicked

### ISSUE THREAD

**Issue by thatoneguy99** [janeczku/calibre-web#169]
I am sure this is a permissions error as per the error in the log. I just don't know where to start.
I am behind a nginx rp on port 80. When I try and read a book "in browser" I get a 500 error and then I see the below in the log. Downloading the book works just fine. Any assistance is much appreciated. I hope I provided enough of the log to help.

`WHERE books.id = ?
 LIMIT ? OFFSET ?
[2017-03-31 19:54:16,686] {/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py:1143} INFO - (4735, 1, 0)
[2017-03-31 19:54:16,688] {/usr/local/lib/python2.7/dist-packages/flask/app.py:1560} ERROR - Exception on /read/4735/epub [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/calibre-web/cps/web.py", line 1573, in read_book
    os.mkdir(book_dir)
OSError: [Errno 13] Permission denied: '/opt/calibre-web/cps/static/4735'
`

**Comment by thatoneguy99** [comment]
Sorry I forgot to mention that I have a sudo user as the owner of /opt/calibre-web/*

**Comment by OzzieIsaacs** [comment]
For each book you open with read in browser, calibre-web creates a subfolder in cps/static with the id of the book (number between 1 and ...) and copies the file to read in that folder. In your case the I'd is 4735. The error indicates that the owner of the process calibre-web has no rights to create this subfolder. So this is related to Linux user rights, as a test you could give '777' permissions to all folders. Downloading books creates no temp folders, so this can work without issues.

**Comment by thatoneguy99** [comment]
Thank you for your asnwer! It is fixed now. I knew what it was but didn't know who to give permissions to and where.
