### ISSUE TITLE
what about this

### ISSUE THREAD

**Issue by wxyhgk** [janeczku/calibre-web#1692]
Internal Server Error
500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
Traceback (most recent call last):
File "/usr/lib/python2.7/site-packages/flask/app.py", line 2447, in wsgi_app
response = self.full_dispatch_request()
File "/usr/lib/python2.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/lib/python2.7/site-packages/flask/app.py", line 1821, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/usr/lib/python2.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/lib/python2.7/site-packages/flask/app.py", line 1936, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/volume1/web/calibre-web-master/cps/web.py", line 195, in decorated_view
return func(*args, **kwargs)
File "/volume1/web/calibre-web-master/cps/web.py", line 268, in inner
return f(*args, **kwargs)
File "/volume1/web/calibre-web-master/cps/editbooks.py", line 702, in upload
if request.method == 'POST' and 'btn-upload' in request.files:
File "/usr/lib/python2.7/site-packages/werkzeug/local.py", line 347, in __getattr__
return getattr(self._get_current_object(), name)
File "/usr/lib/python2.7/site-packages/werkzeug/utils.py", line 90, in __get__
value = self.func(obj)
File "/usr/lib/python2.7/site-packages/werkzeug/wrappers/base_request.py", line 514, in files
self._load_form_data()
File "/usr/lib/python2.7/site-packages/flask/wrappers.py", line 88, in _load_form_data
RequestBase._load_form_data(self)
File "/usr/lib/python2.7/site-packages/werkzeug/wrappers/base_request.py", line 319, in _load_form_data
self._get_stream_for_parsing(), mimetype, content_length, options
File "/usr/lib/python2.7/site-packages/werkzeug/formparser.py", line 232, in parse
return parse_func(self, stream, mimetype, content_length, options)
File "/usr/lib/python2.7/site-packages/werkzeug/formparser.py", line 131, in wrapper
return f(self, stream, *args, **kwargs)
File "/usr/lib/python2.7/site-packages/werkzeug/formparser.py", line 253, in _parse_multipart
form, files = parser.parse(stream, boundary, content_length)
File "/usr/lib/python2.7/site-packages/werkzeug/formparser.py", line 584, in parse
return self.cls(form), self.cls(files)
File "/usr/lib/python2.7/site-packages/werkzeug/datastructures.py", line 419, in __init__
for key, value in mapping or ():
File "/usr/lib/python2.7/site-packages/werkzeug/formparser.py", line 582, in <genexpr>
form = (p[1] for p in formstream if p[0] == "form")
File "/usr/lib/python2.7/site-packages/werkzeug/formparser.py", line 555, in parse_parts
_write(ell)
File "/usr/lib/python2.7/tempfile.py", line 626, in write
rv = file.write(s)
IOError: [Errno 28] No space left on device
Please report this issue with all related information: Create Issue
Return to Home

**Comment by wgibcus** [comment]
"No space left on device". Do you have enough disk space?

**Comment by wxyhgk** [comment]
> "No space left on device". Do you have enough disk space?

yes，I have 。Now I install it again，it  is normal。
