### ISSUE TITLE
server always down.

### ISSUE THREAD

**Issue by vagra** [janeczku/calibre-web#1699]
**Describe the bug/problem**
my server will be  crashes almost every day these days, for unknown reasons. The contents of the log files after the downtime are similar.

**To Reproduce**

**Logfile**

```
[2020-11-06 13:04:08,529] ERROR {tornado.application:67} Uncaught exception
Traceback (most recent call last):
  File "/site/calibre-web/vendor/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/site/calibre-web/vendor/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/site/calibre-web/vendor/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/site/calibre-web/vendor/flask/_compat.py", line 39, in reraise
    raise value
  File "/site/calibre-web/vendor/flask/app.py", line 1948, in full_dispatch_request
    rv = self.preprocess_request()
  File "/site/calibre-web/vendor/flask/app.py", line 2242, in preprocess_request
    rv = func()
  File "/site/calibre-web/cps/web.py", line 294, in before_request
    if current_user.is_authenticated:
  File "/site/calibre-web/vendor/werkzeug/local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
  File "/site/calibre-web/vendor/werkzeug/local.py", line 306, in _get_current_object
    return self.__local()
  File "/site/calibre-web/vendor/flask_login/utils.py", line 26, in <lambda>
    current_user = LocalProxy(lambda: _get_user())
  File "/site/calibre-web/vendor/flask_login/utils.py", line 346, in _get_user
    current_app.login_manager._load_user()
  File "/site/calibre-web/vendor/flask_login/login_manager.py", line 336, in _load_user
    return self._update_request_context_with_user(user)
  File "/site/calibre-web/vendor/flask_login/login_manager.py", line 296, in _update_request_context_with_user
    ctx.user = self.anonymous_user() if user is None else user
  File "/site/calibre-web/cps/ub.py", line 279, in __init__
    self.loadSettings()
  File "/site/calibre-web/cps/ub.py", line 282, in loadSettings
    data = session.query(User).filter(User.role.op('&')(constants.ROLE_ANONYMOUS) == constants.ROLE_ANONYMOUS)\
  File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/orm/query.py", line 3402, in first
    ret = list(self[0:1])
  File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/orm/query.py", line 3176, in __getitem__
    return list(res)
  File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/orm/query.py", line 3508, in __iter__
    return self._execute_and_instances(context)
  File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/orm/query.py", line 3530, in _execute_and_instances
    querycontext, self._connection_from_session, close_with_result=True
  File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/orm/query.py", line 3545, in _get_bind_args
    mapper=self._bind_mapper(), clause=querycontext.statement, **kw
  File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/orm/query.py", line 3523, in _connection_from_session
    conn = self.session.connection(**kw)
  File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/orm/session.py", line 1141, in connection
    execution_options=execution_options,
  File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/orm/session.py", line 1147, in _connection_for_bind
    engine, execution_options
  File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/orm/session.py", line 409, in _connection_for_bind
    self._assert_active()
  File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/orm/session.py", line 283, in _assert_active
    "This session is in 'prepared' state; no further "
sqlalchemy.exc.InvalidRequestError: This session is in 'prepared' state; no further SQL can be emitted within this transaction.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/site/calibre-web/vendor/tornado/http1connection.py", line 273, in _read_message
    delegate.finish()
  File "/site/calibre-web/vendor/tornado/httpserver.py", line 280, in finish
    self.request_callback(self.request)
  File "/site/calibre-web/vendor/tornado/wsgi.py", line 114, in __call__
    WSGIContainer.environ(request), start_response
  File "/site/calibre-web/vendor/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/site/calibre-web/cps/reverseproxy.py", line 81, in __call__
    return self.app(environ, start_response)
  File "/site/calibre-web/vendor/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/site/calibre-web/vendor/flask/app.py", line 1879, in handle_exception
    server_error = handler(server_error)
  File "/site/calibre-web/cps/web.py", line 108, in internal_error
    instance=config.config_calibre_web_title
  File "/site/calibre-web/vendor/flask/templating.py", line 136, in render_template
    ctx.app.update_template_context(context)
  File "/site/calibre-web/vendor/flask/app.py", line 838, in update_template_context
    context.update(func())
  File "/site/calibre-web/vendor/flask_login/utils.py", line 379, in _user_context_processor
    return dict(current_user=_get_user())
  File "/site/calibre-web/vendor/flask_login/utils.py", line 346, in _get_user
    current_app.login_manager._load_user()
  File "/site/calibre-web/vendor/flask_login/login_manager.py", line 336, in _load_user
    return self._update_request_context_with_user(user)
  File "/site/calibre-web/vendor/flask_login/login_manager.py", line 296, in _update_request_context_with_user
    ctx.user = self.anonymous_user() if user is None else user
  File "/site/calibre-web/cps/ub.py", line 279, in __init__
    self.loadSettings()
  File "/site/calibre-web/cps/ub.py", line 282, in loadSettings
    data = session.query(User).filter(User.role.op('&')(constants.ROLE_ANONYMOUS) == constants.ROLE_ANONYMOUS)\
  File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/orm/query.py", line 3402, in first
    ret = list(self[0:1])
  File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/orm/query.py", line 3176, in __getitem__
    return list(res)
  File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/orm/query.py", line 3508, in __iter__
    return self._execute_and_instances(context)
  File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/orm/query.py", line 3530, in _execute_and_instances
    querycontext, self._connection_from_session, close_with_result=True
  File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/orm/query.py", line 3545, in _get_bind_args
    mapper=self._bind_mapper(), clause=querycontext.statement, **kw
  File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/orm/query.py", line 3523, in _connection_from_session
    conn = self.session.connection(**kw)
  File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/orm/session.py", line 1141, in connection
    execution_options=execution_options,
  File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/orm/session.py", line 1147, in _connection_for_bind
    engine, execution_options
  File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/orm/session.py", line 409, in _connection_for_bind
    self._assert_active()
  File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/orm/session.py", line 283, in _assert_active
    "This session is in 'prepared' state; no further "
sqlalchemy.exc.InvalidRequestError: This session is in 'prepared' state; no further SQL can be emitted within this transaction.

```

**Environment (please complete the following information):**
 - OS: CentOS 7
 - Python version: python 3.6
 - Calibre-Web version: git HEAD

**Comment by vagra** [comment]
https://stackoverflow.com/questions/23301968/invalid-transaction-persisting-across-requests

**Comment by vagra** [comment]
I pull the latest code of GitHub(0.6.9), and upgraded the requirements.  cps no longer reports this error. This issue seems to have been solved.
