### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'last_modified'

### ISSUE THREAD

**Issue by timanrebel** [janeczku/calibre-web#1702]
**Describe the bug/problem**
I was able to sync with Kobo. I removed some of the collection I previously created on the Kobo and I marked a book as finished. Afterwards I could no longer sync. Kobo returns an Sync Failed. Please try again.

I tried deleting the book I marked as finished on the Kobo, but that does not solve my problem.

**To Reproduce**
1. Sync Kobo with Kobo Sync
2. See error in Calibre-web Logfile viewer

**Logfile**
```
[2020-11-07 10:17:09,857] DEBUG {cps.kobo:928} Kobo: Received unproxied request, changed request port to external server port
[2020-11-07 10:17:09,858] DEBUG {cps.kobo:938} Kobo: Received unproxied request, changed request url to http://10.0.1.32:8083
[2020-11-07 10:17:09,907] DEBUG {cps.kobo:851} Unimplemented User Request received: http://10.0.1.32/kobo/018f296a5372a21f366b2f083487e108/v1/user/profile
[2020-11-07 10:17:10,215] DEBUG {cps.kobo:851} Unimplemented User Request received: http://10.0.1.32/kobo/018f296a5372a21f366b2f083487e108/v1/user/loyalty/benefits
[2020-11-07 10:17:10,398] DEBUG {cps.kobo:864} Unimplemented Products Request received: http://10.0.1.32/kobo/018f296a5372a21f366b2f083487e108/v1/products/books/subscriptions
[2020-11-07 10:17:10,649] DEBUG {cps.kobo:851} Unimplemented User Request received: http://10.0.1.32/kobo/XXX/v1/analytics/gettests
[2020-11-07 10:17:10,929] DEBUG {cps.kobo:449} Received Kobo tag update request on a collection unknown to CalibreWeb
[2020-11-07 10:17:11,175] DEBUG {cps.kobo:449} Received Kobo tag update request on a collection unknown to CalibreWeb
[2020-11-07 10:17:11,416] DEBUG {cps.kobo:449} Received Kobo tag update request on a collection unknown to CalibreWeb
[2020-11-07 10:17:11,637] DEBUG {cps.kobo:449} Received Kobo tag update request on a collection unknown to CalibreWeb
[2020-11-07 10:17:11,976] DEBUG {cps.kobo:449} Received Kobo tag update request on a collection unknown to CalibreWeb
[2020-11-07 10:17:12,275] DEBUG {cps.kobo:449} Received Kobo tag update request on a collection unknown to CalibreWeb
[2020-11-07 10:17:12,562] DEBUG {cps.kobo:449} Received Kobo tag update request on a collection unknown to CalibreWeb
[2020-11-07 10:17:12,822] DEBUG {cps.kobo:449} Received Kobo tag update request on a collection unknown to CalibreWeb
[2020-11-07 10:17:13,071] DEBUG {cps.kobo:449} Received Kobo tag update request on a collection unknown to CalibreWeb
[2020-11-07 10:17:13,320] DEBUG {cps.kobo:449} Received Kobo tag update request on a collection unknown to CalibreWeb
[2020-11-07 10:17:13,546] DEBUG {cps.kobo:449} Received Kobo tag update request on a collection unknown to CalibreWeb
[2020-11-07 10:17:13,816] DEBUG {cps.kobo:449} Received Kobo tag update request on a collection unknown to CalibreWeb
[2020-11-07 10:17:14,356] DEBUG {cps.kobo:449} Received Kobo tag update request on a collection unknown to CalibreWeb
[2020-11-07 10:17:14,595] DEBUG {cps.kobo:449} Received Kobo tag update request on a collection unknown to CalibreWeb
[2020-11-07 10:17:14,815] DEBUG {cps.kobo:449} Received Kobo tag update request on a collection unknown to CalibreWeb
[2020-11-07 10:17:15,047] DEBUG {cps.kobo:449} Received Kobo tag update request on a collection unknown to CalibreWeb
[2020-11-07 10:17:15,278] DEBUG {cps.kobo:449} Received Kobo tag update request on a collection unknown to CalibreWeb
[2020-11-07 10:17:15,497] DEBUG {cps.kobo:449} Received Kobo tag update request on a collection unknown to CalibreWeb
[2020-11-07 10:17:15,860] DEBUG {cps.kobo:449} Received Kobo tag update request on a collection unknown to CalibreWeb
[2020-11-07 10:17:16,086] DEBUG {cps.kobo:449} Received Kobo tag update request on a collection unknown to CalibreWeb
[2020-11-07 10:17:16,315]  INFO {cps.kobo:130} Kobo library sync request received.
[2020-11-07 10:17:16,315] DEBUG {cps.kobo:132} Kobo: Received unproxied request, changed request port to external server port
[2020-11-07 10:17:16,417] ERROR {cps:1892} Exception on /kobo/XXX/v1/library/sync [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/app/calibre-web/cps/kobo_auth.py", line 112, in inner
    return f(*args, **kwargs)
  File "/app/calibre-web/cps/web.py", line 253, in inner
    return f(*args, **kwargs)
  File "/app/calibre-web/cps/kobo.py", line 212, in HandleSyncRequest
    "ReadingState": get_kobo_reading_state_response(book, kobo_reading_state)
  File "/app/calibre-web/cps/kobo.py", line 740, in get_kobo_reading_state_response
    "StatusInfo": get_status_info_response(kobo_reading_state.book_read_link),
  File "/app/calibre-web/cps/kobo.py", line 748, in get_status_info_response
    "LastModified": convert_to_kobo_timestamp_string(book_read.last_modified),
AttributeError: 'NoneType' object has no attribute 'last_modified'
```

**Expected behavior**
I can not sync with Kobo

**Environment (please complete the following information):**
 - OS: Synology DSM 6
 - Python version: python3.7
 - Calibre-Web version: 11/1/20, 5:25 PM
 - Docker container: Linuxuser
 - Special Hardware: Synology NAS
 - Browser: Safari 14

**Additional context**
Nothing

**Comment by timanrebel** [comment]
The problem might be different. I deleted some book via Calibre-web, but although the files were deleted, the entries in the database were not. I run linuxserver/calibre next to Calibre-web on my Synology, so maybe the database is locked by Calibre?

When I deleted the books with Calibre, I was able to sync again.

**Comment by OzzieIsaacs** [comment]
The errormessages hints to a table in the database which isn't filled properly, with deleting the books you also deleted this entries (or at least made them no longer part of the sync). Could be related to each other

**Comment by timanrebel** [comment]
Yes, I think it was related. Not sure if this is something you can fix after one instance. Shall I close the issue?

**Comment by OzzieIsaacs** [comment]
I take a look at it, the exception can be catched and transformed into a warning message
