### ISSUE TITLE
Database locked

### ISSUE THREAD

**Issue by dr400** [janeczku/calibre-web#1709]
**Describe the bug/problem**
When Calibre database is locked, no access from calibre-web and this is displayed : 

```
Internal Server Error
500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
Traceback (most recent call last):
File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
cursor, statement, parameters, context
File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/default.py", line 593, in do_execute
cursor.execute(statement, parameters)
sqlite3.OperationalError: database is locked
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2447, in wsgi_app
response = self.full_dispatch_request()
File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1952, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1821, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 39, in reraise
raise value
File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1950, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1936, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/app/calibre-web/cps/web.py", line 197, in decorated_view
return login_required(func)(*args, **kwargs)
File "/usr/local/lib/python3.6/dist-packages/flask_login/utils.py", line 272, in decorated_view
return func(*args, **kwargs)
File "/app/calibre-web/cps/web.py", line 621, in index
entries, random, pagination = calibre_db.fill_indexpage(page, db.Books, True, [db.Books.timestamp.desc()])
File "/app/calibre-web/cps/db.py", line 549, in fill_indexpage
return self.fill_indexpage_with_archived_books(page, database, db_filter, order, False, *join)
File "/app/calibre-web/cps/db.py", line 566, in fill_indexpage_with_archived_books
entries = query.order_by(*order).offset(off).limit(self.config.config_books_per_page).all()
File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/query.py", line 3373, in all
return list(self)
File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/query.py", line 3535, in __iter__
return self._execute_and_instances(context)
File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/query.py", line 3560, in _execute_and_instances
result = conn.execute(querycontext.statement, self._params)
File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 1011, in execute
return meth(self, multiparams, params)
File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
return connection._execute_clauseelement(self, multiparams, params)
File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 1130, in _execute_clauseelement
distilled_params,
File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 1317, in _execute_context
e, statement, parameters, cursor, context
File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 1511, in _handle_dbapi_exception
sqlalchemy_exception, with_traceback=exc_info[2], from_=e
File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/util/compat.py", line 182, in raise_
raise exception
File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
cursor, statement, parameters, context
File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/default.py", line 593, in do_execute
cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked
[SQL: SELECT books.id AS books_id, books.title AS books_title, books.sort AS books_sort, books.author_sort AS books_author_sort, books.timestamp AS books_timestamp, books.pubdate AS books_pubdate, books.series_index AS books_series_index, books.last_modified AS books_last_modified, books.path AS books_path, books.has_cover AS books_has_cover, books.uuid AS books_uuid, books.isbn AS books_isbn, books.flags AS books_flags
FROM books
WHERE 1 = 1 ORDER BY books.timestamp DESC
LIMIT ? OFFSET ?]
[parameters: (90, 0)]
(Background on this error at: http://sqlalche.me/e/13/e3q8)`
```

**To Reproduce**
lock calibre database (/books)

**Expected behavior**
Is it possible to present a more userfriendly webpage or to even try to kill calibre lockup of the database ?

Thx in advance

**Comment by OzzieIsaacs** [comment]
How do you look the database?

**Comment by dr400** [comment]
> How do you look the database?

I don't but calibre does it when adding new books or when accessing the db whenever it needs to. It should not take long most of the time but for whatever reason calibre does not release the db, it stays locked and calibre-web crashes (at least, that is my perception of the bug)

**Comment by OzzieIsaacs** [comment]
I can't reproduce this if I'm access the database with calibre while calibre-web is running everything works fine

**Comment by DennisYildirim** [comment]
Yet another unresolved github entry with a #closed tag :D Can't believe this people. :D We will need some qualifications tests for Github memberships i guess. They should not let people to throw scam like this everywhere. Clearly the problem is still happening. I'm having the same issue, and all the bug entries are closed :D As if someone over there does not even bother and furiously clicks closed on every post :D

**Comment by stevenhorner** [comment]
I know this is very old, but I've seen lots of people reporting the same or similar errors and I finally fixed mine. Hope anyone searching for database locks with Calibre-web finds my solution.

In my case when mounting the cifs/smb share that holds my books and calibre database `metadata.db` I had to use the option `nobrl` which is  no byte range locks, basically it appears many devices don't handle locking very well especially NAS devices.

An example mount would be:
`sudo mount -t cifs -o nobrl,username=myuser,uid=1000,gid=1000 //192.168.0.20/books /media/books`

You will likely be prompted for the password for the share, you could also enter it in the command above but for testing purposes I have omitted the option.

You may also need to install cifs-utils which can be done on Debian based Linux with:
`sudo apt-get install cifs-utils`

You would really want to setup your mounts in fstab if using Ubuntu or other Debian based Linux so they persist but the above command would allow you to test.

**Comment by lucasmarcel** [comment]
Thanks @stevenhorner, that's exactly the problem I was having. After upgrading my Synology NAS to version 7, mounting shared started failing due to NTLMv1 now being disabled by default. I fixed the mount command to use NTLMv2 and shares became accessible again but Calibre would complain of the database being locked. Adding the nobrl option fixed that problem too.

**Comment by h4rib0** [comment]
@stevenhorner Thank you! 
I wasted so much time till I found your solution.

Just one hint:

Incorrect Use of -o: The -o option is not necessary in the fstab file. Options should be listed directly after the filesystem type (in this case, cifs).

**Comment by caver01** [comment]
This nobrl option worked for me too with Calibre server mounting a CIFS on my Synology NAS. I too had problems with DS7 and mounting my media share with SONOS that I solved a year ago (I don't remember how, but I think it was similar to @lucasmarcel's description. In any case, THANKS SO MUCH @stevenhorner for the nobrl. I was pulling my hair out trying to get past a database locking issue. Much appreciated!

**Comment by haydonryan** [comment]
me three. I did something different though. mounted the volume in docker via SMB:

````
volumes:
  calibre-library:
    driver_opts:
      type: cifs
      o: "username=yourusername,password=yourpassword,vers=3.0,nobrl,uid=1001,gid=1003"
      device: "//NAS-IP/Data/Repositories/calibre/"
```
