### ISSUE TITLE
Kobo Sync error: AttributeError: 'NoneType' object has no attribute 'last_modified'

### ISSUE THREAD

**Issue by cerbaire** [janeczku/calibre-web#1719]
**Describe the bug/problem**
Cannot sync from device

**To Reproduce**
Connect kobo on the computer
Modify api_endpoint with the one provided by calibre-web (local network)
Eject kobo
Restart kobo
Sync

**Logfile**
[2020-11-21 16:25:14,942]  INFO {cps.kobo:917} Init
[2020-11-21 16:25:15,093] DEBUG {cps.kobo:932} Kobo: Received unproxied request, changed request port to external server port
[2020-11-21 16:25:15,093] DEBUG {cps.kobo:942} Kobo: Received unproxied request, changed request url to http://192.168.1.25:8083
[2020-11-21 16:25:15,171] DEBUG {cps.kobo:855} Unimplemented User Request received: http://192.168.1.25/kobo/aaa/v1/user/profile
[2020-11-21 16:25:15,444] DEBUG {cps.kobo:855} Unimplemented User Request received: http://192.168.1.25/kobo/aaa/v1/user/loyalty/benefits
[2020-11-21 16:25:15,610] DEBUG {cps.kobo:855} Unimplemented User Request received: http://192.168.1.25/kobo/7b21802c971c98ff1247ba6124bea7c3/v1/analytics/gettests
[2020-11-21 16:25:15,939]  INFO {cps.kobo:646} Book 30d7ce29-dc6a-4828-a001-eaf3f5c2e038 not found in database
[2020-11-21 16:25:16,180]  INFO {cps.kobo:134} Kobo library sync request received.
[2020-11-21 16:25:16,180] DEBUG {cps.kobo:136} Kobo: Received unproxied request, changed request port to external server port
[2020-11-21 16:25:40,531] ERROR {cps:1892} Exception on /kobo/aaa/v1/library/sync [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/app/calibre-web/cps/kobo_auth.py", line 112, in inner
    return f(*args, **kwargs)
  File "/app/calibre-web/cps/web.py", line 253, in inner
    return f(*args, **kwargs)
  File "/app/calibre-web/cps/kobo.py", line 216, in HandleSyncRequest
    "ReadingState": get_kobo_reading_state_response(book, kobo_reading_state)
  File "/app/calibre-web/cps/kobo.py", line 744, in get_kobo_reading_state_response
    "StatusInfo": get_status_info_response(kobo_reading_state.book_read_link),
  File "/app/calibre-web/cps/kobo.py", line 752, in get_status_info_response
    "LastModified": convert_to_kobo_timestamp_string(book_read.last_modified),
AttributeError: 'NoneType' object has no attribute 'last_modified'

**Expected behavior**
Kobo sync to work

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. Windows 10/Raspberry Pi OS]
 - Python version: [e.g. python2.7]
 - Calibre-Web version: latest version on master as per today (11/20/20, 8:35 PM)
 - Docker container: Linuxuser:
 - Special Hardware: Synology 718+
 - Browser: [e.g. Chrome 83.0.4103.97, Safari 13.3.7, Firefox 68.0.1 ESR]
 - Kobo Libra H2O

**Additional context**
Add any other context about the problem here. [e.g. access via reverse proxy, database background sync, special database location]

**Comment by OzzieIsaacs** [comment]
I tried to reproduce the error, but I didn't succeed. 
Your app.db file has some invalid entries, currently I don't see how this could have happened. 

There are some possibilities:
1) You could send me the app.db file (I don't need passwords, I can create my own user) via private email (listed on my profile page) and I have a look at it
2) You could delete the app.db file and start allover (I currently see no change how to get this problem, so I'm pretty sure it's not coming again)
3) You open the app.db file with a database browser (like sqlitebrowser) and have a look at the tables, my biggest suspect is a missing column in kobo_reading_state
![grafik](https://user-images.githubusercontent.com/6438895/101168692-16007b00-363c-11eb-8198-a0ea04489eb7.png)
or book_read_link
![grafik](https://user-images.githubusercontent.com/6438895/101168766-34667680-363c-11eb-83eb-217305e61268.png)

**Comment by cerbaire** [comment]
Thanks for your reponse. I reset calibre-web and it is now working correctly.
