### ISSUE TITLE
Active Directory Authentication and Import Users

### ISSUE THREAD

**Issue by mesfinteshome** [janeczku/calibre-web#1733]
Greetings,
First of all I would like to appreciate your work on this and making it open source. I like your work on calibre-web. Have been trying to integrate calibre-web for Active Directory Authentication
**To Reproduce**
1. Go to Admin-> config
2. Click on _"Import Users"

I am running it on Debian 9.3 and running the nightly build of Calibre-web but every time I try to Import users I get the following error
"[2020-11-28 16:42:36,188] ERROR {cps.web:318} argument of type 'int' is not iterable
Traceback (most recent call last):
  File "/home/user/calibre-web/vendor/flask_simpleldap/__init__.py", line 95, in initialize
    current_app.config['LDAP_PORT']))
  File "/usr/local/lib/python3.5/dist-packages/ldap/functions.py", line 96, in initialize
    fileno=fileno, **kwargs
  File "/usr/local/lib/python3.5/dist-packages/ldap/ldapobject.py", line 115, in __init__
    self._l = ldap.functions._ldap_function_call(ldap._ldap_module_lock,_ldap.initialize,uri)
  File "/usr/local/lib/python3.5/dist-packages/ldap/functions.py", line 55, in _ldap_function_call
    result = func(*args,**kwargs)
ldap.LDAPError: (2, 'No such file or directory')
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/user/calibre-web/cps/web.py", line 316, in import_ldap_users
    new_users = services.ldap.get_group_members(config.config_ldap_group_name)
  File "/home/user/calibre-web/cps/services/simpleldap.py", line 97, in get_group_members
    return _ldap.get_group_members(group)
  File "/home/user/calibre-web/vendor/flask_simpleldap/__init__.py", line 256, in get_group_members
    conn = self.bind
  File "/home/user/calibre-web/vendor/flask_simpleldap/__init__.py", line 115, in bind
    conn = self.initialize
  File "/home/user/calibre-web/vendor/flask_simpleldap/__init__.py", line 104, in initialize
    raise LDAPException(self.error(e.args))
  File "/home/user/calibre-web/vendor/flask_simpleldap/__init__.py", line 276, in error
    if 'desc' in e:
TypeError: argument of type 'int' is not iterable

Here is my ldap config
Login type: Use LDAP Authentication
LDAP Server Host Name or IP Address: myserver.mydomain
LDAP Server Port: 389
LDAP Encryption: None
LDAP Authentication: Simple
LDAP Administrator Name: CN="My Name",OU=myOU,DC=mydomain,DC=net
LDAP Administrator Password: "My Password"
LDAP Distinguished Name (DN): DC=mydomain,DC=net

LDAP GROUP Object filter: (&(objectclass=groupOfUniqueNames)(cn=%s))
LDAP Group Name: Domain Users
LDAP Group Members Field: (I have tried 'cn', 'member', 'memberOf'...)

What can be the problem? I appreciate your help

**Comment by mesfinteshome** [comment]
This is the latest I got after changing some LDAP configuration above

AttributeError: 'set' object has no attribute 'items'
[2020-11-28 19:19:26,237] ERROR {cps.web:318} 'set' object has no attribute 'items'
Traceback (most recent call last):
  File "/home/user/calibre-web/cps/web.py", line 316, in import_ldap_users
    new_users = services.ldap.get_group_members(config.config_ldap_group_name)
  File "/home/user/calibre-web/cps/services/simpleldap.py", line 97, in get_group_members
    return _ldap.get_group_members(group)
  File "/home/user/calibre-web/vendor/flask_simpleldap/__init__.py", line 256, in get_group_members
    conn = self.bind
  File "/home/user/calibre-web/vendor/flask_simpleldap/__init__.py", line 115, in bind
    conn = self.initialize
  File "/home/user/calibre-web/vendor/flask_simpleldap/__init__.py", line 98, in initialize
    conn = self._set_custom_options(conn)
  File "/home/user/calibre-web/vendor/flask_simpleldap/__init__.py", line 80, in _set_custom_options
    for k, v in options.items():
AttributeError: 'set' object has no attribute 'items'

**Comment by mesfinteshome** [comment]
Doing this _ldapsearch -H ldap://hostname -D "CN=my name,OU=###,OU=####,OU=####,DC=####,DC=###" -W -b "DC=####,DC=###" '(&(objectclass=group)(cn=Domain Users))' member_ from the command prompt returns some domain users.

**Comment by jackhadrill** [comment]
I am also experiencing this issue.

**Comment by OzzieIsaacs** [comment]
Could you please try to update it to the newest nightly commit. It's possible that the last error message was my fault and it is fixed now.
If you have still problems afterwards, I need the settings for the last version.

**Comment by mesfinteshome** [comment]
Thank you Ozzie,
I am able to login with an account I created with my AD credentials. However, import LDAP users says it is successful but no AD user imported in the users list.

**Comment by OzzieIsaacs** [comment]
Same as #1697?

**Comment by OzzieIsaacs** [comment]
The message on import is changed it now tells you how many users are imported (which should be 0 in this case)

Please try to update to the newest commit version, there is now a new config option to customize the file which is taken during user import:
![grafik](https://user-images.githubusercontent.com/6438895/101048039-9cf11d00-3582-11eb-92e4-a7319c77fde9.png)
You should enter something like: "CN=%s"

**Comment by OzzieIsaacs** [comment]
I changed the name of the first new field, it's now: "LDAP Member User Filter Detection"

**Comment by mesfinteshome** [comment]
Hi Ozzie,
I applied the latest commit and changed the settings....import users gets stack on 
![image](https://user-images.githubusercontent.com/41523904/101075985-cd04e400-35b3-11eb-9cea-783f118c65e1.png)
and I see the following error message in the logs:
[2020-12-03 21:55:03,904] ERROR {cps:1892} Exception on /import_ldap_users [GET]
Traceback (most recent call last):
  File "/calibre-web/vendor/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/calibre-web/vendor/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/calibre-web/vendor/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/calibre-web/vendor/flask/_compat.py", line 39, in reraise
    raise value
  File "/calibre-web/vendor/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/calibre-web/vendor/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/calibre-web/vendor/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/calibre-web/cps/web.py", line 230, in inner
    return f(*args, **kwargs)
  File "/calibre-web/cps/web.py", line 346, in import_ldap_users
    user_data = services.ldap.get_object_details(user=user_identifier)
  File "/calibre-web/cps/services/simpleldap.py", line 89, in get_object_details
    return _ldap.get_object_details(user)
  File "/calibre-web/vendor/flask_simpleldap/__init__.py", line 198, in get_object_details
    for k, v in list(records[0][1].items()):
AttributeError: 'list' object has no attribute 'items'

**Comment by OzzieIsaacs** [comment]
I'm working on it

**Comment by OzzieIsaacs** [comment]
Please try with newest commit

**Comment by mesfinteshome** [comment]
I am gonna test this tomorrow and give you updates. Getting a little bit late here...Thank you for persistently working on this. You are the best!

**Comment by mesfinteshome** [comment]
The import users is working now but only importing very few users even though I ran Import users again doesn't import any other new users.

**Comment by OzzieIsaacs** [comment]
Please provide error/warning messages you get

**Comment by mesfinteshome** [comment]
DEBUG {cps.web:322} LDAP empty response  ---- From the logs
Error: No user returned in response of LDAP server ------ From the interface

**Comment by OzzieIsaacs** [comment]
Calibre-Web is doing a query to get the members of the group to import using beside admin account and so on the following 2 settings, with example values
'config_ldap_group_object_filter': '(& (objectclass=groupofnames)(cn=%s))',
'config_ldap_group_name':'cps'
resulting in a LDAP query: '(& (objectclass=groupofnames)(cn=cps))', as response to this request no records are returned.

This is not matching to your statement that only 15 users are imported??

**Comment by mesfinteshome** [comment]
(& (objectclass=group)(cn=%s))
Domain Users

I get the same number of users and the same users when I do this from linux CLI
sudo ldapsearch -H ldap://myserver -D "CN=My Name,OU=myou1,OU=myou2,OU=myou3,DC=mydomain,DC=local" -W -b "DC=mydomain,DC=locall" '(&(objectclass=group)(cn=Domain Users))' member

**Comment by mesfinteshome** [comment]
I changed the group from "Domain Users" to another one I created and I got the error below

[2020-12-04 16:45:12,972] ERROR {cps:1892} Exception on /import_ldap_users [GET]
Traceback (most recent call last):
  File "/calibre-web/cps/web.py", line 344, in import_ldap_users
    user_data = services.ldap.get_object_details(user=user_identifier, query_filter=query_filter)
  File "/calibre-web/cps/services/simpleldap.py", line 89, in get_object_details
    return _ldap.get_object_details(user, query_filter=query_filter)
  File "/calibre-web/vendor/flask_simpleldap/__init__.py", line 198, in get_object_details
    for k, v in list(records[0][1].items()):
AttributeError: 'list' object has no attribute 'items'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/calibre-web/vendor/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/calibre-web/vendor/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/calibre-web/vendor/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/calibre-web/vendor/flask/_compat.py", line 39, in reraise
    raise value
  File "/calibre-web/vendor/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/calibre-web/vendor/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/calibre-web/vendor/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/calibre-web/cps/web.py", line 230, in inner
    return f(*args, **kwargs)
  File "/calibre-web/cps/web.py", line 346, in import_ldap_users
    log.exception(e)
UnboundLocalError: local variable 'e' referenced before assignment

**Comment by OzzieIsaacs** [comment]
Pleas try newest commit
