### ISSUE TITLE
Cannot download book from OPDS feed

### ISSUE THREAD

**Issue by maaldheefee** [janeczku/calibre-web#1739]
Cannot download book from OPDS feed (ex: /opds/download/1410/epub/). Covers and everything else seems to work.

**To Reproduce**
1. Download a book from OPDS feed.

**Logfile**

```
ERROR {cps:1891} Exception on /opds/download/1410/epub/ [GET]
Traceback (most recent call last):
  File "/root/calibre-web/vendor/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/root/calibre-web/vendor/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/root/calibre-web/vendor/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/root/calibre-web/vendor/flask/_compat.py", line 39, in reraise
    raise value
  File "/root/calibre-web/vendor/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/root/calibre-web/vendor/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/root/calibre-web/cps/opds.py", line 53, in decorated
    return f(*args, **kwargs)
  File "/root/calibre-web/cps/opds.py", line 389, in opds_download_link
    if not load_user_from_request(request).role_download():
AttributeError: 'NoneType' object has no attribute 'role_download'
```

**Expected behavior**
The EPUB file should download.

**Environment (please complete the following information):**

 - OS: Ubuntu 20.04 (LTS)
 - Python version: 3.8.5
 - Calibre-Web version: f18836be
 - Docker container: None
 - Browser: Any

**Additional context**
Works in the web app. (ex: /download/1410/epub/1410.epub)
Works on local Windows environment.

**Comment by OzzieIsaacs** [comment]
This error occurs if accessed only with anonymous browsing enabled, if valid credentials for a user are provided everything worked fine.

**Comment by OzzieIsaacs** [comment]
Thanks for the report. I'm sorry, I can't reproduce the behaviour and need therefore more details:
Do you have enabled one or more of these options, and which one:
- LDAP login
- Reverse proxy authentication
- Anonymous Browsing

Is the user you are using having download rights?
How do you access the server? (localhost, local network) 
Which browser/opds reader did you use? 
Is it happening all the time, even if you start with a fresh browser session, in private mode?
