### ISSUE TITLE
TypeError: join() missing 1 required positional argument: 'target'

### ISSUE THREAD

**Issue by LouiseLo02** [janeczku/calibre-web#1748]
When I updated to the latest commit, it doesn't give any errors until I try to login.
Then I get the following error:

**Logfile**
```
[2020-12-10 01:22:58,730] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/louise/LIBRARY/calibre-web/cps/web.py", line 202, in decorated_view
    return login_required(func)(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/flask_login/utils.py", line 228, in decorated_view
    return func(*args, **kwargs)
  File "/home/louise/LIBRARY/calibre-web/cps/web.py", line 1026, in index
    return render_books_list("newest", sort_param, 1, page)
  File "/home/louise/LIBRARY/calibre-web/cps/web.py", line 728, in render_books_list
    entries, random, pagination = calibre_db.fill_indexpage(page, 0, db.Books, True, order)
  File "/home/louise/LIBRARY/calibre-web/cps/db.py", line 602, in fill_indexpage
    return self.fill_indexpage_with_archived_books(page, pagesize, database, db_filter, order, False, *join)
  File "/home/louise/LIBRARY/calibre-web/cps/db.py", line 615, in fill_indexpage_with_archived_books
    query = self.session.query(database) \
TypeError: join() missing 1 required positional argument: 'target'
```

I have tried both python 3.8 and 3.9. running on linux mint 19

**Comment by OzzieIsaacs** [comment]
Which version of sqlalchemy do you use? (`pip3 freeze`)

**Comment by OzzieIsaacs** [comment]
If it‘s the beta version 1.4 (which it will be), please downgrade to the latest supported version 1.3.xx

**Comment by LouiseLo02** [comment]
> Which version of sqlalchemy do you use? (`pip3 freeze`)

pip3 freeze | grep SQL
SQLAlchemy==1.3.20

**Comment by OzzieIsaacs** [comment]
Thank you. 

I will fix this after the beta phase of sqlalchmy, as I'm having the hope they will revert this change for the final release.
