### ISSUE TITLE
Can't use kobo sync/ jsonschema error

### ISSUE THREAD

**Issue by scsmartt** [janeczku/calibre-web#1784]
**Describe the bug/problem**
I've setup kobo integration on the server, changed the api-endpoint to use the token created. However, every time I try to sync, it shows "Checking for updates" and then a couple seconds later, "Sync failed try again"

**To Reproduce**
1. Go to sync
2. Click on 'Sync'
3. See error

**Logfile**
[2020-12-29 20:03:51,124]  INFO {cps.kobo:964} Init
[2020-12-29 20:03:51,875] ERROR {cps:1891} Exception on /kobo/*************************/v1/library/sync [GET]
Traceback (most recent call last):
  File "C:\Python39\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python39\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python39\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python39\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Python39\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python39\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Calibre-Web\cps\kobo_auth.py", line 113, in inner
    return f(*args, **kwargs)
  File "C:\Calibre-Web\cps\web.py", line 105, in inner
    return f(*args, **kwargs)
  File "C:\Calibre-Web\cps\kobo.py", line 138, in HandleSyncRequest
    sync_token = SyncToken.SyncToken.from_headers(request.headers)
  File "C:\Calibre-Web\cps\services\SyncToken.py", line 143, in from_headers
    books_last_id = data_json["books_last_id"]
KeyError: 'books_last_id'

**Expected behavior**
I expect that it should start syncing my books to my Kobo

**Environment (please complete the following information):**
 - OS: Windows Server 2019
 - Python version: 3.9
 - Calibre-Web version: 0.6.10 Beta

**Comment by OzzieIsaacs** [comment]
Don't use the development branch for productive use, please. This is a possible outcome! 
Please delete the settings db when going back to master branch, as I don't guarantee compatibility
