### ISSUE TITLE
Corrupt calibre database (metadata.db) when editing book authors

### ISSUE THREAD

**Issue by sker65** [janeczku/calibre-web#1789]
**Describe the bug/problem**
Given you have two books B1 & B2. B1 has the author Sam Jones. B2 has two authors Jones, Sam & John Doe.
As you can see for B2 the author is written reversed. When you now go into edit meta data and turn B2 author around so that it is Same Jones & John Doe it results in an error. SQL unique constraint voilated

**To Reproduce**
1. Go to 'Edit metadata of B2'
2. Change first author to Sam Jones
3. Click save
4. Now navigate to authors list
5. Click on "Sam Jones" to show this authors books

To reproduce later there must be again a book with the wrong name, this way you get 2 author with same name. see screen shot.

**Logfile**
Add content of calibre-web.log file or the relevant error, try to reproduce your problem with "debug" log-level to get more output.

**Expected behavior**
Just list books, no SQL error.
I guess when changing the authors name in books with more than one author the cleanup does not work, then you could create two authors with the same name.

**Screenshots**
![image](https://user-images.githubusercontent.com/1519597/103416083-437e0d00-4b85-11eb-9f2e-c67f35f5218b.png)
![image](https://user-images.githubusercontent.com/1519597/103416094-5690dd00-4b85-11eb-87d0-c18d580f7ff0.png)
![image](https://user-images.githubusercontent.com/1519597/103416100-614b7200-4b85-11eb-86dc-e1812d69adda.png)
![image](https://user-images.githubusercontent.com/1519597/103416109-6c060700-4b85-11eb-97e6-93762eee7384.png)

**Environment (please complete the following information):**
 - Calibre-Web version: 0.6.10 beta
 - Docker container: [/Technosoft2000/]:
 - nginx reverse proxy

**Additional context**

Stack trace
Traceback (most recent call last):
File "/usr/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
self.dialect.do_execute(
File "/usr/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
cursor.execute(statement, parameters)
sqlite3.IntegrityError: UNIQUE constraint failed: authors.name
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "/usr/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
response = self.full_dispatch_request()
File "/usr/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/usr/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
raise value
File "/usr/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/calibre-web/app/cps/web.py", line 202, in decorated_view
return login_required(func)(*args, **kwargs)
File "/usr/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
return func(*args, **kwargs)
File "/calibre-web/app/cps/web.py", line 1035, in books_list
return render_books_list(data, sort_param, book_id, page)
File "/calibre-web/app/cps/web.py", line 703, in render_books_list
return render_author_books(page, book_id, order)
File "/calibre-web/app/cps/web.py", line 799, in render_author_books
entries, __, pagination = calibre_db.fill_indexpage(page, 0,
File "/calibre-web/app/cps/db.py", line 602, in fill_indexpage
return self.fill_indexpage_with_archived_books(page, pagesize, database, db_filter, order, False, *join)
File "/calibre-web/app/cps/db.py", line 620, in fill_indexpage_with_archived_books
len(query.all()))
File "/usr/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3373, in all
return list(self)
File "/usr/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3534, in __iter__
self.session._autoflush()
File "/usr/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1629, in _autoflush
util.raise_(e, with_traceback=sys.exc_info()[2])
File "/usr/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
raise exception
File "/usr/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1618, in _autoflush
self.flush()
File "/usr/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 2536, in flush
self._flush(objects)
File "/usr/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 2678, in _flush
transaction.rollback(_capture_exception=True)
File "/usr/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
compat.raise_(
File "/usr/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
raise exception
File "/usr/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 2638, in _flush
flush_context.execute()
File "/usr/lib/python3.8/site-packages/sqlalchemy/orm/unitofwork.py", line 422, in execute
rec.execute(self)
File "/usr/lib/python3.8/site-packages/sqlalchemy/orm/unitofwork.py", line 586, in execute
persistence.save_obj(
File "/usr/lib/python3.8/site-packages/sqlalchemy/orm/persistence.py", line 230, in save_obj
_emit_update_statements(
File "/usr/lib/python3.8/site-packages/sqlalchemy/orm/persistence.py", line 994, in _emit_update_statements
c = cached_connections[connection].execute(
File "/usr/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1011, in execute
return meth(self, multiparams, params)
File "/usr/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
return connection._execute_clauseelement(self, multiparams, params)
File "/usr/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1124, in _execute_clauseelement
ret = self._execute_context(
File "/usr/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1316, in _execute_context
self._handle_dbapi_exception(
File "/usr/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1510, in _handle_dbapi_exception
util.raise_(
File "/usr/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
raise exception
File "/usr/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
self.dialect.do_execute(
File "/usr/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)
(sqlite3.IntegrityError) UNIQUE constraint failed: authors.name
[SQL: UPDATE authors SET name=? WHERE authors.id = ?]
[parameters: ('Börjlind, Cilla', 6)]
(Background on this error at: http://sqlalche.me/e/13/gkpj)

**Comment by sker65** [comment]
Looking at the stacktrace the moment when it happens is somewhat unexpected, as it is the result of an autoflush where an update has happened, which should anyway not be the case when just calling a get request on an /calibre-web/author/new/<author-id>.
To me this looks like the former update, that was made while changing author meta data, was not flushed / commited correctly? But I'm not familiar with sqlalche.me

**Comment by sker65** [comment]
This is how the authors table looks like:
![image](https://user-images.githubusercontent.com/1519597/103416601-bc7e6400-4b87-11eb-879d-c76807e13b33.png)
And book author link
![image](https://user-images.githubusercontent.com/1519597/103416627-d6b84200-4b87-11eb-946b-27a1d6291847.png)

**Comment by OzzieIsaacs** [comment]
Any idea what the "|" in record 6 means? Calibre stores the comma's in author names as "|"

**Comment by OzzieIsaacs** [comment]
You could run a check library from calibre itself (library -> library maintenance -> check library or similar)

**Comment by stehnes** [comment]
I also had problems regarding to the authors table with the error message similar to "(sqlite3.IntegrityError) UNIQUE constraint failed: authors.name"

I could resolv my problem with a complety re-organisation of my author names. (especially with multiple names for a book)
I changed all my wrong names (e.g. "Child, Lee / Doe, Joe"  --->  Lee Child & Joe Doe)
