### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by claudiocuce** [janeczku/calibre-web#1806]
Internal server error after trying to upload 4 books in .doc format.

Calibre-Web
Internal Server Error
500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
Traceback (most recent call last):
File "/var/www/calibreweb/vendor/flask/app.py", line 2447, in wsgi_app
response = self.full_dispatch_request()
File "/var/www/calibreweb/vendor/flask/app.py", line 1952, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/var/www/calibreweb/vendor/flask/app.py", line 1821, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/var/www/calibreweb/vendor/flask/_compat.py", line 39, in reraise
raise value
File "/var/www/calibreweb/vendor/flask/app.py", line 1950, in full_dispatch_request
rv = self.dispatch_request()
File "/var/www/calibreweb/vendor/flask/app.py", line 1936, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/var/www/calibreweb/cps/web.py", line 197, in decorated_view
return login_required(func)(*args, **kwargs)
File "/var/www/calibreweb/vendor/flask_login/utils.py", line 272, in decorated_view
return func(*args, **kwargs)
File "/var/www/calibreweb/cps/web.py", line 627, in index
entries, random, pagination = calibre_db.fill_indexpage(page, db.Books, True, [db.Books.timestamp.desc()])
File "/var/www/calibreweb/cps/db.py", line 549, in fill_indexpage
return self.fill_indexpage_with_archived_books(page, database, db_filter, order, False, *join)
File "/var/www/calibreweb/cps/db.py", line 565, in fill_indexpage_with_archived_books
len(query.all()))
File "/var/www/calibreweb/vendor/sqlalchemy/orm/query.py", line 3373, in all
return list(self)
File "/var/www/calibreweb/vendor/sqlalchemy/orm/query.py", line 3535, in __iter__
return self._execute_and_instances(context)
File "/var/www/calibreweb/vendor/sqlalchemy/orm/query.py", line 3557, in _execute_and_instances
querycontext, self._connection_from_session, close_with_result=True
File "/var/www/calibreweb/vendor/sqlalchemy/orm/query.py", line 3572, in _get_bind_args
mapper=self._bind_mapper(), clause=querycontext.statement, **kw
File "/var/www/calibreweb/vendor/sqlalchemy/orm/query.py", line 3550, in _connection_from_session
conn = self.session.connection(**kw)
File "/var/www/calibreweb/vendor/sqlalchemy/orm/session.py", line 1141, in connection
execution_options=execution_options,
File "/var/www/calibreweb/vendor/sqlalchemy/orm/session.py", line 1147, in _connection_for_bind
engine, execution_options
File "/var/www/calibreweb/vendor/sqlalchemy/orm/session.py", line 409, in _connection_for_bind
self._assert_active()
File "/var/www/calibreweb/vendor/sqlalchemy/orm/session.py", line 296, in _assert_active
code="7s2a",
sqlalchemy.exc.InvalidRequestError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (sqlite3.IntegrityError) UNIQUE constraint failed: authors.name
[SQL: UPDATE authors SET name=? WHERE authors.id = ?]
[parameters: (('Filelfo,', 1248), ('Vincenzo Bianculli, Enrico Bisenzi, Marco Pini', 1259))]
(Background on this error at: http://sqlalche.me/e/13/gkpj) (Background on this error at: http://sqlalche.me/e/13/7s2a)

**Comment by claudiocuce** [comment]
rebooted server, problem solved.
sorry
