### ISSUE TITLE
Not work extended search

### ISSUE THREAD

**Issue by iAHTOH** [janeczku/calibre-web#1812]
[2021-01-15 13:55:49,495] ERROR {cps:1892} Exception on /advsearch/stored/ [GET]

```
Traceback (most recent call last):
  File "/opt/calibre-web/vendor/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/calibre-web/vendor/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/calibre-web/vendor/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/calibre-web/vendor/flask/_compat.py", line 39, in reraise
    raise value
  File "/opt/calibre-web/vendor/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/calibre-web/vendor/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/calibre-web/cps/usermanagement.py", line 37, in decorated_view
    return func(*args, **kwargs)
  File "/opt/calibre-web/cps/web.py", line 727, in books_list
    return render_books_list(data, sort_param, book_id, page)
  File "/opt/calibre-web/cps/web.py", line 418, in render_books_list
    return render_adv_search_results(term, offset, order, config.config_books_per_page)
  File "/opt/calibre-web/cps/web.py", line 1021, in render_adv_search_results
    author_name = author_name.strip().lower().replace(',', '|')
AttributeError: 'list' object has no attribute 'strip'
```

root@disowiki:~# python3
Python 3.5.3 (default, Nov 18 2020, 21:09:16) 
[GCC 6.3.0 20170516] on linux

Linux disowiki 4.19.0-0.bpo.9-amd64 #1 SMP Debian 4.19.118-2+deb10u1~bpo9+1 (2020-06-09) x86_64 GNU/Linux

**Comment by OzzieIsaacs** [comment]
Please fill out the form, and describe **exactly** what you did and entered to get this error, as I have no idea what you did. 

Thank you

**Comment by OzzieIsaacs** [comment]
Problem solved, reason unclear
