### ISSUE TITLE
Advanced Search leads to 500 Internal Server Error

### ISSUE THREAD

**Issue by johnny-cgn** [janeczku/calibre-web#1818]
**Describe the bug/problem**
Searching for any word in the field discription leads to a 500.
**To Reproduce**
1. Go to 'Advanced Search'
2. Type in 'test' in Description
2. Click on 'Search'
4. See error:

```Internal Server Error
500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
Traceback (most recent call last):
File "/opt/calibre-web/vendor/flask/app.py", line 2447, in wsgi_app
response = self.full_dispatch_request()
File "/opt/calibre-web/vendor/flask/app.py", line 1952, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/opt/calibre-web/vendor/flask/app.py", line 1821, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/opt/calibre-web/vendor/flask/_compat.py", line 39, in reraise
raise value
File "/opt/calibre-web/vendor/flask/app.py", line 1950, in full_dispatch_request
rv = self.dispatch_request()
File "/opt/calibre-web/vendor/flask/app.py", line 1936, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/opt/calibre-web/cps/usermanagement.py", line 38, in decorated_view
return login_required(func)(*args, **kwargs)
File "/opt/calibre-web/vendor/flask_login/utils.py", line 272, in decorated_view
return func(*args, **kwargs)
File "/opt/calibre-web/cps/web.py", line 727, in books_list
return render_books_list(data, sort_param, book_id, page)
File "/opt/calibre-web/cps/web.py", line 418, in render_books_list
return render_adv_search_results(term, offset, order, config.config_books_per_page)
File "/opt/calibre-web/cps/web.py", line 1021, in render_adv_search_results
author_name = author_name.strip().lower().replace(',', '|')
AttributeError: 'list' object has no attribute 'strip'
```
**Logfile**
```[2021-01-18 00:14:24,038] ERROR {cps:1892} Exception on /advsearch/stored/ [GET]
Traceback (most recent call last):
  File "/opt/calibre-web/vendor/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/calibre-web/vendor/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/calibre-web/vendor/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/calibre-web/vendor/flask/_compat.py", line 39, in reraise
    raise value
  File "/opt/calibre-web/vendor/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/calibre-web/vendor/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/calibre-web/cps/usermanagement.py", line 38, in decorated_view
    return login_required(func)(*args, **kwargs)
  File "/opt/calibre-web/vendor/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/opt/calibre-web/cps/web.py", line 727, in books_list
    return render_books_list(data, sort_param, book_id, page)
  File "/opt/calibre-web/cps/web.py", line 418, in render_books_list
    return render_adv_search_results(term, offset, order, config.config_books_per_page)
  File "/opt/calibre-web/cps/web.py", line 1021, in render_adv_search_results
    author_name = author_name.strip().lower().replace(',', '|')
AttributeError: 'list' object has no attribute 'strip'
```

**Expected behavior**
Get search results.

**Environment (please complete the following information):**
 - OS: Ubuntu 16.04
 - Python version: 3.5.2 (default, Oct 7 2020, 17:19:02) [GCC 5.4.0 20160609]
 - Calibre-Web version: 0.6.10 
 - Browser: Firefox 84.0.2 (64-Bit)

**Comment by iAHTOH** [comment]
I have [same problem](https://github.com/janeczku/calibre-web/issues/1812)

**Comment by OzzieIsaacs** [comment]
For me it's working. (I'm using python 3.8). Could you please Download the Debug Package from the admin page and send it to me (via private email, not everybody has to know everything).
Is this happening with every search request (also with searches which produce 0 results)?
Are you doing this as logged in user, or as anonymous user?
What happens if you are searching for a title entered and nothing entered in description?

I'm wondering about this error message, because it says that you posted a list in the authors field. But authors field is a normal text input, so you can't get anything else beside a string back.  This might be related to the versions of flask, or werkzeug, I could check this with the debug information I asked for

**Comment by johnny-cgn** [comment]
Just updated to python 3.8 and it's now working like a charm.

**Comment by iAHTOH** [comment]
I confirm.
It worked for me with version Python 3.9.1

**Comment by OzzieIsaacs** [comment]
Problem solved, reason unclear
