### ISSUE TITLE
'NoneType' object has no attribute 'get' error after 0.6.10

### ISSUE THREAD

**Issue by GarckaMan** [janeczku/calibre-web#1825]
**Describe the bug/problem**
After updating 0.6.10, trying to query the database will result in a `AttributeError: 'NoneType' object has no attribute 'get'` error

**To Reproduce**
1. Update to 0.6.10
2. Go _Recently Added_, _Read Books_, etc (anything that queries the database)

**Logfile**
```
ERROR {cps:1892} Exception on / [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/calibre/cps/usermanagement.py", line 38, in decorated_view
    return login_required(func)(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/opt/calibre/cps/web.py", line 718, in index
    return render_books_list("newest", sort_param, 1, page)
  File "/opt/calibre/cps/web.py", line 345, in render_books_list
    sort = current_user.get_view_property(data, 'stored')
  File "/opt/calibre/cps/ub.py", line 142, in get_view_property
    if not self.view_settings.get(page):
AttributeError: 'NoneType' object has no attribute 'get'
```

**Expected behavior**
User should be able to query and see the books on the database

**Screenshots**
![image](https://user-images.githubusercontent.com/68790233/105284569-82eeb680-5b91-11eb-90a9-323edb1e5f8c.png)

**Environment (please complete the following information):**
 - OS: Debian 10 (on a Proxmox LXC)
 - Python version: 3.7.3
 - Calibre-Web version: 0.6.10
 - Docker container: None
 - Special Hardware: AMD
 - Browser: Chrome latest 

**Additional context**
N/A

**Comment by OzzieIsaacs** [comment]
Looks like something went wrong during database migration. Which version did you use before?
Could you delete the userdatabase and "restart"? If this causes trouble, we have another possibility

**Comment by GarckaMan** [comment]
Deleting and creating back the user fixed the issue. Thanks!

**Comment by bonnebulle** [comment]
Same error here after migration..
What do you mean by "userdatabase" ? 
The database of ebooks ?
Tanks
