### ISSUE TITLE
Error "attempt to write a readonly database"

### ISSUE THREAD

**Issue by gdgeorge** [janeczku/calibre-web#1832]
**Describe the bug/problem**
Calibre-web starts, allows login, and lists books but as soon as user clicks <next> for more books, we hang and container must be restarted. Can also happen with other selections. Happens with two different versions: Linuxserver/calibre-web and Technosoft2000/calibre-web.

**To Reproduce**
1. Go to bottom of book list
2. Click on "next" or another page number
3. See error

**Logfile**
Calibre-Web
Internal Server Error
500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
Traceback (most recent call last):
File "/app/calibre-web/cps/db.py", line 627, in fill_indexpage_with_archived_books
len(query.all()))
File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/query.py", line 3373, in all
return list(self)
File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/query.py", line 3535, in __iter__
return self._execute_and_instances(context)
File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/query.py", line 3556, in _execute_and_instances
conn = self._get_bind_args(
File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/query.py", line 3571, in _get_bind_args
return fn(
File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/query.py", line 3550, in _connection_from_session
conn = self.session.connection(**kw)
File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/session.py", line 1142, in connection
return self._connection_for_bind(
File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/session.py", line 1150, in _connection_for_bind
return self.transaction._connection_for_bind(
File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/session.py", line 409, in _connection_for_bind
self._assert_active()
File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/session.py", line 289, in _assert_active
raise sa_exc.InvalidRequestError(
sqlalchemy.exc.InvalidRequestError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)
(sqlite3.OperationalError) attempt to write a readonly database
[SQL: DELETE FROM books_authors_link WHERE books_authors_link.book = ? AND books_authors_link.author = ?]
[parameters: (38, 27)]
(Background on this error at: http://sqlalche.me/e/13/e3q8) (Background on this error at: http://sqlalche.me/e/13/7s2a)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2447, in wsgi_app
response = self.full_dispatch_request()
File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1952, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1821, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/usr/local/lib/python3.8/dist-packages/flask/_compat.py", line 39, in reraise
raise value
File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1950, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1936, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/app/calibre-web/cps/usermanagement.py", line 38, in decorated_view
return login_required(func)(*args, **kwargs)
File "/usr/local/lib/python3.8/dist-packages/flask_login/utils.py", line 272, in decorated_view
return func(*args, **kwargs)
File "/app/calibre-web/cps/web.py", line 718, in index
return render_books_list("newest", sort_param, 1, page)
File "/app/calibre-web/cps/web.py", line 421, in render_books_list
entries, random, pagination = calibre_db.fill_indexpage(page, 0, db.Books, True, order)
File "/app/calibre-web/cps/db.py", line 608, in fill_indexpage
return self.fill_indexpage_with_archived_books(page, pagesize, database, db_filter, order, False, *join)
File "/app/calibre-web/cps/db.py", line 630, in fill_indexpage_with_archived_books
logger.debug(e)
AttributeError: module 'cps.logger' has no attribute 'debug'
Please report this issue with all related information: Create Issue
Return to Home

**Expected behavior**
I would expect to see the next page of books

**Screenshots**
Can send if needed.

**Environment (please complete the following information):**
 - OS: Docker container on Ubuntu 20.04 guest in a Hyper-V virtual machine under Windows 10 Professional.
 - Python version: Python 3.8.5 (default, Jul 28 2020, 12:59:40)
 - Calibre-Web version: 0.6.10 - 9418045a2cbd8646524d1b8181057084a41e1a99 - 2021-01-17T16:28:28+01:00
 - Docker container: LinuxServer
 - Special Hardware: 
 - Browser: Chrome Version 87.0.4280.141 (Official Build) (64-bit) (Also happens with Edge)

**Additional context**
Apache2 with a reverse proxy. Issue occurs when using the domain or ip address and port to access the server.

**Comment by OzzieIsaacs** [comment]
> attempt to write a readonly database

Please check the access rights to the calibre metadata.db file

**Comment by gdgeorge** [comment]
Thanks for getting back to me. 
The directory is on a local NAS mounted to the Docker host at /mnt/media/ebooks/library. Permissions are set via FSTAB.
Within the container, the /books directory is  777 and the metadata.db is 766 (rwxrwrw). User and group are abc.
On the host, the directory is 777 and the file is 766. User and group are 1000. PGID and PUID are set to 1000 within the container.

**Comment by OzzieIsaacs** [comment]
Okay, the only thing I can tell you is, Calibre-Web is getting a permission error if it‘s trying to access the database

**Comment by gdgeorge** [comment]
Thanks Ozzie!

 

Jerry

**Comment by gdgeorge** [comment]
Follow up: it was a permission issue on the NAS. User was set up read-only. Folders were mounted correctly, but the NAS was refusing access.,

**Comment by shahram7** [comment]
Hi there,
I have the same problem and I am not using NAS or SMB shares.
I've changed the permissions and owner of metadata.db it didn't help
![image](https://github.com/janeczku/calibre-web/assets/34509793/087db07e-29e9-40fb-a064-573f05ee0abd)
Now I am using the Calibre-web on my Docker but I have tried it as a plugin on truenas and there I had the same problem too.
Best regards, Shahram

**Comment by kyaroslav83** [comment]
I solved this issue by sending the metadata.db file directly to my virtual machine (SSH) with Docker, so the file had the correct access rights and permissions

**Comment by MoonDusk1996** [comment]
has the appropriate permission levels and I also have the same error. I am using the quick start database

**Comment by j00c3** [comment]
For those who are still having a DB permissions issue _not_ related to NAS/SMB permissions:

Check your service/daemon file at `/usr/local/etc/rc.d/calibre`.

For me, I had to change the `command_args` variable to include the user database and enable-auth parameters. So it went from 
`command_args="${command_args} --log ${calibre_logfile} --pidfile ${pidfile} --max-log-size ${calibre_logsize} --daemonize ${calibre_library}"`

to
`command_args="${command_args} --log ${calibre_logfile} --pidfile ${pidfile} --max-log-size ${calibre_logsize} --userdb /srv/calibre/users.sqlite --enable-auth --daemonize ${calibre_library}"`

If for some reason you don't want to set up a Calibre DB user but just wanna have an writable DB from the LAN, you need to add trusted IP address(es).

`command_args="${command_args} --log ${calibre_logfile} --pidfile ${pidfile} --max-log-size ${calibre_logsize} --trusted-ips=xx.xx.xx.1,xx.xx.xx.2 --daemonize ${calibre_library}"`
