### ISSUE TITLE
500 Internal Server error after update

### ISSUE THREAD

**Issue by kaipee** [janeczku/calibre-web#1846]
**Describe the bug/problem**
After performing an update the server crashes and will no execute.

**Logfile**
```sh
Traceback (most recent call last):
  File "/opt/calibre-web/cps.py", line 34, in <module>
    from cps import create_app
  File "/opt/calibre-web/cps/__init__.py", line 75, in <module>
    config = config_sql.load_configuration(ub.session)
  File "/opt/calibre-web/cps/config_sql.py", line 419, in load_configuration
    _migrate_database(session)
  File "/opt/calibre-web/cps/config_sql.py", line 414, in _migrate_database
    _migrate_table(session, _Settings)
  File "/opt/calibre-web/cps/config_sql.py", line 347, in _migrate_table
    session.query(column).first()
  File "/opt/calibre-web/vendor/sqlalchemy/orm/query.py", line 3287, in first
    ret = list(self[0:1])
  File "/opt/calibre-web/vendor/sqlalchemy/orm/query.py", line 3065, in __getitem__
    return list(res)
  File "/opt/calibre-web/vendor/sqlalchemy/orm/loading.py", line 101, in instances
    util.raise_from_cause(err)
  File "/opt/calibre-web/vendor/sqlalchemy/util/compat.py", line 398, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/opt/calibre-web/vendor/sqlalchemy/util/compat.py", line 153, in reraise
    raise value
  File "/opt/calibre-web/vendor/sqlalchemy/orm/loading.py", line 85, in instances
    for row in fetch
  File "/opt/calibre-web/vendor/sqlalchemy/orm/loading.py", line 85, in <listcomp>
    for row in fetch
  File "/opt/calibre-web/vendor/sqlalchemy/orm/loading.py", line 84, in <listcomp>
    keyed_tuple([proc(row) for proc in process])
  File "/opt/calibre-web/vendor/sqlalchemy/dialects/sqlite/base.py", line 611, in process
    return default_processor(value)
  File "/opt/calibre-web/vendor/sqlalchemy/sql/sqltypes.py", line 2407, in process
    return json_deserializer(value)
  File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Environment (please complete the following information):**
 - OS: Ubuntu 16.04
 - Python version: Python 3.5.2
 - Calibre-Web version: dcba720
 - Docker container: None
 - Special Hardware: Proxmox VM
 - Browser: Firefox 84.0.1

**Comment by OzzieIsaacs** [comment]
Could you please try to rename the app.db file and start with a new one, to check if the error is gone then?
It could also be related to an old version of sqlite, please doublecheck with issue #1633
