### ISSUE TITLE
errno 2 while setup no such file for constants.py

### ISSUE THREAD

**Issue by sheboftek** [janeczku/calibre-web#1853]
**Describe the bug/problem**
while run python setup.py errno 2 happened with  No such file or directory: 'D:\\calibre-web-master\\src\\calibreweb\\cps\\constants.py

**To Reproduce**
 No such file or directory: 'D:\\calibre-web-master\\src\\calibreweb\\cps\\constants.py

**Comment by sheboftek** [comment]
calibre-web-master>python setup.py install
Traceback (most recent call last):
  File "D:\calibre-web-master\setup.py", line 45, in <module>
    version=find_version("src", "calibreweb", "cps", "constants.py")
  File "D:\calibre-web-master\setup.py", line 35, in find_version
    version_file = read(*file_paths)
  File "D:\calibre-web-master\setup.py", line 31, in read
    with codecs.open(os.path.join(here, *parts), 'r') as fp:
  File "C:\Users\Mahmoud\AppData\Local\Programs\Python\Python39\lib\codecs.py", line 905, in open
    file = builtins.open(filename, mode, buffering)
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\calibre-web-master\\src\\calibreweb\\cps\\constants.py

**Comment by sheboftek** [comment]
working
