### ISSUE TITLE
kindlegen fails with Internal Server Error

### ISSUE THREAD

**Issue by gdx775** [janeczku/calibre-web#187]
When using the Send to Kindle functionality (emails confirmed as working),  the application returns an Internal Server Error. Both the application files and kindle2gen are both owned by the running user and have the executable bit set.

kindle2gen is recognised as being present within the about page. 

Further information can be provided if needed.

**Comment by OzzieIsaacs** [comment]
Could you please provide the logbook entries in calibre-web.log for this incident. 

Thanks

**Comment by gdx775** [comment]
Please see below:

# cat /opt/calibre-web/calibre-web.log
[2017-04-25 07:40:28,828] {/usr/local/lib/python2.7/dist-packages/flask/app.py:1560} ERROR - Exception on /send/19 [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/flask_login/utils.py", line 228, in decorated_view
    return func(*args, **kwargs)
  File "/opt/calibre-web/cps/web.py", line 446, in inner
    return f(*args, **kwargs)
  File "/opt/calibre-web/cps/web.py", line 1817, in send_to_kindle
    result = helper.send_mail(book_id, current_user.kindle_mail, config.config_calibre_dir)
  File "/opt/calibre-web/cps/helper.py", line 210, in send_mail
    filepath = make_mobi(book.id, calibrepath)
  File "/opt/calibre-web/cps/helper.py", line 87, in make_mobi
    stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
[2017-04-25 07:42:08,863] {/usr/local/lib/python2.7/dist-packages/flask/app.py:1560} ERROR - Exception on /send/19 [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/flask_login/utils.py", line 228, in decorated_view
    return func(*args, **kwargs)
  File "/opt/calibre-web/cps/web.py", line 446, in inner
    return f(*args, **kwargs)
  File "/opt/calibre-web/cps/web.py", line 1817, in send_to_kindle
    result = helper.send_mail(book_id, current_user.kindle_mail, config.config_calibre_dir)
  File "/opt/calibre-web/cps/helper.py", line 210, in send_mail

  File "/opt/calibre-web/cps/helper.py", line 87, in make_mobi

  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
[2017-04-25 07:42:23,247] {/usr/local/lib/python2.7/dist-packages/flask/app.py:1560} ERROR - Exception on /send/19 [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/flask_login/utils.py", line 228, in decorated_view
    return func(*args, **kwargs)
  File "/opt/calibre-web/cps/web.py", line 446, in inner
    return f(*args, **kwargs)
  File "/opt/calibre-web/cps/web.py", line 1817, in send_to_kindle
    result = helper.send_mail(book_id, current_user.kindle_mail, config.config_calibre_dir)
  File "/opt/calibre-web/cps/helper.py", line 210, in send_mail

  File "/opt/calibre-web/cps/helper.py", line 87, in make_mobi

  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
[2017-04-25 07:42:53,453] {/usr/local/lib/python2.7/dist-packages/flask/app.py:1560} ERROR - Exception on /send/19 [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/flask_login/utils.py", line 228, in decorated_view
    return func(*args, **kwargs)
  File "/opt/calibre-web/cps/web.py", line 446, in inner
    return f(*args, **kwargs)
  File "/opt/calibre-web/cps/web.py", line 1817, in send_to_kindle
    result = helper.send_mail(book_id, current_user.kindle_mail, config.config_calibre_dir)
  File "/opt/calibre-web/cps/helper.py", line 210, in send_mail
    msg.attach(get_attachment(formats['mobi']))
  File "/opt/calibre-web/cps/helper.py", line 87, in make_mobi
    if os.path.exists(file_path + u".epub"):
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
[2017-04-25 07:43:29,525] {/usr/local/lib/python2.7/dist-packages/flask/app.py:1560} ERROR - Exception on /send/19 [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/flask_login/utils.py", line 228, in decorated_view
    return func(*args, **kwargs)
  File "/opt/calibre-web/cps/web.py", line 446, in inner
    return f(*args, **kwargs)
  File "/opt/calibre-web/cps/web.py", line 1817, in send_to_kindle
    result = helper.send_mail(book_id, current_user.kindle_mail, config.config_calibre_dir)
  File "/opt/calibre-web/cps/helper.py", line 210, in send_mail
    msg.attach(get_attachment(formats['mobi']))
  File "/opt/calibre-web/cps/helper.py", line 87, in make_mobi
    if os.path.exists(file_path + u".epub"):
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
[2017-04-25 07:43:32,141] {/usr/local/lib/python2.7/dist-packages/flask/app.py:1560} ERROR - Exception on /send/19 [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/flask_login/utils.py", line 228, in decorated_view
    return func(*args, **kwargs)
  File "/opt/calibre-web/cps/web.py", line 446, in inner
    return f(*args, **kwargs)
  File "/opt/calibre-web/cps/web.py", line 1817, in send_to_kindle
    result = helper.send_mail(book_id, current_user.kindle_mail, config.config_calibre_dir)
  File "/opt/calibre-web/cps/helper.py", line 210, in send_mail
    msg.attach(get_attachment(formats['mobi']))
  File "/opt/calibre-web/cps/helper.py", line 87, in make_mobi
    if os.path.exists(file_path + u".epub"):
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
[2017-04-25 07:44:07,164] {/usr/local/lib/python2.7/dist-packages/flask/app.py:1560} ERROR - Exception on /send/19 [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/flask_login/utils.py", line 228, in decorated_view
    return func(*args, **kwargs)
  File "/opt/calibre-web/cps/web.py", line 446, in inner
    return f(*args, **kwargs)
  File "/opt/calibre-web/cps/web.py", line 1817, in send_to_kindle
    result = helper.send_mail(book_id, current_user.kindle_mail, config.config_calibre_dir)
  File "/opt/calibre-web/cps/helper.py", line 210, in send_mail
    msg.attach(get_attachment(formats['mobi']))
  File "/opt/calibre-web/cps/helper.py", line 87, in make_mobi
    if os.path.exists(file_path + u".epub"):
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
[2017-04-25 07:44:15,846] {/opt/calibre-web/cps/web.py:211} INFO - Starting Calibre Web...
[2017-04-25 07:44:15,898] {/opt/calibre-web/cps.py:28} INFO - Attempting to start gevent
[2017-04-25 07:48:01,314] {/opt/calibre-web/cps/web.py:211} INFO - Starting Calibre Web...
[2017-04-25 07:48:01,367] {/opt/calibre-web/cps.py:28} INFO - Attempting to start gevent
[2017-04-25 07:52:16,215] {/opt/calibre-web/cps/web.py:211} INFO - Starting Calibre Web...
[2017-04-25 07:52:16,267] {cps.py:28} INFO - Attempting to start gevent
[2017-04-25 07:55:42,407] {/opt/calibre-web/cps/web.py:211} INFO - Starting Calibre Web...
[2017-04-25 07:55:42,462] {/opt/calibre-web/cps.py:28} INFO - Attempting to start gevent
[2017-04-25 08:20:02,334] {/opt/calibre-web/cps/web.py:211} INFO - Starting Calibre Web...
[2017-04-25 08:20:02,387] {/opt/calibre-web/cps.py:28} INFO - Attempting to start gevent
[2017-04-25 08:20:18,103] {/usr/local/lib/python2.7/dist-packages/flask/app.py:1560} ERROR - Exception on /send/15 [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/flask_login/utils.py", line 228, in decorated_view
    return func(*args, **kwargs)
  File "/opt/calibre-web/cps/web.py", line 446, in inner
    return f(*args, **kwargs)
  File "/opt/calibre-web/cps/web.py", line 1817, in send_to_kindle
    result = helper.send_mail(book_id, current_user.kindle_mail, config.config_calibre_dir)
  File "/opt/calibre-web/cps/helper.py", line 207, in send_mail
    filepath = make_mobi(book.id, calibrepath)
  File "/opt/calibre-web/cps/helper.py", line 84, in make_mobi
    stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by Kennyl** [comment]
is it docker image?

**Comment by gdx775** [comment]
No pulled down from source. Added to systemd to run automatically. Other than that nothing unique about the configuration.

**Comment by OzzieIsaacs** [comment]
Please try newest version, should now work again

**Comment by gdx775** [comment]
Seems to still be present after a git pull? Seems to have been a couple of changes made to helper.py? Latest log shows:

/opt/calibre-web# cat calibre-web.log
[2017-04-25 20:50:04,606] {/opt/calibre-web/cps/web.py:211} INFO - Starting Calibre Web...
[2017-04-25 20:50:04,658] {/opt/calibre-web/cps.py:28} INFO - Attempting to start gevent
[2017-04-25 20:51:07,146] {/usr/local/lib/python2.7/dist-packages/flask/app.py:1560} ERROR - Exception on /send/67 [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)  File "/usr/local/lib/python2.7/dist-packages/flask_login/utils.py", line 228, in decorated_view
    return func(*args, **kwargs)
  File "/opt/calibre-web/cps/web.py", line 446, in inner
    return f(*args, **kwargs)
  File "/opt/calibre-web/cps/web.py", line 1817, in send_to_kindle
    result = helper.send_mail(book_id, current_user.kindle_mail, config.config_calibre_dir)
  File "/opt/calibre-web/cps/helper.py", line 207, in send_mail
    filepath = make_mobi(book.id, calibrepath)
  File "/opt/calibre-web/cps/helper.py", line 84, in make_mobi    stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by OzzieIsaacs** [comment]
Next try. This time really tested.

**Comment by gdx775** [comment]
Yep that fixed it. Thanks for the quick turn around!
