### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by Northguy** [janeczku/calibre-web#1878]
**Describe the bug/problem**

Reporting crash of Calibre-web according to request on server page:

Calibre-Web
Internal Server Error
500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
Traceback (most recent call last):
File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2447, in wsgi_app
response = self.full_dispatch_request()
File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1952, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1821, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/usr/local/lib/python3.8/dist-packages/flask/_compat.py", line 39, in reraise
raise value
File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1950, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1936, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/app/calibre-web/cps/usermanagement.py", line 37, in decorated_view
return func(*args, **kwargs)
File "/app/calibre-web/cps/web.py", line 719, in index
return render_books_list("newest", sort_param, 1, page)
File "/app/calibre-web/cps/web.py", line 422, in render_books_list
entries, random, pagination = calibre_db.fill_indexpage(page, 0, db.Books, True, order)
File "/app/calibre-web/cps/db.py", line 610, in fill_indexpage
return self.fill_indexpage_with_archived_books(page, pagesize, database, db_filter, order, False, *join)
File "/app/calibre-web/cps/db.py", line 635, in fill_indexpage_with_archived_books
return entries, randm, pagination
UnboundLocalError: local variable 'entries' referenced before assignment

**To Reproduce**
Random browsing through book library.

**Logfile**
[2021-03-03 20:04:41,883] ERROR {cps:1891} Exception on / [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/app/calibre-web/cps/usermanagement.py", line 37, in decorated_view
    return func(*args, **kwargs)
  File "/app/calibre-web/cps/web.py", line 719, in index
    return render_books_list("newest", sort_param, 1, page)
  File "/app/calibre-web/cps/web.py", line 422, in render_books_list
    entries, random, pagination = calibre_db.fill_indexpage(page, 0, db.Books, True, order)
  File "/app/calibre-web/cps/db.py", line 610, in fill_indexpage
    return self.fill_indexpage_with_archived_books(page, pagesize, database, db_filter, order, False, *join)
  File "/app/calibre-web/cps/db.py", line 635, in fill_indexpage_with_archived_books
    return entries, randm, pagination
UnboundLocalError: local variable 'entries' referenced before assignment
[2021-03-03 20:16:53,229] ERROR {cps.db:632} This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)
(sqlite3.OperationalError) attempt to write a readonly database
[SQL: UPDATE authors SET name=? WHERE authors.id = ?]
[parameters: ('Meinema, Femke', 15693)]
(Background on this error at: http://sqlalche.me/e/13/e3q8) (Background on this error at: http://sqlalche.me/e/13/7s2a)
[2021-03-03 20:16:53,230] ERROR {cps:1891} Exception on / [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/app/calibre-web/cps/usermanagement.py", line 37, in decorated_view
    return func(*args, **kwargs)
  File "/app/calibre-web/cps/web.py", line 719, in index
    return render_books_list("newest", sort_param, 1, page)
  File "/app/calibre-web/cps/web.py", line 422, in render_books_list
    entries, random, pagination = calibre_db.fill_indexpage(page, 0, db.Books, True, order)
  File "/app/calibre-web/cps/db.py", line 610, in fill_indexpage
    return self.fill_indexpage_with_archived_books(page, pagesize, database, db_filter, order, False, *join)
  File "/app/calibre-web/cps/db.py", line 635, in fill_indexpage_with_archived_books
    return entries, randm, pagination
UnboundLocalError: local variable 'entries' referenced before assignment
[2021-03-03 20:49:19,753] ERROR {cps.db:632} This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)
(sqlite3.OperationalError) attempt to write a readonly database
[SQL: UPDATE authors SET name=? WHERE authors.id = ?]
[parameters: ('Meinema, Femke', 15693)]
(Background on this error at: http://sqlalche.me/e/13/e3q8) (Background on this error at: http://sqlalche.me/e/13/7s2a)
[2021-03-03 20:49:19,753] ERROR {cps:1891} Exception on / [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/app/calibre-web/cps/usermanagement.py", line 37, in decorated_view
    return func(*args, **kwargs)
  File "/app/calibre-web/cps/web.py", line 719, in index
    return render_books_list("newest", sort_param, 1, page)
  File "/app/calibre-web/cps/web.py", line 422, in render_books_list
    entries, random, pagination = calibre_db.fill_indexpage(page, 0, db.Books, True, order)
  File "/app/calibre-web/cps/db.py", line 610, in fill_indexpage
    return self.fill_indexpage_with_archived_books(page, pagesize, database, db_filter, order, False, *join)
  File "/app/calibre-web/cps/db.py", line 635, in fill_indexpage_with_archived_books
    return entries, randm, pagination
UnboundLocalError: local variable 'entries' referenced before assignment

**Expected behavior**
no crashes

**Screenshots**
n/a

**Environment (please complete the following information):**
 - Docker container: [Linuxserver.io version:- 0.6.11-ls107 Build-date:- 2021-02-24T11:37:51-05:00]:
 - Special Hardware: [Synology DS918+]
 - Browser: [Chrome 88.0.4324.190]

**Additional context**
n/a

**Comment by OzzieIsaacs** [comment]
This was fixed #1865. Please try to update to newest nightly version

**Comment by Northguy** [comment]
Duplicate confirmed. sorry for bothering....

**Comment by Northguy** [comment]
Updated to latest build 

Linuxserver.io version:- 0.6.11-ls108 Build-date:- 2021-03-02T05:11:05-05:00

Crashed again.. please advise which additional information is required for debugging purposes

Traceback (most recent call last):
File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2447, in wsgi_app
response = self.full_dispatch_request()
File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1952, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1821, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/usr/local/lib/python3.8/dist-packages/flask/_compat.py", line 39, in reraise
raise value
File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1950, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1936, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/app/calibre-web/cps/usermanagement.py", line 38, in decorated_view
return login_required(func)(*args, **kwargs)
File "/usr/local/lib/python3.8/dist-packages/flask_login/utils.py", line 272, in decorated_view
return func(*args, **kwargs)
File "/app/calibre-web/cps/web.py", line 728, in books_list
return render_books_list(data, sort_param, book_id, page)
File "/app/calibre-web/cps/web.py", line 397, in render_books_list
return render_author_books(page, book_id, order)
File "/app/calibre-web/cps/web.py", line 491, in render_author_books
entries, __, pagination = calibre_db.fill_indexpage(page, 0,
File "/app/calibre-web/cps/db.py", line 610, in fill_indexpage
return self.fill_indexpage_with_archived_books(page, pagesize, database, db_filter, order, False, *join)
File "/app/calibre-web/cps/db.py", line 635, in fill_indexpage_with_archived_books
return entries, randm, pagination
UnboundLocalError: local variable 'entries' referenced before assignment

**Comment by Northguy** [comment]
In addition: checked the specific Book entry. Authors were modified / renamed via Calibre Desktop, so seems that Calibre-web somehow crashes when a calibre database update is performed.

**Comment by Northguy** [comment]
Have been putting the database to the test over the last few days... cannot reproduce anymore, so closing this issue for now.
