### ISSUE TITLE
E-Mail Test stops on send: ehlo [127.0.0.1]

### ISSUE THREAD

**Issue by zisco67** [janeczku/calibre-web#1905]
**Description**
After successfully configuration of Calibre-Web's mail server the Save and Send Log stops after `send: ehlo [127.0.0.1]`

**To Reproduce**
1. Activate DEBUG-Level log
2. Go to ../admin/mailsettings
3. Click on Save and Send Test e-mail
4. See log-entry

**Logfile**
```
[2021-03-21 09:23:36,542]  INFO {cps.server:216} webserver stop (restart=True)
[2021-03-21 09:23:36,568]  INFO {cps.server:201} Performing restart of Calibre-Web
[2021-03-21 09:23:49,889] DEBUG {cps.config_sql:323} _ConfigSQL updating storage
[2021-03-21 09:23:52,920] DEBUG {cps.services:37} Cannot import simpleldap, logging in with ldap will not work: No module named 'flask_simpleldap'
[2021-03-21 09:24:06,680] DEBUG {cps.helper:69} Cannot import Image, generating covers from non jpg files will not work: MagickWand shared library not found.
You probably had not installed ImageMagick library.
Try to install:
  https://docs.wand-py.org/en/latest/guide/install.html
[2021-03-21 09:24:13,919] DEBUG {cps.uploader:44} Cannot import Image, generating pdf covers for pdf uploads will not work: MagickWand shared library not found.
You probably had not installed ImageMagick library.
Try to install:
  https://docs.wand-py.org/en/latest/guide/install.html
[2021-03-21 09:24:14,041] DEBUG {cps.uploader:59} Cannot import epub, extracting epub metadata will not work: No module named 'lxml'
[2021-03-21 09:24:14,052] DEBUG {cps.uploader:66} Cannot import fb2, extracting fb2 metadata will not work: No module named 'lxml'
[2021-03-21 09:24:14,455] DEBUG {cps.admin:72} Cannot import Flask-Dance, login with Oauth will not work: No module named 'flask_dance'
[2021-03-21 09:24:14,915]  INFO {cps:101} Starting Calibre Web...
[2021-03-21 09:24:16,611]  INFO {cps.server:168} Starting Tornado server on :5003
[2021-03-21 09:24:45,046] DEBUG {cps.config_sql:323} _ConfigSQL updating storage
[2021-03-21 09:24:45,213] DEBUG {cps.tasks.mail:47} send: ehlo [127.0.0.1]

[2021-03-21 09:27:01,344] DEBUG {cps.tasks.mail:47} send: ehlo [127.0.0.1]

[2021-03-21 09:28:30,777] DEBUG {cps.web:1488} Profile updated
[2021-03-21 09:29:13,404] DEBUG {cps.web:1488} Profile updated
[2021-03-21 09:29:22,140] DEBUG {cps.config_sql:323} _ConfigSQL updating storage
[2021-03-21 09:29:22,287] DEBUG {cps.tasks.mail:47} send: ehlo [127.0.0.1]

[2021-03-21 09:45:30,262] DEBUG {cps.config_sql:323} _ConfigSQL updating storage
[2021-03-21 09:45:31,818] DEBUG {cps.tasks.mail:47} send: ehlo [127.0.0.1]
```
**Expected behavior**
Test-mail should be sent.

**Environment (please complete the following information):**
 - OS: Linux 3.2.40 #25426
 - Python version: 3.9.0
 - Calibre-Web version: 0.6.11
 - Docker container: None
 - Special Hardware: armv7l GNU/Linux synology_armada375_ds215j
 - Browser: Chrome 89.0.4389.90

**Additional context**
Synology mail-server not installed.

**Comment by OzzieIsaacs** [comment]
Please update to the newest commit version (e.g. admin section Basic Configuration -> Server -> Updater -> Nightly, Admin Section check for updates -> Updates)
I added some additional log information, so we can figure out whats going wrong

**Comment by zisco67** [comment]
> For me it's working
> Please update to the newest commit version (e.g. admin section Basic Configuration -> Server -> Updater -> Nightly, Admin Section check for updates -> Updates)
> I added some additional log information, so we can figure out whats going wrong

Thanks a lot - now the log shows up with this error:
`ERROR {cps.tasks.mail:173} SMTP AUTH extension not supported by server.`

**Comment by zisco67** [comment]
Sorry for the inconvenience - I enabled Encryption `STARTTLS`, allowed access for unsecure Apps in my google-account - and it works. Is there a better approach instead of enabling unsecure Apps?

**Comment by OzzieIsaacs** [comment]
Currently not, but it‘s on my list to change

**Comment by OzzieIsaacs** [comment]
I included the feature to use send "safe" email from google account. But yet undocumented (!) and untested

**Comment by zisco67** [comment]
Thanks @OzzieIsaacs!
I've tried it, but it doesn't work (upgraded to v4/7/21):

```
[2021-04-08 14:36:28,514]  INFO {cps:101} Starting Calibre Web...
[2021-04-08 14:36:30,345]  INFO {cps.server:227} Starting Tornado server on :5003
[2021-04-08 14:45:30,682] DEBUG {cps.tasks.mail:52} send: ehlo [127.0.0.1]
[2021-04-08 14:45:30,741] DEBUG {cps.tasks.mail:52} send: STARTTLS
[2021-04-08 14:45:30,850] DEBUG {cps.tasks.mail:52} send: ehlo [127.0.0.1]
[2021-04-08 14:45:30,902] DEBUG {cps.tasks.mail:52} send: AUTH PLAIN
[2021-04-08 14:45:31,023] DEBUG {cps.tasks.mail:52} send: AUTH LOGIN
[2021-04-08 14:45:31,055] DEBUG {cps.tasks.mail:52} send: fF5VV3xAcSl+QG5sJTRN
[2021-04-08 14:45:31,144] ERROR {cps.tasks.mail:148} (535, b'5.7.8 Username and Password not accepted. Learn more at\n5.7.8  https://support.google.com/mail/?p=BadCredentials bh14sm6119107ejb.104 - gsmtp')
```

After turning on the unsafe mode again, it worked:
```
[2021-04-08 14:47:48,339] DEBUG {cps.tasks.mail:52} send: ehlo [127.0.0.1]
[2021-04-08 14:47:48,370] DEBUG {cps.tasks.mail:52} send: STARTTLS
[2021-04-08 14:47:48,447] DEBUG {cps.tasks.mail:52} send: ehlo [127.0.0.1]
[2021-04-08 14:47:48,504] DEBUG {cps.tasks.mail:52} send: AUTH PLAIN
[2021-04-08 14:47:49,903] DEBUG {cps.tasks.mail:52} send: mail FROM:<...@gmail.com> size=2408674
[2021-04-08 14:47:49,932] DEBUG {cps.tasks.mail:52} send: rcpt TO:<...@kindle.com>
[2021-04-08 14:47:49,959] DEBUG {cps.tasks.mail:52} send: data
[2021-04-08 14:47:50,291] DEBUG {cps.tasks.mail:52} send: b'Content-Type: multipart/mixed; boundary="===============0974429072=="\r\nMIME-Version: 1.0\r\nto: ...@kindle.com\r\nfrom: ...@gmail.com\r\nsubject: Send to Kindle\r\nMessage-Id: <161788606264.8975.17441193464960922508.calibre-web@localhost>\r\nDate: Thu, 08 Apr 2021 14:47:42 +0200\r\n\r\n'
[2021-04-08 14:47:54,255] DEBUG {cps.tasks.mail:52} send: quit
```
And google informed me about that:
![image](https://user-images.githubusercontent.com/19727604/114035265-3c028a00-987f-11eb-9234-64004ef6de57.png)

**Comment by OzzieIsaacs** [comment]
> But yet undocumented (!) and untested.

Yeah I know. You have to do several configuration steps to make it work... I need some more time to test and document what to do

**Comment by OzzieIsaacs** [comment]
Now there is a section in the wiki describing what to do, wish you good luck

**Comment by zisco67** [comment]
> Now there is a section in the wiki describing what to do, wish you good luck

Thank you for the detailed description; I think, I configured every step quite well, but in the end my calibre-web doesn't come up:
`json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

How can I rollback to the former configuration? I tried to clear the value `0` in setting `mail_server_type` manually, but without success...

**Comment by OzzieIsaacs** [comment]
I need the complete error message (including the parts in the "{")

**Comment by OzzieIsaacs** [comment]
A and also the string in `mail_gmail_token` (or at least an idea of it), from app.db -> settings table and this is most likely the one to delete to make it run again

**Comment by zisco67** [comment]
This is a json of the two settings:
```
{
	"table": "settings",
	"rows":
	[
		{
			"mail_server_type": "",
			"mail_gmail_token": ""
		}
	]
}
```
And this is the complete error-log:
```
Traceback (most recent call last):
  File "/volume1/web/calibre-web/cps.py", line 34, in <module>
    from cps import create_app
  File "/volume1/web/calibre-web/cps/__init__.py", line 75, in <module>
    config = config_sql.load_configuration(ub.session)
  File "/volume1/web/calibre-web/cps/config_sql.py", line 437, in load_configuration
    _migrate_database(session)
  File "/volume1/web/calibre-web/cps/config_sql.py", line 432, in _migrate_database
    _migrate_table(session, _Settings)
  File "/volume1/web/calibre-web/cps/config_sql.py", line 361, in _migrate_table
    session.query(column).first()
  File "/opt/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 3429, in first
    ret = list(self[0:1])
  File "/opt/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 3203, in __getitem__
    return list(res)
  File "/opt/lib/python3.9/site-packages/sqlalchemy/orm/loading.py", line 100, in instances
    cursor.close()
  File "/opt/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.raise_(
  File "/opt/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/opt/lib/python3.9/site-packages/sqlalchemy/orm/loading.py", line 82, in instances
    rows = [
  File "/opt/lib/python3.9/site-packages/sqlalchemy/orm/loading.py", line 83, in <listcomp>
    keyed_tuple([proc(row) for proc in process])
  File "/opt/lib/python3.9/site-packages/sqlalchemy/orm/loading.py", line 83, in <listcomp>
    keyed_tuple([proc(row) for proc in process])
  File "/opt/lib/python3.9/site-packages/sqlalchemy/dialects/sqlite/base.py", line 644, in process
    return default_processor(value)
  File "/opt/lib/python3.9/site-packages/sqlalchemy/sql/sqltypes.py", line 2454, in process
    return json_deserializer(value)
  File "/opt/lib/python3.9/json/__init__.py", line 346, in loads
  File "/opt/lib/python3.9/json/decoder.py", line 337, in decode
  File "/opt/lib/python3.9/json/decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by OzzieIsaacs** [comment]
I don't fully understand what happend, but I think I found the code where the invalid value got stored. Unfortunally it's hard to recover, so I'd like to ask you to enter "{}" in the settings database field `mail_gmail_token`

**Comment by OzzieIsaacs** [comment]
A, and please update to the newest commit version

**Comment by zisco67** [comment]
Thanks for the prompt reply, I changed the files manually and the values in settings as well; Calibre-Web is now up again, with the old settings (I'm trin to investigate more this evening...). These settings worked:
```
{
	"table": "settings",
	"rows":
	[
		{
			"mail_server_type": "",
			"mail_gmail_token": "{}"
		}
	]
}
```
