### ISSUE TITLE
Error during login

### ISSUE THREAD

**Issue by wawrzek** [janeczku/calibre-web#1918]
**Describe the bug/problem**
When login to the remote server which is behind Apache Proxy, and it's hosted in docker image I see the following error. The error appears only during initial login, after that the website work perfectly. Even pressing "Return to Home" works fine.

```
Calibre-Web
Internal Server Error
500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
Traceback (most recent call last):
File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2447, in wsgi_app
response = self.full_dispatch_request()
File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1952, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1821, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/usr/local/lib/python3.8/dist-packages/flask/_compat.py", line 39, in reraise
raise value
File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1950, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1936, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/app/calibre-web/cps/web.py", line 1383, in login
return redirect_back(url_for("web.index"))
File "/app/calibre-web/cps/redirect.py", line 56, in redirect_back
target = url_for(endpoint, **values)
File "/usr/local/lib/python3.8/dist-packages/flask/helpers.py", line 370, in url_for
return appctx.app.handle_url_build_error(error, endpoint, values)
File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2216, in handle_url_build_error
reraise(exc_type, exc_value, tb)
File "/usr/local/lib/python3.8/dist-packages/flask/_compat.py", line 39, in reraise
raise value
File "/usr/local/lib/python3.8/dist-packages/flask/helpers.py", line 357, in url_for
rv = url_adapter.build(
File "/usr/local/lib/python3.8/dist-packages/werkzeug/routing.py", line 2179, in build
raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint '/unix/'. Did you mean 'web.index' instead?
Please report this issue with all related information: Create Issue
Return to Home

```

**To Reproduce**
1. Set linuxserver/calibre-web docker image with docker-compose.yml presented below
2. Set Apache up as a proxy server (config example below)
3. Go to <webserver>/unix
4. Login
5. See Error

Example of Apache2 config
```
<Location /unix>
  ProxyPass "http://localhost:8083"
  ProxyPassReverse "http://localhost:8083"
  ProxyAddHeaders On
  RequestHeader set Host $http_host
  RequestHeader set X-Real-IP $remote_addr
  RequestHeader set X-Scheme $scheme
  RequestHeader set X-Forwarded-Proto $scheme
  RequestHeader set X-Forwarded-For $proxy_add_x_forwarded_for
  RequestHeader set X-Script-Name /unix
</Location>
```

Example of docker-compose.yml file:
```
---
version: "2.0"
services:
  calibre-web:
    image: ghcr.io/linuxserver/calibre-web
    container_name: calibre-web
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - DOCKER_MODS=linuxserver/calibre-web:calibre
    volumes:
      - /srv/calibre-web/config:/config
      - /srv/calibre-web/CalibreUNIX:/books
    ports:
      - 8083:8083
    restart: unless-stopped
```

**Logfile**
Add content of calibre-web.log file or the relevant error, try to reproduce your problem with "debug" log-level to get more output.

Nothing special in logfile, just exception as posted above.

**Expected behavior**

Normal login

**Screenshots**

**Environment (please complete the following information):**
 - OS: Ubuntu 18.04 (Server)
 - Python version: part of docker image
 - Calibre-Web version:  0.6.11
 - Docker container: Linuxserver.io (some details below)
 - Special Hardware: OVH cloud server
 - Browser: Firefox 87.0

```
            "Labels": {
                "build_version": "Linuxserver.io version:- 0.6.11-ls111 Build-date:- 2021-03-23T14:29:24-04:00",
                "maintainer": "chbmb"
            }

**Comment by OzzieIsaacs** [comment]
I'm using the example from the wiki for years now without any problems (without docker):
```
<Location /unix>
    RequestHeader set X-SCRIPT-NAME /unix
    RequestHeader set X-SCHEME $scheme
    ProxyPass http://localhost:8083/
    ProxyPassReverse http://localhost:8083/
</Location>
```
Sometimes less is more, please try to remove some of the variables (my bet is the "X-Forwarded-For") and try again

**Comment by wawrzek** [comment]
I think I found the problem. It was X-SCHEME line. After changing it to:
      RequestHeader set X-Scheme https

My login looks better.

The official documentation helped me. I wonder how I didn't find it in the first place ...
The link is: https://github.com/janeczku/calibre-web/wiki/Setup-Reverse-Proxy#apache-24
