### ISSUE TITLE
problem accessing shelf.

### ISSUE THREAD

**Issue by maxilee** [janeczku/calibre-web#192]
Hello.

I've create public shelf and addedfew books to it and now I can't open it.
in web browser there is info : error 500 internal server error.

in .log file I've got :
```
[2017-05-07 14:00:59,262] {/usr/lib/python2.7/site-packages/flask/app.py:1560} ERROR - Exception on /shelf/1 [GET]
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/python2.7/site-packages/flask_login/utils.py", line 228, in decorated_view
    return func(*args, **kwargs)
  File "/opt/calibre-web-master/cps/web.py", line 1970, in show_shelf
    shelf=shelf)
  File "/opt/calibre-web-master/cps/web.py", line 559, in render_title_template
    return render_template(instance=config.config_calibre_web_title, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/flask/templating.py", line 134, in render_template
    context, ctx.app)
  File "/usr/lib/python2.7/site-packages/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/calibre-web-master/cps/templates/shelf.html", line 1, in top-level template code
    {% extends "layout.html" %}
  File "/opt/calibre-web-master/cps/templates/layout.html", line 168, in top-level template code
    {% block body %}{% endblock %}
  File "/opt/calibre-web-master/cps/templates/shelf.html", line 25, in block "body"
    <p class="author"><a href="{{url_for('author', book_id=entry.authors[0].id) }}">{{entry.authors[0].name}}</a></p>
  File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 411, in getitem
    return obj[argument]
UndefinedError: 'None' has no attribute 'authors'

```
how can debug this ? 
can that problem can be inside metadata.db ?

**Comment by maxilee** [comment]
hello.
I've found issue :)
I've removed book from library. but book was added to shelf.
when book was removed from library, it was still added to shelf.

to fix the problem - I've manualy edited sqlite database app.db and I've removed record from "book_shelf_link" for "book_id" which was removed.

**Comment by OzzieIsaacs** [comment]
Solved with latest commit
