### ISSUE TITLE
[BUG] Crash after adding books with Calibre

### ISSUE THREAD

**Issue by Typhonragewind** [janeczku/calibre-web#1928]
**Describe the bug/problem**
Calibre-web does not load library after addition of books using the Calibre program. After refresh or restart, Calibre-web goes back to the library selection page. And then the error occurs.

**To Reproduce**
1. Open Calibre
2. Add one or more books
3. Refresh or restart calibre-web

**Logfile**
Traceback (most recent call last):
File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2447, in wsgi_app
response = self.full_dispatch_request()
File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1952, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1821, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/usr/local/lib/python3.8/dist-packages/flask/_compat.py", line 39, in reraise
raise value
File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1950, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1936, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/app/calibre-web/cps/admin.py", line 103, in inner
return f(*args, **kwargs)
File "/app/calibre-web/cps/admin.py", line 649, in basic_configuration
return _configuration_update_helper(configured=filepicker)
File "/app/calibre-web/cps/admin.py", line 862, in _configuration_update_helper
reboot, message = _configuration_ldap_helper(to_save, gdrive_error)
File "/app/calibre-web/cps/admin.py", line 786, in _configuration_ldap_helper
if to_save["ldap_import_user_filter"] == '0':
KeyError: 'ldap_import_user_filter'

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: Docker on Ubuntu 20 LTS
 - Python version: Python 36, i assume
 - Calibre-Web version: 6.11
 - Special Hardware: [e.g. Rasperry Pi Zero]
 - Browser: Firefox 87.0

**Additional context**
Access via reverse proxy with header auth. LDAP for users. This problem once solved itself after a day, but i have no idea how or why.

**Comment by OzzieIsaacs** [comment]
> LDAP for users

The stack traceback has nothing to do with the book add or removed. It's related to a edit configuration action in conjunction with ldap. This error is fixed now

**Comment by Typhonragewind** [comment]
> 
> 
> > LDAP for users
> 
> The stack traceback has nothing to do with the book add or removed. It's related to a edit configuration action in conjunction with ldap. This error is fixed now

Yes, but this only happens when i add a new book with calibre and then immediately refresh/restart Calibreweb to display it.

Also, i found that restarting Docker itself (systemctl restart docker) fixes this issue.
