### ISSUE TITLE
Error when converting to mobi

### ISSUE THREAD

**Issue by seannymurrs** [janeczku/calibre-web#1929]
**Describe the bug/problem**
When trying to convert an epub to mobi (to email), the task fails. 

**To Reproduce**
1. Go to a book. 
2. Click on the option to convert to mobi and email. 
3. Scroll down to the task list. 

**Logfile**

```
cps.tasks.convert:207} 
[2021-04-01 22:14:57,105] DEBUG {cps.tasks.convert:222} Failed to import PyQt module: PyQt5.QtGui with error: libGL.so.1: cannot open shared object file: No such file or directory
[2021-04-01 22:14:57,105] DEBUG {cps.tasks.convert:222} Traceback (most recent call last):
[2021-04-01 22:14:57,105] DEBUG {cps.tasks.convert:222}   File "runpy.py", line 194, in _run_module_as_main
[2021-04-01 22:14:57,105] DEBUG {cps.tasks.convert:222}   File "runpy.py", line 87, in _run_code
[2021-04-01 22:14:57,106] DEBUG {cps.tasks.convert:222}   File "site.py", line 45, in <module>
[2021-04-01 22:14:57,106] DEBUG {cps.tasks.convert:222}   File "site.py", line 41, in main
[2021-04-01 22:14:57,106] DEBUG {cps.tasks.convert:222}   File "calibre/ebooks/conversion/cli.py", line 401, in main
[2021-04-01 22:14:57,106] DEBUG {cps.tasks.convert:222}   File "calibre/ebooks/conversion/plumber.py", line 1271, in run
[2021-04-01 22:14:57,106] DEBUG {cps.tasks.convert:222}   File "calibre/ebooks/conversion/plugins/mobi_output.py", line 186, in convert
[2021-04-01 22:14:57,106] DEBUG {cps.tasks.convert:222}   File "bypy-importer.py", line 203, in exec_module
[2021-04-01 22:14:57,106] DEBUG {cps.tasks.convert:222}   File "calibre/ebooks/mobi/writer2/resources.py", line 12, in <module>
[2021-04-01 22:14:57,107] DEBUG {cps.tasks.convert:222}   File "bypy-importer.py", line 203, in exec_module
[2021-04-01 22:14:57,107] DEBUG {cps.tasks.convert:222}   File "calibre/ebooks/mobi/utils.py", line 13, in <module>
[2021-04-01 22:14:57,107] DEBUG {cps.tasks.convert:222}   File "bypy-importer.py", line 203, in exec_module
[2021-04-01 22:14:57,107] DEBUG {cps.tasks.convert:222}   File "calibre/utils/img.py", line 13, in <module>
[2021-04-01 22:14:57,107] DEBUG {cps.tasks.convert:222} ImportError: cannot import name 'QColor' from 'qt.core' (/mnt/mpaths/seannymurrs/calibre-bin/calibre/lib/calibre-extensions/python-lib.bypy.frozen/qt/core.pyc)
[2021-04-01 22:14:57,108]  INFO {cps.tasks.convert:140} ebook converter failed with error while converting book
```

**Expected behavior**
I expected the epub to be converted and emailed.

**Comment by cbartondock** [comment]
If you're on linux
`sudo apt update
sudo apt install libgl1-mesa-glx`

See https://github.com/conda-forge/pygridgen-feedstock/issues/10

**Comment by OzzieIsaacs** [comment]
This is a problem with calibre and not with calibre-web. I never had problems with missing libraries from calibre. Please report this issue at the docker container repo (if applicable) or calibre itself. For helping them fixing the problem please make sure to include all information regarding your setup.
