### ISSUE TITLE
Calibre works fine ... some problems when opening "authors" or other db-issues ...

### ISSUE THREAD

**Issue by wrdlgrmpf** [janeczku/calibre-web#1935]
Traceback (most recent call last):
File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2447, in wsgi_app
response = self.full_dispatch_request()
File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1952, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1821, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/usr/local/lib/python3.8/dist-packages/flask/_compat.py", line 39, in reraise
raise value
File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1950, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1936, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/app/calibre-web/cps/usermanagement.py", line 38, in decorated_view
return login_required(func)(*args, **kwargs)
File "/usr/local/lib/python3.8/dist-packages/flask_login/utils.py", line 272, in decorated_view
return func(*args, **kwargs)
File "/app/calibre-web/cps/web.py", line 728, in books_list
return render_books_list(data, sort_param, book_id, page)
File "/app/calibre-web/cps/web.py", line 397, in render_books_list
return render_author_books(page, book_id, order)
File "/app/calibre-web/cps/web.py", line 491, in render_author_books
entries, __, pagination = calibre_db.fill_indexpage(page, 0,
File "/app/calibre-web/cps/db.py", line 610, in fill_indexpage
return self.fill_indexpage_with_archived_books(page, pagesize, database, db_filter, order, False, *join)
File "/app/calibre-web/cps/db.py", line 635, in fill_indexpage_with_archived_books
return entries, randm, pagination
UnboundLocalError: local variable 'entries' referenced before assignment

**Comment by OzzieIsaacs** [comment]
This error is already fixed in the newest commit version

**Comment by OzzieIsaacs** [comment]
#1894,  #1871

**Comment by MinchinWeb** [comment]
Hit this too. Restarting the docker container seems to fix it. Glad the "proper" fix has been pushed to master!

**Comment by wrdlgrmpf** [comment]
Restarting doens't fix it unfortunately ... same issue when selecting an author ....

**Comment by OzzieIsaacs** [comment]
There is something in your calibre database wrong you are having 2 authors with the same name but 2 different entries. Please perform calibre -> check library if this doesn't help please check authors in calibre and rename one to a different name and then back to the right name, the authors should merge afterwards and the problem in calibre-web should be solved after a restart

**Comment by MinchinWeb** [comment]
> Restarting doesn't fix it unfortunately ... same issue when selecting an author ....

You're right; I should have been more clear. Until I restart it, every page on Calibre-web continues to through an error. Restarting the Docker container allows me to see the other pages. But every time I try and load the author page, it throws the error and breaks Calibre-Web.

The follow on error on other pages:

```
Traceback (most recent call last):
File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2447, in wsgi_app
response = self.full_dispatch_request()
File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1952, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1821, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/usr/local/lib/python3.8/dist-packages/flask/_compat.py", line 39, in reraise
raise value
File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1950, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1936, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/app/calibre-web/cps/usermanagement.py", line 38, in decorated_view
return login_required(func)(*args, **kwargs)
File "/usr/local/lib/python3.8/dist-packages/flask_login/utils.py", line 272, in decorated_view
return func(*args, **kwargs)
File "/app/calibre-web/cps/web.py", line 719, in index
return render_books_list("newest", sort_param, 1, page)
File "/app/calibre-web/cps/web.py", line 422, in render_books_list
entries, random, pagination = calibre_db.fill_indexpage(page, 0, db.Books, True, order)
File "/app/calibre-web/cps/db.py", line 610, in fill_indexpage
return self.fill_indexpage_with_archived_books(page, pagesize, database, db_filter, order, False, *join)
File "/app/calibre-web/cps/db.py", line 635, in fill_indexpage_with_archived_books
return entries, randm, pagination
UnboundLocalError: local variable 'entries' referenced before assignment
```

**Comment by OzzieIsaacs** [comment]
There is something in your calibre database wrong you are having 2 authors with the same name but 2 different entries. Please perform calibre -> check library if this doesn't help please check authors in calibre and rename one to a different name and then back to the right name, the authors should merge afterwards and the problem in calibre-web should be solved after a restart

**Comment by OzzieIsaacs** [comment]
If you update ti the newest commit version the error should not appear anymore (but it still woun't work until you fix the database in calibre)

**Comment by MinchinWeb** [comment]
> There is something in your calibre database wrong you are having 2 authors with the same name but 2 different entries. Please perform calibre -> check library if this doesn't help please check authors in calibre and rename one to a different name and then back to the right name, the authors should merge afterwards and the problem in calibre-web should be solved after a restart

I reviewed my database several times, and nothing came up. However, if the "main" name for an author has a comma in it, it seems to be what is causing the error. Removing the comma from the name seems to solve it.

Here's the error:

```
Traceback (most recent call last):
File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
self.dialect.do_execute(
File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/default.py", line 608, in do_execute
cursor.execute(statement, parameters)
sqlite3.OperationalError: attempt to write a readonly database
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2447, in wsgi_app
response = self.full_dispatch_request()
File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1952, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1821, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/usr/local/lib/python3.8/dist-packages/flask/_compat.py", line 39, in reraise
raise value
File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1950, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1936, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/app/calibre-web/cps/usermanagement.py", line 38, in decorated_view
return login_required(func)(*args, **kwargs)
File "/usr/local/lib/python3.8/dist-packages/flask_login/utils.py", line 272, in decorated_view
return func(*args, **kwargs)
File "/app/calibre-web/cps/web.py", line 804, in author_list
return render_title_template('list.html', entries=entries, folder='web.books_list', charlist=charlist,
File "/app/calibre-web/cps/render_template.py", line 115, in render_title_template
accept=constants.EXTENSIONS_UPLOAD, read_book_ids=get_readbooks_ids(),
File "/app/calibre-web/cps/render_template.py", line 104, in get_readbooks_ids
readBooks = calibre_db.session.query(db.cc_classes[config.config_read_column])\
File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/query.py", line 3373, in all
return list(self)
File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/query.py", line 3534, in __iter__
self.session._autoflush()
File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/session.py", line 1633, in _autoflush
util.raise_(e, with_traceback=sys.exc_info()[2])
File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/util/compat.py", line 182, in raise_
raise exception
File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/session.py", line 1622, in _autoflush
self.flush()
File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/session.py", line 2540, in flush
self._flush(objects)
File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/session.py", line 2682, in _flush
transaction.rollback(_capture_exception=True)
File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
compat.raise_(
File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/util/compat.py", line 182, in raise_
raise exception
File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/session.py", line 2642, in _flush
flush_context.execute()
File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/unitofwork.py", line 422, in execute
rec.execute(self)
File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/unitofwork.py", line 586, in execute
persistence.save_obj(
File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/persistence.py", line 230, in save_obj
_emit_update_statements(
File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/persistence.py", line 994, in _emit_update_statements
c = cached_connections[connection].execute(
File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1011, in execute
return meth(self, multiparams, params)
File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
return connection._execute_clauseelement(self, multiparams, params)
File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1124, in _execute_clauseelement
ret = self._execute_context(
File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1316, in _execute_context
self._handle_dbapi_exception(
File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1510, in _handle_dbapi_exception
util.raise_(
File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/util/compat.py", line 182, in raise_
raise exception
File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
self.dialect.do_execute(
File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/default.py", line 608, in do_execute
cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)
(sqlite3.OperationalError) attempt to write a readonly database
[SQL: UPDATE authors SET name=? WHERE authors.id = ?]
[parameters: ('Charles L. Marohn, Jr.', 1015)]
```

I'm also running *calibre-web* in a Docker container, with only readonly access to the library and `metadata.db` (much harder for something or someone to accidentally delete my whole library), but this seems to be the only place that causes issues. Allowing write access may also fix this, but I'm not sure why displaying a list of authors would require writing to the database....

In any case, @oguzkilcan thanks for helping to get this figured out!

**Comment by OzzieIsaacs** [comment]
> but I'm not sure why displaying a list of authors would require writing to the database....

That's indeed not very obvious. Calibre stores author names with comma by replacing the comma with a pipe ('|'). For displaying the author name correct this has to be undone. 
For handling the authors list, tags list and ratings list with the same code, this is done in the back end (in the python part) instead of changing it during rendering of the html page. Changing the name starts now implicitly a database change session, which fails if you only have read access. The other prerequisite is having a authors name with a comma in the name.

I'm now creating a copy of the authors list changing it there and use this for rendering the html page, this avoids the database session to be started and prevents the error message. Needs more memory and is slower. 

There is a little chance you will get a similar error in conjunction with displaying book languages in some place.

Please update to the newest commit version, feel excited about the change and please close the issue afterwards (if it works as it did for me afterwards)

**Comment by MinchinWeb** [comment]
> That's indeed not very obvious. Calibre stores author names with comma by replacing the comma with a pipe ('|'). For displaying the author name correct this has to be undone.

"Hacks" like this are when I love programming. Part genius, part insanity. ;) (If I had to guess, this was done a long time ago to deal with SQL queries...) In any case, these hack seems to have been removed between v4 and v5 of Calibre, at least as pertaining to new/updated author names. Because I "fixed" all my authors previously, I can't add a comma now and "break" v0.6.11 again. (I even tried editing the the database directly, but could seem to re-break it the way things were before.)

Since, this looks like it will be fixed, maybe it makes sense to moving the copying to a try/except block (or maybe the additional complication isn't worth the hassle). In any case, thanks again for tackling this.

> Please update to the newest commit version, feel excited about the change and please close the issue afterwards (if it works as it did for me afterwards).

*Sidenote*: If anyone else wants to do this, the Linux Server.io docker image is available in a nightly version --> https://github.com/orgs/linuxserver/packages/container/package/calibre-web

I ran both the nightly (b38877e1) and it mostly worked, but this last time I tried to get it up and running, it's throwing an SQL error about a missing column on repeat, so I can't get to the web interface (if you want me to open a new issue with this, let me know). This is starting with a new (empty) confirm directory, and it looks like it's trying to run the Calibre-web SQLite migrations on first run...:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such column: settings.config_ldap_group_object_filter

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/calibre-web/cps/config_sql.py", line 360, in _migrate_table
    session.query(column).first()
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/query.py", line 3429, in first
    ret = list(self[0:1])
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/query.py", line 3203, in __getitem__
    return list(res)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/query.py", line 3535, in __iter__
    return self._execute_and_instances(context)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/query.py", line 3560, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1011, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1124, in _execute_clauseelement
    ret = self._execute_context(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1316, in _execute_context
    self._handle_dbapi_exception(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1510, in _handle_dbapi_exception
    util.raise_(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such column: settings.config_ldap_group_object_filter
[SQL: SELECT settings.config_ldap_group_object_filter AS settings_config_ldap_group_object_filter 
FROM settings
 LIMIT ? OFFSET ?]
[parameters: (1, 0)]
(Background on this error at: http://sqlalche.me/e/13/e3q8)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: near "(": syntax error

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/calibre-web/cps.py", line 34, in <module>
    from cps import create_app
  File "/app/calibre-web/cps/__init__.py", line 75, in <module>
    config = config_sql.load_configuration(ub.session)
  File "/app/calibre-web/cps/config_sql.py", line 436, in load_configuration
    _migrate_database(session)
  File "/app/calibre-web/cps/config_sql.py", line 431, in _migrate_database
    _migrate_table(session, _Settings)
  File "/app/calibre-web/cps/config_sql.py", line 383, in _migrate_table
    session.execute(alter_table)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/session.py", line 1295, in execute
    return self._connection_for_bind(bind, close_with_result=True).execute(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1011, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1124, in _execute_clauseelement
    ret = self._execute_context(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1316, in _execute_context
    self._handle_dbapi_exception(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1510, in _handle_dbapi_exception
    util.raise_(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) near "(": syntax error
[SQL: ALTER TABLE settings ADD COLUMN `config_ldap_group_object_filter` VARCHAR DEFAULT ''(&(objectclass=posixGroup)(cn=%s))'']
(Background on this error at: http://sqlalche.me/e/13/e3q8)
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such column: settings.config_ldap_group_object_filter

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/calibre-web/cps/config_sql.py", line 360, in _migrate_table
    session.query(column).first()
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/query.py", line 3429, in first
    ret = list(self[0:1])
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/query.py", line 3203, in __getitem__
    return list(res)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/query.py", line 3535, in __iter__
    return self._execute_and_instances(context)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/query.py", line 3560, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1011, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1124, in _execute_clauseelement
    ret = self._execute_context(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1316, in _execute_context
    self._handle_dbapi_exception(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1510, in _handle_dbapi_exception
    util.raise_(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such column: settings.config_ldap_group_object_filter
[SQL: SELECT settings.config_ldap_group_object_filter AS settings_config_ldap_group_object_filter 
FROM settings
 LIMIT ? OFFSET ?]
[parameters: (1, 0)]
(Background on this error at: http://sqlalche.me/e/13/e3q8)
```

**Comment by OzzieIsaacs** [comment]
I'll have a look at it. There is a problem during migration of the database with the default value of the column config_ldap_group_object_filter in settings table. (It's working fine for me)
If you get an app.db, you could add the column manually then it should run. I'll try to fix it (I have no idea what is causing the double quotes from the exceptions (**''**(&(objectclass=posixGroup)(cn=%s))**''**)

**Comment by OzzieIsaacs** [comment]
@MinchinWeb  The migration should be solved by now, if not, please open a new issue as i will not find this issue anymore in the future
