### ISSUE TITLE
crash when accessing "authors" list with readonly /books

### ISSUE THREAD

**Issue by khimaros** [janeczku/calibre-web#1963]
**Describe the bug/problem**

Moved from https://github.com/janeczku/calibre-web/issues/1356#issuecomment-820886589

i'm running `0.6.11 - 4a4d02ea6a91ba3e77337cfce65e756e2e806599` from the linuxserver docker image without any mods.

the issue is seems to be stemming from my use of read only docker volume for the /books path. of course, i wouldn't expect write operations to work, but somewhat surprising to see it fail on what seem to be GET operations.

i suspect this is the offending code, as you can see it is attempting to modify the author name if it contains a `|`:
https://github.com/janeczku/calibre-web/blob/b38877e19361eb41f328642667d1f44170a7ed5d/cps/web.py#L838

**To Reproduce**

1. launch the docker server with the /books volume "readonly"
1. navigate to `/author?data=author&sort_param=stored` (by clicking the "Authors" link in the sidebar)

**Logfile**

```
[2021-04-16 03:32:44,129]  INFO {cps:101} Starting Calibre Web...
[2021-04-16 03:32:44,243]  INFO {cps.server:146} Starting Gevent server on [::]:8083
[2021-04-16 03:33:24,699]  INFO {cps.web:1203} Serving book: <elided>
[2021-04-16 03:35:08,974] ERROR {cps:1891} Exception on /author [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: attempt to write a readonly database

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/app/calibre-web/cps/usermanagement.py", line 37, in decorated_view
    return func(*args, **kwargs)
  File "/app/calibre-web/cps/web.py", line 796, in author_list
    entries = calibre_db.session.query(db.Authors, func.count('books_authors_link.book').label('count')) \
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/query.py", line 3373, in all
    return list(self)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/query.py", line 3534, in __iter__
    self.session._autoflush()
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/session.py", line 1633, in _autoflush
    util.raise_(e, with_traceback=sys.exc_info()[2])
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/session.py", line 1622, in _autoflush
    self.flush()
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/session.py", line 2540, in flush
    self._flush(objects)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/session.py", line 2682, in _flush
    transaction.rollback(_capture_exception=True)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.raise_(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/session.py", line 2642, in _flush
    flush_context.execute()
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/unitofwork.py", line 422, in execute
    rec.execute(self)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/unitofwork.py", line 586, in execute
    persistence.save_obj(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/persistence.py", line 230, in save_obj
    _emit_update_statements(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/persistence.py", line 994, in _emit_update_statements
    c = cached_connections[connection].execute(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1011, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1124, in _execute_clauseelement
    ret = self._execute_context(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1316, in _execute_context
    self._handle_dbapi_exception(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1510, in _handle_dbapi_exception
    util.raise_(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)
(sqlite3.OperationalError) attempt to write a readonly database
[SQL: UPDATE authors SET name=? WHERE authors.id = ?]
[parameters: ('<elided>', 100)]
(Background on this error at: http://sqlalche.me/e/13/e3q8)
```

**Expected behavior**
service doesn't throw an exception and crash

**Screenshots**
N/A

**Environment (please complete the following information):**
 - OS: Linux (container)
 - Calibre-Web version: 0.6.11
 - Docker container: [None/Technosoft2000/LinuxServer]: LinuxServer
 - Special Hardware: amd64
 - Browser: N/A

**Comment by OzzieIsaacs** [comment]
Please update to the newest nightly version (there is some linuxserver Docker image for it) and the error should be solved. The version you are using has this problem, yes

**Comment by OzzieIsaacs** [comment]
Duplicate of: #1935
https://github.com/janeczku/calibre-web/issues/1935#issuecomment-819965474

**Comment by khimaros** [comment]
confirmed, this is working with the `:nightly` LinuxServer image. thank you!
