### ISSUE TITLE
Accessing the "Edit Basic Configuration" option results in server 500

### ISSUE THREAD

**Issue by iamdoubz** [janeczku/calibre-web#1964]
**Describe the bug/problem**
A clear and concise description of what the bug is. If you are asking for support, please check our [Wiki](https://github.com/janeczku/calibre-web/wiki) if your question is already answered there.

**To Reproduce**
1. Go to Admin Menu, under the "Configuration" heading, select "Edit Basic Configuration"
2. Get 500 message

**Logfile**
### 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
```
Traceback (most recent call last):
File "/usr/local/lib/python3.8/dist-packages/pydrive2/auth.py", line 577, in Refresh
self.credentials.refresh(self.http)
File "/usr/local/lib/python3.8/dist-packages/oauth2client/client.py", line 545, in refresh
self._refresh(http)
File "/usr/local/lib/python3.8/dist-packages/oauth2client/client.py", line 761, in _refresh
self._do_refresh_request(http)
File "/usr/local/lib/python3.8/dist-packages/oauth2client/client.py", line 819, in _do_refresh_request
raise HttpAccessTokenRefreshError(error_msg, status=resp.status)
oauth2client.client.HttpAccessTokenRefreshError: invalid_grant: Token has been expired or revoked.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2447, in wsgi_app
response = self.full_dispatch_request()
File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1952, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1821, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/usr/local/lib/python3.8/dist-packages/flask/_compat.py", line 39, in reraise
raise value
File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1950, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1936, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/usr/local/lib/python3.8/dist-packages/flask_login/utils.py", line 272, in decorated_view
return func(*args, **kwargs)
File "/app/calibre-web/cps/admin.py", line 95, in inner
return f(*args, **kwargs)
File "/app/calibre-web/cps/admin.py", line 205, in configuration
return _configuration_result()
File "/app/calibre-web/cps/admin.py", line 1149, in _configuration_result
gdrivefolders = gdriveutils.listRootFolders()
File "/app/calibre-web/cps/gdriveutils.py", line 223, in listRootFolders
fileList = drive.ListFile({'q': folder}).GetList()
File "/usr/local/lib/python3.8/dist-packages/pydrive2/apiattr.py", line 166, in GetList
for x in self:
File "/usr/local/lib/python3.8/dist-packages/pydrive2/apiattr.py", line 150, in __next__
result = self._GetList()
File "/usr/local/lib/python3.8/dist-packages/pydrive2/auth.py", line 60, in _decorated
self.auth.LocalWebserverAuth()
File "/usr/local/lib/python3.8/dist-packages/pydrive2/auth.py", line 130, in _decorated
self.Refresh()
File "/usr/local/lib/python3.8/dist-packages/pydrive2/auth.py", line 579, in Refresh
raise RefreshError("Access token refresh failed: %s" % error)
pydrive2.auth.RefreshError: Access token refresh failed: invalid_grant: Token has been expired or revoked.
```

**Expected behavior**
I can edit the basic configuration.

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. Windows 10/Raspberry Pi OS] Ubuntu 20.04
 - Python version: [e.g. python2.7] 3.8.5
 - Calibre-Web version: [e.g. 0.6.8 or 087c4c59 (git rev-parse --short HEAD)]: 0.6.12 Beta - b38877e19361eb41f328642667d1f44170a7ed5d
 - Docker container: [None/Technosoft2000/LinuxServer]: LinuxServer
 - Special Hardware: [e.g. Rasperry Pi Zero] N/A
 - Browser: [e.g. Chrome 83.0.4103.97, Safari 13.3.7, Firefox 68.0.1 ESR] et al

**Additional context**
Nginx 1.19.9 reverse proxy using `sudo docker-compose up -d`

**Comment by iamdoubz** [comment]
Even though I am not using Google Drive anymore (was very unreliable and slow to load), I still had my config set in the `client_secrets.json` file. Once I changed it back to the default contents of `{}`, the 500 error went away.
