### ISSUE TITLE
After upgrading from V0.6.10-Florence to V0.6.11-Jasmin crashes on startup. 

### ISSUE THREAD

**Issue by kevinen98** [janeczku/calibre-web#1979]
**Describe the bug/problem**
After upgrading from V0.6.10-Florence to V0.6.11-Jasmin crashes on startup. According to log there seems not to be a column user.nickname.

**To Reproduce**
1. Update using the webb-interface uppdater.
2. See errors

**Logfile**

```
May 06 11:35:03 server1 systemd[1]: Started Calibre-Web.
May 06 11:35:04 server1 python3[17013]: Traceback (most recent call last):
May 06 11:35:04 server1 python3[17013]:   File "/home/calibre/calibre-web/env/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
May 06 11:35:04 server1 python3[17013]:     cursor, statement, parameters, context
May 06 11:35:04 server1 python3[17013]:   File "/home/calibre/calibre-web/env/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
May 06 11:35:04 server1 python3[17013]:     cursor.execute(statement, parameters)
May 06 11:35:04 server1 python3[17013]: sqlite3.OperationalError: no such column: user.nickname
May 06 11:35:04 server1 python3[17013]: The above exception was the direct cause of the following exception:
May 06 11:35:04 server1 python3[17013]: Traceback (most recent call last):
May 06 11:35:04 server1 python3[17013]:   File "/home/calibre/calibre-web/cps.py", line 34, in <module>
May 06 11:35:04 server1 python3[17013]:     from cps import create_app
May 06 11:35:04 server1 python3[17013]:   File "/home/calibre/calibre-web/cps/__init__.py", line 73, in <module>
May 06 11:35:04 server1 python3[17013]:     ub.init_db(cli.settingspath)
May 06 11:35:04 server1 python3[17013]:   File "/home/calibre/calibre-web/cps/ub.py", line 678, in init_db
May 06 11:35:04 server1 python3[17013]:     migrate_Database(session)
May 06 11:35:04 server1 python3[17013]:   File "/home/calibre/calibre-web/cps/ub.py", line 562, in migrate_Database
May 06 11:35:04 server1 python3[17013]:     if session.query(User).filter(User.role.op('&')(constants.ROLE_ANONYMOUS) == constants.ROLE_ANONYMOUS).first() \
May 06 11:35:04 server1 python3[17013]:   File "/home/calibre/calibre-web/env/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3429, in first
May 06 11:35:04 server1 python3[17013]:     ret = list(self[0:1])
May 06 11:35:04 server1 python3[17013]:   File "/home/calibre/calibre-web/env/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3203, in __getitem__
May 06 11:35:04 server1 python3[17013]:     return list(res)
May 06 11:35:04 server1 python3[17013]:   File "/home/calibre/calibre-web/env/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3535, in __iter__
May 06 11:35:04 server1 python3[17013]:     return self._execute_and_instances(context)
May 06 11:35:04 server1 python3[17013]:   File "/home/calibre/calibre-web/env/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3560, in _execute_and_instances
May 06 11:35:04 server1 python3[17013]:     result = conn.execute(querycontext.statement, self._params)
May 06 11:35:04 server1 python3[17013]:   File "/home/calibre/calibre-web/env/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1011, in execute
May 06 11:35:04 server1 python3[17013]:     return meth(self, multiparams, params)
May 06 11:35:04 server1 python3[17013]:   File "/home/calibre/calibre-web/env/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
May 06 11:35:04 server1 python3[17013]:     return connection._execute_clauseelement(self, multiparams, params)
May 06 11:35:04 server1 python3[17013]:   File "/home/calibre/calibre-web/env/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1130, in _execute_clauseelement
May 06 11:35:04 server1 python3[17013]:     distilled_params,
May 06 11:35:04 server1 python3[17013]:   File "/home/calibre/calibre-web/env/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1317, in _execute_context
May 06 11:35:04 server1 python3[17013]:     e, statement, parameters, cursor, context
May 06 11:35:04 server1 python3[17013]:   File "/home/calibre/calibre-web/env/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1511, in _handle_dbapi_exception
May 06 11:35:04 server1 python3[17013]:     sqlalchemy_exception, with_traceback=exc_info[2], from_=e
May 06 11:35:04 server1 python3[17013]:   File "/home/calibre/calibre-web/env/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
May 06 11:35:04 server1 python3[17013]:     raise exception
May 06 11:35:04 server1 python3[17013]:   File "/home/calibre/calibre-web/env/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
May 06 11:35:04 server1 python3[17013]:     cursor, statement, parameters, context
May 06 11:35:04 server1 python3[17013]:   File "/home/calibre/calibre-web/env/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
May 06 11:35:04 server1 python3[17013]:     cursor.execute(statement, parameters)
May 06 11:35:04 server1 python3[17013]: sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such column: user.nickname
May 06 11:35:04 server1 python3[17013]: [SQL: SELECT user.id AS user_id, user.nickname AS user_nickname, user.email AS user_email, user.role AS user_role, user.password AS user_password, user.kindle_mail AS user_kindle_mail, user.locale AS user_locale, user.sidebar_view AS user_sidebar_view, user.default_language AS user_default_language, user.mature_content AS user_mature_content, user.denied_tags AS user_denied_tags, user.allowed_tags AS user_allowed_tags, user.denied_column_value AS user_denied_column_value, user.allowed_column_value AS user_allowed_column_value, user.view_settings AS user_view_settings
May 06 11:35:04 server1 python3[17013]: FROM user
May 06 11:35:04 server1 python3[17013]: WHERE (user.role & ?) = ?
May 06 11:35:04 server1 python3[17013]:  LIMIT ? OFFSET ?]
May 06 11:35:04 server1 python3[17013]: [parameters: (32, 32, 1, 0)]
May 06 11:35:04 server1 python3[17013]: (Background on this error at: http://sqlalche.me/e/13/e3q8)
May 06 11:35:04 server1 systemd[1]: calibre-start.service: Main process exited, code=exited, status=1/FAILURE
May 06 11:35:04 server1 systemd[1]: calibre-start.service: Failed with result 'exit-code'.

```

**Expected behavior**
Running as normal.

**Environment (please complete the following information):**
 - OS: Debian 10.9
 - Python version: Python3.7
 - Calibre-Web version: d32b2ca5
 - Docker container: None

**Additional context**
It do work when i delete app.db but is there a solution where i don't delete it?

**Comment by OzzieIsaacs** [comment]
Something isn't fitting together. Version 0.6.10 and 0.6.11 both are having a column "nickname" in the user settings. During my latest changes I renamed this column to "name". (In the version you linked this should already be done) 
The only thing I can imaging how to get a database without nickname column would be update to the newest nightly. Then changing the update channel to stable and performing an update to latest stable 0.6.11. Is it this what your did?

Solutions:
A) Delete app.db and restart your calibre-web instance (You should then be back to 0.6.11)
B) Backup app.db and restart your calibre-web instance, afterwards perform an update to the newest nightly version. Stop Calibre-Web. Copy your backup app.db over the new generated app. You are then using the newest nightly version and can't downgrade to 0.6.11
C) Open app.db with some sqlite editor, like sqlitebrowser and change column name to nickname in table users

**Comment by kevinen98** [comment]
No, i have always had stable channel. But my memory might not be correct about which version I upgraded from. I installed Calibre-Webb 1-2 months ago and it might not be from a actual release. Sorry about that.

I consider my problem solved so i close this issue. Thanks for the solutions and keep up the good work!
