### ISSUE TITLE
Internal Server Error When going to Author page.

### ISSUE THREAD

**Issue by ServerGeek82** [janeczku/calibre-web#1985]
**Describe the bug/problem**
Selected Author -> Unknown -> 500 Internal Server error page. (Had to restart container to bring back)
![Screenshot 2021-05-11 095025](https://user-images.githubusercontent.com/22460481/117854640-88eecd00-b23e-11eb-9db2-e4a58f2b9b69.jpg)

**To Reproduce**

**Logfile**
Add content of calibre-web.log file or the relevant error, try to reproduce your problem with "debug" log-level to get more output.

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. Windows 10/Raspberry Pi OS]
 - Python version: [e.g. python2.7]
 - Calibre-Web version: [e.g. 0.6.8 or 087c4c59 (git rev-parse --short HEAD)]:
 - Docker container: [None/Technosoft2000/LinuxServer]:
 - Special Hardware: [HP Proliant G8]
 - Browser: [Chrome ]
Docker Started with below parameters:

docker run -d \
  --name=calibre-web \
  -e PUID=1000 \
  -e PGID=1000 \
  -e TZ=America/City \
  -e DOCKER_MODS=linuxserver/calibre-web:calibre \
  -p 8083:8083 \
  -v /home/docker/calibre-web/config:/config \
  -v /home/docker/calibre-web/books:/books \
  --restart unless-stopped \
  ghcr.io/linuxserver/calibre-web

**Additional context**
Internal Server Error
500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
Traceback (most recent call last):
File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2447, in wsgi_app
response = self.full_dispatch_request()
File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1952, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1821, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/usr/local/lib/python3.8/dist-packages/flask/_compat.py", line 39, in reraise
raise value
File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1950, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1936, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/app/calibre-web/cps/usermanagement.py", line 38, in decorated_view
return login_required(func)(*args, **kwargs)
File "/usr/local/lib/python3.8/dist-packages/flask_login/utils.py", line 272, in decorated_view
return func(*args, **kwargs)
File "/app/calibre-web/cps/web.py", line 719, in index
return render_books_list("newest", sort_param, 1, page)
File "/app/calibre-web/cps/web.py", line 422, in render_books_list
entries, random, pagination = calibre_db.fill_indexpage(page, 0, db.Books, True, order)
File "/app/calibre-web/cps/db.py", line 610, in fill_indexpage
return self.fill_indexpage_with_archived_books(page, pagesize, database, db_filter, order, False, *join)
File "/app/calibre-web/cps/db.py", line 635, in fill_indexpage_with_archived_books
return entries, randm, pagination
UnboundLocalError: local variable 'entries' referenced before assignment

**Comment by OzzieIsaacs** [comment]
#1935, #1894

**Comment by OzzieIsaacs** [comment]
Is fixed in newest release
