### ISSUE TITLE
ImportError: No module named pysqlite2

### ISSUE THREAD

**Issue by wukongtime** [janeczku/calibre-web#199]
1.pip install -r requirements.txt
2.python cps.py
 there is an error here :
```
Traceback (most recent call last):
  File "cps.py", line 13, in <module>
    from cps import web
  File "/root/calibre-web/cps/web.py", line 18, in <module>
    import ub
  File "/root/calibre-web/cps/ub.py", line 16, in <module>
    engine = create_engine('sqlite:///{0}'.format(dbpath), echo=False)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/__init__.py", line 387, in create_engine
    return strategy.create(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 80, in create
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/dialects/sqlite/pysqlite.py", line 339, in dbapi
    raise e
ImportError: No module named pysqlite2
```
so I run this :yum install sqlite-devel
but it doesn't work.
my system：CentOS release 6.8 (Final)
python version: Python 2.7.9

**Comment by OzzieIsaacs** [comment]
Normally sqlite3 should be used automatically and pysqlite2 is only a fallback. So there is something wrong before. Could you please check if sqlite3 is installed on your machine by starting "python" and them:
`import sqlite3`
`sqlite3.version`
Ths should give you an output like '2.6.0'. I don't know CentOS, but if I read the post all over the internet correct than you had to compile python to get a newer version than 2.6. If this is the case, than you should recompile python after installing the sqlite-devel.

**Comment by a1023456** [comment]
You can use Centos 7 版本。

**Comment by OzzieIsaacs** [comment]
Are there any news on this? Otherwise I would close it.
