### ISSUE TITLE
invalid literal for int() with base 10: '1,5'

### ISSUE THREAD

**Issue by jagalile** [janeczku/calibre-web#1992]
**Describe the bug/problem**
I can't see anything from web, I can only see login form

**To Reproduce**
1. Log in
2. See error

**Logfile**
Biblioteca
Internal Server Error
invalid literal for int() with base 10: '1,5'
Traceback (most recent call last):
File "/usr/lib/python3/dist-packages/flask/app.py", line 2292, in wsgi_app
response = self.full_dispatch_request()
File "/usr/lib/python3/dist-packages/flask/app.py", line 1815, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/lib/python3/dist-packages/flask/app.py", line 1718, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/usr/lib/python3/dist-packages/flask/_compat.py", line 35, in reraise
raise value
File "/usr/lib/python3/dist-packages/flask/app.py", line 1813, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/lib/python3/dist-packages/flask/app.py", line 1799, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/home/pi/calibre-web-master/cps/usermanagement.py", line 38, in decorated_view
return login_required(func)(*args, **kwargs)
File "/home/pi/.local/lib/python3.7/site-packages/flask_login/utils.py", line 272, in decorated_view
return func(*args, **kwargs)
File "/home/pi/calibre-web-master/cps/web.py", line 719, in index
return render_books_list("newest", sort_param, 1, page)
File "/home/pi/calibre-web-master/cps/web.py", line 424, in render_books_list
title=_(u"Books"), page=website)
File "/home/pi/calibre-web-master/cps/render_template.py", line 116, in render_title_template
*args, **kwargs)
File "/usr/lib/python3/dist-packages/flask/templating.py", line 135, in render_template
context, ctx.app)
File "/usr/lib/python3/dist-packages/flask/templating.py", line 117, in _render
rv = template.render(context)
File "/usr/lib/python3/dist-packages/jinja2/asyncsupport.py", line 76, in render
return original_render(self, *args, **kwargs)
File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 1008, in render
return self.environment.handle_exception(exc_info, True)
File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 780, in handle_exception
reraise(exc_type, exc_value, tb)
File "/usr/lib/python3/dist-packages/jinja2/_compat.py", line 37, in reraise
raise value.with_traceback(tb)
File "/home/pi/calibre-web-master/cps/templates/index.html", line 1, in top-level template code
{% extends "layout.html" %}
File "/home/pi/calibre-web-master/cps/templates/layout.html", line 150, in top-level template code
{% block body %}{% endblock %}
File "/home/pi/calibre-web-master/cps/templates/index.html", line 126, in block "body"
({{entry.series_index|formatseriesindex}})
File "/home/pi/calibre-web-master/cps/jinjia.py", line 125, in formatseriesindex_filter
if int(series_index) - series_index == 0:
ValueError: invalid literal for int() with base 10: '1,5'
Please report this issue with all related information: Abrir una incidencia
Volver al inicio

**Expected behavior**
I can't do anything, restart raspberry doesn't fix the problem, delete last books uploaded doesn't fix the problem

**Screenshots**
[Screenshot](https://ibb.co/dj6xMWq)

**Environment (please complete the following information):**
 - OS: Raspberry Pi OS
 - Python version: 3,7
 - Calibre-Web version: 6.11
 - Docker container: None
 - Special Hardware: Rasperry Pi 3B+
 - Browser: All

**Additional context**
Add any other context about the problem here. [e.g. access via reverse proxy, database background sync, special database location]

**Comment by jagalile** [comment]
I could fix the problem, I managed to enter via url _customurl/admin/view_  searched last books uploaded and check Series index

[Secreenshot](https://ibb.co/7R3mJNT)
