### ISSUE TITLE
"No such table" error when clicking on a book

### ISSUE THREAD

**Issue by jgillman** [janeczku/calibre-web#20]
After starting calibre-web with `python cps.py` I can navigate around the site and all of the books in my library are properly displayed. If I click on a book I get a 500 error.

I believe I'm getting the same error in docker, though I'm not getting any traceback output when attaching to the container. The webpage shows the same 500 error.

**OS:** 64bit Mac OS X 10.11.4 15E65
**Kernel:** x86_64 Darwin 15.4.0
**Calibre:** 2.53
**Python:** 2.7.11

```
ERROR:cps.web:Exception on /book/125 [GET]
Traceback (most recent call last):
  File "/Users/jgillman/Code/calibre-web/vendor/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/jgillman/Code/calibre-web/vendor/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/jgillman/Code/calibre-web/vendor/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/jgillman/Code/calibre-web/vendor/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/jgillman/Code/calibre-web/vendor/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/jgillman/Code/calibre-web/vendor/flask_login.py", line 717, in decorated_view
    return func(*args, **kwargs)
  File "/Users/jgillman/Code/calibre-web/cps/web.py", line 381, in show_book
    return render_template('detail.html', entry=entries,  cc=cc, title=entries.title, books_shelfs=book_in_shelfs)
  File "/Users/jgillman/Code/calibre-web/vendor/flask/templating.py", line 128, in render_template
    context, ctx.app)
  File "/Users/jgillman/Code/calibre-web/vendor/flask/templating.py", line 110, in _render
    rv = template.render(context)
  File "/Users/jgillman/Code/calibre-web/vendor/jinja2/environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Users/jgillman/Code/calibre-web/vendor/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/jgillman/Code/calibre-web/cps/templates/detail.html", line 1, in top-level template code
    {% extends "layout.html" %}
  File "/Users/jgillman/Code/calibre-web/cps/templates/layout.html", line 136, in top-level template code
    {% block body %}{% endblock %}
  File "/Users/jgillman/Code/calibre-web/cps/templates/detail.html", line 66, in block "body"
    {% if entry['custom_column_' ~ c.id]|length > 0 %}
  File "/Users/jgillman/Code/calibre-web/vendor/jinja2/environment.py", line 387, in getitem
    return getattr(obj, attr)
  File "/Users/jgillman/Code/calibre-web/vendor/sqlalchemy/orm/attributes.py", line 316, in __get__
    return self.impl.get(instance_state(instance), dict_)
  File "/Users/jgillman/Code/calibre-web/vendor/sqlalchemy/orm/attributes.py", line 613, in get
    value = self.callable_(state, passive)
  File "/Users/jgillman/Code/calibre-web/vendor/sqlalchemy/orm/strategies.py", line 524, in _load_for_state
    return self._emit_lazyload(session, state, ident_key, passive)
  File "/Users/jgillman/Code/calibre-web/vendor/sqlalchemy/orm/strategies.py", line 585, in _emit_lazyload
    result = q.all()
  File "/Users/jgillman/Code/calibre-web/vendor/sqlalchemy/orm/query.py", line 2241, in all
    return list(self)
  File "/Users/jgillman/Code/calibre-web/vendor/sqlalchemy/orm/query.py", line 2353, in __iter__
    return self._execute_and_instances(context)
  File "/Users/jgillman/Code/calibre-web/vendor/sqlalchemy/orm/query.py", line 2368, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/Users/jgillman/Code/calibre-web/vendor/sqlalchemy/engine/base.py", line 662, in execute
    params)
  File "/Users/jgillman/Code/calibre-web/vendor/sqlalchemy/engine/base.py", line 761, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/Users/jgillman/Code/calibre-web/vendor/sqlalchemy/engine/base.py", line 874, in _execute_context
    context)
  File "/Users/jgillman/Code/calibre-web/vendor/sqlalchemy/engine/base.py", line 1024, in _handle_dbapi_exception
    exc_info
  File "/Users/jgillman/Code/calibre-web/vendor/sqlalchemy/util/compat.py", line 196, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/Users/jgillman/Code/calibre-web/vendor/sqlalchemy/engine/base.py", line 867, in _execute_context
    context)
  File "/Users/jgillman/Code/calibre-web/vendor/sqlalchemy/engine/default.py", line 324, in do_execute
    cursor.execute(statement, parameters)
OperationalError: (OperationalError) no such table: books_custom_column_1_link u'SELECT custom_column_1.id AS custom_column_1_id, custom_column_1.value AS custom_column_1_value \
nFROM custom_column_1, books_custom_column_1_link \nWHERE ? = books_custom_column_1_link.book AND custom_column_1.id = books_custom_column_1_link.value' (125,)
ERROR:tornado.access:500 GET /book/125 (::1) 89.60ms
```

**Comment by janeczku** [comment]
Looks as if you have some orphaned entries for "custom columns" in your Calibre database that are confusing the app.

**Comment by cervinko** [comment]
@jgillman do you have custom colums set in calibre? would you mind sending me your metadata.db?

**Comment by jgillman** [comment]
@cervinko I don't have any custom columns that I'm aware of. What's the best way for me to send it to you? Do you have a PGP key or anything like that?

**Comment by jgillman** [comment]
@cervinko Ah! I commented too soon. I had apparently created a custom column awhile back called "formats" (which appropriately listed the formats each book was available in). I removed the custom column and calibre-web works like a charm now.

Probably would be good to support (or at least ignore) custom columns. I can't complain though, this UI is 1000x nicer than the built in one!

**Comment by cervinko** [comment]
we do support custom columns. and the custom columns we do not support, we ignore....
could you tell me wich type of custom column it was?

**Comment by janeczku** [comment]
@jgillman Do you remember which type it was?

![calibre-customn](https://cloud.githubusercontent.com/assets/3813921/15521251/09fadcc8-220b-11e6-8899-1cef2563ba7f.png)

**Comment by jgillman** [comment]
Yes, it was "Column build from other columns". If needed I can try to reproduce it tomorrow (busy tonight).

**Comment by janeczku** [comment]
@cervinko Can you add this column type to the ignore list?

**Comment by cervinko** [comment]
will have a look at it next week(end)....

**Comment by janeczku** [comment]
@cervinko THANKS! 😄 👍
