### ISSUE TITLE
Can't click some buttons on Windows install

### ISSUE THREAD

**Issue by scsmartt** [janeczku/calibre-web#2031]
Just setup calibre-web on Windows using the latest version (0.6.13 Beta) with Python 3.9.5 installed. Starts up just fine and I can access the interface. 
The issue I'm having is I can't click a lot of the buttons in the interface. 
For example, clicking on the folder icon to select the calibre database does nothing. If I input the path manually and click "Save", it does nothing.

Checked the log file but there's nothing in there other than this:

> [2021-06-17 08:43:38,320]  WARN {cps.config_sql:317} Log path None not valid, falling back to default
[2021-06-17 08:43:39,384]  WARN {cps.config_sql:348} invalidating configuration
[2021-06-17 08:43:40,032]  INFO {cps.ub:775} github Blueprint Created
[2021-06-17 08:43:40,046]  INFO {cps.ub:775} google Blueprint Created
[2021-06-17 08:43:41,067]  WARN {fake_useragent:180} Error occurred during loading data. Trying to use cache server https://fake-useragent.herokuapp.com/browsers/0.1.11
Traceback (most recent call last):
  File "c:\Calibre-Web\vendor\fake_useragent\utils.py", line 154, in load
    for item in get_browsers(verify_ssl=verify_ssl):
  File "c:\Calibre-Web\vendor\fake_useragent\utils.py", line 99, in get_browsers
    html = html.split('<table class="w3-table-all notranslate">')[1]
IndexError: list index out of range
[2021-06-17 08:43:41,978]  INFO {cps:103} Starting Calibre Web...
[2021-06-17 08:43:42,106]  INFO {cps.server:205} Starting Gevent server on 0.0.0.0:8083
[2021-06-17 08:44:32,492]  WARN {cps.config_sql:348} invalidating configuration
[2021-06-17 08:44:33,705]  INFO {cps:103} Starting Calibre Web...
[2021-06-17 08:44:33,810]  INFO {cps.server:205} Starting Gevent server on 0.0.0.0:8083
[2021-06-17 08:44:48,901]  INFO {cps.server:273} webserver stop (restart=False)
[2021-06-17 08:44:49,909]  INFO {cps.server:258} Performing shutdown of Calibre-Web
[2021-06-17 08:46:44,415]  WARN {cps.config_sql:348} invalidating configuration
[2021-06-17 08:46:45,571]  INFO {cps:103} Starting Calibre Web...
[2021-06-17 08:46:45,676]  INFO {cps.server:205} Starting Gevent server on 0.0.0.0:8083

**Comment by OzzieIsaacs** [comment]
Do you need ldap login?
Do you need oauth login?
Do you need goodreads integration?
Do you need kobo integration?
Do you need Gdrive integration?
If not, would be great if you could uninstall the corresponding requirements and we could reduce the complexity.
If you want to use all of them, it would be great if you could unistall the corresponding requirements to reduce the complexity until it's working and we are having less to debug

**Comment by scsmartt** [comment]
Removed everything except for goodreads and kobo but the issue remains.
New log file:

> [2021-06-17 09:05:29,920]  WARN {cps.config_sql:317} Log path None not valid, falling back to default
[2021-06-17 09:05:30,327]  WARN {cps.config_sql:348} invalidating configuration
[2021-06-17 09:05:32,101]  INFO {cps:103} Starting Calibre Web...
[2021-06-17 09:05:32,228]  INFO {cps.server:205} Starting Gevent server on 0.0.0.0:8083

**Comment by OzzieIsaacs** [comment]
Could you please check if the developer console in your browser shows any javascript error?

**Comment by scsmartt** [comment]
Refused to execute script from '<URL>' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.
dbconfig:285 Uncaught ReferenceError: $ is not defined
    at dbconfig:285
dbconfig:1 Unchecked runtime.lastError: The message port closed before a response was received.

**Comment by scsmartt** [comment]
![Capture](https://user-images.githubusercontent.com/22498617/122403045-0697ae00-cf4c-11eb-87b0-5f29245ebd96.PNG)

**Comment by OzzieIsaacs** [comment]
Please do things as described in #896

**Comment by scsmartt** [comment]
That was it, thank you so much!!
