### ISSUE TITLE
Internal Server Error after updating docker container

### ISSUE THREAD

**Issue by abhilesh** [janeczku/calibre-web#2041]
**Describe the bug/problem**
Running calibre-web through docker on a Raspberry Pi 4 running Raspbian Buster. I recently upgraded the pi to a 64bit kernel and wanted to upgrade the installation to include converter features. Ran docker-compose to update the image. Webserver is accessible however cannot set the location of Calibre database on first run.

**To Reproduce**
1. Go to https://ebooks.servername.com after docker container update
2. Server asks for location of Calibre Database, fill in '/books', hit save
3. Greeted with Internal Server Error with the following error log

**Logfile**
```
Traceback (most recent call last):
File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2447, in wsgi_app
response = self.full_dispatch_request()
File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1952, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1821, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/usr/local/lib/python3.8/dist-packages/flask/_compat.py", line 39, in reraise
raise value
File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1950, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1936, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/app/calibre-web/cps/admin.py", line 107, in inner
return f(*args, **kwargs)
File "/app/calibre-web/cps/admin.py", line 967, in basic_configuration
return _configuration_update_helper(configured=filepicker)
File "/app/calibre-web/cps/admin.py", line 1214, in _configuration_update_helper
reboot_required |= _configuration_oauth_helper(to_save)
File "/app/calibre-web/cps/admin.py", line 1021, in _configuration_oauth_helper
if to_save["config_" + str(element['id']) + "_oauth_client_id"] != element['oauth_client_id'] \
KeyError: 'config_1_oauth_client_id'
```

**Expected behavior**
Calibre database location gets set and library is visible.

**Environment (please complete the following information):**
 - OS: Raspbian 10 (Buster)
 - Python version: 2.7.16
 - Docker container: LinuxServer:
 - Special Hardware: Raspberry Pi 4
 - Browser: [e.g. Chrome 83.0.4103.97, Safari 13.3.7, Firefox 68.0.1 ESR]

**Additional context**
Accessing via a reverse proxy setup through NGINX Proxy Manager

**Comment by abhilesh** [comment]
As per discussions with fellow peers, the error message had something to do with oauth login (I had setup both Google and GitHub OAuth logins for the server).

The suggested resolution was to either delete the ```app.db``` file and starting the config again.
Alternatively, if you do not wish to lose any user configurations set in ```app.db```,  edit the file with a sqlite editor such as sqlitebrowser, search for settings table and put a '0' in ```config_login_type``` field. Afterwards, you can fix the oauth login config and re-enable oauth login.
