### ISSUE TITLE
user login fails after upgrade and DB password move

### ISSUE THREAD

**Issue by halfbeep** [janeczku/calibre-web#2075]
**Describe the bug/problem**
After updating 0.6.13, trying to query the database will result in a AttributeError: 'NoneType' object has no attribute 'get' error

https://github.com/janeczku/calibre-web/issues/1825#issue-790716642  this issue was closed, but I am seeing exactly same issue. Deleting and recreating users isn't really viable.

Any more ideas? 

**To Reproduce**
1. Update to 0.6.13
2. Go Recently Added, Read any content

**Logfile**
AttributeError: 'NoneType' object has no attribute 'get'
[2021-08-02 20:25:21,259] ERROR {cps:1454} Exception on /category/stored/264 [GET]
Traceback (most recent call last):
  File "/home/eso/.local/lib/python3.9/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/eso/.local/lib/python3.9/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/eso/.local/lib/python3.9/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/eso/.local/lib/python3.9/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/eso/calibre-web/cps/usermanagement.py", line 39, in decorated_view
    return login_required(func)(*args, **kwargs)
  File "/home/eso/.local/lib/python3.9/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/eso/calibre-web/cps/web.py", line 761, in books_list
    return render_books_list(data, sort_param, book_id, page)
  File "/home/eso/calibre-web/cps/web.py", line 374, in render_books_list
    order = get_sort_function(sort, data)
  File "/home/eso/calibre-web/cps/web.py", line 347, in get_sort_function
    sort = current_user.get_view_property(data, 'stored')
  File "/home/eso/calibre-web/cps/ub.py", line 178, in get_view_property
    if not self.view_settings.get(page):
AttributeError: 'NoneType' object has no attribute 'get'

**Expected behavior**
User should be able to query and see the content on the database

**Environment (please complete the following information):**
{"Platform": "Linux 4.19.0-17-amd64 #1 SMP Debian 4.19.194-3 (2021-07-18) x86_64 ", "Python": "3.9.1 (default, Jul 31 2021, 22:19:26) \n[GCC 8.3.0]", "Calibre_Web": "0.6.13 Beta - $Format:%%H$ - $Format:%%cI$", "WebServer": "Tornado 6.1", "Flask": "2.0.1", "Flask_Login": "0.5.0", "Flask_Principal": "0.4.0", "Werkzeug": "2.0.1", "Babel": "2.9.1", "Jinja2": "3.0.1", "Requests": "2.24.0", "SqlAlchemy": "1.4.22", "pySqlite": "2.6.0", "SQLite": "3.34.1", "iso639": "0.4.5", "pytz": "2021.1", "Unidecode": "installed", "Scholarly": "not installed", "Flask_SimpleLDAP": null, "python_LDAP": null, "Goodreads": null, "jsonschema": null, "flask_dance": null, "greenlet": "1.1.0", "Image Magick": "ImageMagick 6.9.10-23 Q16 x86_64 20190101 https://imagemagick.org", "PyPdf": "v1.0.3", "lxml": "not installed", "Wand": "0.6.6", "Comic_API": "not installed", "ebook converter": "not installed", "unrar": "not installed", "kepubify": "not installed"}

**Screenshot**
![logs2](https://user-images.githubusercontent.com/29512820/127924756-68c36078-95cb-4edb-9b43-7a0ee771e809.png)

**Additional context**
See previous issue, all works ok perfect with new user

**Comment by halfbeep** [comment]
password code and algo uses position in DB in addition to HASH stored in DB - when moving from one extracting and importing records - unique id field must be the same before and after
