### ISSUE TITLE
error when reading book in browser (config problem?)

### ISSUE THREAD

**Issue by perler** [janeczku/calibre-web#21]
when I try to read a book in the browser I get things like below.

It may be a problem in the config.ini (it needs some documentation). I simply filled the db_root =  line...

```
WARNING:tornado.access:404 GET /cover/bookname (1.2.3.4) 8.70ms
ERROR:cps.web:Exception on /read/2853 [GET]
Traceback (most recent call last):
  File "/opt/calibre-web/vendor/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/calibre-web/vendor/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/calibre-web/vendor/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/calibre-web/vendor/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/calibre-web/vendor/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/calibre-web/vendor/flask_login.py", line 717, in decorated_view
    return func(*args, **kwargs)
  File "/opt/calibre-web/cps/web.py", line 507, in read_book
    os.mkdir(newDir)
OSError: [Errno 2] No such file or directory: '/opt/calibre-web/cps/static/2853/OEBPS/images/diagram'
ERROR:tornado.access:500 GET /read/2853 (87.157.53.113) 860.93ms
```

**Comment by janeczku** [comment]
@perler Need more information. Are you using the Docker image? If not whats the exact command you are using to start the app?

**Comment by perler** [comment]
no it's debian 7 (kind of, actually openmediavault.org) and the command is:

```
cd /opt/calibre-web
python /opt/calibre-web/cps.py &
```

**Comment by janeczku** [comment]
@perler Added a fix in 46c83bb. Please try again with the current HEAD.

**Comment by perler** [comment]
not yet, but the error is different:

```
[2016-06-17 20:23:12,177] {/opt/calibre-web/vendor/flask/app.py:1423} ERROR - Exception on /read/2871 [GET]
Traceback (most recent call last):
  File "/opt/calibre-web/vendor/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/calibre-web/vendor/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/calibre-web/vendor/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/calibre-web/vendor/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/calibre-web/vendor/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/calibre-web/vendor/flask_login.py", line 717, in decorated_view
    return func(*args, **kwargs)
  File "/opt/calibre-web/cps/web.py", line 503, in read_book
    zfile = zipfile.ZipFile(os.path.join(config.DB_ROOT, book.path, data.name) + ".epub")
  File "/usr/lib/python2.7/zipfile.py", line 714, in __init__
    self._GetContents()
  File "/usr/lib/python2.7/zipfile.py", line 748, in _GetContents
    self._RealGetContents()
  File "/usr/lib/python2.7/zipfile.py", line 759, in _RealGetContents
    endrec = _EndRecData(fp)
  File "/usr/lib/python2.7/zipfile.py", line 238, in _EndRecData
    endrec = list(struct.unpack(structEndArchive, recData))
error: unpack requires a string argument of length 22
```

**Comment by janeczku** [comment]
@perler Does this happen with all your books or just some?

**Comment by perler** [comment]
ah, good question. only with one single book and now even this book doesn't crash the reader. so you can close the issue. (but a lot of books are empty (display nothing) I will open another issue for this.
