### ISSUE TITLE
LDAP authentification with Synology Directory Server is not working

### ISSUE THREAD

**Issue by HerrTim** [janeczku/calibre-web#2104]
**Describe the bug/problem**
LDAP authentification with Synology Directory Server is not working. The log files shows KeyError:'CN'. Loading screen does not stop turning. It was tested with and without OpenLDAP checkbox activated and also with "LDAP Member User Filter Detection" on Autodetect and CustomFilter.

"config_ldap_serv_username": "CN=Administrator,CN=Users,DC=calibreweb,DC=com"
"config_ldap_dn": "DC=calibreweb,DC=com"
"config_ldap_user_object": "CN=%s"
"config_ldap_group_object_filter": "(&(objectclass=group)(CN=%s))"
"config_ldap_group_members_field": "member"
"config_ldap_member_user_object": "CN=%s"

I've tested ldapsearch successful: ldapsearch -x -b "DC=calibreweb,DC=com" -H ldap://ldap.calibreweb.com:389 -D "CN=Administrator,CN=Users,DC=calibreweb,DC=com" -W "(&(objectclass=group)(CN=calibreweb))"

**Logfile**
[2021-08-29 23:10:21,228] DEBUG {cps.updater:303} Stable version: {'version': '0.6.12'}
[2021-08-29 23:10:23,581] ERROR {cps:1891} Exception on /import_ldap_users [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.8/dist-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/app/calibre-web/cps/admin.py", line 94, in inner
    return f(*args, **kwargs)
  File "/app/calibre-web/cps/admin.py", line 1743, in import_ldap_users
    user_count, message = ldap_import_create_user(user, user_data)
  File "/app/calibre-web/cps/admin.py", line 1659, in ldap_import_create_user
    username = user_data[user_login_field][0].decode('utf-8')
KeyError: 'CN'

**Expected behavior**
User should be imported after the button "Import LDAP Users" is pressed.

**Environment (please complete the following information):**
 - Calibre-Web version: 0.6.12
 - Docker container: LinuxServer
 - Special Hardware: Synology NAS
 - Browser: Firefox

**Comment by OzzieIsaacs** [comment]
I can't reproduce it, as I don't know what the device tree looks like. I need something like this:
```
dn: cn=cps,ou=groups,dc=calibreweb,dc=com
objectclass: groupofnames
cn: cps
member: uid=Mümmy 7,ou=People,dc=calibreweb,dc=com
```

From you settings the LDAP group name is missing (calibreweb?)
If you update to the newest nightly version the error should be catched and output as normal error message (hope so, as I can't test it)

**Comment by HerrTim** [comment]
Yes, sorry I missed that. But I found the solution for the problem. I've replaced the "CN=%s" in  "config_ldap_user_object" with the sAMAccountName and disabled OpenLdap and it worked. Problem was in front of screen :-)
