### ISSUE TITLE
500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

### ISSUE THREAD

**Issue by aboutdever** [janeczku/calibre-web#2123]
Traceback (most recent call last):
File "/usr/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
response = self.full_dispatch_request()
File "/usr/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/usr/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
raise value
File "/usr/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/calibre-web/app/cps/usermanagement.py", line 39, in decorated_view
return login_required(func)(*args, **kwargs)
File "/usr/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
return func(*args, **kwargs)
File "/calibre-web/app/cps/web.py", line 752, in index
return render_books_list("newest", sort_param, 1, page)
File "/calibre-web/app/cps/web.py", line 374, in render_books_list
order = get_sort_function(sort, data)
File "/calibre-web/app/cps/web.py", line 347, in get_sort_function
sort = current_user.get_view_property(data, 'stored')
File "/calibre-web/app/cps/ub.py", line 189, in get_view_property
if not self.view_settings.get(page):
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by aboutdever** [comment]
Can someone help me, please

**Comment by OzzieIsaacs** [comment]
Could you please try this: https://github.com/janeczku/calibre-web/issues/1825#issuecomment-764874109
