### ISSUE TITLE
Command Line Access Not Working

### ISSUE THREAD

**Issue by MontyJ** [janeczku/calibre-web#2130]
**Environment**
QNAP NAS TS-251 (latest firmware update as of 9/29/2021)
Installed using .qpkg from QNAPClub V0.6.11. Was updated to V0.6.12.
Docker: None
SSH access with admin login

**Describe the bug/problem**
Unable to access CW from the command line to reset admin password or even the -h switch to list available options. The admin password was accidentally deleted in my password manager and I need to change it w/o losing all user db data.

The docs say "Starting the script with -h lists all supported command line options." I have tried running the "Calibre-Web.sh" script but it only gives me:
```
[/share/CACHEDEV1_DATA/.qpkg/Calibre-Web] # bash Calibre-Web.sh -h
Usage: Calibre-Web.sh {start|stop|restart}
[/share/CACHEDEV1_DATA/.qpkg/Calibre-Web] # 
```
If I try to run the cps.py script I get this:
`[/share/CACHEDEV1_DATA/.qpkg/Calibre-Web/calibre-web] # python3 cps.py -h
Traceback (most recent call last):
  File "/share/CACHEDEV1_DATA/.qpkg/Calibre-Web/calibre-web/cps.py", line 34, in <module>
    from cps import create_app
  File "/share/CACHEDEV1_DATA/.qpkg/Calibre-Web/calibre-web/cps/__init__.py", line 28, in <module>
    from babel import Locale as LC
ModuleNotFoundError: No module named 'babel'`
There is a babel.cfg file in that folder.

**To Reproduce**
1. SSH into the QNAP using Admin login'
2. Navigate to the .../Calibre-Web folder and the .../Calibre-Web/calibre-web folder
3. Use bash or python3 to run 'scripts' shown in code above

**Logfile**
[2021-09-29 09:19:43,078]  WARN {cps.web:1549} Login failed for user "admin" IP-address: ::ffff:xxx.xxx.xxx.xxx
[2021-09-29 09:51:47,679] DEBUG {cps.web:1544} You are now logged in as: 'monty'
[2021-09-29 09:54:04,800] DEBUG {cps.services:29} Cannot import goodreads, showing authors-metadata will not work: No module named 'betterreads'
[2021-09-29 09:54:04,803] DEBUG {cps.services:37} Cannot import simpleldap, logging in with ldap will not work: No module named 'flask_simpleldap'
[2021-09-29 09:54:04,805] DEBUG {cps.services:45} Cannot import SyncToken, syncing books with Kobo Devices will not work: No module named 'jsonschema'
[2021-09-29 09:54:04,807] DEBUG {cps.services:52} Cannot import gmail, sending books via Gmail Oauth2 Verification will not work: No module named 'google_auth_oauthlib'
[2021-09-29 09:54:05,407] DEBUG {cps.gdriveutils:73} Cannot import pydrive,httplib2, using gdrive will not work: No module named 'pydrive'
[2021-09-29 09:54:06,180] DEBUG {cps.comic:44} Cannot import comicapi, extracting comic metadata will not work: No module named 'comicapi'
[2021-09-29 09:54:06,201] DEBUG {cps.comic:51} Cannot import rarfile, extracting cover files from rar files will not work: No module named 'rarfile'
[2021-09-29 09:54:06,454] DEBUG {cps.admin:76} Cannot import Flask-Dance, login with Oauth will not work: No module named 'flask_dance'
[2021-09-29 09:54:06,470] DEBUG {cps.gdrive:46} Cannot import googleapiclient, using GDrive will not work: No module named 'googleapiclient'
[2021-09-29 09:54:06,551]  INFO {cps:101} Starting Calibre Web...
[2021-09-29 09:54:07,043]  INFO {cps.server:205} Starting Gevent server on [::]:8083
[2021-09-29 09:54:56,241] DEBUG {cps.web:1570} User logged out
[2021-09-29 09:55:04,497] DEBUG {cps.web:1544} You are now logged in as: 'monty'
[2021-09-29 10:00:42,130] DEBUG {cps.services:29} Cannot import goodreads, showing authors-metadata will not work: No module named 'betterreads'
[2021-09-29 10:00:42,132] DEBUG {cps.services:37} Cannot import simpleldap, logging in with ldap will not work: No module named 'flask_simpleldap'
[2021-09-29 10:00:42,134] DEBUG {cps.services:45} Cannot import SyncToken, syncing books with Kobo Devices will not work: No module named 'jsonschema'
[2021-09-29 10:00:42,135] DEBUG {cps.services:52} Cannot import gmail, sending books via Gmail Oauth2 Verification will not work: No module named 'google_auth_oauthlib'
[2021-09-29 10:00:42,518] DEBUG {cps.gdriveutils:73} Cannot import pydrive,httplib2, using gdrive will not work: No module named 'pydrive'
[2021-09-29 10:00:43,078] DEBUG {cps.comic:44} Cannot import comicapi, extracting comic metadata will not work: No module named 'comicapi'
[2021-09-29 10:00:43,082] DEBUG {cps.comic:51} Cannot import rarfile, extracting cover files from rar files will not work: No module named 'rarfile'
[2021-09-29 10:00:43,206] DEBUG {cps.admin:76} Cannot import Flask-Dance, login with Oauth will not work: No module named 'flask_dance'
[2021-09-29 10:00:43,221] DEBUG {cps.gdrive:46} Cannot import googleapiclient, using GDrive will not work: No module named 'googleapiclient'
[2021-09-29 10:00:43,297]  INFO {cps:101} Starting Calibre Web...
[2021-09-29 10:00:43,795]  INFO {cps.server:205} Starting Gevent server on [::]:8083
[2021-09-29 14:54:53,466] DEBUG {cps.web:1544} You are now logged in as: 'monty'
[/share/CACHEDEV1_DATA/.qpkg/Calibre-Web/calibre-web] # 

**Expected behavior**
Using the -h switch, should get a list of available options.
Using the -s switch, should change admin password.

**Additional context**
This is all done on localhost. However, CW is running normally with web access for all except admin login due to no valid password available.

**Comment by OzzieIsaacs** [comment]
Calibre-Web.sh -h is not the script the wiki is talking about. Calibre-web is started with `python3 cps.py` or something like this. So calling  `python3 cps.py -h` will work, if you are calling the right python3. 
This leads us to your second problem. If `python3 cps.py` isn't working you installed calibre-web not with the system python but probably created a virtual environment, so finding the python3 where babel is installed at, this will work.

How did you install calibre-web?
