### ISSUE TITLE
Latest update breaks system with python3.5

### ISSUE THREAD

**Issue by kaipee** [janeczku/calibre-web#2137]
**Describe the bug/problem**
Application crash when updating to latest version.

**To Reproduce**
1. Update system to latest using web browser.
2. Install latest requirements (pip3 install -r requirements.txt)
3. Reboot system

**Logfile**
```
/usr/bin/python3 /opt/calibre-web/cps.py
Traceback (most recent call last):
  File "/opt/calibre-web/cps.py", line 29, in <module>
    from cps import create_app
  File "/opt/calibre-web/cps/__init__.py", line 46, in <module>
    from flask_wtf.csrf import CSRFProtect
  File "/usr/local/lib/python3.5/dist-packages/flask_wtf/__init__.py", line 1, in <module>
    from .csrf import CSRFProtect, CsrfProtect
  File "/usr/local/lib/python3.5/dist-packages/flask_wtf/csrf.py", line 220
    dest = f'{view.__module__}.{view.__name__}'
                                              ^
SyntaxError: invalid syntax
```

**Expected behavior**

**Environment (please complete the following information):**
 - OS: Ubuntu 18.04
 - Python version: Python 3.5.2
 - Calibre-Web version: dcba720

**Comment by kaipee** [comment]
I can confirm the service works again with this change. Thanks for your help.
