### ISSUE TITLE
Error after config: "no such table: custom_columns"

### ISSUE THREAD

**Issue by flashliao** [janeczku/calibre-web#216]
After setup and config.show the error.the error is
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: custom_columns [SQL: 'SELECT id, datatype FROM custom_columns']

**Comment by flashliao** [comment]
my computer is centos7.I'm trying windows 10 envirments

**Comment by flashliao** [comment]
winows10 is the same problem

**Comment by flashliao** [comment]
[2017-07-02 19:35:42,611] {D:\calibre-web-master\cps\web.py:211} INFO - Starting Calibre Web...
[2017-07-02 19:35:42,785] {D:\calibre-web-master\cps\book_formats.py:18} WARNING - cannot import Image, generating pdf covers for pdf uploads will not work: MagickWand shared library not found.
You probably had not installed ImageMagick library.
Try to install:
  http://docs.wand-py.org/en/latest/guide/install.html#install-imagemagick-on-windows
[2017-07-02 19:35:43,040] {D:\calibre-web-master\cps.py:28} INFO - Attempting to start gevent
[2017-07-02 19:36:49,684] {C:\Python27\lib\site-packages\flask\app.py:1560} ERROR - Exception on /config [POST]
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python27\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python27\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python27\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python27\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\calibre-web-master\cps\web.py", line 436, in inner
    return f(*args, **kwargs)
  File "D:\calibre-web-master\cps\web.py", line 2110, in basic_configuration
    return configuration_helper(1)
  File "D:\calibre-web-master\cps\web.py", line 2215, in configuration_helper
    if not db.setup_db():
  File "D:\calibre-web-master\cps\db.py", line 322, in setup_db
    cc = conn.execute("SELECT id, datatype FROM custom_columns")
  File "C:\Python27\lib\site-packages\sqlalchemy\engine\base.py", line 939, in execute
    return self._execute_text(object, multiparams, params)
  File "C:\Python27\lib\site-packages\sqlalchemy\engine\base.py", line 1097, in _execute_text
    statement, parameters
  File "C:\Python27\lib\site-packages\sqlalchemy\engine\base.py", line 1189, in _execute_context
    context)
  File "C:\Python27\lib\site-packages\sqlalchemy\engine\base.py", line 1402, in _handle_dbapi_exception
    exc_info
  File "C:\Python27\lib\site-packages\sqlalchemy\util\compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "C:\Python27\lib\site-packages\sqlalchemy\engine\base.py", line 1182, in _execute_context
    context)
  File "C:\Python27\lib\site-packages\sqlalchemy\engine\default.py", line 470, in do_execute
    cursor.execute(statement, parameters)
OperationalError: (sqlite3.OperationalError) no such table: custom_columns [SQL: 'SELECT id, datatype FROM custom_columns']
[2017-07-02 19:36:54,448] {C:\Python27\lib\site-packages\flask\app.py:1560} ERROR - Exception on / [GET]
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python27\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python27\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python27\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python27\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Python27\lib\site-packages\flask_login\utils.py", line 228, in decorated_view
    return func(*args, **kwargs)
  File "D:\calibre-web-master\cps\web.py", line 999, in index
    entries, random, pagination = fill_indexpage(page, db.Books, True, db.Books.timestamp.desc())
  File "D:\calibre-web-master\cps\web.py", line 479, in fill_indexpage
    random = db.session.query(db.Books).filter(lang_filter).order_by(func.random()).limit(config.config_random_books)
AttributeError: 'NoneType' object has no attribute 'query'
[2017-07-02 19:37:08,733] {C:\Python27\lib\site-packages\flask\app.py:1560} ERROR - Exception on /admin/user/new [GET]
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python27\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python27\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python27\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python27\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Python27\lib\site-packages\flask_login\utils.py", line 228, in decorated_view
    return func(*args, **kwargs)
  File "D:\calibre-web-master\cps\web.py", line 422, in inner
    return f(*args, **kwargs)
  File "D:\calibre-web-master\cps\web.py", line 2240, in new_user
    languages = db.session.query(db.Languages).all()
AttributeError: 'NoneType' object has no attribute 'query'

**Comment by OzzieIsaacs** [comment]
Looks like the database of calibre is somehow corrupted. Could you please try in calibre 
library -> library maintenance -> check library (or similar).

**Comment by flashliao** [comment]
after I setup calibre not calibre-web,chose the calibre  metadata.db the address,it can work out.
So sorry too late feedback.

**Comment by vtulin** [comment]
Same error in docker container.
**Technosoft2000/docker-calibre-web** and **linuxserver/docker-calibre-web**.

**Comment by OzzieIsaacs** [comment]
have you tried to repair the database in calibre

**Comment by vtulin** [comment]
When I start the docker container web interface shows me the config webpage to finish, I fill only "Location of Calibre database" which is required and after pushing "Submit" web UI become unaccessable, and log shows above error. However "metadata.db" in /books folder and "app.db"+"calibre-web.log" in /config folder are created.

**Comment by OzzieIsaacs** [comment]
Calibre Web is made for using an existing Calibre database not for creating one.

**Comment by vtulin** [comment]
Thank you! That works. I installed portable version of Calibre and grab "Calibre Library" folder from there.
