### ISSUE TITLE
Problems with converting book

### ISSUE THREAD

**Issue by Ahormigo** [janeczku/calibre-web#2166]
Hi I detect this problem

**This is the error:**
```
[2021-11-04 12:28:49,166]  INFO {cps.editbooks:1080} converting: book id: 16347 from: EPUB to: MOBI
[2021-11-04 12:28:49,171]  INFO {cps.tasks.convert:125} Book id 16347 - target format of .mobi does not exist. Moving forward with convert.
[2021-11-04 12:29:00,580]  INFO {cps.editbooks:1080} converting: book id: 16347 from: EPUB to: AZW3
[2021-11-04 12:29:01,182]  INFO {cps.tasks.convert:125} Book id 16347 - target format of .azw3 does not exist. Moving forward with convert.
[2021-11-04 12:37:17,885]  INFO {cps.tasks.convert:125} Book id 16348 - target format of .mobi does not exist. Moving forward with convert.
[2021-11-04 12:37:21,186]  INFO {cps.tasks.convert:164} ebook converter failed with error while converting book
[2021-11-04 12:37:38,515]  INFO {cps.editbooks:1080} converting: book id: 16348 from: EPUB to: AZW3
[2021-11-04 12:37:39,208]  INFO {cps.tasks.convert:125} Book id 16348 - target format of .azw3 does not exist. Moving forward with convert.
[2021-11-04 12:37:42,320]  INFO {cps.tasks.convert:164} ebook converter failed with error while converting book
[2021-11-04 12:37:45,125]  INFO {cps.editbooks:1080} converting: book id: 16348 from: EPUB to: MOBI
[2021-11-04 12:37:45,131]  INFO {cps.tasks.convert:125} Book id 16348 - target format of .mobi does not exist. Moving forward with convert.
[2021-11-04 12:37:48,304]  INFO {cps.tasks.convert:164} ebook converter failed with error while converting book
[2021-11-04 12:37:55,228]  INFO {cps.editbooks:1080} converting: book id: 16348 from: EPUB to: FB2
[2021-11-04 12:37:55,234]  INFO {cps.tasks.convert:125} Book id 16348 - target format of .fb2 does not exist. Moving forward with convert.
[2021-11-04 12:37:58,467]  INFO {cps.tasks.convert:164} ebook converter failed with error while converting book
```

I have installed :
Linux 4.4.180+ #42218 SMP Mon Oct 18 19:16:55 CST 2021 x86_64 x86_64
Python 3.8.10 (default, Sep 28 2021, 16:10:42) [GCC 9.3.0]
Calibre web  0.6.15 Beta - 42cc13d1e2c09c87047518453f00f55318d1afc8 - 2021-11-03T21:07:16+04:00
ebook-convert (calibre 5.31.1)
kepubify v4.0.1
UNRAR 5.61 beta 1 freeware Copyright (c) 1993-2018 Alexander Roshal

**Comment by OzzieIsaacs** [comment]
This messages point towards a problem from calibre-ebook converter while converting the books. Please enable DEBUG level logging (admin -> basic configuration -> logfile configuration -> loglevel)  and try it again. There should be more output then. Normally this are problems with the specific books itself

**Comment by Ahormigo** [comment]
Hi again, I have the same problem,
as you can see: (I try with different format and books)

[2021-11-04 12:59:49,921]  INFO {cps.tasks.convert:125} Book id 16220 - target format of .mobi does not exist. Moving forward with convert.
[2021-11-04 12:59:50,317] DEBUG {cps.tasks.convert:225} No write access to /root/.config/calibre using a temporary dir instead
[2021-11-04 12:59:50,368] DEBUG {cps.tasks.convert:225} 1% Convirtiendo entrada a HTML...
[2021-11-04 12:59:50,368] DEBUG {cps.tasks.convert:225} InputFormatPlugin: EPUB Input running
[2021-11-04 12:59:50,368] DEBUG {cps.tasks.convert:225} on /books/Yenisse Gonzalez/Y si la culpa no es de la vaca (16220)/Y si la culpa no es de la vaca - Yenisse Gonzalez.epub
[2021-11-04 12:59:50,469] DEBUG {cps.tasks.convert:225} Found HTML cover titlepage.xhtml
[2021-11-04 12:59:50,480] DEBUG {cps.tasks.convert:225} Parsing all content...
[2021-11-04 12:59:51,041] DEBUG {cps.tasks.convert:225} Referenced file 'text/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX' not found
[2021-11-04 12:59:51,068] DEBUG {cps.tasks.convert:225} 34% Aplicando transformaciones al libro electrónico...
[2021-11-04 12:59:51,168] DEBUG {cps.tasks.convert:225} Merging user specified metadata...
[2021-11-04 12:59:51,169] DEBUG {cps.tasks.convert:225} Detecting structure...
[2021-11-04 12:59:51,221] DEBUG {cps.tasks.convert:225} Flattening CSS and remapping font sizes...
[2021-11-04 12:59:52,171] DEBUG {cps.tasks.convert:225} Source base font size is 12.00000pt
[2021-11-04 12:59:52,895] DEBUG {cps.tasks.convert:225} Removing fake margins...
[2021-11-04 12:59:52,971] DEBUG {cps.tasks.convert:225} Cleaning up manifest...
[2021-11-04 12:59:52,971] DEBUG {cps.tasks.convert:225} Trimming unused files from manifest...
[2021-11-04 12:59:52,997] DEBUG {cps.tasks.convert:225} Trimming 'titlepage.xhtml' from manifest
[2021-11-04 12:59:52,998] DEBUG {cps.tasks.convert:225} Creating MOBI Output...
[2021-11-04 12:59:52,999] DEBUG {cps.tasks.convert:225} 67% Ejecutando el complemento MOBI Output
[2021-11-04 12:59:53,272] DEBUG {cps.tasks.convert:225} 
[2021-11-04 12:59:53,273] DEBUG {cps.tasks.convert:238} Failed to import PyQt module: PyQt5.QtGui with error: libGL.so.1: cannot open shared object file: No such file or directory
[2021-11-04 12:59:53,273] DEBUG {cps.tasks.convert:238} Traceback (most recent call last):
[2021-11-04 12:59:53,273] DEBUG {cps.tasks.convert:238}   File "runpy.py", line 194, in _run_module_as_main
[2021-11-04 12:59:53,273] DEBUG {cps.tasks.convert:238}   File "runpy.py", line 87, in _run_code
[2021-11-04 12:59:53,273] DEBUG {cps.tasks.convert:238}   File "site.py", line 45, in <module>
[2021-11-04 12:59:53,273] DEBUG {cps.tasks.convert:238}   File "site.py", line 41, in main
[2021-11-04 12:59:53,273] DEBUG {cps.tasks.convert:238}   File "calibre/ebooks/conversion/cli.py", line 399, in main
[2021-11-04 12:59:53,274] DEBUG {cps.tasks.convert:238}   File "calibre/ebooks/conversion/plumber.py", line 1271, in run
[2021-11-04 12:59:53,274] DEBUG {cps.tasks.convert:238}   File "calibre/ebooks/conversion/plugins/mobi_output.py", line 185, in convert
[2021-11-04 12:59:53,274] DEBUG {cps.tasks.convert:238}   File "bypy-importer.py", line 279, in exec_module
[2021-11-04 12:59:53,274] DEBUG {cps.tasks.convert:238}   File "calibre/ebooks/mobi/writer2/resources.py", line 14, in <module>
[2021-11-04 12:59:53,274] DEBUG {cps.tasks.convert:238}   File "bypy-importer.py", line 279, in exec_module
[2021-11-04 12:59:53,274] DEBUG {cps.tasks.convert:238}   File "calibre/ebooks/mobi/utils.py", line 13, in <module>
[2021-11-04 12:59:53,274] DEBUG {cps.tasks.convert:238}   File "bypy-importer.py", line 279, in exec_module
[2021-11-04 12:59:53,274] DEBUG {cps.tasks.convert:238}   File "calibre/utils/img.py", line 13, in <module>
[2021-11-04 12:59:53,274] DEBUG {cps.tasks.convert:238} ImportError: cannot import name 'QColor' from 'qt.core' (/app/calibre/lib/calibre-extensions/python-lib.bypy.frozen/qt/core.pyc)
[2021-11-04 12:59:53,275]  INFO {cps.tasks.convert:164} ebook converter failed with error while converting book
[2021-11-04 14:08:20,213] DEBUG {cps.updater:326} Nightly version: 42cc13d1e2c09c87047518453f00f55318
![Captura de pantalla 2021-11-04 a las 14 08 14](https://user-images.githubusercontent.com/93663285/140319299-476ba346-252f-4a3f-b30f-d5adb8935fae.png)
d1afc8, 2021-11-03T21:07:16+04:00

**Comment by OzzieIsaacs** [comment]
> Failed to import PyQt module: PyQt5.QtGui with error: libGL.so.1: cannot open shared object file: No such file or directory

>  ImportError: cannot import name 'QColor' from 'qt.core' (/app/calibre/lib/calibre-extensions/python-lib.bypy.frozen/qt/core.pyc)

You are running calibre on a headless server?
Calibre is missing something from Qt library. 
My bet the command:
/opt/calibre/ebook-convert "/books/Yenisse Gonzalez/Y si la culpa no es de la vaca (16220)/Y si la culpa no es de la vaca - Yenisse Gonzalez.epub" "/books/Yenisse Gonzalez/Y si la culpa no es de la vaca (16220)/Y si la culpa no es de la vaca - Yenisse Gonzalez.mobi" 
from command line will also fail -> Not a problem of Calibre-Web.

If so, please close the issue

**Comment by Ahormigo** [comment]
i'm running calibre on a Synology NAS with a Docker image.
![Captura de pantalla 2021-11-04 a las 14 33 26](https://user-images.githubusercontent.com/93663285/140322501-624204e4-6afe-4c1c-ba6a-310032d0060c.png)

I'll try to reinstall to old versión

**Comment by Dinth** [comment]
@Ahormigo im assuming that you have managed to convert the book successfully after downgrading. Could you please log a regression with linuxserver team?
