### ISSUE TITLE
Windows .exe failing to launch. "No module named 'sqlalchemy.sql.default_comparator'"

### ISSUE THREAD

**Issue by justinross** [janeczku/calibre-web#2188]
**Describe the bug/problem**
calibre-web is crashing on startup (Windows) after first install. 

**To Reproduce**
1. Install from latest release .exe, V0.6.14 Fanja
2. Run calibreweb.exe
3. CLI throws the following error:

**Logfile**
```
C:\Calibre-Web>C:\Calibre-Web\calibreweb.exe
Traceback (most recent call last):
  File "__init__.py", line 29, in <module>
  File "C:\Development\calibre-web-test\test\venv\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 531, in exec_module
  File "cps\__init__.py", line 35, in <module>
  File "C:\Development\calibre-web-test\test\venv\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 531, in exec_module
  File "cps\config_sql.py", line 23, in <module>
  File "C:\Development\calibre-web-test\test\venv\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 531, in exec_module
  File "sqlalchemy\__init__.py", line 9, in <module>
  File "C:\Development\calibre-web-test\test\venv\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 531, in exec_module
  File "sqlalchemy\engine\__init__.py", line 18, in <module>
  File "C:\Development\calibre-web-test\test\venv\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 531, in exec_module
  File "sqlalchemy\engine\events.py", line 9, in <module>
  File "C:\Development\calibre-web-test\test\venv\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 531, in exec_module
  File "sqlalchemy\engine\base.py", line 12, in <module>
  File "C:\Development\calibre-web-test\test\venv\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 531, in exec_module
  File "sqlalchemy\engine\interfaces.py", line 11, in <module>
  File "C:\Development\calibre-web-test\test\venv\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 531, in exec_module
  File "sqlalchemy\sql\__init__.py", line 150, in <module>
  File "sqlalchemy\sql\__init__.py", line 145, in __go
  File "sqlalchemy\util\_preloaded.py", line 63, in import_prefix
ModuleNotFoundError: No module named 'sqlalchemy.sql.default_comparator'
[13928] Failed to execute script __init__
```

**Expected behavior**
Expected the software to launch properly. 

**Screenshots**

**Environment (please complete the following information):**
 - OS: Windows 10
 - Python version: running from .exe so I'm not sure 
 - Calibre-Web version: V0.6.14 Fanja
 - Docker container: N/A
 - Special Hardware: N/A
 - Browser: Not getting that far

**Comment by OzzieIsaacs** [comment]
Looks like a basic absolutly not working problem. I‘ll have a look at it

**Comment by justinross** [comment]
Thanks! With python stuff, I always assume I just screwed something up, since I don't really know what I'm doing, but installing from the .exe, I figured this was a fairly safe report to file. :)

Let me know if I can provide any extra info.

**Comment by OzzieIsaacs** [comment]
The advantage of the exe file is that everything is included and there is no additional python stuff to worry about

**Comment by OzzieIsaacs** [comment]
Thanks for reproting, I had a very stupid error in my build script. 
I replaced the exe file with a working on (I checked it this time)
Please download it and enjoy.

**Comment by Darthagnon** [comment]
Thank you for the fix! I was just about to report the same bug as the OP with the previous build.
