### ISSUE TITLE
Updating via Web UI causing error once logged in...

### ISSUE THREAD

**Issue by After-Shock** [janeczku/calibre-web#2190]
**Describe the bug/problem**
A clear and concise description of what the bug is. If you are asking for support, please check our [Wiki](https://github.com/janeczku/calibre-web/wiki) if your question is already answered there.

**To Reproduce**

**Logfile**
Add content of calibre-web.log file or the relevant error, try to reproduce your problem with "debug" log-level to get more output.

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. Windows 10/Raspberry Pi OS]
 - Python version: [e.g. python2.7]
 - Calibre-Web version: [e.g. 0.6.8 or 087c4c59 (git rev-parse --short HEAD)]:
 - Docker container: [None/LinuxServer]:
 - Special Hardware: [e.g. Rasperry Pi Zero]
 - Browser: [e.g. Chrome 83.0.4103.97, Safari 13.3.7, Firefox 68.0.1 ESR]

**Additional context**
Using Docker and went to update via the WebGui, no issues during the update, unable to login after the restart. 

calibre-web.log file:
`AttributeError: 'NoneType' object has no attribute 'query'
[2021-11-24 22:49:14,120]  INFO {cps.server:272} webserver stop (restart=False)
[2021-11-24 22:49:14,120]  INFO {cps.server:257} Performing shutdown of Calibre-Web
[2021-11-24 22:49:32,423] ERROR {cps.config_sql:348} (sqlite3.OperationalError) unable to open database: /books/metadata.db
[SQL: attach database '/books/metadata.db' as calibre;]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2021-11-24 22:49:32,424]  WARN {cps.config_sql:349} invalidating configuration
[2021-11-24 22:49:32,854]  WARN {fake_useragent:180} Error occurred during loading data. Trying to use cache server https://fake-useragent.herokuapp.com/browsers/0.1.11
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/fake_useragent/utils.py", line 154, in load
    for item in get_browsers(verify_ssl=verify_ssl):
  File "/usr/local/lib/python3.8/dist-packages/fake_useragent/utils.py", line 99, in get_browsers
    html = html.split('<table class="w3-table-all notranslate">')[1]
IndexError: list index out of range
[2021-11-24 22:49:33,402]  INFO {cps:134} Starting Calibre Web...
[2021-11-24 22:49:33,461]  INFO {cps.server:204} Starting Gevent server on [::]:8083
[2021-11-24 22:49:48,102] ERROR {cps:1457} Exception on / [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/app/calibre-web/cps/usermanagement.py", line 38, in decorated_view
    return login_required(func)(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/app/calibre-web/cps/web.py", line 744, in index
    return render_books_list("newest", sort_param, 1, page)
  File "/app/calibre-web/cps/web.py", line 408, in render_books_list
    entries, random, pagination = calibre_db.fill_indexpage(page, 0, db.Books, True, order,
  File "/app/calibre-web/cps/db.py", line 679, in fill_indexpage
    return self.fill_indexpage_with_archived_books(page, pagesize, database, db_filter, order, False, *join)
  File "/app/calibre-web/cps/db.py", line 692, in fill_indexpage_with_archived_books
    query = self.session.query(database)
AttributeError: 'NoneType' object has no attribute 'query'`

**Comment by After-Shock** [comment]
Just caught the:
https://github.com/janeczku/calibre-web/issues/2161
