### ISSUE TITLE
Build Install flask-WTF into the Docker Image

### ISSUE THREAD

**Issue by After-Shock** [janeczku/calibre-web#2191]
Upgrading from 0.6.13 -> 0.6.14 requires the install of flask-WTF, this issue tracker is to have it added to the latest docker image as to alleviate the need to install it manually within the container after it has been built. 

**To Reproduce**
Upgrade via the webgui and restart, receive the below internal server error. 

**Logfile**

```
Internal Server Error
500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
Traceback (most recent call last):
File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2073, in wsgi_app
response = self.full_dispatch_request()
File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1518, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1516, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1502, in dispatch_request
return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
File "/app/calibre-web/cps/usermanagement.py", line 38, in decorated_view
return login_required(func)(*args, **kwargs)
File "/usr/local/lib/python3.8/dist-packages/flask_login/utils.py", line 272, in decorated_view
return func(*args, **kwargs)
File "/app/calibre-web/cps/web.py", line 744, in index
return render_books_list("newest", sort_param, 1, page)
File "/app/calibre-web/cps/web.py", line 408, in render_books_list
entries, random, pagination = calibre_db.fill_indexpage(page, 0, db.Books, True, order,
File "/app/calibre-web/cps/db.py", line 679, in fill_indexpage
return self.fill_indexpage_with_archived_books(page, pagesize, database, db_filter, order, False, *join)
File "/app/calibre-web/cps/db.py", line 692, in fill_indexpage_with_archived_books
query = self.session.query(database)
AttributeError: 'NoneType' object has no attribute 'query'
```

**Additional context**
https://github.com/janeczku/calibre-web/issues/2161

Resolution:
access docker container console.

apt-get -y install python3-pip
pip install flask-WTF

restart container.

**Comment by After-Shock** [comment]
See that it's been addressed in the nightly build

**Comment by marcolaeti** [comment]
voici ce que je recois comme message dans la console Docker
https://i.imgur.com/6OqDT3A.png
que faire ?
