### ISSUE TITLE
Cannot log in using LDAP on fresh install

### ISSUE THREAD

**Issue by 1337joe** [janeczku/calibre-web#2197]
**Describe the bug/problem**
I'm trying to set up ldap authentication. With the help of the wiki I was able to get it hooked up to import a user (so I know it's connecting to the ldap), but when I try to log in as the imported user I get an error:
`INFO {cps.web:1543} LDAP bind_user: simple_bind() argument 1 must be str or None, not dict`

**To Reproduce**
1. Fresh docker image/config directory
2. Configure ldap
3. Import users
4. Attempt to log in as an imported user
5. Get error displayed on the web page and in the log.

**Logfile**
Deleted my config directory and started fresh to get a clean and concise log.
```
[2021-11-30 01:29:57,973]  WARN {cps.config_sql:318} Log path None not valid, falling back to default
[2021-11-30 01:29:58,290]  WARN {cps.config_sql:349} invalidating configuration
[2021-11-30 01:29:58,579]  INFO {cps.ub:851} github Blueprint Created
[2021-11-30 01:29:58,585]  INFO {cps.ub:851} google Blueprint Created
[2021-11-30 01:29:58,924]  WARN {fake_useragent:180} Error occurred during loading data. Trying to use cache server https://fake-useragent.herokuapp.com/browsers/0.1.11
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/fake_useragent/utils.py", line 154, in load
    for item in get_browsers(verify_ssl=verify_ssl):
  File "/usr/local/lib/python3.8/dist-packages/fake_useragent/utils.py", line 99, in get_browsers
    html = html.split('<table class="w3-table-all notranslate">')[1]
IndexError: list index out of range
[2021-11-30 01:29:59,238]  INFO {cps:134} Starting Calibre Web...
[2021-11-30 01:29:59,343]  INFO {cps.server:204} Starting Gevent server on [::]:8083
[2021-11-30 01:32:19,797]  INFO {cps.server:272} webserver stop (restart=True)
[2021-11-30 01:32:19,800]  INFO {cps.server:260} Performing restart of Calibre-Web
[2021-11-30 01:32:21,215]  INFO {cps:134} Starting Calibre Web...
[2021-11-30 01:32:21,313]  INFO {cps.server:204} Starting Gevent server on [::]:8083
[2021-11-30 01:32:42,766]  INFO {cps.web:1543} LDAP bind_user: simple_bind() argument 1 must be str or None, not dict
[2021-11-30 01:34:23,242]  INFO {cps.server:272} webserver stop (restart=True)
[2021-11-30 01:34:23,245]  INFO {cps.server:260} Performing restart of Calibre-Web
[2021-11-30 01:34:24,651]  INFO {cps:134} Starting Calibre Web...
[2021-11-30 01:34:24,780]  INFO {cps.server:204} Starting Gevent server on [::]:8083
[2021-11-30 01:37:27,291]  INFO {cps.server:272} webserver stop (restart=True)
[2021-11-30 01:37:27,295]  INFO {cps.server:260} Performing restart of Calibre-Web
[2021-11-30 01:37:28,703]  INFO {cps:134} Starting Calibre Web...
[2021-11-30 01:37:28,832]  INFO {cps.server:204} Starting Gevent server on [::]:8083
[2021-11-30 01:37:35,797]  INFO {cps.web:1543} LDAP bind_user: simple_bind() argument 1 must be str or None, not dict
[2021-11-30 01:51:28,651] DEBUG {cps.updater:332} Stable version: {'version': '0.6.14'}
```

**Expected behavior**
To be logged in.

**Screenshots**

![image](https://user-images.githubusercontent.com/6081511/143965350-b9551efe-649d-48cf-92fe-696f937bd680.png)

**Environment (please complete the following information):**
 - OS: CentOS Linux release 8.5.2111, running podman instead of docker
 - Python version: Python 3.8.10 (default, Sep 28 2021, 16:10:42)
 - Calibre-Web version: 0.6.14
 - Docker container: LinuxServer (docker.io/linuxserver/calibre-web:latest)
 - Browser: Firefox 94.0.2 (64-bit), running on Windows 10

**Additional context**
FreeIPA providing the ldap
nginx reverse proxy
~400 book library mounted read-only

**Comment by 1337joe** [comment]
Checking the box for "LDAP Server is OpenLDAP?" seems to have fixed it. Haven't dug into the code to see why, I initially stopped trying because the error message (passing the wrong type argument into a function) seemed like an implementation code error.
