### ISSUE TITLE
Internal Server Error while trying to access user table

### ISSUE THREAD

**Issue by blueochotona** [janeczku/calibre-web#2201]
After nightly build update : ,0.6.15 Beta - 87e526642cbbb2491ecdcf6c616479481ca817d0 - 2021-11-27T18:23:06+01:00

The following error is produced while trying to access the user table http://calibreweb/admin/usertable

Internal Server Error
500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
Traceback (most recent call last):
File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2073, in wsgi_app
response = self.full_dispatch_request()
File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1518, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1516, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1502, in dispatch_request
return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
File "/usr/local/lib/python3.8/dist-packages/flask_login/utils.py", line 272, in decorated_view
return func(*args, **kwargs)
File "/app/calibre-web/cps/admin.py", line 93, in inner
return f(*args, **kwargs)
File "/app/calibre-web/cps/admin.py", line 251, in edit_user_table
languages = calibre_db.speaking_language()
File "/app/calibre-web/cps/db.py", line 810, in speaking_language
return sorted(languages, key=lambda x: x.name, reverse=reverse_order)
TypeError: '<' not supported between instances of 'NoneType' and 'str'

**Comment by blueochotona** [comment]
[calibre-web.log](https://github.com/janeczku/calibre-web/files/7630869/calibre-web.log)

Attempting to go back the stable channel with 6.14 did not seem to resolve the issue.

**Comment by blueochotona** [comment]
Hey OzzielSaacs,

Thank you for helping with this :) Really appreciate it . 

I ran the library maintenance twice, deleting and clearing all unknown files etc, it came back clear.  Also deleted the identified book on May 15th .

Restarted the CalibreWeb Docker , but the issue remains. 

I have attached the db file here .
[metadata.zip](https://github.com/janeczku/calibre-web/files/7646281/metadata.zip)

**Comment by OzzieIsaacs** [comment]
The book with the language "chinese sign language" caused the problem. Updating to the newest nightly version will solve the issue, or changing/deleting the language of this book.
