### ISSUE TITLE
Converting AZW3 to EPUB 

### ISSUE THREAD

**Issue by Dinth** [janeczku/calibre-web#2216]
**Describe the bug/problem**
Its no longer possible to convert AZW3 books downloaded from Amazon to EPUB format. This functionality used to work fine in the past.

**To Reproduce**
1. Add an AZW3 book to calibre-web (it might be downloaded from Amazon)
2. Try to convert it to EPUB
3. The conversion fails almost instantly.

**Logfile**
```
[2021-12-11 06:33:34,963]  INFO {cps.editbooks:1080} converting: book id: 1053 from: AZW3 to: EPUB
[2021-12-11 06:33:34,981] DEBUG {cps.services.worker:88} Add Task for user: admin: <cps.tasks.convert.TaskConvert object at 0x7f9e1dfe01f0>
[2021-12-11 06:33:34,998]  INFO {cps.tasks.convert:125} Book id 1053 - target format of .epub does not exist. Moving forward with convert.
[2021-12-11 06:33:35,660] DEBUG {cps.tasks.convert:225} No write access to /root/.config/calibre using a temporary dir instead
[2021-12-11 06:33:35,808] DEBUG {cps.tasks.convert:225} 1% Converting input to HTML...
[2021-12-11 06:33:35,809] DEBUG {cps.tasks.convert:225} InputFormatPlugin: MOBI Input running
[2021-12-11 06:33:35,809] DEBUG {cps.tasks.convert:225} on /books/!Calibre/William Gibson/The Difference Engine (1053)/The Difference Engine - William Gibson.azw3
[2021-12-11 06:33:35,905] DEBUG {cps.tasks.convert:225} Found KF8 MOBI of type 'standalone'
[2021-12-11 06:33:36,139] DEBUG {cps.tasks.convert:225} 
[2021-12-11 06:33:36,139] DEBUG {cps.tasks.convert:238} Traceback (most recent call last):
[2021-12-11 06:33:36,140] DEBUG {cps.tasks.convert:238}   File "runpy.py", line 194, in _run_module_as_main
[2021-12-11 06:33:36,140] DEBUG {cps.tasks.convert:238}   File "runpy.py", line 87, in _run_code
[2021-12-11 06:33:36,140] DEBUG {cps.tasks.convert:238}   File "site.py", line 45, in <module>
[2021-12-11 06:33:36,140] DEBUG {cps.tasks.convert:238}   File "site.py", line 41, in main
[2021-12-11 06:33:36,140] DEBUG {cps.tasks.convert:238}   File "calibre/ebooks/conversion/cli.py", line 419, in main
[2021-12-11 06:33:36,140] DEBUG {cps.tasks.convert:238}   File "calibre/ebooks/conversion/plumber.py", line 1111, in run
[2021-12-11 06:33:36,141] DEBUG {cps.tasks.convert:238}   File "calibre/customize/conversion.py", line 244, in __call__
[2021-12-11 06:33:36,141] DEBUG {cps.tasks.convert:238}   File "calibre/ebooks/conversion/plugins/mobi_input.py", line 44, in convert
[2021-12-11 06:33:36,141] DEBUG {cps.tasks.convert:238}   File "calibre/ebooks/mobi/reader/mobi8.py", line 86, in __call__
[2021-12-11 06:33:36,141] DEBUG {cps.tasks.convert:238}   File "calibre/ebooks/mobi/reader/mobi6.py", line 163, in check_for_drm
[2021-12-11 06:33:36,142] DEBUG {cps.tasks.convert:238} calibre.ebooks.DRMError: The Difference Engine (S.F. MASTERWORKS)
[2021-12-11 06:33:36,143]  INFO {cps.tasks.convert:164} ebook converter failed with error while converting book
[2021-12-11 06:33:51,000] DEBUG {cps.updater:332} Stable version: {'version': '0.6.14'}
```

**Expected behavior**
The book should be converted. This functionality worked just a few months ago

**Environment (please complete the following information):**
 - OS: Linux 4.19.0-18-amd64 1 SMP Debian 4.19.208-1 (2021-09-29) x86_64 x86_64
 - Python version: 3.8.10 (default, Sep 28 2021, 16:10:42) [GCC 9.3.0]
 - Calibre-Web version: 0.6.14 - 4da64ceb23e69da3953f9c454ea261d9d0621e25 - 2021-10-31T11:31:53+01:00
 - Docker container: LinuxServer

**Comment by Dinth** [comment]
Also logged the bug on LinuxServer github: https://github.com/linuxserver/docker-calibre-web/issues/172

**Comment by OzzieIsaacs** [comment]
Sound like DRM error of the book `calibre.ebooks.drmerror`. Not a problem of calibre-web

**Comment by Dinth** [comment]
Thanks for the reply. Any workarounds you can propose, maybe a newer version of ebook-convert is required? At some point i have been converting all my books downloaded from Amazon without a problem, only now have an issue with this one.

**Comment by OzzieIsaacs** [comment]
I have no idea, as I‘m not the programmer of calibre itself, so maybe an older version of calibre could solve your problem

**Comment by Dinth** [comment]
So this is an upstream issue with calibre's tool? Do you think its worth logging a bug with them?

**Comment by OzzieIsaacs** [comment]
Maybe, never had this case before

**Comment by wgibcus** [comment]
> So this is an upstream issue with calibre's tool? Do you think its worth logging a bug with them?

You might need to investigate third party tools like Epubor to remove the DRM.
