### ISSUE TITLE
500 Internal Server Error: .... return get_language_names(locale)[lang_code] KeyError: 'hmj'

### ISSUE THREAD

**Issue by UlliHei** [janeczku/calibre-web#2217]
**Describe the bug/problem**
Using Synology Nas and Calibre Web with German language. Uploaded a mass of books with my calibre library in different languages.
Afterwards the error message appears, when opening e.g. User Profile or in Admin configuration the user configuration page
http://calibre:8083/me 
http://calibre:8083/admin/viewconfig
http://calibre:8083/admin/user/new

**To Reproduce**
see description

**Logfile**
Traceback (most recent call last):
File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2073, in wsgi_app
response = self.full_dispatch_request()
File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1518, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1516, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1502, in dispatch_request
return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
File "/usr/local/lib/python3.8/dist-packages/flask_login/utils.py", line 272, in decorated_view
return func(*args, **kwargs)
File "/app/calibre-web/cps/admin.py", line 93, in inner
return f(*args, **kwargs)
File "/app/calibre-web/cps/admin.py", line 1488, in new_user
languages = calibre_db.speaking_language()
File "/app/calibre-web/cps/db.py", line 809, in speaking_language
lang.name = isoLanguages.get_language_name(get_locale(), lang.lang_code)
File "/app/calibre-web/cps/isoLanguages.py", line 53, in get_language_name
return get_language_names(locale)[lang_code]
KeyError: 'hmj'

**Expected behavior**
no error, but the correct website is shown

**Screenshots**
not necessary

**Environment (please complete the following information):**
 - OS: Synology Nas Calibre-Web in Docker
 - Python version: [e.g. python3.8]
 - Calibre-Web version: 0.6.14
 - Docker container: linuxserver
 - Special Hardware: [e.g. Rasperry Pi Zero]
 - Browser: Chrome 96.0.4664.93

**Comment by OzzieIsaacs** [comment]
Please update to the newest nightly version. The problem should disappear then. Alternatively please remove the "Ge" language from all of your books, this would also work as workaround

**Comment by UlliHei** [comment]
Thanks, this worked, still the bug is visible within the log.
[2021-12-14 01:34:35,953] ERROR {cps.isoLanguages:59} Missing translation for language name: hmj

**Comment by OzzieIsaacs** [comment]
Can't reproduce this. Please make sure you are using the latest version form yesterday evening around 17:00 UTC
