### ISSUE TITLE
Calibre Web Internal Server Issue

### ISSUE THREAD

**Issue by jdude104** [janeczku/calibre-web#2226]
Got this error when going to login to my server, attempted to rebuild database but it did not solve the issue.

```
Internal Server Error  
500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.  
Traceback (most recent call last):  
File "/usr/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
response = self.full_dispatch_request()  
File "/usr/lib/python3.8/site-packages/flask/app.py", line 1518, in full_dispatch_request
rv = self.handle_user_exception(e)  
File "/usr/lib/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
rv = self.dispatch_request()  
File "/usr/lib/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request
return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)  
File "/calibre-web/app/cps/usermanagement.py", line 38, in decorated_view
return login_required(func)(*args, **kwargs)  
File "/usr/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
return func(*args, **kwargs)  
File "/calibre-web/app/cps/web.py", line 719, in index
return render_books_list("newest", sort_param, 1, page)  
File "/calibre-web/app/cps/web.py", line 422, in render_books_list
entries, random, pagination = calibre_db.fill_indexpage(page, 0, db.Books, True, order)  
File "/calibre-web/app/cps/db.py", line 610, in fill_indexpage
return self.fill_indexpage_with_archived_books(page, pagesize, database, db_filter, order, False, *join)  
File "/calibre-web/app/cps/db.py", line 623, in fill_indexpage_with_archived_books
query = self.session.query(database) \  
TypeError: join() missing 1 required positional argument: 'target'
```

**Comment by siddhartha1728** [comment]
First check your permission to db file and path where books are stored. Allow read write permission for all.
Stop the application and restart again.

**Comment by jdude104** [comment]
It seems like it does have read/write permissions. For context I am using docker to run it. Here is a startup log, noticed some errors about merging chnages, could those be the culprit?
https://gist.github.com/jdude104/429b80defb248f9648c40041b1082f7e

**Comment by jdude104** [comment]
Solved the issue with: 
`git reset --hard HEAD
git clean -f -d
git pull`
