### ISSUE TITLE
[Docker] AttributeError: 'NoneType' object has no attribute 'query'

### ISSUE THREAD

**Issue by deeztek** [janeczku/calibre-web#2231]
**Describe the bug/problem**
After I login to calibre-web I get an Internal Server error

**To Reproduce**
Login 

**Logfile**
Traceback (most recent call last):
File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2073, in wsgi_app
response = self.full_dispatch_request()
File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1518, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1516, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1502, in dispatch_request
return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
File "/app/calibre-web/cps/usermanagement.py", line 38, in decorated_view
return login_required(func)(*args, **kwargs)
File "/usr/local/lib/python3.8/dist-packages/flask_login/utils.py", line 272, in decorated_view
return func(*args, **kwargs)
File "/app/calibre-web/cps/web.py", line 744, in index
return render_books_list("newest", sort_param, 1, page)
File "/app/calibre-web/cps/web.py", line 408, in render_books_list
entries, random, pagination = calibre_db.fill_indexpage(page, 0, db.Books, True, order,
File "/app/calibre-web/cps/db.py", line 679, in fill_indexpage
return self.fill_indexpage_with_archived_books(page, pagesize, database, db_filter, order, False, *join)
File "/app/calibre-web/cps/db.py", line 685, in fill_indexpage_with_archived_books
randm = self.session.query(Books) \
AttributeError: 'NoneType' object has no attribute 'query'

**Expected behavior**
Expect to login and see my book library

**Screenshots**
N/A

**Environment (please complete the following information):**
 - OS: Ubuntu 
 - Python version: No clue
 - Calibre-Web version: [e.g. 0.6.8 or 087c4c59 (git rev-parse --short HEAD)]:
 - Docker container: [None/LinuxServer]: LinuxServer
 - Special Hardware:
 - Browser:Chrome

**Additional context**
Access with Traefik reverse proxy. However, accessing through port 8085 produces the same result

**Comment by OzzieIsaacs** [comment]
Looks to me like some access problem to your metadata.db database. Please ask for help at the LinuxServer Docker repository.

**Comment by Athanor66** [comment]
I solved the problem by adding the user and the **docker** group to the ACL of the folder containing the metadata.db file.
If you see into the log file, you can find something similar to this:
```
[2023-01-27 17:41:59,734] ERROR {cps.config_sql:357} (sqlite3.OperationalError) _unable to open database: /riviste/metadata.db_
[SQL: attach database '/riviste/metadata.db' as calibre;]
```
Try these commands in a ssh shell:
`getfacl /Volume2/BIBLIOTECHE/RIVISTE/ `  <---- your Calibre folder, where is the metadata.db file
if "docker" isn't present in the ACL, add it with these commands:
```
setfacl -m u:docker:wrx /Volume2/BIBLIOTECHE/RIVISTE/
setfacl -m g:docker:wrx /Volume2/BIBLIOTECHE/RIVISTE/
```

Then restart your calibre-web docker component e voilà, it works!
