### ISSUE TITLE
Can't revoke Metadata Watch

### ISSUE THREAD

**Issue by jagalile** [janeczku/calibre-web#2233]
**Describe the bug/problem**
I have a setup with GDrive (where I have all the books), I configured the Metadata Watch Channel ID and now the token has expired, when I want to revoke it the server returns an error 500.

![image](https://user-images.githubusercontent.com/17300743/147051114-83c89e03-a885-4e7f-a542-0ee2de111997.png)

**Logfile**
```
[2021-12-22 07:08:07,452]  INFO {oauth2client.client:777} Refreshing access_token
[2021-12-22 07:08:07,464]  INFO {oauth2client.client:806} Failed to retrieve access token: {
  "error": "invalid_grant",
  "error_description": "Token has been expired or revoked."
}
[2021-12-22 07:08:07,464]  INFO {cps.gdriveutils:234} GDrive Error Access token refresh failed: invalid_grant: Token has been expired or revoked.
[2021-12-22 07:08:45,110] ERROR {cps:1457} Exception on /gdrive/watch/revoke [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/local/lib/python3.8/dist-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/-----/calibre-web/cps/admin.py", line 93, in inner
    return f(*args, **kwargs)
  File "/home/-----/calibre-web/cps/gdrive.py", line 110, in revoke_watch_gdrive
    gdriveutils.stopChannel(gdriveutils.Gdrive.Instance().drive, last_watch_response['id'],
  File "/home/-----/calibre-web/cps/gdriveutils.py", line 504, in stopChannel
    return drive.auth.service.channels().stop(body=body).execute()
AttributeError: 'NoneType' object has no attribute 'channels'
```

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04
 - Python version: python3
 - Calibre-Web version: Nightly last
 - Docker container: None
 - Browser: Chrome

**Comment by jagalile** [comment]
This also makes it impossible for me to download books or view covers

**Cover error**
![image](https://user-images.githubusercontent.com/17300743/147052202-d287c6f8-f79f-43f3-8cfc-ee984630d675.png)

**Download fail**
```
[2021-12-22 07:21:37,151] ERROR {cps:1457} Exception on /download/3020/epub/3020.epub [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/pydrive2/auth.py", line 563, in Refresh
    self.credentials.refresh(self.http)
  File "/usr/local/lib/python3.8/dist-packages/oauth2client/client.py", line 545, in refresh
    self._refresh(http)
  File "/usr/local/lib/python3.8/dist-packages/oauth2client/client.py", line 761, in _refresh
    self._do_refresh_request(http)
  File "/usr/local/lib/python3.8/dist-packages/oauth2client/client.py", line 819, in _do_refresh_request
    raise HttpAccessTokenRefreshError(error_msg, status=resp.status)
oauth2client.client.HttpAccessTokenRefreshError: invalid_grant: Token has been expired or revoked.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/javier_galilea_pesos/calibre-web/cps/usermanagement.py", line 38, in decorated_view
    return login_required(func)(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/javier_galilea_pesos/calibre-web/cps/web.py", line 109, in inner
    return f(*args, **kwargs)
  File "/home/javier_galilea_pesos/calibre-web/cps/web.py", line 1435, in download_link
    return get_download_link(book_id, book_format, client)
  File "/home/javier_galilea_pesos/calibre-web/cps/helper.py", line 844, in get_download_link
    return do_download_file(book, book_format, client, data1, headers)
  File "/home/javier_galilea_pesos/calibre-web/cps/helper.py", line 677, in do_download_file
    df = gd.getFileFromEbooksFolder(book.path, data.name + "." + book_format)
  File "/home/javier_galilea_pesos/calibre-web/cps/gdriveutils.py", line 336, in getFileFromEbooksFolder
    return getFile(folderId, fileName, drive)
  File "/home/javier_galilea_pesos/calibre-web/cps/gdriveutils.py", line 280, in getFile
    fileList = drive.ListFile({'q': metaDataFile}).GetList()
  File "/usr/local/lib/python3.8/dist-packages/pydrive2/apiattr.py", line 166, in GetList
    for x in self:
  File "/usr/local/lib/python3.8/dist-packages/pydrive2/apiattr.py", line 150, in __next__
    result = self._GetList()
  File "/usr/local/lib/python3.8/dist-packages/pydrive2/auth.py", line 60, in _decorated
    self.auth.LocalWebserverAuth()
  File "/usr/local/lib/python3.8/dist-packages/pydrive2/auth.py", line 130, in _decorated
    self.Refresh()
  File "/usr/local/lib/python3.8/dist-packages/pydrive2/auth.py", line 565, in Refresh
    raise RefreshError("Access token refresh failed: %s" % error)
pydrive2.auth.RefreshError: Access token refresh failed: invalid_grant: Token has been expired or revoked.
```

**Comment by OzzieIsaacs** [comment]
I don't think an empty Calibre folder is working on GDrive:
![image](https://user-images.githubusercontent.com/6438895/147222116-d483d5df-325e-4c62-8b53-d426968d5841.png)
With the empty folder you have no more a valid calibre database configured and therefore no covers. Please fix this first and maybe disable "use google drive" and try to tick it afterwards and do the config again. It should work then again. I'll try to reproduce the problem

**Comment by OzzieIsaacs** [comment]
1) I'm now catching the error messages you posted, so you no longer see the internal server error page, this should lead to the case that you should be able to revoke the metadata watch (I could not reproduce this error). 
2) If I remove all folders on my gdrive I can also get to a configuration page with emtpy Google Drive Calibre folder, but this seems not your problem. Anyhow errors related to this one are now also catched. If I try to download a file in this case and the file is not listed in gdrive.db (file was never changed or downloaded before) I also got a traceback, this is now also catched. But not your problem. 
It looks like for a unknown reason you can not renew the authentication token (no internet connection?, google is blocked from your server? or like the error message suggested you have revoked the access token?)

**Comment by OzzieIsaacs** [comment]
I tried to reproduce the error, but I didn't succeed.

**Comment by jagalile** [comment]
I had the library directory configured, I guess it must have been deconfigured. If I remove the use of GDrive and put it back it doesn't let me select any directory.

The cover issue may be because of that, but I have to say that it wasn't working properly for me before either. Anyway I will try to sort out the GDrive connection first. It seems that the GDrive configuration is not responding, in the Google console I haven't modified anything. If there has been any change it is changing the update from stable to nightly.

I don't know if there is any way to reset the configuration and try to do it again. I have updated the user, calve and api authentication json, it still does not allow me to select the GDrive library directory.

![image](https://user-images.githubusercontent.com/17300743/147228601-3c2191e9-aaea-4685-9091-e9afccd005e8.png)

If you need more data, logs or images, let me know.

**Comment by OzzieIsaacs** [comment]
If you "untick" Use Google Drive -> save -> remove (+ backup) gdrive_credentials file (maybe restart calibre-web to be sure) and then tick use Google Drive it should present you the authenticate button back and you should be able to generate a new token

**Comment by OzzieIsaacs** [comment]
I'm not sure if this could be related: Please also ensure that your callback URL is showing up as verified in google console

**Comment by jagalile** [comment]
> If you "untick" Use Google Drive -> save -> remove (+ backup) gdrive_credentials file (maybe restart calibre-web to be sure) and then tick use Google Drive it should present you the authenticate button back and you should be able to generate a new token

This has worked perfectly. Thank you very much for the support.

Now I have the problem with the covers that happened to me before. I don't know if I should close this issue and open another one or if I can continue here, just in case I expose the problem. If you think you have to close it go ahead, I will open a specific one for it.

I can not see the covers of the books, it is an intermittent error, because from time to time when I enter the library I can see them, but if I browse for a while they end up failing. I can't identify the error, since I don't see anything in the logs.

![image](https://user-images.githubusercontent.com/17300743/147235298-5dd43247-9cf5-4fd4-a2f3-246763e91daf.png)

**Logs**
`[2021-12-23 11:22:31,081]  INFO {cps.server:272} webserver stop (restart=True)
[2021-12-23 11:22:32,249]  INFO {cps.server:260} Performing restart of Calibre-Web
[2021-12-23 11:22:35,708] DEBUG {cps.services:35} Cannot import simpleldap, logging in with ldap will not work: No module named 'flask_simpleldap'
[2021-12-23 11:22:41,596]  INFO {cps:133} *** "requests" version does not fit the requirements. Should: <2.25.0, Found: 2.25.0, please consider installing required version ***
[2021-12-23 11:22:41,598]  INFO {cps:141} Starting Calibre Web...
[2021-12-23 11:22:42,032]  INFO {cps.server:204} Starting Gevent server on [::]:443
[2021-12-23 11:22:53,110] DEBUG {cps.updater:326} Nightly version: bdedec90dd8df032cbc666a26618f17bcde3b6ea, 2021-12-23T11:13:08+01:00
[2021-12-23 11:23:01,129] DEBUG {cps.config_sql:337} _ConfigSQL updating storage
[2021-12-23 11:23:18,330]  INFO {oauth2client.client:2074} Successfully retrieved access token
[2021-12-23 11:23:23,588] DEBUG {cps.config_sql:337} _ConfigSQL updating storage
[2021-12-23 11:23:42,198] DEBUG {cps.updater:326} Nightly version: bdedec90dd8df032cbc666a26618f17bcde3b6ea, 2021-12-23T11:13:08+01:00
[2021-12-23 11:32:49,756] DEBUG {cps.updater:326} Nightly version: bdedec90dd8df032cbc666a26618f17bcde3b6ea, 2021-12-23T11:13:08+01:00`

**Comment by OzzieIsaacs** [comment]
Let's open a new issue
