### ISSUE TITLE
Unsupported book language "dse"

### ISSUE THREAD

**Issue by hokjes** [janeczku/calibre-web#2253]
**Describe the bug/problem**
When I want to edit a user then the internal server error appears. The same happens when trying to click on languages for selection of book languages

**To Reproduce**
1. Go to Users
2. Click on a user
or
3. click on languages in the explorer section

**Logfile**
Traceback (most recent call last):
File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2073, in wsgi_app
response = self.full_dispatch_request()
File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1518, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1516, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1502, in dispatch_request
return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
File "/app/calibre-web/cps/usermanagement.py", line 38, in decorated_view
return login_required(func)(*args, **kwargs)
File "/usr/local/lib/python3.8/dist-packages/flask_login/utils.py", line 272, in decorated_view
return func(*args, **kwargs)
File "/app/calibre-web/cps/web.py", line 993, in language_overview
languages = calibre_db.speaking_language()
File "/app/calibre-web/cps/db.py", line 809, in speaking_language
lang.name = isoLanguages.get_language_name(get_locale(), lang.lang_code)
File "/app/calibre-web/cps/isoLanguages.py", line 53, in get_language_name
return get_language_names(locale)[lang_code]
KeyError: 'dse'

Linuxserver docker on synology and calibre-web 0.6.14

**Comment by OzzieIsaacs** [comment]
Please update to the newest nightly version then the error disapears. Instead you will see books with language "unkown", where they are actually having "dutch sign language". I will add this to the supported languages

**Comment by OzzieIsaacs** [comment]
Fixed in the newest nightly version
