### ISSUE TITLE
cps hangs with AttributeError: module 'pyparsing' has no attribute 'downcaseTokens

### ISSUE THREAD

**Issue by dscharalampidis** [janeczku/calibre-web#2260]
**Describe the bug/problem**
A clear and concise description of what the bug is. If you are asking for support, please check our [Wiki](https://github.com/janeczku/calibre-web/wiki) if your question is already answered there.

**To Reproduce**
After a recent system update, running 'cps' hangs.

**Logfile**
$ Traceback (most recent call last):
  File "/home/dscharalampidis/.local/bin/cps", line 5, in <module>
    from calibreweb import main
  File "/home/dscharalampidis/.local/lib/python3.9/site-packages/calibreweb/__init__.py", line 31, in <module>
    from cps.opds import opds
  File "/home/dscharalampidis/.local/lib/python3.9/site-packages/calibreweb/cps/opds.py", line 33, in <module>
    from .helper import get_download_link, get_book_cover
  File "/home/dscharalampidis/.local/lib/python3.9/site-packages/calibreweb/cps/helper.py", line 54, in <module>
    from .tasks.convert import TaskConvert
  File "/home/dscharalampidis/.local/lib/python3.9/site-packages/calibreweb/cps/tasks/convert.py", line 36, in <module>
    from cps.tasks.mail import TaskEmail
  File "/home/dscharalampidis/.local/lib/python3.9/site-packages/calibreweb/cps/tasks/mail.py", line 47, in <module>
    from cps import gdriveutils
  File "/home/dscharalampidis/.local/lib/python3.9/site-packages/calibreweb/cps/gdriveutils.py", line 39, in <module>
    from apiclient import errors
  File "/home/dscharalampidis/.local/lib/python3.9/site-packages/apiclient/__init__.py", line 8, in <module>
    from googleapiclient import discovery
  File "/home/dscharalampidis/.local/lib/python3.9/site-packages/googleapiclient/discovery.py", line 48, in <module>
    import httplib2
  File "/home/dscharalampidis/.local/lib/python3.9/site-packages/httplib2/__init__.py", line 52, in <module>
    from . import auth
  File "/home/dscharalampidis/.local/lib/python3.9/site-packages/httplib2/auth.py", line 20, in <module>
    auth_param_name = token.copy().setName("auth-param-name").addParseAction(pp.downcaseTokens)
AttributeError: module 'pyparsing' has no attribute 'downcaseTokens'

**Expected behavior**
The service should start normally.

**Environment (please complete the following information):**
 - OS: 5.15.11-gentoo-x86_64 
 - Python version: python3.9
 - Calibre-Web version: 0.6.14
 - Docker container: None
 - Special Hardware: None

**Comment by OzzieIsaacs** [comment]
Please check your versions of pyparsing and/or httplib2.
Either pyparsing <3.0 or httplib>0.20.2 should work

**Comment by dscharalampidis** [comment]
I was running `httplib2-0.19.1', upgrading to 'httplib2-0.20.2' did the trick.
Thank you very much!
