### ISSUE TITLE
No web access on Synology after v0.6.8

### ISSUE THREAD

**Issue by Niaw** [janeczku/calibre-web#2269]
Hello,

## Expected Behavior
When loading the web page, it should display the calibre-web web page.

## Current Behavior
Instead, it display an error (my OS is in French, so the message too):
La connexion a été réinitialisée
La connexion avec le serveur a été réinitialisée pendant le chargement de la page.
- Le site est peut-être temporairement indisponible ou surchargé. Réessayez plus tard ;
- Si vous n’arrivez à naviguer sur aucun site, vérifiez la connexion au réseau de votre ordinateur ;
- Si votre ordinateur ou votre réseau est protégé par un pare-feu ou un proxy, assurez-vous que Firefox est autorisé à accéder au Web.

## Steps to Reproduce
1. Update to a superior version, like linuxserver/calibre-web:amd64-version-0.6.9 or newer
2. No change to the working (and simple) configuration
3. Try to load the webpage: http://<IP>:8083/
4. The error message appear
5. When going back to linuxserver/calibre-web:amd64-0.6.8-ls80 it is working again

## Environment
**OS:** Synology DSM 6.2.4-25556 Update 2 (on Synology DS1812+)
**CPU architecture:** x86_64 (Intel Atom D2700 CPU)
**How docker service was installed:** last version of the official Synology package (NAS OS provided)

## Command used to create docker container (run/create/compose/screenshot)

GUI used, but after, I have exported, then imported the configuration json file, only changing the image name in the json file to match the container image downloaded.
But I have tried multiple methods, and multiple parameters, cleaning the files between each test.
{
   "cap_add" : [],
   "cap_drop" : [],
   "cmd" : "",
   "cpu_priority" : 50,
   "devices" : null,
   "enable_publish_all_ports" : false,
   "enable_restart_policy" : true,
   "enabled" : false,
   "entrypoint_default" : "/init",
   "env_variables" : [
      {
         "key" : "PATH",
         "value" : "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      },
      {
         "key" : "HOME",
         "value" : "/root"
      },
      {
         "key" : "LANGUAGE",
         "value" : "en_US.UTF-8"
      },
      {
         "key" : "LANG",
         "value" : "en_US.UTF-8"
      },
      {
         "key" : "TERM",
         "value" : "xterm"
      },
      {
         "key" : "PUID",
         "value" : "1085"
      },
      {
         "key" : "PGID",
         "value" : "65549"
      },
      {
         "key" : "TZ",
         "value" : "Indian/Reunion"
      }
   ],
   "exporting" : false,
   "id" : "16d51417c4d94e35647be1b6b1e57104db01923a7319009c8198d6f1a568f748",
   "image" : "linuxserver/calibre-web:amd64-0.6.8-ls80",
   "is_ddsm" : false,
   "is_package" : false,
   "links" : [],
   "memory_limit" : 536870912,
   "memory_limit_slider" : 512,
   "name" : "Calibre-Web",
   "network" : [
      {
         "driver" : "bridge",
         "name" : "bridge"
      }
   ],
   "network_mode" : "bridge",
   "port_bindings" : [
      {
         "container_port" : 8083,
         "host_port" : 8083,
         "type" : "tcp"
      }
   ],
   "privileged" : false,
   "shortcut" : {
      "enable_shortcut" : false
   },
   "use_host_network" : false,
   "volume_bindings" : [
      {
         "host_volume_file" : "/reading/books",
         "mount_point" : "/books",
         "type" : "rw"
      },
      {
         "host_volume_file" : "/docker/calibre-web/config",
         "mount_point" : "/config",
         "type" : "rw"
      }
   ]
}

I have the exact same result with this docker-compose.yml:
version: "2.1"
services:
    calibre-web:
        image: linuxserver/calibre-web:amd64-0.6.8-ls80
        container_name: Calibre-Web
        environment:
            - PUID=1085
            - PGID=65549
            - TZ=Indian/Reunion
        volumes:
            - /volume1/docker/calibre-web/config:/config
            - /volume1/reading/books:/books
        ports:
            - 8083:8083
        restart: unless-stopped

This one works, but every version after, latest, or amd64-latest, or 0.6.9... doesn't work.

## Docker logs

(new to old)
2021-10-04 18:19:48	stdout	fake_useragent.errors.FakeUserAgentError: Maximum amount of retries reached
2021-10-04 18:19:48	stdout	    raise FakeUserAgentError('Maximum amount of retries reached')
2021-10-04 18:19:48	stdout	  File "/usr/local/lib/python3.8/dist-packages/fake_useragent/utils.py", line 84, in get
2021-10-04 18:19:48	stdout	    ret = json.loads(get(
2021-10-04 18:19:48	stdout	  File "/usr/local/lib/python3.8/dist-packages/fake_useragent/utils.py", line 187, in load
2021-10-04 18:19:48	stdout	    write(path, load(use_cache_server=use_cache_server, verify_ssl=verify_ssl))
2021-10-04 18:19:48	stdout	  File "/usr/local/lib/python3.8/dist-packages/fake_useragent/utils.py", line 245, in update
2021-10-04 18:19:48	stdout	    update(path, use_cache_server=use_cache_server, verify_ssl=verify_ssl)
2021-10-04 18:19:48	stdout	  File "/usr/local/lib/python3.8/dist-packages/fake_useragent/utils.py", line 250, in load_cached
2021-10-04 18:19:48	stdout	    self.data = load_cached(
2021-10-04 18:19:48	stdout	  File "/usr/local/lib/python3.8/dist-packages/fake_useragent/fake.py", line 75, in load
2021-10-04 18:19:48	stdout	    self.load()
2021-10-04 18:19:48	stdout	  File "/usr/local/lib/python3.8/dist-packages/fake_useragent/fake.py", line 69, in __init__
2021-10-04 18:19:48	stdout	    'User-Agent': UserAgent().random,
2021-10-04 18:19:48	stdout	  File "/usr/local/lib/python3.8/dist-packages/scholarly/_proxy_generator.py", line 368, in _new_session
2021-10-04 18:19:48	stdout	    self._new_session()
2021-10-04 18:19:48	stdout	  File "/usr/local/lib/python3.8/dist-packages/scholarly/_proxy_generator.py", line 54, in __init__
2021-10-04 18:19:48	stdout	    self.pm = ProxyGenerator()
2021-10-04 18:19:48	stdout	  File "/usr/local/lib/python3.8/dist-packages/scholarly/_navigator.py", line 59, in __init__
2021-10-04 18:19:48	stdout	    cls._instances[cls] = super(Singleton, cls).__call__(*args,
2021-10-04 18:19:48	stdout	  File "/usr/local/lib/python3.8/dist-packages/scholarly/_navigator.py", line 45, in __call__
2021-10-04 18:19:48	stdout	    self.__nav = Navigator()
2021-10-04 18:19:48	stdout	  File "/usr/local/lib/python3.8/dist-packages/scholarly/_scholarly.py", line 27, in __init__
2021-10-04 18:19:48	stdout	    scholarly = _Scholarly()
2021-10-04 18:19:47	stdout	  File "/usr/local/lib/python3.8/dist-packages/scholarly/__init__.py", line 4, in <module>
2021-10-04 18:19:47	stdout	    from scholarly import scholarly
2021-10-04 18:19:47	stdout	  File "/app/calibre-web/cps/about.py", line 58, in <module>
2021-10-04 18:19:47	stdout	    from cps.about import about
2021-10-04 18:19:47	stdout	  File "/app/calibre-web/cps.py", line 39, in <module>
2021-10-04 18:19:47	stdout	Traceback (most recent call last):
2021-10-04 18:19:47	stdout	
2021-10-04 18:19:47	stdout	During handling of the above exception, another exception occurred:
2021-10-04 18:19:47	stdout	
2021-10-04 18:19:47	stdout	urllib.error.URLError: <urlopen error [Errno -3] Temporary failure in name resolution>
2021-10-04 18:19:47	stdout	    raise URLError(err)
2021-10-04 18:19:47	stdout	  File "/usr/lib/python3.8/urllib/request.py", line 1357, in do_open
2021-10-04 18:19:47	stdout	    return self.do_open(http.client.HTTPSConnection, req,
2021-10-04 18:19:47	stdout	  File "/usr/lib/python3.8/urllib/request.py", line 1397, in https_open
2021-10-04 18:19:47	stdout	    result = func(*args)
2021-10-04 18:19:47	stdout	  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
2021-10-04 18:19:47	stdout	    result = self._call_chain(self.handle_open, protocol, protocol +
2021-10-04 18:19:47	stdout	  File "/usr/lib/python3.8/urllib/request.py", line 542, in _open
2021-10-04 18:19:47	stdout	    response = self._open(req, data)
2021-10-04 18:19:47	stdout	  File "/usr/lib/python3.8/urllib/request.py", line 525, in open
2021-10-04 18:19:47	stdout	    return opener.open(url, data, timeout)
2021-10-04 18:19:47	stdout	  File "/usr/lib/python3.8/urllib/request.py", line 222, in urlopen
2021-10-04 18:19:47	stdout	    with contextlib.closing(urlopen(
2021-10-04 18:19:47	stdout	  File "/usr/local/lib/python3.8/dist-packages/fake_useragent/utils.py", line 64, in get
2021-10-04 18:19:47	stdout	Traceback (most recent call last):
2021-10-04 18:19:47	stdout	
2021-10-04 18:19:47	stdout	During handling of the above exception, another exception occurred:
2021-10-04 18:19:47	stdout	
2021-10-04 18:19:47	stdout	socket.gaierror: [Errno -3] Temporary failure in name resolution
2021-10-04 18:19:47	stdout	    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
2021-10-04 18:19:47	stdout	  File "/usr/lib/python3.8/socket.py", line 918, in getaddrinfo
2021-10-04 18:19:47	stdout	    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
2021-10-04 18:19:47	stdout	  File "/usr/lib/python3.8/socket.py", line 787, in create_connection
2021-10-04 18:19:47	stdout	    self.sock = self._create_connection(
2021-10-04 18:19:47	stdout	  File "/usr/lib/python3.8/http/client.py", line 918, in connect
2021-10-04 18:19:47	stdout	    super().connect()
2021-10-04 18:19:47	stdout	  File "/usr/lib/python3.8/http/client.py", line 1414, in connect
2021-10-04 18:19:47	stdout	    self.connect()
2021-10-04 18:19:47	stdout	  File "/usr/lib/python3.8/http/client.py", line 947, in send
2021-10-04 18:19:47	stdout	    self.send(msg)
2021-10-04 18:19:47	stdout	  File "/usr/lib/python3.8/http/client.py", line 1007, in _send_output
2021-10-04 18:19:47	stdout	    self._send_output(message_body, encode_chunked=encode_chunked)
2021-10-04 18:19:47	stdout	  File "/usr/lib/python3.8/http/client.py", line 1247, in endheaders
2021-10-04 18:19:47	stdout	    self.endheaders(body, encode_chunked=encode_chunked)
2021-10-04 18:19:47	stdout	  File "/usr/lib/python3.8/http/client.py", line 1298, in _send_request
2021-10-04 18:19:47	stdout	    self._send_request(method, url, body, headers, encode_chunked)
2021-10-04 18:19:47	stdout	  File "/usr/lib/python3.8/http/client.py", line 1252, in request
2021-10-04 18:19:47	stdout	    h.request(req.get_method(), req.selector, req.data, headers,
2021-10-04 18:19:47	stdout	  File "/usr/lib/python3.8/urllib/request.py", line 1354, in do_open
2021-10-04 18:19:47	stdout	Traceback (most recent call last):
2021-10-04 18:19:47	stdout	
2021-10-04 18:19:47	stdout	During handling of the above exception, another exception occurred:
2021-10-04 18:19:47	stdout	
2021-10-04 18:19:47	stdout	fake_useragent.errors.FakeUserAgentError: Maximum amount of retries reached
2021-10-04 18:19:47	stdout	    raise FakeUserAgentError('Maximum amount of retries reached')
2021-10-04 18:19:47	stdout	  File "/usr/local/lib/python3.8/dist-packages/fake_useragent/utils.py", line 84, in get
2021-10-04 18:19:47	stdout	    html = get(settings.BROWSERS_STATS_PAGE, verify_ssl=verify_ssl)
2021-10-04 18:19:47	stdout	  File "/usr/local/lib/python3.8/dist-packages/fake_useragent/utils.py", line 97, in get_browsers
2021-10-04 18:19:47	stdout	    for item in get_browsers(verify_ssl=verify_ssl):
2021-10-04 18:19:47	stdout	  File "/usr/local/lib/python3.8/dist-packages/fake_useragent/utils.py", line 154, in load
2021-10-04 18:19:47	stdout	Traceback (most recent call last):
2021-10-04 18:19:47	stdout	
2021-10-04 18:19:47	stdout	During handling of the above exception, another exception occurred:
2021-10-04 18:19:47	stdout	
2021-10-04 18:19:47	stdout	urllib.error.URLError: <urlopen error [Errno -3] Temporary failure in name resolution>
2021-10-04 18:19:47	stdout	    raise URLError(err)
2021-10-04 18:19:47	stdout	  File "/usr/lib/python3.8/urllib/request.py", line 1357, in do_open
2021-10-04 18:19:47	stdout	    return self.do_open(http.client.HTTPSConnection, req,
2021-10-04 18:19:47	stdout	  File "/usr/lib/python3.8/urllib/request.py", line 1397, in https_open
2021-10-04 18:19:47	stdout	    result = func(*args)
2021-10-04 18:19:47	stdout	  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
2021-10-04 18:19:47	stdout	    result = self._call_chain(self.handle_open, protocol, protocol +
2021-10-04 18:19:47	stdout	  File "/usr/lib/python3.8/urllib/request.py", line 542, in _open
2021-10-04 18:19:47	stdout	    response = self._open(req, data)
2021-10-04 18:19:47	stdout	  File "/usr/lib/python3.8/urllib/request.py", line 525, in open
2021-10-04 18:19:47	stdout	    return opener.open(url, data, timeout)
2021-10-04 18:19:47	stdout	  File "/usr/lib/python3.8/urllib/request.py", line 222, in urlopen
2021-10-04 18:19:47	stdout	    with contextlib.closing(urlopen(
2021-10-04 18:19:47	stdout	  File "/usr/local/lib/python3.8/dist-packages/fake_useragent/utils.py", line 64, in get
2021-10-04 18:19:47	stdout	Traceback (most recent call last):
2021-10-04 18:19:47	stdout	
2021-10-04 18:19:47	stdout	During handling of the above exception, another exception occurred:
2021-10-04 18:19:47	stdout	
2021-10-04 18:19:47	stdout	socket.gaierror: [Errno -3] Temporary failure in name resolution
2021-10-04 18:19:47	stdout	    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
2021-10-04 18:19:47	stdout	  File "/usr/lib/python3.8/socket.py", line 918, in getaddrinfo
2021-10-04 18:19:47	stdout	    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
2021-10-04 18:19:47	stdout	  File "/usr/lib/python3.8/socket.py", line 787, in create_connection
2021-10-04 18:19:47	stdout	    self.sock = self._create_connection(
2021-10-04 18:19:47	stdout	  File "/usr/lib/python3.8/http/client.py", line 918, in connect
2021-10-04 18:19:47	stdout	    super().connect()
2021-10-04 18:19:47	stdout	  File "/usr/lib/python3.8/http/client.py", line 1414, in connect
2021-10-04 18:19:47	stdout	    self.connect()
2021-10-04 18:19:47	stdout	  File "/usr/lib/python3.8/http/client.py", line 947, in send
2021-10-04 18:19:47	stdout	    self.send(msg)
2021-10-04 18:19:47	stdout	  File "/usr/lib/python3.8/http/client.py", line 1007, in _send_output
2021-10-04 18:19:47	stdout	    self._send_output(message_body, encode_chunked=encode_chunked)
2021-10-04 18:19:47	stdout	  File "/usr/lib/python3.8/http/client.py", line 1247, in endheaders
2021-10-04 18:19:47	stdout	    self.endheaders(body, encode_chunked=encode_chunked)
2021-10-04 18:19:47	stdout	  File "/usr/lib/python3.8/http/client.py", line 1298, in _send_request
2021-10-04 18:19:47	stdout	    self._send_request(method, url, body, headers, encode_chunked)
2021-10-04 18:19:47	stdout	  File "/usr/lib/python3.8/http/client.py", line 1252, in request
2021-10-04 18:19:47	stdout	    h.request(req.get_method(), req.selector, req.data, headers,
2021-10-04 18:19:47	stdout	  File "/usr/lib/python3.8/urllib/request.py", line 1354, in do_open
2021-10-04 18:19:47	stdout	Traceback (most recent call last):
2021-10-04 18:18:03	stdout	[services.d] done.
2021-10-04 18:18:03	stdout	[services.d] starting services
2021-10-04 18:18:03	stdout	[cont-init.d] done.
2021-10-04 18:18:03	stdout	[cont-init.d] 99-custom-scripts: exited 0.
2021-10-04 18:18:03	stdout	[custom-init] no custom files found exiting...
2021-10-04 18:18:03	stdout	[cont-init.d] 99-custom-scripts: executing... 
2021-10-04 18:18:03	stdout	[cont-init.d] 90-custom-folders: exited 0.
2021-10-04 18:18:03	stdout	[cont-init.d] 90-custom-folders: executing... 
2021-10-04 18:18:03	stdout	[cont-init.d] 30-config: exited 0.
2021-10-04 18:17:58	stdout	[cont-init.d] 30-config: executing... 
2021-10-04 18:17:58	stdout	[cont-init.d] 10-adduser: exited 0.
2021-10-04 18:17:58	stdout	
2021-10-04 18:17:58	stdout	-------------------------------------
2021-10-04 18:17:58	stdout	User gid:    65549
2021-10-04 18:17:58	stdout	User uid:    1085
2021-10-04 18:17:58	stdout	
2021-10-04 18:17:58	stdout	-------------------------------------
2021-10-04 18:17:58	stdout	GID/UID
2021-10-04 18:17:58	stdout	-------------------------------------
2021-10-04 18:17:58	stdout	https://www.linuxserver.io/donate/
2021-10-04 18:17:58	stdout	To support LSIO projects visit:
2021-10-04 18:17:58	stdout	
2021-10-04 18:17:58	stdout	-------------------------------------
2021-10-04 18:17:58	stdout	Brought to you by linuxserver.io
2021-10-04 18:17:58	stdout	
2021-10-04 18:17:58	stdout	
2021-10-04 18:17:58	stdout	         |_| |___/ |_|  \__/
2021-10-04 18:17:58	stdout	         | | \__ \ | | | () |
2021-10-04 18:17:58	stdout	         | | / __| | |  /  \
2021-10-04 18:17:58	stdout	         | |  ___   _    __
2021-10-04 18:17:58	stdout	          _         ()
2021-10-04 18:17:58	stdout	-------------------------------------
2021-10-04 18:17:58	stdout	
2021-10-04 18:17:58	stdout	[cont-init.d] 10-adduser: executing... 
2021-10-04 18:17:58	stdout	[cont-init.d] 01-envfile: exited 0.
2021-10-04 18:17:58	stdout	[cont-init.d] 01-envfile: executing... 
2021-10-04 18:17:58	stdout	[cont-init.d] executing container initialization scripts...
2021-10-04 18:17:58	stdout	[fix-attrs.d] done.
2021-10-04 18:17:58	stdout	[fix-attrs.d] applying ownership & permissions fixes...
2021-10-04 18:17:58	stdout	[s6-init] ensuring user provided files have correct perms...exited 0.
2021-10-04 18:17:58	stdout	[s6-init] making user provided files available at /var/run/s6/etc...exited 0.

**Comment by OzzieIsaacs** [comment]
Please ask for help at the linuxserver docker repository

**Comment by Niaw** [comment]
Yes, that's what I did.
Do you think it is related to the docker container and not to calibre-web?

**Comment by OzzieIsaacs** [comment]
I never had a problem like that. It‘s stating it has a problem with name resolution (scholarly seems to be the reason).

**Comment by Niaw** [comment]
Ok, thank you.
