### ISSUE TITLE
can not run first time without internet connection

### ISSUE THREAD

**Issue by hppyworld** [janeczku/calibre-web#2299]
when try to first time run this without internet connection, it do not work. Please try to fix this. this app should run without internet connection. 
to reproduce it. 

before running first time. disconnect from internet. and then try to run it. seems like from log tries to connect to some url but url is connection time out so it can not start the service.
```
 Traceback (most recent call last):
 File "/usr/lib/python3.8/urllib/request.py", line 1354, in do_open
 h.request(req.get_method(), req.selector, req.data, headers,
 File "/usr/lib/python3.8/http/client.py", line 1256, in request
 self._send_request(method, url, body, headers, encode_chunked)
 File "/usr/lib/python3.8/http/client.py", line 1302, in _send_request
 self.endheaders(body, encode_chunked=encode_chunked)
 File "/usr/lib/python3.8/http/client.py", line 1251, in endheaders
 self._send_output(message_body, encode_chunked=encode_chunked)
 File "/usr/lib/python3.8/http/client.py", line 1011, in _send_output
 self.send(msg)
 File "/usr/lib/python3.8/http/client.py", line 951, in send
 self.connect()
 File "/usr/lib/python3.8/http/client.py", line 1418, in connect
 super().connect()
 File "/usr/lib/python3.8/http/client.py", line 922, in connect
 self.sock = self._create_connection(
 File "/usr/lib/python3.8/socket.py", line 808, in create_connection
 raise err
 File "/usr/lib/python3.8/socket.py", line 796, in create_connection
 sock.connect(sa)
 socket.timeout: timed out

 During handling of the above exception, another exception occurred:

 Traceback (most recent call last):
 File "/usr/local/lib/python3.8/dist-packages/fake_useragent/utils.py", line 64, in get
 with contextlib.closing(urlopen(
 File "/usr/lib/python3.8/urllib/request.py", line 222, in urlopen
 return opener.open(url, data, timeout)
 File "/usr/lib/python3.8/urllib/request.py", line 525, in open
 response = self._open(req, data)
 File "/usr/lib/python3.8/urllib/request.py", line 542, in _open
 result = self._call_chain(self.handle_open, protocol, protocol +
 File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
 result = func(*args)
 File "/usr/lib/python3.8/urllib/request.py", line 1397, in https_open
 return self.do_open(http.client.HTTPSConnection, req,
 File "/usr/lib/python3.8/urllib/request.py", line 1357, in do_open
 raise URLError(err)
 urllib.error.URLError:

 During handling of the above exception, another exception occurred:

 Traceback (most recent call last):
 File "/usr/local/lib/python3.8/dist-packages/fake_useragent/utils.py", line 154, in load
 for item in get_browsers(verify_ssl=verify_ssl):
 File "/usr/local/lib/python3.8/dist-packages/fake_useragent/utils.py", line 97, in get_browsers
 html = get(settings.BROWSERS_STATS_PAGE, verify_ssl=verify_ssl)
 File "/usr/local/lib/python3.8/dist-packages/fake_useragent/utils.py", line 84, in get
 raise FakeUserAgentError('Maximum amount of retries reached')
 fake_useragent.errors.FakeUserAgentError: Maximum amount of retries reached

 During handling of the above exception, another exception occurred:

 Traceback (most recent call last):
 File "/usr/lib/python3.8/urllib/request.py", line 1354, in do_open
 h.request(req.get_method(), req.selector, req.data, headers,
 File "/usr/lib/python3.8/http/client.py", line 1256, in request
 self._send_request(method, url, body, headers, encode_chunked)
 File "/usr/lib/python3.8/http/client.py", line 1302, in _send_request
 self.endheaders(body, encode_chunked=encode_chunked)
 File "/usr/lib/python3.8/http/client.py", line 1251, in endheaders
 self._send_output(message_body, encode_chunked=encode_chunked)
 File "/usr/lib/python3.8/http/client.py", line 1011, in _send_output
 self.send(msg)
 File "/usr/lib/python3.8/http/client.py", line 951, in send
 self.connect()
 File "/usr/lib/python3.8/http/client.py", line 1418, in connect
 super().connect()
 File "/usr/lib/python3.8/http/client.py", line 922, in connect
 self.sock = self._create_connection(
 File "/usr/lib/python3.8/socket.py", line 808, in create_connection
 raise err
 File "/usr/lib/python3.8/socket.py", line 796, in create_connection
 sock.connect(sa)
 socket.timeout: timed out

 During handling of the above exception, another exception occurred:

 Traceback (most recent call last):
 File "/usr/local/lib/python3.8/dist-packages/fake_useragent/utils.py", line 64, in get
 with contextlib.closing(urlopen(
 File "/usr/lib/python3.8/urllib/request.py", line 222, in urlopen
 return opener.open(url, data, timeout)
 File "/usr/lib/python3.8/urllib/request.py", line 525, in open
 response = self._open(req, data)
 File "/usr/lib/python3.8/urllib/request.py", line 542, in _open
 result = self._call_chain(self.handle_open, protocol, protocol +
 File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
 result = func(*args)
 File "/usr/lib/python3.8/urllib/request.py", line 1397, in https_open
 return self.do_open(http.client.HTTPSConnection, req,
 File "/usr/lib/python3.8/urllib/request.py", line 1357, in do_open
 raise URLError(err)
 urllib.error.URLError:

 During handling of the above exception, another exception occurred:

 Traceback (most recent call last):
 File "/app/calibre-web/cps.py", line 34, in
 from cps.about import about
 File "/app/calibre-web/cps/about.py", line 61, in
 from scholarly import scholarly
 File "/usr/local/lib/python3.8/dist-packages/scholarly/init.py", line 4, in
 scholarly = _Scholarly()
 File "/usr/local/lib/python3.8/dist-packages/scholarly/_scholarly.py", line 27, in init
 self.__nav = Navigator()
 File "/usr/local/lib/python3.8/dist-packages/scholarly/_navigator.py", line 45, in call
 cls._instances[cls] = super(Singleton, cls).call(*args,
 File "/usr/local/lib/python3.8/dist-packages/scholarly/_navigator.py", line 59, in init
 self.pm = ProxyGenerator()
 File "/usr/local/lib/python3.8/dist-packages/scholarly/_proxy_generator.py", line 54, in init
 self._new_session()
 File "/usr/local/lib/python3.8/dist-packages/scholarly/_proxy_generator.py", line 368, in _new_session
 'User-Agent': UserAgent().random,
 File "/usr/local/lib/python3.8/dist-packages/fake_useragent/fake.py", line 69, in init
 self.load()
 File "/usr/local/lib/python3.8/dist-packages/fake_useragent/fake.py", line 75, in load
 self.data = load_cached(
 File "/usr/local/lib/python3.8/dist-packages/fake_useragent/utils.py", line 250, in load_cached
 update(path, use_cache_server=use_cache_server, verify_ssl=verify_ssl)
 File "/usr/local/lib/python3.8/dist-packages/fake_useragent/utils.py", line 245, in update
 write(path, load(use_cache_server=use_cache_server, verify_ssl=verify_ssl))
 File "/usr/local/lib/python3.8/dist-packages/fake_useragent/utils.py", line 187, in load
 ret = json.loads(get(
 File "/usr/local/lib/python3.8/dist-packages/fake_useragent/utils.py", line 84, in get
 raise FakeUserAgentError('Maximum amount of retries reached')
 fake_useragent.errors.FakeUserAgentError: Maximum amount of retries reached
```

**Comment by OzzieIsaacs** [comment]
`scholarly` is the reason for this. So if you don't want to grap metadata from googel scholar you should uninstall it (`pip3 uninstall scholarly`). Or please update to the newest nightly version
