### ISSUE TITLE
500 Internal Server Error while adding books

### ISSUE THREAD

**Issue by gzplca** [janeczku/calibre-web#2357]
Calibre-Web
Internal Server Error
500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
Traceback (most recent call last):
File "/usr/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
response = self.full_dispatch_request()
File "/usr/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
File "/usr/local/calibre-web/app/cps/usermanagement.py", line 38, in decorated_view
return login_required(func)(*args, **kwargs)
File "/usr/lib/python3.9/site-packages/flask_login/utils.py", line 272, in decorated_view
return func(*args, **kwargs)
File "/usr/local/calibre-web/app/cps/web.py", line 744, in index
return render_books_list("newest", sort_param, 1, page)
File "/usr/local/calibre-web/app/cps/web.py", line 378, in render_books_list
entries, random, pagination = calibre_db.fill_indexpage(page, 0, db.Books, True, order[0],
File "/usr/local/calibre-web/app/cps/db.py", line 713, in fill_indexpage
return self.fill_indexpage_with_archived_books(page, database, pagesize, db_filter, order, False,
File "/usr/local/calibre-web/app/cps/db.py", line 720, in fill_indexpage_with_archived_books
randm = self.session.query(Books) \
AttributeError: 'NoneType' object has no attribute 'query'

**Comment by OzzieIsaacs** [comment]
I can't reproduce it.

Without any context (the form you deleted) it makes no sense for me to spend time on this issue.
