### ISSUE TITLE
Exception on /metadata/search [POST]

### ISSUE THREAD

**Issue by zisco67** [janeczku/calibre-web#2363]
On newest cps-version, metadata-search doesn't work:
```
[2022-04-05 12:12:04,532]  INFO {scholarly:95} Getting https://scholar.google.com/scholar?hl=en&q=Die%20Enkelin&as_vis=0&as_sdt=0,33
[2022-04-05 12:12:20,204] ERROR {cps:1457} Exception on /metadata/search [POST]
Traceback (most recent call last):
  File "/opt/lib/python3.10/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/lib/python3.10/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/lib/python3.10/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/lib/python3.10/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/volume1/web/calibre-web/vendor/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/volume1/web/calibre-web/cps/search_metadata.py", line 141, in metadata_search
    data.extend([asdict(x) for x in future.result()])
  File "/opt/lib/python3.10/concurrent/futures/_base.py", line 438, in result
  File "/opt/lib/python3.10/concurrent/futures/_base.py", line 390, in __get_result
  File "/opt/lib/python3.10/concurrent/futures/thread.py", line 52, in run
  File "/volume1/web/calibre-web/cps/metadata_provider/lubimyczytac.py", line 116, in search
    root = fromstring(result.text)
  File "/opt/lib/python3.10/site-packages/lxml/html/__init__.py", line 875, in fromstring
  File "/opt/lib/python3.10/site-packages/lxml/html/__init__.py", line 763, in document_fromstring
lxml.etree.ParserError: Document is empty
```

**Comment by zisco67** [comment]
Thanks for the prompt response - now I'm getting thie error:
`[2022-04-06 08:59:37,851] ERROR {cps.editbooks:885} Document is empty`

**Comment by OzzieIsaacs** [comment]
Strange. 
I didn't check it fully, so I updated calibre-web again, now the error should get fully catched.
This only can happen if a request to :  "https://lubimyczytac.pl/szukaj/ksiazki?phrase=[some text]" returns absolutly nothing, except the header, which I can't reproduce. 
Which search term are you using?
Do you use docker and is something needed to access the internet (proxy in between?) which isn't working?

**Comment by zisco67** [comment]
No Docker, no proxy!
But now it seems to work fine, THX!

**Comment by shaojs321** [comment]
I got the same error code and I suspect it might be the reason I'm using the api to query too many times. When I installed it for the first time without any problem, I encountered this problem after dozens of queries (I encountered this problem in Douban query)
