### ISSUE TITLE
Unable to access webui, running on unraid docker container

### ISSUE THREAD

**Issue by JValentine9** [janeczku/calibre-web#2380]
**Describe the bug/problem**
Attempting to use the webui

**To Reproduce**
Just attempting to navigate to the home page

**Logfile**
500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
Traceback (most recent call last):
File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2073, in wsgi_app
response = self.full_dispatch_request()
File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1518, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1516, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1502, in dispatch_request
return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
File "/app/calibre-web/cps/usermanagement.py", line 34, in decorated_view
return func(*args, **kwargs)
File "/app/calibre-web/cps/web.py", line 752, in index
return render_books_list("newest", sort_param, 1, page)
File "/app/calibre-web/cps/web.py", line 391, in render_books_list
entries, random, pagination = calibre_db.fill_indexpage(page, 0, db.Books, True, order[0],
File "/app/calibre-web/cps/db.py", line 725, in fill_indexpage
return self.fill_indexpage_with_archived_books(page, database, pagesize, db_filter, order, False,
File "/app/calibre-web/cps/db.py", line 732, in fill_indexpage_with_archived_books
random_query = self.generate_linked_query(config_read_column, database)
File "/app/calibre-web/cps/db.py", line 686, in generate_linked_query
query = (self.session.query(database, ub.ArchivedBook.is_archived, ub.ReadBook.read_status)
AttributeError: 'NoneType' object has no attribute 'query'

**Expected behavior**
access to the webserver

**Screenshots**
![image](https://user-images.githubusercontent.com/39357521/164350945-a7a75454-652b-4555-abf8-d1c70970e67a.png)

**Environment (please complete the following information):**
Unraid 6.9.2 docker container lscr.io/linuxserver/calibre-web

**Additional context**
Add any other context about the problem here. [e.g. access via reverse proxy, database background sync, special database location]

**Comment by OzzieIsaacs** [comment]
This seems to be a docker related problem with database access. I often get this question but never received an answer, so:
A) You just created an empty metadata.db file
B) Your metadata.db file is something else than a calibre library file
C) You can't access the metadata.db file or don't have proper permissions
D) Something went wrong with "linking" to the metadata.db file outside the docker container

**Comment by OzzieIsaacs** [comment]
Here:  #2231,  #2357, #2190, #2185,  #1106 ...
