### ISSUE TITLE
500 error after adding custom column of type "Text, but with a fixed set of permitted values"

### ISSUE THREAD

**Issue by msmcilvride** [janeczku/calibre-web#2398]
**Describe the bug/problem**
I have been playing around with custom columns in Calibre and found a configuration that does not allow me to edit books in Calibre-Web. When selecting Edit Metadata on a book, I receive a 500 Internal Server Error.

**To Reproduce**
1. In Calibre, create a new column of type "Text, but with a fixed set of permitted values".
2. Add any values, ie "one,two"three".
3. Apply and restart Calibre.
4. In Calibre-Web, navigate to a title and select "Edit Metadata".

**Logfile**
```
[2022-05-04 12:55:22,156] ERROR {cps:1457} Exception on /admin/book/5 [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/app/calibre-web/cps/usermanagement.py", line 35, in decorated_view
    return login_required(func)(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/app/calibre-web/cps/editbooks.py", line 69, in inner
    return f(*args, **kwargs)
  File "/app/calibre-web/cps/editbooks.py", line 745, in show_edit_book
    return render_edit_book(book_id)
  File "/app/calibre-web/cps/editbooks.py", line 407, in render_edit_book
    return render_title_template('book_edit.html', book=book, authors=author_names, cc=cc,
  File "/app/calibre-web/cps/render_template.py", line 122, in render_title_template
    return render_template(instance=config.config_calibre_web_title, sidebar=sidebar, simple=simple,
  File "/usr/local/lib/python3.8/dist-packages/flask/templating.py", line 147, in render_template
    return _render(
  File "/usr/local/lib/python3.8/dist-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/usr/local/lib/python3.8/dist-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.8/dist-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/app/calibre-web/cps/templates/book_edit.html", line 1, in top-level template code
    {% extends "layout.html" %}
  File "/app/calibre-web/cps/templates/layout.html", line 150, in top-level template code
    {% block body %}{% endblock %}
  File "/app/calibre-web/cps/templates/book_edit.html", line 179, in block 'body'
    {% for opt in c.get_display_dict().enum_values %}
  File "/app/calibre-web/cps/db.py", line 389, in get_display_dict
    display_dict = ast.literal_eval(self.display)
  File "/usr/lib/python3.8/ast.py", line 99, in literal_eval
    return _convert(node_or_string)
  File "/usr/lib/python3.8/ast.py", line 88, in _convert
    return dict(zip(map(_convert, node.keys),
  File "/usr/lib/python3.8/ast.py", line 98, in _convert
    return _convert_signed_num(node)
  File "/usr/lib/python3.8/ast.py", line 75, in _convert_signed_num
    return _convert_num(node)
  File "/usr/lib/python3.8/ast.py", line 66, in _convert_num
    _raise_malformed_node(node)
  File "/usr/lib/python3.8/ast.py", line 63, in _raise_malformed_node
    raise ValueError(f'malformed node or string: {node!r}')
ValueError: malformed node or string: <_ast.Name object at 0x14be34204eb0>`
```
**Expected behavior**
The "Edit Metadata" button should bring me to the edit page and allow me to make changes to a title's metadata.

**Environment (please complete the following information):**
 - LinuxServer Docker container on Unraid 6.9.2.

**Comment by OzzieIsaacs** [comment]
Your description didn't lead to a problem, the problem only occurs if you are defining a default value and/or color (at least for me). I fixed it in the nightly release. 
If possible, please update to the newest nightly build version of the container

**Comment by msmcilvride** [comment]
On second look, my description was poor. The issue you describe is exactly what I meant. Calibre-Web is great, thanks for the quick fix.
