### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by billouetaudrey** [janeczku/calibre-web#2405]
**Describe the bug/problem**
A clear and concise description of what the bug is. If you are asking for support, please check our [Wiki](https://github.com/janeczku/calibre-web/wiki) if your question is already answered there.

**To Reproduce**
1. Go to calibre-web
2. Click on login
3. See error

**Logfile**
```
Traceback (most recent call last):
File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2073, in wsgi_app
response = self.full_dispatch_request()
File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1518, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1516, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1502, in dispatch_request
return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
File "/app/calibre-web/cps/usermanagement.py", line 38, in decorated_view
return login_required(func)(*args, **kwargs)
File "/usr/local/lib/python3.8/dist-packages/flask_login/utils.py", line 272, in decorated_view
return func(*args, **kwargs)
File "/app/calibre-web/cps/web.py", line 763, in index
return render_books_list("newest", sort_param, 1, page)
File "/app/calibre-web/cps/web.py", line 411, in render_books_list
entries, random, pagination = calibre_db.fill_indexpage(page, 0, db.Books, True, order[0],
File "/app/calibre-web/cps/db.py", line 679, in fill_indexpage
return self.fill_indexpage_with_archived_books(page, pagesize, database, db_filter, order, False, *join)
File "/app/calibre-web/cps/db.py", line 685, in fill_indexpage_with_archived_books
randm = self.session.query(Books) \
AttributeError: 'NoneType' object has no attribute 'query'
```

**Expected behavior**
Calibre-Web
Internal Server Error
500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

**Environment (please complete the following information):**
 - OS: Linux Mint Docker
- Linuxserver.io version:- 0.6.15-ls147 Build-date:- 2022-01-18T10:48:34+01:00
--

Habitually, when do restart, it's work, but not anymore :(

Any help please?

**Comment by billouetaudrey** [comment]
[_calibre-web_logs.txt](https://github.com/janeczku/calibre-web/files/8685857/_calibre-web_logs.txt)

This is the log when Calibre start

**Comment by billouetaudrey** [comment]
Fixed, was my external hdd unplug with the db ;) sorry
