### ISSUE TITLE
Calibre-Web crashes (500) when given non-existent metadata.db path 

### ISSUE THREAD

**Issue by Dunrar** [janeczku/calibre-web#2419]
**Describe the bug/problem**
When editing the calibre database path in the admin settings, it crashes the application when providing a non-existent path. At first the site is being refreshed and a warning is shown (`DB Location is not Valid, Please Enter Correct Path`). But further interaction is not possible because 500 Internal Server Error is thrown. 

**To Reproduce**
1. Go to '/admin/dbconfig'
2. Enter non-existent path
3. Click on 'Save'
4. Refresh
5. See error

**Logfile**
```
Traceback (most recent call last):
File "/home/username/calibre-web/venv/lib/python3.10/site-packages/flask/app.py", line 2073, in wsgi_app
response = self.full_dispatch_request()
File "/home/username/calibre-web/venv/lib/python3.10/site-packages/flask/app.py", line 1518, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/home/username/calibre-web/venv/lib/python3.10/site-packages/flask/app.py", line 1516, in full_dispatch_request
rv = self.dispatch_request()
File "/home/username/calibre-web/venv/lib/python3.10/site-packages/flask/app.py", line 1502, in dispatch_request
return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
File "/home/username/calibre-web/cps/usermanagement.py", line 35, in decorated_view
return login_required(func)(*args, **kwargs)
File "/home/username/calibre-web/venv/lib/python3.10/site-packages/flask_login/utils.py", line 272, in decorated_view
return func(*args, **kwargs)
File "/home/username/calibre-web/cps/web.py", line 779, in index
return render_books_list("newest", sort_param, 1, page)
File "/home/username/calibre-web/cps/web.py", line 399, in render_books_list
entries, random, pagination = calibre_db.fill_indexpage(page, 0, db.Books, True, order[0],
File "/home/username/calibre-web/cps/db.py", line 731, in fill_indexpage
return self.fill_indexpage_with_archived_books(page, database, pagesize, db_filter, order, False,
File "/home/username/calibre-web/cps/db.py", line 738, in fill_indexpage_with_archived_books
random_query = self.generate_linked_query(config_read_column, database)
File "/home/username/calibre-web/cps/db.py", line 692, in generate_linked_query
query = (self.session.query(database, ub.ArchivedBook.is_archived, ub.ReadBook.read_status)
AttributeError: 'NoneType' object has no attribute 'query'
```

**Expected behavior**
To see the error/warning and keep the old DB configuration.

**Comment by OzzieIsaacs** [comment]
Sorry I can't reproduce this. I need more details.
I started with a **new installation** using the newest nightly version. **Which version are you using?**
After entering a non existent path I get this result:
![grafik](https://user-images.githubusercontent.com/6438895/169693800-9ff13015-3551-47a3-98f5-b32a309a1ffa.png)

If I click on refresh I get asked if I want to resend the data:
![grafik](https://user-images.githubusercontent.com/6438895/169693824-54e6eee0-cbc5-4996-bb5b-a38b5a599bc6.
If I click on resend, the page reloads and I get the same message again?
![grafik](https://user-images.githubusercontent.com/6438895/169693864-848d1e25-b501-4767-89a0-cb38b4a6e70e.png)

Everybody who presented my this error message in the past was using docker. I was never able to reproduce it in a normal installation. **Are you using a docker container? **

Do I need anything more as starting point to reproduce the bug?

**Comment by Dunrar** [comment]
Just did a fresh install with the most recent version, following these instructions https://github.com/janeczku/calibre-web/wiki/Manual-Installation (0.6.19 Beta). I get the bug with a docker installation and the manual installation. A working metadata.db file has to be specified first, the bug only appears when changing to a non-existent path from a working configuration.
