### ISSUE TITLE
Email to Kindle - 500 Internal Error

### ISSUE THREAD

**Issue by tzortst** [janeczku/calibre-web#243]
Ubuntu 16.04.2 LTS
kindlegen is in vendor dir

When trying to email ebook (EPUB) which would require conversion to MOBI calibre-web hangs then returns 500 internal error, attach are the logs

If i try to email a book already in MOBI format it emails successfully
```
[2017-07-19 18:45:12,004] {/usr/local/lib/python2.7/dist-packages/flask/app.py:1560} ERROR - Exception on /send/11 [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/flask_login/utils.py", line 228, in decorated_view
    return func(*args, **kwargs)
  File "/usr/calibre-web/cps/web.py", line 446, in inner
    return f(*args, **kwargs)
  File "/usr/calibre-web/cps/web.py", line 1834, in send_to_kindle
    result = helper.send_mail(book_id, current_user.kindle_mail, config.config_calibre_dir)
  File "/usr/calibre-web/cps/helper.py", line 228, in send_mail
    data, resultCode = make_mobi(book.id, calibrepath)
  File "/usr/calibre-web/cps/helper.py", line 122, in make_mobi
    db.session.commit()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 906, in commit
    self.transaction.commit()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 465, in commit
    t[1].commit()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1632, in commit
    self._do_commit()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1663, in _do_commit
    self.connection._commit_impl()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 723, in _commit_impl
    self._handle_dbapi_exception(e, None, None, None, None)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1402, in _handle_dbapi_exception
    exc_info
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 721, in _commit_impl
    self.engine.dialect.do_commit(self.connection)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/default.py", line 443, in do_commit
    dbapi_connection.commit()
OperationalError: (sqlite3.OperationalError) database is locked

```

**Comment by tzortst** [comment]
I can see the MOBI version of the book has been created on the file-system but hasn't bee updated on the calibre DB

**Comment by tzortst** [comment]
Looks like Calibre doesn't play well over NFS.

I was able to solve the database locked error with the following

https://coderwall.com/p/zrxobw/calibre-libraries-on-nas

**Comment by klerpi** [comment]
Thanks! You saved me.
