### ISSUE TITLE
After the automatic update last night, this error occurred when I downloaded the debug log today continue yesterday's work

### ISSUE THREAD

**Issue by filwu8** [janeczku/calibre-web#2433]
After the automatic update last night, this error occurred when I downloaded the debug log today
continue yesterday's work

500 Internal Server Error
```
The server encountered an internal error and was unable to complete your request. There is an error in the application.
Traceback (most recent call last):
File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2073, in wsgi_app
response = self.full_dispatch_request()
File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1518, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1516, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1502, in dispatch_request
return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
File "/usr/local/lib/python3.8/dist-packages/flask_login/utils.py", line 272, in decorated_view
return func(*args, **kwargs)
File "/app/calibre-web/cps/admin.py", line 95, in inner
return f(*args, **kwargs)
File "/app/calibre-web/cps/admin.py", line 1460, in download_debug
return debug_info.send_debug()
File "/app/calibre-web/cps/debug_info.py", line 62, in send_debug
zf.writestr('libs.txt', json.dumps(collect_stats()))
File "/usr/lib/python3.8/json/__init__.py", line 231, in dumps
return _default_encoder.encode(obj)
File "/usr/lib/python3.8/json/encoder.py", line 199, in encode
chunks = self.iterencode(o, _one_shot=True)
File "/usr/lib/python3.8/json/encoder.py", line 257, in iterencode
return _iterencode(o, 0)
File "/usr/lib/python3.8/json/encoder.py", line 179, in default
raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type LazyString is not JSON serializable
Please report this issue with all related information: [创建问题](https://github.com/janeczku/calibre-web/issues/new?assignees=&labels=&template=bug_report.md&title=)
```

**Comment by filwu8** [comment]
thanks
