### ISSUE TITLE
Advanced search return a 500 Internal Server Error when read status input is set to yes

### ISSUE THREAD

**Issue by jagalile** [janeczku/calibre-web#2437]
**Describe the bug/problem**
When I try to list all my read books the web return a 500 Internal Server Error inestead of list all read books.

**To Reproduce**
1. Go to Advanced Search
2. Select YES on Read Status
3. Click on Search button

**Logfile**
```
[2022-06-06 18:15:47,174] ERROR {cps:1457} Exception on /advsearch/stored/ [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1802, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: ambiguous column name: book_read_link.id
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/javier_galilea_pesos/calibre-web/cps/usermanagement.py", line 35, in decorated_view
    return login_required(func)(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/javier_galilea_pesos/calibre-web/cps/web.py", line 788, in books_list
    return render_books_list(data, sort_param, book_id, page)
  File "/home/javier_galilea_pesos/calibre-web/cps/web.py", line 396, in render_books_list
    return render_adv_search_results(term, offset, order, config.config_books_per_page)
  File "/home/javier_galilea_pesos/calibre-web/cps/search.py", line 347, in render_adv_search_results
    q = q.order_by(*sort).all()
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/query.py", line 2759, in all
    return self._iter().all()
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/query.py", line 2894, in _iter
    result = self.session.execute(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/session.py", line 1692, in execute
    result = conn._execute_20(statement, params or {}, execution_options)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1614, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/sql/elements.py", line 325, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1481, in _execute_clauseelement
    ret = self._execute_context(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1845, in _execute_context
    self._handle_dbapi_exception(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 2026, in _handle_dbapi_exception
    util.raise_(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1802, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) ambiguous column name: book_read_link.id
[SQL: SELECT books.id AS books_id, books.title AS books_title, books.sort AS books_sort, books.author_sort AS books_author_sort, books.timestamp AS books_timestamp, books.pubdate AS books_pubdate, books.series_index AS books_series_index, books.last_modified AS books_last_modified, books.path AS books_path, books.has_cover AS books_has_cover, books.uuid AS books_uuid, books.isbn AS books_isbn, books.flags AS books_flags, archived_book.is_archived AS archived_book_is_archived, book_read_link.id AS book_read_link_id, book_read_link.book_id AS book_read_link_book_id, book_read_link.user_id AS book_read_link_user_id, book_read_link.read_status AS book_read_link_read_status, book_read_link.last_modified AS book_read_link_last_modified, book_read_link.last_time_started_reading AS book_read_link_last_time_started_reading, book_read_link.times_started_reading AS book_read_link_times_started_reading 
FROM books LEFT OUTER JOIN book_read_link ON books.id = book_read_link.book_id AND book_read_link.user_id = ? LEFT OUTER JOIN archived_book ON books.id = archived_book.book_id AND archived_book.user_id = ? LEFT OUTER JOIN books_series_link ON books.id = books_series_link.book LEFT OUTER JOIN series ON series.id = books_series_link.series LEFT OUTER JOIN book_read_link ON books.id = book_read_link.book_id LEFT OUTER JOIN book_shelf_link ON books.id = book_shelf_link.book_id 
WHERE 1 = 1 AND book_read_link.user_id = ? AND book_read_link.read_status = ? AND (book_shelf_link.shelf IS NULL OR (book_shelf_link.shelf NOT IN (SELECT 1 FROM (SELECT 1) WHERE 1!=1))) AND NOT (EXISTS (SELECT 1 
FROM calibre.data 
WHERE books.id = calibre.data.book AND calibre.data.format = ?)) AND NOT (EXISTS (SELECT 1 
FROM calibre.data 
WHERE books.id = calibre.data.book AND calibre.data.format = ?)) ORDER BY books.timestamp DESC]
[parameters: (3, 3, 3, 1, 'CBR', 'CBZ')]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2022-06-06 18:16:01,149] DEBUG {cps.updater:323} Nightly version: 25f2af3f03ae84f4c0df685058b4d9bf9e455fd9, 2022-06-05T10:06:43+02:00`
```
**Expected behavior**
The query should show all read books.

**Screenshots**
![image](https://user-images.githubusercontent.com/17300743/172221934-04ccc4b1-22a2-480b-a897-17bd12fcd7c1.png)

**Environment (please complete the following information):**
 - OS: `Linux 5.11.0-1023-gcp #25~20.04.1-Ubuntu SMP Mon Nov 15 15:54:39 UTC 2021 x86_64 x86_64`
 - Python version: `3.8.10`
 - Calibre-Web version: `0.6.19 Beta - 25f2af3f03ae84f4c0df685058b4d9bf9e455fd9 - 2022-06-05T10:06:43+02:00`
 - Docker container: None
 - Browser: `Google Chrome Version 102.0.5005.63 (Official Build) (64-bit)`

**Additional context**
Database is on Drive

**Comment by filwu8** [comment]
i have error too


500 Internal Server Error
The server encountered an internal error and was unable to complete your request. There is an error in the application.
Traceback (most recent call last):
File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1819, in _execute_context
self.dialect.do_execute(
File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/default.py", line 732, in do_execute
cursor.execute(statement, parameters)
sqlite3.OperationalError: ambiguous column name: book_read_link.id
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2073, in wsgi_app
response = self.full_dispatch_request()
File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1518, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1516, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1502, in dispatch_request
return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
File "/app/calibre-web/cps/usermanagement.py", line 35, in decorated_view
return login_required(func)(*args, **kwargs)
File "/usr/local/lib/python3.8/dist-packages/flask_login/utils.py", line 272, in decorated_view
return func(*args, **kwargs)
File "/app/calibre-web/cps/web.py", line 788, in books_list
return render_books_list(data, sort_param, book_id, page)
File "/app/calibre-web/cps/web.py", line 396, in render_books_list
return render_adv_search_results(term, offset, order, config.config_books_per_page)
File "/app/calibre-web/cps/search.py", line 347, in render_adv_search_results
q = q.order_by(*sort).all()
File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/query.py", line 2768, in all
return self._iter().all()
File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/query.py", line 2903, in _iter
result = self.session.execute(
File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/session.py", line 1696, in execute
result = conn._execute_20(statement, params or {}, execution_options)
File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1631, in _execute_20
return meth(self, args_10style, kwargs_10style, execution_options)
File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/sql/elements.py", line 325, in _execute_on_connection
return connection._execute_clauseelement(
File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1498, in _execute_clauseelement
ret = self._execute_context(
File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1862, in _execute_context
self._handle_dbapi_exception(
File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 2043, in _handle_dbapi_exception
util.raise_(
File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/util/compat.py", line 207, in raise_
raise exception
File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1819, in _execute_context
self.dialect.do_execute(
File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/default.py", line 732, in do_execute
cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) ambiguous column name: book_read_link.id
[SQL: SELECT books.id AS books_id, books.title AS books_title, books.sort AS books_sort, books.author_sort AS books_author_sort, books.timestamp AS books_timestamp, books.pubdate AS books_pubdate, books.series_index AS books_series_index, books.last_modified AS books_last_modified, books.path AS books_path, books.has_cover AS books_has_cover, books.uuid AS books_uuid, books.isbn AS books_isbn, books.flags AS books_flags, archived_book.is_archived AS archived_book_is_archived, book_read_link.id AS book_read_link_id, book_read_link.book_id AS book_read_link_book_id, book_read_link.user_id AS book_read_link_user_id, book_read_link.read_status AS book_read_link_read_status, book_read_link.last_modified AS book_read_link_last_modified, book_read_link.last_time_started_reading AS book_read_link_last_time_started_reading, book_read_link.times_started_reading AS book_read_link_times_started_reading
FROM books LEFT OUTER JOIN book_read_link ON books.id = book_read_link.book_id AND book_read_link.user_id = ? LEFT OUTER JOIN archived_book ON books.id = archived_book.book_id AND archived_book.user_id = ? LEFT OUTER JOIN books_series_link ON books.id = books_series_link.book LEFT OUTER JOIN series ON series.id = books_series_link.series LEFT OUTER JOIN book_read_link ON books.id = book_read_link.book_id LEFT OUTER JOIN book_shelf_link ON books.id = book_shelf_link.book_id
WHERE 1 = 1 AND book_read_link.user_id = ? AND book_read_link.read_status = ? AND (book_shelf_link.shelf IS NULL OR (book_shelf_link.shelf NOT IN (SELECT 1 FROM (SELECT 1) WHERE 1!=1))) ORDER BY books.timestamp DESC]
[parameters: (1, 1, 1, 1)]
(Background on this error at: https://sqlalche.me/e/14/e3q8)

**Comment by jagalile** [comment]
Solved, thanks!
