### ISSUE TITLE
SQLalchemy module gives visit_JSON error upon executing calibre-web

### ISSUE THREAD

**Issue by mmtung** [janeczku/calibre-web#2491]
**Good morning! Compiling calibre-web on Linux (debian / armv7l GNU/Linux) works fine. However, upon executing 'python3 cps.py' the following error is issued:**

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/sqlalchemy/sql/visitors.py", line 86, in _compiler_dispatch
    meth = getter(visitor)
AttributeError: 'SQLiteTypeCompiler' object has no attribute 'visit_JSON'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/sqlalchemy/sql/compiler.py", line 2789, in visit_create_table
    create_column, first_pk=column.primary_key and not first_pk
  File "/usr/lib/python3/dist-packages/sqlalchemy/sql/compiler.py", line 341, in process
    return obj._compiler_dispatch(self, **kwargs)
  File "/usr/lib/python3/dist-packages/sqlalchemy/sql/visitors.py", line 90, in _compiler_dispatch
    return meth(self, **kw)
  File "/usr/lib/python3/dist-packages/sqlalchemy/sql/compiler.py", line 2821, in visit_create_column
    text = self.get_column_specification(column, first_pk=first_pk)
  File "/usr/lib/python3/dist-packages/sqlalchemy/dialects/sqlite/base.py", line 907, in get_column_specification
    column.type, type_expression=column
  File "/usr/lib/python3/dist-packages/sqlalchemy/sql/compiler.py", line 391, in process
    return type_._compiler_dispatch(self, **kw)
  File "/usr/lib/python3/dist-packages/sqlalchemy/sql/visitors.py", line 88, in _compiler_dispatch
    raise exc.UnsupportedCompilationError(visitor, cls)
sqlalchemy.exc.UnsupportedCompilationError: Compiler <sqlalchemy.dialects.sqlite.base.SQLiteTypeCompiler object at 0xb4faf930> can't render element of type <class 'sqlalchemy.sql.sqltypes.JSON'>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "cps.py", line 31, in <module>
    main()
  File "/home/mike/calibre-web/cps/main.py", line 26, in main
    app = create_app()
  File "/home/mike/calibre-web/cps/__init__.py", line 110, in create_app
    ub.init_db(cli_param.settings_path, cli_param.user_credentials)
  File "/home/mike/calibre-web/cps/ub.py", line 832, in init_db
    Base.metadata.create_all(engine)
  File "/usr/lib/python3/dist-packages/sqlalchemy/sql/schema.py", line 4200, in create_all
    ddl.SchemaGenerator, self, checkfirst=checkfirst, tables=tables
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 2011, in _run_visitor
    conn._run_visitor(visitorcallable, element, **kwargs)
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1599, in _run_visitor
    visitorcallable(self.dialect, self, **kwargs).traverse_single(element)
  File "/usr/lib/python3/dist-packages/sqlalchemy/sql/visitors.py", line 130, in traverse_single
    return meth(obj, **kw)
  File "/usr/lib/python3/dist-packages/sqlalchemy/sql/ddl.py", line 779, in visit_metadata
    _is_metadata_operation=True,
  File "/usr/lib/python3/dist-packages/sqlalchemy/sql/visitors.py", line 130, in traverse_single
    return meth(obj, **kw)
  File "/usr/lib/python3/dist-packages/sqlalchemy/sql/ddl.py", line 824, in visit_table
    include_foreign_key_constraints,
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 980, in execute
    return meth(self, multiparams, params)
  File "/usr/lib/python3/dist-packages/sqlalchemy/sql/ddl.py", line 72, in _execute_on_connection
    return connection._execute_ddl(self, multiparams, params)
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1035, in _execute_ddl
    else None,
  File "<string>", line 1, in <lambda>
  File "/usr/lib/python3/dist-packages/sqlalchemy/sql/elements.py", line 448, in compile
    return self._compiler(dialect, bind=bind, **kw)
  File "/usr/lib/python3/dist-packages/sqlalchemy/sql/ddl.py", line 29, in _compiler
    return dialect.ddl_compiler(dialect, self, **kw)
  File "/usr/lib/python3/dist-packages/sqlalchemy/sql/compiler.py", line 310, in __init__
    self.string = self.process(self.statement, **compile_kwargs)
  File "/usr/lib/python3/dist-packages/sqlalchemy/sql/compiler.py", line 341, in process
    return obj._compiler_dispatch(self, **kwargs)
  File "/usr/lib/python3/dist-packages/sqlalchemy/sql/visitors.py", line 90, in _compiler_dispatch
    return meth(self, **kw)
  File "/usr/lib/python3/dist-packages/sqlalchemy/sql/compiler.py", line 2801, in visit_create_table
    % (table.description, column.name, ce.args[0])
  File "/usr/lib/python3/dist-packages/sqlalchemy/util/compat.py", line 296, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/lib/python3/dist-packages/sqlalchemy/util/compat.py", line 276, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3/dist-packages/sqlalchemy/sql/compiler.py", line 2789, in visit_create_table
    create_column, first_pk=column.primary_key and not first_pk
  File "/usr/lib/python3/dist-packages/sqlalchemy/sql/compiler.py", line 341, in process
    return obj._compiler_dispatch(self, **kwargs)
  File "/usr/lib/python3/dist-packages/sqlalchemy/sql/visitors.py", line 90, in _compiler_dispatch
    return meth(self, **kw)
  File "/usr/lib/python3/dist-packages/sqlalchemy/sql/compiler.py", line 2821, in visit_create_column
    text = self.get_column_specification(column, first_pk=first_pk)
  File "/usr/lib/python3/dist-packages/sqlalchemy/dialects/sqlite/base.py", line 907, in get_column_specification
    column.type, type_expression=column
  File "/usr/lib/python3/dist-packages/sqlalchemy/sql/compiler.py", line 391, in process
    return type_._compiler_dispatch(self, **kw)
  File "/usr/lib/python3/dist-packages/sqlalchemy/sql/visitors.py", line 88, in _compiler_dispatch
    raise exc.UnsupportedCompilationError(visitor, cls)
sqlalchemy.exc.CompileError: (in table 'user', column 'view_settings'): Compiler <sqlalchemy.dialects.sqlite.base.SQLiteTypeCompiler object at 0xb4faf930> can't render element of type <class 'sqlalchemy.sql.sqltypes.JSON'>

**Comment by OzzieIsaacs** [comment]
How did you compile? it? 

Did you use the script from here (https://github.com/OzzieIsaacs/calibre-web-test/blob/aa2fa9ee2ca9d95aa2b4ae9d0cb3aefe874297f5/build/make_release.py), 

What do you mean by compiling?

**Comment by mmtung** [comment]
Thanks for your speedy reply, Ozzie. For installation (and precompiling
some of the included libraries) I was using the command

	pip3 install --system --target vendor -r requirements.txt

after downloading the git files (requirements.txt is provided with the
git repository for calibre-web).

Should I use calibre-web-test instead of calibre-web?

**Comment by OzzieIsaacs** [comment]
> Should I use calibre-web-test instead of calibre-web?

No, this was referring to the term "compile"

The installation via the "--target vendor" folder is no longer supported. 
Please use the procedure from the readme for installation
: 
https://github.com/janeczku/calibre-web#installation

or manual installation procedure which is also referred in the readme:

https://github.com/janeczku/calibre-web/wiki/Manual-Installation

**Comment by mmtung** [comment]
Many thanks, Ozzie! I was following other (obviously obsolete) instructions
on the web. After installing manually some Python modules and running pip3,
everything is now running smoothly.

**Comment by OzzieIsaacs** [comment]
Great
