### ISSUE TITLE
searching as admin results in database error message

### ISSUE THREAD

**Issue by bartart3d** [janeczku/calibre-web#2492]
**Describe the bug/problem**
Since recently, when I search through the search entry field as the default admin user, I get this as a result:
(sqlite3.DatabaseError) database disk image is malformed (Background on this error at: http://sqlalche.me/e/13/4xp6)
and a whole bunch more, described in the logfile section.

When I search as a newly created user, with the same rights I get the results I want, no problem occurs at all.

For now I'll just use my newly created user, but I thought I'd just mention the error, the more bugs squashed, the better :-) .

**To Reproduce**
I doubt it will be easily reproducible, but this is what I did:

1. log in as default admin user (my password was changed)
2. enter any kind of search entry en click 'search'
3. Result: the above mentioned error

**Logfile**

```
Traceback (most recent call last):
File "/root/.local/lib/python3.7/site-packages/sqlalchemy/engine/result.py", line 1284, in fetchall
l = self.process_rows(self._fetchall_impl())
File "/root/.local/lib/python3.7/site-packages/sqlalchemy/engine/result.py", line 1230, in _fetchall_impl
return self.cursor.fetchall()
sqlite3.DatabaseError: database disk image is malformed
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "/usr/lib/python3/dist-packages/flask/app.py", line 2292, in wsgi_app
response = self.full_dispatch_request()
File "/usr/lib/python3/dist-packages/flask/app.py", line 1815, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/lib/python3/dist-packages/flask/app.py", line 1718, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/usr/lib/python3/dist-packages/flask/_compat.py", line 35, in reraise
raise value
File "/usr/lib/python3/dist-packages/flask/app.py", line 1813, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/lib/python3/dist-packages/flask/app.py", line 1799, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/home/pi/Documents/calibre-web-master/cps/usermanagement.py", line 35, in decorated_view
return login_required(func)(*args, **kwargs)
File "/home/pi/Documents/calibre-web-master/vendor/flask_login/utils.py", line 272, in decorated_view
return func(*args, **kwargs)
File "/home/pi/Documents/calibre-web-master/cps/web.py", line 761, in books_list
return render_books_list(data, sort_param, book_id, page)
File "/home/pi/Documents/calibre-web-master/cps/web.py", line 384, in render_books_list
return render_search_results(term, offset, order, config.config_books_per_page)
File "/home/pi/Documents/calibre-web-master/cps/web.py", line 731, in render_search_results
*join)
File "/home/pi/Documents/calibre-web-master/cps/db.py", line 881, in get_search_results
result = self.search_query(term, config, *join).order_by(*order).all()
File "/root/.local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3373, in all
return list(self)
File "/root/.local/lib/python3.7/site-packages/sqlalchemy/orm/loading.py", line 100, in instances
cursor.close()
File "/root/.local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
with_traceback=exc_tb,
File "/root/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
raise exception
File "/root/.local/lib/python3.7/site-packages/sqlalchemy/orm/loading.py", line 76, in instances
fetch = cursor.fetchall()
File "/root/.local/lib/python3.7/site-packages/sqlalchemy/engine/result.py", line 1289, in fetchall
e, None, None, self.cursor, self.context
File "/root/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1511, in _handle_dbapi_exception
sqlalchemy_exception, with_traceback=exc_info[2], from_=e
File "/root/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
raise exception
File "/root/.local/lib/python3.7/site-packages/sqlalchemy/engine/result.py", line 1284, in fetchall
l = self.process_rows(self._fetchall_impl())
File "/root/.local/lib/python3.7/site-packages/sqlalchemy/engine/result.py", line 1230, in _fetchall_impl
return self.cursor.fetchall()
sqlalchemy.exc.DatabaseError: (sqlite3.DatabaseError) database disk image is malformed
(Background on this error at: http://sqlalche.me/e/13/4xp6)

```

**Expected behavior**
A search result

**Environment (please complete the following information):**
 - OS:Raspbian
 - Python version: 2.7.16
 - Calibre-Web version: 0.6.18

 - Special Hardware: Raspberry4
 - Browser: tested on Chrome 103.0.5060.114 (Officiële build) (64-bits) and firefox 102.0 (64-bit)

**Comment by OzzieIsaacs** [comment]
This is most likely a problem with the database file itself. Please perform a library maintenance from calibre program itself, the error should disappear afterwards

**Comment by bartart3d** [comment]
Hey,
it did solve the issue, which does surprise me, because searching as another user did work.
Anyhow, it's solved!

**Comment by bartart3d** [comment]
closed
