### ISSUE TITLE
Cbz files compressed using different methods do not open

### ISSUE THREAD

**Issue by hstonc** [janeczku/calibre-web#2517]
I can't open cbz files compressed with 7z in calibre-web, but I can open cbz files compressed with File Roller.
1.cbz compressed to cbz with 7z command
without any parameters
2.cbz is compressed to cbz using File Roller.

Related documents:
https://drive.google.com/drive/folders/1THYXZ6bJhnw3twdRvTbsuEWdS69CCfWp

Logfile:
None

**Environment (please complete the following information):**
 - OS: [Linuxmint 21]
 - Python version: [Python 3.10.4]
 - Calibre-Web version: [0.6.19]:
 - Docker container: [None]:
 - Browser: [Firefox 103.0.1]

**Comment by ocean2333** [comment]
i meet similar problem when using linuxserver/calibre-web 0.6.19 version docker on debian system. i compress some .jpg pictures with winrar without any parameter. and get a rar format compress file, then i rename it to pics.cbz and upload it to calibre-web. when i read it online, it can not show any picture or can only show one of them. when i check browser console, it show these errors:

Uncaught TypeError: Cannot read properties of null (reading 'byteLength')
    at createURLFromArray (kthoom.js:108:21)
    at new kthoom.ImageFile (kthoom.js:167:24)
    at kthoom.js:198:44
    at uncompress.js:276:33

i roughly read source code and i think it might be caused by  something in readRARContent function. it returns a null array to readData and makes array.byteLength throws error.
i walkaround this problem by using zip compress format.

**Comment by wgibcus** [comment]
Number 2 works fine on my system, number 1 not at all. I know from experience that cbz readers are pretty fussy about compression. I use no compression whatsoever for my cbz files for maximum compatibility.
