### ISSUE TITLE
help

### ISSUE THREAD

**Issue by astlea** [janeczku/calibre-web#2532]
Traceback (most recent call last):
File "/www/wwwroot/calibre-web-master/wrwe_venv/lib/python3.7/site-packages/flask/app.py", line 2525, in wsgi_app
response = self.full_dispatch_request()
File "/www/wwwroot/calibre-web-master/wrwe_venv/lib/python3.7/site-packages/flask/app.py", line 1822, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/www/wwwroot/calibre-web-master/wrwe_venv/lib/python3.7/site-packages/flask/app.py", line 1820, in full_dispatch_request
rv = self.dispatch_request()
File "/www/wwwroot/calibre-web-master/wrwe_venv/lib/python3.7/site-packages/flask/app.py", line 1796, in dispatch_request
return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
File "/www/wwwroot/calibre-web-master/cps/web.py", line 165, in decorated_view
return func(*args, **kwargs)
File "/www/wwwroot/calibre-web-master/cps/web.py", line 484, in index
entries, random, pagination = fill_indexpage(page, db.Books, True, [db.Books.timestamp.desc()])
File "/www/wwwroot/calibre-web-master/cps/helper.py", line 740, in fill_indexpage
entries = db.session.query(database).join(*join, isouter=True).filter(db_filter).filter(common_filters()).\
TypeError: join() missing 1 required positional argument: 'target'

**Comment by OzzieIsaacs** [comment]
Please update sqlalchemy to a more recent version

**Comment by astlea** [comment]
the sqlalchemy is new
![屏幕截图 2022-08-31 081247](https://user-images.githubusercontent.com/74756868/187565363-01aae68d-e00f-4dc7-bd73-58db2d784ba3.png)
The platform used is https://www.bt.cn/new/product_linux.html

**Comment by astlea** [comment]
the sqlalchemy 1.1.0
