### ISSUE TITLE
Error when importing metadata

### ISSUE THREAD

**Issue by StrangeRanger** [janeczku/calibre-web#2548]
**Describe the bug/problem**
Sometimes, when trying to import the retrieved metadata when adding a new PDF, I get an internal error message. It seems like it still imports/applies the metadata, so I'm unsure what's wrong. Below is the error message:

```log
PDF Gallery
500 Internal Server Error
The server encountered an internal error and was unable to complete your request. There is an error in the application.
Traceback (most recent call last):
File "/var/calibre/.local/share/virtualenvs/calibre-web-eKriAZSx/lib/python3.10/site-packages/sqlalchemy/engine/cursor.py", line 977, in fetchall
rows = dbapi_cursor.fetchall()
sqlite3.InterfaceError: Cursor needed to be reset because of commit/rollback and can no longer be fetched from.
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "/var/www/calibre.randomserver.xyz/calibre-web/cps/editbooks.py", line 169, in edit_book
modify_date |= edit_book_comments(Markup(to_save['description']).unescape(), book)
File "/var/www/calibre.randomserver.xyz/calibre-web/cps/editbooks.py", line 988, in edit_book_comments
if len(book.comments):
File "/var/calibre/.local/share/virtualenvs/calibre-web-eKriAZSx/lib/python3.10/site-packages/sqlalchemy/orm/attributes.py", line 482, in __get__
return self.impl.get(state, dict_)
File "/var/calibre/.local/share/virtualenvs/calibre-web-eKriAZSx/lib/python3.10/site-packages/sqlalchemy/orm/attributes.py", line 942, in get
value = self._fire_loader_callables(state, key, passive)
File "/var/calibre/.local/share/virtualenvs/calibre-web-eKriAZSx/lib/python3.10/site-packages/sqlalchemy/orm/attributes.py", line 978, in _fire_loader_callables
return self.callable_(state, passive)
File "/var/calibre/.local/share/virtualenvs/calibre-web-eKriAZSx/lib/python3.10/site-packages/sqlalchemy/orm/strategies.py", line 912, in _load_for_state
return self._emit_lazyload(
File "/var/calibre/.local/share/virtualenvs/calibre-web-eKriAZSx/lib/python3.10/site-packages/sqlalchemy/orm/strategies.py", line 1050, in _emit_lazyload
result = result.unique().scalars().all()
File "/var/calibre/.local/share/virtualenvs/calibre-web-eKriAZSx/lib/python3.10/site-packages/sqlalchemy/engine/result.py", line 1430, in all
return self._allrows()
File "/var/calibre/.local/share/virtualenvs/calibre-web-eKriAZSx/lib/python3.10/site-packages/sqlalchemy/engine/result.py", line 401, in _allrows
rows = self._fetchall_impl()
File "/var/calibre/.local/share/virtualenvs/calibre-web-eKriAZSx/lib/python3.10/site-packages/sqlalchemy/engine/result.py", line 1343, in _fetchall_impl
return self._real_result._fetchall_impl()
File "/var/calibre/.local/share/virtualenvs/calibre-web-eKriAZSx/lib/python3.10/site-packages/sqlalchemy/engine/result.py", line 1755, in _fetchall_impl
return list(self.iterator)
File "/var/calibre/.local/share/virtualenvs/calibre-web-eKriAZSx/lib/python3.10/site-packages/sqlalchemy/orm/loading.py", line 147, in chunks
fetch = cursor._raw_all_rows()
File "/var/calibre/.local/share/virtualenvs/calibre-web-eKriAZSx/lib/python3.10/site-packages/sqlalchemy/engine/result.py", line 392, in _raw_all_rows
rows = self._fetchall_impl()
File "/var/calibre/.local/share/virtualenvs/calibre-web-eKriAZSx/lib/python3.10/site-packages/sqlalchemy/engine/cursor.py", line 1805, in _fetchall_impl
return self.cursor_strategy.fetchall(self, self.cursor)
File "/var/calibre/.local/share/virtualenvs/calibre-web-eKriAZSx/lib/python3.10/site-packages/sqlalchemy/engine/cursor.py", line 981, in fetchall
self.handle_exception(result, dbapi_cursor, e)
File "/var/calibre/.local/share/virtualenvs/calibre-web-eKriAZSx/lib/python3.10/site-packages/sqlalchemy/engine/cursor.py", line 941, in handle_exception
result.connection._handle_dbapi_exception(
File "/var/calibre/.local/share/virtualenvs/calibre-web-eKriAZSx/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2124, in _handle_dbapi_exception
util.raise_(
File "/var/calibre/.local/share/virtualenvs/calibre-web-eKriAZSx/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
raise exception
File "/var/calibre/.local/share/virtualenvs/calibre-web-eKriAZSx/lib/python3.10/site-packages/sqlalchemy/engine/cursor.py", line 977, in fetchall
rows = dbapi_cursor.fetchall()
sqlalchemy.exc.InterfaceError: (sqlite3.InterfaceError) Cursor needed to be reset because of commit/rollback and can no longer be fetched from.
(Background on this error at: https://sqlalche.me/e/14/rvf5)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/var/calibre/.local/share/virtualenvs/calibre-web-eKriAZSx/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1057, in _rollback_impl
self.engine.dialect.do_rollback(self.connection)
File "/var/calibre/.local/share/virtualenvs/calibre-web-eKriAZSx/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 683, in do_rollback
dbapi_connection.rollback()
sqlite3.OperationalError: cannot rollback - no transaction is active
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "/var/calibre/.local/share/virtualenvs/calibre-web-eKriAZSx/lib/python3.10/site-packages/flask/app.py", line 2073, in wsgi_app
response = self.full_dispatch_request()
File "/var/calibre/.local/share/virtualenvs/calibre-web-eKriAZSx/lib/python3.10/site-packages/flask/app.py", line 1518, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/var/calibre/.local/share/virtualenvs/calibre-web-eKriAZSx/lib/python3.10/site-packages/flask/app.py", line 1516, in full_dispatch_request
rv = self.dispatch_request()
File "/var/calibre/.local/share/virtualenvs/calibre-web-eKriAZSx/lib/python3.10/site-packages/flask/app.py", line 1502, in dispatch_request
return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
File "/var/www/calibre.randomserver.xyz/calibre-web/cps/usermanagement.py", line 34, in decorated_view
return func(*args, **kwargs)
File "/var/www/calibre.randomserver.xyz/calibre-web/cps/editbooks.py", line 71, in inner
return f(*args, **kwargs)
File "/var/www/calibre.randomserver.xyz/calibre-web/cps/editbooks.py", line 232, in edit_book
calibre_db.session.rollback()
File "/var/calibre/.local/share/virtualenvs/calibre-web-eKriAZSx/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1399, in rollback
self._transaction.rollback(_to_root=self.future)
File "/var/calibre/.local/share/virtualenvs/calibre-web-eKriAZSx/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 900, in rollback
util.raise_(rollback_err[1], with_traceback=rollback_err[2])
File "/var/calibre/.local/share/virtualenvs/calibre-web-eKriAZSx/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
raise exception
File "/var/calibre/.local/share/virtualenvs/calibre-web-eKriAZSx/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 865, in rollback
t[1].rollback()
File "/var/calibre/.local/share/virtualenvs/calibre-web-eKriAZSx/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2438, in rollback
self._do_rollback()
File "/var/calibre/.local/share/virtualenvs/calibre-web-eKriAZSx/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2642, in _do_rollback
self._close_impl(try_deactivate=True)
File "/var/calibre/.local/share/virtualenvs/calibre-web-eKriAZSx/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2625, in _close_impl
self._connection_rollback_impl()
File "/var/calibre/.local/share/virtualenvs/calibre-web-eKriAZSx/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2617, in _connection_rollback_impl
self.connection._rollback_impl()
File "/var/calibre/.local/share/virtualenvs/calibre-web-eKriAZSx/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1059, in _rollback_impl
self._handle_dbapi_exception(e, None, None, None, None)
File "/var/calibre/.local/share/virtualenvs/calibre-web-eKriAZSx/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2124, in _handle_dbapi_exception
util.raise_(
File "/var/calibre/.local/share/virtualenvs/calibre-web-eKriAZSx/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
raise exception
File "/var/calibre/.local/share/virtualenvs/calibre-web-eKriAZSx/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1057, in _rollback_impl
self.engine.dialect.do_rollback(self.connection)
File "/var/calibre/.local/share/virtualenvs/calibre-web-eKriAZSx/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 683, in do_rollback
dbapi_connection.rollback()
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) cannot rollback - no transaction is active
(Background on this error at: https://sqlalche.me/e/14/e3q8)
Please report this issue with all related information: [Create Issue](https://github.com/janeczku/calibre-web/issues/new?assignees=&labels=&template=bug_report.md&title=)
[Return to Home](https://calibre.randomserver.xyz/)
```

**To Reproduce**
1. Import some PDF into instance
2. Retrieve metadata
3. Try to import data
4. Possibly encounter internal error

**Logfile**
```log
[2022-09-23 10:12:13,471] ERROR {cps.editbooks:231} (sqlite3.InterfaceError) Cursor needed to be reset because of commit/rollback and can no longer be fetched from.
(Background on this error at: https://sqlalche.me/e/14/rvf5)
[2022-09-23 10:12:13,476] ERROR {cps:1457} Exception on /admin/book/52 [POST]
Traceback (most recent call last):
  File "/var/calibre/.local/share/virtualenvs/calibre-web-eKriAZSx/lib/python3.10/site-packages/sqlalchemy/engine/cursor.py", line 977, in fetchall
    rows = dbapi_cursor.fetchall()
sqlite3.InterfaceError: Cursor needed to be reset because of commit/rollback and can no longer be fetched from.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/www/calibre.randomserver.xyz/calibre-web/cps/editbooks.py", line 169, in edit_book
    modify_date |= edit_book_comments(Markup(to_save['description']).unescape(), book)
  File "/var/www/calibre.randomserver.xyz/calibre-web/cps/editbooks.py", line 988, in edit_book_comments
    if len(book.comments):
  File "/var/calibre/.local/share/virtualenvs/calibre-web-eKriAZSx/lib/python3.10/site-packages/sqlalchemy/orm/attributes.py", line 482, in __get__
    return self.impl.get(state, dict_)
  File "/var/calibre/.local/share/virtualenvs/calibre-web-eKriAZSx/lib/python3.10/site-packages/sqlalchemy/orm/attributes.py", line 942, in get
    value = self._fire_loader_callables(state, key, passive)
  File "/var/calibre/.local/share/virtualenvs/calibre-web-eKriAZSx/lib/python3.10/site-packages/sqlalchemy/orm/attributes.py", line 978, in _fire_loader_callables
    return self.callable_(state, passive)
  File "/var/calibre/.local/share/virtualenvs/calibre-web-eKriAZSx/lib/python3.10/site-packages/sqlalchemy/orm/strategies.py", line 912, in _load_for_state
    return self._emit_lazyload(
  File "/var/calibre/.local/share/virtualenvs/calibre-web-eKriAZSx/lib/python3.10/site-packages/sqlalchemy/orm/strategies.py", line 1050, in _emit_lazyload
    result = result.unique().scalars().all()
  File "/var/calibre/.local/share/virtualenvs/calibre-web-eKriAZSx/lib/python3.10/site-packages/sqlalchemy/engine/result.py", line 1430, in all
    return self._allrows()
  File "/var/calibre/.local/share/virtualenvs/calibre-web-eKriAZSx/lib/python3.10/site-packages/sqlalchemy/engine/result.py", line 401, in _allrows
    rows = self._fetchall_impl()
  File "/var/calibre/.local/share/virtualenvs/calibre-web-eKriAZSx/lib/python3.10/site-packages/sqlalchemy/engine/result.py", line 1343, in _fetchall_impl
    return self._real_result._fetchall_impl()
  File "/var/calibre/.local/share/virtualenvs/calibre-web-eKriAZSx/lib/python3.10/site-packages/sqlalchemy/engine/result.py", line 1755, in _fetchall_impl
    return list(self.iterator)
  File "/var/calibre/.local/share/virtualenvs/calibre-web-eKriAZSx/lib/python3.10/site-packages/sqlalchemy/orm/loading.py", line 147, in chunks
    fetch = cursor._raw_all_rows()
  File "/var/calibre/.local/share/virtualenvs/calibre-web-eKriAZSx/lib/python3.10/site-packages/sqlalchemy/engine/result.py", line 392, in _raw_all_rows
    rows = self._fetchall_impl()
  File "/var/calibre/.local/share/virtualenvs/calibre-web-eKriAZSx/lib/python3.10/site-packages/sqlalchemy/engine/cursor.py", line 1805, in _fetchall_impl
    return self.cursor_strategy.fetchall(self, self.cursor)
  File "/var/calibre/.local/share/virtualenvs/calibre-web-eKriAZSx/lib/python3.10/site-packages/sqlalchemy/engine/cursor.py", line 981, in fetchall
    self.handle_exception(result, dbapi_cursor, e)
  File "/var/calibre/.local/share/virtualenvs/calibre-web-eKriAZSx/lib/python3.10/site-packages/sqlalchemy/engine/cursor.py", line 941, in handle_exception
    result.connection._handle_dbapi_exception(
  File "/var/calibre/.local/share/virtualenvs/calibre-web-eKriAZSx/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2124, in _handle_dbapi_exception
    util.raise_(
  File "/var/calibre/.local/share/virtualenvs/calibre-web-eKriAZSx/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
    raise exception
  File "/var/calibre/.local/share/virtualenvs/calibre-web-eKriAZSx/lib/python3.10/site-packages/sqlalchemy/engine/cursor.py", line 977, in fetchall
    rows = dbapi_cursor.fetchall()
sqlalchemy.exc.InterfaceError: (sqlite3.InterfaceError) Cursor needed to be reset because of commit/rollback and can no longer be fetched from.
(Background on this error at: https://sqlalche.me/e/14/rvf5)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/calibre/.local/share/virtualenvs/calibre-web-eKriAZSx/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1057, in _rollback_impl
    self.engine.dialect.do_rollback(self.connection)
  File "/var/calibre/.local/share/virtualenvs/calibre-web-eKriAZSx/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 683, in do_rollback
    dbapi_connection.rollback()
sqlite3.OperationalError: cannot rollback - no transaction is active

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/calibre/.local/share/virtualenvs/calibre-web-eKriAZSx/lib/python3.10/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/var/calibre/.local/share/virtualenvs/calibre-web-eKriAZSx/lib/python3.10/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/var/calibre/.local/share/virtualenvs/calibre-web-eKriAZSx/lib/python3.10/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/var/calibre/.local/share/virtualenvs/calibre-web-eKriAZSx/lib/python3.10/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/var/www/calibre.randomserver.xyz/calibre-web/cps/usermanagement.py", line 34, in decorated_view
    return func(*args, **kwargs)
  File "/var/www/calibre.randomserver.xyz/calibre-web/cps/editbooks.py", line 71, in inner
    return f(*args, **kwargs)
  File "/var/www/calibre.randomserver.xyz/calibre-web/cps/editbooks.py", line 232, in edit_book
    calibre_db.session.rollback()
  File "/var/calibre/.local/share/virtualenvs/calibre-web-eKriAZSx/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1399, in rollback
    self._transaction.rollback(_to_root=self.future)
  File "/var/calibre/.local/share/virtualenvs/calibre-web-eKriAZSx/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 900, in rollback
    util.raise_(rollback_err[1], with_traceback=rollback_err[2])
  File "/var/calibre/.local/share/virtualenvs/calibre-web-eKriAZSx/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
    raise exception
  File "/var/calibre/.local/share/virtualenvs/calibre-web-eKriAZSx/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 865, in rollback
    t[1].rollback()
  File "/var/calibre/.local/share/virtualenvs/calibre-web-eKriAZSx/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2438, in rollback
    self._do_rollback()
  File "/var/calibre/.local/share/virtualenvs/calibre-web-eKriAZSx/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2642, in _do_rollback
    self._close_impl(try_deactivate=True)
  File "/var/calibre/.local/share/virtualenvs/calibre-web-eKriAZSx/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2625, in _close_impl
    self._connection_rollback_impl()
  File "/var/calibre/.local/share/virtualenvs/calibre-web-eKriAZSx/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2617, in _connection_rollback_impl
    self.connection._rollback_impl()
  File "/var/calibre/.local/share/virtualenvs/calibre-web-eKriAZSx/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1059, in _rollback_impl
    self._handle_dbapi_exception(e, None, None, None, None)
  File "/var/calibre/.local/share/virtualenvs/calibre-web-eKriAZSx/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2124, in _handle_dbapi_exception
    util.raise_(
  File "/var/calibre/.local/share/virtualenvs/calibre-web-eKriAZSx/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
    raise exception
  File "/var/calibre/.local/share/virtualenvs/calibre-web-eKriAZSx/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1057, in _rollback_impl
    self.engine.dialect.do_rollback(self.connection)
  File "/var/calibre/.local/share/virtualenvs/calibre-web-eKriAZSx/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 683, in do_rollback
    dbapi_connection.rollback()
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) cannot rollback - no transaction is active
(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2022-09-23 10:13:50,454]  INFO {cps.helper:553} Moving title: /var/www/calibre.randomserver.xyz/gallery/Unknown/Operating Systems_ Three Easy Pieces - Remzi H. Arpaci-Dusseau (52) into existing: /var/www/calibre.randomserver.xyz/gallery/Remzi H. Arpaci-Dusseau/Operating Systems (52)
[2022-09-23 10:13:50,457] ERROR {cps.helper:583} Error in rename file in path [Errno 2] No such file or directory: '/var/www/calibre.randomserver.xyz/gallery/Remzi H. Arpaci-Dusseau/Operating Systems (52)/Operating Systems_ Three Easy Pieces - Rem - Unknown.pdf'
```

**Expected behavior**
The internal error does not occur.

**Environment (please complete the following information):**
- OS: Ubuntu 22.04
- Python version: Pipenv installed - 3.10.x
- Calibre-Web version: 0.6.19
- Browser: Brave Version 1.43.93, Chromium: 105.0.5195.127

**Comment by Unescience** [comment]
I have the same issue. Same circumstances, same stack trace. 

The files (cover image and epub/pdf/whatever file) are moved and renamed correctly, but the database is not getting updated. So after reloading the page it shows the old-named book in the library because of the outdated information in the database. When trying to download the book a 404 error is thrown as one would expect after the file itself is moved.

After some restarts and evaluation I can't name an obvious reason for this error. I tried books with special characters in the authors name or title and some without, but it seems random.

**Comment by OzzieIsaacs** [comment]
From the error message it looks like its related to books description. 
Could you please give me an example of search term and the search result you choose to get this error? 
It's also possible that the status of the book (having a description before or not) is part of the problem

**Comment by Unescience** [comment]
Search Term: "Hochsaison. Alpenkrimi - Jorg Maurer", empty description
Result: https://books.google.com/books?id=Uf-YAgAAQBAJ

If the error is only occuring when the description is empty - is there a workaround? The error would appear as soon as the book is uploaded, so we need to edit the book beforehand?

**Comment by OzzieIsaacs** [comment]
I tried to reproduce the error, but without success. 

Just to make sure what we are doing:. You have imported the pdf book. Afterwards you click on Load Metadata / Metadaten laden. Then you enter the term you gave me into the search bar in the top bar of the dialog box. Then you click on the cover of one of the results (which is the book from the google books link you gave me. The dialogbox then closes and all the data appears on the edit books  page (path: .../admin/book/ [numer]). Then you click on save and get the error

**Comment by WillMatthews** [comment]
I have exactly the same error. I have had this occur with EPUB books too.
It typically happens after I upload a few books in a row, and always when I Fetch Metadata from an online source.
Please let me know if I can contribute anything to help describe the bug.
I suspect it's something to do with the cover? I haven't really done much digging so far.
Thanks

**Comment by gewoondemax** [comment]
Upgraded to 6.22 ..... CalibreWeb now errors with ... Database fout: Cursor needed to be reset because of commit/rollback and can no longer be fetched from.. and I get the same behavior as above with other users. I tried to change the name from an already existing book

**Comment by Stormwind99** [comment]
I was getting this error in 6.21 whenever I tried to edit the metadata of any book via Fetch Metadata, but after upgrading to 6.22 I no longer get the error.

`
[2024-08-02 09:46:00,217] ERROR {cps.metadata_provider.amazon:129} 503 Server Error: Service Unavailable for url: https://www.amazon.com/s?k=The+Chaos+Agent&i=digital-text&sprefix=The+Chaos+Agent%2Cdigital-text&ref=nb_sb_noss
[2024-08-02 09:46:25,022] ERROR {cps.editbooks:228} Database error: (sqlite3.InterfaceError) Cursor needed to be reset because of commit/rollback and can no longer be fetched from.
(Background on this error at: https://sqlalche.me/e/14/rvf5)
`

**Comment by gewoondemax** [comment]
I found out when i alter the title and press the fetch metadata it errors most of the time.

When altering title and save it first. Then you can press the fetch metadata and all is good 😂

So maybe I have a to slow system or to much Containers(3)? 
Calibre-web, NGiNX proxy, AudioBookshelf on a dedicated Mac mini i7 16GB/500Gb running Docker Desktop 4.33 for Mac

😄 anybody?
