### ISSUE TITLE
LDAP Sync Issue

### ISSUE THREAD

**Issue by khalimerot** [janeczku/calibre-web#2626]
Cannot sync my LDAP users, settings seems ok to me. 
i'm not really sure about the certificates files, i usually use the fingerprint.

**To Reproduce**
1. Setup LDAP as mention below
2. Clic Sync LDAP Users
3. Got an infinite loading popup

**Logfile**
```
[2022-12-18 18:46:02,650] ERROR {cps:1457} Exception on /import_ldap_users [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/local/lib/python3.10/dist-packages/flask_login/utils.py", line 303, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/app/calibre-web/cps/admin.py", line 95, in inner
    return f(*args, **kwargs)
  File "/app/calibre-web/cps/admin.py", line 1575, in import_ldap_users
    new_users = services.ldap.get_group_members(config.config_ldap_group_name)
  File "/app/calibre-web/cps/services/simpleldap.py", line 96, in get_group_members
    return _ldap.get_group_members(group)
  File "/usr/local/lib/python3.10/dist-packages/flask_simpleldap/__init__.py", line 256, in get_group_members
    conn = self.bind
  File "/usr/local/lib/python3.10/dist-packages/flask_simpleldap/__init__.py", line 115, in bind
    conn = self.initialize
  File "/usr/local/lib/python3.10/dist-packages/flask_simpleldap/__init__.py", line 98, in initialize
    conn = self._set_custom_options(conn)
  File "/usr/local/lib/python3.10/dist-packages/flask_simpleldap/__init__.py", line 81, in _set_custom_options
    conn.set_option(k, v)
  File "/usr/local/lib/python3.10/dist-packages/ldap/ldapobject.py", line 698, in set_option
    return self._ldap_call(self._l.set_option,option,invalue)
  File "/usr/local/lib/python3.10/dist-packages/ldap/ldapobject.py", line 128, in _ldap_call
    result = func(*args,**kwargs)
ValueError: option error
```
**Expected behavior**
LDAP user would sync or give an understable error.

**Environment (please complete the following information):**
 - OS: Unraid / Docker
 - Calibre-Web version: 0.6.19
 - Docker container: lscr.io/linuxserver/calibre-web

**Additional context**
As said i'm not sure about the certificate files, but if i try to put a wrong file on purpose i got an error when trying to save, so i guess it's ok.

My LDAP is a Synology with Active directory software.

Here is my config : 

```
LDAP Server Host Name or IP Address
ds920.zordon.dom // tried with IP too
LDAP Server Port
686
LDAP Encryption
SSL / tried TLS too
LDAP CACertificate Path (Only needed for Client Certificate Authentication)
**/books/CertifAD/server.csr** 
LDAP Certificate Path (Only needed for Client Certificate Authentication)
**/books/CertifAD/cert.pem**
LDAP Keyfile Path (Only needed for Client Certificate Authentication)
**/books/CertifAD/privkey.pem**
LDAP Authentication
Simple
LDAP Administrator Username
CN=***,CN=Users,DC=zordon,DC=dom
LDAP Administrator Password
LDAP Distinguished Name (DN)
DC=zordon,DC=dom
LDAP User Object Filter
(&(memberof=CN=Calibre,CN=Users,DC=zordon,DC=dom)(cn=%s))
 LDAP Server is OpenLDAP?
Tried Y and N > same result.
```

Search string seems ok as they are working with DSquerry.

**Comment by khalimerot** [comment]
So, i have read a lot about CAcert, how to setup it's own CA signed certificate 

This tutorial helped a lot : 

https://arminreiter.com/2022/01/create-your-own-certificate-authority-ca-using-openssl/

So i created my own CA cert, Cacert.crt wich is installed on Windows, and on the calibre-web : 

"LDAP CACertificate Path"

Then i created a new certificate signed with the CAcert.crt

Wich i installed on my synology giving the key (app.crt & app.key) 
app.crt is in calibre : "LDAP Certificate Path"
and app.key is in calibre : "LDAP Keyfile Path"

On the synology it seems to work, when i'm going on it's webpage i don't have the usual unsecure website as the RootCA is installed on Windows.

In calibre i have a "can't contact LDAP server"

I'll try to add the CAcert to one of my debian VM and see if ldapsearch give an error.

**Comment by khalimerot** [comment]
Still digging.

It seems ldapsearch (wich is used by calibre web if i'm not wrong) deprecated SSL (again if i'm not wrong)

So, i setup Calibre-Web to connect with TLS on port 389. 

Now i have an answer but it's "0 User Successfully Imported"

The problem must come from my filters, i'll continue to search.

**Comment by khalimerot** [comment]
Solved, and everything working, 

So there was not any problem with Calibre-Web just me having trouble understanding how it works.

If someone with a Synology Directory Server app (not the LDAP one) read this:

you must use TLS on port 389

LDAPS will not work with Calibre-Web and the synology directory server
