### ISSUE TITLE
Calibre-web not syncing to Kobo Libra 2

### ISSUE THREAD

**Issue by Tekgnome-svg** [janeczku/calibre-web#2651]
Calibre-web not syncing to Kobo Libra 2. 

I have set up calibre-web, setup a bookshelf, enabled kobo sync, and replaced the API URL on the tablet with the one provided but it won't sync.

**To Reproduce**
1. setup calibre-web
2. Enable Kobo sync in basic settings, Port 8083
3. replaced kobo Webstore API with the one provided under my account (api_endpoint=http://192.168.1.10:8083/kobo/redacted)
4. setup shelf and add book(s)
5. Tap sync on Kobo Libra 2

.

**Expected behavior**
Books to download and sync

**Environment (please complete the following information):**
 - OS: Truenas Scale
 - Truecharts Docker Calibre-Web app
 - Calibre-Web version: 0.6.19_13.0.11
 - Docker container: Yes
 - Special Hardware: Kobo Libra 2

Troubleshooting steps I have tried:
Restarting Kobo device
Restarting server
Force sync
Factory resetting Kobo Libra 2 and re-setting it back up again
Tried different port numbers

**Comment by HamzaM** [comment]
What error do you get ? I tried this today on my Kobo Clara HD and I also get an error but it says "Network Error" after I click disovery on the bottom of the main page (after successfully syncing)

**Comment by Tekgnome-svg** [comment]
There's no specific error, it acts like the sync is successful but non of the books on my shelf sync over to it.

**Comment by HamzaM** [comment]
> There's no specific error, it acts like the sync is successful but none of the books on my shelf sync over to it.

What do you see in the /sync link from your opds ?

**Comment by flipside101** [comment]
same issue as OP same device a well. The connects but stays on "checking for updates" and then I get "Sync Failed. please try again" when i remove the api line it connects and updates and syncs to the cloud

**Comment by KeenanWoods** [comment]
Another data point for this issue: I have the same issue as OP, but not as @flipside101 - I don't get a "Sync Failed" pop-up; the Kobo thinks it synced properly. 

For further testing, I was able to get this syncing and running perfectly on my Kobo Forma (syncs as normal with Calibre-web, including downloading new books). I even tried copy-pasting the "Kobo eReader.conf" file from my Forma to my Clara 2e, but I still had the exact same issue: the device thinks it is syncing properly, but it doesn't sync with my Calibre-web setup.

My /sync file shows when the Forma connects, but it doesn't reflect any connection attempts by the Clara 2e (successful or unsuccessful).

**Comment by flipside101** [comment]
http://myipaddress:8083/kobo/MyToken/v1/library/sync - looks to pull only part of a library sync

**Comment by flipside101** [comment]
Has anyone found a fix for this yet ?

**Comment by flipside101** [comment]
error from logs
[2023-01-30 21:23:46,039] ERROR {cps:1457} Exception on /kobo/056efa4093fa37886f5e35e3e0cf27c2/v1/library/sync [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlite3.DatabaseError: database disk image is malformed
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/app/calibre-web/cps/kobo_auth.py", line 162, in inner
    return f(*args, **kwargs)
  File "/app/calibre-web/cps/web.py", line 116, in inner
    return f(*args, **kwargs)
  File "/app/calibre-web/cps/kobo.py", line 213, in HandleSyncRequest
    log.debug("Books to Sync: {}".format(len(books.all())))
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/orm/query.py", line 2773, in all
    return self._iter().all()
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/orm/query.py", line 2916, in _iter
    result = self.session.execute(
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/orm/session.py", line 1714, in execute
    result = conn._execute_20(statement, params or {}, execution_options)
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/base.py", line 1705, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/sql/elements.py", line 334, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/base.py", line 1572, in _execute_clauseelement
    ret = self._execute_context(
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/base.py", line 1943, in _execute_context
    self._handle_dbapi_exception(
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/base.py", line 2124, in _handle_dbapi_exception
    util.raise_(
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.DatabaseError: (sqlite3.DatabaseError) database disk image is malformed
[SQL: SELECT books.id AS books_id, books.title AS books_title, books.sort AS books_sort, books.author_sort AS books_author_sort, books.timestamp AS books_timestamp, books.pubdate AS books_pubdate, books.series_index AS books_series_index, books.last_modified AS books_last_modified, books.path AS books_path, books.has_cover AS books_has_cover, books.uuid AS books_uuid, books.isbn AS books_isbn, books.flags AS books_flags, archived_book.last_modified AS archived_book_last_modified, archived_book.is_archived AS archived_book_is_archived 
FROM books JOIN calibre.data ON books.id = calibre.data.book LEFT OUTER JOIN archived_book ON books.id = archived_book.book_id AND archived_book.user_id = ? 
WHERE (books.id NOT IN (SELECT kobo_synced_books.book_id 
FROM kobo_synced_books 
WHERE kobo_synced_books.user_id = ?)) AND 1 = 1 AND calibre.data.format IN (?, ?) ORDER BY books.last_modified, books.id
 LIMIT ? OFFSET ?]
[parameters: (5, 5, 'KEPUB', 'EPUB', 100, 0)]
(Background on this error at: https://sqlalche.me/e/14/4xp6)
[2023-01-30 21:23:56,043] DEBUG {cps.updater:323} Nightly version: d2056ceb51b33cf3dfe079f024fcba905609f186, 2023-01-29T14:28:49+01:00
[2023-01-30 21:32:50,446] DEBUG {cps.ub:83} Found stored session: d4fcbab8f25e49c3ee4ecaeb0d249ee059b9374b6295f30c02228b9e31e168510fce501c238d3578ddcc945721e9443a6f07ac60fc3b212655ff7766981af411
[2023-01-30 21:32:51,107] DEBUG {cps.ub:83} Found stored session: d4fcbab8f25e49c3ee4ecaeb0d249ee059b9374b6295f30c02228b9e31e168510fce501c238d3578ddcc945721e9443a6f07ac60fc3b212655ff7766981af411
[2023-01-30 21:35:34,997] DEBUG {cps.updater:323} Nightly version: d2056ceb51b33cf3dfe079f024fcba905609f186, 2023-01-29T14:28:49+01:00
[2023-01-30 21:36:25,438] DEBUG {cps.helper:943} unrar version 6.11 beta 1
[2023-01-30 21:36:25,439] DEBUG {cps.config_sql:346} _ConfigSQL updating storage
[2023-01-30 21:37:51,459] DEBUG {cps.ub:83} Found stored session: d4fcbab8f25e49c3ee4ecaeb0d249ee059b9374b6295f30c02228b9e31e168510fce501c238d3578ddcc945721e9443a6f07ac60fc3b212655ff7766981af411
[2023-01-30 21:37:51,682] DEBUG {cps.ub:83} Found stored session: d4fcbab8f25e49c3ee4ecaeb0d249ee059b9374b6295f30c02228b9e31e168510fce501c238d3578ddcc945721e9443a6f07ac60fc3b212655ff7766981af411
[2023-01-30 21:37:51,804] DEBUG {cps.ub:83} Found stored session: d4fcbab8f25e49c3ee4ecaeb0d249ee059b9374b6295f30c02228b9e31e168510fce501c238d3578ddcc945721e9443a6f07ac60fc3b212655ff7766981af411
[2023-01-30 21:37:51,804]  INFO {cps.kobo:141} Kobo library sync request received.
[2023-01-30 21:37:51,804] DEBUG {cps.kobo:142} SyncToken: 0001-01-01 00:00:00,0001-01-01 00:00:00,0001-01-01 00:00:00,0001-01-01 00:00:00,0001-01-01 00:00:00,eyJ0eXAiOjEsInZlciI6bnVsbCwicHR5cCI6IlN5bmNUb2tlbiJ9.eyJJbnRlcm5hbFN5bmNUb2tlbiI6ImV5SjBlWEFpT2pFc0luWmxjaUk2SW5ZeUlpd2ljSFI1Y0NJNklsTjVibU5VYjJ0bGJpSjkuZXlKVGRXSnpZM0pwY0hScGIyNUZiblJwZEd4bGJXVnVkSE1pT25zaVNYTkpibWwwYVdGc0lqcHVkV3hzTENKSFpXNWxjbUYwYVc5dVZHbHRaU0k2Ym5Wc2JDd2lWR2x0WlhOMFlXMXdJam9pTVRrd01DMHdNUzB3TVZRd01Eb3dNRG93TUZvaUxDSkRhR1ZqYTFOMWJTSTZiblZzYkN3aVNXUWlPaUl3TURBd01EQXdNQzB3TURBd0xUQXdNREF0TURBd01DMHdNREF3TURBd01EQXdNREFpZlN3aVJuVjBkWEpsVTNWaWMyTnlhWEIwYVc5dVJXNTBhWFJzWlcxbGJuUnpJanB1ZFd4c0xDSkZiblJwZEd4bGJXVnVkSE1pT25zaVNYTkpibWwwYVdGc0lqcHVkV3hzTENKSFpXNWxjbUYwYVc5dVZHbHRaU0k2Ym5Wc2JDd2lWR2x0WlhOMFlXMXdJam9pTWpBeU15MHdNUzB5TlZReU1qb3pOam8xTkZvaUxDSkRhR1ZqYTFOMWJTSTZJbnRjSWxOcmFYQkRjbVZoZEdWa1hDSTZabUZzYzJVc1hDSkRjbVZoZEdWa1EyOTFiblJjSWpveExGd2lRM0psWVhSbFpGd2lPbHRjSW1WbU5qTXdZMkV3TFRrek5tRXROR00yTkMwNVkyVTNMVGs1TlRNek5qZ3lZalV6TkZ3aVhTeGNJbE5yYVhCTmIyUnBabWxsWkZ3aU9tWmhiSE5sTEZ3aVRXOWthV1pwWldSY0lqcGJYWDBpTENKSlpDSTZJbVZtTmpNd1kyRXdMVGt6Tm1FdE5HTTJOQzA1WTJVM0xUazVOVE16TmpneVlqVXpOQ0o5TENKRVpXeGxkR1ZrUlc1MGFYUnNaVzFsYm5SeklqcDdJa2x6U1c1cGRHbGhiQ0k2Ym5Wc2JDd2lSMlZ1WlhKaGRHbHZibFJwYldVaU9tNTFiR3dzSWxScGJXVnpkR0Z0Y0NJNklqSXdNak10TURFdE1UQlVNakk2TXpFNk5UVmFJaXdpUTJobFkydFRkVzBpT201MWJHd3NJa2xrSWpvaU1EQXdNREF3TURBdE1EQXdNQzB3TURBd0xUQXdNREF0TURBd01EQXdNREF3TURBd0luMHNJbEpsWVdScGJtZFRkR0YwWlhNaU9uc2lTWE5KYm1sMGFXRnNJanB1ZFd4c0xDSkhaVzVsY21GMGFXOXVWR2x0WlNJNmJuVnNiQ3dpVkdsdFpYTjBZVzF3SWpvaU1qQXlNeTB3TVMweU9WUXlNem95TURveU9Gb2lMQ0pEYUdWamExTjFiU0k2Ym5Wc2JDd2lTV1FpT2lKbE1EWmhaalZqWVMxaU1HTTNMVFEzTURrdFlURmpZeTB3Tm1FNU5XUTJaVEJsWWpVaWZTd2lWR0ZuY3lJNmV5SkpjMGx1YVhScFlXd2lPbTUxYkd3c0lrZGxibVZ5WVhScGIyNVVhVzFsSWpwdWRXeHNMQ0pVYVcxbGMzUmhiWEFpT2lJeU1ESXpMVEF4TFRJMVZESXlPak0yT2pVMVdpSXNJa05vWldOclUzVnRJanB1ZFd4c0xDSkpaQ0k2SWpReE1EUTBNams0TFRkak1tVXRORGd6TUMxaE5HSTVMVGN3WkRCaU1USmpZamd4WkNKOUxDSkVaV3hsZEdWa1ZHRm5jeUk2ZXlKSmMwbHVhWFJwWVd3aU9tNTFiR3dzSWtkbGJtVnlZWFJwYjI1VWFXMWxJanB1ZFd4c0xDSlVhVzFsYzNSaGJYQWlPaUl4T1RBd0xUQXhMVEF4VkRBd09qQXdPakF3V2lJc0lrTm9aV05yVTNWdElqcHVkV3hzTENKSlpDSTZJakF3TURBd01EQXdMVEF3TURBdE1EQXdNQzB3TURBd0xUQXdNREF3TURBd01EQXdNQ0o5TENKUWNtOWtkV04wVFdWMFlXUmhkR0VpT25zaVNYTkpibWwwYVdGc0lqcHVkV3hzTENKSFpXNWxjbUYwYVc5dVZHbHRaU0k2Ym5Wc2JDd2lWR2x0WlhOMFlXMXdJam9pTWpBeU15MHdNUzB4TUZReU1qb3pNVG8xTlZvaUxDSkRhR1ZqYTFOMWJTSTZiblZzYkN3aVNXUWlPaUl3TURBd01EQXdNQzB3TURBd0xUQXdNREF0TURBd01DMHdNREF3TURBd01EQXdNREFpZlgwIiwiSXNDb250aW51YXRpb25Ub2tlbiI6ZmFsc2V9
[2023-01-30 21:37:51,805] DEBUG {cps.kobo:144} Kobo: Received unproxied request, changed request port to external server port
[2023-01-30 21:37:57,872] ERROR {cps:1457} Exception on /kobo/056efa4093fa37886f5e35e3e0cf27c2/v1/library/sync [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlite3.DatabaseError: database disk image is malformed
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/app/calibre-web/cps/kobo_auth.py", line 162, in inner
    return f(*args, **kwargs)
  File "/app/calibre-web/cps/web.py", line 116, in inner
    return f(*args, **kwargs)
  File "/app/calibre-web/cps/kobo.py", line 213, in HandleSyncRequest
    log.debug("Books to Sync: {}".format(len(books.all())))
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/orm/query.py", line 2773, in all
    return self._iter().all()
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/orm/query.py", line 2916, in _iter
    result = self.session.execute(
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/orm/session.py", line 1714, in execute
    result = conn._execute_20(statement, params or {}, execution_options)
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/base.py", line 1705, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/sql/elements.py", line 334, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/base.py", line 1572, in _execute_clauseelement
    ret = self._execute_context(
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/base.py", line 1943, in _execute_context
    self._handle_dbapi_exception(
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/base.py", line 2124, in _handle_dbapi_exception
    util.raise_(
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.DatabaseError: (sqlite3.DatabaseError) database disk image is malformed
[SQL: SELECT books.id AS books_id, books.title AS books_title, books.sort AS books_sort, books.author_sort AS books_author_sort, books.timestamp AS books_timestamp, books.pubdate AS books_pubdate, books.series_index AS books_series_index, books.last_modified AS books_last_modified, books.path AS books_path, books.has_cover AS books_has_cover, books.uuid AS books_uuid, books.isbn AS books_isbn, books.flags AS books_flags, archived_book.last_modified AS archived_book_last_modified, archived_book.is_archived AS archived_book_is_archived 
FROM books JOIN calibre.data ON books.id = calibre.data.book LEFT OUTER JOIN archived_book ON books.id = archived_book.book_id AND archived_book.user_id = ? 
WHERE (books.id NOT IN (SELECT kobo_synced_books.book_id 
FROM kobo_synced_books 
WHERE kobo_synced_books.user_id = ?)) AND 1 = 1 AND calibre.data.format IN (?, ?) ORDER BY books.last_modified, books.id
 LIMIT ? OFFSET ?]
[parameters: (5, 5, 'KEPUB', 'EPUB', 100, 0)]
(Background on this error at: https://sqlalche.me/e/14/4xp6)
[2023-01-30 21:38:26,173] DEBUG {cps.updater:323} Nightly version: d2056ceb51b33cf3dfe079f024fcba905609f186, 2023-01-29T14:28:49+01:00

**Comment by ExtraGG** [comment]
I am also affected by this issue. Sync takes very long, and then it fails.

**Comment by aniqueta** [comment]
I have the same issue with a Libra 2. Only syncing 25 books, some recently add but also some not. Unclear pattern, and logs look normal.

**Comment by aniqueta** [comment]
I resolved this for my Libra 2 after using `Force full kobo sync` in the user settings. It appears this is necessary when moving to a new device.

**Comment by aniqueta** [comment]
Proposed updates to the wiki: https://github.com/janeczku/calibre-web/wiki/Kobo-Integration#changing-kobo-devices

**Comment by jzarca01** [comment]
From what I could try, you need to make sure your user has "Allow downloads" checked

**Comment by lukehmcc** [comment]
I have "Allow Downloads" enabled, and my /sync endpoint is populated properly. My but Libra 2 is also failing. Only 18 books. This happened after my kobo updated last.

**Comment by Bykow** [comment]
I have similar situation:
- allow downloads
- /sync populated
- Libra 2 
- On the Kobo: "Sync Failed. Please try again."

Logs of the container:
```
INFO {cps.kobo:1066} Init 
INFO {cps.kobo:143} Kobo library sync request received. 
```
Nothing else sadly...

**Comment by OzzieIsaacs** [comment]
@bart47 are you syncing both devices to one user account? This is not working

**Comment by barthoum47** [comment]
i should retry it with a second account/token...
But 2 devices should theorically work on the same calbre-web account/token, if i reset sync history on calibre web between syncs

**Comment by auspex** [comment]
I'm having a similar problem (I can't, for the life of me remember _which_ Kobo I have...). My Kobo synced fine before I had a drive failure on my server and had to rebuild my docker stack.

https://books.***/kobo/TOKEN/v1/library/sync returns a well formed JSON object. I have no idea if it's _correct_ but it looks right.

If I try to sync from the Kobo, there's no sign that it even tries to connect in the calibre-web log (whereas going to the URL in a browser shows `[2024-01-28 18:25:49,484]  INFO {cps.kobo:146} Kobo library sync request received`).

I tried deleting .kobo/Kobo/Kobo eReader.conf, and it synced fine directly to Kobo, then I added the `api_endpoint=` line (to sync to calibre-web rather than Kobo) and sync stopped working. So, the wifi is clearly operational, but it doesn't seem to send anything to calibre-web

**Comment by subnetz** [comment]
@auspex If you're using a reverse proxy (like nginx), add the following proxy settings:  
```nginx
        server_name books.example.com;

        location / {
                proxy_pass                   http://127.0.0.1:8083;
                proxy_set_header             Host              $http_host;
                proxy_set_header             X-Forwarded-For   $proxy_add_x_forwarded_for;
                proxy_set_header             X-Scheme          $scheme;
                proxy_set_header             X-Script-Name     /calibre-web;
                proxy_busy_buffers_size      1024k;
                proxy_buffers                4                 512k;
                proxy_buffer_size            1024k;
        }
        client_max_body_size 2G;
```
- reload nginx with `sudo nginx -s reload`
- try to sync again
- if it doesn't work yet, go to `My Profile` -> `Kobo Sync Token` -> `Force Full Kobo Sync`

**Comment by auspex** [comment]
It's traefik, and it _should_ have those settings, but I'll check. It's funny, I just said to my wife that I really needed to get back to fixing this, and your response arrived within a couple of minutes🤣

**Comment by auspex** [comment]
No dice. I still see nothing in the log. How do I turn on Debug logging? Also, what do I have to do to stop it complaining at startup:
```
WARN {cps.config_sql:352} Log path  not valid, falling back to default
```
fwiw, the old (working) traefik setup before my drive died definitely didn't have the `X-Script-Name` header set.

**Comment by Drakmyth** [comment]
Not sure if this has been ruled out, but I got a Libra 2 recently and was experiencing the same issue. In my case the issue was that I had uploaded *.azw books I had pulled from Kindle, but they were actually KFX format books and couldn't be converted. After installing the KFX Input and DeDRM plugins into the calibre desktop app, I was able to convert them to *.epub. From there calibre-web had no trouble syncing them to my selected shelf and onto my device.

In the logs it looked like everything was fine, the sync would run but the books just wouldn't appear on the device. It was through mostly luck that I decided to install those plugins and try again from scratch that I discovered the real issue.

**Comment by c64bob** [comment]
> In my case, I think I have to just blame my Kobo. I'm finding it dropping wifi while doing other things. Why it can get _some_ connectivity to through the browser and none with the he kobo sync is a mystery, but it's not reliable enough to be blaming calibre-web

@auspex , did you manage to find out why the kobo sync didn't work? I'm asking because I have exactly the same problem. I have a kobo clara colour, and wifi is fully functional. I can sync with the kobo cloud, but as soon as I switch out the api_endpoint with the one provided by calibre-web, there is an error that "sync failed". I am using traefik as well, and no sync requests are showing up in my access logs. Accessing the endpoint by browser shows a fully working sync, so the problem must be either my kobo or traefik.

Any pointers are greatly appreciated :)

**Comment by auspex** [comment]
No. In my case I'm sure it's the Wi-Fi. I'm fact the other day, I noticed that it HAD successfully synced with my calibre-web, even though I had changed nothing. I know the Wi-Fi works _sometimes_, and seeing the sync work occasionally is consistent

**Comment by rjaakke** [comment]
Disable syncing Notebooks in the sync settings on the Kobo fixed it for me on de Libra 2 Color.

**Comment by flipside101** [comment]
> Disable syncing Notebooks in the sync settings on the Kobo fixed it for me on de Libra 2 Color.

Unfortunately that setting is on the libre 2

**Comment by encg** [comment]
> Disable syncing Notebooks in the sync settings on the Kobo fixed it for me on de Libra 2 Color.

Thanks - this fixed the sync issue with my Libra Colour

**Comment by alexlambson** [comment]
Can someone post the `Kobo eReader.conf` with the sync settings disabled? I don't have access to the sync settings when not logged in

**Comment by rjaakke** [comment]
NotebookSync=false 

This should disable notebook syncing.

**Comment by alexlambson** [comment]
Ah I see. I have to be signed in for sync to work at all

**Comment by jasongi** [comment]
Had the same issue when trying to use calibre-web behind nginx-proxy-manager, was solved by:

### 1. settings the proxy buffer vars ([as above](https://github.com/janeczku/calibre-web/issues/2651#issuecomment-1925476291))

you can see if this is an issue based on these (nginx proxy manager) logs:
```
2025/01/26 06:42:48 [error] 1284#1284: *1828594 upstream sent too big header while reading response header from upstream
```
The vars I set were...
```
proxy_busy_buffers_size      1024k;
proxy_buffers                4                 512k;
proxy_buffer_size            1024k;
```

Because I'm using nginx proxy manager, do this in "Advanced" tab like this:

```
location / {
    proxy_busy_buffers_size      1024k;
    proxy_buffers                4                 512k;
    proxy_buffer_size            1024k;
    include conf.d/include/proxy.conf;
}
```

### 2. Forcing https, setting the forward port from 443 to 80

Because I'm behind a reverse proxy with SSL Termination, I thought I would Force HTTPS and set the "Server External Port (for port forwarded API calls)" to 443. Turns out this breaks the images which the kobo only ever fetches via http. This means that you need to have http (and optionally https) and the Server External Port needs to be the http one. I saw this problem manifest in my reverse proxy logs like this:
```
[26/Jan/2025:07:57:38 +0000] - - 400 - GET http redacted.com "/kobo/redacted/isGreyscale/image.jpg"
```
and then in the calibre-web logs I saw the requests never made it to the instance because they were `http` requests to an https only proxy.

The solution was to uncheck "Force SSL" and change the Server External Port to port 80. You can still leave SSL on and list the api_endpoint as https, but the images will always go via http. I don't know why becuase the cdn in Kobo eReader.conf appears to be listed as https - but I observed it always going to the http URL.

**Comment by bfcns** [comment]
Is the "Force SSL" a calibre setting or a web server?

**Comment by UnaDeKalamares** [comment]
I'm seeing this same issue with a Kobo Libra Colour. I've setup the sync token, deleted and re-created it, and forced a full kobo sync, all to no avail. This is all I can see in my container's log:

[2026-05-03 12:32:59,845]  INFO {kobo.py:1062} Init
[2026-05-03 12:33:01,279]  INFO {kobo.py:149} Kobo library sync request received

I'm running Calibre-Web 0.6.26, and my device is on 4.45.23684 

EDIT: I realized that I provided not enough information. Apologies. 

I used to be able to sync shelves effortlessly, and I've realized that, if I make a shelf no longer available to my user and force a full Kobo sync, It won't get deleted on my device, and I still can download every book. It looks like the sync DB is not being updated or something similar.

Also, I'm running in plain HTTP mode, since this server is not open to the web.

**Comment by new-usemame** [comment]
If your Kobo says "Sync failed, please try again" behind nginx, the fix is bumping nginx's default `proxy_buffer_size` — the sync response headers exceed nginx's 4 KB default and nginx silently drops the response (CWA log shows nothing). Several folks in this thread already worked this out from the nginx error log (`upstream sent too big header`). We just shipped the documentation for it in [Calibre-Web-NextGen](https://github.com/new-usemame/Calibre-Web-NextGen), a community-maintained CWA build:

```nginx
proxy_buffer_size       32k;
proxy_buffers           4 32k;
proxy_busy_buffers_size 64k;
```

(Larger libraries: `128k / 4 256k / 256k`.) Released today in v4.0.139 ([\`fb4134a3\`](https://github.com/new-usemame/Calibre-Web-NextGen/commit/fb4134a3)) — the Kobo sync section of the README now has a prominent callout, the "Sync failed" troubleshooting entry lists the buffer cause, and there's a copy-paste-ready reference config at [\`examples/nginx-reverse-proxy.conf\`](https://github.com/new-usemame/Calibre-Web-NextGen/blob/main/examples/nginx-reverse-proxy.conf) with TLS, X-Forwarded-* headers, upload-size, and the buffer directives. Comments in the config explain why each non-default value exists so future maintainers don't "clean it up" back to broken defaults.

Drop-in image: \`ghcr.io/new-usemame/calibre-web-nextgen:latest\`. Heads-up if you're on plain calibre-web rather than CWA: this build is CWA-derived, so it bakes in the auto-ingest folder watcher, the kepubify pipeline, and KOReader sync on top of the same calibre-web core.

Reported on the fork side by @Glennza1962 ([new-usemame/Calibre-Web-NextGen#308](https://github.com/new-usemame/Calibre-Web-NextGen/issues/308)) and @Gusdezup ([#331](https://github.com/new-usemame/Calibre-Web-NextGen/issues/331)) — both independently traced the same root cause. Fork tracker for follow-up: https://github.com/new-usemame/Calibre-Web-NextGen/issues.

**Comment by UnaDeKalamares** [comment]
Thank you @new-usemame but I'm not running nginx but the problem persists, and my Kobo doesn't throw any errors; it simply refuses to sync.

However, I've noticed that it might only be related to new shelves; adding new books to a shelf already synced with the e-reader actually works. It used to work, otherwise I wouldn't have any shelf on my device.
