### ISSUE TITLE
Date parse error

### ISSUE THREAD

**Issue by vlapra** [janeczku/calibre-web#2656]
I run latest docker image (lscr.io/linuxserver/calibre-web) at Synology NAS docker using CLI command.
After logging into I got exception.
Do you have any idea?
```
Traceback (most recent call last):
File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 2073, in wsgi_app
response = self.full_dispatch_request()
File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1518, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1516, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1502, in dispatch_request
return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
File "/app/calibre-web/cps/usermanagement.py", line 35, in decorated_view
return login_required(func)(*args, **kwargs)
File "/usr/local/lib/python3.10/dist-packages/flask_login/utils.py", line 303, in decorated_view
return current_app.ensure_sync(func)(*args, **kwargs)
File "/app/calibre-web/cps/web.py", line 781, in index
return render_books_list("newest", sort_param, 1, page)
File "/app/calibre-web/cps/web.py", line 399, in render_books_list
entries, random, pagination = calibre_db.fill_indexpage(page, 0, db.Books, True, order[0],
File "/app/calibre-web/cps/db.py", line 730, in fill_indexpage
return self.fill_indexpage_with_archived_books(page, database, pagesize, db_filter, order, False,
File "/app/calibre-web/cps/db.py", line 740, in fill_indexpage_with_archived_books
.limit(self.config.config_random_books).all())
File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/orm/query.py", line 2773, in all
return self._iter().all()
File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/result.py", line 1129, in all
return self._allrows()
File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/result.py", line 401, in _allrows
rows = self._fetchall_impl()
File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/result.py", line 1813, in _fetchall_impl
return list(self.iterator)
File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/orm/loading.py", line 147, in chunks
fetch = cursor._raw_all_rows()
File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/result.py", line 393, in _raw_all_rows
return [make_row(row) for row in rows]
File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/result.py", line 393, in <listcomp>
return [make_row(row) for row in rows]
ValueError: Couldn't parse datetime string: '2011-01-01'
```

**Comment by onovy** [comment]
Hit same bug. "pubdate" in Calibre DB is timestamp. It can store "date only" in format "2011-01-01" or "date+time" in format "2011-01-01 00:00...". Both formats work in Calibre, only first one in Calibre web. I fixed in in my local DB manually.

**Comment by vlapra** [comment]
Thanks, it really helps. I have corrected data this way:

```
UPDATE books
SET pubdate = DATETIME(pubdate, '+0 minutes');
```

**Comment by OzzieIsaacs** [comment]
Is there a setting to change the publishing date to only "date" in calibre itself?

**Comment by onovy** [comment]
According to source code, Calibre always stores date+time+tz (in UTC) and it's using datetime utils parser to parse it back. That parser supports all formats. So it's not possible to break it with Callibre itself, but only with other third-party tools.

One problem is with SQLite3 itself - it doesn't validate timestamp field (which is feature):
```
sqlite> create table a (ts timestamp);
sqlite> .schema a
CREATE TABLE a (ts timestamp);
sqlite> insert into a values ('abcde');
sqlite> select * from a;
abcde
sqlite> 
```

Second problem is with missing specification of Calibre metadata DB file. Is it valid to have "YYYY-MM-DD" format or not?

Because Calibre is "reference implementation" and Calibre supports this date format, I think it's better to support it (for reading) too. It's harmless.

**Comment by OzzieIsaacs** [comment]
@onovy: Well, the question is still how can it happen to have a date only date in the calibre database? 
Is there any setting in Calibre itself?

**Comment by onovy** [comment]
Already answered both questions in my last post.
