### ISSUE TITLE
Error 500 'User' object has no attribute 'eReader_mail'

### ISSUE THREAD

**Issue by BasedDodge** [janeczku/calibre-web#2670]
Getting Error 500 when trying to send book to reader. Seems there's a flask issue and the user class is missing some attributes?

**To Reproduce**
1. Go to book
2. Click on "Send to eReader"
3. See error

Log:
```
[2023-01-21 22:26:10,848] ERROR {cps:1449} Exception on /send/67/Mobi/0 [POST]
Traceback (most recent call last):
  File "/opt/calibre-web/venv/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/calibre-web/venv/lib/python3.8/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/calibre-web/venv/lib/python3.8/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/calibre-web/venv/lib/python3.8/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/opt/calibre-web/venv/lib/python3.8/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/opt/calibre-web/cps/web.py", line 116, in inner
    return f(*args, **kwargs)
  File "/opt/calibre-web/cps/web.py", line 1201, in send_to_ereader
    elif current_user.eReader_mail:
AttributeError: 'User' object has no attribute 'eReader_mail'
```

**Expected behavior**
Send file to eReader

**Environment (please complete the following information):**
 - OS: Ubuntu 
 - Python version: [e.g. python2.7]
 - Calibre-Web version: 0.6.19 
 - Docker container: None
 - Browser: Firefox 108.0.2

**Comment by OzzieIsaacs** [comment]
Sorry, please update to the newest nightly version, should work again then
