### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by gt-sun** [janeczku/calibre-web#2691]
**Describe the bug/problem**
500 code

**To Reproduce**
1. Go to '/'

**Logfile**
The server encountered an internal error and was unable to complete your request. There is an error in the application.
Traceback (most recent call last):
File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 2073, in wsgi_app
response = self.full_dispatch_request()
File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1519, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1517, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1503, in dispatch_request
return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
File "/usr/local/lib/python3.10/dist-packages/flask_login/utils.py", line 290, in decorated_view
return current_app.ensure_sync(func)(*args, **kwargs)
File "/app/calibre-web/cps/web.py", line 1431, in profile
languages = calibre_db.speaking_language()
File "/app/calibre-web/cps/db.py", line 975, in speaking_language
languages = self.session.query(Languages) \
AttributeError: 'NoneType' object has no attribute 'query'

**Expected behavior**

**Screenshots**
<img width="1387" alt="image" src="https://user-images.githubusercontent.com/12756112/218317319-4ff74cf7-5cf2-4ce3-8884-5b3ce8483c4e.png">

**Environment (please complete the following information):**
 - OS: ~# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.5 LTS
Release:	20.04
Codename:	focal
 - Docker container: linuxserver/calibre-web:nightly-version-dda20eb9

**Comment by OzzieIsaacs** [comment]
Calibre-Web is a web app providing a clean interface for browsing, reading and downloading eBooks using a **valid** [Calibre](https://calibre-ebook.com/) database.

**Comment by Athanor66** [comment]
I solved the problem by adding the user and the **docker** group to the ACL of the folder containing the metadata.db file.
If you see into the log file, you can find something similar to this:
```
[2023-01-27 17:41:59,734] ERROR {cps.config_sql:357} (sqlite3.OperationalError) _unable to open database: /riviste/metadata.db_
[SQL: attach database '/riviste/metadata.db' as calibre;]
```
Try these commands in a ssh shell:
`getfacl /Volume2/BIBLIOTECHE/RIVISTE/ `  <---- your Calibre folder, where is the metadata.db file
if "docker" isn't present in the ACL, add it with these commands:
```
setfacl -m u:docker:wrx /Volume2/BIBLIOTECHE/RIVISTE/
setfacl -m g:docker:wrx /Volume2/BIBLIOTECHE/RIVISTE/
```

Then restart your calibre-web docker component e voilà, it works!
