### ISSUE TITLE
Database errors 

### ISSUE THREAD

**Issue by FlavioDF** [janeczku/calibre-web#2698]
Calibre Web
500 Internal Server Error
The server encountered an internal error and was unable to complete your request. There is an error in the application.
Traceback (most recent call last):
File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
self.dialect.do_execute(
File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/default.py", line 736, in do_execute
cursor.execute(statement, parameters)
sqlite3.OperationalError: database is locked
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 2073, in wsgi_app
response = self.full_dispatch_request()
File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1518, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1516, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1502, in dispatch_request
return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
File "/app/calibre-web/cps/usermanagement.py", line 35, in decorated_view
return login_required(func)(*args, **kwargs)
File "/usr/local/lib/python3.10/dist-packages/flask_login/utils.py", line 303, in decorated_view
return current_app.ensure_sync(func)(*args, **kwargs)
File "/app/calibre-web/cps/web.py", line 781, in index
return render_books_list("newest", sort_param, 1, page)
File "/app/calibre-web/cps/web.py", line 399, in render_books_list
entries, random, pagination = calibre_db.fill_indexpage(page, 0, db.Books, True, order[0],
File "/app/calibre-web/cps/db.py", line 730, in fill_indexpage
return self.fill_indexpage_with_archived_books(page, database, pagesize, db_filter, order, False,
File "/app/calibre-web/cps/db.py", line 765, in fill_indexpage_with_archived_books
.filter(self.common_filters(allow_show_archived))
File "/app/calibre-web/cps/db.py", line 650, in common_filters
.all())
File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/orm/query.py", line 2773, in all
return self._iter().all()
File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/orm/query.py", line 2916, in _iter
result = self.session.execute(
File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/orm/session.py", line 1714, in execute
result = conn._execute_20(statement, params or {}, execution_options)
File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/base.py", line 1705, in _execute_20
return meth(self, args_10style, kwargs_10style, execution_options)
File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/sql/elements.py", line 334, in _execute_on_connection
return connection._execute_clauseelement(
File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/base.py", line 1572, in _execute_clauseelement
ret = self._execute_context(
File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/base.py", line 1943, in _execute_context
self._handle_dbapi_exception(
File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/base.py", line 2124, in _handle_dbapi_exception
util.raise_(
File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/util/compat.py", line 211, in raise_
raise exception
File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
self.dialect.do_execute(
File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/default.py", line 736, in do_execute
cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked
[SQL: SELECT archived_book.id AS archived_book_id, archived_book.user_id AS archived_book_user_id, archived_book.book_id AS archived_book_book_id, archived_book.is_archived AS archived_book_is_archived, archived_book.last_modified AS archived_book_last_modified
FROM archived_book
WHERE archived_book.user_id = ? AND archived_book.is_archived = 1]
[parameters: (1,)]
(Background on this error at: https://sqlalche.me/e/14/e3q8)

**Environment (please complete the following information):**
 - OS: [e.g. Linux-Synology-Docker]
 - Python version: Python 3.10.6
 - Calibre-Web version:  VERSION=0.6.19-ls195 CALIBREWEB_RELEASE=0.6.19 
 - Docker container: Linux
 - Special Hardware: Synology-NAS 1821+
 - Browser: [Firefox 68.0.1 ESR]

**Additional context**
Add any other context about the problem here. [e.g. access via reverse proxy, database background sync, special database location]

**Comment by OzzieIsaacs** [comment]
Without any more info you are on your own: 
https://github.com/janeczku/calibre-web/issues?q=is%3Aissue+database+is+locked+is%3Aclosed

**Comment by itsOnly1Jah** [comment]
Just encounter the Database Lock issue and managed to fix it.  If your books happen to be mounted on a smb share you have to specify the `--nobrl` flag. It seems the calibre doesn't like the the db file being stored on a share according to [this](https://askubuntu.com/questions/991529/calibre-does-it-possible-to-use-network-samba-share-for-library-storage-folder).  The man for `mount.cifs` has this for the `nobrl` entry:
```
 nobrl  Do  not send byte range lock requests to the server. This is necessary for certain applications that break with cifs style mandatory byte range locks (and most cifs servers do not yet sup‐
              port requesting advisory byte range locks).
```
