### ISSUE TITLE
error login calibre web

### ISSUE THREAD

**Issue by edwindelossantos** [janeczku/calibre-web#2704]
Calibre-Web
500 Internal Server Error
The server encountered an internal error and was unable to complete your request. There is an error in the application.
Traceback (most recent call last):
File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 2073, in wsgi_app
response = self.full_dispatch_request()
File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1518, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1516, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1502, in dispatch_request
return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
File "/app/calibre-web/cps/usermanagement.py", line 35, in decorated_view
return login_required(func)(*args, **kwargs)
File "/usr/local/lib/python3.10/dist-packages/flask_login/utils.py", line 303, in decorated_view
return current_app.ensure_sync(func)(*args, **kwargs)
File "/app/calibre-web/cps/web.py", line 781, in index
return render_books_list("newest", sort_param, 1, page)
File "/app/calibre-web/cps/web.py", line 399, in render_books_list
entries, random, pagination = calibre_db.fill_indexpage(page, 0, db.Books, True, order[0],
File "/app/calibre-web/cps/db.py", line 730, in fill_indexpage
return self.fill_indexpage_with_archived_books(page, database, pagesize, db_filter, order, False,
File "/app/calibre-web/cps/db.py", line 737, in fill_indexpage_with_archived_books
random_query = self.generate_linked_query(config_read_column, database)
File "/app/calibre-web/cps/db.py", line 691, in generate_linked_query
query = (self.session.query(database, ub.ArchivedBook.is_archived, ub.ReadBook.read_status)
AttributeError: 'NoneType' object has no attribute 'query'
Please report this issue with all related information: [Create Issue](https://github.com/janeczku/calibre-web/issues/new?assignees=&labels=&template=bug_report.md&title=)
[Return to Home](http://172.21.10.64:8083/)

**Comment by OzzieIsaacs** [comment]
Without any context I can‘t help you

**Comment by Athanor66** [comment]
I solved the problem by adding the user and the **docker** group to the ACL of the folder containing the metadata.db file.
If you see into the log file, you can find something similar to this:
```
[2023-01-27 17:41:59,734] ERROR {cps.config_sql:357} (sqlite3.OperationalError) _unable to open database: /riviste/metadata.db_
[SQL: attach database '/riviste/metadata.db' as calibre;]
```
Try these commands in a ssh shell:
`getfacl /Volume2/BIBLIOTECHE/RIVISTE/ `  <---- your Calibre folder, where is the metadata.db file
if "docker" isn't present in the ACL, add it with these commands:
```
setfacl -m u:docker:wrx /Volume2/BIBLIOTECHE/RIVISTE/
setfacl -m g:docker:wrx /Volume2/BIBLIOTECHE/RIVISTE/
```

Then restart your calibre-web docker component e voilà, it works!
