### ISSUE TITLE
Error 500: sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) disk I/O error

### ISSUE THREAD

**Issue by chevem** [janeczku/calibre-web#2706]
**Describe the bug/problem**
Showed up 2 days ago after the last reboot of my server (Debian 11 VM). When calibre-web is launched it starts ok but on the server side I have the following messages stacking every few seconds
[xxx.xxxxx] CIFS: VFS: cifs_setlk failed rc=-5

On calibre-web side, the app is fully functionnal for about 1 or 2 minutes and then, whatever I do, I have the 500  error page

Everything seem up to date on the server side, so is calibre-web (no update available reported on admin interface)

**Logfile**
```
Traceback (most recent call last):
File "/home/freebox/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
self.dialect.do_execute(
File "/home/freebox/.local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
cursor.execute(statement, parameters)
sqlite3.OperationalError: disk I/O error
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "/home/freebox/.local/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
response = self.full_dispatch_request()
File "/home/freebox/.local/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/home/freebox/.local/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
rv = self.dispatch_request()
File "/home/freebox/.local/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
File "/home/freebox/calibre-web/cps/usermanagement.py", line 35, in decorated_view
return login_required(func)(*args, **kwargs)
File "/home/freebox/.local/lib/python3.9/site-packages/flask_login/utils.py", line 303, in decorated_view
return current_app.ensure_sync(func)(*args, **kwargs)
File "/home/freebox/calibre-web/cps/web.py", line 790, in books_list
return render_books_list(data, sort_param, book_id, page)
File "/home/freebox/calibre-web/cps/web.py", line 362, in render_books_list
return render_rated_books(page, book_id, order=order)
File "/home/freebox/calibre-web/cps/web.py", line 410, in render_rated_books
entries, random, pagination = calibre_db.fill_indexpage(page, 0,
File "/home/freebox/calibre-web/cps/db.py", line 730, in fill_indexpage
return self.fill_indexpage_with_archived_books(page, database, pagesize, db_filter, order, False,
File "/home/freebox/calibre-web/cps/db.py", line 738, in fill_indexpage_with_archived_books
randm = (random_query.filter(self.common_filters(allow_show_archived))
File "/home/freebox/.local/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 2772, in all
return self._iter().all()
File "/home/freebox/.local/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 2907, in _iter
result = self.session.execute(
File "/home/freebox/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1712, in execute
result = conn._execute_20(statement, params or {}, execution_options)
File "/home/freebox/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1705, in _execute_20
return meth(self, args_10style, kwargs_10style, execution_options)
File "/home/freebox/.local/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 333, in _execute_on_connection
return connection._execute_clauseelement(
File "/home/freebox/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1572, in _execute_clauseelement
ret = self._execute_context(
File "/home/freebox/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1943, in _execute_context
self._handle_dbapi_exception(
File "/home/freebox/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2124, in _handle_dbapi_exception
util.raise_(
File "/home/freebox/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
raise exception
File "/home/freebox/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
self.dialect.do_execute(
File "/home/freebox/.local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) disk I/O error
[SQL: SELECT books.id AS books_id, books.title AS books_title, books.sort AS books_sort, books.author_sort AS books_author_sort, books.timestamp AS books_timestamp, books.pubdate AS books_pubdate, books.series_index AS books_series_index, books.last_modified AS books_last_modified, books.path AS books_path, books.has_cover AS books_has_cover, books.uuid AS books_uuid, books.isbn AS books_isbn, books.flags AS books_flags, archived_book.is_archived AS archived_book_is_archived, book_read_link.read_status AS book_read_link_read_status
FROM books LEFT OUTER JOIN book_read_link ON book_read_link.user_id = ? AND book_read_link.book_id = books.id LEFT OUTER JOIN archived_book ON books.id = archived_book.book_id AND archived_book.user_id = ?
WHERE (books.id NOT IN (SELECT 1 FROM (SELECT 1) WHERE 1!=1)) ORDER BY random()
LIMIT ? OFFSET ?]
[parameters: (1, 1, 4, 0)]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
```

**Environment (please complete the following information):**
 - OS: Debian 11 VM (on Freebox server, french provider)
 - Python version: 3
 - Calibre-Web version: up do date (no update available on admin interface)
 - Docker container: None
 - Special Hardware: 
 - Browser:

**Comment by OzzieIsaacs** [comment]
The "real" error message is: 
`sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) disk I/O error`
Google thinks this could be caused by a not writable metadata.db journal file (maybe folder permissions of the book database).
If possible please try if the metadata.db file is working if you use calibre itself (a library maintenance -> check for errors could also help)

**Comment by chevem** [comment]
That solved the problem.
I tried adding a new book in the calibre library (in calibre app) to force and update of the metadata.db. Since then I have no more error or the server nor on calibre-web.
Thanks a lot and sorry for the wrong interpretation of the error message.
