### ISSUE TITLE
Cannot Convert EPUB to PDF: AttributeError: 'QWebEngineProfile'...

### ISSUE THREAD

**Issue by brandoningli** [janeczku/calibre-web#2747]
**Describe the bug/problem**
When attempting to convert an EPUB to PDF, I get the following error and the task fails

```
Calibre failed with error: AttributeError: 'QWebEngineProfile' object has no attribute 'setUrlRequestInterceptor'
```

This book reads fine with the in-browser EPUB reader.

**To Reproduce**
1. Go to an EPUB
2. Edit metadata
3. Convert From `EPUB` to `PDF`
4. In the tasks list, see that it fails.
5. In the debug log, see the reason.

**Logfile**
```
[2023-04-11 20:21:22,696]  INFO {cps.editbooks:322} converting: book id: 605 from: EPUB to: PDF
[2023-04-11 20:21:22,698] DEBUG {cps.services.worker:91} Add Task for user: brandon - Convert 605
[2023-04-11 20:21:22,699]  INFO {cps.tasks.convert:142} Book id 605 - target format of .pdf does not exist. Moving forward with convert.
[2023-04-11 20:21:22,858] DEBUG {cps.tasks.convert:254} 1% Converting input to HTML...
[2023-04-11 20:21:22,975] DEBUG {cps.tasks.convert:254} InputFormatPlugin: EPUB Input running
[2023-04-11 20:21:22,975] DEBUG {cps.tasks.convert:254} on /home/calibre/eBooks/Steve Jobs/Make Something Wonderful (605)/Make Something Wonderful - Steve Jobs.epub
[2023-04-11 20:21:23,393] DEBUG {cps.tasks.convert:254} Parsing all content...
[2023-04-11 20:21:23,599] DEBUG {cps.tasks.convert:254} 34% Running transforms on e-book...
[2023-04-11 20:21:23,635] DEBUG {cps.tasks.convert:254} Merging user specified metadata...
[2023-04-11 20:21:23,635] DEBUG {cps.tasks.convert:254} Detecting structure...
[2023-04-11 20:21:23,642] DEBUG {cps.tasks.convert:254}  Detected chapter: Part I, 1976–1985
[2023-04-11 20:21:23,642] DEBUG {cps.tasks.convert:254}  Detected chapter: Part II, 1985–1996
[2023-04-11 20:21:23,642] DEBUG {cps.tasks.convert:254}  Detected chapter: Part III, 1996–2011
[2023-04-11 20:21:23,647] DEBUG {cps.tasks.convert:254} Flattening CSS and remapping font sizes...
[2023-04-11 20:21:24,404] DEBUG {cps.tasks.convert:254} Source base font size is 12.00000pt
[2023-04-11 20:21:24,760] DEBUG {cps.tasks.convert:254} Removing fake margins...
[2023-04-11 20:21:24,839] DEBUG {cps.tasks.convert:254} Cleaning up manifest...
[2023-04-11 20:21:24,839] DEBUG {cps.tasks.convert:254} Trimming unused files from manifest...
[2023-04-11 20:21:24,852] DEBUG {cps.tasks.convert:254} Trimming 'OPS/chapter-12-photo03-text.xhtml' from manifest
[2023-04-11 20:21:24,852] DEBUG {cps.tasks.convert:254} Trimming 'OPS/chapter-55-photo05-text.xhtml' from manifest
[2023-04-11 20:21:24,852] DEBUG {cps.tasks.convert:254} Trimming 'OPS/epb.ncx' from manifest
[2023-04-11 20:21:24,853] DEBUG {cps.tasks.convert:254} Creating PDF Output...
[2023-04-11 20:21:24,853] DEBUG {cps.tasks.convert:254} 67% Running PDF Output plugin
[2023-04-11 20:21:24,901] DEBUG {cps.tasks.convert:254} The cover image has an id != "cover". Renaming to work around bug in Nook Color
[2023-04-11 20:21:25,063] DEBUG {cps.tasks.convert:254} 68% Parsed all content for markup transformation
[2023-04-11 20:21:25,380] DEBUG {cps.tasks.convert:254} 70% Completed markup transformation
[2023-04-11 20:21:25,602] DEBUG {cps.tasks.convert:268} QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-calibre'
[2023-04-11 20:21:25,603] DEBUG {cps.tasks.convert:268} WebEngineContext used before QtWebEngine::initialize() or OpenGL context creation failed.
[2023-04-11 20:21:25,603] DEBUG {cps.tasks.convert:268} Traceback (most recent call last):
[2023-04-11 20:21:25,603] DEBUG {cps.tasks.convert:268}   File "/usr/bin/ebook-convert", line 20, in <module>
[2023-04-11 20:21:25,603] DEBUG {cps.tasks.convert:268}     sys.exit(main())
[2023-04-11 20:21:25,603] DEBUG {cps.tasks.convert:268}   File "/usr/lib/calibre/calibre/ebooks/conversion/cli.py", line 401, in main
[2023-04-11 20:21:25,603] DEBUG {cps.tasks.convert:268}     plumber.run()
[2023-04-11 20:21:25,603] DEBUG {cps.tasks.convert:268}   File "/usr/lib/calibre/calibre/ebooks/conversion/plumber.py", line 1274, in run
[2023-04-11 20:21:25,603] DEBUG {cps.tasks.convert:268}     self.output_plugin.convert(self.oeb, self.output, self.input_plugin,
[2023-04-11 20:21:25,603] DEBUG {cps.tasks.convert:268}   File "/usr/lib/calibre/calibre/ebooks/conversion/plugins/pdf_output.py", line 188, in convert
[2023-04-11 20:21:25,603] DEBUG {cps.tasks.convert:268}     self.convert_text(oeb_book)
[2023-04-11 20:21:25,603] DEBUG {cps.tasks.convert:268}   File "/usr/lib/calibre/calibre/ebooks/conversion/plugins/pdf_output.py", line 253, in convert_text
[2023-04-11 20:21:25,603] DEBUG {cps.tasks.convert:268}     convert(
[2023-04-11 20:21:25,603] DEBUG {cps.tasks.convert:268}   File "/usr/lib/calibre/calibre/ebooks/pdf/html_writer.py", line 1195, in convert
[2023-04-11 20:21:25,603] DEBUG {cps.tasks.convert:268}     manager = RenderManager(opts, log, container.root)
[2023-04-11 20:21:25,603] DEBUG {cps.tasks.convert:268}   File "/usr/lib/calibre/calibre/ebooks/pdf/html_writer.py", line 279, in __init__
[2023-04-11 20:21:25,603] DEBUG {cps.tasks.convert:268}     ans.setUrlRequestInterceptor(self.interceptor)
[2023-04-11 20:21:25,603] DEBUG {cps.tasks.convert:268} AttributeError: 'QWebEngineProfile' object has no attribute 'setUrlRequestInterceptor'
[2023-04-11 20:21:25,603]  INFO {cps.tasks.convert:188} ebook converter failed with error while converting book
[2023-04-11 20:21:25,603] ERROR {cps.tasks.convert:192} Calibre failed with error: AttributeError: 'QWebEngineProfile' object has no attribute 'setUrlRequestInterceptor'
```

**Expected behavior**
The EPUB should be converted to a PDF.

**Environment (please complete the following information):**
 - OS: Ubuntu Server 20.04 LTS
 - Python version: python 3.8.10
 - Calibre-Web version: 13c0d30a (also on v0.6.20 stable)
 - Docker container: None
 - Special Hardware: VMWare Virtual Machine
 - Browser: Firefox 112.0 on MacOS
 - Calibre installed via the Ubuntu standard repos
 
![image](https://user-images.githubusercontent.com/6826623/231323491-6c8b1440-5827-4a20-8ac3-1c82edc7d733.png)

**Comment by brandoningli** [comment]
Finally got around to manually installing the latest Calibre binary from their website, and that did the trick.
