### ISSUE TITLE
AttributeError: type object 'Books' has no attribute 'custom_column_6'

### ISSUE THREAD

**Issue by kimcdow** [janeczku/calibre-web#2760]
**Describe the bug/problem**
Receive the following error when trying to perform a search.
AttributeError: type object 'Books' has no attribute 'custom_column_6'

**To Reproduce**
open calibre web perform a search using the search bar.

https://calibre.FQDN/search/stored/?query=butterfly

**Logfile**
Calibre-Web
500 Internal Server Error
The server encountered an internal error and was unable to complete your request. There is an error in the application.
Traceback (most recent call last):
File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 2073, in wsgi_app
response = self.full_dispatch_request()
File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1518, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1516, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1502, in dispatch_request
return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
File "/app/calibre-web/cps/usermanagement.py", line 35, in decorated_view
return login_required(func)(*args, **kwargs)
File "/usr/local/lib/python3.10/dist-packages/flask_login/utils.py", line 303, in decorated_view
return current_app.ensure_sync(func)(*args, **kwargs)
File "/app/calibre-web/cps/web.py", line 790, in books_list
return render_books_list(data, sort_param, book_id, page)
File "/app/calibre-web/cps/web.py", line 392, in render_books_list
return render_search_results(term, offset, order, config.config_books_per_page)
File "/app/calibre-web/cps/search.py", line 379, in render_search_results
entries, result_count, pagination = calibre_db.get_search_results(term,
File "/app/calibre-web/cps/db.py", line 886, in get_search_results
result = self.search_query(term, config, *join).order_by(*order).all()
File "/app/calibre-web/cps/db.py", line 861, in search_query
getattr(Books,
AttributeError: type object 'Books' has no attribute 'custom_column_6'
Please report this issue with all related information: [Create Issue](https://github.com/janeczku/calibre-web/issues/new?assignees=&labels=&template=bug_report.md&title=)

**Expected behavior**
A search is performed returning books matching search criteria.

**Screenshots**

**Additional context**
Calibre 6.13
![image](https://user-images.githubusercontent.com/20283750/233383741-aba10f67-af56-4d57-beb6-8038c6d4a827.png)
![image](https://user-images.githubusercontent.com/20283750/233383900-1cc4c7d4-4ad0-465d-bfee-f3d2c71739e4.png)

**Comment by OzzieIsaacs** [comment]
No response
