### ISSUE TITLE
500 internal server error

### ISSUE THREAD

**Issue by GHMCr** [janeczku/calibre-web#2800]
App (deployed in k8s cluster) was working fine until this morning. From then:

500 Internal Server Error
The server encountered an internal error and was unable to complete your request. There is an error in the application.
```
Traceback (most recent call last):
File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 2073, in wsgi_app
response = self.full_dispatch_request()
File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1519, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1517, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1503, in dispatch_request
return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
File "/app/calibre-web/cps/usermanagement.py", line 34, in decorated_view
return func(*args, **kwargs)
File "/app/calibre-web/cps/web.py", line 790, in index
return render_books_list("newest", sort_param, 1, page)
File "/app/calibre-web/cps/web.py", line 408, in render_books_list
entries, random, pagination = calibre_db.fill_indexpage(page, 0, db.Books, True, order[0],
File "/app/calibre-web/cps/db.py", line 782, in fill_indexpage
return self.fill_indexpage_with_archived_books(page, database, pagesize, db_filter, order, False,
File "/app/calibre-web/cps/db.py", line 789, in fill_indexpage_with_archived_books
random_query = self.generate_linked_query(config_read_column, database)
File "/app/calibre-web/cps/db.py", line 743, in generate_linked_query
query = (self.session.query(database, ub.ArchivedBook.is_archived, ub.ReadBook.read_status)
AttributeError: 'NoneType' object has no attribute 'query'
```

**Comment by XXBrain** [comment]
I have the same issue. Created a new docker container and used fresh metadata.db from library folder. After defing the db location I loaded admin page succesfully, but on first request the error occurs.

**Comment by OzzieIsaacs** [comment]
@XXBrain I experienced the same issue, depending on how you download the included metadata.db file, it‘s corrupted. If you download all files as zip, it should work

**Comment by boosh** [comment]
Yeah the link in the README should be to the [raw file](https://github.com/janeczku/calibre-web/raw/master/library/metadata.db), not the web link.

**Comment by OzzieIsaacs** [comment]
The link in readme ist changed. Thanks
