### ISSUE TITLE
Error on refreshing saved search

### ISSUE THREAD

**Issue by slash5toaster** [janeczku/calibre-web#2802]
**Describe the bug/problem**
Calibre-Web
500 Internal Server Error
```
The server encountered an internal error and was unable to complete your request. There is an error in the application.
Traceback (most recent call last):
File "/usr/local/calibre-web/.venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
response = self.full_dispatch_request()
File "/usr/local/calibre-web/.venv/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/local/calibre-web/.venv/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/local/calibre-web/.venv/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
File "/usr/local/calibre-web/.venv/lib/python3.9/site-packages/calibreweb/cps/usermanagement.py", line 34, in decorated_view
return func(*args, **kwargs)
File "/usr/local/calibre-web/.venv/lib/python3.9/site-packages/calibreweb/cps/web.py", line 799, in books_list
return render_books_list(data, sort_param, book_id, page)
File "/usr/local/calibre-web/.venv/lib/python3.9/site-packages/calibreweb/cps/web.py", line 399, in render_books_list
term = json.loads(flask_session.get('query', ''))
File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
return _default_decoder.decode(s)
File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
obj, end = self.raw_decode(s, idx=_w(s, 0).end())
File "/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0).
```

**To Reproduce**
1. Go to search for term, close window
2. Reopen window with http://<server>/search/stored/?query=
3. See error

**Logfile**
'''
2023-05-31 13:58:30,476] ERROR {cps:1457} Exception on /search/stored/ [GET]
```
Traceback (most recent call last):
  File "/usr/local/calibre-web/.venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/calibre-web/.venv/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/calibre-web/.venv/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/calibre-web/.venv/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/local/calibre-web/.venv/lib/python3.9/site-packages/calibreweb/cps/usermanagement.py", line 34, in decorated_view
    return func(*args, **kwargs)
  File "/usr/local/calibre-web/.venv/lib/python3.9/site-packages/calibreweb/cps/web.py", line 799, in books_list
    return render_books_list(data, sort_param, book_id, page)
  File "/usr/local/calibre-web/.venv/lib/python3.9/site-packages/calibreweb/cps/web.py", line 399, in render_books_list
    term = json.loads(flask_session.get('query', ''))
  File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
'''
```
**Expected behavior**
Return to home page

**Screenshots**

**Environment (please complete the following information):**
 - OS: Debian GNU/Linux 11  6.1.21-v8+ #1642 SMP PREEMPT Mon Apr  3 17:24:16 BST 2023 aarch64 GNU/Linux
 - Python version: [Python 3.9.2]
 - Calibre-Web version: pip list | grep cali
calibreweb 0.6.20
 - Docker container: [None]:
 - Special Hardware: [Rasperry Pi 4b]
 - Browser: [any]

**Additional context**
Add any other context about the problem here. [e.g. access via reverse proxy, database background sync, special database location]

**Comment by OzzieIsaacs** [comment]
Please update to the newest nightly, it's no longer crashing there. 
But the results are stored in a the browser session, so closing the browser should give no results afterwards (what it currently doesn't do, it gives you all books as result)

**Comment by OzzieIsaacs** [comment]
Please check newest nightly version
