### ISSUE TITLE
Invalid cover file content

### ISSUE THREAD

**Issue by cyberb** [janeczku/calibre-web#2810]
Some books like epub are extracting the cover ok, but pdf book uploads are not able to extract the cover.
I get this error when:
1. upload cover jpg/png file
2. Url with jpg file
3. Fetching the book metadata, shows cover but still could not save.

I get this error in the log but no real root cause, looking at the code there is no log for the exception itself.

https://github.com/janeczku/calibre-web/blob/master/cps/helper.py#L918

Is it possible to add exception logging or you know the answer right away (still error could be more specific about the problem I need to fix)?

**Comment by OzzieIsaacs** [comment]
For me it‘s working. Could you please send me one of the problematic files (private email, the address from my profile page) and I have a look at it?

**Comment by OzzieIsaacs** [comment]
If you change the code to:
```
        except (BlobError, MissingDelegateError) as e:
            log.exception("Invalid cover file content:  %s", e)
```
You should see more output

**Comment by cyberb** [comment]
NoDecodeDelegateForThisImageFormat
Does this mean I have image magic issues?

```
Jun 11 15:57:09 syncloud calibre.web[14021]: --- Logging error ---
Jun 11 15:57:09 syncloud calibre.web[14021]: Traceback (most recent call last):
Jun 11 15:57:09 syncloud calibre.web[14021]:   File "/snap/calibre/75/calibre/web/cps/helper.py", line 912, in save_cover
Jun 11 15:57:09 syncloud calibre.web[14021]:     imgc = Image(blob=io.BytesIO(img.content))
Jun 11 15:57:09 syncloud calibre.web[14021]:   File "/snap/calibre/75/calibre/usr/local/lib/python3.8/site-packages/wand/image.py", line 9363, in __init__
Jun 11 15:57:09 syncloud calibre.web[14021]:     self.read(blob=blob)
Jun 11 15:57:09 syncloud calibre.web[14021]:   File "/snap/calibre/75/calibre/usr/local/lib/python3.8/site-packages/wand/image.py", line 10120, in read
Jun 11 15:57:09 syncloud calibre.web[14021]:     self.raise_exception()
Jun 11 15:57:09 syncloud calibre.web[14021]:   File "/snap/calibre/75/calibre/usr/local/lib/python3.8/site-packages/wand/resource.py", line 225, in raise_exception
Jun 11 15:57:09 syncloud calibre.web[14021]:     raise e
Jun 11 15:57:09 syncloud calibre.web[14021]: wand.exceptions.MissingDelegateError: NoDecodeDelegateForThisImageFormat `JPEG' @ error/blob.c/BlobToImage/361
Jun 11 15:57:09 syncloud calibre.web[14021]: During handling of the above exception, another exception occurred:
Jun 11 15:57:09 syncloud calibre.web[14021]: Traceback (most recent call last):
Jun 11 15:57:09 syncloud calibre.web[14021]:   File "/snap/calibre/75/calibre/usr/local/lib/python3.8/logging/__init__.py", line 1085, in emit
Jun 11 15:57:09 syncloud calibre.web[14021]:     msg = self.format(record)
Jun 11 15:57:09 syncloud calibre.web[14021]:   File "/snap/calibre/75/calibre/usr/local/lib/python3.8/logging/__init__.py", line 929, in format
Jun 11 15:57:09 syncloud calibre.web[14021]:     return fmt.format(record)
Jun 11 15:57:09 syncloud calibre.web[14021]:   File "/snap/calibre/75/calibre/usr/local/lib/python3.8/logging/__init__.py", line 668, in format
Jun 11 15:57:09 syncloud calibre.web[14021]:     record.message = record.getMessage()
Jun 11 15:57:09 syncloud calibre.web[14021]:   File "/snap/calibre/75/calibre/usr/local/lib/python3.8/logging/__init__.py", line 373, in getMessage
Jun 11 15:57:09 syncloud calibre.web[14021]:     msg = msg % self.args
Jun 11 15:57:09 syncloud calibre.web[14021]: TypeError: not all arguments converted during string formatting
Jun 11 15:57:09 syncloud calibre.web[14021]: Call stack:
Jun 11 15:57:09 syncloud calibre.web[14021]:   File "/snap/calibre/75/calibre/usr/local/lib/python3.8/site-packages/gevent/baseserver.py", line 34, in _handle_and_close_when_done
Jun 11 15:57:09 syncloud calibre.web[14021]:     return handle(*args_tuple)
Jun 11 15:57:09 syncloud calibre.web[14021]:   File "/snap/calibre/75/calibre/usr/local/lib/python3.8/site-packages/gevent/pywsgi.py", line 1577, in handle
Jun 11 15:57:09 syncloud calibre.web[14021]:     handler.handle()
Jun 11 15:57:09 syncloud calibre.web[14021]:   File "/snap/calibre/75/calibre/usr/local/lib/python3.8/site-packages/gevent/pywsgi.py", line 464, in handle
Jun 11 15:57:09 syncloud calibre.web[14021]:     result = self.handle_one_request()
Jun 11 15:57:09 syncloud calibre.web[14021]:   File "/snap/calibre/75/calibre/usr/local/lib/python3.8/site-packages/gevent/pywsgi.py", line 694, in handle_one_request
Jun 11 15:57:09 syncloud calibre.web[14021]:     self.handle_one_response()
Jun 11 15:57:09 syncloud calibre.web[14021]:   File "/snap/calibre/75/calibre/usr/local/lib/python3.8/site-packages/gevent/pywsgi.py", line 999, in handle_one_response
Jun 11 15:57:09 syncloud calibre.web[14021]:     self.run_application()
Jun 11 15:57:09 syncloud calibre.web[14021]:   File "/snap/calibre/75/calibre/usr/local/lib/python3.8/site-packages/gevent/pywsgi.py", line 945, in run_application
Jun 11 15:57:09 syncloud calibre.web[14021]:     self.result = self.application(self.environ, self.start_response)
Jun 11 15:57:09 syncloud calibre.web[14021]:   File "/snap/calibre/75/calibre/usr/local/lib/python3.8/site-packages/flask/app.py", line 2091, in __call__Jun 11 15:57:09 syncloud calibre.web[14021]:     return self.wsgi_app(environ, start_response)
Jun 11 15:57:09 syncloud calibre.web[14021]:   File "/snap/calibre/75/calibre/web/cps/reverseproxy.py", line 79, in __call__
Jun 11 15:57:09 syncloud calibre.web[14021]:     return self.app(environ, start_response)
Jun 11 15:57:09 syncloud calibre.web[14021]:   File "/snap/calibre/75/calibre/usr/local/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_appJun 11 15:57:09 syncloud calibre.web[14021]:     response = self.full_dispatch_request()
Jun 11 15:57:09 syncloud calibre.web[14021]:   File "/snap/calibre/75/calibre/usr/local/lib/python3.8/site-packages/flask/app.py", line 1517, in full_dispatch_request
Jun 11 15:57:09 syncloud calibre.web[14021]:     rv = self.dispatch_request()
Jun 11 15:57:09 syncloud calibre.web[14021]:   File "/snap/calibre/75/calibre/usr/local/lib/python3.8/site-packages/flask/app.py", line 1503, in dispatch_request
Jun 11 15:57:09 syncloud calibre.web[14021]:     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
Jun 11 15:57:09 syncloud calibre.web[14021]:   File "/snap/calibre/75/calibre/web/cps/usermanagement.py", line 35, in decorated_view
Jun 11 15:57:09 syncloud calibre.web[14021]:     return login_required(func)(*args, **kwargs)
Jun 11 15:57:09 syncloud calibre.web[14021]:   File "/snap/calibre/75/calibre/usr/local/lib/python3.8/site-packages/flask_login/utils.py", line 290, in decorated_view
Jun 11 15:57:09 syncloud calibre.web[14021]:     return current_app.ensure_sync(func)(*args, **kwargs)Jun 11 15:57:09 syncloud calibre.web[14021]:   File "/snap/calibre/75/calibre/web/cps/editbooks.py", line 71, in inner
Jun 11 15:57:09 syncloud calibre.web[14021]:     return f(*args, **kwargs)
Jun 11 15:57:09 syncloud calibre.web[14021]:   File "/snap/calibre/75/calibre/web/cps/editbooks.py", line 158, in edit_book
Jun 11 15:57:09 syncloud calibre.web[14021]:     result, error = helper.save_cover_from_url(to_save["cover_url"].strip(), book.path)
Jun 11 15:57:09 syncloud calibre.web[14021]:   File "/snap/calibre/75/calibre/web/cps/helper.py", line 855, in save_cover_from_url
Jun 11 15:57:09 syncloud calibre.web[14021]:     return save_cover(img, book_path)
Jun 11 15:57:09 syncloud calibre.web[14021]:   File "/snap/calibre/75/calibre/web/cps/helper.py", line 917, in save_cover
Jun 11 15:57:09 syncloud calibre.web[14021]:     log.exception("Invalid cover file content", e)
```

**Comment by OzzieIsaacs** [comment]
Yes, this seems to be a imagemagick error, if it happens to all your files. You could try this file (https://github.com/OzzieIsaacs/calibre-web-test/blob/main/test/files/book.epub) this is definitiv working, to be sure pleaee download the zip file from this repro.

**Comment by cyberb** [comment]
sorry, the usual problem (was wrong)
```
export MAGICK_CODER_MODULE_PATH=$(echo ${DIR}/usr/lib/*-linux*/ImageMagick-*/modules-*)/coders
```
