### ISSUE TITLE
Fetching metadata from lubimyczytac provider fails

### ISSUE THREAD

**Issue by divinitus** [janeczku/calibre-web#2822]
**Describe the bug/problem**
A clear and concise description of what the bug is. If you are asking for support, please check our [Wiki](https://github.com/janeczku/calibre-web/wiki) if your question is already answered there.

**To Reproduce**
1. Go to '/book/xxxx'
2. Click on ''Edit Metadata"
3. Click on "Fetch Metadata"
4. Wait for the search to result in "Search error!!"
5. See error in calibre-web.log

**Logfile**
[2023-07-03 22:11:10,534] ERROR {cps.db:848} Author  not found to display name in right order
[2023-07-03 22:12:03,659] ERROR {cps:1449} Exception on /metadata/search [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/local/lib/python3.10/dist-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/app/calibre-web/cps/search_metadata.py", line 141, in metadata_search
    data.extend([asdict(x) for x in future.result() if x])
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/app/calibre-web/cps/metadata_provider/lubimyczytac.py", line 129, in search
    final_matches = pool.starmap(
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 375, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 774, in get
    raise self._value
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/app/calibre-web/cps/metadata_provider/lubimyczytac.py", line 225, in parse_single_book
    match.tags = self._parse_tags()
  File "/app/calibre-web/cps/metadata_provider/lubimyczytac.py", line 285, in _parse_tags
    return [
TypeError: 'NoneType' object is not iterable

**Expected behavior**
Metadata being retrived

**Environment (please complete the following information):**
 - OS: Linux
 - Python version: 3.10
 - Calibre-Web version: 0.6.20
 - Docker container: [LinuxServer]: 
 - Special Hardware: [none]
 - Browser: [Firefox 114.0.2]

**Additional context**
Add any other context about the problem here. [e.g. access via reverse proxy, database background sync, special database location]

**Comment by kaibagley** [comment]
I'm getting a similar, probably the same, issue. Can't fetch the metadata, but when looking at the docker logs for the container, I get permission errors for updating the calibre-web.log file.
