### ISSUE TITLE
Calibre-Web 500 Internal Server Error

### ISSUE THREAD

**Issue by itchygrub** [janeczku/calibre-web#2825]
Calibre-Web 500 Internal Server Error

The server encountered an internal error and was unable to complete your request. There is an error in the application.
Traceback (most recent call last):
File "/opt/calibre-web/venv/lib/python3.10/site-packages/flask/app.py", line 2073, in wsgi_app
response = self.full_dispatch_request()
File "/opt/calibre-web/venv/lib/python3.10/site-packages/flask/app.py", line 1519, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/opt/calibre-web/venv/lib/python3.10/site-packages/flask/app.py", line 1517, in full_dispatch_request
rv = self.dispatch_request()
File "/opt/calibre-web/venv/lib/python3.10/site-packages/flask/app.py", line 1503, in dispatch_request
return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
File "/opt/calibre-web/venv/lib/python3.10/site-packages/calibreweb/cps/usermanagement.py", line 35, in decorated_view
return login_required(func)(*args, **kwargs)
File "/opt/calibre-web/venv/lib/python3.10/site-packages/flask_login/utils.py", line 290, in decorated_view
return current_app.ensure_sync(func)(*args, **kwargs)
File "/opt/calibre-web/venv/lib/python3.10/site-packages/calibreweb/cps/web.py", line 790, in index
return render_books_list("newest", sort_param, 1, page)
File "/opt/calibre-web/venv/lib/python3.10/site-packages/calibreweb/cps/web.py", line 408, in render_books_list
entries, random, pagination = calibre_db.fill_indexpage(page, 0, db.Books, True, order[0],
File "/opt/calibre-web/venv/lib/python3.10/site-packages/calibreweb/cps/db.py", line 782, in fill_indexpage
return self.fill_indexpage_with_archived_books(page, database, pagesize, db_filter, order, False,
File "/opt/calibre-web/venv/lib/python3.10/site-packages/calibreweb/cps/db.py", line 789, in fill_indexpage_with_archived_books
random_query = self.generate_linked_query(config_read_column, database)
File "/opt/calibre-web/venv/lib/python3.10/site-packages/calibreweb/cps/db.py", line 743, in generate_linked_query
query = (self.session.query(database, ub.ArchivedBook.is_archived, ub.ReadBook.read_status)
AttributeError: 'NoneType' object has no attribute 'query'
Please report this issue with all related information: [Create Issue](https://github.com/janeczku/calibre-web/issues/new/choose=)
[Return to Home](http://192.168.1.141:8083/)

[calibre-web.log](https://github.com/janeczku/calibre-web/files/11964541/calibre-web.log)

New Build
proxmox - VM - Ubuntu 22.04.2 Live server.
Pyhton 3.10
Brave v1.52.129
Calibre 0.6.20

Start cps &
192.168.1.141:8083
login
Connect Library database - cifs connection
save 
click ok admin get error 
or get past this create user
get error.
Sometimes - stop process delete the app.db
restart process
login 
create library site.
Does the same in Chrome

**Comment by itchygrub** [comment]
Not sure what the problem was but there where a couple of metadata.db and metadata_db_prefs_backup.json files in directory, deleted the others and it seems to have corrected the above.
