### ISSUE TITLE
Errors in calibre after uploading a book through calibre-web

### ISSUE THREAD

**Issue by kaibagley** [janeczku/calibre-web#2829]
**Describe the bug/problem**
After uploading a book to calibre-web, and then fetching metadata. Stopping and restarting the calibre Docker containers causes calibre to continuously throw errors.

**To Reproduce**
1. Upload epub
2. fetch and change metadata
3. docker compose down
4. docker compose up -d

**Logfile**
calibre                        | Failed to write backup metadata for id: 37 once
calibre                        | Traceback (most recent call last):
calibre                        |   File "calibre/db/backend.py", line 1971, in write_backup
calibre                        |   File "os.py", line 225, in makedirs
calibre                        | FileExistsError: [Errno 17] File exists: '/Calibre_Library/Ruth Goodman/How To Be a Victorian (37)'
calibre                        | 
calibre                        | During handling of the above exception, another exception occurred:
calibre                        | 
calibre                        | Traceback (most recent call last):
calibre                        |   File "calibre/db/backup.py", line 117, in do_one
calibre                        |   File "calibre/db/cache.py", line 85, in call_func_with_lock
calibre                        |   File "calibre/db/cache.py", line 1579, in write_backup
calibre                        |   File "calibre/db/backend.py", line 1975, in write_backup
calibre                        |   File "polyglot/builtins.py", line 61, in reraise
calibre                        |   File "calibre/db/backend.py", line 1966, in write_backup
calibre                        | PermissionError: [Errno 13] Permission denied: '/Calibre_Library/Ruth Goodman/How To Be a Victorian (37)/metadata.opf'

**Expected behavior**
No errors being thrown in the logs

**Environment (please complete the following information):**
 - OS: Ubuntu 22.04
 - Python version: 3.10.6
 - Calibre-Web version: linuxserver/calibre-web:latest
 - Docker container: linuxserver

**Additional context**
Uploaded another file earlier but didn't fetch metadata right after. Didn't notice any issues with this

**Comment by kaibagley** [comment]
Oops, my bad. For some reason the book's owner was root? Not sure how I managed that
