### ISSUE TITLE
500 Internal Server Error / kobo "sync failed"

### ISSUE THREAD

**Issue by blogbourri** [janeczku/calibre-web#2834]
**Describe the bug/problem**
When I go to /kobo/[sync token]/v1/library/sync, I get a 500 internal server problem, and sync attempts on my kobo device give "sync failed" errors. I was using kobo sync without issue previously. A recent update to the linuxserver.io docker image seems to have triggered this error, but I don't understand the error messages well enough to know if it's more likely to be an issue with their image or calibre-web itself. A fresh reinstall has the same issue.

**To Reproduce**
1. Go to /kobo/[sync token]/v1/library/sync
2. "The server encountered an internal error and was unable to complete your request. There is an error in the application."

**Logfile**
```
Traceback (most recent call last):
File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 2073, in wsgi_app
response = self.full_dispatch_request()
File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1519, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1517, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1503, in dispatch_request
return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
File "/app/calibre-web/cps/kobo_auth.py", line 168, in inner
return f(*args, **kwargs)
File "/app/calibre-web/cps/web.py", line 122, in inner
return f(*args, **kwargs)
File "/app/calibre-web/cps/kobo.py", line 224, in HandleSyncRequest
"BookMetadata": get_metadata(book.Books),
File "/app/calibre-web/cps/kobo.py", line 465, in get_metadata
if get_epub_layout(book, book_data) == 'pre-paginated':
File "/app/calibre-web/cps/epub.py", line 57, in get_epub_layout
tree = etree.fromstring(cf)
File "src/lxml/etree.pyx", line 3257, in lxml.etree.fromstring
File "src/lxml/parser.pxi", line 1916, in lxml.etree._parseMemoryDocument
File "src/lxml/parser.pxi", line 1803, in lxml.etree._parseDoc
File "src/lxml/parser.pxi", line 1144, in lxml.etree._BaseParser._parseDoc
File "src/lxml/parser.pxi", line 618, in lxml.etree._ParserContext._handleParseResultDoc
File "src/lxml/parser.pxi", line 728, in lxml.etree._handleParseResult
File "src/lxml/parser.pxi", line 657, in lxml.etree._raiseParseError
File "<string>", line 4
lxml.etree.XMLSyntaxError: Namespace prefix dc on title is not defined, line 4, column 14
```

**Expected behavior**
Kobo should sync with calibre-web

**Screenshots**

**Environment (please complete the following information):**
 - OS: synology nas/docker
 - Python version: not sure how to check
 - Calibre-Web version: 0.6.20
 - Docker container: linuxserver
 - Special Hardware: synology nas
 - Browser: n/a

**Additional context**
have tested using both local ip and public subdomain. am fairly new to self-hosting, could be a configuration issue, but I did have this working without issue previously.

**Comment by zombiehoffa** [comment]
I am getting this error as well. I am running the linuxserver docker

**Comment by OzzieIsaacs** [comment]
Same problem as in  #2840. Please update to the newest nightly version, it should work then

**Comment by blogbourri** [comment]
Running the latest nightly from linuxserver does not resolve the problem; am also unclear if the issue is actually a duplicate, the error messages seem different? But I could be mistaken there.

**Comment by blogbourri** [comment]
Might be that linuxserver's image is still running behind the latest nightly? Reading the suggestion that it was caused by unparseable epubs got me thinking. I double checked what epubs I had added before the issues began, and they were all generated by go-shiori's new export to epub. I removed those epubs from my calibre library, and now kobo sync is able to complete.

**Comment by OzzieIsaacs** [comment]
The error message in #2840 is: 
`lxml.etree.XMLSyntaxError: []`
The error message here is:
`lxml.etree.XMLSyntaxError: []`

So the error message is the same and the error is catched in the newest nightly version. The reason is that the epub file is invalid, so the sync should work. 
It's possible that the epubs aren't working on your kobo reader afterwards, but then this is not the fault of calibre-web anymore
