### ISSUE TITLE
Cannot sync books to Kobo due to exception

### ISSUE THREAD

**Issue by timotheeandres** [janeczku/calibre-web#2840]
**Describe the bug/problem**
I added a few very large books to my Calibre-web library, and since around that time I cannot sync my Kobo anymore. I am not sure if it is related, but it happened pretty much at the same time.
Although, I tried to sync only some of the books, but the error still happens.

**To Reproduce**
1. Connect Kobo (Nia) to calibre-web
2. Click "Syncronize"
3. Kobo gets a synchronization error
4. Logs show a python exception

**Logfile**
```
[2023-07-22 09:36:48,398] DEBUG {cps.updater:329} Stable version: {'version': '0.6.20'}
[2023-07-22 09:37:39,242] DEBUG {cps.babel:26} Could not parse locale "*": expected only letters, got '*'
[2023-07-22 09:37:39,336] DEBUG {cps.kobo:987} Unimplemented User Request received: http://<domain>/kobo/ebb06dba3d1c577f21bd00491d85bf9b/v1/user/profile (request is forwarded to kobo if configured)
[2023-07-22 09:37:40,124] DEBUG {cps.kobo:1027} Unimplemented Products Request received: http://<domain>/kobo/ebb06dba3d1c577f21bd00491d85bf9b/v1/deals (request is forwarded to kobo if configured)
[2023-07-22 09:38:02,239] DEBUG {cps.ub:84} Found stored session: 6f0cabdef656e4cbaa36e5052620c710eec92ac9a7ace0553af112da801630d7cd85f941312eed12bccb757c3f772b5f578268c44602967a27cdf138d19cda70
[2023-07-22 09:38:02,322] DEBUG {cps.ub:84} Found stored session: 6f0cabdef656e4cbaa36e5052620c710eec92ac9a7ace0553af112da801630d7cd85f941312eed12bccb757c3f772b5f578268c44602967a27cdf138d19cda70
[2023-07-22 09:38:02,385] DEBUG {cps.ub:84} Found stored session: 6f0cabdef656e4cbaa36e5052620c710eec92ac9a7ace0553af112da801630d7cd85f941312eed12bccb757c3f772b5f578268c44602967a27cdf138d19cda70
[2023-07-22 09:38:02,461] DEBUG {cps.ub:84} Found stored session: 6f0cabdef656e4cbaa36e5052620c710eec92ac9a7ace0553af112da801630d7cd85f941312eed12bccb757c3f772b5f578268c44602967a27cdf138d19cda70
[2023-07-22 09:38:02,542] DEBUG {cps.ub:84} Found stored session: 6f0cabdef656e4cbaa36e5052620c710eec92ac9a7ace0553af112da801630d7cd85f941312eed12bccb757c3f772b5f578268c44602967a27cdf138d19cda70
[2023-07-22 09:38:02,634] DEBUG {cps.ub:84} Found stored session: 6f0cabdef656e4cbaa36e5052620c710eec92ac9a7ace0553af112da801630d7cd85f941312eed12bccb757c3f772b5f578268c44602967a27cdf138d19cda70
[2023-07-22 09:38:02,730] DEBUG {cps.ub:84} Found stored session: 6f0cabdef656e4cbaa36e5052620c710eec92ac9a7ace0553af112da801630d7cd85f941312eed12bccb757c3f772b5f578268c44602967a27cdf138d19cda70
[2023-07-22 09:38:02,810] DEBUG {cps.ub:84} Found stored session: 6f0cabdef656e4cbaa36e5052620c710eec92ac9a7ace0553af112da801630d7cd85f941312eed12bccb757c3f772b5f578268c44602967a27cdf138d19cda70
[2023-07-22 09:38:02,898] DEBUG {cps.ub:84} Found stored session: 6f0cabdef656e4cbaa36e5052620c710eec92ac9a7ace0553af112da801630d7cd85f941312eed12bccb757c3f772b5f578268c44602967a27cdf138d19cda70
[2023-07-22 09:38:03,267] DEBUG {cps.ub:84} Found stored session: 6f0cabdef656e4cbaa36e5052620c710eec92ac9a7ace0553af112da801630d7cd85f941312eed12bccb757c3f772b5f578268c44602967a27cdf138d19cda70
[2023-07-22 09:38:03,334] DEBUG {cps.ub:84} Found stored session: 6f0cabdef656e4cbaa36e5052620c710eec92ac9a7ace0553af112da801630d7cd85f941312eed12bccb757c3f772b5f578268c44602967a27cdf138d19cda70
[2023-07-22 09:38:03,406] DEBUG {cps.ub:84} Found stored session: 6f0cabdef656e4cbaa36e5052620c710eec92ac9a7ace0553af112da801630d7cd85f941312eed12bccb757c3f772b5f578268c44602967a27cdf138d19cda70
[2023-07-22 09:38:03,412]  INFO {cps.kobo:143} Kobo library sync request received.
[2023-07-22 09:38:03,412] DEBUG {cps.kobo:144} SyncToken: 2023-05-26 18:33:38.498220,2023-05-26 18:34:38.144115,0001-01-01 00:00:00,2023-06-04 08:08:36.403872,0001-01-01 00:00:00,eyJ0eXAiOjEsInZlciI6bnVsbCwicHR5cCI6IlN5bmNUb2tlbiJ9.eyJJbnRlcm5hbFN5bmNUb2tlbiI6ImV5SjBlWEFpT2pFc0luWmxjaUk2SW5ZeUlpd2ljSFI1Y0NJNklsTjVibU5VYjJ0bGJpSjkuZXlKVGRXSnpZM0pwY0hScGIyNUZiblJwZEd4bGJXVnVkSE1pT25zaVNYTkpibWwwYVdGc0lqcHVkV3hzTENKSFpXNWxjbUYwYVc5dVZHbHRaU0k2Ym5Wc2JDd2lWR2x0WlhOMFlXMXdJam9pTVRrd01DMHdNUzB3TVZRd01Eb3dNRG93TUZvaUxDSkRhR1ZqYTFOMWJTSTZiblZzYkN3aVNXUWlPaUl3TURBd01EQXdNQzB3TURBd0xUQXdNREF0TURBd01DMHdNREF3TURBd01EQXdNREFpZlN3aVJuVjBkWEpsVTNWaWMyTnlhWEIwYVc5dVJXNTBhWFJzWlcxbGJuUnpJanB1ZFd4c0xDSkZiblJwZEd4bGJXVnVkSE1pT25zaVNYTkpibWwwYVdGc0lqcHVkV3hzTENKSFpXNWxjbUYwYVc5dVZHbHRaU0k2Ym5Wc2JDd2lWR2x0WlhOMFlXMXdJam9pTWpBeU15MHdOUzB4TWxRd09EbzBNVG8xTUZvaUxDSkRhR1ZqYTFOMWJTSTZJbnRjSWxOcmFYQkRjbVZoZEdWa1hDSTZabUZzYzJVc1hDSkRjbVZoZEdWa1EyOTFiblJjSWpvd0xGd2lRM0psWVhSbFpGd2lPbHRkTEZ3aVUydHBjRTF2WkdsbWFXVmtYQ0k2Wm1Gc2MyVXNYQ0pOYjJScFptbGxaRndpT2x0ZGZTSXNJa2xrSWpvaU1EQXdNREF3TURBdE1EQXdNQzB3TURBd0xUQXdNREF0TURBd01EQXdNREF3TURBd0luMHNJa1JsYkdWMFpXUkZiblJwZEd4bGJXVnVkSE1pT25zaVNYTkpibWwwYVdGc0lqcHVkV3hzTENKSFpXNWxjbUYwYVc5dVZHbHRaU0k2Ym5Wc2JDd2lWR2x0WlhOMFlXMXdJam9pTWpBeU15MHdOUzB4TWxRd09EbzBNVG8xTUZvaUxDSkRhR1ZqYTFOMWJTSTZiblZzYkN3aVNXUWlPaUl3TURBd01EQXdNQzB3TURBd0xUQXdNREF0TURBd01DMHdNREF3TURBd01EQXdNREFpZlN3aVVtVmhaR2x1WjFOMFlYUmxjeUk2ZXlKSmMwbHVhWFJwWVd3aU9tNTFiR3dzSWtkbGJtVnlZWFJwYjI1VWFXMWxJanB1ZFd4c0xDSlVhVzFsYzNSaGJYQWlPaUl5TURJekxUQTFMVEV5VkRBNE9qUXhPalV3V2lJc0lrTm9aV05yVTNWdElqcHVkV3hzTENKSlpDSTZJakF3TURBd01EQXdMVEF3TURBdE1EQXdNQzB3TURBd0xUQXdNREF3TURBd01EQXdNQ0o5TENKVVlXZHpJanA3SWtselNXNXBkR2xoYkNJNmJuVnNiQ3dpUjJWdVpYSmhkR2x2YmxScGJXVWlPbTUxYkd3c0lsUnBiV1Z6ZEdGdGNDSTZJakl3TWpNdE1EVXRNVEpVTURnNk5ERTZOVEJhSWl3aVEyaGxZMnRUZFcwaU9tNTFiR3dzSWtsa0lqb2lNREF3TURBd01EQXRNREF3TUMwd01EQXdMVEF3TURBdE1EQXdNREF3TURBd01EQXdJbjBzSWtSbGJHVjBaV1JVWVdkeklqcDdJa2x6U1c1cGRHbGhiQ0k2Ym5Wc2JDd2lSMlZ1WlhKaGRHbHZibFJwYldVaU9tNTFiR3dzSWxScGJXVnpkR0Z0Y0NJNklqRTVNREF0TURFdE1ERlVNREE2TURBNk1EQmFJaXdpUTJobFkydFRkVzBpT201MWJHd3NJa2xrSWpvaU1EQXdNREF3TURBdE1EQXdNQzB3TURBd0xUQXdNREF0TURBd01EQXdNREF3TURBd0luMHNJbEJ5YjJSMVkzUk5aWFJoWkdGMFlTSTZleUpKYzBsdWFYUnBZV3dpT201MWJHd3NJa2RsYm1WeVlYUnBiMjVVYVcxbElqcHVkV3hzTENKVWFXMWxjM1JoYlhBaU9pSXlNREl6TFRBMUxURXlWREE0T2pReE9qVXdXaUlzSWtOb1pXTnJVM1Z0SWpwdWRXeHNMQ0pKWkNJNklqQXdNREF3TURBd0xUQXdNREF0TURBd01DMHdNREF3TFRBd01EQXdNREF3TURBd01DSjlmUSIsIklzQ29udGludWF0aW9uVG9rZW4iOmZhbHNlfQ
[2023-07-22 09:38:03,461] DEBUG {cps.kobo:215} Books to Sync: 100
[2023-07-22 09:38:09,657] ERROR {cps:1449} Exception on /kobo/ebb06dba3d1c577f21bd00491d85bf9b/v1/library/sync [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/app/calibre-web/cps/kobo_auth.py", line 168, in inner
    return f(*args, **kwargs)
  File "/app/calibre-web/cps/web.py", line 122, in inner
    return f(*args, **kwargs)
  File "/app/calibre-web/cps/kobo.py", line 224, in HandleSyncRequest
    "BookMetadata": get_metadata(book.Books),
  File "/app/calibre-web/cps/kobo.py", line 465, in get_metadata
    if get_epub_layout(book, book_data) == 'pre-paginated':
  File "/app/calibre-web/cps/epub.py", line 57, in get_epub_layout
    tree = etree.fromstring(cf)
  File "src/lxml/etree.pyx", line 3257, in lxml.etree.fromstring
  File "src/lxml/parser.pxi", line 1916, in lxml.etree._parseMemoryDocument
  File "src/lxml/parser.pxi", line 1803, in lxml.etree._parseDoc
  File "src/lxml/parser.pxi", line 1144, in lxml.etree._BaseParser._parseDoc
  File "src/lxml/parser.pxi", line 618, in lxml.etree._ParserContext._handleParseResultDoc
  File "src/lxml/parser.pxi", line 728, in lxml.etree._handleParseResult
  File "src/lxml/parser.pxi", line 657, in lxml.etree._raiseParseError
  File "<string>", line 14
lxml.etree.XMLSyntaxError: StartTag: invalid element name, line 14, column 219
```

**Expected behavior**
The Kobo e-reader gets the latest books in the library.

**Screenshots**
![ezgif com-optimize](https://github.com/janeczku/calibre-web/assets/25198539/27551ce0-63ee-4785-97e6-f211dc29d131)

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04.6 LTS
 - Docker container: LinuxServer v0.6.20
 - e-reader: Kobo Nia 

**Additional context**
Using nginx as reverse proxy with the following config:
```
server {
  server_name <domain>;
  listen 80;

  location / {
    return 302 https://$host$request_uri;
  }

  location ^~ /kobo/ {
    proxy_pass http://127.0.0.1:8083/kobo;

    include snippets/proxy_pass.conf;

    proxy_busy_buffers_size 512k;
    proxy_buffers 4 512k;
    proxy_buffer_size 512k;
  }
}

server {
  server_name <domain>;

  listen 443 ssl; # managed by Certbot
  include snippets/certbot/<domain>.conf;

  client_max_body_size 200M;

  location / {
    proxy_pass http://127.0.0.1:8083;

    include snippets/proxy_pass.conf;

    proxy_cookie_path / "/; Secure";

    client_max_body_size 200M;
  }
}
```

**Comment by OzzieIsaacs** [comment]
Please try to update to the newest nightly (there should be a container from linuxserver for this). The error is now catched.  

The reason is at least one epub file with an invalid unparsable "container.xml" in it. There will be an error in the log file, the books will be transfered to kobo and can be used normally now.

**Comment by RacmanT** [comment]
Any luck after the update? I've tried but I got no results

**Comment by OzzieIsaacs** [comment]
Is there another error message?

**Comment by timotheeandres** [comment]
The error doesn't appear in the logs anymore, but the sync still doesn't go through and displays the same error message on my Kobo.
The logs on Calibre-web now show:
```
[2023-07-30 18:50:11,244] DEBUG {cps.babel:26} Could not parse locale "*": expected only letters, got '*'
[2023-07-30 18:50:11,402] DEBUG {cps.kobo:987} Unimplemented User Request received: http://<domain>/kobo/ebb06dba3d1c577f21bd00491d85bf9b/v1/user/profile (request is forwarded to kobo if configured)
[2023-07-30 18:50:12,139] DEBUG {cps.kobo:1027} Unimplemented Products Request received: http://<domain>/kobo/ebb06dba3d1c577f21bd00491d85bf9b/v1/deals (request is forwarded to kobo if configured)
```
However, I noticed that one of my books returns 404 when I try to read it on the web reader, and looking into the folder tree I saw that some files seem to be split into multiple folders... I'll investigate this further.

**Comment by RacmanT** [comment]
`[2023-07-30 19:42:49,128] DEBUG {cps.kobo:215} Books to Sync: 7
[2023-07-30 19:42:49,140] ERROR {cps:1449} Exception on /kobo/94c86310afc820630bb6bc7749e30452/v1/library/sync [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/app/calibre-web/cps/kobo_auth.py", line 168, in inner
    return f(*args, **kwargs)
  File "/app/calibre-web/cps/web.py", line 122, in inner
    return f(*args, **kwargs)
  File "/app/calibre-web/cps/kobo.py", line 224, in HandleSyncRequest
    "BookMetadata": get_metadata(book.Books),
  File "/app/calibre-web/cps/kobo.py", line 465, in get_metadata
    if get_epub_layout(book, book_data) == 'pre-paginated':
  File "/app/calibre-web/cps/epub.py", line 61, in get_epub_layout
    p = tree.xpath('/pkg:package/pkg:metadata', namespaces=ns)[0]
IndexError: list index out of range`

this is what I have with the nightly version

**Comment by OzzieIsaacs** [comment]
I updated calibre-web to also catch this new error, please try another update

**Comment by timotheeandres** [comment]
The error I had was due to a misconfiguration of nginx: I have my server behind _two_ nginx servers acting as proxies; I was changing the second one, but the first one was returning 502 because the configuration was not updated.
Everything works fine now! Thank you very much for the quick fix!

**Comment by timotheeandres** [comment]
Hi @OzzieIsaacs! I'm sad to report that I am having the issue again, same logs.
One of the following files is the most probable cause, as it appeared once I added them to Calibre-Web:
[Magic the Gathering - Infraction Procedure Guide (IPG).pdf](https://github.com/janeczku/calibre-web/files/12652242/Magic.the.Gathering.-.Infraction.Procedure.Guide.IPG.pdf)
[Magic the Gathering - Judging at Regular (JAR).pdf](https://github.com/janeczku/calibre-web/files/12652243/Magic.the.Gathering.-.Judging.at.Regular.JAR.pdf)
[Magic the Gathering - Tournament rules.pdf](https://github.com/janeczku/calibre-web/files/12652244/Magic.the.Gathering.-.Tournament.rules.pdf)
[Magic the Gathering - Comprehensive rules.pdf](https://github.com/janeczku/calibre-web/files/12652245/Magic.the.Gathering.-.Comprehensive.rules.pdf)
