### ISSUE TITLE
Cover thumbnail generation fails (HTTP 500 error)

### ISSUE THREAD

**Issue by hal2100** [janeczku/calibre-web#2865]
**Describe the bug/problem**
Books downloaded to Kobo Libra 2 do not get a cover on the reader. The cover download link results in an 500 error.

**To Reproduce**
Good question, this is a new calibre-web instance with the Kobo sync set up.
Synchronizing the books results in the following line in access.log... 

**Logfile access.log**
2023-08-15 20:35:29] "GET /kobo/[REDACTED]/abd621e1-1183-409a-bf7f-f94d7b291e7d/355/530/80/isGreyscale/image.jpg HTTP/1.1" 500

**Logfile calibre-web.log**
[2023-08-15 20:33:33,371] ERROR {cps:1414} Exception on /kobo/[REDACTED]/68073e84-62fa-4017-8647-ee0bd95d01de/355/530/80/isGreyscale/image.jpg [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/app/calibre-web/cps/kobo_auth.py", line 168, in inner
    return f(*args, **kwargs)
  File "/app/calibre-web/cps/kobo.py", line 933, in HandleCoverImageRequest
    resolution = None if height > 1000 else COVER_THUMBNAIL_SMALL
TypeError: '>' not supported between instances of 'str' and 'int'

**Expected behavior**
The covers download correctly.

**Environment (please complete the following information):**
 - Calibre-Web version: 0.6.21 Beta - ba0e5399d6d94694639f956e353cca34dbd0ffe2 - 2023-08-12T14:09:14+02:00
 - Docker container: [None/LinuxServer]: LinuxServer:nightly
 - Browser: Firefox

**Additional context**
No special setup as far as I can see...

**Comment by OzzieIsaacs** [comment]
I have aloof at it this evening

**Comment by OzzieIsaacs** [comment]
Please try to update to the newest nightly version (as soon as it shows up on the linuxserver docker)

**Comment by hal2100** [comment]
It is fixed now, thanks a lot!
