### ISSUE TITLE
Sync to Kobo results in "IndexError: list index out of range"

### ISSUE THREAD

**Issue by auspex** [janeczku/calibre-web#2879]
**Describe the bug/problem**
When attempting to sync to a Kobo, I get an error `IndexError: list index out of range`. 

My Calibre-web _was_ setup to sync only a single shelf, on which there was only one book. However, it's now managed to sync FROM the Kobo to CW, and created shelves for every series... So, not as simple as I hoped to figure out _where_ there's an issue.

**To Reproduce**
1. Calibre-web (and Calibre) installed as Docker containers
2. Traefik & Authelia set up per https://github.com/janeczku/calibre-web/wiki/Setup-Reverse-Proxy/#traefik--241-with-authelia-forward-auth
3. Either choose "sync" from the Kobo, or just go to the sync URL https://books.DOMAIN/kobo/********
5. See error

**Logfile**
```
[2023-09-05 16:14:31,763]  INFO {cps.kobo:143} Kobo library sync request received.
[2023-09-05 16:14:31,831] ERROR {cps:1449} Exception on /kobo/**************/v1/library/sync [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/app/calibre-web/cps/kobo_auth.py", line 168, in inner
    return f(*args, **kwargs)
  File "/app/calibre-web/cps/web.py", line 122, in inner
    return f(*args, **kwargs)
  File "/app/calibre-web/cps/kobo.py", line 224, in HandleSyncRequest
    "BookMetadata": get_metadata(book.Books),
  File "/app/calibre-web/cps/kobo.py", line 465, in get_metadata
    if get_epub_layout(book, book_data) == 'pre-paginated':
  File "/app/calibre-web/cps/epub.py", line 58, in get_epub_layout
    p = tree.xpath('/pkg:package/pkg:metadata', namespaces=ns)[0]
IndexError: list index out of range
```
**Expected behavior**
I'd hope that the sync would have continued without a fatal error in the server.

**Screenshots**

**Environment (please complete the following information):**
 - OS: Linux Mint 21.2 Victoria
 - Calibre Web	0.6.20 - 1451a67912a41a4811dcd425abc49bc49becb711 - 2023-03-27T19:49:57+02:00
 - Python	3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0]
 - Platform	Linux 6.2.0-31-generic  31~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Wed Aug 16 13:45:26 UTC 2 x86_64 x86_64
 - Docker container: LinuxServer
 - Special Hardware: 
 - Browser: N/A

**Additional context**
My library has 3200+ books, of which fewer than half have an actual e-book, as it is where I log every book I read. However, I doubt it's just coming up with an error on a non-existent book or it wouldn't likely be "pre-paginated".

**Comment by OzzieIsaacs** [comment]
Please try to update to the newest nightly version(there should be a docker container available), it should work then

**Comment by OzzieIsaacs** [comment]
Duplicate of #2840

**Comment by auspex** [comment]
Ah. Cool. The originally reported error was nothing like... but I see it further down.
