### ISSUE TITLE
Error 500 when uploading 9 PDFs each 40 MByte

### ISSUE THREAD

**Issue by JarlMorgennebel** [janeczku/calibre-web#2891]
**Describe the bug/problem**
Uploading 9 PDFs at once using the web frontend logged in as admin.
Server reports error 500.

**To Reproduce**
1. Click Upload
2. Select 9 PDFs
3. Wait

**Logfile**
````
[2023-09-19 08:14:00,949] DEBUG {cps.uploader:261} Temporary file: /tmp/calibre_web/ed92792829c4f7719689d3293dc917e6
[2023-09-19 08:14:02,919] ERROR {cps:1449} Exception on /upload [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/app/calibre-web/cps/usermanagement.py", line 35, in decorated_view
    return login_required(func)(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/app/calibre-web/cps/editbooks.py", line 61, in inner
    return f(*args, **kwargs)
  File "/app/calibre-web/cps/editbooks.py", line 252, in upload
    meta, error = file_handling_on_upload(requested_file)
  File "/app/calibre-web/cps/editbooks.py", line 738, in file_handling_on_upload
    meta = uploader.upload(requested_file, config.config_rarfile_location)
  File "/app/calibre-web/cps/uploader.py", line 263, in upload
    return process(tmp_file_path, filename_root, file_extension, rarExcecutable)
  File "/app/calibre-web/cps/uploader.py", line 92, in process
    if not meta.author.strip() or meta.author.lower() == 'unknown':
AttributeError: 'str' object has no attribute 'author'
````

**Expected behavior**
No error 500 and working uploads.

**Screenshots**

**Environment (please complete the following information):**
 - OS: Devuan Linux
 - Python version: python3.10
 - Calibre-Web version:  0.6.20
 - Docker container: ghcr.io/linuxserver/calibre-web
 - Special Hardware: Wyse 5070, 32 GB RAM, 256 GB SSD
 - Browser: Vivaldi 6.2.3105.48 (Stable channel) (x86_64) on Mac OS

**Additional context**
Access via nginx-proxy-manager. Settings in Advanced tab:

`````
client_max_body_size 2G;
proxy_buffer_size 128k;
proxy_buffers 4 256k;
proxy_busy_buffers_size 256k;
proxy_hide_header 'x-frame-options';
proxy_set_header Host $host;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
real_ip_header X-Forwarded-For;
````

**Comment by AubinF** [comment]
Hi, similar issue here. Although it does not seem to be related to the number of files. I repeatedly get the same error even with one "wrong" file.

        
Traceback (most recent call last):
  File "/home/www-data/envs/calibre-web-env/lib/python3.10/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/www-data/envs/calibre-web-env/lib/python3.10/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/www-data/envs/calibre-web-env/lib/python3.10/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/www-data/envs/calibre-web-env/lib/python3.10/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/www-data/envs/calibre-web-env/lib/python3.10/site-packages/calibreweb/cps/usermanagement.py", line 35, in decorated_view
    return login_required(func)(*args, **kwargs)
  File "/home/www-data/envs/calibre-web-env/lib/python3.10/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/home/www-data/envs/calibre-web-env/lib/python3.10/site-packages/calibreweb/cps/editbooks.py", line 61, in inner
    return f(*args, **kwargs)
  File "/home/www-data/envs/calibre-web-env/lib/python3.10/site-packages/calibreweb/cps/editbooks.py", line 252, in upload
    meta, error = file_handling_on_upload(requested_file)
  File "/home/www-data/envs/calibre-web-env/lib/python3.10/site-packages/calibreweb/cps/editbooks.py", line 738, in file_handling_on_upload
    meta = uploader.upload(requested_file, config.config_rarfile_location)
  File "/home/www-data/envs/calibre-web-env/lib/python3.10/site-packages/calibreweb/cps/uploader.py", line 263, in upload
    return process(tmp_file_path, filename_root, file_extension, rarExcecutable)
  File "/home/www-data/envs/calibre-web-env/lib/python3.10/site-packages/calibreweb/cps/uploader.py", line 92, in process
    if not meta.author.strip() or meta.author.lower() == 'unknown':
AttributeError: 'str' object has no attribute 'author'


I have tried to set the author/Author tag of my pdf file using exiftool but it did not help.

OS: ubuntu 22 LTS
Calibre Web version : 0.6.20 (running in virtual env)
python: 3.10.12
browser: chromium web browser 117.0.5938.92

**Comment by OzzieIsaacs** [comment]
Please update to the newest nightly version. This PR https://github.com/janeczku/calibre-web/pull/2775 could be related to this. If it‘s not helping please report back, in this case I‘ll have a deeper look at it
