### ISSUE TITLE
Error during upload of multiple PDF files

### ISSUE THREAD

**Issue by Eulenbaer** [janeczku/calibre-web#2912]
**Describe the bug/problem**
The Server encountered an error during the upload of multiple PDFs via the web-interface.
The location of the PDFs is a SMB share e.g. \\SERVER\folder\ebook.pdf

**To Reproduce**
1. Login as User
2. Select 'Upload' from the top right corner
3. Select multiple PDF files to be uploaded (located at SMB share)

**Logfile**
[2023-10-15 12:51:52,874]  WARN {cps.uploader:88} cannot parse metadata, using default: seek of closed file
[2023-10-15 12:51:52,886] ERROR {cps:1449} Exception on /upload [POST]
Traceback (most recent call last):
  File "/lsiopy/lib/python3.10/site-packages/sqlalchemy/engine/cursor.py", line 991, in fetchall
    rows = dbapi_cursor.fetchall()
sqlite3.InterfaceError: Cursor needed to be reset because of commit/rollback and can no longer be fetched from.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/lsiopy/lib/python3.10/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/lsiopy/lib/python3.10/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/lsiopy/lib/python3.10/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/lsiopy/lib/python3.10/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/app/calibre-web/cps/usermanagement.py", line 35, in decorated_view
    return login_required(func)(*args, **kwargs)
  File "/lsiopy/lib/python3.10/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/app/calibre-web/cps/editbooks.py", line 61, in inner
    return f(*args, **kwargs)
  File "/app/calibre-web/cps/editbooks.py", line 272, in upload
    error = helper.update_dir_structure(book_id,
  File "/app/calibre-web/cps/helper.py", line 718, in update_dir_structure
    return update_dir_structure_file(book_id,
  File "/app/calibre-web/cps/helper.py", line 456, in update_dir_structure_file
    local_book = calibre_db.get_book(book_id)
  File "/app/calibre-web/cps/db.py", line 652, in get_book
    return self.session.query(Books).filter(Books.id == book_id).first()
  File "/lsiopy/lib/python3.10/site-packages/sqlalchemy/orm/query.py", line 2824, in first
    return self.limit(1)._iter().first()
  File "/lsiopy/lib/python3.10/site-packages/sqlalchemy/engine/result.py", line 1498, in first
    return self._only_one_row(
  File "/lsiopy/lib/python3.10/site-packages/sqlalchemy/engine/result.py", line 559, in _only_one_row
    row = onerow(hard_close=True)
  File "/lsiopy/lib/python3.10/site-packages/sqlalchemy/engine/result.py", line 1386, in _fetchone_impl
    return self._real_result._fetchone_impl(hard_close=hard_close)
  File "/lsiopy/lib/python3.10/site-packages/sqlalchemy/engine/result.py", line 1801, in _fetchone_impl
    row = next(self.iterator, _NO_ROW)
  File "/lsiopy/lib/python3.10/site-packages/sqlalchemy/orm/loading.py", line 147, in chunks
    fetch = cursor._raw_all_rows()
  File "/lsiopy/lib/python3.10/site-packages/sqlalchemy/engine/result.py", line 392, in _raw_all_rows
    rows = self._fetchall_impl()
  File "/lsiopy/lib/python3.10/site-packages/sqlalchemy/engine/cursor.py", line 1819, in _fetchall_impl
    return self.cursor_strategy.fetchall(self, self.cursor)
  File "/lsiopy/lib/python3.10/site-packages/sqlalchemy/engine/cursor.py", line 995, in fetchall
    self.handle_exception(result, dbapi_cursor, e)
  File "/lsiopy/lib/python3.10/site-packages/sqlalchemy/engine/cursor.py", line 955, in handle_exception
    result.connection._handle_dbapi_exception(
  File "/lsiopy/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2134, in _handle_dbapi_exception
    util.raise_(
  File "/lsiopy/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/lsiopy/lib/python3.10/site-packages/sqlalchemy/engine/cursor.py", line 991, in fetchall
    rows = dbapi_cursor.fetchall()
sqlalchemy.exc.InterfaceError: (sqlite3.InterfaceError) Cursor needed to be reset because of commit/rollback and can no longer be fetched from.
(Background on this error at: https://sqlalche.me/e/14/rvf5)

**Expected behavior**
Nothing, a successfull upload I guess.

**Screenshots**
...

**Environment (please complete the following information):**
 - OS: Docker
 - Python version: python3.10
 - Calibre-Web version: [e.g. 0.6.8 or 087c4c59 (git rev-parse --short HEAD)]:
 - Docker container: [None/LinuxServer]:
 - Special Hardware: [e.g. Rasperry Pi Zero]
 - Browser: [e.g. Chrome 83.0.4103.97, Safari 13.3.7, Firefox 68.0.1 ESR]

**Additional context**
Docker image: https://docs.linuxserver.io/images/docker-calibre-web

**Comment by OzzieIsaacs** [comment]
I‘m aware of this. It‘s indeed an ugly bug. For now there is only the workaround to upload book by book, or to restore the database from the metadata backup if this error occurs

**Comment by Eulenbaer** [comment]
Alright, thanks for the reply. I will avoid uploading multiple PDF at once.

**Comment by OzzieIsaacs** [comment]
The error occurs also with any other file format

**Comment by cgraham149** [comment]
Same happens for multiple audio m4a/mp3 files in a series for audiobooks.

Example:
- chapter-01.mp3
- chapter-02.mp3
- chapter-03.mp3

They all get renamed to _{{title}} - {{author}}_ **without** being incremented.

If file exists then increment +1 to fie name, then save would possibly be a fix? 

I just tried to add multiple series files to Calibre desktop and had same results. Each file **overwrites** the previous file.

### Workaround 1
Upload one large audio file instead of a series of chapters (not ideal).

### Workaround 2
Create new entry per each audio file uploaded and make it part of a Calibre book series (also, not ideal). 

Any other suggestions or workarounds?

**Comment by OzzieIsaacs** [comment]
The newest nightly version should solve the issue (hopefully)
