### ISSUE TITLE
Database Error Viewing Series or doing Text Search

### ISSUE THREAD

**Issue by Count0Int** [janeczku/calibre-web#2923]
**Describe the bug/problem**
Error that states the database error: disk image is malformed.

The app is mostly working, but I get this error when selecting 'Series'.  I get a similiar error when doing a text search.

I exported the calibre database and reimported it new, but still get the error.  I have also done database maintenance and there are no errors.

Wondering if there is a way to determine what the issue is in the database so I can correct either the book/record or metadata....

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: Windows 10 for Calibre Server
 - Calibre-Web version: 0.6.21
 - Docker container: LinuxServer running on TrueNAS virtual machine.
 - Browser: Occurs on both Edge and Chrome browsers.

Error/Logfile:

Calibre-Web
500 Internal Server Error
The server encountered an internal error and was unable to complete your request. There is an error in the application.
Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1910, in _execute_context
self.dialect.do_execute(
File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
cursor.execute(statement, parameters)
sqlite3.DatabaseError: database disk image is malformed
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
response = self.full_dispatch_request()
File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1519, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1517, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1503, in dispatch_request
return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
File "/usr/local/app/calibre-web/cps/usermanagement.py", line 35, in decorated_view
return login_required(func)(*args, **kwargs)
File "/usr/local/lib/python3.9/site-packages/flask_login/utils.py", line 290, in decorated_view
return current_app.ensure_sync(func)(*args, **kwargs)
File "/usr/local/app/calibre-web/cps/web.py", line 1013, in series_list
entries = (calibre_db.session.query(db.Books, func.count('books_series_link').label('count'),
File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 2773, in all
return self._iter().all()
File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 2916, in _iter
result = self.session.execute(
File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1717, in execute
result = conn._execute_20(statement, params or {}, execution_options)
File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1710, in _execute_20
return meth(self, args_10style, kwargs_10style, execution_options)
File "/usr/local/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 334, in _execute_on_connection
return connection._execute_clauseelement(
File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1577, in _execute_clauseelement
ret = self._execute_context(
File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1953, in _execute_context
self._handle_dbapi_exception(
File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2134, in _handle_dbapi_exception
util.raise_(
File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
raise exception
File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1910, in _execute_context
self.dialect.do_execute(
File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
cursor.execute(statement, parameters)
sqlalchemy.exc.DatabaseError: (sqlite3.DatabaseError) database disk image is malformed
[SQL: SELECT books.id AS books_id, books.title AS books_title, books.sort AS books_sort, books.author_sort AS books_author_sort, books.timestamp AS books_timestamp, books.pubdate AS books_pubdate, books.series_index AS books_series_index, books.last_modified AS books_last_modified, books.path AS books_path, books.has_cover AS books_has_cover, books.uuid AS books_uuid, books.isbn AS books_isbn, books.flags AS books_flags, count(?) AS count, max(books.series_index) AS max_1, books.id AS books_id__1
FROM books JOIN books_series_link ON books.id = books_series_link.book JOIN series ON series.id = books_series_link.series
WHERE (books.id NOT IN (SELECT 1 FROM (SELECT 1) WHERE 1!=1)) GROUP BY books_series_link.series
HAVING max(books.series_index) OR books.series_index = ? ORDER BY series.sort ASC]
[parameters: ('books_series_link', '')]
(Background on this error at: https://sqlalche.me/e/14/4xp6)

**Comment by OzzieIsaacs** [comment]
Most likely (for unkonwn reason) the database file (metadata.db) is indeed corupted, sometimes this affects only certain tables within the database. So certain functions are working and others are not. 
If check database from calibre isn't working and rebuild database isn't working, I would need the database file (the metadata.db file), preferably by email (email address from my profile page) and I have a look at it.
