### ISSUE TITLE
Calibre-Web 500 Internal Server Error

### ISSUE THREAD

**Issue by fscbest** [janeczku/calibre-web#2925]
**Describe the bug/problem**
Calibre-Web failing with "500 Internal Server Error" when login.

**To Reproduce**

**Logfile**
The server encountered an internal error and was unable to complete your request. There is an error in the application.
Traceback (most recent call last):
File "/lsiopy/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
response = self.full_dispatch_request()
File "/lsiopy/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/lsiopy/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
rv = self.dispatch_request()
File "/lsiopy/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
File "/app/calibre-web/cps/usermanagement.py", line 35, in decorated_view
return login_required(func)(*args, **kwargs)
File "/lsiopy/lib/python3.10/site-packages/flask_login/utils.py", line 290, in decorated_view
return current_app.ensure_sync(func)(*args, **kwargs)
File "/app/calibre-web/cps/web.py", line 790, in index
return render_books_list("newest", sort_param, 1, page)
File "/app/calibre-web/cps/web.py", line 408, in render_books_list
entries, random, pagination = calibre_db.fill_indexpage(page, 0, db.Books, True, order[0],
File "/app/calibre-web/cps/db.py", line 803, in fill_indexpage
return self.fill_indexpage_with_archived_books(page, database, pagesize, db_filter, order, False,
File "/app/calibre-web/cps/db.py", line 810, in fill_indexpage_with_archived_books
random_query = self.generate_linked_query(config_read_column, database)
File "/app/calibre-web/cps/db.py", line 764, in generate_linked_query
query = (self.session.query(database, ub.ArchivedBook.is_archived, ub.ReadBook.read_status)
AttributeError: 'NoneType' object has no attribute 'query'

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: Synology DSM 7.2.1-69057
 - Python version: python3.10
 - Calibre-Web version: [e.g. 0.6.8 or 087c4c59 (git rev-parse --short HEAD)]:
 - Docker container: Synology DSM 7.2.1-69057:
 - Special Hardware: 
 - Browser: Chrome Version 119.0.6045.105 (Official Build) (64-bit)]

**Additional context**
Add any other context about the problem here. [e.g. access via reverse proxy, database background sync, special database location]

**Comment by OzzieIsaacs** [comment]
This is a usual docker problem with wrong permissions. If you search for the "AttributeError: 'NoneType' object has no attribute 'query'" message in the issues you will find several of this issues. Please follow the instructions of the docker container provider very strict.

**Comment by fscbest** [comment]
I don't think so...
It did work for a couple of weeks until calibre-web was updated.

**Comment by fscbest** [comment]
GET http://******:7083/author?data=author&sort_param=stored 500 (INTERNAL SERVER ERROR)
content.js:12 up_chaunce 
{action: 'checkTikTokPageNeedForceReload', forceReload: false}
action
: 
"checkTikTokPageNeedForceReload"
forceReload
: 
false

**Comment by mamema** [comment]
had the :same problem.
Solution: Delete container, delete image, delete config.
Start from scratch
solved!

**Comment by IceflowRE** [comment]
> Hi, I encountered the same 500 error after updating the db via an external source on the Caliber web application in a Truenas Scale NAS (.db is not writable). In Truenas, there is no need to uninstall everything, but each time the .db is updated, you must return the owner and group rights to APPS via the SMB ACL system, and then caliber-Web works again (it This is a writing problem on the .db which reappears with each modification or update.) You then have to redeploy the application and everything works correctly. Sorry if my English is not very correct but I am French...

You can fix this with setting the correct IDs, add this to the `docker-compose.yml` file (replace the ids correctly)
```
    environment:
      - PUID=1000
      - PGID=1000
```

**Comment by bonnebulle** [comment]
Hum
am facing the same / near issue... 
Am using Docker...

ENV (ok) :
PGID 	1000
PUID 	1000

With permission errors on upgrade...

Current version : 0.6.23 
Try to upgrade to : 0.6.24

Trying :
```bash
$ /var/www/pip/venv/bin/cps -p app.db -d

Excluded file list for updater not found, or not accessible

*** Finished ***
```


Logs / infos :
[calibre-web.log](https://github.com/user-attachments/files/19576170/calibre-web.log)
[Calibre_debug_light.tar.gz](https://github.com/user-attachments/files/19576189/Calibre_debug_light.tar.gz)

Thanks for all
