### ISSUE TITLE
I can not add a book

### ISSUE THREAD

**Issue by linknixon** [janeczku/calibre-web#2980]
I am getting this error while adding a book on version 0.6.21
```
Traceback (most recent call last):
File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 2073, in wsgi_app
response = self.full_dispatch_request()
File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1519, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1517, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1503, in dispatch_request
return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
File "/usr/local/lib/python3.10/dist-packages/calibreweb/cps/usermanagement.py", line 34, in decorated_view
return func(*args, **kwargs)
File "/usr/local/lib/python3.10/dist-packages/calibreweb/cps/web.py", line 790, in index
return render_books_list("newest", sort_param, 1, page)
File "/usr/local/lib/python3.10/dist-packages/calibreweb/cps/web.py", line 413, in render_books_list
return render_title_template('index.html', random=random, entries=entries, pagination=pagination,
File "/usr/local/lib/python3.10/dist-packages/calibreweb/cps/render_template.py", line 114, in render_title_template
return render_template(instance=config.config_calibre_web_title, sidebar=sidebar, simple=simple,
File "/usr/local/lib/python3.10/dist-packages/flask/templating.py", line 154, in render_template
return _render(
File "/usr/local/lib/python3.10/dist-packages/flask/templating.py", line 128, in _render
rv = template.render(context)
File "/usr/local/lib/python3.10/dist-packages/jinja2/environment.py", line 1301, in render
self.environment.handle_exception()
File "/usr/local/lib/python3.10/dist-packages/jinja2/environment.py", line 936, in handle_exception
raise rewrite_traceback_stack(source=source)
File "/usr/local/lib/python3.10/dist-packages/calibreweb/cps/templates/index.html", line 2, in top-level template code
{% extends "layout.html" %}
File "/usr/local/lib/python3.10/dist-packages/calibreweb/cps/templates/layout.html", line 167, in top-level template code
{% block body %}{% endblock %}
File "/usr/local/lib/python3.10/dist-packages/calibreweb/cps/templates/index.html", line 137, in block 'body'
({{entry.Books.series_index|formatseriesindex}})
File "/usr/local/lib/python3.10/dist-packages/calibreweb/cps/jinjia.py", line 123, in formatseriesindex_filter
if int(series_index) - series_index == 0:
TypeError: unsupported operand type(s) for -: 'int' and 'str'
```

**Comment by OzzieIsaacs** [comment]
Please try to update to the newest commit version, it should work then. 
Additionally I would be interested what causes the issue, so it would be great if you could send me the corresponding book, or 
In case of a epub, please open the book using a zip reader and search for a file named "content.opf". Please send me the file via my private email (I guess it is having a dash instead of a number or something like this)
