### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by filwu8** [janeczku/calibre-web#2985]
i can't download my books，and i can’t read my book。500 Internal Server Error

Before this, it was used normally for about 2 years, but this fault occurred after upgrading the software recently

500 Internal Server Error
The server encountered an internal error and was unable to complete your request. There is an error in the application.
Traceback (most recent call last):
File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 2073, in wsgi_app
response = self.full_dispatch_request()
File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1518, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1516, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1502, in dispatch_request
return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
File "/app/calibre-web/cps/usermanagement.py", line 35, in decorated_view
return login_required(func)(*args, **kwargs)
File "/usr/local/lib/python3.10/dist-packages/flask_login/utils.py", line 303, in decorated_view
return current_app.ensure_sync(func)(*args, **kwargs)
File "/app/calibre-web/cps/web.py", line 122, in inner
return f(*args, **kwargs)
File "/app/calibre-web/cps/web.py", line 1225, in download_link
return get_download_link(book_id, book_format, client)
File "/app/calibre-web/cps/helper.py", line 1045, in get_download_link
return do_download_file(book, book_format, client, data1, headers)
File "/app/calibre-web/cps/helper.py", line 958, in do_download_file
response = make_response(send_from_directory(filename, data.name + "." + book_format))
File "/usr/local/lib/python3.10/dist-packages/flask/helpers.py", line 700, in send_from_directory
return werkzeug.utils.send_from_directory( # type: ignore
File "/usr/local/lib/python3.10/dist-packages/werkzeug/utils.py", line 852, in send_from_directory
return send_file(path, environ, **kwargs)
File "/usr/local/lib/python3.10/dist-packages/werkzeug/utils.py", line 752, in send_file
file = open(path, "rb") # type: ignore
OSError: [Errno 5] Input/output error: '/books/Lin Yu Xiang Suo Zai De Zhen Shi G/San Zhong Men 1 (31231)/San Zhong Men 1 - Lin Yu Xiang Suo Zai De Zhen Sh.txt'

**Comment by filwu8** [comment]
I know how ever , 
Computer hard drive malfunction
hard disk error
i fix it

please  close  issues，Thanks ！
