### ISSUE TITLE
Unable to generate kobo sync token

### ISSUE THREAD

**Issue by saxx0n** [janeczku/calibre-web#3047]
**Describe the bug/problem** 

When I attempt to create a kobo sync token, I get 3 dots on the pop-up where I expect the token to be, however the auth URL never appears.  

**To Reproduce**

Log in as a user, click on the user tab in the upper right corner, and click "create/view" on the kobo sync token

**Logfile**

```
[2024-05-09 14:07:44,306] ERROR {cps:1414} Exception on /kobo_auth/generate_auth_token/1 [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1910, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlite3.InterfaceError: bad parameter or other API misuse
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/calibre-web/cps/kobo_auth.py", line 110, in generate_auth_token
    formats = [data.format for data in book.data]
                                       ^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/orm/attributes.py", line 487, in __get__
    return self.impl.get(state, dict_)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/orm/attributes.py", line 959, in get
    value = self._fire_loader_callables(state, key, passive)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/orm/attributes.py", line 995, in _fire_loader_callables
    return self.callable_(state, passive)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/orm/strategies.py", line 912, in _load_for_state
    return self._emit_lazyload(
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/orm/strategies.py", line 1046, in _emit_lazyload
    result = session.execute(
             ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1717, in execute
    result = conn._execute_20(statement, params or {}, execution_options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1710, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/sql/elements.py", line 334, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1577, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1953, in _execute_context
    self._handle_dbapi_exception(
  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 2134, in _handle_dbapi_exception
    util.raise_(
  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1910, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.InterfaceError: (sqlite3.InterfaceError) bad parameter or other API misuse
[SQL: SELECT calibre.data.id AS calibre_data_id, calibre.data.book AS calibre_data_book, calibre.data.format AS calibre_data_format, calibre.data.uncompressed_size AS calibre_data_uncompressed_size, calibre.data.name AS calibre_data_name
FROM calibre.data
WHERE ? = calibre.data.book]
[parameters: (1020,)]
(Background on this error at: https://sqlalche.me/e/14/rvf5)
```
**Expected behavior**

A token to be generated/displayed

**Environment (please complete the following information):**

 - OS: Ubuntu 22.04
 - Python version: 3.12.3
 - Calibre-Web version: 0.6.21
 - Docker container: k3s
 - Special Hardware: N/A
 - Browser: Firefox 125.0.3

**Comment by Bakkoda** [comment]
I just installed calibre-web last night via tteck script to test it out. Everything works fine except as soon as I hit generate token i get a popup with 3 dots, the following error and the LXC hangs for a bit.

**Logfile**
`[2024-05-10 08:44:05,594] ERROR {cps:1414} Exception on /kobo_auth/generate_auth_token/1 [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/cursor.py", line 991, in fetchall
    rows = dbapi_cursor.fetchall()
sqlite3.InterfaceError: Cursor needed to be reset because of commit/rollback and can no longer be fetched from.
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/usr/local/lib/python3.9/dist-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/calibreweb/cps/kobo_auth.py", line 110, in generate_auth_token
    formats = [data.format for data in book.data]
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/attributes.py", line 487, in __get__
    return self.impl.get(state, dict_)
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/attributes.py", line 959, in get
    value = self._fire_loader_callables(state, key, passive)
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/attributes.py", line 995, in _fire_loader_callables
    return self.callable_(state, passive)
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/strategies.py", line 912, in _load_for_state
    return self._emit_lazyload(
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/strategies.py", line 1050, in _emit_lazyload
    result = result.unique().scalars().all()
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/result.py", line 1476, in all
    return self._allrows()
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/result.py", line 401, in _allrows
    rows = self._fetchall_impl()
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/result.py", line 1389, in _fetchall_impl
    return self._real_result._fetchall_impl()
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/result.py", line 1813, in _fetchall_impl
    return list(self.iterator)
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/loading.py", line 147, in chunks
    fetch = cursor._raw_all_rows()
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/result.py", line 392, in _raw_all_rows
    rows = self._fetchall_impl()
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/cursor.py", line 1819, in _fetchall_impl
    return self.cursor_strategy.fetchall(self, self.cursor)
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/cursor.py", line 995, in fetchall
    self.handle_exception(result, dbapi_cursor, e)
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/cursor.py", line 955, in handle_exception
    result.connection._handle_dbapi_exception(
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/base.py", line 2134, in _handle_dbapi_exception
    util.raise_(
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/cursor.py", line 991, in fetchall
    rows = dbapi_cursor.fetchall()
sqlalchemy.exc.InterfaceError: (sqlite3.InterfaceError) Cursor needed to be reset because of commit/rollback and can no longer be fetched from.
(Background on this error at: https://sqlalche.me/e/14/rvf5)`

**Environment (please complete the following information):**

OS: Linux 5.15.149-1-pve
Python version: 3.9.2
Calibre-Web version: 0.6.21
Special Hardware: N/A
Browser: Firefox 125.0.3

**Comment by ja-m** [comment]
I also had the problem that the token was never generated. I saw in the processes that kepubify was running at the same time. So I removed the kepubify link “/usr/bin/kepubify”, restarted the Docker container and generated the token again. After the generation, I set the link again and everything worked fine.

**Comment by saxx0n** [comment]
This one can be tracked down to user error/non-intutive error message.

My library was still in the middle of a epub -> kepub conversion and once it finished the token popped right up

**Comment by mduijm** [comment]
hi, this problem is still there, when /usr/bin/kepubify is configured, the token won't be displayed until all books have been converted. Can this behavior be changed? When adding new users and they want to create a token I have to manually remove and add the /usr/bin/kepubify every time.

**Comment by mduijm** [comment]
or another idea is to have a task that will auto convert all books to this format?

**Comment by macr0dev** [comment]
I have stumbled across this problem as well.  Didn't have it on original setup a few years ago, but my wife's Kobo reset so I needed the key again.  Fortunately I was able to dig it out of the database, but I pulled out the kepubify dir, pulled the settings referencing it, restarted the container, nothing.  
  
I'm not getting the log errors that the user who created the issue is though.

**Comment by jake-bateman** [comment]
I'm also having this issue, without any keypubify processes running. To clarify a bit as it took me a second to work out, the workaround described by @mduijm does indeed work;

Go to the admin > external binaries settings and remove the path from the kepubify box. Save. Generate API URL. Put path back in box.

I even tried renaming the binary entirely within the container and that did not allow a URL to be generated, but this workaround does indeed help.

**Comment by Athenano** [comment]
I am having this issue now, and I have removed the path to kepubify, but I am still not getting a token. Has anyone else had this issue come back?

**Comment by theodotdot** [comment]
I have had issues with the sync on my kobo and tried to view the token and got the 3 dots, deleted it and tried generating it again and I keep having the 3 dots. I don't have kepubify installed, running 0.6.25

**Comment by BrainBacon** [comment]
May be related to #3539

I noticed a 500 response with `no such column: books.isbn` when trying to generate a token.

**Comment by Dirk71** [comment]
This issue is only applicable in the standard-theme (light). In the dark theme, the kepubify-path has not to be removed before generating a token. But the dark theme has another issue as you can see here.....the token is visible but difficult to read (I have highlighted this in green).....

<img width="898" height="174" alt="Image" src="https://github.com/user-attachments/assets/4c35c719-2684-4ec2-aea2-32bfb62829b8" />
