### ISSUE TITLE
Upload issue

### ISSUE THREAD

**Issue by elis33v** [janeczku/calibre-web#3104]
After the update 0.6.22, when I try to upload a book I get a 500 error.

The logs show this:

```
[2024-07-18 11:15:37,866]  INFO {apscheduler.scheduler:181} Scheduler started
[2024-07-18 11:15:37,909]  INFO {apscheduler.scheduler:895} Added job "delete temp" to job store "default"
[2024-07-18 11:15:37,911]  INFO {apscheduler.scheduler:895} Added job "backup metadata" to job store "default"
[2024-07-18 11:15:37,914]  INFO {apscheduler.scheduler:895} Added job "delete superfluous book covers" to job store "default"
[2024-07-18 11:15:37,915]  INFO {apscheduler.scheduler:895} Added job "generate book covers" to job store "default"
[2024-07-18 11:15:37,915]  INFO {apscheduler.scheduler:895} Added job "end scheduled task" to job store "default"
[2024-07-18 11:15:37,916]  INFO {apscheduler.scheduler:895} Added job "immediately delete temp" to job store "default"
[2024-07-18 11:15:38,266]  INFO {apscheduler.executors.default:123} Running job "immediately delete temp (trigger: date[2024-07-18 14:15:37 UTC], next run at: 2024-07-18 14:15:37 UTC)" (scheduled at 2024-07-18 14:15:37.916826+03:00)
[2024-07-18 11:15:38,266]  INFO {apscheduler.scheduler:641} Removed job 83a6c71610f84c6ebc2b9854f3ed8a1b
[2024-07-18 11:15:38,270]  INFO {apscheduler.executors.default:144} Job "immediately delete temp (trigger: date[2024-07-18 14:15:37 MSK], next run at: 2024-07-18 14:15:37 MSK)" executed successfully
[2024-07-18 11:15:42,439]  INFO {cps.server:269} Starting Tornado server on :443
[2024-07-18 11:15:49,473] ERROR {cps.db:882} Author King, S not found to display name in right order
[2024-07-18 11:15:49,478] ERROR {cps.db:882} Author King, S not found to display name in right order
[2024-07-18 11:15:49,483] ERROR {cps.db:882} Author King, S not found to display name in right order
[2024-07-18 11:15:49,487] ERROR {cps.db:882} Author King, S not found to display name in right order
[2024-07-18 11:15:49,492] ERROR {cps.db:882} Author King, S not found to display name in right order
[2024-07-18 11:15:57,727] ERROR {cps:1414} Exception on /upload [POST]
Traceback (most recent call last):
  File "C:\Users\u\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\u\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\u\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\u\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "E:\calibre\cps\usermanagement.py", line 35, in decorated_view
    return login_required(func)(*args, **kwargs)
  File "C:\Users\u\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "E:\calibre\cps\editbooks.py", line 59, in inner
    return f(*args, **kwargs)
  File "E:\calibre\cps\editbooks.py", line 249, in upload
    meta, error = file_handling_on_upload(requested_file)
  File "E:\calibre\cps\editbooks.py", line 755, in file_handling_on_upload
    if not validate_mime_type(requested_file, allowed_extensions):
  File "E:\calibre\cps\file_helper.py", line 49, in validate_mime_type
    mime = magic.Magic(mime=True)
  File "C:\Users\u\AppData\Local\Programs\Python\Python310\lib\site-packages\magic\magic.py", line 71, in __init__
    magic_load(self.cookie, magic_file)
  File "C:\Users\u\AppData\Local\Programs\Python\Python310\lib\site-packages\magic\magic.py", line 272, in magic_load
    return _magic_load(cookie, coerce_filename(filename))
  File "C:\Users\u\AppData\Local\Programs\Python\Python310\lib\site-packages\magic\magic.py", line 203, in errorcheck_negative_one
    raise MagicException(err)
magic.magic.MagicException: b'could not find any valid magic files!'
```
I saw a warning about the need to install magic and other packages, and installed everything necessary, but still received an error.

 - OS: Win Server 2019
 - Python version: 3.10.6
 - Calibre-Web version: 0.6.22
 - Docker container: [None/LinuxServer]:
 - Special Hardware: [e.g. Rasperry Pi Zero]
 - Browser: any

**Comment by OzzieIsaacs** [comment]
Some details would be good. 
What filetype? 
What is the setting for allowed upload filetypes?
In between you could deactivate the check of uploaded files in admin -> basic config -> security -> "Check if file extensions matches file content on upload"

**Comment by elis33v** [comment]
These were epub files.

Yes, disabling the security check helped, although on version 0.6.21 the same files downloaded without problems, thank you!

Any ideas why the check algorithm works so strangely?

**Comment by OzzieIsaacs** [comment]
MY fault, on windows you need to install a additional library, called libmagic, you can find it here (https://github.com/nscaife/file-windows/releases/tag/20170108) for 64bit python or here (https://gnuwin32.sourceforge.net/downlinks/file.php) for 32bit python. The files need to be installed in path (e.g. script folder of your calibre-web venv, or in the root folder of calibre-web

**Comment by ikwyl6** [comment]
Came here with the magicexception.. Did:
`$ pip install libmagic` within my `venv` and all worked...Had to restart cps binary. thanks.

```
[2024-12-12 00:23:30,694]  INFO {flask_wtf.csrf:263} The CSRF token has expired.
[2024-12-12 00:24:07,500]  INFO {tornado.general:294} Malformed HTTP message from 192.168.4.1: Content-Length too long
[2024-12-12 00:24:31,821] ERROR {cps:1414} Exception on /upload [POST]
Traceback (most recent call last):
  File "/home/alarm/dev/venv/lib/python3.12/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alarm/dev/venv/lib/python3.12/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alarm/dev/venv/lib/python3.12/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alarm/dev/venv/lib/python3.12/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alarm/dev/venv/lib/python3.12/site-packages/calibreweb/cps/usermanagement.py", line 97, in decorated_view
    return login_required(func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alarm/dev/venv/lib/python3.12/site-packages/calibreweb/cps/cw_login/utils.py", line 296, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alarm/dev/venv/lib/python3.12/site-packages/calibreweb/cps/editbooks.py", line 60, in inner
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/alarm/dev/venv/lib/python3.12/site-packages/calibreweb/cps/editbooks.py", line 251, in upload
    meta, error = file_handling_on_upload(requested_file)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alarm/dev/venv/lib/python3.12/site-packages/calibreweb/cps/editbooks.py", line 761, in file_handling_on_upload
    if not validate_mime_type(requested_file, allowed_extensions):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alarm/dev/venv/lib/python3.12/site-packages/calibreweb/cps/file_helper.py", line 53, in validate_mime_type
    mime = magic.Magic(mime=True)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alarm/dev/venv/lib/python3.12/site-packages/magic/__init__.py", line 73, in __init__
    magic_load(self.cookie, magic_file)
  File "/home/alarm/dev/venv/lib/python3.12/site-packages/magic/__init__.py", line 332, in magic_load
    return _magic_load(cookie, coerce_filename(filename))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alarm/dev/venv/lib/python3.12/site-packages/magic/__init__.py", line 225, in errorcheck_negative_one
    raise MagicException(err)
magic.MagicException: b"File 5.45 supports only version 18 magic files. `/usr/share/file/misc/magic.mgc' is version 20"
[2024-12-12 00:25:35,101] ERROR {cps:1414} Exception on /upload [POST]
Traceback (most recent call last):
  File "/home/alarm/dev/venv/lib/python3.12/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alarm/dev/venv/lib/python3.12/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alarm/dev/venv/lib/python3.12/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alarm/dev/venv/lib/python3.12/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alarm/dev/venv/lib/python3.12/site-packages/calibreweb/cps/usermanagement.py", line 97, in decorated_view
    return login_required(func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alarm/dev/venv/lib/python3.12/site-packages/calibreweb/cps/cw_login/utils.py", line 296, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alarm/dev/venv/lib/python3.12/site-packages/calibreweb/cps/editbooks.py", line 60, in inner
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/alarm/dev/venv/lib/python3.12/site-packages/calibreweb/cps/editbooks.py", line 251, in upload
    meta, error = file_handling_on_upload(requested_file)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alarm/dev/venv/lib/python3.12/site-
packages/calibreweb/cps/editbooks.py", line 761, in file_handling_on_upload
    if not validate_mime_type(requested_file, allowed_extensions):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alarm/dev/venv/lib/python3.12/site-packages/calibreweb/cps/file_helper.py", line 53, in validate_mime_type
    mime = magic.Magic(mime=True)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alarm/dev/venv/lib/python3.12/site-packages/magic/__init__.py", line 73, in __init__
    magic_load(self.cookie, magic_file)
  File "/home/alarm/dev/venv/lib/python3.12/site-packages/magic/__init__.py", line 332, in magic_load
    return _magic_load(cookie, coerce_filename(filename))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alarm/dev/venv/lib/python3.12/site-packages/magic/__init__.py", line 225, in errorcheck_negative_one
    raise MagicException(err)
magic.MagicException: b"File 5.45 supports only version 18 magic files. `/usr/share/file/misc/magic.mgc' is version 20"
```
