### ISSUE TITLE
Internal Server Error on loading metadata from douban

### ISSUE THREAD

**Issue by shawnzhou1120** [janeczku/calibre-web#311]
more issue i met today.
i installed the calibre-web in my DSM(Synology NAS) docker.it work well in the morning.but there are some big errors at night.
1.it show me there are no writer permission when i upload the books,but i set the local folders are RW permission when i install the docker calibre-web,and it work well this morning.i dont kown what is the problem. i try to restart the docker,or del it,re-intall the calibre-web,but the issue still be here.
2.i set the folders to RW permisson by manual.and it work again.but a more issue is here after i upload 2 books.1time,i upload 1 book and save it,it work well.but the web shown me "Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application." after i upload the 2nd books,get the info from douban/google,and click save.
following is the docker log :
"
::ffff:172.17.0.1 - - [2017-09-05 14:31:23] "GET /cover/Unknown/CYu%20Yan%20Ru%20Men%20Jing%20Dian%20Di%20Wu%20Ban HTTP/1.1" 200 983724 0.043828 
::ffff:172.17.0.1 - - [2017-09-05 14:31:23] "GET /static/js/libs/bootstrap-datepicker/locales/bootstrap-datepicker.zh_Hans_CN.min.js HTTP/1.1" 404 342 0.0
::ffff:172.17.0.1 - - [2017-09-05 14:31:27] "GET /static/generic_cover.jpg HTTP/1.1" 200 182867 0.008884 
::ffff:172.17.0.1 - - [2017-09-05 14:31:49] "GET /upload?q=68b0891/get_series_json?q=%E5%B7%A5%E5%85%B7%E4%B9%A6 HTTP/1.1" 302 364 0.010543 
::ffff:172.17.0.1 - - [2017-09-05 14:31:49] "GET / HTTP/1.1" 200 17227 0.201936 
::ffff:172.17.0.1 - - [2017-09-05 14:31:58] "GET /upload?q=68b0891/get_languages_json?q=%E4%B8%AD%E6%96%87 HTTP/1.1" 302 364 0.010515 
::ffff:172.17.0.1 - - [2017-09-05 14:31:58] "GET / HTTP/1.1" 200 17176 0.203421 
[2017-09-05 14:32:12,350] ERROR in app: Exception on /admin/book/21 [POST] 
Traceback (most recent call last): 
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app 
    response = self.full_dispatch_request() 
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request 
    rv = self.handle_user_exception(e) 
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception 
    reraise(exc_type, exc_value, tb) 
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request 
    rv = self.dispatch_request() 
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request 
    return self.view_functions[rule.endpoint](**req.view_args) 
  File "/usr/lib/python2.7/site-packages/flask_login/utils.py", line 228, in decorated_view 
    return func(*args, **kwargs) 
  File "/calibre-web/app/cps/web.py", line 509, in inner 
    return f(*args, **kwargs) 
  File "/calibre-web/app/cps/web.py", line 2883, in edit_book 
    db.session.commit() 
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 906, in commit 
    self.transaction.commit() 
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 461, in commit 
    self._prepare_impl() 
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 441, in _prepare_impl 
    self.session.flush() 
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2171, in flush 
    self._flush(objects) 
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2291, in _flush 
“

**Comment by roly445** [comment]
I'm having a similar issue, I'm running on docker.

**Comment by shawnzhou1120** [comment]
i think it should be the issue( get medata from douban).
i try it again and again.and found.most time ,i choose get medata from douban ,the system will be broken.and show me the "Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application".

**Comment by eko133** [comment]
I am having a similar issue, running on docker as well

**Comment by jkrehm** [comment]
In `static/js/get_meta.js` could you add the following to line 106
```
                if (book.rating > 0) {
                    book.rating /= 2;
                }
```
and try. Doing that fixed the issue for me. Douban's ratings are 0-10 and Calibre's database appears to have a constraint of 0-5. If that's the only problem that needs fixed, I'll submit a PR with it.

**Comment by xieyangwanmu** [comment]
I have a  issue, 


[2017-09-12 13:58:53,649] ERROR in app: Exception on /admin/book/10202 [POST]
Traceback (most recent call last):
  File "/home/wwwroot/calibre/vendor/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/wwwroot/calibre/vendor/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/wwwroot/calibre/vendor/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/wwwroot/calibre/vendor/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/wwwroot/calibre/vendor/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/wwwroot/calibre/cps/web.py", line 509, in inner
    return f(*args, **kwargs)
  File "/home/wwwroot/calibre/cps/web.py", line 2746, in edit_book
    if to_save["cover_url"] and save_cover(to_save["cover_url"], book.path):
  File "/home/wwwroot/calibre/cps/web.py", line 2899, in save_cover
    img = requests.get(url)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 55, in get
    return request('get', url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 44, in request
    return session.request(method=method, url=url, **kwargs)
  
File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 455, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 558, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 385, in send
    raise SSLError(e)
**SSLError: hostname 'img3.doubanio.com' doesn't match '*.ucdl.pp.uc.cn'**
::ffff:172.21.227.226 - - [2017-09-12 13:58:53] "POST /calibre-web/admin/book/10202 HTTP/1.0" 500 431 0.036440

**Comment by jkrehm** [comment]
That last error looks like some DNS issue or something. Not to say the application shouldn't catch such things (instead of producing a 500 error) but I don't think the issue is within the application.
