### ISSUE TITLE
Delete this Shelf error

### ISSUE THREAD

**Issue by xxyyer** [janeczku/calibre-web#318]
**When I delete shelf:**

Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

**server err:**
[2017-09-11 20:17:50,656] ERROR in app: Exception on /shelf/delete/2 [GET]
Traceback (most recent call last):
  File "/home/xxy/calibre-web/build/calibre-web/vendor/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/xxy/calibre-web/build/calibre-web/vendor/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/xxy/calibre-web/build/calibre-web/vendor/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/xxy/calibre-web/build/calibre-web/vendor/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/xxy/calibre-web/build/calibre-web/vendor/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/xxy/calibre-web/build/calibre-web/vendor/flask_login/utils.py", line 228, in decorated_view
    return func(*args, **kwargs)
  File "/home/xxy/calibre-web/build/calibre-web/cps/web.py", line 2150, in delete_shelf
    if deleted:
UnboundLocalError: local variable 'deleted' referenced before assignment
ERROR:tornado.access:500 GET /shelf/delete/2 (14.16.39.104) 5.18ms

**Comment by xxyyer** [comment]
think you jkrehm 

 @login_required
  def delete_shelf(shelf_id):
      cur_shelf = ub.session.query(ub.Shelf).filter(ub.Shelf.id == shelf_id).first()
 +    **deleted = false**
      if current_user.role_admin():
          deleted = ub.session.query(ub.Shelf).filter(ub.Shelf.id == shelf_id).delete()
      else:

**Comment by xxyyer** [comment]
There's nothing error output with your changes, but can't really delete shelf.

**Comment by fuchst** [comment]
Maybe you could try the second change in this commit:
https://github.com/fuchst/calibre-web/commit/db9523c2741647d52e4f0875f6547c749cc726a4

**Comment by xxyyer** [comment]
The problem is solved, thank you!

@ e174d51d2460b2d3e194da80f087b069cd17edd6
