### ISSUE TITLE
500 Internal Server Error - KeyError: 'tag_name'

### ISSUE THREAD

**Issue by w473** [janeczku/calibre-web#3185]
**Describe the bug/problem** 

Happened after multiple edits of book metadata - fetching it from website and just saving. Now whole calibre-web is broken - same error on all request. Restart doesn't help. Library check from Calibre show all is fine.

**Logfile**

calibre-web.log shows same error as in frontend

`Traceback (most recent call last):
File "/lsiopy/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
response = self.full_dispatch_request()
File "/lsiopy/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/lsiopy/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
rv = self.dispatch_request()
File "/lsiopy/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
File "/app/calibre-web/cps/usermanagement.py", line 35, in decorated_view
return login_required(func)(*args, **kwargs)
File "/lsiopy/lib/python3.10/site-packages/flask_login/utils.py", line 290, in decorated_view
return current_app.ensure_sync(func)(*args, **kwargs)
File "/app/calibre-web/cps/web.py", line 1642, in show_book
return render_title_template('detail.html',
File "/app/calibre-web/cps/render_template.py", line 153, in render_title_template
cwa_update_notification()
File "/app/calibre-web/cps/render_template.py", line 141, in cwa_update_notification
update_available, current_verision, tag_name = cwa_update_available()
File "/app/calibre-web/cps/render_template.py", line 119, in cwa_update_available
tag_name = response.json()['tag_name']
KeyError: 'tag_name'`
**Expected behavior**

No error :)

**Environment (please complete the following information):**

 - Docker container: [None/LinuxServer]: crocodilestick/calibre-web-automated:latest
 - Browser: unrelated

**Comment by fitim7** [comment]
Traceback (most recent call last):
File "/lsiopy/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
response = self.full_dispatch_request()
File "/lsiopy/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/lsiopy/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
rv = self.dispatch_request()
File "/lsiopy/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
File "/app/calibre-web/cps/usermanagement.py", line 35, in decorated_view
return login_required(func)(*args, **kwargs)
File "/lsiopy/lib/python3.10/site-packages/flask_login/utils.py", line 290, in decorated_view
return current_app.ensure_sync(func)(*args, **kwargs)
File "/app/calibre-web/cps/web.py", line 806, in index
return render_books_list("newest", sort_param, 1, page)
File "/app/calibre-web/cps/web.py", line 417, in render_books_list
return render_title_template('index.html', random=random, entries=entries, pagination=pagination,
File "/app/calibre-web/cps/render_template.py", line 153, in render_title_template
cwa_update_notification()
File "/app/calibre-web/cps/render_template.py", line 141, in cwa_update_notification
update_available, current_verision, tag_name = cwa_update_available()
File "/app/calibre-web/cps/render_template.py", line 119, in cwa_update_available
tag_name = response.json()['tag_name']
KeyError: 'tag_name'

I have exactlw the same error ...
