### ISSUE TITLE
Smtplib Error

### ISSUE THREAD

**Issue by itchygrub** [janeczku/calibre-web#3202]
## Short Notice from the maintainer 

After 6 years of more or less intensive programming on Calibre-Web, I need a break. 
The last few months, maintaining Calibre-Web has felt more like work than a hobby. I felt pressured and teased by people to solve "their" problems and merge PRs for "their" Calibre-Web. 
I have turned off all notifications from Github/Discord and will now concentrate undisturbed on the development of “my” Calibre-Web over the next few weeks/months.  
I will look into the issues and maybe also the PRs from time to time, but don't expect a quick response from me.

Please also have a look at our [Contributing Guidelines](https://github.com/janeczku/calibre-web/blob/master/CONTRIBUTING.md)

**Describe the bug/problem** 
Trying to set email server settings
Used IMAP and POP3.

A clear and concise description of what the bug is. If you are asking for support, please check our [Wiki](https://github.com/janeczku/calibre-web/wiki) if your question is already answered there.

**To Reproduce**

**Logfile**
tail -100 cweb1.log
[2024-10-25 04:00:00,001]  INFO {apscheduler.executors.default:123} Running job "delete temp (trigger: cron[hour='4'], next run at: 2024-10-26 04:00:00 AEDT)" (scheduled at 2024-10-25 04:00:00+11:00)
[2024-10-25 04:00:00,003] DEBUG {cps.services.worker:91} Add Task for user: System - Clean up
[2024-10-25 04:00:00,003]  INFO {apscheduler.executors.default:144} Job "delete temp (trigger: cron[hour='4'], next run at: 2024-10-26 04:00:00 AEDT)" executed successfully
[2024-10-25 04:00:00,845] DEBUG {cps.tasks.clean:43} Deleted expired session_keys
[2024-10-25 04:10:00,001]  INFO {apscheduler.executors.default:123} Running job "end scheduled task (trigger: cron[hour='4', minute='10'], next run at: 2024-10-26 04:10:00 AEDT)" (scheduled at 2024-10-25 04:10:00+11:00)
[2024-10-25 04:10:00,001]  INFO {apscheduler.executors.default:144} Job "end scheduled task (trigger: cron[hour='4', minute='10'], next run at: 2024-10-26 04:10:00 AEDT)" executed successfully
[2024-10-26 04:00:00,001]  INFO {apscheduler.executors.default:123} Running job "delete temp (trigger: cron[hour='4'], next run at: 2024-10-27 04:00:00 AEDT)" (scheduled at 2024-10-26 04:00:00+11:00)
[2024-10-26 04:00:00,002] DEBUG {cps.services.worker:91} Add Task for user: System - Clean up
[2024-10-26 04:00:00,003]  INFO {apscheduler.executors.default:144} Job "delete temp (trigger: cron[hour='4'], next run at: 2024-10-27 04:00:00 AEDT)" executed successfully
[2024-10-26 04:00:00,003] DEBUG {cps.tasks.clean:43} Deleted expired session_keys
[2024-10-26 04:10:00,001]  INFO {apscheduler.executors.default:123} Running job "end scheduled task (trigger: cron[hour='4', minute='10'], next run at: 2024-10-27 04:10:00 AEDT)" (scheduled at 2024-10-26 04:10:00+11:00)
[2024-10-26 04:10:00,002]  INFO {apscheduler.executors.default:144} Job "end scheduled task (trigger: cron[hour='4', minute='10'], next run at: 2024-10-27 04:10:00 AEDT)" executed successfully
[2024-10-26 16:02:42,711] DEBUG {cps.config_sql:388} _ConfigSQL updating storage
[2024-10-26 16:02:42,722] DEBUG {cps.services.worker:91} Add Task for user: admin - E-mail E-mail, Calibre-Web Test Email
[2024-10-26 16:02:43,440] DEBUG {cps.tasks.mail:197} Start sending e-mail
[2024-10-26 16:02:43,783] ERROR {cps.tasks.mail:175} (-1, b'[CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE NAMESPACE LITERAL+ AUTH=PLAIN AUTH=LOGIN] Dovecot ready.')
Traceback (most recent call last):
  File "/calibre-web/cps/tasks/mail.py", line 168, in run
    self.send_standard_email(msg)
  File "/calibre-web/cps/tasks/mail.py", line 200, in send_standard_email
    self.asyncSMTP = EmailSSL(self.settings["mail_server"], self.settings["mail_port"],
  File "/calibre-web/cps/tasks/mail.py", line 109, in __init__
    smtplib.SMTP_SSL.__init__(self, *args, **kwargs)
  File "/usr/lib/python3.10/smtplib.py", line 1050, in __init__
    SMTP.__init__(self, host, port, local_hostname, timeout,
  File "/usr/lib/python3.10/smtplib.py", line 258, in __init__
    raise SMTPConnectError(code, msg)
smtplib.SMTPConnectError: (-1, b'[CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE NAMESPACE LITERAL+ AUTH=PLAIN AUTH=LOGIN] Dovecot ready.')
[2024-10-26 16:13:29,732] DEBUG {cps.updater:331} Stable version: {'version': '0.6.24b'}
[2024-10-26 16:15:36,962] DEBUG {cps.config_sql:388} _ConfigSQL updating storage
[2024-10-26 16:15:36,973] DEBUG {cps.services.worker:91} Add Task for user: admin - E-mail E-mail, Calibre-Web Test Email
[2024-10-26 16:15:36,977] DEBUG {cps.tasks.mail:197} Start sending e-mail
[2024-10-26 16:15:37,354] ERROR {cps.tasks.mail:175} (-1, b'[CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE NAMESPACE LITERAL+ AUTH=PLAIN AUTH=LOGIN] Dovecot ready.')
Traceback (most recent call last):
  File "/calibre-web/cps/tasks/mail.py", line 168, in run
    self.send_standard_email(msg)
  File "/calibre-web/cps/tasks/mail.py", line 200, in send_standard_email
    self.asyncSMTP = EmailSSL(self.settings["mail_server"], self.settings["mail_port"],
  File "/calibre-web/cps/tasks/mail.py", line 109, in __init__
    smtplib.SMTP_SSL.__init__(self, *args, **kwargs)
  File "/usr/lib/python3.10/smtplib.py", line 1050, in __init__
    SMTP.__init__(self, host, port, local_hostname, timeout,
  File "/usr/lib/python3.10/smtplib.py", line 258, in __init__
    raise SMTPConnectError(code, msg)
smtplib.SMTPConnectError: (-1, b'[CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE NAMESPACE LITERAL+ AUTH=PLAIN AUTH=LOGIN] Dovecot ready.')
[2024-10-26 16:16:02,399] DEBUG {cps.updater:331} Stable version: {'version': '0.6.24b'}
[2024-10-26 16:17:38,256] DEBUG {cps.config_sql:388} _ConfigSQL updating storage
[2024-10-26 16:17:38,267] DEBUG {cps.services.worker:91} Add Task for user: admin - E-mail E-mail, Calibre-Web Test Email
[2024-10-26 16:17:38,271] DEBUG {cps.tasks.mail:197} Start sending e-mail
[2024-10-26 16:17:38,525] ERROR {cps.tasks.mail:175} (-1, b'Dovecot ready.')
Traceback (most recent call last):
  File "/calibre-web/cps/tasks/mail.py", line 168, in run
    self.send_standard_email(msg)
  File "/calibre-web/cps/tasks/mail.py", line 200, in send_standard_email
    self.asyncSMTP = EmailSSL(self.settings["mail_server"], self.settings["mail_port"],
  File "/calibre-web/cps/tasks/mail.py", line 109, in __init__
    smtplib.SMTP_SSL.__init__(self, *args, **kwargs)
  File "/usr/lib/python3.10/smtplib.py", line 1050, in __init__
    SMTP.__init__(self, host, port, local_hostname, timeout,
  File "/usr/lib/python3.10/smtplib.py", line 258, in __init__
    raise SMTPConnectError(code, msg)
smtplib.SMTPConnectError: (-1, b'Dovecot ready.')
[2024-10-26 16:22:01,508] DEBUG {cps.updater:331} Stable version: {'version': '0.6.24b'}
[2024-10-26 16:31:01,696] DEBUG {cps.updater:331} Stable version: {'version': '0.6.24b'}
[2024-10-26 16:36:30,212] DEBUG {cps.updater:331} Stable version: {'version': '0.6.24b'}
[2024-10-26 16:36:48,043] DEBUG {cps.config_sql:388} _ConfigSQL updating storage
[2024-10-26 16:36:48,046] DEBUG {cps.services.worker:91} Add Task for user: admin - E-mail E-mail, Calibre-Web Test Email
[2024-10-26 16:36:48,051] DEBUG {cps.tasks.mail:197} Start sending e-mail
[2024-10-26 16:36:48,406] ERROR {cps.tasks.mail:175} (-1, b'Dovecot ready.')
Traceback (most recent call last):
  File "/calibre-web/cps/tasks/mail.py", line 168, in run
    self.send_standard_email(msg)
  File "/calibre-web/cps/tasks/mail.py", line 200, in send_standard_email
    self.asyncSMTP = EmailSSL(self.settings["mail_server"], self.settings["mail_port"],
  File "/calibre-web/cps/tasks/mail.py", line 109, in __init__
    smtplib.SMTP_SSL.__init__(self, *args, **kwargs)
  File "/usr/lib/python3.10/smtplib.py", line 1050, in __init__
    SMTP.__init__(self, host, port, local_hostname, timeout,
  File "/usr/lib/python3.10/smtplib.py", line 258, in __init__
    raise SMTPConnectError(code, msg)
smtplib.SMTPConnectError: (-1, b'Dovecot ready.')
[2024-10-26 16:37:04,951] DEBUG {cps.updater:331} Stable version: {'version': '0.6.24b'}
[2024-10-26 16:37:42,223] DEBUG {cps.updater:331} Stable version: {'version': '0.6.24b'}
[2024-10-26 16:37:50,108] DEBUG {cps.config_sql:388} _ConfigSQL updating storage
[2024-10-26 16:37:50,111] DEBUG {cps.services.worker:91} Add Task for user: admin - E-mail E-mail, Calibre-Web Test Email
[2024-10-26 16:37:50,459] DEBUG {cps.tasks.mail:197} Start sending e-mail
[2024-10-26 16:37:50,601] ERROR {cps.tasks.mail:175} (-1, b'Dovecot ready.')
Traceback (most recent call last):
  File "/calibre-web/cps/tasks/mail.py", line 168, in run
    self.send_standard_email(msg)
  File "/calibre-web/cps/tasks/mail.py", line 200, in send_standard_email
    self.asyncSMTP = EmailSSL(self.settings["mail_server"], self.settings["mail_port"],
  File "/calibre-web/cps/tasks/mail.py", line 109, in __init__
    smtplib.SMTP_SSL.__init__(self, *args, **kwargs)
  File "/usr/lib/python3.10/smtplib.py", line 1050, in __init__
    SMTP.__init__(self, host, port, local_hostname, timeout,
  File "/usr/lib/python3.10/smtplib.py", line 258, in __init__
    raise SMTPConnectError(code, msg)
smtplib.SMTPConnectError: (-1, b'Dovecot ready.')
[2024-10-26 16:41:10,727] DEBUG {cps.updater:331} Stable version: {'version': '0.6.24b'}

**Expected behavior**

Able to have email

**Screenshots**

![Ashampoo_Snap_Saturday, October 26, 2024_16h38m34s](https://github.com/user-attachments/assets/924a3b47-1cbf-41eb-8d1f-f59b4b82dbea)

**Environment (please complete the following information):**

 - OS: Ubuntu 22.04
 - Python version: python 3.10
 - Calibre-Web version: 0.6.24 Beta
 - Docker container: Proxmox Conatiner
 - Special Hardware: Mini PC
 - Browser: Brave and Chrome

**Additional context**
Add any other context about the problem here. [e.g. access via reverse proxy, database background sync, special database location]

**Comment by OzzieIsaacs** [comment]
> Used IMAP and POP3.

As all text on the config page indicate you need a "SMTP server" to send email (not POP3 not IMAP).

**Comment by itchygrub** [comment]
First error IMAP Port 993
Second error POP3 Port 995
Used smtp server associated with my domain name

**Comment by OzzieIsaacs** [comment]
Sorry, this response is so vague, as the first post. 

I had cases like this in the past, it's for me like pulling blood out of a stone. I'm not doing this anymore.  This makes absolutely no sense for me to response to this. Please google by yourself "dovecoat smtp"

**Comment by itchygrub** [comment]
Sorry
I have used this program before.
When I setup the email using the same email configuration settings using my own hosted email configuration details it worked straight a way.
The first errors were from the using the IMAP configuration details or setting up email clients
The second error were from the POP3 configuration details for setting up email clients
SMTP - IMAP
mail.****.net
Port 993
SMTP - POP3
mail.****.net
Port 995
