### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by mahmoudsalem91** [janeczku/calibre-web#3207]
**Describe the bug/problem** 

I wanted to update metadata of a book. pressed edit and then "Fetch metadata". Found a match and choosed then i got the following error when i pressed Save button.

**Expected behavior**

Should have saved the information and returned to the Book again.

**Screenshots**

![image](https://github.com/user-attachments/assets/c760b836-fa04-47a6-b355-950436a12113)

**Environment (please complete the following information):**

 - OS: Ubuntu latest
 - Python version: Docker version installed
 - Calibre-Web version: Latest docker
 - Docker container: LinuxServer
 - Special Hardware: Desktop computer
 - Browser: Version 130.0.6723.70 (Officiell version) (64 bit)

**Error**

500 Internal Server Error
The server encountered an internal error and was unable to complete your request. There is an error in the application.
Traceback (most recent call last):
File "/lsiopy/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
self.dialect.do_execute(
File "/lsiopy/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 941, in do_execute
cursor.execute(statement, parameters)
sqlite3.InterfaceError: Cursor needed to be reset because of commit/rollback and can no longer be fetched from.
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "/app/calibre-web/cps/editbooks.py", line 171, in edit_book
modification, warning = modify_identifiers(input_identifiers, book.identifiers, calibre_db.session)
File "/lsiopy/lib/python3.10/site-packages/sqlalchemy/orm/attributes.py", line 566, in __get__
return self.impl.get(state, dict_) # type: ignore[no-any-return]
File "/lsiopy/lib/python3.10/site-packages/sqlalchemy/orm/attributes.py", line 1086, in get
value = self._fire_loader_callables(state, key, passive)
File "/lsiopy/lib/python3.10/site-packages/sqlalchemy/orm/attributes.py", line 1121, in _fire_loader_callables
return self.callable_(state, passive)
File "/lsiopy/lib/python3.10/site-packages/sqlalchemy/orm/strategies.py", line 978, in _load_for_state
return self._emit_lazyload(
File "/lsiopy/lib/python3.10/site-packages/sqlalchemy/orm/strategies.py", line 1141, in _emit_lazyload
result = session.execute(
File "/lsiopy/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2362, in execute
return self._execute_internal(
File "/lsiopy/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2247, in _execute_internal
result: Result[Any] = compile_state_cls.orm_execute_statement(
File "/lsiopy/lib/python3.10/site-packages/sqlalchemy/orm/context.py", line 305, in orm_execute_statement
result = conn.execute(
File "/lsiopy/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1418, in execute
return meth(
File "/lsiopy/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 515, in _execute_on_connection
return connection._execute_clauseelement(
File "/lsiopy/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1640, in _execute_clauseelement
ret = self._execute_context(
File "/lsiopy/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1846, in _execute_context
return self._exec_single_context(
File "/lsiopy/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1986, in _exec_single_context
self._handle_dbapi_exception(
File "/lsiopy/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2355, in _handle_dbapi_exception
raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
File "/lsiopy/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
self.dialect.do_execute(
File "/lsiopy/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 941, in do_execute
cursor.execute(statement, parameters)
sqlalchemy.exc.InterfaceError: (sqlite3.InterfaceError) Cursor needed to be reset because of commit/rollback and can no longer be fetched from.
[SQL: SELECT identifiers.id AS identifiers_id, identifiers.type AS identifiers_type, identifiers.val AS identifiers_val, identifiers.book AS identifiers_book
FROM identifiers
WHERE ? = identifiers.book]
[parameters: (83,)]
(Background on this error at: https://sqlalche.me/e/20/rvf5)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/lsiopy/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1127, in _rollback_impl
self.engine.dialect.do_rollback(self.connection)
File "/lsiopy/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 699, in do_rollback
dbapi_connection.rollback()
sqlite3.OperationalError: cannot rollback - no transaction is active
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "/lsiopy/lib/python3.10/site-packages/flask/app.py", line 1473, in wsgi_app
response = self.full_dispatch_request()
File "/lsiopy/lib/python3.10/site-packages/flask/app.py", line 882, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/lsiopy/lib/python3.10/site-packages/flask/app.py", line 880, in full_dispatch_request
rv = self.dispatch_request()
File "/lsiopy/lib/python3.10/site-packages/flask/app.py", line 865, in dispatch_request
return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args) # type: ignore[no-any-return]
File "/app/calibre-web/cps/usermanagement.py", line 97, in decorated_view
return login_required(func)(*args, **kwargs)
File "/app/calibre-web/cps/cw_login/utils.py", line 296, in decorated_view
return current_app.ensure_sync(func)(*args, **kwargs)
File "/app/calibre-web/cps/editbooks.py", line 70, in inner
return f(*args, **kwargs)
File "/app/calibre-web/cps/editbooks.py", line 227, in edit_book
calibre_db.session.rollback()
File "/lsiopy/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1990, in rollback
self._transaction.rollback(_to_root=True)
File "<string>", line 2, in rollback
File "/lsiopy/lib/python3.10/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
ret_value = fn(self, *arg, **kw)
File "/lsiopy/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1395, in rollback
raise rollback_err[1].with_traceback(rollback_err[2])
File "/lsiopy/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1360, in rollback
t[1].rollback()
File "/lsiopy/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2610, in rollback
self._do_rollback()
File "/lsiopy/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2729, in _do_rollback
self._close_impl(try_deactivate=True)
File "/lsiopy/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2712, in _close_impl
self._connection_rollback_impl()
File "/lsiopy/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2704, in _connection_rollback_impl
self.connection._rollback_impl()
File "/lsiopy/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1129, in _rollback_impl
self._handle_dbapi_exception(e, None, None, None, None)
File "/lsiopy/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2355, in _handle_dbapi_exception
raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
File "/lsiopy/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1127, in _rollback_impl
self.engine.dialect.do_rollback(self.connection)
File "/lsiopy/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 699, in do_rollback
dbapi_connection.rollback()
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) cannot rollback - no transaction is active
(Background on this error at: https://sqlalche.me/e/20/e3q8)

**Comment by zisco67** [comment]
Similar issue here:
```
Calibre-Web
500 Internal Server Error
The server encountered an internal error and was unable to complete your request. There is an error in the application.
Traceback (most recent call last):
File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 2073, in wsgi_app
response = self.full_dispatch_request()
File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1519, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1517, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1503, in dispatch_request
return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
File "/usr/local/lib/python3.9/dist-packages/calibreweb/cps/usermanagement.py", line 35, in decorated_view
return login_required(func)(*args, **kwargs)
File "/usr/local/lib/python3.9/dist-packages/flask_login/utils.py", line 290, in decorated_view
return current_app.ensure_sync(func)(*args, **kwargs)
File "/usr/local/lib/python3.9/dist-packages/calibreweb/cps/web.py", line 790, in index
return render_books_list("newest", sort_param, 1, page)
File "/usr/local/lib/python3.9/dist-packages/calibreweb/cps/web.py", line 408, in render_books_list
entries, random, pagination = calibre_db.fill_indexpage(page, 0, db.Books, True, order[0],
File "/usr/local/lib/python3.9/dist-packages/calibreweb/cps/db.py", line 803, in fill_indexpage
return self.fill_indexpage_with_archived_books(page, database, pagesize, db_filter, order, False,
File "/usr/local/lib/python3.9/dist-packages/calibreweb/cps/db.py", line 810, in fill_indexpage_with_archived_books
random_query = self.generate_linked_query(config_read_column, database)
File "/usr/local/lib/python3.9/dist-packages/calibreweb/cps/db.py", line 764, in generate_linked_query
query = (self.session.query(database, ub.ArchivedBook.is_archived, ub.ReadBook.read_status)
AttributeError: 'NoneType' object has no attribute 'query'
```
metadata.db seems to be in almost stable condition and is not locked:
```
sqlite3 metadata.db "PRAGMA integrity_check;"
*** in database main ***
Page 1970 is never used
row 110 missing from index sqlite_autoindex_metadata_dirtied_1
wrong # of entries in index sqlite_autoindex_metadata_dirtied_1
wrong # of entries in index books_idx
wrong # of entries in index authors_idx
```
Any ideas? THX!

**Comment by zisco67** [comment]
After another reboot if my Calibre-Web proxmox-LXC all systems are up!

**Comment by limeade23** [comment]
Hello,

I'm experiencing similar issues when modifying metadata as well.
However, since the system hangs without receiving a response, I couldn't check the logs. 
(I had to force restart afterwards)

Additionally, when changing metadata, if you modify the author name or book title, although the folder name changes, these changes aren't reflected in the DB, resulting in books becoming unfindable.

I think  
Restore the folder to its original state when an error occurs, or  
Try moving directories only after all DB operations are complete

This issue occurs intermittently...


1. before metadata modification
<img width="595" alt="스크린샷 2024-11-04 오전 1 46 31" src="https://github.com/user-attachments/assets/c4ac13ac-8f60-4fce-9c10-5602b8caa135">

2. File path before changes
<img width="376" alt="스크린샷 2024-11-04 오전 1 45 59" src="https://github.com/user-attachments/assets/ce487d97-a891-4fad-8a87-c7c194036823">

3.  after metadata modification and Calibre-Web restart due to error
<img width="1080" alt="스크린샷 2024-11-04 오전 1 44 57" src="https://github.com/user-attachments/assets/51d99a53-b510-48dc-a1f4-1578c8650524">

4. File path after changes
<img width="376" alt="스크린샷 2024-11-04 오전 1 43 22" src="https://github.com/user-attachments/assets/59089376-e7c8-4e3e-8f12-13804e211036">

**Comment by OzzieIsaacs** [comment]
Typically docker problems, caused by permission problems
