### ISSUE TITLE
upload 200MB/400MB pdf file error

### ISSUE THREAD

**Issue by xxyyer** [janeczku/calibre-web#322]
# **When I uploaded the 200MB size PDF file.**

**browser:**
Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

**server (in docker):**
calibre-web_1  | 2017-09-13 02:33:58,689 DEBG 'nginx' stderr output:
calibre-web_1  | 2017/09/13 02:33:58 [warn] 31#31: *1 a client request body is buffered to a temporary file /data/tmp/nginx/client_temp/1/00/0000000001, client: 172.22.200.19, server: , request: "POST /upload HTTP/1.1", host: "172.22.200.12:8083", referrer: "http://172.22.200.12:8083/"
calibre-web_1  |
calibre-web_1  |    **** Missing whitespace after 'endobj'.
calibre-web_1  | 2017-09-13 02:34:33,647 DEBG 'root' stdout output:
calibre-web_1  |    **** Missing whitespace after 'endobj'.
calibre-web_1  |
calibre-web_1  |    **** Missing whitespace after 'endobj'.
calibre-web_1  |    **** Missing whitespace after 'endobj'.
calibre-web_1  | 2017-09-13 02:34:33,648 DEBG 'root' stdout output:
calibre-web_1  |    **** Missing whitespace after 'endobj'.
calibre-web_1  |    **** Missing whitespace after 'endobj'.
......................
...........................
......................
...........................
......................
...........................repeat..................
......................
...........................
......................
...........................
calibre-web_1  |
calibre-web_1  |    **** Missing whitespace after 'endobj'.
calibre-web_1  | 2017-09-13 02:34:33,686 DEBG 'root' stdout output:
calibre-web_1  |    **** Missing whitespace after 'endobj'.
calibre-web_1  |
calibre-web_1  |
calibre-web_1  |    **** This file had errors that were repaired or ignored.
calibre-web_1  | 2017-09-13 02:34:34,325 DEBG 'root' stdout output:
calibre-web_1  |
calibre-web_1  |    **** This file had errors that were repaired or ignored.
calibre-web_1  |
calibre-web_1  |    **** The file was produced by:
calibre-web_1  |    **** >>>> FreePic2Pdf_Lib - 2.10 <<<<
calibre-web_1  |    **** Please notify the author of the software that produced this
calibre-web_1  |    **** file that it does not conform to Adobe's published PDF
calibre-web_1  |    **** specification.
calibre-web_1  |
calibre-web_1  | 2017-09-13 02:34:34,325 DEBG 'root' stdout output:
calibre-web_1  |    **** The file was produced by:
calibre-web_1  |    **** >>>> FreePic2Pdf_Lib - 2.10 <<<<
calibre-web_1  |    **** Please notify the author of the software that produced this
calibre-web_1  |    **** file that it does not conform to Adobe's published PDF
calibre-web_1  |    **** specification.
calibre-web_1  |
calibre-web_1  |
calibre-web_1  | [2017-09-13 02:34:34,412] ERROR in app: Exception on /upload [POST]
calibre-web_1  | Traceback (most recent call last):
calibre-web_1  |   File "/usr/lib/python2.7/site-packages/Flask-0.12.2-py2.7.egg/flask/app.py", line 1982, in wsgi_app
calibre-web_1  |     response = self.full_dispatch_request()
calibre-web_1  |   File "/usr/lib/python2.7/site-packages/Flask-0.12.2-py2.7.egg/flask/app.py", line 1614, in full_dispatch_request
calibre-web_1  |     rv = self.handle_user_exception(e)
calibre-web_1  |   File "/usr/lib/python2.7/site-packages/Flask-0.12.2-py2.7.egg/flask/app.py", line 1517, in handle_user_exception
calibre-web_1  |     reraise(exc_type, exc_value, tb)
calibre-web_1  |   File "/usr/lib/python2.7/site-packages/Flask-0.12.2-py2.7.egg/flask/app.py", line 1612, in full_dispatch_request
calibre-web_1  |     rv = self.dispatch_request()
calibre-web_1  |   File "/usr/lib/python2.7/site-packages/Flask-0.12.2-py2.7.egg/flask/app.py", line 1598, in dispatch_request
calibre-web_1  |     return self.view_functions[rule.endpoint](**req.view_args)
calibre-web_1  |   File "/usr/lib/python2.7/site-packages/Flask_Login-0.4.0-py2.7.egg/flask_login/utils.py", line 228, in decorated_view
calibre-web_1  |     return func(*args, **kwargs)
calibre-web_1  |   File "/opt/app/cps/web.py", line 499, in inner
calibre-web_1  |     return f(*args, **kwargs)
calibre-web_1  |   File "/opt/app/cps/web.py", line 2956, in upload
calibre-web_1  |     if not os.path.exists(filepath):
calibre-web_1  |   File "/usr/lib64/python2.7/genericpath.py", line 18, in exists
calibre-web_1  |     os.stat(path)
calibre-web_1  | TypeError: must be encoded string without NULL bytes, not unicode
calibre-web_1  | 2017-09-13 02:34:34,413 DEBG 'root' stdout output:
calibre-web_1  | [2017-09-13 02:34:34,412] ERROR in app: Exception on /upload [POST]
calibre-web_1  | Traceback (most recent call last):
calibre-web_1  |   File "/usr/lib/python2.7/site-packages/Flask-0.12.2-py2.7.egg/flask/app.py", line 1982, in wsgi_app
calibre-web_1  |     response = self.full_dispatch_request()
calibre-web_1  |   File "/usr/lib/python2.7/site-packages/Flask-0.12.2-py2.7.egg/flask/app.py", line 1614, in full_dispatch_request
calibre-web_1  |     rv = self.handle_user_exception(e)
calibre-web_1  |   File "/usr/lib/python2.7/site-packages/Flask-0.12.2-py2.7.egg/flask/app.py", line 1517, in handle_user_exception
calibre-web_1  |     reraise(exc_type, exc_value, tb)
calibre-web_1  |   File "/usr/lib/python2.7/site-packages/Flask-0.12.2-py2.7.egg/flask/app.py", line 1612, in full_dispatch_request
calibre-web_1  |     rv = self.dispatch_request()
calibre-web_1  |   File "/usr/lib/python2.7/site-packages/Flask-0.12.2-py2.7.egg/flask/app.py", line 1598, in dispatch_request
calibre-web_1  |     return self.view_functions[rule.endpoint](**req.view_args)
calibre-web_1  |   File "/usr/lib/python2.7/site-packages/Flask_Login-0.4.0-py2.7.egg/flask_login/utils.py", line 228, in decorated_view
calibre-web_1  |     return func(*args, **kwargs)
calibre-web_1  |   File "/opt/app/cps/web.py", line 499, in inner
calibre-web_1  |     return f(*args, **kwargs)
calibre-web_1  |   File "/opt/app/cps/web.py", line 2956, in upload
calibre-web_1  |     if not os.path.exists(filepath):
calibre-web_1  |   File "/usr/lib64/python2.7/genericpath.py", line 18, in exists
calibre-web_1  |     os.stat(path)
calibre-web_1  | TypeError: must be encoded string without NULL bytes, not unicode

# 
**When I uploaded the 400MB size PDF file.**

calibre-web_1  | 2017-09-13 02:42:55,067 DEBG 'nginx' stderr output:
calibre-web_1  | 2017/09/13 02:42:55 [error] 32#32: *85 client intended to send too large body: 453998607 bytes, client: 172.22.200.19, server: , request: "POST /upload HTTP/1.1", host: "172.22.200.12:8083", referrer: "http://172.22.200.12:8083/readbooks/"
calibre-web_1  |
calibre-web_1  | 2017-09-13 02:42:55,076 DEBG 'nginx' stderr output:
calibre-web_1  | 2017/09/13 02:42:55 [error] 32#32: *88 client intended to send too large body: 453998607 bytes, client: 172.22.200.19, server: , request: "POST /upload HTTP/1.1", host: "172.22.200.12:8083", referrer: "http://172.22.200.12:8083/readbooks/"

**Comment by xxyyer** [comment]
The problem is solved:
vi /etc/nginx/nginx.d/80-buffers.conf

# Set max upload size
# Modify 256 to 1024.
client_max_body_size 1024M;
