### ISSUE TITLE
Calibre-web crashes after additional format is uploaded

### ISSUE THREAD

**Issue by NikolaSivkov** [janeczku/calibre-web#3260]
**Describe the bug/problem** 

After uploading an book epub format to an already existing pdf version of the book, the admin url throws an error. However, not all books do this in my case, i have 5-6 out of 20

** UPDATE ** 

just noticed that the series field is being prefileled with `1`, if i delete it, the error doesn't happen anymore.

**To Reproduce**

1. upload a pdf book
2. go to the admin url of the book by clicking edit metadata button
3. click upload format
4. upload epub ( the series field is pre-filled with "1")
6. click save
7. press browser back button / click edit metadata button
8. see error

**Logfile**

```
[2024-12-16 11:34:57,082] ERROR {cps:838} Exception on /admin/book/170 [GET]
Traceback (most recent call last):
  File "/lsiopy/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/calibre-web/cps/usermanagement.py", line 96, in decorated_view
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/app/calibre-web/cps/editbooks.py", line 70, in inner
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/app/calibre-web/cps/editbooks.py", line 93, in show_edit_book
    return render_edit_book(book_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/calibre-web/cps/editbooks.py", line 977, in render_edit_book
    return render_title_template('book_edit.html', book=book, authors=author_names, cc=cc,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/calibre-web/cps/render_template.py", line 113, in render_title_template
    return render_template(instance=config.config_calibre_web_title, sidebar=sidebar, simple=simple,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.12/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.12/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.12/site-packages/jinja2/environment.py", line 1304, in render
    self.environment.handle_exception()
  File "/lsiopy/lib/python3.12/site-packages/jinja2/environment.py", line 939, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/app/calibre-web/cps/templates/book_edit.html", line 1, in top-level template code
    {% extends "layout.html" %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/calibre-web/cps/templates/layout.html", line 168, in top-level template code
    {% block body %}{% endblock %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/calibre-web/cps/templates/book_edit.html", line 111, in block 'body'
    <input type="number" step="0.01" min="0" placeholder="1" class="form-control" name="series_index" id="series_index" value="{{book.series_index|formatfloat(2)}}">
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/calibre-web/cps/jinjia.py", line 116, in formatfloat
    formated_value = ('{0:.' + str(decimals) + 'f}').format(value)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: Unknown format code 'f' for object of type 'str'
```

**Expected behavior**

no error thrown
**Screenshots**

![image](https://github.com/user-attachments/assets/78055b3b-f060-4058-9a93-a85bdf53b977)

**Environment (please complete the following information):**

 - calibre-web docker
 - Python version: ¯\_(ツ)_/¯
 - Calibre-Web version: 0.6.24
 - Docker container: LinuxServer
 - Special Hardware: n/a
 - Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36 Edg/131.0.0.0

**Additional context**
 Accessed via reverse proxy.

**Comment by OzzieIsaacs** [comment]
Please update to the latest nightly build, the problem should be solved there (there is a nightly container available from LinuxServer)
