### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by ShuaiZePing** [janeczku/calibre-web#3264]
## Short Notice from the maintainer 

After 6 years of more or less intensive programming on Calibre-Web, I need a break. 
The last few months, maintaining Calibre-Web has felt more like work than a hobby. I felt pressured and teased by people to solve "their" problems and merge PRs for "their" Calibre-Web. 
I have turned off all notifications from Github/Discord and will now concentrate undisturbed on the development of “my” Calibre-Web over the next few weeks/months.  
I will look into the issues and maybe also the PRs from time to time, but don't expect a quick response from me.

Please also have a look at our [Contributing Guidelines](https://github.com/janeczku/calibre-web/blob/master/CONTRIBUTING.md)

**Describe the bug/problem** 

A clear and concise description of what the bug is. If you are asking for support, please check our [Wiki](https://github.com/janeczku/calibre-web/wiki) if your question is already answered there.

**To Reproduce**

**Logfile**

Add content of calibre-web.log file or the relevant error, try to reproduce your problem with "debug" log-level to get more output.

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**

 - OS: [e.g. Windows 10/Raspberry Pi OS]
 - Python version: [e.g. python2.7]
 - Calibre-Web version: [e.g. 0.6.8 or 087c4c59 (git rev-parse --short HEAD)]:
 - Docker container: [None/LinuxServer]:
 - Special Hardware: [e.g. Rasperry Pi Zero]
 - Browser: [e.g. Chrome 83.0.4103.97, Safari 13.3.7, Firefox 68.0.1 ESR]

**Additional context**
Add any other context about the problem here. [e.g. access via reverse proxy, database background sync, special database location]
Traceback (most recent call last):
File "/root/calibre/lib/python3.8/site-packages/flask/app.py", line 1473, in wsgi_app
response = self.full_dispatch_request()
File "/root/calibre/lib/python3.8/site-packages/flask/app.py", line 882, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/root/calibre/lib/python3.8/site-packages/flask/app.py", line 880, in full_dispatch_request
rv = self.dispatch_request()
File "/root/calibre/lib/python3.8/site-packages/flask/app.py", line 865, in dispatch_request
return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args) # type: ignore[no-any-return]
File "/root/calibre/lib/python3.8/site-packages/calibreweb/cps/usermanagement.py", line 97, in decorated_view
return login_required(func)(*args, **kwargs)
File "/root/calibre/lib/python3.8/site-packages/calibreweb/cps/cw_login/utils.py", line 296, in decorated_view
return current_app.ensure_sync(func)(*args, **kwargs)
File "/root/calibre/lib/python3.8/site-packages/calibreweb/cps/web.py", line 813, in index
return render_books_list("newest", sort_param, 1, page)
File "/root/calibre/lib/python3.8/site-packages/calibreweb/cps/web.py", line 419, in render_books_list
entries, random, pagination = calibre_db.fill_indexpage(page, 0, db.Books, True, order[0],
File "/root/calibre/lib/python3.8/site-packages/calibreweb/cps/db.py", line 819, in fill_indexpage
return self.fill_indexpage_with_archived_books(page, database, pagesize, db_filter, order, False,
File "/root/calibre/lib/python3.8/site-packages/calibreweb/cps/db.py", line 826, in fill_indexpage_with_archived_books
random_query = self.generate_linked_query(config_read_column, database)
File "/root/calibre/lib/python3.8/site-packages/calibreweb/cps/db.py", line 780, in generate_linked_query
query = (self.session.query(database, ub.ArchivedBook.is_archived, ub.ReadBook.read_status)
AttributeError: 'NoneType' object has no attribute 'query'

**Comment by OzzieIsaacs** [comment]
With no additional context I can‘t help you
