### ISSUE TITLE
Get trouble in python cps.py

### ISSUE THREAD

**Issue by XxZhang2017** [janeczku/calibre-web#347]
Traceback (most recent call last):
  File "cps.py", line 13, in <module>
    from cps import web
  File "D:\east bay\software_engi\git_pro\cps\web.py", line 38, in <module>
    import helper
  File "D:\east bay\software_engi\git_pro\cps\helper.py", line 40, in <module>
    import gdriveutils as gd
  File "D:\east bay\software_engi\git_pro\cps\gdriveutils.py", line 16, in <module>
    import web
  File "D:\east bay\software_engi\git_pro\cps\web.py", line 216, in <module>
    cache_buster.init_cache_busting(app)
  File "D:\east bay\software_engi\git_pro\cps\cache_buster.py", line 28, in init_cache_busting
    file_hash = hashlib.md5(f.read()).hexdigest()[:7]
UnicodeDecodeError: 'gbk' codec can't decode byte 0xff in position 62: illegal multibyte sequence

**Comment by OzzieIsaacs** [comment]
Please try the newest commit, this is was a python 3 related error
