### ISSUE TITLE
Cannot read epub with latest version?

### ISSUE THREAD

**Issue by gytisgreitai** [janeczku/calibre-web#360]
Hi,

so today I just moved to new server, and installed calibre-web. Rsynced calibre library from the old one (calibre-web is fresh, no previous data). And everytime I try to read an epub book in browser I get this exception (I'm logged in with default admin/admin123)
```

[2017-10-09 22:44:04,180] ERROR in app: Exception on /read/192/epub [GET]
Traceback (most recent call last):
  File "/opt/calibre-web/vendor/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/calibre-web/vendor/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/calibre-web/vendor/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/calibre-web/vendor/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/calibre-web/vendor/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/calibre-web/cps/web.py", line 1820, in read_book
    return render_title_template('read.html', bookid=book_id, title=_(u"Read a Book"), bookmark=bookmark)
  File "/opt/calibre-web/cps/web.py", line 613, in render_title_template
    return render_template(instance=config.config_calibre_web_title, *args, **kwargs)
  File "/opt/calibre-web/vendor/flask/templating.py", line 134, in render_template
    context, ctx.app)
  File "/opt/calibre-web/vendor/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/opt/calibre-web/vendor/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/opt/calibre-web/vendor/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/calibre-web/cps/templates/read.html", line 87, in top-level template code
    useBookmarks: {{ g.user.is_authenticated | tojson }}
  File "/opt/calibre-web/vendor/flask/json.py", line 269, in tojson_filter
    return Markup(htmlsafe_dumps(obj, **kwargs))
  File "/opt/calibre-web/vendor/flask/json.py", line 183, in htmlsafe_dumps
    rv = dumps(obj, **kwargs) \
  File "/opt/calibre-web/vendor/flask/json.py", line 123, in dumps
    rv = _json.dumps(obj, **kwargs)
  File "/usr/lib/python2.7/json/__init__.py", line 251, in dumps
    sort_keys=sort_keys, **kw).encode(obj)
  File "/usr/lib/python2.7/json/encoder.py", line 209, in encode
    chunks = list(chunks)
  File "/usr/lib/python2.7/json/encoder.py", line 442, in _iterencode
    o = _default(o)
  File "/opt/calibre-web/vendor/flask/json.py", line 80, in default
    return _json.JSONEncoder.default(self, o)
  File "/usr/lib/python2.7/json/encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <function is_authenticated at 0x7fa7736f2a28> is not JSON serializable
ERROR:tornado.access:500 GET /read/192/epub (x.x.x.x.x) 159.89ms
```

**Comment by OzzieIsaacs** [comment]
Please try newest commit should now work again

**Comment by gytisgreitai** [comment]
Oh wow, that was fast. Thank you, working!
