### ISSUE TITLE
guest accounts still can not read books,this time  is no book details,I guess  program bug.

### ISSUE THREAD

**Issue by flashliao** [janeczku/calibre-web#361]
I doubt #360 fix the account bug,but  not notice the guest account bugs.Now book details show blank
![default](https://user-images.githubusercontent.com/28710685/31384135-319b694c-adf0-11e7-9505-631e33e3dab2.png)

**Comment by flashliao** [comment]
[2017-10-10 19:32:56,934] {/root/calibre-web-master/cps/web.py:228} INFO - Starting Calibre Web...
[2017-10-10 19:32:57,655] {/root/calibre-web-master/cps/book_formats.py:18} WARNING - cannot import Image, generating pdf covers for pdf uploads will not work: MagickWand shared library not found.
You probably had not installed ImageMagick library.
Try to install:
  http://docs.wand-py.org/en/latest/guide/install.html
[2017-10-10 19:32:57,923] {/root/calibre-web-master/cps.py:28} INFO - Attempting to start gevent
[2017-10-10 19:34:26,101] {/usr/lib64/python2.7/site-packages/flask/app.py:1560} ERROR - Exception on /book/132 [GET]
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/root/calibre-web-master/cps/web.py", line 1320, in show_book
    title=entries.title, books_shelfs=book_in_shelfs, have_read=have_read)
  File "/root/calibre-web-master/cps/web.py", line 613, in render_title_template
    return render_template(instance=config.config_calibre_web_title, *args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/flask/templating.py", line 134, in render_template
    context, ctx.app)
  File "/usr/lib64/python2.7/site-packages/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/root/calibre-web-master/cps/templates/detail.html", line 1, in top-level template code
    {% extends is_xhr|yesno("fragment.html", "layout.html") %}
  File "/root/calibre-web-master/cps/templates/fragment.html", line 2, in top-level template code
    {% block body %}{% endblock %}
  File "/root/calibre-web-master/cps/templates/detail.html", line 184, in block "body"
    {% if g.user.shelf.all() or g.public_shelfes %}
  File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 430, in getattr
    return getattr(obj, attribute)
UndefinedError: 'werkzeug.local.LocalProxy object' has no attribute 'shelf'
[2017-10-10 19:54:16,920] {/root/calibre-web-master/cps/web.py:228} INFO - Starting Calibre Web...
[2017-10-10 19:54:17,260] {/root/calibre-web-master/cps.py:28} INFO - Attempting to start gevent
[2017-10-10 19:56:02,114] {/usr/lib64/python2.7/site-packages/flask/app.py:1560} ERROR - Exception on /book/132 [GET]
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/root/calibre-web-master/cps/web.py", line 1320, in show_book
    title=entries.title, books_shelfs=book_in_shelfs, have_read=have_read)
  File "/root/calibre-web-master/cps/web.py", line 613, in render_title_template
    return render_template(instance=config.config_calibre_web_title, *args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/flask/templating.py", line 134, in render_template
    context, ctx.app)
  File "/usr/lib64/python2.7/site-packages/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/root/calibre-web-master/cps/templates/detail.html", line 1, in top-level template code
    {% extends is_xhr|yesno("fragment.html", "layout.html") %}
  File "/root/calibre-web-master/cps/templates/fragment.html", line 2, in top-level template code
    {% block body %}{% endblock %}
  File "/root/calibre-web-master/cps/templates/detail.html", line 184, in block "body"
    {% if g.user.shelf.all() or g.public_shelfes %}
  File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 430, in getattr
    return getattr(obj, attribute)
UndefinedError: 'werkzeug.local.LocalProxy object' has no attribute 'shelf'
[2017-10-10 19:59:10,124] {/usr/lib64/python2.7/site-packages/flask/app.py:1560} ERROR - Exception on /book/129 [GET]
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/root/calibre-web-master/cps/web.py", line 1320, in show_book
    title=entries.title, books_shelfs=book_in_shelfs, have_read=have_read)
  File "/root/calibre-web-master/cps/web.py", line 613, in render_title_template
    return render_template(instance=config.config_calibre_web_title, *args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/flask/templating.py", line 134, in render_template
    context, ctx.app)
  File "/usr/lib64/python2.7/site-packages/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/root/calibre-web-master/cps/templates/detail.html", line 1, in top-level template code
    {% extends is_xhr|yesno("fragment.html", "layout.html") %}
  File "/root/calibre-web-master/cps/templates/fragment.html", line 2, in top-level template code
    {% block body %}{% endblock %}
  File "/root/calibre-web-master/cps/templates/detail.html", line 184, in block "body"
    {% if g.user.shelf.all() or g.public_shelfes %}
  File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 430, in getattr
    return getattr(obj, attribute)
UndefinedError: 'werkzeug.local.LocalProxy object' has no attribute 'shelf'

**Comment by gytisgreitai** [comment]
I get the same error when under nginx proxy, if accessing calibre-web directly, works fine.

**Comment by gytisgreitai** [comment]
https://github.com/janeczku/calibre-web/pull/364 should fix that

**Comment by OzzieIsaacs** [comment]
The newest comit should fix it.
