### ISSUE TITLE
[BUG] Edit Metadata crashes db-engine

### ISSUE THREAD

**Issue by dihmandrake** [janeczku/calibre-web#379]
# Issue:
After editing and posting the metadata of a book the server yields for a few seconds and then returns HTTP 500

## Server traceback:
_See below for text version_
![image](https://user-images.githubusercontent.com/16025288/32302085-23a7e0c2-bf61-11e7-9643-e57485a090a6.png)

`Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/bin/calibre-web/cps/web.py", line 391, in decorated_view
    return login_required(func)(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flask_login/utils.py", line 228, in decorated_view
    return func(*args, **kwargs)
  File "/usr/bin/calibre-web/cps/web.py", line 514, in inner
    return f(*args, **kwargs)
  File "/usr/bin/calibre-web/cps/web.py", line 2952, in edit_book
    db.session.commit()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 906, in commit
    self.transaction.commit()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 465, in commit
    t[1].commit()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1632, in commit
    self._do_commit()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1663, in _do_commit
    self.connection._commit_impl()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 723, in _commit_impl
    self._handle_dbapi_exception(e, None, None, None, None)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1402, in _handle_dbapi_exception
    exc_info
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 721, in _commit_impl
    self.engine.dialect.do_commit(self.connection)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/default.py", line 443, in do_commit
    dbapi_connection.commit()
OperationalError: (sqlite3.OperationalError) database is locked`

## Trailing Impact:
Any call that involves the database from now fails (config access still okay)
This persists until a restart

_See below for text version_
![image](https://user-images.githubusercontent.com/16025288/32302098-3e9b8d84-bf61-11e7-8d25-0b2cf2b5d7ba.png)

`Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/bin/calibre-web/cps/web.py", line 391, in decorated_view
    return login_required(func)(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flask_login/utils.py", line 228, in decorated_view
    return func(*args, **kwargs)
  File "/usr/bin/calibre-web/cps/web.py", line 514, in inner
    return f(*args, **kwargs)
  File "/usr/bin/calibre-web/cps/web.py", line 2743, in edit_book
    db.session.connection().connection.connection.create_function("title_sort", 1, db.title_sort)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 998, in connection
    execution_options=execution_options)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 1003, in _connection_for_bind
    engine, execution_options)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 382, in _connection_for_bind
    self._assert_active()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 264, in _assert_active
    "This session is in 'prepared' state; no further "
InvalidRequestError: This session is in 'prepared' state; no further SQL can be emitted within this transaction.`

## Setup Notes:
- Ubuntu Server 16.04.3 Server LTS
- python 2.7; pip 9.0.1
- Installed requirements.txt & optional-requirements.txt
- Other installs involve sssd cifs-utils (The machine is Active Directory Domain joined)
- The Calibre Lib is on a network share mounted via SMB3 cifs (Server Win 2016)
- Installed missing dependencies from the log
- Database has been reduced to 15 entries for testing

_Installed Libs_
![image](https://user-images.githubusercontent.com/16025288/32302062-fd273d9e-bf60-11e7-9bcb-eb2124feca95.png)

## Notes
The image of an book is updated anyway

## Probable Cause:
The db engine never finishes the commit for the new metadata (correctly) and a session to the db never closes. Therefore the application locks. This is might cause due to the fact that the data is on a network share (Calibre operates without any issues).

## Suggested quick Solutions:
To stop the trailing impact and improve overall application stability (catch unkown db errors), this error could be caught and the db-connection (forcibly) reset

## Possible full Solutions:
- Increase db timeout (https://stackoverflow.com/questions/27160987/sqlite-python-sqlite3-operationalerror-database-is-locked) [Not working]; Tried adding `connect_args={'timeout': 30}` as argument to dp.py Line 307; Error occurs after 30 secs
- Update db engine? [Not working]
- Smaller commits as retry on failure
- Under "Database Locking Behavior / Concurrency" @ http://docs.sqlalchemy.org/en/latest/dialects/sqlite.html could be considered

## Tried Solutions
- Comment out line 2953 in /cps/web.py [`db.session.commit()`] works as expected. No data is written to the sqlite database and the application continues as expected
- Installed `libsqlite3-dev` did not help
- Upgraded pysqlite to 2.8.3 (in System & vendor) did not help [requires `libsqlite3-dev`]

### Personal Note
My free time currently is pretty limited so I won't have any time to fix this issue myself. Additionally the last time I used python is few years ago, so my development speed would be quite slow. I would love to see this issue fixed, but I don't have the time myself.

**Comment by OzzieIsaacs** [comment]
The thing which looks most suspicious to me, is the location of the database "mounted via smb3". Could you please try to place the database locally? To me it looks like you can't get get write access to the database.

**Comment by OzzieIsaacs** [comment]
I found some bugs in editing the metadata, I don't think its related to timeout. I also implemented the rollback in case of an error.
