### ISSUE TITLE
Cannot delete book

### ISSUE THREAD

**Issue by Thijxx** [janeczku/calibre-web#382]
Crash when I try to delete a book.

```
Nov 04 23:21:22 calibre.local python[610]: [2017-11-04 23:21:22,810] ERROR in app: Exception on /delete/833/ [GET]
Nov 04 23:21:22 calibre.local python[610]: Traceback (most recent call last):
Nov 04 23:21:22 calibre.local python[610]: File "/opt/calibre-web/vendor/flask/app.py", line 1982, in wsgi_app
Nov 04 23:21:22 calibre.local python[610]: response = self.full_dispatch_request()
Nov 04 23:21:22 calibre.local python[610]: File "/opt/calibre-web/vendor/flask/app.py", line 1614, in full_dispatch_request
Nov 04 23:21:22 calibre.local python[610]: rv = self.handle_user_exception(e)
Nov 04 23:21:22 calibre.local python[610]: File "/opt/calibre-web/vendor/flask/app.py", line 1517, in handle_user_exception
Nov 04 23:21:22 calibre.local python[610]: reraise(exc_type, exc_value, tb)
Nov 04 23:21:22 calibre.local python[610]: File "/opt/calibre-web/vendor/flask/app.py", line 1612, in full_dispatch_request
Nov 04 23:21:22 calibre.local python[610]: rv = self.dispatch_request()
Nov 04 23:21:22 calibre.local python[610]: File "/opt/calibre-web/vendor/flask/app.py", line 1598, in dispatch_request
Nov 04 23:21:22 calibre.local python[610]: return self.view_functions[rule.endpoint](**req.view_args)
Nov 04 23:21:22 calibre.local python[610]: File "/opt/calibre-web/vendor/flask_login/utils.py", line 228, in decorated_view
Nov 04 23:21:22 calibre.local python[610]: return func(*args, **kwargs)
Nov 04 23:21:22 calibre.local python[610]: File "/opt/calibre-web/cps/web.py", line 1444, in delete_book
Nov 04 23:21:22 calibre.local python[610]: app.logger.info('Book with id "'+book_id+'" could not be deleted')
Nov 04 23:21:22 calibre.local python[610]: TypeError: cannot concatenate 'str' and 'int' objects
Nov 04 23:21:22 calibre.local python[610]: ERROR:tornado.access:500 GET /calibre-web/delete/833/ (127.0.0.1) 26.18ms
Nov 04 23:21:23 calibre.local python[610]: WARNING:tornado.access:404 GET /favicon.ico (127.0.0.1) 9.41ms

```

**Comment by OzzieIsaacs** [comment]
The error should not occour anymore with the newest commit.
Error only occoured if book to delete wasn't found in the database. I can't read the reason for this from the log.
