### ISSUE TITLE
order by the newest or oldest or desc titile show Internal Server Error.

### ISSUE THREAD

**Issue by flashliao** [janeczku/calibre-web#388]
order by the newest or oldest or desc titile show Internal Server Error.
the log is
-------------------------------------------------------------------------------------------
File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/root/calibre-web-master/cps/web.py", line 390, in decorated_view
    return func(*args, **kwargs)
  File "/root/calibre-web-master/cps/web.py", line 1051, in newest_books
    if current_cuser.show_sorted():
NameError: global name 'current_cuser' is not defined
[2017-11-15 09:08:05,273] {/usr/lib64/python2.7/site-packages/flask/app.py:1560} ERROR - Exception on /books/oldest [GET]
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/root/calibre-web-master/cps/web.py", line 390, in decorated_view
    return func(*args, **kwargs)
  File "/root/calibre-web-master/cps/web.py", line 1062, in oldest_books
    if current_cuser.show_sorted():
NameError: global name 'current_cuser' is not defined
[2017-11-15 09:08:09,852] {/usr/lib64/python2.7/site-packages/flask/app.py:1560} ERROR - Exception on /books/a-z [GET]
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/root/calibre-web-master/cps/web.py", line 390, in decorated_view
    return func(*args, **kwargs)
  File "/root/calibre-web-master/cps/web.py", line 1074, in titles_ascending
    if current_cuser.show_sorted():
NameError: global name 'current_cuser' is not defined
[2017-11-15 09:08:50,656] {/usr/lib64/python2.7/site-packages/flask/app.py:1560} ERROR - Exception on /books/newest [GET]
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/root/calibre-web-master/cps/web.py", line 390, in decorated_view
    return func(*args, **kwargs)
  File "/root/calibre-web-master/cps/web.py", line 1051, in newest_books
    if current_cuser.show_sorted():
NameError: global name 'current_cuser' is not defined
[2017-11-15 09:10:13,913] {/usr/lib64/python2.7/site-packages/flask/app.py:1560} ERROR - Exception on /books/newest [GET]
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/root/calibre-web-master/cps/web.py", line 390, in decorated_view
    return func(*args, **kwargs)
  File "/root/calibre-web-master/cps/web.py", line 1051, in newest_books
    if current_cuser.show_sorted():
NameError: global name 'current_cuser' is not defined
[2017-11-15 09:11:06,418] {/usr/lib64/python2.7/site-packages/flask/app.py:1560} ERROR - Exception on /books/oldest [GET]
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/root/calibre-web-master/cps/web.py", line 390, in decorated_view
    return func(*args, **kwargs)
  File "/root/calibre-web-master/cps/web.py", line 1062, in oldest_books
    if current_cuser.show_sorted():
NameError: global name 'current_cuser' is not defined
---------------------------------------------------------------------------------

**Comment by OzzieIsaacs** [comment]
Should work now
