### ISSUE TITLE
Errors at startup/access

### ISSUE THREAD

**Issue by simkin** [janeczku/calibre-web#39]
When I start the application and try to access the webpage the following error is logged (and the page is not loaded). Could you please advise what might be wrong?

**Config:**
root@nas:/opt/calibre-web# cat config.ini
[General]
DB_ROOT = /dikkert/Server/Books/Library
APP_DB_ROOT = /opt/calibre-web
MAIN_DIR = /opt/calibre-web
LOG_DIR = /opt/calibre-web
PORT = 8282
NEWEST_BOOKS = 60
[Advanced]
TITLE_REGEX = ^(A|The|An|Der|Die|Das|Den|Ein|Eine|Einen|Dem|Des|Einem|Eines)\s+
DEVELOPMENT = 0
PUBLIC_REG = 0
UPLOADING = 1
ANON_BROWSE = 0

**Debug**: [debug.txt](https://github.com/janeczku/calibre-web/files/373321/debug.txt)
**Normal log below**

`root@nas:/opt/calibre-web# python --version
Python 2.7.9
root@nas:/opt/calibre-web# python cps.py
ERROR:cps.web:Exception on / [GET]
Traceback (most recent call last):
  File "/opt/calibre-web/vendor/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/calibre-web/vendor/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/calibre-web/vendor/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/calibre-web/vendor/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/calibre-web/vendor/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/calibre-web/vendor/flask_login.py", line 715, in decorated_view
    elif not current_user.is_authenticated():
  File "/opt/calibre-web/vendor/werkzeug/local.py", line 338, in __getattr__
    return getattr(self._get_current_object(), name)
  File "/opt/calibre-web/vendor/werkzeug/local.py", line 297, in _get_current_object
    return self.__local()
  File "/opt/calibre-web/vendor/flask_login.py", line 46, in <lambda>
    current_user = LocalProxy(lambda: _get_user() or
  File "/opt/calibre-web/vendor/flask_login.py", line 753, in _get_user
    current_app.login_manager._load_user()
  File "/opt/calibre-web/vendor/flask_login.py", line 335, in _load_user
    return self._load_from_header(request.headers[header_name])
  File "/opt/calibre-web/vendor/flask_login.py", line 393, in _load_from_header
    user = self.header_callback(header)
  File "/opt/calibre-web/cps/web.py", line 116, in load_user_from_header
    basic_password = header_val.split(':')[1]
IndexError: list index out of range
ERROR:tornado.access:500 GET / (::1) 22.11ms
WARNING:tornado.access:404 GET /favicon.ico (::1) 1.59ms
`

Control-C:
`^CTraceback (most recent call last):
  File "cps.py", line 25, in <module>
    IOLoop.instance().start()
  File "/opt/calibre-web/vendor/tornado/ioloop.py", line 646, in start
    event_pairs = self._impl.poll(poll_timeout)
KeyboardInterrupt
`

**Comment by simkin** [comment]
Unable to reproduce :/, closing
