### ISSUE TITLE
Show read and unread books shows Internal Server Error with guest accounts.

### ISSUE THREAD

**Issue by flashliao** [janeczku/calibre-web#391]
Show read and unread books shows Internal Server Error with guest accounts.

**Comment by flashliao** [comment]
UnboundLocalError: local variable 'readBookIds' referenced before assignment
[2017-11-17 15:11:47,365] {/usr/lib64/python2.7/site-packages/flask/app.py:1560} ERROR - Exception on /readbooks/ [GET]
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/root/calibre-web-master/cps/web.py", line 390, in decorated_view
    return func(*args, **kwargs)
  File "/root/calibre-web-master/cps/web.py", line 1803, in read_books
    return render_read_books(page, True)
  File "/root/calibre-web-master/cps/web.py", line 1782, in render_read_books
    name = _(u'Read Books') + ' (' + str(len(readBookIds)) + ')'
UnboundLocalError: local variable 'readBookIds' referenced before assignment
