### ISSUE TITLE
[BUG] Updating metadata always fires a 500 error.

### ISSUE THREAD

**Issue by gfriloux** [janeczku/calibre-web#395]
When we add a book, we are moved to the "edit page" of the book.
From there, editing metadata will always lead to a 500 error.
Despite the 500 error, edited datas will be saved correctly.

Here is the traceback : 
```
nov. 26 20:01:52 friloux.me python[44161]: [2017-11-26 20:01:52,611] ERROR in app: Exception on /admin/book/80 [POST]
nov. 26 20:01:52 friloux.me python[44161]: Traceback (most recent call last):
nov. 26 20:01:52 friloux.me python[44161]:   File "/usr/share/webapps/calibre-web/vendor/flask/app.py", line 1982, in wsgi_app
nov. 26 20:01:52 friloux.me python[44161]:     response = self.full_dispatch_request()
nov. 26 20:01:52 friloux.me python[44161]:   File "/usr/share/webapps/calibre-web/vendor/flask/app.py", line 1614, in full_dispatch_request
nov. 26 20:01:52 friloux.me python[44161]:     rv = self.handle_user_exception(e)
nov. 26 20:01:52 friloux.me python[44161]:   File "/usr/share/webapps/calibre-web/vendor/flask/app.py", line 1517, in handle_user_exception
nov. 26 20:01:52 friloux.me python[44161]:     reraise(exc_type, exc_value, tb)
nov. 26 20:01:52 friloux.me python[44161]:   File "/usr/share/webapps/calibre-web/vendor/flask/_compat.py", line 33, in reraise
nov. 26 20:01:52 friloux.me python[44161]:     raise value
nov. 26 20:01:52 friloux.me python[44161]:   File "/usr/share/webapps/calibre-web/vendor/flask/app.py", line 1612, in full_dispatch_request
nov. 26 20:01:52 friloux.me python[44161]:     rv = self.dispatch_request()
nov. 26 20:01:52 friloux.me python[44161]:   File "/usr/share/webapps/calibre-web/vendor/flask/app.py", line 1598, in dispatch_request
nov. 26 20:01:52 friloux.me python[44161]:     return self.view_functions[rule.endpoint](**req.view_args)
nov. 26 20:01:52 friloux.me python[44161]:   File "/usr/share/webapps/calibre-web/cps/web.py", line 391, in decorated_view
nov. 26 20:01:52 friloux.me python[44161]:     return login_required(func)(*args, **kwargs)
nov. 26 20:01:52 friloux.me python[44161]:   File "/usr/share/webapps/calibre-web/vendor/flask_login/utils.py", line 228, in decorated_view
nov. 26 20:01:52 friloux.me python[44161]:     return func(*args, **kwargs)
nov. 26 20:01:52 friloux.me python[44161]:   File "/usr/share/webapps/calibre-web/cps/web.py", line 514, in inner
nov. 26 20:01:52 friloux.me python[44161]:     return f(*args, **kwargs)
nov. 26 20:01:52 friloux.me python[44161]:   File "/usr/share/webapps/calibre-web/cps/web.py", line 2864, in edit_book
nov. 26 20:01:52 friloux.me python[44161]:     book.author_sort = helper.get_sorted_author(input_authors[0])
nov. 26 20:01:52 friloux.me python[44161]: TypeError: 'map' object is not subscriptable
nov. 26 20:01:52 friloux.me python[44161]: ERROR:tornado.access:500 POST /admin/book/80 (127.0.0.1) 19.69ms
```
The database has been initially created using calibre 3.12 from https://calibre-ebook.com/.
If any more information is needed, tell me, but i must say that i know nothing to python.

**Comment by OzzieIsaacs** [comment]
Could be related to #392. I found one issue if the authors name, or the title has a pipe symbol (|)in the name. Could this be the issue here?

**Comment by gfriloux** [comment]
1. Setting a publication date manually doesn't solve the issue
2. I don't have any special char in the name of the book

**Comment by gfriloux** [comment]
The `books` table will look like this : 
```
sqlite> select * from books;
id|title|sort|timestamp|pubdate|series_index|author_sort|isbn|lccn|path|flags|uuid|has_cover|last_modified
...
80|Astérix - Astérix gladiateur - no4|Astérix - Astérix gladiateur - no4|2017-11-26 20:01:32.139371|1962-03-22 00:00:00||Unknown, |||Unknown/Asterix - T04 - Asterix gladiateur|1|9eaf3579-c76a-4a8b-a316-a2e9985b37d4|1|2017-11-26 20:01:32.139377
...
```
In this example, there is a "é" char, but i have others books that only contains chars from the ASCII table that triggers the same error.

**Comment by OzzieIsaacs** [comment]
I‘ll take a look at it. Thanks for the detailed informations

**Comment by gfriloux** [comment]
I just got another error : I went from /authors to /series, and got another 500 : 
```
nov. 26 20:23:07 friloux.me python[44161]: [2017-11-26 20:23:07,410] ERROR in app: Exception on /series [GET]
nov. 26 20:23:07 friloux.me python[44161]: Traceback (most recent call last):
nov. 26 20:23:07 friloux.me python[44161]:   File "/usr/share/webapps/calibre-web/vendor/sqlalchemy/engine/base.py", line 1159, in _execute_context
nov. 26 20:23:07 friloux.me python[44161]:     context)
nov. 26 20:23:07 friloux.me python[44161]:   File "/usr/share/webapps/calibre-web/vendor/sqlalchemy/engine/default.py", line 467, in do_executemany
nov. 26 20:23:07 friloux.me python[44161]:     cursor.executemany(statement, parameters)
nov. 26 20:23:07 friloux.me python[44161]: sqlite3.IntegrityError: UNIQUE constraint failed: authors.name
nov. 26 20:23:07 friloux.me python[44161]: The above exception was the direct cause of the following exception:
nov. 26 20:23:07 friloux.me python[44161]: Traceback (most recent call last):
nov. 26 20:23:07 friloux.me python[44161]:   File "/usr/share/webapps/calibre-web/vendor/flask/app.py", line 1982, in wsgi_app
nov. 26 20:23:07 friloux.me python[44161]:     response = self.full_dispatch_request()
nov. 26 20:23:07 friloux.me python[44161]:   File "/usr/share/webapps/calibre-web/vendor/flask/app.py", line 1614, in full_dispatch_request
nov. 26 20:23:07 friloux.me python[44161]:     rv = self.handle_user_exception(e)
nov. 26 20:23:07 friloux.me python[44161]:   File "/usr/share/webapps/calibre-web/vendor/flask/app.py", line 1517, in handle_user_exception
nov. 26 20:23:07 friloux.me python[44161]:     reraise(exc_type, exc_value, tb)
nov. 26 20:23:07 friloux.me python[44161]:   File "/usr/share/webapps/calibre-web/vendor/flask/_compat.py", line 33, in reraise
nov. 26 20:23:07 friloux.me python[44161]:     raise value
nov. 26 20:23:07 friloux.me python[44161]:   File "/usr/share/webapps/calibre-web/vendor/flask/app.py", line 1612, in full_dispatch_request
nov. 26 20:23:07 friloux.me python[44161]:     rv = self.dispatch_request()
nov. 26 20:23:07 friloux.me python[44161]:   File "/usr/share/webapps/calibre-web/vendor/flask/app.py", line 1598, in dispatch_request
nov. 26 20:23:07 friloux.me python[44161]:     return self.view_functions[rule.endpoint](**req.view_args)
nov. 26 20:23:07 friloux.me python[44161]:   File "/usr/share/webapps/calibre-web/cps/web.py", line 391, in decorated_view
nov. 26 20:23:07 friloux.me python[44161]:     return login_required(func)(*args, **kwargs)
nov. 26 20:23:07 friloux.me python[44161]:   File "/usr/share/webapps/calibre-web/vendor/flask_login/utils.py", line 228, in decorated_view
nov. 26 20:23:07 friloux.me python[44161]:     return func(*args, **kwargs)
nov. 26 20:23:07 friloux.me python[44161]:   File "/usr/share/webapps/calibre-web/cps/web.py", line 1208, in series_list
nov. 26 20:23:07 friloux.me python[44161]:     .group_by('books_series_link.series').order_by(db.Series.sort).all()
nov. 26 20:23:07 friloux.me python[44161]:   File "/usr/share/webapps/calibre-web/vendor/sqlalchemy/orm/query.py", line 2703, in all
nov. 26 20:23:07 friloux.me python[44161]:     return list(self)
nov. 26 20:23:07 friloux.me python[44161]:   File "/usr/share/webapps/calibre-web/vendor/sqlalchemy/orm/query.py", line 2854, in __iter__
nov. 26 20:23:07 friloux.me python[44161]:     self.session._autoflush()
nov. 26 20:23:07 friloux.me python[44161]:   File "/usr/share/webapps/calibre-web/vendor/sqlalchemy/orm/session.py", line 1422, in _autoflush
nov. 26 20:23:07 friloux.me python[44161]:     util.raise_from_cause(e)
nov. 26 20:23:07 friloux.me python[44161]:   File "/usr/share/webapps/calibre-web/vendor/sqlalchemy/util/compat.py", line 203, in raise_from_cause
nov. 26 20:23:07 friloux.me python[44161]:     reraise(type(exception), exception, tb=exc_tb, cause=cause)
nov. 26 20:23:07 friloux.me python[44161]:   File "/usr/share/webapps/calibre-web/vendor/sqlalchemy/util/compat.py", line 187, in reraise
nov. 26 20:23:07 friloux.me python[44161]:     raise value
nov. 26 20:23:07 friloux.me python[44161]:   File "/usr/share/webapps/calibre-web/vendor/sqlalchemy/orm/session.py", line 1412, in _autoflush
nov. 26 20:23:07 friloux.me python[44161]:     self.flush()
nov. 26 20:23:07 friloux.me python[44161]:   File "/usr/share/webapps/calibre-web/vendor/sqlalchemy/orm/session.py", line 2192, in flush
nov. 26 20:23:07 friloux.me python[44161]:     self._flush(objects)
nov. 26 20:23:07 friloux.me python[44161]:   File "/usr/share/webapps/calibre-web/vendor/sqlalchemy/orm/session.py", line 2312, in _flush
nov. 26 20:23:07 friloux.me python[44161]:     transaction.rollback(_capture_exception=True)
nov. 26 20:23:07 friloux.me python[44161]:   File "/usr/share/webapps/calibre-web/vendor/sqlalchemy/util/langhelpers.py", line 66, in __exit__
nov. 26 20:23:07 friloux.me python[44161]:     compat.reraise(exc_type, exc_value, exc_tb)
nov. 26 20:23:07 friloux.me python[44161]:   File "/usr/share/webapps/calibre-web/vendor/sqlalchemy/util/compat.py", line 187, in reraise
nov. 26 20:23:07 friloux.me python[44161]:     raise value
nov. 26 20:23:07 friloux.me python[44161]:   File "/usr/share/webapps/calibre-web/vendor/sqlalchemy/orm/session.py", line 2276, in _flush
nov. 26 20:23:07 friloux.me python[44161]:     flush_context.execute()
nov. 26 20:23:07 friloux.me python[44161]:   File "/usr/share/webapps/calibre-web/vendor/sqlalchemy/orm/unitofwork.py", line 389, in execute
nov. 26 20:23:07 friloux.me python[44161]:     rec.execute(self)
nov. 26 20:23:07 friloux.me python[44161]:   File "/usr/share/webapps/calibre-web/vendor/sqlalchemy/orm/unitofwork.py", line 548, in execute
nov. 26 20:23:07 friloux.me python[44161]:     uow
nov. 26 20:23:07 friloux.me python[44161]:   File "/usr/share/webapps/calibre-web/vendor/sqlalchemy/orm/persistence.py", line 177, in save_obj
nov. 26 20:23:07 friloux.me python[44161]:     mapper, table, update)
nov. 26 20:23:07 friloux.me python[44161]:   File "/usr/share/webapps/calibre-web/vendor/sqlalchemy/orm/persistence.py", line 737, in _emit_update_statements
nov. 26 20:23:07 friloux.me python[44161]:     execute(statement, multiparams)
nov. 26 20:23:07 friloux.me python[44161]:   File "/usr/share/webapps/calibre-web/vendor/sqlalchemy/engine/base.py", line 945, in execute
nov. 26 20:23:07 friloux.me python[44161]:     return meth(self, multiparams, params)
nov. 26 20:23:07 friloux.me python[44161]:   File "/usr/share/webapps/calibre-web/vendor/sqlalchemy/sql/elements.py", line 263, in _execute_on_connection
nov. 26 20:23:07 friloux.me python[44161]:     return connection._execute_clauseelement(self, multiparams, params)
nov. 26 20:23:07 friloux.me python[44161]:   File "/usr/share/webapps/calibre-web/vendor/sqlalchemy/engine/base.py", line 1053, in _execute_clauseelement
nov. 26 20:23:07 friloux.me python[44161]:     compiled_sql, distilled_params
nov. 26 20:23:07 friloux.me python[44161]:   File "/usr/share/webapps/calibre-web/vendor/sqlalchemy/engine/base.py", line 1189, in _execute_context
nov. 26 20:23:07 friloux.me python[44161]:     context)
nov. 26 20:23:07 friloux.me python[44161]:   File "/usr/share/webapps/calibre-web/vendor/sqlalchemy/engine/base.py", line 1402, in _handle_dbapi_exception
nov. 26 20:23:07 friloux.me python[44161]:     exc_info
nov. 26 20:23:07 friloux.me python[44161]:   File "/usr/share/webapps/calibre-web/vendor/sqlalchemy/util/compat.py", line 203, in raise_from_cause
nov. 26 20:23:07 friloux.me python[44161]:     reraise(type(exception), exception, tb=exc_tb, cause=cause)
nov. 26 20:23:07 friloux.me python[44161]:   File "/usr/share/webapps/calibre-web/vendor/sqlalchemy/util/compat.py", line 186, in reraise
nov. 26 20:23:07 friloux.me python[44161]:     raise value.with_traceback(tb)
nov. 26 20:23:07 friloux.me python[44161]:   File "/usr/share/webapps/calibre-web/vendor/sqlalchemy/engine/base.py", line 1159, in _execute_context
nov. 26 20:23:07 friloux.me python[44161]:     context)
nov. 26 20:23:07 friloux.me python[44161]:   File "/usr/share/webapps/calibre-web/vendor/sqlalchemy/engine/default.py", line 467, in do_executemany
nov. 26 20:23:07 friloux.me python[44161]:     cursor.executemany(statement, parameters)
nov. 26 20:23:07 friloux.me python[44161]: sqlalchemy.exc.IntegrityError: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely) (sqlite3.IntegrityError) UNIQUE constraint failed: authors.name [SQL: 'UPDATE authors SET name=? WHERE authors.id = ?'] [parameters: (('Marais,Jérémie Kaminka', 56), ('Xavier Fauche,Adam', 57), ('Batem,Olivier Saive', 58), ('René Goscinny,Albert Uderzo', 60))]
nov. 26 20:23:07 friloux.me python[44161]: ERROR:tornado.access:500 GET /series (127.0.0.1) 138.07ms
```
I am not able to figure if this is the same issue or not, thats why i haven't open another issue for this.

**Comment by OzzieIsaacs** [comment]
Could you please restart Calibre-web, maybe it‘s caused because of the other error

**Comment by gfriloux** [comment]
I had to restart it, as it was not willing to work at all.
Once done, /series was answering correctly.

**Comment by gfriloux** [comment]
It seems the issue is with authors.
I can go to /category, /series, and loop between the two. But once i load /authors, the next URI will fail with a 500 error.

Here is my `authors` table : 
```
sqlite> select * from authors;
id|name|sort|link
1|Dennis Gluth|Gluth, Dennis|
4|Pierre Bellemare|Bellemare, Pierre|
5|Bellemare Pierre|Pierre, Bellemare|
6|Pierre Bellemare, Jacques Antoine|Pierre Bellemare, Jacques Antoine|
7|Bellemare, Pierre|Bellemare, Pierre|
8|Christie Golden|Golden, Christie|
9|George R.R. Martin|George R.R. Martin|
10|Goodkind,Terry|Goodkind,Terry|
12|Terry Goodkind|Goodkind, Terry|
13|Goodkind, Terry|Goodkind| Terry|
14|Oliver Bowden|Bowden, Oliver|
16|Mark Millar,John Romita Jr|Mark Millar|John Romita Jr|
36|Robinson Academy|Academy, Robinson|
45|GREG|GREG|
46|Stéphane Colman|Stéphane Colman|
48|Colman|Colman|
50|Yann|Yann|
51|Dugomier|Dugomier|
54|Marais,Jérémie Kaminka|Marais|Jérémie Kaminka|
55|Marais|Marais|
56|Marais|Jérémie Kaminka|Marais|Jérémie Kaminka|
57|Xavier Fauche|Adam|Xavier Fauche|Adam|
58|Batem|Olivier Saive|Batem|Olivier Saive|
59|Xavier Fauche|Xavier Fauche|
60|René Goscinny|Albert Uderzo|René Goscinny|Albert Uderzo|
```

**Comment by gfriloux** [comment]
If you need my .db to be able to reproduce the bug, just ask me and ill mail it.

**Comment by OzzieIsaacs** [comment]
At least no 60 has a pipe in the name. I‘m sure the issue is related to this. Could you please edit the name in Calibre (it won‘t show the pipe but instead a comma). I can‘t see if other names have also pipes or if they are the field separators. I think if you edit all relevant names the problem will disappear. I need some time to fix it

**Comment by gfriloux** [comment]
Oh sorry for not spotting this, i was just thinking it was different columns.
Im going to try to update these.

**Comment by gfriloux** [comment]
Ok you found the problem.
After updating all the authors having pipe inside there names, no more errors.
My only issue is that when adding a new books, and scrap infos, the pipe gets added, and the issue comes back (and creates a duplicate author name for the new book)

**Comment by OzzieIsaacs** [comment]
Should now work (at least better without 500 error). 
Please try.
The behavior of calibre seems not to be very consistent in this matter, sometimes the pipe is shown in the UI, sometimes not. When I have more time I will ask the calibre guys what the expected behavior is.

**Comment by gfriloux** [comment]
Hello, your fix also solves the issue on my side !
Thank you very much!

**Comment by gfriloux** [comment]
I have found another error that did raise after uploading some ebooks.
It also throws a 500 error after editing metadata (right after scrapping infos from google).

Do you want me to open a new issue ?

**Comment by OzzieIsaacs** [comment]
Yes please, and could you please paste the trace, thanks
