### ISSUE TITLE
[BUG] Updating metadata always fires a 500 error.

### ISSUE THREAD

**Issue by gfriloux** [janeczku/calibre-web#397]
It started suddently, after uploading a few comics.
This is not linked to #395 as there isn't pipes in authors.name. Going through /author and switch to another URI works perfectly fine.

Issue : When uploading a new ebook, i scrap its infos from google using the "Get metadata" button. Once i submit the metadata, calibre-web will throw a 500 error.

Refreshing the page will work, metadata will be correct.
calibre-web gives the following backtrace : 
```
nov. 28 14:53:49 friloux.me python[46335]: [2017-11-28 14:53:49,313] ERROR in app: Exception on /admin/book/341 [POST]
nov. 28 14:53:49 friloux.me python[46335]: Traceback (most recent call last):
nov. 28 14:53:49 friloux.me python[46335]:   File "/usr/share/webapps/calibre-web/vendor/flask/app.py", line 1982, in wsgi_app
nov. 28 14:53:49 friloux.me python[46335]:     response = self.full_dispatch_request()
nov. 28 14:53:49 friloux.me python[46335]:   File "/usr/share/webapps/calibre-web/vendor/flask/app.py", line 1614, in full_dispatch_request
nov. 28 14:53:49 friloux.me python[46335]:     rv = self.handle_user_exception(e)
nov. 28 14:53:49 friloux.me python[46335]:   File "/usr/share/webapps/calibre-web/vendor/flask/app.py", line 1517, in handle_user_exception
nov. 28 14:53:49 friloux.me python[46335]:     reraise(exc_type, exc_value, tb)
nov. 28 14:53:49 friloux.me python[46335]:   File "/usr/share/webapps/calibre-web/vendor/flask/_compat.py", line 33, in reraise
nov. 28 14:53:49 friloux.me python[46335]:     raise value
nov. 28 14:53:49 friloux.me python[46335]:   File "/usr/share/webapps/calibre-web/vendor/flask/app.py", line 1612, in full_dispatch_request
nov. 28 14:53:49 friloux.me python[46335]:     rv = self.dispatch_request()
nov. 28 14:53:49 friloux.me python[46335]:   File "/usr/share/webapps/calibre-web/vendor/flask/app.py", line 1598, in dispatch_request
nov. 28 14:53:49 friloux.me python[46335]:     return self.view_functions[rule.endpoint](**req.view_args)
nov. 28 14:53:49 friloux.me python[46335]:   File "/usr/share/webapps/calibre-web/cps/web.py", line 391, in decorated_view
nov. 28 14:53:49 friloux.me python[46335]:     return login_required(func)(*args, **kwargs)
nov. 28 14:53:49 friloux.me python[46335]:   File "/usr/share/webapps/calibre-web/vendor/flask_login/utils.py", line 228, in decorated_view
nov. 28 14:53:49 friloux.me python[46335]:     return func(*args, **kwargs)
nov. 28 14:53:49 friloux.me python[46335]:   File "/usr/share/webapps/calibre-web/cps/web.py", line 514, in inner
nov. 28 14:53:49 friloux.me python[46335]:     return f(*args, **kwargs)
nov. 28 14:53:49 friloux.me python[46335]:   File "/usr/share/webapps/calibre-web/cps/web.py", line 2864, in edit_book
nov. 28 14:53:49 friloux.me python[46335]:     book.author_sort = helper.get_sorted_author(input_authors[0])
nov. 28 14:53:49 friloux.me python[46335]: TypeError: 'map' object is not subscriptable
nov. 28 14:53:49 friloux.me python[46335]: ERROR:tornado.access:500 POST /admin/book/341 (127.0.0.1) 35.01ms
```

Here is the result of `select id,name from authors;` : 
```
58|Batem,Olivier Saive
5|Bellemare Pierre
7|Bellemare, Pierre
150|Bob De Groot
8|Christie Golden
48|Colman
1|Dennis Gluth
51|Dugomier
155|Fauche, Léturgie
144|Fauche,Léturgie
64|Franquin
9|George R.R. Martin
147|Gerra
13|Goodkind, Terry
10|Goodkind,Terry
143|Goscinny
63|Goscinny,Albert Uderzo
162|Goscinny,Morris
66|Goupil
45|GREG
158|Greg,Goscinny
156|Guylouis
157|Guylouis,Xavier Fauche,Jean Léturgie
167|Hergé
67|Jacot
152|Jean Léturgie,Yann Le Pennetier
166|Job
165|Lambil,Raoul Cauvin
160|Lodewijk,Vicq,Bob De Groot,Goscinny
55|Marais
56|Marais and Jérémie Kaminka
54|Marais,Jérémie Kaminka
16|Mark Millar,John Romita Jr
163|Morris
149|Nordmann
14|Oliver Bowden
146|Pennac,Benacquista
4|Pierre Bellemare
6|Pierre Bellemare, Jacques Antoine
164|Raoul Cauvin
60|René Goscinny,Albert Uderzo
36|Robinson Academy
46|Stéphane Colman
12|Terry Goodkind
148|Tonino Benacquista,Daniel Pennac,Achdé
65|Unknown
154|Van Banda
161|Vicq
159|Vidal
59|Xavier Fauche
57|Xavier Fauche,Adam
151|Xavier Fauche,Eric Adam
153|Xavier Fauche,Jean Léturgie
50|Yann
```

**Comment by OzzieIsaacs** [comment]
I improved the errorhandling for changing authorsname and title names a bit, you could try it again. For digging deeper into this problem I need some more informations: 
- the error is related to the sort_name column in the database, but this one is missing in your post
- which author is the author of book 341, which is causing the problem.

By the way: The intended way of having more than one author is by seperating them with a "&". After doing this, you could get rid of all the double entries like: no 57, no. 59, no. 151 and no 153 (Has nothing to do with the issue, just for information)

**Comment by gfriloux** [comment]
> the error is related to the sort_name column in the database, but this one is missing in your post
Ok, i can see Pipes too in the `authors.sort` column:
```
sqlite> select sort from authors order by id;
sort
Gluth, Dennis
Bellemare, Pierre
Pierre, Bellemare
Pierre Bellemare, Jacques Antoine
Bellemare, Pierre
Golden, Christie
George R.R. Martin
Goodkind,Terry
Goodkind, Terry
Goodkind| Terry
Bowden, Oliver
Mark Millar|John Romita Jr
Academy, Robinson
GREG
Stéphane Colman
Colman
Yann
Dugomier
Marais|Jérémie Kaminka
Marais
Marais|Jérémie Kaminka
Xavier Fauche|Adam
Batem|Olivier Saive
Xavier Fauche
René Goscinny|Albert Uderzo
Goscinny|Albert Uderzo
Franquin,
Unknown,
Goupil
Jacot,
Goscinny
Fauche|Léturgie
Pennac|Benacquista
Gerra
Tonino Benacquista|Daniel Pennac|Achdé
Nordmann
Bob De Groot
Xavier Fauche|Eric Adam
Jean Léturgie|Yann Le Pennetier
Xavier Fauche|Jean Léturgie
Van Banda
Fauche|Léturgie
Guylouis
Guylouis|Xavier Fauche|Jean Léturgie
Greg|Goscinny
Vidal
Lodewijk|Vicq|Bob De Groot|Goscinny
Vicq
Goscinny|Morris
Morris
Raoul Cauvin
Lambil|Raoul Cauvin
Job
Hergé
Herge
Hergé et Rodier
Agatha Christie
```
I am going to edit these to see if it fixes.

> which author is the author of book 341, which is causing the problem.
Agatha Christie : 
```
sqlite> select * from authors where name LIKE "Agatha%";
id|name|sort|link
170|Agatha Christie|Agatha Christie|
```
But i think its wrong to focus on it : it does that with just everybook, not only hers.

> By the way: The intended way of having more than one author is by seperating them with a "&". 
Well, authors is filled with what calibre-web fetches from google, i do not edit this value myself.

**Comment by gfriloux** [comment]
Here is the logs i get with latest code, when importing a book (without editing the DB) : 
```
déc. 01 13:01:48 friloux.me python[50099]: /usr/share/webapps/calibre-web/vendor/sqlalchemy/sql/compiler.py:624: SAWarning: Can't resolve label reference 'books_authors_link.author'; converting to text() (this warning may be suppressed after 10 occurrences)
déc. 01 13:01:48 friloux.me python[50099]:   util.ellipses_string(element.element))
déc. 01 13:01:48 friloux.me python[50099]: [2017-12-01 13:01:48,458] ERROR in app: Exception on /admin/book/390 [POST]
déc. 01 13:01:48 friloux.me python[50099]: Traceback (most recent call last):
déc. 01 13:01:48 friloux.me python[50099]:   File "/usr/share/webapps/calibre-web/vendor/flask/app.py", line 1982, in wsgi_app
déc. 01 13:01:48 friloux.me python[50099]:     response = self.full_dispatch_request()
déc. 01 13:01:48 friloux.me python[50099]:   File "/usr/share/webapps/calibre-web/vendor/flask/app.py", line 1614, in full_dispatch_request
déc. 01 13:01:48 friloux.me python[50099]:     rv = self.handle_user_exception(e)
déc. 01 13:01:48 friloux.me python[50099]:   File "/usr/share/webapps/calibre-web/vendor/flask/app.py", line 1517, in handle_user_exception
déc. 01 13:01:48 friloux.me python[50099]:     reraise(exc_type, exc_value, tb)
déc. 01 13:01:48 friloux.me python[50099]:   File "/usr/share/webapps/calibre-web/vendor/flask/_compat.py", line 33, in reraise
déc. 01 13:01:48 friloux.me python[50099]:     raise value
déc. 01 13:01:48 friloux.me python[50099]:   File "/usr/share/webapps/calibre-web/vendor/flask/app.py", line 1612, in full_dispatch_request
déc. 01 13:01:48 friloux.me python[50099]:     rv = self.dispatch_request()
déc. 01 13:01:48 friloux.me python[50099]:   File "/usr/share/webapps/calibre-web/vendor/flask/app.py", line 1598, in dispatch_request
déc. 01 13:01:48 friloux.me python[50099]:     return self.view_functions[rule.endpoint](**req.view_args)
déc. 01 13:01:48 friloux.me python[50099]:   File "/usr/share/webapps/calibre-web/cps/web.py", line 393, in decorated_view
déc. 01 13:01:48 friloux.me python[50099]:     return login_required(func)(*args, **kwargs)
déc. 01 13:01:48 friloux.me python[50099]:   File "/usr/share/webapps/calibre-web/vendor/flask_login/utils.py", line 228, in decorated_view
déc. 01 13:01:48 friloux.me python[50099]:     return func(*args, **kwargs)
déc. 01 13:01:48 friloux.me python[50099]:   File "/usr/share/webapps/calibre-web/cps/web.py", line 516, in inner
déc. 01 13:01:48 friloux.me python[50099]:     return f(*args, **kwargs)
déc. 01 13:01:48 friloux.me python[50099]:   File "/usr/share/webapps/calibre-web/cps/web.py", line 2946, in edit_book
déc. 01 13:01:48 friloux.me python[50099]:     book.author_sort = helper.get_sorted_author(input_authors[0])
déc. 01 13:01:48 friloux.me python[50099]: TypeError: 'map' object is not subscriptable
déc. 01 13:01:49 friloux.me python[50099]: ERROR:tornado.access:500 POST /admin/book/390 (127.0.0.1) 140.79ms
```

**Comment by gfriloux** [comment]
I have now updated the DB.
There isnt any entry in the authors table with a pipe in the columns `sort` or `name` : 
```
sqlite> select id,name from authors where name LIKE "%|%";
sqlite> select id,sort from authors where sort LIKE "%|%";
sqlite>
```

**Comment by OzzieIsaacs** [comment]
Ok. 
May I come back to your inital offer of sending me the metadata.db (per email to the adress given on my page)? If you are still willing to do this? I think then I can find it quickly.

**Comment by gfriloux** [comment]
I just emailed it to you.
Thx for the time you spend on solving these reports!

**Comment by gabriellluz** [comment]
This bug is happening to me, too. It started after updating.

**Comment by OzzieIsaacs** [comment]
For me its working.

Are you running on python2 or python3?

**Comment by gfriloux** [comment]
I use python3 on archlinux.

**Comment by OzzieIsaacs** [comment]
Okay, python3 is not officially support, I'm using python 2.7.
I'll take a look what the reason is behind.

**Comment by gfriloux** [comment]
I first tried to make it work on python2 and failed (my newbie skills with python are probably at cause), and strangely, i got it running smoothly with python3 (except for those 2 bugs)

**Comment by OzzieIsaacs** [comment]
It only worked on coincidence in the past, but should now work really.
Normally the project is python 3 compatible, but its hard to test everything, and to keep everything running under every circumstances

**Comment by gfriloux** [comment]
I confirm the issue is solved since your commit.
Nice work!

I'll continue to report bugs as i spot them (and try to collect as much info as i can), that's the best help i can offer actually.

**Comment by OzzieIsaacs** [comment]
Feedback is always welcome, every bug found is a small step towards a better product
