### ISSUE TITLE
Problem: Installation in Synology without Docker

### ISSUE THREAD

**Issue by yabdali** [janeczku/calibre-web#398]
I installed your app by using git clone, installation directory is /volume1/web/calibre-web.  I did run the dependencies script (requirements.txt) then run the startup script nohup python cps.py but when I tried to access http://localip:8083 or http://localip:8083/opds I keep getting This site can’t be reached.   I tried using ssh wget but got Connecting to mylocalip:8083... failed: Connection refused.

I tried creating a virtual host pointing to web/calibre-web but I got error 403!

I am running Apache 2.2, php 7.0 and I have http group set with read/write permissions on the calibre-web folder. 

I am running the latest DSM 6.1.4-15217 Update 2

Appreciate your help and support, thanks.

**Comment by OzzieIsaacs** [comment]
I don't know the synology, so I can only give some basic support. 
Is there some sort of firewall active, maybe blocking the port? Is the port 8083 maybe in use with some other application? Is there anything relevant in the logfile calibre-web? 
On my linux system nohup generates an outputfile "nohup.out" is there anything (traceback or so) in there?
In the configuration with apache the error 403 (forbidden) points towards an additional configuration problem in apache. I know to less about synology to give further hints

**Comment by yabdali** [comment]
Thanks for your response. Here are more details. 403 There is an error while processing this request.

Virtual host (port based) 8083
web directory: web/calibre-web

Started the app using ssh: python cps.py
_ssh using netstat shows the following_
tcp        0      0 192.168.88.191:8083     192.168.88.108:51104    ESTABLISHED
tcp        0      0 192.168.88.191:8083     192.168.88.108:51107    TIME_WAIT  
tcp        0      0 192.168.88.191:8083     192.168.88.108:51105    TIME_WAIT  

_cat nohup.out_
Traceback (most recent call last):
  File "cps.py", line 13, in <module>
    from cps import web
  File "/volume1/web/calibre-web/cps/web.py", line 236, in <module>
    import uploader
  File "/volume1/web/calibre-web/cps/uploader.py", line 8, in <module>
    import book_formats
  File "/volume1/web/calibre-web/cps/book_formats.py", line 14, in <module>
    from wand.image import Image
  File "/volume1/web/calibre-web/vendor/wand/image.py", line 20, in <module>
    from .api import MagickPixelPacket, libc, libmagick, library
  File "/volume1/web/calibre-web/vendor/wand/api.py", line 180, in <module>
    libraries = load_library()
  File "/volume1/web/calibre-web/vendor/wand/api.py", line 121, in load_library
    for libwand_path, libmagick_path in library_paths():
  File "/volume1/web/calibre-web/vendor/wand/api.py", line 109, in library_paths
    libwand = ctypes.util.find_library('MagickWand' + suffix)
  File "/usr/lib/python2.7/ctypes/util.py", line 242, in find_library
    raise RuntimeError("can not find library %s" % name)
RuntimeError: can not find library MagickWand

_cat calibre-web.log_
[2017-11-27 23:19:36,964] {/volume1/web/calibre-web/cps/web.py:228} INFO - Starting Calibre Web...
[2017-11-27 23:21:25,297] {/volume1/web/calibre-web/cps/web.py:228} INFO - Starting Calibre Web...
[2017-11-27 23:27:14,751] {/volume1/web/calibre-web/cps/web.py:228} INFO - Starting Calibre Web...
[2017-11-27 23:41:41,064] {/volume1/web/calibre-web/cps/web.py:228} INFO - Starting Calibre Web...
[2017-11-27 23:55:35,119] {/volume1/web/calibre-web/cps/web.py:228} INFO - Starting Calibre Web...
[2017-11-29 01:15:12,916] {/volume1/web/calibre-web/cps/web.py:228} INFO - Starting Calibre Web...
[2017-11-29 01:32:31,006] {/volume1/web/calibre-web/cps/web.py:228} INFO - Starting Calibre Web...

_cat /var/log/httpd/apache22-error_log_
2017-11-29T23:41:36+04:00 DiskStation [Wed Nov 29 23:41:36 2017] [notice] Digest: generating secret for digest authentication ...
2017-11-29T23:41:36+04:00 DiskStation [Wed Nov 29 23:41:36 2017] [notice] Digest: done
2017-11-29T23:41:36+04:00 DiskStation [Wed Nov 29 23:41:36 2017] [notice] Apache/2.2.34 (Unix) mod_fastcgi/mod_fastcgi-SNAP-0910052141 conf
igured -- resuming normal operations
2017-11-29T23:41:36+04:00 DiskStation [Wed Nov 29 23:41:36 2017] [notice] FastCGI: process manager initialized (pid 28051)
2017-11-29T23:41:48+04:00 DiskStation [Wed Nov 29 23:41:48 2017] [error] [client 192.168.88.108] Directory index forbidden by Options direc
tive: /volume1/web/calibre-web/
2017-11-29T23:41:49+04:00 DiskStation [Wed Nov 29 23:41:49 2017] [error] [client 192.168.88.108] File does not exist: /volume1/web/calibre-
web/missing, referer: http://192.168.88.191:8083/
2017-11-29T23:41:50+04:00 DiskStation [Wed Nov 29 23:41:50 2017] [error] [client 192.168.88.108] File does not exist: /volume1/web/calibre-
web/favicon.ico, referer: http://192.168.88.191:8083/
2017-11-29T23:44:47+04:00 DiskStation [Wed Nov 29 23:44:47 2017] [error] [client 192.168.88.108] Directory index forbidden by Options direc
tive: /volume1/web/calibre-web/
2017-11-29T23:44:47+04:00 DiskStation [Wed Nov 29 23:44:47 2017] [error] [client 192.168.88.108] File does not exist: /volume1/web/calibre-
web/missing, referer: http://192.168.88.191:8083/
2017-11-29T23:44:52+04:00 DiskStation [Wed Nov 29 23:44:52 2017] [error] [client 192.168.88.108] Directory index forbidden by Options direc
tive: /volume1/web/calibre-web/
2017-11-29T23:44:52+04:00 DiskStation [Wed Nov 29 23:44:52 2017] [error] [client 192.168.88.108] File does not exist: /volume1/web/calibre-
web/missing, referer: http://192.168.88.191:8083/

**Comment by yabdali** [comment]
Additional notes:
I have lazylibrarian installed using the same method: git clone and its running fine.  I also have bicbucstriim and COPS installed using synocommunity packages on different ports without problems.

**Comment by idalin** [comment]
You don't have ImageMagick installed in your synology.  Or maybe wrong version.
docker is a much easier way to install calibre-web in DSM.

**Comment by OzzieIsaacs** [comment]
@idalin is absolutly right: There is a problem with with the ImageMagick installation. Seems that there are parts missing or are wrong version. "MagickWand" points to the python library "Wand". 
For testing purpose it could be easier to uninstall "wand" dependency.

For the non working apache, there are additional problems:
"Directory index forbidden by Options directive: /volume1/web/calibre-web/ " means that some restrictions are in place for this folder:
Adding: 
<DirectoryMatch "/web/calibre-web/">
    Order allow,deny
    Allow from all
</DirectoryMatch> 

to the virtual host configuration could help (I'm not sure if volume1 has to be included in the path for the directory match?).

**Comment by yabdali** [comment]
Thanks for the support and inputs, I decided to stop after spending few days wasted in making it work.  Synology doesnt seem to have a direct way of integrating MagickWand with PHP.  I literally read most of the documentation and gone through most of the cases submitted on different forums.

I finally managed to get it installed and running in a WD Mycloud box that was sitting idle for long time. Again, thanks.

**Comment by andrewchenshx** [comment]
my Synology DS218 encounter the same "

> RuntimeError: can not find library MagickWand

"error. anyone comes up with a solution?

**Comment by OzzieIsaacs** [comment]
Please try to delete/rename the folder „wand“ in the vendor folder

**Comment by OzzieIsaacs** [comment]
I had another idea, please try the newest commit

**Comment by OzzieIsaacs** [comment]
No feedback for long time, closing issue
