### ISSUE TITLE
sqlite3.OperationalError database is locked 

### ISSUE THREAD

**Issue by jiangjiangflies** [janeczku/calibre-web#415]
When I copied some books to calibre library, I couldn't connect my server anymore. The error message is "sqlite3.OperationalError) database is locked ".

**Comment by OzzieIsaacs** [comment]
Calibre is not made for doing concurrent database accesses. It's not recommended to change things in calibre and in parallel do things in calibre-web. After closing calibre it should work as expected, again.

**Comment by OzzieIsaacs** [comment]
No repsonse for long time

**Comment by jiangjiangflies** [comment]
I used calibredb from command and so there is no calibre running. But I still can't start calibre-web. The full output is as follows:
```
Traceback (most recent call last):
  File "cps.py", line 13, in <module>
    from cps import web
  File "/home/calibre-web/cps/web.py", line 36, in <module>
    import ub
  File "/home/calibre-web/cps/ub.py", line 696, in <module>
    clean_database()
  File "/home/calibre-web/cps/ub.py", line 612, in clean_database
    session.query(RemoteAuthToken).filter(now > RemoteAuthToken.expiration).delete()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 3247, in delete
    delete_op.exec_()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/persistence.py", line 1326, in exec_
    self._do_exec()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/persistence.py", line 1518, in _do_exec
    self._execute_stmt(delete_stmt)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/persistence.py", line 1333, in _execute_stmt
    mapper=self.mapper)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 1176, in execute
    bind, close_with_result=True).execute(clause, params or {})
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 948, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/elements.py", line 269, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1060, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1200, in _execute_context
    context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception
    exc_info
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/default.py", line 507, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked [SQL: u'DELETE FROM remote_auth_token WHERE remote_auth_token.expiration < ?'] [parameters: ('2018-05-06 14:51:22.264179',)] (Background on this error at: http://sqlalche.me/e/e3q8)

```

**Comment by jiangjiangflies** [comment]
I deleted the static files in /cps/static and it works fine now.
