### ISSUE TITLE
Not able to see Book details 

### ISSUE THREAD

**Issue by saitoh183** [janeczku/calibre-web#429]
```
::ffff:192.168.13.198 - - [2018-01-06 19:27:33] "GET /calibreweb/ HTTP/1.0" 200 76535 0.228185
[2018-01-06 19:27:37,438] ERROR in app: Exception on /book/571 [GET]
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/calibre-web/app/cps/web.py", line 393, in decorated_view
    return login_required(func)(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/flask_login/utils.py", line 228, in decorated_view
    return func(*args, **kwargs)
  File "/calibre-web/app/cps/web.py", line 1400, in show_book
    ub.ReadBook.book_id == book_id)).all()
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2703, in all
    return list(self)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2855, in __iter__
    return self._execute_and_instances(context)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2878, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 945, in execute
    return meth(self, multiparams, params)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 263, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1053, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1189, in _execute_context
    context)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1402, in _handle_dbapi_exception
    exc_info
  File "/usr/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 470, in do_execute
    cursor.execute(statement, parameters)
DatabaseError: (sqlite3.DatabaseError) database disk image is malformed [SQL: u'SELECT book_read_link.id AS book_read_link_id, book_read_link.book_id AS book_read_link_book_id, book_read_link.user_id AS book_read_link_user_id, book_read_link.is_read AS book_read_link_is_read \nFROM book_read_link \nWHERE book_read_link.user_id = ? AND book_read_link.book_id = ?'] [parameters: (3, 571)]
```

![image](https://user-images.githubusercontent.com/1534197/34645326-121e6fa2-f318-11e7-9156-9f7950bd2527.png)

In using the latest docker image. I thought it could because i was using a older image. but i get the same problem...i dont know when it started to do this. From what i understand is that when i restart the container, if there is a updated version of calibre-web it will pull it before starting?

**Comment by OzzieIsaacs** [comment]
The error hints towards a defective calibre-db. Please try to open the library with calibre and start the database repair function within calibre.

**Comment by saitoh183** [comment]
> The error hints towards a defective calibre-db. Please try to open the library with calibre and start the database repair function within calibre.

I did a library check and no errors were returned. So im creating a new calibre library and copying all the books over to it so that i create a new metadata.db. Now in calibre-web (docker version) I just dont want to loose my books read data and my users that have signed up. Do i need to modify anything in the app.db file or just point to the new location in the db configuration?

**Comment by OzzieIsaacs** [comment]
Just point to the new calibre-db. But be aware calibre-web references to the book by the ID and not the books titles for read data. So if your new calibre-db has the books stored in a different order, than the information is gone now.

**Comment by saitoh183** [comment]
I created a brand new library and then moved all books from one library to another. Then I left calibre on the new library and started calibre-web and I get the same problem. How does it know which library I'm using? Is it using the last library I left connected to Calibre?

**Comment by OzzieIsaacs** [comment]
In the admin page in the config section you can change the db settings.

**Comment by OzzieIsaacs** [comment]
No feedback for long time
