### ISSUE TITLE
gdrive authentication missing a /

### ISSUE THREAD

**Issue by RXWatcher1** [janeczku/calibre-web#431]
example:
my domain is calibre.domain.com in the example below.
I have tried:
add an additional / to the end of the Calibre Base URL entry and that didnt help.
the URLs in the API are correct. You can't have a trailing / in the Authorized JavaScript origins(https://calibre.domain.com) and the Authorized redirect URIs has the correct: https://calibre.domain.com/gdrive/callback in it.

FlowExchangeError: invalid_requestInvalid parameter value for redirect_uri: Non-public domains not allowed: https://calibre.domain.comgdrive/callback
::ffff:172.17.0.14 - - [2018-01-09 23:33:05] "GET /gdrive/callback?code=<removed code> HTTP/1.1" 500 412 0.038928
[2018-01-09 23:33:20,482] ERROR in app: Exception on /gdrive/callback [GET]
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/calibre-web/app/cps/web.py", line 1542, in google_drive_callback
    credentials = Gauth.Instance().auth.flow.step2_exchange(auth_code)
  File "/usr/lib/python2.7/site-packages/oauth2client/_helpers.py", line 133, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/oauth2client/client.py", line 2089, in step2_exchange
    raise FlowExchangeError(error_msg)

It appears to be here: 
if create_new_yaml:
            with open('settings.yaml', 'w') as f:
                with open('gdrive_template.yaml', 'r') as t:
                    f.write(t.read() % {'client_id': content.config_google_drive_client_id, 'client_secret': content.config_google_drive_client_secret,
                     "redirect_uri": content.config_google_drive_calibre_url_base + 'gdrive/callback'})

There should be a / before gdrive. By editing this and redoing it I was able to authenticate however now Enable Watch of Metadata.db fails.

**Comment by OzzieIsaacs** [comment]
I changed it, but couldn't test it completely.
