### ISSUE TITLE
ImportError: No module named singledispatch on python cps.py command

### ISSUE THREAD

**Issue by halethrain** [janeczku/calibre-web#433]
Running Ubuntu 16.04, I have installed all dependencies but receive this error when I attempt to launch. I am using Python 3.5 and have confirmed singledispatch to be present

Traceback (most recent call last):
  File "cps.py", line 18, in <module>
    from tornado.wsgi import WSGIContainer
  File "/opt/calibre-web/vendor/tornado/wsgi.py", line 42, in <module>
    from tornado import web
  File "/opt/calibre-web/vendor/tornado/web.py", line 85, in <module>
    from tornado import gen
  File "/opt/calibre-web/vendor/tornado/gen.py", line 99, in <module>
    from singledispatch import singledispatch  # backport
ImportError: No module named singledispatch

**Comment by OzzieIsaacs** [comment]
I can't reproduce the issue. But what I read from the code: In py3.4 and upwards you should have a module "functools", which isn't listed by pip, because it's part of the python installation.  In python3 you should never get to "line 99 in gen.py", because this line is for python2.
Could you please try the following statement in a python3 console:
from functools import singledispatch  
(There should be no error/traceback)
On my system the file (functools.py) is located in /usr/lib/python3.x. You can get a version from, if its missing, but I'm not sure if it is the only missing file: https://raw.githubusercontent.com/python/cpython/master/Lib/functools.py
And I'm not sure if this is the right way.
