### ISSUE TITLE
AttributeError: module 'smtplib' has no attribute 'stderr'

### ISSUE THREAD

**Issue by ovv** [janeczku/calibre-web#436]
Hi. Great piece of software :+1: !

While testing the send mail configuration I got this error.

```
jan 12 20:11:43 calibre-1 python[3823]: [2018-01-12 20:11:43,901] ERROR in app: Exception on /admin/mailsettings [POST]
jan 12 20:11:43 calibre-1 python[3823]: Traceback (most recent call last):
jan 12 20:11:43 calibre-1 python[3823]:   File "/home/calibre/.env/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
jan 12 20:11:43 calibre-1 python[3823]:     response = self.full_dispatch_request()
jan 12 20:11:43 calibre-1 python[3823]:   File "/home/calibre/.env/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
jan 12 20:11:43 calibre-1 python[3823]:     rv = self.handle_user_exception(e)
jan 12 20:11:43 calibre-1 python[3823]:   File "/home/calibre/.env/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
jan 12 20:11:43 calibre-1 python[3823]:     reraise(exc_type, exc_value, tb)
jan 12 20:11:43 calibre-1 python[3823]:   File "/home/calibre/.env/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
jan 12 20:11:43 calibre-1 python[3823]:     raise value
jan 12 20:11:43 calibre-1 python[3823]:   File "/home/calibre/.env/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
jan 12 20:11:43 calibre-1 python[3823]:     rv = self.dispatch_request()
jan 12 20:11:43 calibre-1 python[3823]:   File "/home/calibre/.env/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
jan 12 20:11:43 calibre-1 python[3823]:     return self.view_functions[rule.endpoint](**req.view_args)
jan 12 20:11:43 calibre-1 python[3823]:   File "/home/calibre/.env/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
jan 12 20:11:43 calibre-1 python[3823]:     return func(*args, **kwargs)
jan 12 20:11:43 calibre-1 python[3823]:   File "/home/calibre/web/cps/web.py", line 472, in inner
jan 12 20:11:43 calibre-1 python[3823]:     return f(*args, **kwargs)
jan 12 20:11:43 calibre-1 python[3823]:   File "/home/calibre/web/cps/web.py", line 2743, in edit_mailsettings
jan 12 20:11:43 calibre-1 python[3823]:     result = helper.send_test_mail(current_user.kindle_mail)
jan 12 20:11:43 calibre-1 python[3823]:   File "/home/calibre/web/cps/helper.py", line 198, in send_test_mail
jan 12 20:11:43 calibre-1 python[3823]:     return send_raw_email(kindle_mail, msg)
jan 12 20:11:43 calibre-1 python[3823]:   File "/home/calibre/web/cps/helper.py", line 167, in send_raw_email
jan 12 20:11:43 calibre-1 python[3823]:     org_stderr = smtplib.stderr
jan 12 20:11:43 calibre-1 python[3823]: AttributeError: module 'smtplib' has no attribute 'stderr'
jan 12 20:11:43 calibre-1 python[3823]: ERROR:tornado.access:500 POST /admin/mailsettings (127.0.0.1) 16.32ms
```

Tested with python `3.6.4`.

Commenting line 167, 168 & 184 from [helper.py](https://github.com/janeczku/calibre-web/blob/master/cps/helper.py#L167-L184) fixed the issue.

Thanks for looking into this.

**Comment by OzzieIsaacs** [comment]
Problem with python 3. Is fixed now.
