### ISSUE TITLE
Does calibre-web now lock the DB (preventing books from being added)?

### ISSUE THREAD

**Issue by simkin** [janeczku/calibre-web#440]
It seems Books are no longer getting added via cronjob if calibre-web is running. Is this intentional?
root@nas:/dikkert/tmp/books# **/opt/calibre/calibredb add --library-path=/dikkert/Server/Books Woodrow\,\ Margje\ -\ Verwoest\ 2017.epub**
```
Traceback (most recent call last):
  File "site.py", line 77, in main
  File "site-packages/calibre/db/cli/main.py", line 253, in main
  File "site-packages/calibre/db/cli/main.py", line 55, in run_cmd
  File "site-packages/calibre/db/cli/cmd_add.py", line 374, in main
  File "site-packages/calibre/db/cli/cmd_add.py", line 152, in do_add
  File "site-packages/calibre/db/cli/main.py", line 190, in run
  File "site-packages/calibre/db/cli/main.py", line 177, in db
  File "site-packages/calibre/db/legacy.py", line 81, in __init__
  File "site-packages/calibre/db/legacy.py", line 48, in create_backend
  File "site-packages/calibre/db/backend.py", line 384, in __init__
  File "site-packages/calibre/db/schema_upgrades.py", line 19, in __init__
  File "site-packages/calibre/db/backend.py", line 844, in execute
  File "src/cursor.c", line 236, in resetcursor
BusyError: BusyError: database is locked
```
root@nas:/dikkert/tmp/books# **service calibre-web stop**
root@nas:/dikkert/tmp/books# **/opt/calibre/calibredb add --library-path=/dikkert/Server/Books Woodrow\,\ Margje\ -\ Verwoest\ 2017.epub**
```
The following books were not added as they already exist in the database (see --duplicates option):
  Verwoest
    /dikkert/tmp/books/Woodrow, Margje - Verwoest 2017.epub
```

**Comment by simkin** [comment]
unable to reproduce, cannot explain why it was locked

**Comment by georgecarstoiu** [comment]
Ran into same issue. Installed Calibre Web and then Calibre told me that the database is locked and that it needs to rebuild it.

**Comment by toozej** [comment]
If you're mounting your calibre library over CIFS, give https://coderwall.com/p/zrxobw/calibre-libraries-on-nas a try. Fixed this issue for me after unmounting my books share, adjusting the CIFS mount in /etc/fstab, remounting the share and restarting the container(s).

**Comment by psyciknz** [comment]
Just wanted to add a comment, that I had the same issue (raspberry Pi + docker + CIFS) and adding nobrl as mentioned in the above link also worked.

**Comment by MrCaringi** [comment]
yes! it worked for mi too! thanks
https://github.com/janeczku/calibre-web/issues/440

**Comment by theg1nger** [comment]
@toozej Thanks! That did it!

**Comment by sherwinmartin** [comment]
on ubuntu server 18.04, the nobrl flagged worked. but i had to restart the server in order for the change to take affect. thanks
