### ISSUE TITLE
Discover Button Broken

### ISSUE THREAD

**Issue by bhanderson** [janeczku/calibre-web#444]
Using the technosoft2000/calibre-web docker container 
```
[2018-01-31 06:45:14,078] ERROR in app: Exception on /discover [GET]
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/calibre-web/app/cps/web.py", line 393, in decorated_view
    return login_required(func)(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/flask_login/utils.py", line 228, in decorated_view
    return func(*args, **kwargs)
  File "/calibre-web/app/cps/web.py", line 1194, in discover
    return render_title_template('discover.html', entries=entries, pagination=pagination, title=_(u"Random Books"))
  File "/calibre-web/app/cps/web.py", line 618, in render_title_template
    return render_template(instance=config.config_calibre_web_title, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/flask/templating.py", line 134, in render_template
    context, ctx.app)
  File "/usr/lib/python2.7/site-packages/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/calibre-web/app/cps/templates/discover.html", line 1, in top-level template code
    {% extends "layout.html" %}
  File "/calibre-web/app/cps/templates/layout.html", line 172, in top-level template code
    {% block body %}{% endblock %}
  File "/calibre-web/app/cps/templates/discover.html", line 18, in block "body"
    <p class="author"><a href="{{url_for('author', book_id=entry.authors[0].id) }}">{{entry.authors[0].name}}</a></p>
  File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 430, in getattr
    return getattr(obj, attribute)
UndefinedError: sqlalchemy.orm.collections.InstrumentedList object has no element 0
::ffff:172.17.0.1 - - [2018-01-31 06:45:14] "GET /discover HTTP/1.0" 500 431 0.312121
```

This prints in the docker log when I press the discover button

**Comment by OzzieIsaacs** [comment]
I fixed it. Until its merged to the docker container, the error is still happening to you. 
You could open calibre, there should be at least one book having no author. If you enter a authors name at this book, the error should disapear.

**Comment by bhanderson** [comment]
Awesome thanks!
