### ISSUE TITLE
No cover images displayed

### ISSUE THREAD

**Issue by bannmann** [janeczku/calibre-web#46]
With my Calibre library, no cover image can be displayed. From the traceback shown below, I guess you should use unicode encoding when constructing the file system path for serving an image:

```
ERROR:cps.web:Exception on /cover/Ellen Porath/Der Bund der Drachenlanze 9 - Stahl (165) [GET]
Traceback (most recent call last):
  File "C:\Program Files\Calibre2\calibre-web-master\vendor\flask\app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Program Files\Calibre2\calibre-web-master\vendor\flask\app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Program Files\Calibre2\calibre-web-master\vendor\flask\app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Program Files\Calibre2\calibre-web-master\vendor\flask\app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Program Files\Calibre2\calibre-web-master\vendor\flask\app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Program Files\Calibre2\calibre-web-master\vendor\flask_login.py", line 717, in decorated_view
    return func(*args, **kwargs)
  File "C:\Program Files\Calibre2\calibre-web-master\cps\web.py", line 529, in get_cover
    return send_from_directory(os.path.join(config.DB_ROOT, cover_path), "cover.jpg")
  File "C:\Python27\lib\ntpath.py", line 85, in join
    result_path = result_path + p_path
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 9: ordinal not in range(128)
ERROR:tornado.access:500 GET /cover/Ellen%20Porath/Der%20Bund%20der%20Drachenlanze%209%20-%20Stahl%20%28165%29 (::1) 5.00ms
```

Note that the image URLs referenced in the generated HTML looked normal to me.

**Comment by OzzieIsaacs** [comment]
Please try this one
https://github.com/OzzieIsaacs/calibre-web
Should be working now

**Comment by cervinko** [comment]
fix has been merged. @bannmann is this resolved?
