### ISSUE TITLE
Can't set books database path without crashing

### ISSUE THREAD

**Issue by duckduckquack** [janeczku/calibre-web#464]
Trying to setup Calibre in a docker instance, works fine on first "boot" but setting the books db path throws a 500 error, only way i can get around it is to delete and start over? Is there a way to check the path outside of the web config? 

Here is the error it throws after you set the path.
`
[2018-03-11 15:49:21,659] {/usr/lib/python2.7/site-packages/flask/app.py:1560} ERROR - Exception on /config [POST]
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/app/calibre-web/cps/web.py", line 486, in inner
    return f(*args, **kwargs)
  File "/app/calibre-web/cps/web.py", line 2469, in basic_configuration
    return configuration_helper(1)
  File "/app/calibre-web/cps/web.py", line 2631, in configuration_helper
    if not db.setup_db():
  File "/app/calibre-web/cps/db.py", line 335, in setup_db
    cc = conn.execute("SELECT id, datatype FROM custom_columns")
  File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 942, in execute
    return self._execute_text(object, multiparams, params)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1104, in _execute_text
    statement, parameters
  File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1200, in _execute_context
    context)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception
    exc_info
  File "/usr/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 507, in do_execute
    cursor.execute(statement, parameters)
OperationalError: (sqlite3.OperationalError) no such table: custom_columns [SQL: 'SELECT id, datatype FROM custom_columns'] (Background on this error at: http://sqlalche.me/e/e3q8)
`

**Comment by OzzieIsaacs** [comment]
Calibre-Web is made for using an existing Calibre dB, not for creating a new one. Please use Calibre to create a database and point in calibre-web to the location of the than existing database (metadata.db)

**Comment by duckduckquack** [comment]
doh! my bad, missed that part...
