### ISSUE TITLE
Latest Update (03-31-18) gives me 500 Internal Server Error

### ISSUE THREAD

**Issue by teflontoni** [janeczku/calibre-web#476]
`Traceback (most recent call last):
  File "/opt/weblibrary/vendor/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/weblibrary/vendor/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/weblibrary/vendor/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/weblibrary/vendor/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/weblibrary/vendor/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/weblibrary/cps/web.py", line 393, in decorated_view
    return login_required(func)(*args, **kwargs)
  File "/opt/weblibrary/vendor/flask_login/utils.py", line 228, in decorated_view
    return func(*args, **kwargs)
  File "/opt/weblibrary/cps/web.py", line 1097, in index
    title=_(u"Recently Added Books"))
  File "/opt/weblibrary/cps/web.py", line 618, in render_title_template
    return render_template(instance=config.config_calibre_web_title, *args, **kwargs)
  File "/opt/weblibrary/vendor/flask/templating.py", line 134, in render_template
    context, ctx.app)
  File "/opt/weblibrary/vendor/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/opt/weblibrary/vendor/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/opt/weblibrary/vendor/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/weblibrary/cps/templates/layout.html", line 104, in template
    <span>{{_('please don't refresh the page')}}</span>.
TemplateSyntaxError: expected token ',', got 't'
ERROR:tornado.access:500 GET // (::1) 276.56ms
`

What can I do to get calibre-web up and running again?

**Comment by Kyosfonica** [comment]
On file /opt/weblibrary/cps/templates/layout.html add \ on line 104:
Leave it like this:
<span>{{_('please don\'t refresh the page')}}</span>

**Comment by OzzieIsaacs** [comment]
Sorry, fixed it

**Comment by teflontoni** [comment]
thanks, guys
