### ISSUE TITLE
sqlalchemy.exc.OperationalError at startup on QNAP-NAS

### ISSUE THREAD

**Issue by gelsas** [janeczku/calibre-web#477]
I want to manage my ebooks via this and have a QNAP NAS, can I install this on it somehow ?

**Comment by OzzieIsaacs** [comment]
This question is very unspecific.
Do you have shell access (via ssh?). 
Clone the repro to a folder. 
Install python if not already done, install dependencies like described in the readme. 
Start the program.

**Comment by ltjdym** [comment]
Same question. _m going to try using linux station I guess.._

**Comment by OzzieIsaacs** [comment]
Please describe the exact problem, otherwise I will close the issue.

**Comment by gelsas** [comment]
I will later (currently not on pc) post the Error I am getting while trying to install  this.

**Comment by gelsas** [comment]
This is the error I am getting when trying to run python cps.py :

`Successfully built Flask-Babel Flask-Login Flask-Principal iso-639 PyPDF2 SQLAlchemy tornado blinker itsdangerous MarkupSafe
Installing collected packages: pytz, Babel, itsdangerous, MarkupSafe, Jinja2, Werkzeug, click, Flask, Flask-Babel, Flask-Login, blinker, Flask-Principal, iso-639, PyPDF2, idna, urllib3, certifi, chardet, requests, SQLAlchemy, futures, six, singledispatch, backports-abc, tornado, Wand, unidecode
Successfully installed Babel-2.5.3 Flask-0.12.2 Flask-Babel-0.11.1 Flask-Login-0.4.1 Flask-Principal-0.4.0 Jinja2-2.10 MarkupSafe-1.0 PyPDF2-1.26.0 SQLAlchemy-1.2.6 Wand-0.4.4 Werkzeug-0.14.1 backports-abc-0.5 blinker-1.4 certifi-2018.1.18 chardet-3.0.4 click-6.7 futures-3.2.0 idna-2.6 iso-639-0.4.5 itsdangerous-0.24 pytz-2018.3 requests-2.18.4 singledispatch-3.4.0.3 six-1.11.0 tornado-5.0.1 unidecode-1.0.22 urllib3-1.22
[/share/CACHEDEV1_DATA/Python] # python cps.py
Traceback (most recent call last):
  File "cps.py", line 13, in <module>
    from cps import web
  File "/share/CACHEDEV1_DATA/Python/cps/web.py", line 36, in <module>
    import ub
  File "/share/CACHEDEV1_DATA/Python/cps/ub.py", line 732, in <module>
    Base.metadata.create_all(engine)
  File "/share/CACHEDEV1_DATA/Python/vendor/sqlalchemy/sql/schema.py", line 4004, in create_all
    tables=tables)
  File "/share/CACHEDEV1_DATA/Python/vendor/sqlalchemy/engine/base.py", line 1940, in _run_visitor
    conn._run_visitor(visitorcallable, element, **kwargs)
  File "/share/CACHEDEV1_DATA/Python/vendor/sqlalchemy/engine/base.py", line 1549, in _run_visitor
    **kwargs).traverse_single(element)
  File "/share/CACHEDEV1_DATA/Python/vendor/sqlalchemy/sql/visitors.py", line 121, in traverse_single
    return meth(obj, **kw)
  File "/share/CACHEDEV1_DATA/Python/vendor/sqlalchemy/sql/ddl.py", line 757, in visit_metadata
    _is_metadata_operation=True)
  File "/share/CACHEDEV1_DATA/Python/vendor/sqlalchemy/sql/visitors.py", line 121, in traverse_single
    return meth(obj, **kw)
  File "/share/CACHEDEV1_DATA/Python/vendor/sqlalchemy/sql/ddl.py", line 791, in visit_table
    include_foreign_key_constraints=include_foreign_key_constraints
  File "/share/CACHEDEV1_DATA/Python/vendor/sqlalchemy/engine/base.py", line 948, in execute
    return meth(self, multiparams, params)
  File "/share/CACHEDEV1_DATA/Python/vendor/sqlalchemy/sql/ddl.py", line 68, in _execute_on_connection
    return connection._execute_ddl(self, multiparams, params)
  File "/share/CACHEDEV1_DATA/Python/vendor/sqlalchemy/engine/base.py", line 1009, in _execute_ddl
    compiled
  File "/share/CACHEDEV1_DATA/Python/vendor/sqlalchemy/engine/base.py", line 1200, in _execute_context
    context)
  File "/share/CACHEDEV1_DATA/Python/vendor/sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception
    exc_info
  File "/share/CACHEDEV1_DATA/Python/vendor/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/share/CACHEDEV1_DATA/Python/vendor/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/share/CACHEDEV1_DATA/Python/vendor/sqlalchemy/engine/default.py", line 507, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) near ""NOCASE"": syntax error [SQL: u'\nCREATE TABLE bookmark (\n\tid INTEGER NOT NULL, \n\tuser_id INTEGER, \n\tbook_id INTEGER, \n\tformat VARCHAR COLLATE "NOCASE", \n\tbookmark_key VARCHAR, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(user_id) REFERENCES user (id)\n)\n\n'] (Background on this error at: http://sqlalche.me/e/e3q8)
`

**Comment by OzzieIsaacs** [comment]
It has something to do with the sqlite database (storage for parameters of calibre-web)
Could you please go to the "vendor" directory and start a python console by typing: `python`.
And than enter the following sequence:
```
from sqlalchemy import *
engine = create_engine('sqlite:////share/CACHEDEV1_DATA/Python/test.db', echo=False)
engine.dialect.dbapi.version
engine.dialect.dbapi.sqlite_version
```
Please post the output of this and please also the python version (should show up after starting the python command)
I assume that the user running the python command has write permissions in the folder where cps.py is located?

**Comment by gelsas** [comment]
This is the output:

[/share/CACHEDEV1_DATA/Python/vendor] # python
Python 2.7.5 (default, Mar 31 2018, 03:16:11)
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from sqlalchemy import *
>>> engine = create_engine('sqlite:////share/CACHEDEV1_DATA/Python/test.db', echo=False)
>>> engine.dialect.dbapi.version
'2.6.0'
>>> engine.dialect.dbapi.sqlite_version
'3.4.1'
>>>


Yes it has the write permissions. (Any way to double check this again? Just to be 100% sure) (Sorry for the questions. I am quite new to python)

**Comment by OzzieIsaacs** [comment]
Your sqlite version is rather old, but I just changed the changelog, nothing relevant seems to be changed. I believe it's not the write permission, its a problem with the database.
Could you please go to cps/ub.py and change line 250 from:
`    format = Column(String(collation='NOCASE'))`
to:
`    format = Column(String)`
(Be carefull with the tabs and spaces beginning of the line, they are important).
Try to start the program afterwards. It hopefully should work then. (Sideeffect: Bookmarks in the online-reader maybe could not be correct set and found again)

**Comment by gelsas** [comment]
Just did it!Nnow I get the following error:

[/share/CACHEDEV1_DATA/Python] # python cps.py
Traceback (most recent call last):
  File "cps.py", line 13, in <module>
    from cps import web
  File "/share/CACHEDEV1_DATA/Python/cps/web.py", line 36, in <module>
    import ub
  File "/share/CACHEDEV1_DATA/Python/cps/ub.py", line 744, in <module>
    config = Config()
  File "/share/CACHEDEV1_DATA/Python/cps/ub.py", line 334, in __init__
    self.loadSettings()
  File "/share/CACHEDEV1_DATA/Python/cps/ub.py", line 339, in loadSettings
    self.config_calibre_dir = data.config_calibre_dir
AttributeError: 'NoneType' object has no attribute 'config_calibre_dir'

**Comment by OzzieIsaacs** [comment]
Could you please try to delete the app.db file in the ../Python/ folder and restart it again (it‘s still database issue, now no data can‘t read from database). Other idea would be: from the qnap website I saw you can install python3. Would this be an option for you?

**Comment by gelsas** [comment]
Just deleted the file and run python cps.py again:

Now I get this error:
[/share/CACHEDEV1_DATA/Python] # python cps.py
Traceback (most recent call last):
  File "cps.py", line 13, in <module>
    from cps import web
  File "/share/CACHEDEV1_DATA/Python/cps/web.py", line 36, in <module>
    import ub
  File "/share/CACHEDEV1_DATA/Python/cps/ub.py", line 744, in <module>
    config = Config()
  File "/share/CACHEDEV1_DATA/Python/cps/ub.py", line 334, in __init__
    self.loadSettings()
  File "/share/CACHEDEV1_DATA/Python/cps/ub.py", line 339, in loadSettings
    self.config_calibre_dir = data.config_calibre_dir
AttributeError: 'NoneType' object has no attribute 'config_calibre_dir'
[/share/CACHEDEV1_DATA/Python] #
[/share/CACHEDEV1_DATA/Python] # python cps.py
Traceback (most recent call last):
  File "cps.py", line 13, in <module>
    from cps import web
  File "/share/CACHEDEV1_DATA/Python/cps/web.py", line 38, in <module>
    import helper
  File "/share/CACHEDEV1_DATA/Python/cps/helper.py", line 4, in <module>
    import db
  File "/share/CACHEDEV1_DATA/Python/cps/db.py", line 9, in <module>
    import ast
ImportError: No module named ast


Regarding python3, I would not install python 3 right now, because it is very unstable. And QNAP staff adviced to use python2. So if possible I would like to keep the current python version.

**Comment by OzzieIsaacs** [comment]
Very strange, but we are getting closer. Please go into the ../Python/ folder and start:
`pip install --target vendor ast`.
After successfully installing this, try to restart. If more ImportErrors appear, please redo the procedure above with the missing module name (in this case it was ast).

**Comment by gelsas** [comment]
It gets even more strange now. I installed ast but it still says it is missing.

Collecting ast
  Downloading AST-0.0.2-py2-none-any.whl
Installing collected packages: ast
Successfully installed ast-0.0.2
[/share/CACHEDEV1_DATA/Python] # python cps.py
Traceback (most recent call last):
  File "cps.py", line 13, in <module>
    from cps import web
  File "/share/CACHEDEV1_DATA/Python/cps/web.py", line 38, in <module>
    import helper
  File "/share/CACHEDEV1_DATA/Python/cps/helper.py", line 4, in <module>
    import db
  File "/share/CACHEDEV1_DATA/Python/cps/db.py", line 9, in <module>
    import ast
ImportError: No module named ast

Completly new question could I use this: https://www.qnap.com/solution/container_station/en/ and then use this https://hub.docker.com/r/technosoft2000/calibre-web/ ? 

I mean that docker image should have everything needed already inside right ?

Thank you by the way for beeing so patient with me!

**Comment by gelsas** [comment]
I have got it running now using the docker version and can access it now.

Now this leaves me only with one question how can I apply this: https://github.com/janeczku/calibre-web/issues/454 to my calibre web docker version ?

(Regarding the solution you proposed, i will try that one on an old qnap nas I have and then report back to you regarding it)

**Comment by OzzieIsaacs** [comment]
You have to wait for technosoft to integrate it in the docker container, sorry.

**Comment by Technosoft2000** [comment]
Hi @gelsas,

I'll check how I can integrate #454 into the docker image - I've created an issue at my repo https://github.com/Technosoft2000/docker-calibre-web/issues/26

**Comment by jeffmuia** [comment]
Had the same problem, i solved it by login to my root account and installing the calibre and calibre web as using the root account., i think it access right to calibre files

**Comment by Technosoft2000** [comment]
Hi @gelsas,

in the latest release v1.1.11 of my docker image #454 caliBlur! CSS is integrated and can be directly changed over the Web Interface of Calibre-Web
