### ISSUE TITLE
New SSL option breaks existing non-SSL setups.

### ISSUE THREAD

**Issue by kendokan** [janeczku/calibre-web#478]
It appears to be looking that certs that don't exist. Also see https://github.com/linuxserver/docker-calibre-web/issues/16 for the linuxserver.io docker image, but this looks like it belongs here instead.

```
Traceback (most recent call last):
File "/usr/lib/python2.7/site-packages/gevent/greenlet.py", line 536, in run
result = self._run(*self.args, **self.kwargs)
File "/usr/lib/python2.7/site-packages/gevent/baseserver.py", line 26, in _handle_and_close_when_done
return handle(*args_tuple)
File "/usr/lib/python2.7/site-packages/gevent/server.py", line 173, in wrap_socket_and_handle
ssl_socket = self.wrap_socket(client_socket, **self.ssl_args)
File "/usr/lib/python2.7/site-packages/gevent/_sslgte279.py", line 702, in wrap_socket
ciphers=ciphers)
File "/usr/lib/python2.7/site-packages/gevent/_sslgte279.py", line 187, in __init__
raise ValueError("certfile must be specified for server-side "
ValueError: certfile must be specified for server-side operations
Sat Mar 31 09:46:10 2018 <Greenlet at 0x7f1043b80870: _handle_and_close_when_done(<bound method WSGIServer.wrap_socket_and_handle of, <bound method WSGIServer.do_close of <WSGIServer a, (<socket at 0x7f1043b4cd90 fileno=[Errno 9] Bad fi)> failed with ValueError
```

**Comment by OzzieIsaacs** [comment]
Sorry, had some problems with my gevent installation, should work now
