### ISSUE TITLE
command line -p option 

### ISSUE THREAD

**Issue by jibtga** [janeczku/calibre-web#489]
I do not know if I'm using it well the "-p" option in command line.

Is this correct ?  
python cps.py -p /path/to/calibre/metadata.db

I am getting errors

thanks in advance

**Comment by OzzieIsaacs** [comment]
this should work, please post the error you are getting

**Comment by jibtga** [comment]
python cps.py -p /media/sf_library/Book/metadata.db
Traceback (most recent call last):
  File "cps.py", line 13, in <module>
    from cps import web
  File "/media/sf_library/calibre-web-master/cps/web.py", line 36, in <module>
    import ub
  File "/media/sf_library/calibre-web-master/cps/ub.py", line 744, in <module>
    config = Config()
  File "/media/sf_library/calibre-web-master/cps/ub.py", line 334, in __init__
    self.loadSettings()
  File "/media/sf_library/calibre-web-master/cps/ub.py", line 339, in loadSettings
    self.config_calibre_dir = data.config_calibre_dir
AttributeError: 'NoneType' object has no attribute 'config_calibre_dir'
[1]+  Terminado (killed)      python cps.py


Thanks

**Comment by OzzieIsaacs** [comment]
Sorry I misslead you, the -p option is for the location of the settings database of calibre-web (to run multiple instances of the program with different settings). To specifiy the metadata.db location, just start calibre-web go to the settings page (first page to pop up) and enter the path to the calibre database there

**Comment by jibtga** [comment]
Thanks
