### ISSUE TITLE
Error opening file - client_secrets.json

### ISSUE THREAD

**Issue by dagoldfish** [janeczku/calibre-web#501]
Hi,

I have been trying to get the google drive function working, however, every time it hits an Internal server error page after I hit the authenticate to google drive button.

Stack trace is as following:
[2018-04-24 15:16:23,184] {/home/calibre/calibre-web/cps/web.py:230} INFO - Starting Calibre Web...
[2018-04-24 15:16:23,413] {/home/calibre/calibre-web/cps.py:28} INFO - Attempting to start gevent
[2018-04-24 15:16:45,195] {/home/calibre/calibre-web/vendor/flask/app.py:1560} ERROR - Exception on /gdrive/authenticate [GET]
Traceback (most recent call last):
  File "/home/calibre/calibre-web/vendor/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/calibre/calibre-web/vendor/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/calibre/calibre-web/vendor/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/calibre/calibre-web/vendor/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/calibre/calibre-web/vendor/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/calibre/calibre-web/vendor/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/calibre/calibre-web/cps/web.py", line 472, in inner
    return f(*args, **kwargs)
  File "/home/calibre/calibre-web/cps/web.py", line 1535, in authenticate_google_drive
    authUrl = Gauth.Instance().auth.GetAuthUrl()
  File "/home/calibre/calibre-web/vendor/pydrive/auth.py", line 485, in GetAuthUrl
    self.GetFlow()
  File "/home/calibre/calibre-web/vendor/pydrive/auth.py", line 443, in GetFlow
    self.LoadClientConfig()
  File "/home/calibre/calibre-web/vendor/pydrive/auth.py", line 366, in LoadClientConfig
    self.LoadClientConfigFile()
  File "/home/calibre/calibre-web/vendor/pydrive/auth.py", line 388, in LoadClientConfigFile
    raise InvalidConfigError('Invalid client secrets file %s' % error)
InvalidConfigError: Invalid client secrets file ('Error opening file', 'client_secrets.json', 'No such file or directory', 2)

I feel like I am doing something wrong, however I refollowed the instructions a few times and everytime I get to the same result.

Optional-requirements have been installed and the .json file is under the cps folder.

Running: CentOS Linux release 7.4.1708 (Core) 
non-docker version

**Comment by saitoh183** [comment]
@dagoldfish 

did you get it working?

**Comment by saitoh183** [comment]
Ah ok.. I'm just still trying to figure out what URL Base I need to put

**Comment by OzzieIsaacs** [comment]
Calibre-web seems not to find the file:
'Error opening file', 'client_secrets.json', 'No such file or directory', 2)
Could you please try to enter the complete path and the filename in the config field? Is the file accessable by the user running calibre-web?

**Comment by OzzieIsaacs** [comment]
you wrote:
... is under the cps folder.
The file is supposed to be in the root folder of calibre-web ( in the same folder cps.py is located)

**Comment by OzzieIsaacs** [comment]
The latest commit includes better error handling regarding gdrive setup
