### ISSUE TITLE
Google Drive setup question

### ISSUE THREAD

**Issue by saitoh183** [janeczku/calibre-web#502]
@OzzieIsaacs 
I setup google drive with calibre web but I don't know what to put in **Calibre Base URL**  to get the **monitor metadata.db** and book reading to work since I use the docker rdp container and acces it via guacamole. I tried activating the Calibre web server and using local IP:port but that doesnt work. could you give more detail on what i should put? Im using [aptalca/docker-rdp-calibre](https://hub.docker.com/r/aptalca/docker-rdp-calibre/)

```
[2018-04-27 01:00:19,361] {/usr/lib/python2.7/site-packages/sqlalchemy/engine/base.py:1154} INFO - (1, 1, 0)
[2018-04-27 01:00:19,426] {/usr/lib/python2.7/site-packages/flask/app.py:1560} ERROR - Exception on /gdrive/watch/subscribe [GET]
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/python2.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/calibre-web/app/cps/web.py", line 472, in inner
    return f(*args, **kwargs)
  File "/calibre-web/app/cps/web.py", line 1556, in watch_gdrive
    'web_hook', address, gdrive_watch_callback_token, current_milli_time() + 604800*1000)
  File "/calibre-web/app/cps/gdriveutils.py", line 281, in watchChange
    return drive.auth.service.changes().watch(body=body).execute()
  File "/usr/lib/python2.7/site-packages/oauth2client/_helpers.py", line 133, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/googleapiclient/http.py", line 841, in execute
    raise HttpError(resp, content, uri=self.uri)
HttpError: <HttpError 400 when requesting https://www.googleapis.com/drive/v2/changes/watch?alt=json returned "WebHook callback must be HTTPS: http://192.168.13.198:8081/gdrive/watch/callback">
```
![image](https://user-images.githubusercontent.com/1534197/39345485-aa37ffd4-49b6-11e8-9bfd-a9304f898d59.png)

**Comment by OzzieIsaacs** [comment]
HttpError: .... "WebHook callback must be HTTPS: http://192.168.13.198:8081/gdrive/watch/callback"
Google seems to request to have the calibre-web instance running on https. Could you please configure it that way (either by reverse proxy or with the build in ssl-config from the last version)

**Comment by saitoh183** [comment]
@OzzieIsaacs 
http://192.168.13.198:8081 Is my Calibre URL not Calibre-Web. So your saying it is my Calibre-Web URL that i must put in the Call Back field?

**Comment by OzzieIsaacs** [comment]
Yes, like written in the readme
...which will be CALIBRE_WEB_URL...

**Comment by OzzieIsaacs** [comment]
Maybe than you don‘t need https. I don‘t use the gdrive storage

**Comment by saitoh183** [comment]
i have book images and i can download books, but i cant monitor metadata or read books online

**Comment by OzzieIsaacs** [comment]
So what is not working is the optional part of the readme "Using Google Drive integration".
As the readme indicates, calibre-web has to respond on https request.
From my understanding in the field  "URL for calibre" you have to put your public accessible ip adress of calibre-web (https://yourdomain.com/calibreweb).
Calibre has nothing to do with this configuration. There is even no need to install it on your machine

**Comment by saitoh183** [comment]
That is what i did...and yeah i figured Calibre has nothing to do with it :)

When i put my https://yourdomain.com/calibreweb i get the error above 
`HttpError: <HttpError 401 when requesting https://www.googleapis.com/drive/v2/changes/watch?alt=json returned "Unauthorized WebHook callback channel: https:/yourdomain.com/calibreweb/gdrive/watch/callback">` 

https://yourdomain.com/calibreweb is my reverse proxy (setup like the wiki here says)

**Comment by saitoh183** [comment]
@OzzieIsaacs 
> So what is not working is the optional part of the readme "Using Google Drive integration".
yes 

But i also cant read books online via the **Read in Browser**
```
[2018-05-06 11:04:56,010] ERROR in app: Exception on /read/571/epub [GET]
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/calibre-web/app/cps/web.py", line 393, in decorated_view
    return login_required(func)(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/calibre-web/app/cps/web.py", line 1920, in read_book
    raise ValueError('Error opening eBook. File does not exist: ', epub_file)
```
but i can download the book from gdrive
![image](https://user-images.githubusercontent.com/1534197/39674708-04b20a68-511e-11e8-8ce3-95fd6e9bcb48.png)

**Comment by OzzieIsaacs** [comment]
Okay, meanwhile after several hours of trying I found a solution: To Activate the metadata watch you have to add your domain to the verified domains:
![add_domain](https://user-images.githubusercontent.com/6438895/40281466-66effd4e-5c62-11e8-928d-440f048ad9ee.png)
And than follow the instructions:
![verify_domain](https://user-images.githubusercontent.com/6438895/40281467-6e00aae8-5c62-11e8-9909-993e0f619c46.png)
Afterwards the error should not occur anymore. I have it working now, and try to improve the behavior.

**Comment by OzzieIsaacs** [comment]
Regarding the non working online reading of books: It a bug, it's just not implemented, it assumes the book is on the local drive

**Comment by saitoh183** [comment]
Ok.. I will give this a try
