### ISSUE TITLE
Synology NAS docker question

### ISSUE THREAD

**Issue by abubaman** [janeczku/calibre-web#505]
I use Synology 716+II and docker. and I use some docker containers like wordpress, mariadb, phpmyadmin, plex and dokuwiki. They are working fine.

calibre-web which was running in docker was fine. but now it has problem.
so, I delete the container and make it again. but it automatically shutdown so many times.

below is log, so please look into what the problems is. many thanks.

        ,----,
      ,/   .`|
    ,`   .'  : .--.--.        ,----,        ,-.
  ;    ;     //  /    '.    .'   .' \   ,--/ /|
.'___,/    ,'|  :  /`. /  ,----,'    |,--. :/ |
|    :     | ;  |  |--`   |    :  .  ;:  : ' /
;    |.';  ; |  :  ;_     ;    |.'  / |  '  /
`----'  |  |  \  \    `.  `----'/  ;  '  |  :
    '   :  ;   `----.   \   /  ;  /   |  |   \
    |   |  '   __ \  \  |  ;  /  /-,  '  : |. \
    '   :  |  /  /`--'  / /  /  /.`|  |  | ' \ \
    ;   |.'  '--'.     /./__;      :  '  : |--'
    '---'      `--'---' |   :    .'   ;  |,'
                        ;   | .'      '--'
                        `---'

      PRESENTS ANOTHER AWESOME DOCKER IMAGE

      ~~~~~         Calibre Web       ~~~~~

[INFO] Docker image version: 1.1.11
[INFO] Alpine Linux version: 3.6.2
[INFO] Create group calibre with id 15000
[INFO] Create user calibre with id 1048
[INFO] Current active timezone is UTC
[INFO] The defined timezone is already active.
[INFO] Change the ownership of /calibre-web (including subfolders) to calibre:calibre
[INFO] Current git version is:
git version 2.13.5
[INFO] Checkout the latest Calibre-Web version ...
[INFO] ... git clone -b master --single-branch https://github.com/janeczku/calibre-web.git /calibre-web/app -v
Cloning into '/calibre-web/app'...
POST git-upload-pack (177 bytes)
remote: Counting objects: 8008, done.
remote: Compressing objects: 100% (57/57), done.
remote: Total 8008 (delta 44), reused 67 (delta 32), pack-reused 7908
Receiving objects: 100% (8008/8008), 35.04 MiB | 5.25 MiB/s, done.
Resolving deltas: 100% (4414/4414), done.
[INFO] Autoupdate is active, try to pull the latest sources for Calibre-Web ...
[INFO] ... current git status is
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working tree clean
9867959916297fd13b191934f4b2611816cfe82d
[INFO] ... pulling sources
Already up-to-date.
[INFO] ... git status after update is
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working tree clean
9867959916297fd13b191934f4b2611816cfe82d
[INFO] Config directory option is DEACTIVATED
> due this the Calibre books directory /books will be used to store the configuration
[INFO] Checking permissions of the config directory: /books
> Output is: 777 users 100 UNKNOWN 1026
> Permissions: 777
> Assigned group: users
> Assigned group ID: 100
> Assigned owner: UNKNOWN
> Assigned owner ID: 1026
> Using permissions for checks: 0777
> Everyone has write access at /books
[INFO] 'app.db' and 'gdrive.db' will be linked into /books
> create 'app.db' link /calibre-web/app/app.db assigned to source /books/app.db
> change the ownership of /calibre-web/app/app.db to calibre:calibre
> create 'gdrive.db' link /calibre-web/app/gdrive.db assigned to source /books/gdrive.db
> change the ownership of /calibre-web/app/gdrive.db to calibre:calibre
[INFO] Checking permissions of the books directory: /books
> Output is: 777 users 100 UNKNOWN 1026
> Permissions: 777
> Assigned group: users
> Assigned group ID: 100
> Assigned owner: UNKNOWN
> Assigned owner ID: 1026
> Using permissions for checks: 0777
> Everyone has write access at /books
[INFO] The mapped volume for /books contains a Calibre database file 'metadata.db' which will be used
[INFO] The kindlegen directory exist already and will be used: /calibre-web/kindlegen
[INFO] Downloading kindlegen from http://kindlegen.s3.amazonaws.com/kindlegen_linux_2.6_i386_v2_9.tar.gz into directory: /calibre-web/kindlegen/kindlegen_linux_2.6_i386_v2_9.tar.gz
Connecting to kindlegen.s3.amazonaws.com (52.216.96.19:80)
kindlegen_linux_2.6_ 100% |*******************************| 10559k  0:00:00 ETA
[INFO] Extracting kindlegen_linux_2.6_i386_v2_9.tar.gz into directory: /calibre-web/kindlegen
[INFO] Change the ownership of /calibre-web/kindlegen (including subfolders) to calibre:calibre
[INFO] kindlegen (Amazon Kindle Generator) will be linked into /calibre-web/app/vendor
[INFO] Creating the vendor directory: /calibre-web/app/vendor
[INFO] Change the ownership of /calibre-web/app/vendor (including subfolders) to calibre:calibre
> create kindlegen link /calibre-web/app/vendor/kindlegen assigned to source /calibre-web/kindlegen/kindlegen
> change the ownership of /calibre-web/app/vendor/kindlegen to calibre:calibre
[INFO] Creating directory for temporary directories and files: /tmp
[INFO] Change the ownership of /tmp (including subfolders) to calibre:calibre
[INFO] Launching Calibre-Web ...
Traceback (most recent call last):
  File "/calibre-web/app/cps.py", line 13, in <module>
    from cps import web
  File "/calibre-web/app/cps/web.py", line 36, in <module>
    import ub
  File "/calibre-web/app/cps/ub.py", line 741, in <module>
    clean_database()
  File "/calibre-web/app/cps/ub.py", line 657, in clean_database
    session.query(RemoteAuthToken).filter(now > RemoteAuthToken.expiration).delete()
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 3247, in delete
    delete_op.exec_()
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 1326, in exec_
    self._do_exec()
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 1518, in _do_exec
    self._execute_stmt(delete_stmt)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 1333, in _execute_stmt
    mapper=self.mapper)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 1176, in execute
    bind, close_with_result=True).execute(clause, params or {})
  File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 948, in execute
    return meth(self, multiparams, params)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 269, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1060, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1200, in _execute_context
    context)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception
    exc_info
  File "/usr/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 507, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) attempt to write a readonly database [SQL: u'DELETE FROM remote_auth_token WHERE remote_auth_token.expiration < ?'] [parameters: ('2018-05-15 10:40:42.582011',)] (Background on this error at: http://sqlalche.me/e/e3q8)
        ,----,
      ,/   .`|
    ,`   .'  : .--.--.        ,----,        ,-.
  ;    ;     //  /    '.    .'   .' \   ,--/ /|
.'___,/    ,'|  :  /`. /  ,----,'    |,--. :/ |
|    :     | ;  |  |--`   |    :  .  ;:  : ' /
;    |.';  ; |  :  ;_     ;    |.'  / |  '  /
`----'  |  |  \  \    `.  `----'/  ;  '  |  :
    '   :  ;   `----.   \   /  ;  /   |  |   \
    |   |  '   __ \  \  |  ;  /  /-,  '  : |. \
    '   :  |  /  /`--'  / /  /  /.`|  |  | ' \ \
    ;   |.'  '--'.     /./__;      :  '  : |--'
    '---'      `--'---' |   :    .'   ;  |,'
                        ;   | .'      '--'
                        `---'

      PRESENTS ANOTHER AWESOME DOCKER IMAGE

      ~~~~~         Calibre Web       ~~~~~

[INFO] Docker image version: 1.1.11
[INFO] Alpine Linux version: 3.6.2
[WARNING] A group with id 15000 exists already [in use by calibre] and will be modified.
[WARNING] The group calibre will be renamed to calibre
[WARNING] A user with id 1048 exists already [in use by calibre].
[WARNING] Create user calibre with temporary user id 999.
adduser: user 'calibre' in use
[WARNING] Assign non-unique user id 1048 to created user calibre
usermod: no changes
[INFO] Current active timezone is UTC
[INFO] The defined timezone is already active.
[INFO] Change the ownership of /calibre-web (including subfolders) to calibre:calibre
[INFO] Current git version is:
git version 2.13.5
[INFO] Checkout the latest Calibre-Web version ...
[INFO] Autoupdate is active, try to pull the latest sources for Calibre-Web ...
[INFO] ... current git status is
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working tree clean
9867959916297fd13b191934f4b2611816cfe82d
[INFO] ... pulling sources
Already up-to-date.
[INFO] ... git status after update is
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working tree clean
9867959916297fd13b191934f4b2611816cfe82d
[INFO] Config directory option is DEACTIVATED
> due this the Calibre books directory /books will be used to store the configuration
[INFO] Checking permissions of the config directory: /books
> Output is: 777 users 100 UNKNOWN 1026
> Permissions: 777
> Assigned group: users
> Assigned group ID: 100
> Assigned owner: UNKNOWN
> Assigned owner ID: 1026
> Using permissions for checks: 0777
> Everyone has write access at /books
[INFO] 'app.db' and 'gdrive.db' will be linked into /books
> 'app.db' link /calibre-web/app/app.db exists already and won't be recreated
> 'gdrive.db' link /calibre-web/app/gdrive.db exists already and won't be recreated
[INFO] Checking permissions of the books directory: /books
> Output is: 777 users 100 UNKNOWN 1026
> Permissions: 777
> Assigned group: users
> Assigned group ID: 100
> Assigned owner: UNKNOWN
> Assigned owner ID: 1026
> Using permissions for checks: 0777
> Everyone has write access at /books
[INFO] The mapped volume for /books contains a Calibre database file 'metadata.db' which will be used
[INFO] The kindlegen directory exist already and will be used: /calibre-web/kindlegen
[INFO] Kindlegen application exists already in directory: /calibre-web/kindlegen
[INFO] kindlegen (Amazon Kindle Generator) will be linked into /calibre-web/app/vendor
> kindlegen link /calibre-web/app/vendor/kindlegen exists already and won't be recreated
[INFO] Launching Calibre-Web ...
Traceback (most recent call last):
  File "/calibre-web/app/cps.py", line 13, in <module>
    from cps import web
  File "/calibre-web/app/cps/web.py", line 36, in <module>
    import ub
  File "/calibre-web/app/cps/ub.py", line 741, in <module>
    clean_database()
  File "/calibre-web/app/cps/ub.py", line 657, in clean_database
    session.query(RemoteAuthToken).filter(now > RemoteAuthToken.expiration).delete()
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 3247, in delete
    delete_op.exec_()
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 1326, in exec_
    self._do_exec()
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 1518, in _do_exec
    self._execute_stmt(delete_stmt)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 1333, in _execute_stmt
    mapper=self.mapper)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 1176, in execute
    bind, close_with_result=True).execute(clause, params or {})
  File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 948, in execute
    return meth(self, multiparams, params)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 269, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1060, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1200, in _execute_context
    context)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception
    exc_info
  File "/usr/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 507, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) attempt to write a readonly database [SQL: u'DELETE FROM remote_auth_token WHERE remote_auth_token.expiration < ?'] [parameters: ('2018-05-15 10:40:48.795746',)] (Background on this error at: http://sqlalche.me/e/e3q8)
        ,----,
      ,/   .`|
    ,`   .'  : .--.--.        ,----,        ,-.
  ;    ;     //  /    '.    .'   .' \   ,--/ /|
.'___,/    ,'|  :  /`. /  ,----,'    |,--. :/ |
|    :     | ;  |  |--`   |    :  .  ;:  : ' /
;    |.';  ; |  :  ;_     ;    |.'  / |  '  /
`----'  |  |  \  \    `.  `----'/  ;  '  |  :
    '   :  ;   `----.   \   /  ;  /   |  |   \
    |   |  '   __ \  \  |  ;  /  /-,  '  : |. \
    '   :  |  /  /`--'  / /  /  /.`|  |  | ' \ \
    ;   |.'  '--'.     /./__;      :  '  : |--'
    '---'      `--'---' |   :    .'   ;  |,'
                        ;   | .'      '--'
                        `---'

      PRESENTS ANOTHER AWESOME DOCKER IMAGE

      ~~~~~         Calibre Web       ~~~~~

[INFO] Docker image version: 1.1.11
[INFO] Alpine Linux version: 3.6.2
[WARNING] A group with id 15000 exists already [in use by calibre] and will be modified.
[WARNING] The group calibre will be renamed to calibre
[WARNING] A user with id 1048 exists already [in use by calibre].
[WARNING] Create user calibre with temporary user id 999.
adduser: user 'calibre' in use
[WARNING] Assign non-unique user id 1048 to created user calibre
usermod: no changes
[INFO] Current active timezone is UTC
[INFO] The defined timezone is already active.
[INFO] Change the ownership of /calibre-web (including subfolders) to calibre:calibre
[INFO] Current git version is:
git version 2.13.5
[INFO] Checkout the latest Calibre-Web version ...
[INFO] Autoupdate is active, try to pull the latest sources for Calibre-Web ...
[INFO] ... current git status is
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working tree clean
9867959916297fd13b191934f4b2611816cfe82d
[INFO] ... pulling sources
Already up-to-date.
[INFO] ... git status after update is
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working tree clean
9867959916297fd13b191934f4b2611816cfe82d
[INFO] Config directory option is DEACTIVATED
> due this the Calibre books directory /books will be used to store the configuration
[INFO] Checking permissions of the config directory: /books
> Output is: 777 users 100 UNKNOWN 1026
> Permissions: 777
> Assigned group: users
> Assigned group ID: 100
> Assigned owner: UNKNOWN
> Assigned owner ID: 1026
> Using permissions for checks: 0777
> Everyone has write access at /books
[INFO] 'app.db' and 'gdrive.db' will be linked into /books
> 'app.db' link /calibre-web/app/app.db exists already and won't be recreated
> 'gdrive.db' link /calibre-web/app/gdrive.db exists already and won't be recreated
[INFO] Checking permissions of the books directory: /books
> Output is: 777 users 100 UNKNOWN 1026
> Permissions: 777
> Assigned group: users
> Assigned group ID: 100
> Assigned owner: UNKNOWN
> Assigned owner ID: 1026
> Using permissions for checks: 0777
> Everyone has write access at /books
[INFO] The mapped volume for /books contains a Calibre database file 'metadata.db' which will be used
[INFO] The kindlegen directory exist already and will be used: /calibre-web/kindlegen
[INFO] Kindlegen application exists already in directory: /calibre-web/kindlegen
[INFO] kindlegen (Amazon Kindle Generator) will be linked into /calibre-web/app/vendor
> kindlegen link /calibre-web/app/vendor/kindlegen exists already and won't be recreated
[INFO] Launching Calibre-Web ...
Traceback (most recent call last):
  File "/calibre-web/app/cps.py", line 13, in <module>
    from cps import web
  File "/calibre-web/app/cps/web.py", line 36, in <module>
    import ub
  File "/calibre-web/app/cps/ub.py", line 741, in <module>
    clean_database()
  File "/calibre-web/app/cps/ub.py", line 657, in clean_database
    session.query(RemoteAuthToken).filter(now > RemoteAuthToken.expiration).delete()
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 3247, in delete
    delete_op.exec_()
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 1326, in exec_
    self._do_exec()
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 1518, in _do_exec
    self._execute_stmt(delete_stmt)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 1333, in _execute_stmt
    mapper=self.mapper)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 1176, in execute
    bind, close_with_result=True).execute(clause, params or {})
  File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 948, in execute
    return meth(self, multiparams, params)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 269, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1060, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1200, in _execute_context
    context)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception
    exc_info
  File "/usr/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 507, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) attempt to write a readonly database [SQL: u'DELETE FROM remote_auth_token WHERE remote_auth_token.expiration < ?'] [parameters: ('2018-05-15 10:40:54.220113',)] (Background on this error at: http://sqlalche.me/e/e3q8)
        ,----,
      ,/   .`|
    ,`   .'  : .--.--.        ,----,        ,-.
  ;    ;     //  /    '.    .'   .' \   ,--/ /|
.'___,/    ,'|  :  /`. /  ,----,'    |,--. :/ |
|    :     | ;  |  |--`   |    :  .  ;:  : ' /
;    |.';  ; |  :  ;_     ;    |.'  / |  '  /
`----'  |  |  \  \    `.  `----'/  ;  '  |  :
    '   :  ;   `----.   \   /  ;  /   |  |   \
    |   |  '   __ \  \  |  ;  /  /-,  '  : |. \
    '   :  |  /  /`--'  / /  /  /.`|  |  | ' \ \
    ;   |.'  '--'.     /./__;      :  '  : |--'
    '---'      `--'---' |   :    .'   ;  |,'
                        ;   | .'      '--'
                        `---'

      PRESENTS ANOTHER AWESOME DOCKER IMAGE

      ~~~~~         Calibre Web       ~~~~~

[INFO] Docker image version: 1.1.11
[INFO] Alpine Linux version: 3.6.2
[WARNING] A group with id 15000 exists already [in use by calibre] and will be modified.
[WARNING] The group calibre will be renamed to calibre
[WARNING] A user with id 1048 exists already [in use by calibre].
[WARNING] Create user calibre with temporary user id 999.
adduser: user 'calibre' in use
[WARNING] Assign non-unique user id 1048 to created user calibre
usermod: no changes
[INFO] Current active timezone is UTC
[INFO] The defined timezone is already active.
[INFO] Change the ownership of /calibre-web (including subfolders) to calibre:calibre
[INFO] Current git version is:
git version 2.13.5
[INFO] Checkout the latest Calibre-Web version ...
[INFO] Autoupdate is active, try to pull the latest sources for Calibre-Web ...
[INFO] ... current git status is
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working tree clean
9867959916297fd13b191934f4b2611816cfe82d
[INFO] ... pulling sources
Already up-to-date.
[INFO] ... git status after update is
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working tree clean
9867959916297fd13b191934f4b2611816cfe82d
[INFO] Config directory option is DEACTIVATED
> due this the Calibre books directory /books will be used to store the configuration
[INFO] Checking permissions of the config directory: /books
> Output is: 777 users 100 UNKNOWN 1026
> Permissions: 777
> Assigned group: users
> Assigned group ID: 100
> Assigned owner: UNKNOWN
> Assigned owner ID: 1026
> Using permissions for checks: 0777
> Everyone has write access at /books
[INFO] 'app.db' and 'gdrive.db' will be linked into /books
> 'app.db' link /calibre-web/app/app.db exists already and won't be recreated
> 'gdrive.db' link /calibre-web/app/gdrive.db exists already and won't be recreated
[INFO] Checking permissions of the books directory: /books
> Output is: 777 users 100 UNKNOWN 1026
> Permissions: 777
> Assigned group: users
> Assigned group ID: 100
> Assigned owner: UNKNOWN
> Assigned owner ID: 1026
> Using permissions for checks: 0777
> Everyone has write access at /books
[INFO] The mapped volume for /books contains a Calibre database file 'metadata.db' which will be used
[INFO] The kindlegen directory exist already and will be used: /calibre-web/kindlegen
[INFO] Kindlegen application exists already in directory: /calibre-web/kindlegen
[INFO] kindlegen (Amazon Kindle Generator) will be linked into /calibre-web/app/vendor
> kindlegen link /calibre-web/app/vendor/kindlegen exists already and won't be recreated
[INFO] Launching Calibre-Web ...
Traceback (most recent call last):
  File "/calibre-web/app/cps.py", line 13, in <module>
    from cps import web
  File "/calibre-web/app/cps/web.py", line 36, in <module>
    import ub
  File "/calibre-web/app/cps/ub.py", line 741, in <module>
    clean_database()
  File "/calibre-web/app/cps/ub.py", line 657, in clean_database
    session.query(RemoteAuthToken).filter(now > RemoteAuthToken.expiration).delete()
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 3247, in delete
    delete_op.exec_()
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 1326, in exec_
    self._do_exec()
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 1518, in _do_exec
    self._execute_stmt(delete_stmt)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 1333, in _execute_stmt
    mapper=self.mapper)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 1176, in execute
    bind, close_with_result=True).execute(clause, params or {})
  File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 948, in execute
    return meth(self, multiparams, params)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 269, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1060, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1200, in _execute_context
    context)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception
    exc_info
  File "/usr/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 507, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) attempt to write a readonly database [SQL: u'DELETE FROM remote_auth_token WHERE remote_auth_token.expiration < ?'] [parameters: ('2018-05-15 10:40:59.418574',)] (Background on this error at: http://sqlalche.me/e/e3q8)
        ,----,
      ,/   .`|
    ,`   .'  : .--.--.        ,----,        ,-.
  ;    ;     //  /    '.    .'   .' \   ,--/ /|
.'___,/    ,'|  :  /`. /  ,----,'    |,--. :/ |
|    :     | ;  |  |--`   |    :  .  ;:  : ' /
;    |.';  ; |  :  ;_     ;    |.'  / |  '  /
`----'  |  |  \  \    `.  `----'/  ;  '  |  :
    '   :  ;   `----.   \   /  ;  /   |  |   \
    |   |  '   __ \  \  |  ;  /  /-,  '  : |. \
    '   :  |  /  /`--'  / /  /  /.`|  |  | ' \ \
    ;   |.'  '--'.     /./__;      :  '  : |--'
    '---'      `--'---' |   :    .'   ;  |,'
                        ;   | .'      '--'
                        `---'

      PRESENTS ANOTHER AWESOME DOCKER IMAGE

      ~~~~~         Calibre Web       ~~~~~

[INFO] Docker image version: 1.1.11
[INFO] Alpine Linux version: 3.6.2
[WARNING] A group with id 15000 exists already [in use by calibre] and will be modified.
[WARNING] The group calibre will be renamed to calibre
[WARNING] A user with id 1048 exists already [in use by calibre].
[WARNING] Create user calibre with temporary user id 999.
adduser: user 'calibre' in use
[WARNING] Assign non-unique user id 1048 to created user calibre
usermod: no changes
[INFO] Current active timezone is UTC
[INFO] The defined timezone is already active.
[INFO] Change the ownership of /calibre-web (including subfolders) to calibre:calibre
[INFO] Current git version is:
git version 2.13.5
[INFO] Checkout the latest Calibre-Web version ...
[INFO] Autoupdate is active, try to pull the latest sources for Calibre-Web ...
[INFO] ... current git status is
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working tree clean
9867959916297fd13b191934f4b2611816cfe82d
[INFO] ... pulling sources
Already up-to-date.
[INFO] ... git status after update is
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working tree clean
9867959916297fd13b191934f4b2611816cfe82d
[INFO] Config directory option is DEACTIVATED
> due this the Calibre books directory /books will be used to store the configuration
[INFO] Checking permissions of the config directory: /books
> Output is: 777 users 100 UNKNOWN 1026
> Permissions: 777
> Assigned group: users
> Assigned group ID: 100
> Assigned owner: UNKNOWN
> Assigned owner ID: 1026
> Using permissions for checks: 0777
> Everyone has write access at /books
[INFO] 'app.db' and 'gdrive.db' will be linked into /books
> 'app.db' link /calibre-web/app/app.db exists already and won't be recreated
> 'gdrive.db' link /calibre-web/app/gdrive.db exists already and won't be recreated
[INFO] Checking permissions of the books directory: /books
> Output is: 777 users 100 UNKNOWN 1026
> Permissions: 777
> Assigned group: users
> Assigned group ID: 100
> Assigned owner: UNKNOWN
> Assigned owner ID: 1026
> Using permissions for checks: 0777
> Everyone has write access at /books
[INFO] The mapped volume for /books contains a Calibre database file 'metadata.db' which will be used
[INFO] The kindlegen directory exist already and will be used: /calibre-web/kindlegen
[INFO] Kindlegen application exists already in directory: /calibre-web/kindlegen
[INFO] kindlegen (Amazon Kindle Generator) will be linked into /calibre-web/app/vendor
> kindlegen link /calibre-web/app/vendor/kindlegen exists already and won't be recreated
[INFO] Launching Calibre-Web ...
Traceback (most recent call last):
  File "/calibre-web/app/cps.py", line 13, in <module>
    from cps import web
  File "/calibre-web/app/cps/web.py", line 36, in <module>
    import ub
  File "/calibre-web/app/cps/ub.py", line 741, in <module>
    clean_database()
  File "/calibre-web/app/cps/ub.py", line 657, in clean_database
    session.query(RemoteAuthToken).filter(now > RemoteAuthToken.expiration).delete()
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 3247, in delete
    delete_op.exec_()
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 1326, in exec_
    self._do_exec()
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 1518, in _do_exec
    self._execute_stmt(delete_stmt)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 1333, in _execute_stmt
    mapper=self.mapper)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 1176, in execute
    bind, close_with_result=True).execute(clause, params or {})
  File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 948, in execute
    return meth(self, multiparams, params)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 269, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1060, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1200, in _execute_context
    context)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception
    exc_info
  File "/usr/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 507, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) attempt to write a readonly database [SQL: u'DELETE FROM remote_auth_token WHERE remote_auth_token.expiration < ?'] [parameters: ('2018-05-15 10:41:05.094869',)] (Background on this error at: http://sqlalche.me/e/e3q8)

**Comment by Kyosfonica** [comment]
I have the exact same error. I do not know which change broke the code. I was using my own branch and after updating it with the latest master version the container is unable to load.

**Comment by OzzieIsaacs** [comment]
Could you please try to delete the app.db, looks like a problem with the programs settings database (keep the old file somewhere)

**Comment by abubaman** [comment]
I think database has some error. I deleted app.db but problem was not disappeared.
So I made a new Calibre-Library again, and then docker-calibre-web works fine.

So, Now I'm using Calibre-web with new Calibre-Library.
