### ISSUE TITLE
Problems when sending to kindle

### ISSUE THREAD

**Issue by bjhiggins** [janeczku/calibre-web#524]
My calibre-web server is running in a Docker container from technosoft2000/calibre-web.  When I click the "Send to Kindle" button, I am redirected to the URL https://MYSERVER/send/589 and receive this message:

"Internal Server Error"

When I look at the output logs from the container, I see the following:

::ffff:172.17.0.1 - - [2018-06-14 14:25:49] "GET /book/589 HTTP/1.0" 200 6882 0.030209

Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/gevent/pywsgi.py", line 935, in handle_one_response
    self.run_application()
  File "/usr/lib/python2.7/site-packages/gevent/pywsgi.py", line 908, in run_application
    self.result = self.application(self.environ, self.start_response)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/calibre-web/app/cps/web.py", line 201, in __call__
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_exception
    self.log_exception((exc_type, exc_value, tb))
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1560, in log_exception
    ), exc_info=exc_info)
TypeError: 'str' object is not callable
Thu Jun 14 14:26:00 2018 {'REMOTE_PORT': '44346', 'HTTP_HOST': 'MYSERVER', 'REMOTE_ADDR': '::ffff:172.17.0.1', (hidden keys: 29)} failed with TypeError

::ffff:172.17.0.1 - - [2018-06-14 14:26:00] "GET /send/589 HTTP/1.0" 500 161 5.022789
TypeError: 'str' object is not callable

I can confirm that I have installed the latest Kindlegen from Amazon as well as have done "git pull" from the master branch on the container.

Any thoughts?

**Comment by OzzieIsaacs** [comment]
I'm sorry. 
I tried to reproduce the error, it works for me on windos and linux (without docker) with and without proxy. I have no glue what's the reason behind it.

**Comment by OzzieIsaacs** [comment]
Have you updated to the newest commit within the container? (Admin page check for updates?)

**Comment by OzzieIsaacs** [comment]
Not reproducable
