### ISSUE TITLE
Editing categories gives '500 Internal Server Error'

### ISSUE THREAD

**Issue by Jucgshu** [janeczku/calibre-web#531]
Hi guys,

Each time I try to edit a category's book, Calibre-web crashes with a 500 error.

Is it just me?

```[2018-06-24 08:31:03,355] ERROR in app: Exception on /admin/book/994 [POST]
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/app/calibre-web/cps/web.py", line 393, in decorated_view
    return login_required(func)(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/app/calibre-web/cps/web.py", line 516, in inner
    return f(*args, **kwargs)
  File "/app/calibre-web/cps/web.py", line 3092, in edit_book
    if len(book.comments):
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/attributes.py", line 242, in __get__
    return self.impl.get(instance_state(instance), dict_)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/attributes.py", line 599, in get
    value = self.callable_(state, passive)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/strategies.py", line 630, in _load_for_state
    session, state, primary_key_identity, passive)
  File "<string>", line 1, in <lambda>
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/strategies.py", line 764, in _emit_lazyload
    result = q(session).with_post_criteria(set_default_params).all()
  File "/usr/lib/python2.7/site-packages/sqlalchemy/ext/baked.py", line 439, in all
    return list(self)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/ext/baked.py", line 341, in __iter__
    self.session._autoflush()
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 1444, in _autoflush
    util.raise_from_cause(e)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 1434, in _autoflush
    self.flush()
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2254, in flush
    self._flush(objects)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2380, in _flush
    transaction.rollback(_capture_exception=True)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2344, in _flush
    flush_context.execute()
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 391, in execute
    rec.execute(self)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 556, in execute
    uow
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 177, in save_obj
    mapper, table, update)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 768, in _emit_update_statements
    execute(statement, multiparams)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 948, in execute
    return meth(self, multiparams, params)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 269, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1060, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1200, in _execute_context
    context)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception
    exc_info
  File "/usr/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 508, in do_execute
    cursor.execute(statement, parameters)
OperationalError: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely) (sqlite3.OperationalError) attempt to write a readonly database [SQL: u'UPDATE books SET series_index=? WHERE books.id = ?'] [parameters: (u'1.0', 994)] (Background on this error at: http://sqlalche.me/e/e3q8)
::ffff:172.19.0.2 - - [2018-06-24 08:31:03] "POST /admin/book/994 HTTP/1.1" 500 412 0.050423```

**Comment by OzzieIsaacs** [comment]
Somehow your database is readonly (do you have calibre open in parallel?)

**Comment by Jucgshu** [comment]
Thanks @OzzieIsaacs 

This is weird. ```metadata.db``` is owned by the same user I run my Docker container with. And is ```-rw-r--r--``` ?

**Comment by OzzieIsaacs** [comment]
I checked it, for me no error occours. Nonetheless I improved the error handling during editing books. If the error still persits I need the calibre database for debugging. If you are willing to hand it over to me, please send my a email (email adress in my profile

**Comment by OzzieIsaacs** [comment]
Closed due to to feedback
