### ISSUE TITLE
upload gives error

### ISSUE THREAD

**Issue by aroundmyroom** [janeczku/calibre-web#543]
Latest commit and than a revert gives me an error uploading a book

root@boeken:/home/dennis/calibre-web# tail -f calibre-web.log
    context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line                    1413, in _handle_dbapi_exception
    exc_info
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/compat.py", line                    265, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line                    1193, in _execute_context
    context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/default.py", li                   ne 509, in do_execute
    cursor.execute(statement, parameters)
OperationalError: (raised as a result of Query-invoked autoflush; consider using                    a session.no_autoflush block if this flush is occurring prematurely) (sqlite3.O                   perationalError) no such function: title_sort [SQL: u'UPDATE books SET path=? WH                   ERE books.id = ?'] [parameters: (u'Nicci French/De dag van de doden (1198)', 119                   8)] (Background on this error at: http://sqlalche.me/e/e3q8)

even trying to remove it after restarting gives issues. with 

  return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/dennis/calibre-web/cps/web.py", line 1436, in delete_book
    helper.delete_book(book, config.config_calibre_dir)
  File "/home/dennis/calibre-web/cps/helper.py", line 405, in delete_book
    return delete_book_file(book, calibrepath)
  File "/home/dennis/calibre-web/cps/helper.py", line 302, in delete_book_file
    if len(next(os.walk(path))[1]):
StopIteration

dunno where to look (I think it is in the filename) where
nicci, French ... is stated. with that even calibre is crashing ..

**Comment by OzzieIsaacs** [comment]
I need a bit mor of the log. There should be some lines ...web.py" line xxx, in ...

**Comment by aroundmyroom** [comment]
[2018-07-14 22:47:39,039] {/usr/local/lib/python2.7/dist-packages/flask/app.py:1761} ERROR - Exception on /upload [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/dennis/calibre-web/cps/web.py", line 329, in decorated_view
    return login_required(func)(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/dennis/calibre-web/cps/web.py", line 442, in inner
    return f(*args, **kwargs)
  File "/home/dennis/calibre-web/cps/web.py", line 3329, in upload
    book.languages[0].language_name = _(meta.languages)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/attributes.py", line 242, in __get__
    return self.impl.get(instance_state(instance), dict_)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/attributes.py", line 599, in get
    value = self.callable_(state, passive)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/strategies.py", line 631, in _load_for_state
    session, state, primary_key_identity, passive)
  File "<string>", line 1, in <lambda>
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/strategies.py", line 771, in _emit_lazyload
    with_post_criteria(set_default_params).all()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/ext/baked.py", line 446, in all
    return list(self)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/ext/baked.py", line 348, in __iter__
    self.session._autoflush()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 1444, in _autoflush
    util.raise_from_cause(e)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/compat.py", line 265, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 1434, in _autoflush
    self.flush()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 2254, in flush
    self._flush(objects)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 2380, in _flush
    transaction.rollback(_capture_exception=True)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 2344, in _flush
    flush_context.execute()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/unitofwork.py", line 391, in execute
    rec.execute(self)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/unitofwork.py", line 556, in execute
    uow
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/persistence.py", line 177, in save_obj
    mapper, table, update)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/persistence.py", line 768, in _emit_update_statements
    execute(statement, multiparams)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 948, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/elements.py", line 269, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1060, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1200, in _execute_context
    context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception
    exc_info
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/compat.py", line 265, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/default.py", line 509, in do_execute
    cursor.execute(statement, parameters)
OperationalError: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occur
ring prematurely) (sqlite3.OperationalError) no such function: title_sort [SQL: u'UPDATE books SET path=? WHERE books.id = ?'] [para
meters: (u'Patricia Snel/Expat exit (1206)', 1206)] (Background on this error at: http://sqlalche.me/e/e3q8)

**Comment by aroundmyroom** [comment]
and this one

[2018-07-14 22:47:00,471] {/home/dennis/calibre-web/cps/web.py:173} INFO - Starting Calibre Web...
[2018-07-14 22:47:00,605] {/home/dennis/calibre-web/cps/server.py:52} INFO - Starting Gevent server
[2018-07-14 22:47:11,589] {/usr/local/lib/python2.7/dist-packages/flask/app.py:1761} ERROR - Exception on /delete/1205/ [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/dennis/calibre-web/cps/web.py", line 1436, in delete_book
    helper.delete_book(book, config.config_calibre_dir)
  File "/home/dennis/calibre-web/cps/helper.py", line 405, in delete_book
    return delete_book_file(book, calibrepath)
  File "/home/dennis/calibre-web/cps/helper.py", line 302, in delete_book_file
    if len(next(os.walk(path))[1]):
StopIteration

**Comment by OzzieIsaacs** [comment]
Please try the newest commit. 
The delete works definitly now, for the upload issue I'm not 100% sure, because works for me (error depends on content of uploaded book)

**Comment by aroundmyroom** [comment]
both issues are resolved at my side.
Uploading books work again fine and deleting a book also.
