### ISSUE TITLE
Error 500 after reboot

### ISSUE THREAD

**Issue by Emil8250** [janeczku/calibre-web#549]
I've just installed Calibre Web, and everything looked great, I rebooted the server and now I get an Error 500 everytime I access the webpage. 

This is the error I get: 

`[2018-07-18 11:45:50,090] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/root/calibre-web-master/vendor/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/root/calibre-web-master/vendor/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/root/calibre-web-master/vendor/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/root/calibre-web-master/vendor/flask/_compat.py", line 35, in reraise
    raise value
  File "/root/calibre-web-master/vendor/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/root/calibre-web-master/vendor/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/root/calibre-web-master/cps/web.py", line 328, in decorated_view
    return login_required(func)(*args, **kwargs)
  File "/root/calibre-web-master/vendor/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/root/calibre-web-master/cps/web.py", line 1048, in index
    entries, random, pagination = fill_indexpage(page, db.Books, True, [db.Books.timestamp.desc()])
  File "/root/calibre-web-master/cps/web.py", line 487, in fill_indexpage
    random = db.session.query(db.Books).filter(common_filters())\
  File "/root/calibre-web-master/cps/web.py", line 480, in common_filters
    db.Books.tags.any(db.Tags.name.in_(config.mature_content_tags()))
  File "/root/calibre-web-master/cps/ub.py", line 497, in mature_content_tags
    return list(map(lstrip, self.config_mature_content_tags.split(",")))
AttributeError: 'NoneType' object has no attribute 'split'
ERROR:flask.app:Exception on / [GET]
Traceback (most recent call last):
  File "/root/calibre-web-master/vendor/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/root/calibre-web-master/vendor/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/root/calibre-web-master/vendor/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/root/calibre-web-master/vendor/flask/_compat.py", line 35, in reraise
    raise value
  File "/root/calibre-web-master/vendor/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/root/calibre-web-master/vendor/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/root/calibre-web-master/cps/web.py", line 328, in decorated_view
    return login_required(func)(*args, **kwargs)
  File "/root/calibre-web-master/vendor/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/root/calibre-web-master/cps/web.py", line 1048, in index
    entries, random, pagination = fill_indexpage(page, db.Books, True, [db.Books.timestamp.desc()])
  File "/root/calibre-web-master/cps/web.py", line 487, in fill_indexpage
    random = db.session.query(db.Books).filter(common_filters())\
  File "/root/calibre-web-master/cps/web.py", line 480, in common_filters
    db.Books.tags.any(db.Tags.name.in_(config.mature_content_tags()))
  File "/root/calibre-web-master/cps/ub.py", line 497, in mature_content_tags
    return list(map(lstrip, self.config_mature_content_tags.split(",")))
AttributeError: 'NoneType' object has no attribute 'split'
ERROR:tornado.access:500 GET / (5.186.121.183) 22.27ms`

I hope somebody can point me in the right direction.

//Emil

**Comment by Emil8250** [comment]
Btw. tried installing Flask, without luck.

**Comment by OzzieIsaacs** [comment]
Found it

**Comment by OzzieIsaacs** [comment]
Please update to newest version and try again

**Comment by Emil8250** [comment]
Newest version of Calibre Web?
