### ISSUE TITLE
Cannot authenticate Google Drive

### ISSUE THREAD

**Issue by astrodad** [janeczku/calibre-web#554]
Hello,

I'm using technosoft2000/calibre-web and I've copied the client_secrets.json file into the app folder. When I run calibre-web for the first time, I click on the option to authenticate, but the Google authentication never loads. Instead, in the log, I see a HTTP 302 (redirect) back to calibre-web:

::ffff:172.17.0.14 - - [2018-07-25 16:17:55] "GET /gdrive/authenticate HTTP/1.1" 302 387 0.001537
::ffff:172.18.0.13 - - [2018-07-25 16:17:55] "GET /config HTTP/1.1" 200 12218 0.005547
::ffff:172.17.0.14 - - [2018-07-25 16:19:29] "GET /config HTTP/1.1" 200 12218 0.005338
::ffff:172.18.0.13 - - [2018-07-25 16:19:33] "GET /gdrive/authenticate HTTP/1.1" 302 387 0.001510
::ffff:172.17.0.14 - - [2018-07-25 16:19:33] "GET /config HTTP/1.1" 200 12218 0.005587

I've configured the app and authentication in Google Drive, but I don't think it's even getting that far. My calibre-web url is https://calibre.domain.com/ and I am using CloudFlare for DNS.

Any help would be appreciated.

**Comment by OzzieIsaacs** [comment]
It‘s a bug. On the initial config page you are not logged in, so you get a error message. Please log in as administrator and press the authenticate button. It should work then.

**Comment by astrodad** [comment]
Thanks for the response. So how do I log in if I can't get past the initial config page?

**Comment by OzzieIsaacs** [comment]
After you have entered a valid location for the metadata.db and saved it, it should offer you a button go to login page

**Comment by astrodad** [comment]
I copied a metadata file temporarily over into /books and got to the login screen. When I go to Authenticate, I get this:

[2018-07-25 19:45:35,378] {/usr/lib/python2.7/site-packages/flask/app.py:1560} ERROR - Exception on /gdrive/authenticate [GET]
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/python2.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/calibre-web/app/cps/web.py", line 424, in inner
    return f(*args, **kwargs)
  File "/calibre-web/app/cps/web.py", line 1511, in authenticate_google_drive
    authUrl = Gauth.Instance().auth.GetAuthUrl()
NameError: global name 'Gauth' is not defined

**Comment by OzzieIsaacs** [comment]
Sorry, please update to the newest commit.

**Comment by astrodad** [comment]
I deleted everything and started again from scratch. This is what it's in the log when I do just about anything now: 

[2018-07-26 01:09:39,566] {/usr/lib/python2.7/site-packages/sqlalchemy/engine/base.py:1154} INFO - (1,)
[2018-07-26 01:09:49,262] {/usr/lib/python2.7/site-packages/sqlalchemy/orm/path_registry.py:63} DEBUG - set 'memoized_setups' on path 'EntityRegistry((<Mapper at 0x7fcd1a2b5810; Shelf>,))' to '{}'
[2018-07-26 01:09:49,263] {/usr/lib/python2.7/site-packages/sqlalchemy/orm/path_registry.py:63} DEBUG - set 'memoized_setups' on path 'EntityRegistry((<Mapper at 0x7fcd1a7f1f10; User>,))' to '{}'
[2018-07-26 01:09:49,264] {/usr/lib/python2.7/site-packages/sqlalchemy/orm/path_registry.py:63} DEBUG - set 'memoized_setups' on path 'EntityRegistry((<Mapper at 0x7fcd1a7f1f10; User>,))' to '{}'
[2018-07-26 01:09:49,264] {/usr/lib/python2.7/site-packages/sqlalchemy/orm/path_registry.py:63} DEBUG - set 'memoized_setups' on path 'EntityRegistry((<Mapper at 0x7fcd1a2828d0; Settings>,))' to '{}'
[2018-07-26 01:09:49,287] {/usr/lib/python2.7/site-packages/sqlalchemy/orm/path_registry.py:63} DEBUG - set 'memoized_setups' on path 'EntityRegistry((<Mapper at 0x7fcd1a2b5810; Shelf>,))' to '{}'
[2018-07-26 01:09:49,289] {/usr/lib/python2.7/site-packages/sqlalchemy/orm/path_registry.py:63} DEBUG - set 'memoized_setups' on path 'EntityRegistry((<Mapper at 0x7fcd1a276050; Downloads>,))' to '{}'
[2018-07-26 01:09:51,828] {/usr/lib/python2.7/site-packages/sqlalchemy/orm/path_registry.py:63} DEBUG - set 'memoized_setups' on path 'EntityRegistry((<Mapper at 0x7fcd1a2b5810; Shelf>,))' to '{}'
[2018-07-26 01:09:51,829] {/usr/lib/python2.7/site-packages/sqlalchemy/orm/path_registry.py:63} DEBUG - set 'memoized_setups' on path 'EntityRegistry((<Mapper at 0x7fcd1a7f1f10; User>,))' to '{}'
[2018-07-26 01:09:51,834] {/calibre-web/app/cps/gdriveutils.py:136} ERROR - Google Drive gdrive_credentials file not present, reauthenticate in config section

The gdrive_credentials file does exist.

**Comment by astrodad** [comment]
Having done nothing, it started to work, but then this morning I see this in the log:

[2018-07-26 02:54:25,608] {/calibre-web/app/cps/web.py:1803} ERROR - Message No refresh_token found.Please set access_type of OAuth to offline.
[2018-07-26 02:54:25,731] {/calibre-web/app/cps/web.py:1803} ERROR - Message No refresh_token found.Please set access_type of OAuth to offline.
[2018-07-26 02:54:25,743] {/calibre-web/app/cps/web.py:1803} ERROR - Message No refresh_token found.Please set access_type of OAuth to offline.
[2018-07-26 02:54:35,614] {/calibre-web/app/cps/gdriveutils.py:136} ERROR - Google Drive gdrive_credentials file not present, reauthenticate in config section

**Comment by OzzieIsaacs** [comment]
Could you please update to the newest commit, the error messages should be improved and showing better what's going on.

**Comment by OzzieIsaacs** [comment]
Authenticate button is now only shown if you are logged in.
