### ISSUE TITLE
500 error after editing user profile

### ISSUE THREAD

**Issue by rmzg** [janeczku/calibre-web#561]
A user tried to turn off the 'random books' section in her profile and thereafter got repeated 500 errors:

```
[2018-07-29 20:31:26,999] ERROR in app: Exception on /rated [GET]
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/calibre-web/app/cps/web.py", line 327, in decorated_view
    return func(*args, **kwargs)
  File "/calibre-web/app/cps/web.py", line 1135, in best_rated_books
    [db.Books.timestamp.desc()])
  File "/calibre-web/app/cps/web.py", line 487, in fill_indexpage
    random = db.session.query(db.Books).filter(common_filters())\
  File "/calibre-web/app/cps/web.py", line 480, in common_filters
    db.Books.tags.any(db.Tags.name.in_(config.mature_content_tags()))
  File "/calibre-web/app/cps/ub.py", line 497, in mature_content_tags
    return list(map(lstrip, self.config_mature_content_tags.split(",")))
AttributeError: 'NoneType' object has no attribute 'split'
```

This was solved by enabling the checkbox for 'show mature content'

**Comment by OzzieIsaacs** [comment]
Seems to be related to #549. Could you please try to update to the newest commit, afterwards it should work.
