### ISSUE TITLE
I can't install all dependencies on Raspbian?

### ISSUE THREAD

**Issue by tareefdev** [janeczku/calibre-web#573]
I have caibre-web successfully installed and running on Arch Linux, but today I tried to install it on my raspberry pi 3 which run with Raspiban (based on stretch Debian), so I cloned the repo, and then tried to execute `pip3 install --target vendor -r requirements.txt`, which installed some dependencies and then print this in terminal:

```
Installing collected packages: pytz, Babel, MarkupSafe, Jinja2, click, itsdangerous, Werkzeug, Flask, Flask-Babel, Flask-Login, blinker, Flask-Principal, six, singledispatch, backports-abc, iso-639, PyPDF2, idna, certifi, urllib3, chardet, requests, SQLAlchemy, tornado, Wand, unidecode
Exception:
Traceback (most recent call last):                                                                     
  File "/usr/local/lib/python3.5/dist-packages/pip/_internal/basecommand.py", line 141, in main        
    status = self.run(options, args)                                                                   
  File "/usr/local/lib/python3.5/dist-packages/pip/_internal/commands/install.py", line 347, in run    
    use_user_site=options.use_user_site,                                                               
  File "/usr/local/lib/python3.5/dist-packages/pip/_internal/req/__init__.py", line 49, in install_given_reqs                                                                                                 
    **kwargs
  File "/usr/local/lib/python3.5/dist-packages/pip/_internal/req/req_install.py", line 941, in install
    use_user_site=use_user_site, pycompile=pycompile,
  File "/usr/local/lib/python3.5/dist-packages/pip/_internal/req/req_install.py", line 526, in move_wheel_files
    warn_script_location=warn_script_location,
  File "/usr/local/lib/python3.5/dist-packages/pip/_internal/wheel.py", line 215, in move_wheel_files
    prefix=prefix,
  File "/usr/local/lib/python3.5/dist-packages/pip/_internal/locations.py", line 165, in distutils_scheme
    i.finalize_options()
  File "/usr/lib/python3.5/distutils/command/install.py", line 273, in finalize_options
    raise DistutilsOptionError("can't combine user with prefix, "
distutils.errors.DistutilsOptionError: can't combine user with prefix, exec_prefix/home, or install_(plat)base
```
I tried `sudo`, and `pip2` as well without any result.

**Comment by OzzieIsaacs** [comment]
pip2 is definitifly the wrong one (its the pip for python 2), so pip3 is the right one. Looks like some general problem with ip.

Please make sure to excecute the command while in the root folder of calibre-web.
Could you please try to use the command `pip3 install -r requirements.txt` this should install the dependencies "systemwide". If this isn't working could you please try to install the dependency one by one (open requirements.txt and paste the name of the dependency before the "="  to the command line like  `pip3 install tornado`...
If this isn't working, please try your favorite search engine with the phrase `can't combine user with prefix, exec_prefix/home, or install_(plat)base`, and try to find a solution by yourself.

**Comment by tareefdev** [comment]
This is strange because I tried to install dependencies using `root` but it didn't work, now I tried to install each one at a time with root, and I was able to install all of them, and so caliber-web works on my raspberry pi, thanks for your suggestion.
