### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by wonx** [janeczku/calibre-web#61]
Hello, thanks for this promising piece of software. I was looking for a more convenient way to access my ebook library from the network, and I think this is just what I was looking for.

Anyway, I often get this error on the browser (Firefox and Chrome):

```
Internal Server Error

The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the aplication.
```

While in the command line I can read this:

```
root@host:~/calibre-web-biblio# python cps.py
ERROR:cps.web:Exception on / [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/root/calibre-web-biblio/cps/web.py", line 393, in index
    return render_template('index.html', random=random, entries=entries, pagination=pagination, title="Latest Books")
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 128, in render_template
    context, ctx.app)
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 110, in _render
    rv = template.render(context)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 989, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/root/calibre-web-biblio/cps/templates/index.html", line 1, in top-level template code
    {% extends "layout.html" %}
  File "/root/calibre-web-biblio/cps/templates/layout.html", line 66, in top-level template code
    {% if g.user.is_authenticated() %}
AttributeError: 'bool' object has no attribute '__call__'
ERROR:tornado.access:500 GET / (192.168.1.132) 3776.21ms

```

Sometimes I can work around it if I first load http://localhost:8083/feed and then enter the main web page, but not all the time. Am I doing something wrong? The script is running on a Debian jessie server which is up to date.

Thank you in advance.

**Comment by cervinko** [comment]
Do you get this error when you are logged in to calibre-web or only as anonymous user?

Do you have flask-login installed on your system. if yes what version.

this could be related to https://github.com/miguelgrinberg/flasky/issues/74  but this is just a first guess.

**Comment by wonx** [comment]
Sorry for the delay, for some reason I was expecting an email notification. 
My error appears when using it as an anonymous user. I just changed the settings, and then the error is more similar to the one you pointed (TypeError: 'bool' object is not callable). The only way I've managed to enter my library is following this method: 1) enter http://url:port/feed. 2) enter login and password 3) enter http:/url:port. If I enter the library directly, I still got the same error.

I didn't have flask-login installed in my system. I just installed it via apt-get and got the 0.2.6-1 version. The problem still persists.

**Comment by OzzieIsaacs** [comment]
i remember an issue like this, caused by anonymous users. I fixed it, i can take a look at it later. Could you please try to switch anon user off and try it with activated user management

**Comment by wonx** [comment]
Yes. I'm currently using calibre-web with anon disabled. 
Btw, just for the sake of completeness, this is the error message I get when anon user is disabled (in config.ini):

```
root@host:~/calibre-web-biblio# python cps.py
ERROR:cps.web:Exception on /login [GET]
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/root/calibre-web-psico/cps/web.py", line 625, in login
    if current_user is not None and current_user.is_authenticated():
TypeError: 'bool' object is not callable
ERROR:tornado.access:500 GET /login?next=%2F (188.xxx.xxx.xxx) 5.56ms
```
Notice how, in the browser, I'm being redirected to http://host:port/login?next=%2F

**Comment by OzzieIsaacs** [comment]
I can reproduce the error by downloading after using the newest version of flask-login:
ERROR:cps.web:Exception on / [GET]
Traceback (most recent call last):
  File "C:\calibre-web\vendor\flask\app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\calibre-web\vendor\flask\app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\calibre-web\vendor\flask\app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\calibre-web\vendor\flask\app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\calibre-web\vendor\flask\app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:/calibre-web\cps\web.py", line 541, in index
    return render_template('index.html', random=random, entries=entries, pagination=pagination, title=_(u"Latest Books"))
  File "C:\calibre-web\vendor\flask\templating.py", line 128, in render_template
    context, ctx.app)
  File "C:\calibre-web\vendor\flask\templating.py", line 110, in _render
    rv = template.render(context)
  File "C:\calibre-web\vendor\jinja2\environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "C:\calibre-web\vendor\jinja2\environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\calibre-web\cps\templates\index.html", line 1, in top-level template code
    {% extends "layout.html" %}
  File "C:\calibre-web\cps\templates\layout.html", line 54, in top-level template code
    {% if g.user.is_authenticated() or g.user.is_anonymous() %}
AttributeError: 'bool' object has no attribute '__call__'
ERROR:tornado.access:500 GET / (127.0.0.1) 505.00ms

I try to look after it tomoorw.

**Comment by cervinko** [comment]
if this error only occurs with flask-login > 0.3.0 then everything is clear. flask-login changed is_authenticated to a property in UserMixin.
I think we should vendor the latest flask-login and adjust our code to it.

**Comment by OzzieIsaacs** [comment]
i can only reproduce it with a new flask-login version, otherwise it works for me

**Comment by wonx** [comment]
One temporary solution is downgrading the flask-login version. 
`pip uninstall flask-login` (or `apt-get remove python-flask-login` if installed via apt-get)
`pip install flask-login==0.2.11`

I tried it and it works.

**Comment by OzzieIsaacs** [comment]
Updated flask-login
