### ISSUE TITLE
Error 500 at login after first config under certain circumstances

### ISSUE THREAD

**Issue by OzzieIsaacs** [janeczku/calibre-web#611]
First reported from  @kianrafiee in Issue #609
First off, when I run a new setup of calibre-web, I always seem to get this HTTP error page when I add the initial setup info even though it starts to function fine afterwards.

**Comment by OzzieIsaacs** [comment]
Error is only occouring if a user is logged in (sessioncookies still active). Stacktrace:
[2018-09-06 21:08:57,305] ERROR in app: Exception on /config [POST]
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python27\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python27\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python27\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python27\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\Desktop\calibre-web\cps\web.py", line 446, in inner
    return f(*args, **kwargs)
  File "D:\Desktop\calibre-web\cps\web.py", line 2786, in basic_configuration
    return configuration_helper(1)
  File "D:\Desktop\calibre-web\cps\web.py", line 2970, in configuration_helper
    goodreads=goodreads_support, title=_(u"Basic Configuration"), page="config")
  File "D:\Desktop\calibre-web\cps\web.py", line 631, in render_title_template
    return render_template(instance=config.config_calibre_web_title, *args, **kwargs)
  File "C:\Python27\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "C:\Python27\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "C:\Python27\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "C:\Python27\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "D:\Desktop\calibre-web\cps\templates\config_edit.html", line 1, in top-level template code
    {% extends "layout.html" %}
  File "D:\Desktop\calibre-web\cps\templates\layout.html", line 2, in top-level template code
    <html lang="{{ g.user.locale }}">
  File "C:\Python27\lib\site-packages\jinja2\environment.py", line 430, in getattr
    return getattr(obj, attribute)
  File "C:\Python27\lib\site-packages\werkzeug\local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
  File "C:\Python27\lib\site-packages\sqlalchemy\orm\attributes.py", line 242, in __get__
    return self.impl.get(instance_state(instance), dict_)
  File "C:\Python27\lib\site-packages\sqlalchemy\orm\attributes.py", line 594, in get
    value = state._load_expired(state, passive)
  File "C:\Python27\lib\site-packages\sqlalchemy\orm\state.py", line 608, in _load_expired
    self.manager.deferred_scalar_loader(self, toload)
  File "C:\Python27\lib\site-packages\sqlalchemy\orm\loading.py", line 810, in load_scalar_attributes
    (state_str(state)))
DetachedInstanceError: Instance <User at 0x49fc9f0> is not bound to a Session; attribute refresh operation cannot proceed (Background on this error at : http://sqlalche.me/e/bhk3)

Error might be related to #588

**Comment by kianrafiee** [comment]
Hmm, maybe its a browser cache issue related to login? Because I just realized when I cleared my container and config folder, restarted container, it never asked for login info...
