### ISSUE TITLE
Administration: Cannot change log file path and name

### ISSUE THREAD

**Issue by Ribero** [janeczku/calibre-web#615]
Changing the path of the log file in the server administration GUI result in an error:

`Logfile location is not valid, please enter correct path`

I made many tentatives using different values: 

- /calibre-web/config/calibre-web.log -> error + no logfile created 
- config/calibre-web.log -> error + no logfile created 
- /calibre-web/config/ -> error + no logfile created 
- <empty>
- debug.log -> error 500 Internal Server Error  + a logfile IS created 

I'm using Calibre-Web (9/3/18, 7:12 PM) on Technosoft2k Docker image.

Log:

```
[2018-09-07 14:59:08,211] {/calibre-web/app/cps/web.py:2949} INFO - Reboot required, restarting                                                                                        
[2018-09-07 14:59:09,261] {/usr/lib/python2.7/site-packages/flask/app.py:1761} ERROR - Exception on /admin/config [POST]                                                               
Traceback (most recent call last):                                                                                                                                                     
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app                                                                                                         
    response = self.full_dispatch_request()                                                                                                                                            
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request                                                                                            
    rv = self.handle_user_exception(e)                                                                                                                                                 
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception                                                                                            
    reraise(exc_type, exc_value, tb)                                                                                                                                                   
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request                                                                                            
    rv = self.dispatch_request()                                                                                                                                                       
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request                                                                                                 
    return self.view_functions[rule.endpoint](**req.view_args)                                                                                                                         
  File "/usr/lib/python2.7/site-packages/flask_login/utils.py", line 261, in decorated_view                                                                                            
    return func(*args, **kwargs)                                                                                                                                                       
  File "/calibre-web/app/cps/web.py", line 438, in inner                                                                                                                               
    return f(*args, **kwargs)                                                                                                                                                          
  File "/calibre-web/app/cps/web.py", line 2684, in configuration                                                                                                                      
    return configuration_helper(0)                                                                                                                                                     
  File "/calibre-web/app/cps/web.py", line 2959, in configuration_helper                                                                                                               
    goodreads=goodreads_support, title=_(u"Basic Configuration"), page="config")                                                                                                       
  File "/calibre-web/app/cps/web.py", line 637, in render_title_template                                                                                                               
    return render_template(instance=config.config_calibre_web_title, *args, **kwargs)                                                                                                  
  File "/usr/lib/python2.7/site-packages/flask/templating.py", line 135, in render_template                                                                                            
    context, ctx.app)                                                                                                                                                                  
  File "/usr/lib/python2.7/site-packages/flask/templating.py", line 117, in _render                                                                                                    
    rv = template.render(context)                                                                                                                                                      
  File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 1008, in render                                                                                                  
    return self.environment.handle_exception(exc_info, True)                                                                                                                           
  File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 780, in handle_exception                                                                                         
    reraise(exc_type, exc_value, tb)                                                                                                                                                   
  File "/calibre-web/app/cps/templates/config_edit.html", line 1, in top-level template code                                                                                           
    {% extends "layout.html" %}                                                                                                                                                        
  File "/calibre-web/app/cps/templates/layout.html", line 2, in top-level template code                                                                                                
    <html lang="{{ g.user.locale }}">                                                                                                                                                  
  File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 430, in getattr                                                                                                  
    return getattr(obj, attribute)                                                                                                                                                     
  File "/usr/lib/python2.7/site-packages/werkzeug/local.py", line 347, in __getattr__                                                                                                  
    return getattr(self._get_current_object(), name)                                                                                                                                   
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/attributes.py", line 242, in __get__                                                                                           
    return self.impl.get(instance_state(instance), dict_)                                                                                                                              
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/attributes.py", line 594, in get                                                                                               
    value = state._load_expired(state, passive)                                                                                                                                        
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/state.py", line 608, in _load_expired                                                                                          
    self.manager.deferred_scalar_loader(self, toload)                                                                                                                                  
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/loading.py", line 813, in load_scalar_attributes                                                                               
    (state_str(state)))                                                                                                                                                                
DetachedInstanceError: Instance <User at 0x7f9bdaf07150> is not bound to a Session; attribute refresh operation cannot proceed (Background on this error at: http://sqlalche.me/e/bhk3)
[2018-09-07 14:59:10,474] {/calibre-web/app/cps/server.py:72} INFO - Performing restart of Calibre-Web    
```

**Comment by OzzieIsaacs** [comment]
It's the oposite way around, the server is starting new to get the new settings effective (which is required for some of the settings) and then fails, because the login data belong to the old server instance.  Related to #611

**Comment by OzzieIsaacs** [comment]
I can't reproduce the error.
I did a blind change, could you please update to the newest version and try it again, there is a certain chance that it is working now (better). 
Looks like a timing issue.

**Comment by Ribero** [comment]
The blind change seems to be the good one: I was not able to reproduce the issue anymore... Fixed for me.
