### ISSUE TITLE
500 Internal Server Error when you click on "Default" bookshelf (on main page)

### ISSUE THREAD

**Issue by holta** [janeczku/calibre-web#620]
When clicking the (very prominent, pre-installed) "Default" bookshelf on Calibre-Web's main page, this "Default" bookshelf (http://box/books/shelf/1) fails shows this error in the browser:

>Internal Server Error
>
>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

CLARIF:
- the server is NOT overloaded
- rebooting does not help
- this error occurs regardless if a book can been tagged as being on the "Default" bookshelf (or not!)
- other (manually-created) bookshelves like http://box/books/shelf/2 DO work!
- is it helpful if we run this very same test on other OS's like Debian 9.5 and Raspbian on Raspberry Pi?

Does this error log below from /usr/local/calibre-web/calibre-web.log help?  (excerpted from the Ubuntu 18.04 Desktop/Graphical PC [not server edition of 18.04] where Calibre-Web is running)
```
[2018-09-10 11:57:54,326] {/usr/local/calibre-web/cps/web.py:187} INFO - Starting Calibre Web...
[2018-09-10 11:57:54,537] {/usr/local/calibre-web/cps/server.py:56} INFO - Starting Tornado server
[2018-09-10 11:58:10,215] {/usr/local/calibre-web/vendor/flask/app.py:1761} ERROR - Exception on /shelf/1 [GET]
Traceback (most recent call last):
  File "/usr/local/calibre-web/vendor/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/calibre-web/vendor/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/calibre-web/vendor/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/calibre-web/vendor/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/calibre-web/vendor/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/calibre-web/cps/web.py", line 332, in decorated_view
    return func(*args, **kwargs)
  File "/usr/local/calibre-web/cps/web.py", line 2552, in show_shelf
    shelf=shelf, page="shelf")
  File "/usr/local/calibre-web/cps/web.py", line 639, in render_title_template
    return render_template(instance=config.config_calibre_web_title, *args, **kwargs)
  File "/usr/local/calibre-web/vendor/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/usr/local/calibre-web/vendor/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/calibre-web/cps/templates/shelf.html", line 1, in top-level template code
    {% extends "layout.html" %}
  File "/usr/local/calibre-web/cps/templates/layout.html", line 185, in top-level template code
    {% block body %}{% endblock %}
  File "/usr/local/calibre-web/cps/templates/shelf.html", line 24, in block "body"
    <p class="title">{{entry.title|shortentitle}}</p>
  File "/usr/local/calibre-web/cps/web.py", line 365, in shortentitle_filter
    text = s.split()
UndefinedError: 'None' has no attribute 'title'
```
Background: https://github.com/iiab/iiab/issues/1040#issuecomment-419745320

**Comment by OzzieIsaacs** [comment]
I doublechecked: if you set up the system no default shelf is created. 
But anyway we have the problem. The logbook helps a lot, thanks for providing it. Somehow you managed to add a book to the shelf which is no longer existing in the database. Usually if calibre-web detects such a book it should autodelete the entry to clean the database. I'll check why this didn't happen in this case.
It's not necessary to do the test on another operating system (my expectation is: no default bookshelf, no problem)
Thanks for reporting

**Comment by holta** [comment]
> Somehow you managed to add a book to the shelf which is no longer existing in the database.

@arky as the primary developer who integrated Calibre-Web into Internet-in-a-Box (https://github.com/iiab) might you have ideas as to why this is happening?

> Usually if calibre-web detects such a book it should autodelete the entry to clean the database. I'll check why this didn't happen in this case.

Profound thanks @OzzieIsaacs for your amazing work~

**Comment by OzzieIsaacs** [comment]
I included a fix which deletes "vanished" books from the shelf. 
I also checked that deleting books also deletes entries for the book from the read list and also from all shelfs, so I have no clue how this could happen. 
If you anyhow could reproduce how you did this it would be great to kill the problem at it's source and not at it's "drain". (Now there is a logbook entry generated in case the event occours)

**Comment by OzzieIsaacs** [comment]
I think I found it: In case of adding book X of database 1 to a shelf and lateron change the database to database 2 where no book X is present the crash can occur.
-> delete readlinks and shelfs on a database change. (A warning message should appear!)

**Comment by holta** [comment]
Earlier in August @arky had [written](https://github.com/iiab/iiab/blob/master/roles/calibre-web/README.rst#known-issues) "Trying to access an empty public bookshelf causes a system error."

Is this now resolved sufficiently?

**Comment by OzzieIsaacs** [comment]
I did some tests with empty public book shelfs, I can't reproduce the problem. I think this problem is related to the original issue, or it was the same issue
