### ISSUE TITLE
Attempts to reconvert if mobi already exists

### ISSUE THREAD

**Issue by weidercs** [janeczku/calibre-web#625]
When I try "send to kindle" using ebook-convert on a book that's already been converted, looking at the logs it converts it again and when trying to add it to the calibre db it fails with a sql non-unique error.

```
calibre-web          | [2018-09-13 03:11:57,099] DEBUG in worker: 1% Converting input to HTML...
calibre-web          | [2018-09-13 03:11:57,099] DEBUG in worker: InputFormatPlugin: EPUB Input running
calibre-web          | [2018-09-13 03:11:57,099] DEBUG in worker: on /books/Bob Woodward/Fear (503)/Fear - Bob Woodward.epub
calibre-web          | [2018-09-13 03:11:57,255] DEBUG in worker: Found HTML cover ops/xhtml/cover.html
calibre-web          | [2018-09-13 03:11:57,262] DEBUG in worker: Parsing all content...
calibre-web          | [2018-09-13 03:11:57,431] DEBUG in worker: MediaQuery: No match: ('IDENT', u'amzn-kf8', 443, 8)
calibre-web          | [2018-09-13 03:11:57,432] DEBUG in worker: MediaQuery: No match for None in Choice(Sequence(ONLY|NOT, media_type, Sequence(AND, Sequence(expression, media_feature, Sequence(colon, Choice(ColorValue, Dimension, Value)), expression END))), Sequence(Sequence(expression, media_feature, Sequence(colon, Choice(ColorValue, Dimension, Value)), expression END), Sequence(AND, Sequence(expression, media_feature, Sequence(colon, Choice(ColorValue, Dimension, Value)), expression END))))
calibre-web          | [2018-09-13 03:11:57,432] DEBUG in worker: No content to parse.
calibre-web          | [2018-09-13 03:11:57,432] DEBUG in worker: MediaQuery: No content.
calibre-web          | [2018-09-13 03:11:57,433] DEBUG in worker: MediaQuery: No match: ('IDENT', u'amzn-mobi', 448, 8)
calibre-web          | [2018-09-13 03:11:57,433] DEBUG in worker: MediaQuery: No match for None in Choice(Sequence(ONLY|NOT, media_type, Sequence(AND, Sequence(expression, media_feature, Sequence(colon, Choice(ColorValue, Dimension, Value)), expression END))), Sequence(Sequence(expression, media_feature, Sequence(colon, Choice(ColorValue, Dimension, Value)), expression END), Sequence(AND, Sequence(expression, media_feature, Sequence(colon, Choice(ColorValue, Dimension, Value)), expression END))))
calibre-web          | [2018-09-13 03:11:57,433] DEBUG in worker: No content to parse.
calibre-web          | [2018-09-13 03:11:57,433] DEBUG in worker: MediaQuery: No content.
calibre-web          | [2018-09-13 03:11:57,835] DEBUG in worker: 34% Running transforms on e-book...
calibre-web          | [2018-09-13 03:11:57,843] DEBUG in worker: Merging user specified metadata...
calibre-web          | [2018-09-13 03:11:57,844] DEBUG in worker: Detecting structure...
calibre-web          | [2018-09-13 03:11:57,864] DEBUG in worker: 	Detected chapter: PROLOGUE
calibre-web          | [2018-09-13 03:11:57,888] DEBUG in worker: Flattening CSS and remapping font sizes...
calibre-web          | [2018-09-13 03:12:00,248] DEBUG in worker: Source base font size is 12.00000pt
calibre-web          | [2018-09-13 03:12:00,819] DEBUG in worker: Removing fake margins...
calibre-web          | [2018-09-13 03:12:00,838] DEBUG in worker: Cleaning up manifest...
calibre-web          | [2018-09-13 03:12:00,838] DEBUG in worker: Trimming unused files from manifest...
calibre-web          | [2018-09-13 03:12:01,003] DEBUG in worker: Creating MOBI Output...
calibre-web          | [2018-09-13 03:12:01,003] DEBUG in worker: 67% Running MOBI Output plugin
calibre-web          | [2018-09-13 03:12:01,059] DEBUG in worker: Serializing resources...
calibre-web          | libpng warning: iCCP: known incorrect sRGB profile
calibre-web          | libpng warning: iCCP: known incorrect sRGB profile
calibre-web          | libpng warning: iCCP: known incorrect sRGB profile
calibre-web          | [2018-09-13 03:12:01,564] DEBUG in worker: Creating MOBI 6 output
calibre-web          | [2018-09-13 03:12:01,636] DEBUG in worker: Applying case-transforming CSS...
calibre-web          | [2018-09-13 03:12:05,116] DEBUG in worker: Rasterizing SVG images...
calibre-web          | [2018-09-13 03:12:05,136] DEBUG in worker: Converting XHTML to Mobipocket markup...
calibre-web          | [2018-09-13 03:12:11,165] DEBUG in worker: Serializing markup content...
calibre-web          | [2018-09-13 03:12:11,660] DEBUG in worker:   Compressing markup content...
calibre-web          | [2018-09-13 03:12:14,937] DEBUG in worker: Generating MOBI index for a book
calibre-web          | [2018-09-13 03:12:14,956] DEBUG in worker: MOBI output written to /books/Bob Woodward/Fear (503)/Fear - Bob Woodward.mobi
calibre-web          | [2018-09-13 03:12:14,956] DEBUG in worker: Output saved to   /books/Bob Woodward/Fear (503)/Fear - Bob Woodward.mobi
calibre-web          | [2018-09-13 03:12:15,017] DEBUG in worker: 
calibre-web          | Exception in thread Thread-1:
calibre-web          | Traceback (most recent call last):
calibre-web          |   File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
calibre-web          |     self.run()
calibre-web          |   File "/calibre-web/app/cps/worker.py", line 175, in run
calibre-web          |     self.convert_any_format()
calibre-web          |   File "/calibre-web/app/cps/worker.py", line 219, in convert_any_format
calibre-web          |     filename = self.convert_ebook_format()
calibre-web          |   File "/calibre-web/app/cps/worker.py", line 311, in convert_ebook_format
calibre-web          |     web.db.session.commit()
calibre-web          |   File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 943, in commit
calibre-web          |     self.transaction.commit()
calibre-web          |   File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 467, in commit
calibre-web          |     self._prepare_impl()
calibre-web          |   File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 447, in _prepare_impl
calibre-web          |     self.session.flush()
calibre-web          |   File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2254, in flush
calibre-web          |     self._flush(objects)
calibre-web          |   File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2380, in _flush
calibre-web          |     transaction.rollback(_capture_exception=True)
calibre-web          |   File "/usr/lib/python2.7/site-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
calibre-web          |     compat.reraise(exc_type, exc_value, exc_tb)
calibre-web          |   File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2344, in _flush
calibre-web          |     flush_context.execute()
calibre-web          |   File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 391, in execute
calibre-web          |     rec.execute(self)
calibre-web          |   File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 556, in execute
calibre-web          |     uow
calibre-web          |   File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 181, in save_obj
calibre-web          |     mapper, table, insert)
calibre-web          |   File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 866, in _emit_insert_statements
calibre-web          |     execute(statement, params)
calibre-web          |   File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 948, in execute
calibre-web          |     return meth(self, multiparams, params)
calibre-web          |   File "/usr/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 269, in _execute_on_connection
calibre-web          |     return connection._execute_clauseelement(self, multiparams, params)
calibre-web          |   File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1060, in _execute_clauseelement
calibre-web          |     compiled_sql, distilled_params
calibre-web          |   File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1200, in _execute_context
calibre-web          |     context)
calibre-web          |   File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception
calibre-web          |     exc_info
calibre-web          |   File "/usr/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 265, in raise_from_cause
calibre-web          |     reraise(type(exception), exception, tb=exc_tb, cause=cause)
calibre-web          |   File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
calibre-web          |     context)
calibre-web          |   File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 509, in do_execute
calibre-web          |     cursor.execute(statement, parameters)
calibre-web          | IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: data.book, data.format [SQL: u'INSERT INTO data (book, format, uncompressed_size, name) VALUES (?, ?, ?, ?)'] [parameters: (503, u'mobi', 16014776, u'Fear - Bob Woodward')] (Background on this error at: http://sqlalche.me/e/gkpj)
calibre-web          | 
```

**Comment by bodybybuddha** [comment]
@weidercs - The only way I got this to occur in my setup was if I attempted to Send to Kindle multiple times and before the previous request was fulfilled.  Also could occur if I asked for a conversion, and then a quick Send to Kindle request.  

Can I assume this is how this could have occurred for you?  I wasn't able to recreate the issue if I allowed the system to complete the tasks before attempting to make another request.  Once the system is done with the first request, I wasn't able to create a second request b/c the system already knew there was a mobi file. (follow?)

In any event, I think this does expose an issue that should be fixed.  However, if the system does fail on subsequent requests, the easiest work around is to wait till all tasks are completed and then try to execute the same request again later - hopefully the system would have caught up and won't allow you to make another conversion request, etc.

**Comment by bodybybuddha** [comment]
I submitted PR to help with the situation above.  The bit I added was to check to see if the targeted format already exists on disk.  The assumption is that if one does exist, a conversion has happened (and we'll just assume the database was updated correctly here...) so the task item will be marked at 100% complete.  

This should allow the conversion only and send-to-kindle workflows to continue to work without a lot of rethinking (coding) of the existing workflow.

**Comment by bodybybuddha** [comment]
@weidercs - can you download the latest version and see if you can reproduce the issue?

**Comment by weidercs** [comment]
apologies, was out of town for the weekend.  I have multiple users and it was easy to reproduce by having the 1st user send to kindle, then having a 2nd user send the same file (even after it was sent successfully) send to kindle.  I'll download the PR and see if it fixes things.
Thanks!

**Comment by weidercs** [comment]
looks good now, thanks!
```
calibre-web          | [2018-09-17 16:49:19,313] INFO in worker: Book id 503 already converted to .mobi
```
closing.

**Comment by bodybybuddha** [comment]
Cool - this fix should work as long as we don't have more than two worker threads (main, and one worker).  We'd have to figure out a different method if we decide in the future to have a pool of threads working.  We'll cross that bridge later.
