### ISSUE TITLE
submit metadata error:[Errno 2] No such file or directory

### ISSUE THREAD

**Issue by SilentZhang** [janeczku/calibre-web#637]
An error occurred while updating metadata:
Rename title from: '/home/silentstorm_zc/Books/Calibre/Qiao Zhi Ma Ding/Bing Yu Huo Zhi Ge (Quan 15Ce ) (273)' to '/home/silentstorm_zc/Books/Calibre/Qiao Zhi Ma Ding/Bing Yu Huo Zhi Ge (273)' failed with error: [Errno 2] No such file or directory

calibre-web.log:
[2018-09-19 02:01:42,991] {/var/dev/calibre-web/cps/helper.py:239} ERROR - Rename title from: /home/silentstorm_zc/Books/Calibre/Qiao Zhi Ma Ding/Bing Yu Huo Zhi Ge (Quan 15Ce ) (273) to /home/silentstorm_zc/Books/Calibre/Qiao Zhi Ma Ding/Bing Yu Huo Zhi Ge (273)
[2018-09-19 02:01:42,992] {/var/dev/calibre-web/cps/helper.py:240} ERROR - [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/var/dev/calibre-web/cps/helper.py", line 230, in update_dir_structure_file
    os.renames(path, new_title_path)
  File "/usr/lib64/python2.7/os.py", line 199, in renames
    rename(old, new)
OSError: [Errno 2] No such file or directory

**Comment by OzzieIsaacs** [comment]
Could you please check if the original directory: '/home/silentstorm_zc/Books/Calibre/Qiao Zhi Ma Ding/Bing Yu Huo Zhi Ge (Quan 15Ce ) (273)'
Is a valid and accessible (by the user running Calibre-web) directory? The user should have write permissions, as the directory names have to be changed.

**Comment by OzzieIsaacs** [comment]
No response for long time, closing.
