### ISSUE TITLE
Install it on Synology NAS

### ISSUE THREAD

**Issue by georgecarstoiu** [janeczku/calibre-web#641]
Hey,

I've been trying to run it from a Synology NAS.

After installing dependencies I got the following:
```
pyopenssl 16.0.0 has requirement cryptography>=1.3, but you'll have cryptography 0.9.3 which is incompatible.
caldav 0.1.10 has requirement lxml==2.1.5, but you'll have lxml 3.6.0 which is incompatible.
```

When I tried to run the cps.py file I get the following trace:
```
Traceback (most recent call last):
  File "cps.py", line 13, in <module>
    from cps.server import Server
  File "/volume1/homes/george.carstoiu/calibre-web/cps/server.py", line 20, in <module>
    import web
  File "/volume1/homes/george.carstoiu/calibre-web/cps/web.py", line 47, in <module>
    import helper
  File "/volume1/homes/george.carstoiu/calibre-web/cps/helper.py", line 14, in <module>
    import worker
  File "/volume1/homes/george.carstoiu/calibre-web/cps/worker.py", line 152, in <module>
    class WorkerThread(threading.Thread):
  File "/volume1/homes/george.carstoiu/calibre-web/cps/worker.py", line 362, in WorkerThread
    text=_(u'This e-mail has been sent via Calibre-Web.')):
  File "/volume1/homes/george.carstoiu/calibre-web/vendor/flask_babel/__init__.py", line 552, in gettext
    t = get_translations()
  File "/volume1/homes/george.carstoiu/calibre-web/vendor/flask_babel/__init__.py", line 217, in get_translations
    return support.NullTranslations()
AttributeError: 'module' object has no attribute 'NullTranslations'
```

A bit stuck at this point. Anybody an idea on how to address this? Thanks!

**Comment by bodybybuddha** [comment]
I don't have an answer for your posted issue - but have you explored the docker implementation on your NAS?  If you have a NAS that can run docker, it'll be worth learning docker as there will be a lot of other containers you could use -- and you'll not have to worry too much about configurations.

**Comment by georgecarstoiu** [comment]
My DS415Play does not support Docker unfortunately.

**Comment by Technosoft2000** [comment]
Hi @georgecarstoiu,

if you don't have **pip** installed yet then do the following:
```
root@NAS:~# cd /tmp

root@NAS:/tmp# wget https://bootstrap.pypa.io/get-pip.py

--2018-09-23 12:58:56--  https://bootstrap.pypa.io/get-pip.py
Resolving bootstrap.pypa.io... 151.101.64.175, 151.101.192.175, 151.101.0.175, ...
Connecting to bootstrap.pypa.io|151.101.64.175|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1642522 (1.6M) [text/x-python]
Saving to: 'get-pip.py'

get-pip.py                                   100%[============================================================================================>]   1.57M  6.37MB/s    in 0.2s    

2018-09-23 12:58:57 (6.37 MB/s) - 'get-pip.py' saved [1642522/1642522]

root@NAS:/tmp# python get-pip.py

/usr/local/lib/python2.7/site-packages/cffi/model.py:526: UserWarning: 'point_conversion_form_t' has no values explicitly defined; next version will refuse to guess which integer
 type it is meant to be (unsigned/signed, int/long)
  % self._get_c_name())
Collecting pip
  Downloading https://files.pythonhosted.org/packages/5f/25/e52d3f31441505a5f3af41213346e5b6c221c9e086a166f3703d2ddaf940/pip-18.0-py2.py3-none-any.whl (1.3MB)
    100% |████████████████████████████████| 1.3MB 6.0MB/s 
Collecting wheel
  Downloading https://files.pythonhosted.org/packages/81/30/e935244ca6165187ae8be876b6316ae201b71485538ffac1d718843025a9/wheel-0.31.1-py2.py3-none-any.whl (41kB)
    100% |████████████████████████████████| 51kB 8.2MB/s 
Installing collected packages: pip, wheel
Successfully installed pip-18.0 wheel-0.31.1

root@NAS:/tmp# pip --version
/usr/local/lib/python2.7/site-packages/cffi/model.py:526: UserWarning: 'point_conversion_form_t' has no values explicitly defined; next version will refuse to guess which integer
 type it is meant to be (unsigned/signed, int/long)
  % self._get_c_name())
pip 18.0 from /usr/lib/python2.7/site-packages/pip (python 2.7)

```

Then could you please execute the following command to list the outdated python packages and post the result:
`pip list --outdated`

on my NAS I got then the following list as example:
```
Package          Version            Latest   Type 
---------------- ------------------ -------- -----
attrs            16.0.0             18.2.0   wheel
Babel            0.9.6              2.6.0    wheel
caldav           0.1.10             0.5.0    sdist
cffi             1.6.0              1.11.5   wheel
coverage         4.1                4.5.1    wheel
cryptography     0.9.3              2.3.1    wheel
Cython           0.24               0.28.5   wheel
decorator        4.0.9              4.3.0    wheel
docutils         0.12               0.14     wheel
FormEncode       1.3.0              1.3.1    sdist
gevent           1.0.2              1.3.6    wheel
greenlet         0.4.9              0.4.15   wheel
idna             2.1                2.7      wheel
ipaddress        1.0.16             1.0.22   wheel
Jinja2           2.8                2.10     wheel
lxml             3.6.0              4.2.5    wheel
Mako             1.0.4.dev0         1.0.7    sdist
MarkupSafe       0.23               1.0      sdist
mock             1.0.1              2.0.0    wheel
netifaces        0.10.4             0.10.7   wheel
passlib          1.6.5.post20170913 1.7.1    wheel
Pillow           3.2.0              5.2.0    wheel
psutil           4.2.0              5.4.7    sdist
psycopg2         2.6.1              2.7.5    wheel
py               1.4.31             1.6.0    wheel
pyasn1           0.1.9              0.4.4    wheel
pyasn1-modules   0.0.8              0.2.2    wheel
pycparser        2.14               2.19     sdist
pycurl           7.19.5.1           7.43.0.2 sdist
pydot            1.1.0              1.2.4    sdist
PyGreSQL         5.0                5.0.6    sdist
pykerberos       1.1.11             1.2.1    sdist
pyOpenSSL        16.0.0             18.0.0   wheel
pyparsing        2.1.4              2.2.1    wheel
pyserial         3.1                3.4      wheel
pytest           2.9.1              3.8.1    wheel
python-dateutil  2.5.3              2.7.3    wheel
python-ldap      2.4.25             3.1.0    sdist
python-stdnum    1.4                1.9      wheel
pytz             2016.4             2018.5   wheel
pyusb            1.0.0              1.0.2    sdist
PyYAML           3.11               3.13     sdist
qrcode           5.3                6.0      wheel
reportlab        3.3.0              3.5.8    wheel
requests         2.10.0             2.19.1   wheel
service-identity 16.0.0             17.0.0   wheel
setuptools       25.1.6             40.4.2   wheel
simplejson       3.8.2              3.16.0   sdist
six              1.10.0             1.11.0   wheel
sqlparse         0.1.11             0.2.4    wheel
Twisted          13.0.0             18.7.0   sdist
unittest2        0.5.1              1.1.0    wheel
vobject          0.9.2              0.9.6.1  sdist
Werkzeug         0.11.10            0.14.1   wheel
xattr            0.8.0              0.9.6    sdist
xlwt             1.1.1              1.3.0    wheel
zope.interface   4.1.3              4.5.0    sdist
```

With the following command you can upgrade the outdated packages:
` pip install --upgrade <package>`

For **`<package>`** you've to insert the name of the package you want to upgrade.

Here is a one-liner to upgrade all outdated packages at once:
`pip list --outdated --format=freeze | grep -v '^\-e' | cut -d = -f 1  | xargs -n1 pip install -U`

If you want only to test which packages he would update then use the following command:
`pip list --outdated --format=freeze | grep -v '^\-e' | cut -d = -f 1  | xargs -n1 echo`

Btw. be careful updating all packages at once, because it depends which python applications you're running and which dependencies they have and it could then result that they don't run anymore.
That is the reason why to prefer a Docker container if possible, because the application is then isolated from the rest of the system, I know in your case you can't use a Docker container because it isn't supported on your NAS :-|

**Comment by georgecarstoiu** [comment]
Hey Technosoft2000 ,

Thank you for the detailed message. Tried it several times, but kept running into different issues along the way. Will stick to having the server on my Windows machine for now.

Will close the ticket. It is a good basis for other people who want to give it a go.

**Comment by Technosoft2000** [comment]
I've found the following article which can be interessting for others:

**How to install Docker on an unsupported Synology NAS**
https://tylermade.net/2017/09/28/how-to-install-docker-on-an-unsupported-synology-nas/

The important thing/note is that this will only work if the Synology NAS uses an 64bit Intel CPU like the 
**DS416play**: Intel Celeron N3060, 2x 1.60GHz.

The **DS415play**: Intel Atom CE5335, 2x 1.60GHz is a 32bit CPU and therefore the above article will not work.

Also ARM CPU's are not supported.

Here an overview of all CPU's used at Synology:
https://www.synology-wiki.de/index.php/Welchen_Prozessortyp_besitzt_mein_System%3F
