### ISSUE TITLE
Google Drive error: No refresh_token found.Please set access_type of OAuth to offline.

### ISSUE THREAD

**Issue by MaximMityutko** [janeczku/calibre-web#644]
Using docker container for calibre-web; Google Drive is authenticated and works fine for approx. 8 hours, but afterwards book images stop displaying and I see following errors in log:

[2018-09-25 06:43:40,020] ERROR in helper: Error Message: No refresh_token found.Please set access_type of OAuth to offline.
[2018-09-25 06:43:40,021] ERROR in helper: No refresh_token found.Please set access_type of OAuth to offline.
Traceback (most recent call last):
  File "/app/calibre-web/cps/helper.py", line 324, in get_book_cover
    path=gd.get_cover_via_gdrive(cover_path)
  File "/app/calibre-web/cps/gdriveutils.py", line 464, in get_cover_via_gdrive
    df = getFileFromEbooksFolder(cover_path, 'cover.jpg')
  File "/app/calibre-web/cps/gdriveutils.py", line 240, in getFileFromEbooksFolder
    drive = getDrive(Gdrive.Instance().drive)
  File "/app/calibre-web/cps/gdriveutils.py", line 149, in getDrive
    drive.auth.Refresh()
  File "/usr/lib/python2.7/site-packages/pydrive/auth.py", line 470, in Refresh
    raise RefreshError('No refresh_token found.'
RefreshError: No refresh_token found.Please set access_type of OAuth to offline.

And when I try to reach /admin/config the request times out. Tried to create new OAuth token in Google Developers console (double checked to use Web Application) but the result is the same.

Any suggestions?

**Comment by OzzieIsaacs** [comment]
I think the error-message is missleading, it's not a problem with the file itself, but somehow the authentification token is lost in the software. 
It's very strange that the config page is timing out, are there any relevant logbook entries regarding this?

**Comment by MaximMityutko** [comment]
I redeployed containers yesterday's evening and recreated client_secrets. In the morning everything was fine. I'll keep an eye out and upload the logs if the problem reoccurs.

**Comment by MaximMityutko** [comment]
I've been running container for a week now. Looks good, have not seen this error.
