### ISSUE TITLE
Metadata update error if syncing with Google Drive

### ISSUE THREAD

**Issue by MaximMityutko** [janeczku/calibre-web#646]
Scenario: 
1. Upload the book with no author information.
2. Try to get metadata from other services, e.g. Google.
3. Metadata update fails with the following error in logs:

[2018-09-26 13:23:56,027] ERROR in web: 'cps.db.Languages object' has no attribute 'language_name'
Traceback (most recent call last):
  File "/calibre-web/app/cps/web.py", line 3671, in edit_book
    title=_(u"edit metadata"), page="editbook")
  File "/calibre-web/app/cps/web.py", line 639, in render_title_template
    return render_template(instance=config.config_calibre_web_title, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/usr/lib/python2.7/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/calibre-web/app/cps/templates/book_edit.html", line 1, in top-level template code
    {% extends "layout.html" %}
  File "/calibre-web/app/cps/templates/layout.html", line 185, in top-level template code
    {% block body %}{% endblock %}
  File "/calibre-web/app/cps/templates/book_edit.html", line 108, in block "body"
    <input type="text" class="form-control typeahead" name="languages" id="languages" value="{% for language in book.languages %}{{language.language_name.strip()}}{% if not loop.last %}, {% endif %}{% endfor %}">
  File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 430, in getattr
    return getattr(obj, attribute)
UndefinedError: 'cps.db.Languages object' has no attribute 'language_name'

I see that file was successfully uploaded to /books/Unknown, synced to Google Drive/<<library>>/Unknown and afterwards removed from /books.

**Comment by OzzieIsaacs** [comment]
It should be fixed now
