### ISSUE TITLE
500 Internal Server Error with nginx reverse proxy

### ISSUE THREAD

**Issue by 97carmine** [janeczku/calibre-web#648]
I have calibre web running through a reverse proxy with nginx but I can not access it due to 500 Internal Server Error. The log shows this:
 
```
Traceback (most recent call last):
  File "/opt/calibre-web/vendor/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/calibre-web/vendor/flask/app.py", line 1816, in full_dispatch_request
    return self.finalize_request(rv)
  File "/opt/calibre-web/vendor/flask/app.py", line 1833, in finalize_request
    response = self.process_response(response)
  File "/opt/calibre-web/vendor/flask/app.py", line 2114, in process_response
    self.session_interface.save_session(self, ctx.session, response)
  File "/opt/calibre-web/vendor/flask/sessions.py", line 384, in save_session
    samesite=samesite
TypeError: set_cookie() got an unexpected keyword argument 'samesite'
```

Regards

**Comment by 97carmine** [comment]
I have installed flask v1.0.2

This is my nginx config

```
server {
     listen [::]:443 ssl http2;
     listen 443 ssl http2;
     server_name  mydomain.com;
     server_tokens off;
     etag on;
     ssl_certificate /etc/certbot/live/mydomain.com/fullchain.pem; # managed by Certbot
     ssl_certificate_key /etc/certbot/live/mydomain.com/privkey.pem; # managed by Certbot
     ssl_protocols TLSv1.2 TLSv1.3;
     ssl_ciphers 'ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:TLS13-CHACHA20-POLY1305-SHA256:TLS13-AES-256-GCM-SHA384';
     ssl_prefer_server_ciphers on;
     ssl_stapling on;
     ssl_stapling_verify on;
     ssl_session_timeout 1d;
     ssl_session_cache shared:SSL:50m;
     ssl_session_tickets on;
     resolver 8.8.8.8 8.8.4.4 valid=200s;
     resolver_timeout 5s;
     add_header Strict-Transport-Security 'max-age=31536000; includeSubDomains; preload';
     add_header X-XSS-Protection "1; mode=block";
     add_header X-Frame-Options SAMEORIGIN;
     add_header X-Content-Type-Options nosniff;
     http2_max_field_size 16k;
     http2_max_header_size 32k;
     ssl_ecdh_curve secp384r1;
     proxy_set_header Host $host;
     fastcgi_pass_request_headers on;

     root /var/www/domain;
     index index.php index.html;

     access_log /var/log/nginx/apps.access.log;
     error_log /var/log/nginx/apps.error.log;
     }

     ## calibre web ##
     location /calibre {
          client_max_body_size 20M;
	  proxy_pass              http://127.0.0.1:8083/;
          proxy_set_header        Host            $http_host;
          proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header        X-Scheme        $scheme;
          proxy_set_header        X-Script-Name   /calibre;
     }
```

I have web gauge installed on a computer with OpenSUSE 15.0, python 2.7 without docker

**Comment by 97carmine** [comment]
Thanks, I only had to update the version since by default OpenSUSE 15.0 includes the version 0.12.2 and I have used the version 0.14.1 available in Tumbleweed and calibre web already works perfectly
