### ISSUE TITLE
Error when opening advanced search

### ISSUE THREAD

**Issue by joshjhall** [janeczku/calibre-web#66]
I'm getting the following error report in the logs.

```
[2016-10-03 00:43:43,826] {/opt/calibre/vendor/flask/app.py:1423} ERROR - Exception on /advanced_search [GET]
Traceback (most recent call last):
  File "/opt/calibre/vendor/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/calibre/vendor/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/calibre/vendor/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/calibre/vendor/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/calibre/vendor/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/calibre/cps/web.py", line 492, in advanced_search
    author_name = request.args.get("author_name").strip()
AttributeError: 'NoneType' object has no attribute 'strip'
```

**Comment by OzzieIsaacs** [comment]
Should work now, please check
