### ISSUE TITLE
Error on view /tasks

### ISSUE THREAD

**Issue by EternalDeiwos** [janeczku/calibre-web#698]
I uploaded a whole series of EPUBs all at once and now I get this error when I try to browse `/tasks`:

```
[2018-11-06 09:59:07,326] ERROR in app: Exception on /tasks [GET]
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/python2.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/app/calibre-web/cps/web.py", line 1731, in get_tasks_status
    tasks=helper.global_WorkerThread.get_taskstatus()
  File "/app/calibre-web/cps/worker.py", line 205, in get_taskstatus
    if self.queue[self.current]['status'] == STAT_STARTED:
IndexError: list index out of range
::ffff:172.17.0.1 - - [2018-11-06 09:59:07] "GET /calibre/tasks HTTP/1.0" 500 431 0.011973
```

Any Ideas?

(This is running through the `linux-server/calibre-web` docker image)

**Comment by OzzieIsaacs** [comment]
I‘ll take a look this evening

**Comment by OzzieIsaacs** [comment]
I can't reproduce it. 
As far as I know is the linux-server-docker image build once a week. I did a change on failing line of code at the weekend. I think if you update the docker image next week, the error should disappear.

**Comment by EternalDeiwos** [comment]
I updated and the tasks view seems to be working again. Closing this.
