### ISSUE TITLE
exception occured installing in mac

### ISSUE THREAD

**Issue by amritms** [janeczku/calibre-web#721]
I followed the quick start steps on this repo and got the exception.

System: Mac OSX 10.13.6
pip version: 18.1
python version: 2.7.15

sudo pip install --target vendor -r requirements.txt

Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/pip/_internal/cli/base_command.py", line 143, in main
    status = self.run(options, args)
  File "/usr/local/lib/python2.7/site-packages/pip/_internal/commands/install.py", line 366, in run
    use_user_site=options.use_user_site,
  File "/usr/local/lib/python2.7/site-packages/pip/_internal/req/__init__.py", line 49, in install_given_reqs
    **kwargs
  File "/usr/local/lib/python2.7/site-packages/pip/_internal/req/req_install.py", line 760, in install
    use_user_site=use_user_site, pycompile=pycompile,
  File "/usr/local/lib/python2.7/site-packages/pip/_internal/req/req_install.py", line 382, in move_wheel_files
    warn_script_location=warn_script_location,
  File "/usr/local/lib/python2.7/site-packages/pip/_internal/wheel.py", line 215, in move_wheel_files
    prefix=prefix,
  File "/usr/local/lib/python2.7/site-packages/pip/_internal/locations.py", line 165, in distutils_scheme
    i.finalize_options()
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/command/install.py", line 264, in finalize_options
    "must supply either home or prefix/exec-prefix -- not both"
DistutilsOptionError: must supply either home or prefix/exec-prefix -- not both

PS: I don't know python.

**Comment by OzzieIsaacs** [comment]
A quick googling gave the following result:


On OSX(mac), assuming a project folder called /var/myproject

    cd /var/myproject
    Create a file called setup.cfg and add
    [install]
    prefix=
    Run pip install -r requirements.txt -t .

(https://stackoverflow.com/questions/24257803/distutilsoptionerror-must-supply-either-home-or-prefix-exec-prefix-not-both)

You could also try: pip install -r requirements.txt (without the target stuff), this should install the requirements global
