### ISSUE TITLE
OSError: [Errno 20] Not a directory

### ISSUE THREAD

**Issue by ChrisThoma** [janeczku/calibre-web#729]
This error only started showing up after installing the optional requirements.
I'm on OSX for reference.

Traceback (most recent call last):
  File "cps.py", line 13, in <module>
    from cps.server import Server
  File "/Users/christhoma/development/dsa/calibre-web/cps/server.py", line 8, in <module>
    import web
  File "/Users/christhoma/development/dsa/calibre-web/cps/web.py", line 84, in <module>
    import rarfile
  File "/Users/christhoma/development/dsa/calibre-web/vendor/rarfile.py", line 2950, in <module>
    _check_unrar_tool()
  File "/Users/christhoma/development/dsa/calibre-web/vendor/rarfile.py", line 2931, in _check_unrar_tool
    custom_check([ORIG_UNRAR_TOOL], True)
  File "/Users/christhoma/development/dsa/calibre-web/vendor/rarfile.py", line 2823, in custom_check
    p = custom_popen(cmd)
  File "/Users/christhoma/development/dsa/calibre-web/vendor/rarfile.py", line 2813, in custom_popen
    creationflags=creationflags)
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 20] Not a directory

**Comment by ChrisThoma** [comment]
I went through and installed the optional requirements one by one and the failure started happening when I got to rarfile.

**Comment by ChrisThoma** [comment]
brew install unrar fixed this.
