### ISSUE TITLE
Crash with * (asterisk) in Accept-Language header

### ISSUE THREAD

**Issue by guardiande** [janeczku/calibre-web#739]
I'm using the `technosoft2000/calibre-web` docker image and since I upgraded the image recently Kobo's web browser causes internal server errors when trying to login.

It boils down to the browser sending the `Accept-Language` header: 

```
Accept-Language: de-DE,de;q=0.9,en;q=0.8,*;q=0.7
```

This causes the following exception:

```
[2018-12-30 12:28:52,493] ERROR in app: Exception on /login [GET]
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/calibre-web/app/cps/web.py", line 2347, in login
    return render_title_template('login.html', title=_(u"login"), next_url=next_url,
  File "/usr/lib/python2.7/site-packages/flask_babel/__init__.py", line 552, in gettext
    t = get_translations()
  File "/usr/lib/python2.7/site-packages/flask_babel/__init__.py", line 227, in get_translations
    [get_locale()],
  File "/usr/lib/python2.7/site-packages/flask_babel/__init__.py", line 257, in get_locale
    rv = babel.locale_selector_func()
  File "/calibre-web/app/cps/web.py", line 197, in get_locale
    preferred = [str(LC.parse(x.replace('-','_'))) for x in request.accept_languages.values()]
  File "/usr/lib/python2.7/site-packages/babel/core.py", line 268, in parse
    parts = parse_locale(identifier, sep=sep)
  File "/usr/lib/python2.7/site-packages/babel/core.py", line 1094, in parse_locale
    raise ValueError('expected only letters, got %r' % lang)
ValueError: expected only letters, got '*'
::ffff:172.18.0.2 - - [2018-12-30 12:28:52] "GET /login?next=%2Fbooks%2Ffiction%2F HTTP/1.1" 500 412 0.015654
```

This can be easily reproduced by the follow `curl` command:

```
curl -H 'Accept-Language: de-DE,de;q=0.9,en;q=0.8,*;q=0.7' https://server.url/books/login?next=%2Fbooks%2Ffiction%2F
```

Removing the `*` successfully processes the request.

**Comment by OzzieIsaacs** [comment]
Yes, I see the problem, I‘ll fix it later
