### ISSUE TITLE
Attempting to view PDF's in the browser results in 500 errors

### ISSUE THREAD

**Issue by mlg9000** [janeczku/calibre-web#78]
As stated in the title, Epub seems to work.  The errors I get are:

Traceback (most recent call last):
  File "/opt/calibre-web/vendor/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/calibre-web/vendor/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/calibre-web/vendor/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/calibre-web/vendor/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/calibre-web/vendor/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/calibre-web/vendor/flask_login.py", line 792, in decorated_view
    return func(*args, **kwargs)
  File "/opt/calibre-web/cps/web.py", line 906, in read_book
    return render_template('readpdf.html', pdffile=all_name, title=_(u"Read a Book"))
  File "/opt/calibre-web/vendor/flask/templating.py", line 133, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/opt/calibre-web/vendor/jinja2/environment.py", line 851, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/opt/calibre-web/vendor/jinja2/environment.py", line 812, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/opt/calibre-web/vendor/jinja2/environment.py", line 786, in _load_template
    template = self.loader.load(self, name, globals)
  File "/opt/calibre-web/vendor/jinja2/loaders.py", line 125, in load
    code = environment.compile(source, name, filename)
  File "/opt/calibre-web/vendor/jinja2/environment.py", line 565, in compile
    self.handle_exception(exc_info, source_hint=source_hint)
  File "/opt/calibre-web/vendor/jinja2/environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/calibre-web/cps/templates/readpdf.html", line 29, in template
    <title>{{_(PDF.js viewer)}}</title>

**Comment by OzzieIsaacs** [comment]
Could you please check and verify that you are on the latest commit? 
Line 29 in cps/templates/readpdf.html should read: 
    <title>{{_(PDF.js viewer)}}</title>

**Comment by mlg9000** [comment]
This is happening with the latest version from git

**Comment by mlg9000** [comment]
After reloading with the update I no longer see any errors, but the PDF's don't actually load.  There isn't anything in the log or debug output that indicates what's going on.

**Comment by OzzieIsaacs** [comment]
I check it on windows firefox, and internet explorer and also under Linux with firefox. It is working for me. 
How far do you/your computer get? 
Which browser do you use?
Does a new window/tab open? If yes, could you please check the error console of your web browser (Firefox: Extras, Web developer, web console or similar, I'm on a non english system).
Is the file for reading created ([calibre-web folder]\cps\static\[bookno] (you can see the book no. if you move the mouse over the "read in browser -> pdf" button in calibre web, it's the last no. in the link displayed.) If not, we may have some access rights problem. 
Server runs on windows or Linux?

**Comment by mlg9000** [comment]
It turns out it does work now.  I have calibre-web behind a reverse proxy and for whatever reason PDF fail to load but EPUB is fine.  Hitting it directly works so I need to sort out my proxy issue.  Thanks for the fix.
