### ISSUE TITLE
500 Internal Server Error after connecting "read" status on every page -- totally broke it. 

### ISSUE THREAD

**Issue by jvimedia** [janeczku/calibre-web#788]
ERROR:flask.app:Exception on /admin/viewconfig [GET]
Traceback (most recent call last):
  File "/theuserrunningcalibreweb/calibre-web/vendor/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/theuserrunningcalibreweb/calibre-web/vendor/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/theuserrunningcalibreweb/calibre-web/vendor/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/theuserrunningcalibreweb/calibre-web/vendor/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/theuserrunningcalibreweb/calibre-web/vendor/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/theuserrunningcalibreweb/calibre-web/vendor/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/theuserrunningcalibreweb/calibre-web/cps/web.py", line 448, in inner
    return f(*args, **kwargs)
  File "/theuserrunningcalibreweb/calibre-web/cps/web.py", line 2875, in view_configuration
    .filter(db.and_(db.Custom_Columns.datatype == 'bool',db.Custom_Columns.mark_for_delete == 0)).all()
  File "/theuserrunningcalibreweb/calibre-web/vendor/sqlalchemy/orm/query.py", line 2925, in all
    return list(self)
  File "/theuserrunningcalibreweb/calibre-web/vendor/sqlalchemy/orm/query.py", line 3081, in __iter__
    return self._execute_and_instances(context)
  File "/theuserrunningcalibreweb/calibre-web/vendor/sqlalchemy/orm/query.py", line 3103, in _execute_and_instances
    querycontext, self._connection_from_session, close_with_result=True
  File "/theuserrunningcalibreweb/calibre-web/vendor/sqlalchemy/orm/query.py", line 3111, in _get_bind_args
    mapper=self._bind_mapper(), clause=querycontext.statement, **kw
  File "/theuserrunningcalibreweb/calibre-web/vendor/sqlalchemy/orm/query.py", line 3096, in _connection_from_session
    conn = self.session.connection(**kw)
  File "/theuserrunningcalibreweb/calibre-web/vendor/sqlalchemy/orm/session.py", line 1120, in connection
    execution_options=execution_options,
  File "/theuserrunningcalibreweb/calibre-web/vendor/sqlalchemy/orm/session.py", line 1126, in _connection_for_bind
    engine, execution_options
  File "/theuserrunningcalibreweb/calibre-web/vendor/sqlalchemy/orm/session.py", line 401, in _connection_for_bind
    self._assert_active()
  File "/theuserrunningcalibreweb/calibre-web/vendor/sqlalchemy/orm/session.py", line 288, in _assert_active
    % self._rollback_exception
InvalidRequestError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (sqlite3.OperationalError) attempt to write a readonly database [SQL: u'DELETE FROM books_authors_link WHERE books_authors_link.book = ? AND books_authors_link.author = ?'] [parameters: ((6695, 3665), (6692, 3661), (6676, 3649), (6693, 2999), (6691, 3662), (6677, 3650), (6724, 3802), (6723, 3803), (6713, 3805), (6706, 3806))] (Background on this error at: http://sqlalche.me/e/e3q8)
ERROR:tornado.access:500 GET /admin/viewconfig (192.168.XXX.XXX) 23.82ms

**Comment by OzzieIsaacs** [comment]
The errormessage tells me you tried to delete authors from a book, which didn't work out, because you didn't have write access to the calibre database at that time. 
(Maybe calibre was open in parallel and tried to write also to the database?)
Please try to restart calibre-web, it should work again afterwards. If not, please try to rebuild database from calibre.

**Comment by jvimedia** [comment]
Weird, I wasn't aware that I did that. I simply linked the calibre read database to calibre-web.
Then everything 500'ed no matter what I did. Restarting calibre-web is fixing it. 
I couldn't reproduce the error. Therefore I will close this for now.
