### ISSUE TITLE
Problems connecting to google drive [Docker]

### ISSUE THREAD

**Issue by seyo-IV** [janeczku/calibre-web#791]
I have installed the docker images of calibre-web. Now im having trouble to connect it to google drive. Iv downlaoded the json file and placed it in the container under calibre-web.

On the configuration page im getting "Bitte Google Drive Konfiguration nach Login beenden" but no prompt or redirection appears. When i click on send. It loads the page gain and shows me a menu under google drive but there are no options i can choose.

Idk what im doing wrong.

**Comment by seyo-IV** [comment]
Ok now im getting redirected but im getting also a Initial Server Error

**Comment by seyo-IV** [comment]
ok here are the logs
`[2019-01-30 15:43:32,438] {/usr/lib/python2.7/site-packages/flask/app.py:1761} ERROR - Exception on /config [POST]
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/app/calibre-web/cps/web.py", line 438, in inner
    return f(*args, **kwargs)
  File "/app/calibre-web/cps/web.py", line 2987, in basic_configuration
    return configuration_helper(1)
  File "/app/calibre-web/cps/web.py", line 3016, in configuration_helper
    if filedata['web']['redirect_uris'][0].endswith('/'):
KeyError: 'redirect_uris'
`

**Comment by OzzieIsaacs** [comment]
Could you please log in as admin. And go to the setup page in admin section. Afterwards the redirect to google and back should work. (One issue might be that you might start from localhost and google will redirect you to the adress which is acceccable from outside like www.myoutsideadress.com/calibre-web. If you are not logged in on that adress this could be an issue.

**Comment by OzzieIsaacs** [comment]
There have been some bugs in the recent version, so Google Drive setup could not completed, could you please update to the newest version and try again.

**Comment by OzzieIsaacs** [comment]
No feedback for long time, so I'll close the issue

**Comment by christophwolff** [comment]
I got the same error. Iam on the latest container.

`[2019-10-15 21:51:23,874] ERROR in app: Exception on /config [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/app/calibre-web/cps/web.py", line 475, in inner
    return f(*args, **kwargs)
  File "/app/calibre-web/cps/web.py", line 2921, in basic_configuration
    return configuration_helper(1)
  File "/app/calibre-web/cps/web.py", line 2952, in configuration_helper
    if filedata['web']['redirect_uris'][0].endswith('/'):
KeyError: 'redirect_uris'`

**Comment by christophwolff** [comment]
I have the version running here
https://calibre.chrislautlos.de
