### ISSUE TITLE
Redirect 404's

### ISSUE THREAD

**Issue by truitt661** [janeczku/calibre-web#792]
I've been trying to get google drive to redirect back to the site when authenticate google drive. I am using ubuntu 18.04 nginx reverse proxy, no docker. I have the callback set as sim.domain.com/gdrive/callback. 

I used grive to sync my google drive but still havent been able to fullly accomplished this yet. I have loads of books on my google drive and been trying to get this thing to work for months. 

Please help.

[2019-01-31 19:22:45,317] {/home/robert/projects/calibre-web/cps/gdriveutils.py:160} ERROR - Google Drive error: No credential to refresh.
[2019-01-31 19:22:45,318] {/home/robert/projects/calibre-web/cps/helper.py:437} ERROR - Error Message: No credential to refresh.
[2019-01-31 19:22:45,318] {/home/robert/projects/calibre-web/cps/helper.py:438} ERROR - No credential to refresh.
Traceback (most recent call last):
  File "/home/robert/projects/calibre-web/cps/helper.py", line 430, in get_book_cover
    path=gd.get_cover_via_gdrive(cover_path)
  File "/home/robert/projects/calibre-web/cps/gdriveutils.py", line 485, in get_cover_via_gdrive
    df = getFileFromEbooksFolder(cover_path, 'cover.jpg')
  File "/home/robert/projects/calibre-web/cps/gdriveutils.py", line 259, in getFileFromEbooksFolder
    drive = getDrive(Gdrive.Instance().drive)
  File "/home/robert/projects/calibre-web/cps/gdriveutils.py", line 169, in getDrive
    drive.auth.Refresh()
  File "/home/robert/projects/calibre-web/vendor/pydrive/auth.py", line 468, in Refresh
    raise RefreshError('No credential to refresh.')
RefreshError: No credential to refresh.
[2019-01-31 19:24:23,658] {/home/robert/projects/calibre-web/cps/web.py:2268} INFO - Login failed for user "admin" IP-adress: 71.201.212.30
[2019-01-31 19:24:34,028] {/home/robert/projects/calibre-web/cps/helper.py:437} ERROR - Error Message: No credential to refresh.
[2019-01-31 19:24:34,028] {/home/robert/projects/calibre-web/cps/helper.py:438} ERROR - No credential to refresh.
Traceback (most recent call last):
  File "/home/robert/projects/calibre-web/cps/helper.py", line 430, in get_book_cover
    path=gd.get_cover_via_gdrive(cover_path)
  File "/home/robert/projects/calibre-web/cps/gdriveutils.py", line 485, in get_cover_via_gdrive
    df = getFileFromEbooksFolder(cover_path, 'cover.jpg')
  File "/home/robert/projects/calibre-web/cps/gdriveutils.py", line 259, in getFileFromEbooksFolder
    drive = getDrive(Gdrive.Instance().drive)
  File "/home/robert/projects/calibre-web/cps/gdriveutils.py", line 169, in getDrive
    drive.auth.Refresh()
  File "/home/robert/projects/calibre-web/vendor/pydrive/auth.py", line 468, in Refresh
    raise RefreshError('No credential to refresh.')
RefreshError: No credential to refresh.

**Comment by OzzieIsaacs** [comment]
I can reproduce the error. I try to improve the setup.

**Comment by truitt661** [comment]
ok

**Comment by OzzieIsaacs** [comment]
Please change the update channel to nightly and try the newest commit. 
There is a bug in the current updater, which deletes all Google Drive relevant files, so please backup: settings.yaml, gdrive.db, gdrive_credentials and client_secrets.json, if you have those files.

**Comment by truitt661** [comment]
Hey it's working now

**Comment by ge2sasag** [comment]
I think I have s imilar problem now. When I give permission to google drive in the last step of authentication and it is supposed to go to yourdomain/calibre-web/gdrive/callback, I get a 404 error saying that my page does not exists. I checked the client_secrets.json file and it is properly written.
