### ISSUE TITLE
500 error on viewing books

### ISSUE THREAD

**Issue by Oreolek** [janeczku/calibre-web#801]
Master branch, latest commit. On single book pages and AJAX blocks: error 500

Log file has this.
```
[2019-02-05 12:59:32,784] {[calibre-web root]/vendor/flask/app.py:1761} ERROR - Exception on /book/190 [GET]
Traceback (most recent call last):
  File "[calibre-web root]/vendor/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "[calibre-web root]/vendor/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "[calibre-web root]/vendor/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "[calibre-web root]/vendor/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "[calibre-web root]/vendor/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "[calibre-web root]/cps/web.py", line 341, in decorated_view
    return func(*args, **kwargs)
  File "[calibre-web root]/cps/web.py", line 1590, in show_book
    have_read=have_read, kindle_list=kindle_list, reader_list=reader_list, page="book")
  File "[calibre-web root]/cps/web.py", line 701, in render_title_template
    return render_template(instance=config.config_calibre_web_title, *args, **kwargs)
  File "[calibre-web root]/vendor/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "[calibre-web root]/vendor/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "[calibre-web root]/cps/templates/detail.html", line 1, in top-level template code
    {% extends is_xhr|yesno("fragment.html", "layout.html") %}
  File "[calibre-web root]/cps/templates/layout.html", line 188, in top-level template code
    {% block body %}{% endblock %}
  File "[calibre-web root]/cps/templates/detail.html", line 8, in block "body"
    <img src="{{ url_for('get_cover', book_id=entry.id) }}" alt="{{ entry.title }}" />
  File "[calibre-web root]/vendor/flask/helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "[calibre-web root]/vendor/flask/app.py", line 2061, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "[calibre-web root]/vendor/flask/helpers.py", line 345, in url_for
    force_external=external)
  File "[calibre-web root]/vendor/werkzeug/routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
BuildError: Could not build url for endpoint 'get_cover' with values ['book_id']. Did you forget to specify values ['cover_path']?
```

**Comment by OzzieIsaacs** [comment]
For me it'S working: Please check file cps/web.py
![grafik](https://user-images.githubusercontent.com/6438895/52299645-3dc22180-2986-11e9-9f2c-adc97378eea8.png)
line 2030 and 2032 look like in the screenshot. Seems like they don't in your copy??

**Comment by Oreolek** [comment]
They are same as in your screenshot.
