### ISSUE TITLE
500 error on basepage after upgrade. Admin view is intact

### ISSUE THREAD

**Issue by simkin** [janeczku/calibre-web#808]
```
[2019-02-11 09:08:57,531] {/opt/calibre-web/vendor/flask/app.py:1761} ERROR - Exception on / [GET]
Traceback (most recent call last):
  File "/opt/calibre-web/vendor/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/calibre-web/vendor/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/calibre-web/vendor/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/calibre-web/vendor/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/calibre-web/vendor/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/calibre-web/cps/web.py", line 342, in decorated_view
    return login_required(func)(*args, **kwargs)
  File "/opt/calibre-web/vendor/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/opt/calibre-web/cps/web.py", line 1210, in index
    title=_(u"Recently Added Books"), page="root")
  File "/opt/calibre-web/cps/web.py", line 701, in render_title_template
    return render_template(instance=config.config_calibre_web_title, *args, **kwargs)
  File "/opt/calibre-web/vendor/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/opt/calibre-web/vendor/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/opt/calibre-web/vendor/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/opt/calibre-web/vendor/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/calibre-web/cps/templates/index.html", line 1, in top-level template code
    {% extends "layout.html" %}
  File "/opt/calibre-web/cps/templates/layout.html", line 188, in top-level template code
    {% block body %}{% endblock %}
  File "/opt/calibre-web/cps/templates/index.html", line 13, in block "body"
    <img src="{{ url_for('get_cover', cover_path=entry.path.replace('\\','/')) }}" alt="{{ entry.title }}" />
  File "/opt/calibre-web/vendor/flask/helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/opt/calibre-web/vendor/flask/app.py", line 2061, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/opt/calibre-web/vendor/flask/helpers.py", line 345, in url_for
    force_external=external)
  File "/opt/calibre-web/vendor/werkzeug/routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
BuildError: Could not build url for endpoint 'get_cover' with values ['cover_path']. Did you forget to specify values ['book_id']?
```

**Comment by OzzieIsaacs** [comment]
The file cps/templates/index.html is not the newest version, line 13 should be:
` <img src="{{ url_for('get_cover', book_id=entry.id) }}" alt="{{ entry.title }}" />`
Your error indicates it's:
`<img src="{{ url_for('get_cover', cover_path=entry.path.replace('\\','/')) }}" alt="{{ entry.title }}" />`
Could you please check the file content. You are the second one complainig about it. Maybe there is some caching issue of jnjia template engine used by calibre-web. If the file is the right one, could you please stop calibre-web, restart it again, check if problem is disappeared, if not please search for some caching files of index.html (I don't know where, because I never had it.) 
If you can post the version of jinija and tornado/gevent from the about section, I can try to figure it out.
(Your Browser cache maybe could also be the problem??)

**Comment by simkin** [comment]
Might has something to do with the updater not always working for me (need to force restart the service for the process to complete). I run calibre as user:group and I suspect sometimes that causes a permission error womewhere, either in /tmp or when restarting the service, not sure if that makes sense or not?

Line 13:
<img src="{{ url_for('get_cover', cover_path=entry.path.replace('\\','/')) }}" alt="{{ entry.title }}" />

I am hosting calibre-web behind Cloudflare CDN that does some caching, but I disabled to make sure this is not the rootcause

**Comment by OzzieIsaacs** [comment]
Okay, so the index.html file is old version, you need to replace it (or at least this file) with the newest version from github to make it work again.

**Comment by OzzieIsaacs** [comment]
The updater is downloading the zip file from github webpage, extracting it to [tempfolder]/calibre-web, checking afterwards all files in the tempfile with the files in the calibre-web folder and generating a list of files to delete. Afterwards all files from tempfolder are copied over the files in the calibre-web folder and deleting the files to delete. 
At last the WSGI server and the worker thread (does emailing and converting in background) are stopped and calibre-web forks itself into a new process. (At that point you should see a message like restarting Calibre-web)

**Comment by simkin** [comment]
Admin view version page showed I was on the latest version, nevertheless git pull updated lots of files, Restarted and now all is OK. Somehow I think it related to the updater but if I am the only one complaining about it I can imagine you are doubting this :)

Closing this one and will recreate separate one for updater if I have better logs
