### ISSUE TITLE
[help wanted] Can't access any category

### ISSUE THREAD

**Issue by roberpreston** [janeczku/calibre-web#847]
I'm running calibre-web 0.6.1 on macOS, python 3.7.2. I can access Recently Added and open those books, I can upload and edit books, I can access and change Settings too but I can't access any category/search due to `Internal Server Error`. 

This is the log output:

```
[2019-03-17 17:01:41,400] ERROR in app: Exception on /series/37/ [GET]
Traceback (most recent call last):
  File "/calibre-web/vendor/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/calibre-web/vendor/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/calibre-web/vendor/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/calibre-web/vendor/flask/_compat.py", line 33, in reraise
    raise value
  File "/calibre-web/vendor/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/calibre-web/vendor/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/calibre-web/cps/web.py", line 344, in decorated_view
    return login_required(func)(*args, **kwargs)
  File "/calibre-web/vendor/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/calibre-web/cps/web.py", line 1430, in series
    title=_(u"Series: %(serie)s", serie=name.name), page="series")
  File "/calibre-web/cps/web.py", line 703, in render_title_template
    return render_template(instance=config.config_calibre_web_title, accept=EXTENSIONS_UPLOAD, *args, **kwargs)
  File "/calibre-web/vendor/flask/templating.py", line 134, in render_template
    context, ctx.app)
  File "/calibre-web/vendor/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/calibre-web/vendor/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/calibre-web/vendor/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/calibre-web/vendor/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/calibre-web/vendor/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/calibre-web/cps/templates/index.html", line 1, in top-level template code
    {% extends "layout.html" %}
  File "/calibre-web/cps/templates/layout.html", line 190, in top-level template code
    {% block body %}{% endblock %}
  File "/calibre-web/cps/templates/index.html", line 25, in block "body"
    {% if loop.index > config_authors_max and config_authors_max != 0 %}
jinja2.exceptions.UndefinedError: 'config_authors_max' is undefined
ERROR:tornado.access:500 GET /series/37/ (127.0.0.1) 31.26ms
WARNING:tornado.access:404 GET /favicon.ico (127.0.0.1) 9.33ms
```

Any clue on how to fix this?

**Comment by OzzieIsaacs** [comment]
The project is currently in transition from updating everybody with everything to a stable/nightly system. Unfortunately there was a bug in the updater, so I had to revert this system. It looks now you've updated from an older version right into this system and you now stuck in a "buggy commit". Could you please change the updater to nightly (admin -> basic configuration -> server settings). Then you should have the option to update to a newer commit, where is issue is fixed. It's recommend afterwards to revert the updater setting to "stable"

**Comment by roberpreston** [comment]
Thank you @OzzieIsaacs. Problem fixed.
