### ISSUE TITLE
error when checking settings for some users

### ISSUE THREAD

**Issue by sbelongie** [janeczku/calibre-web#91]
When I click to see my profile or one other user I get a 500 error.
I tried to reinstall calibre-web but still have the issue.

Here is the log 

ERROR - Exception on /admin/user/2 [GET]
Traceback (most recent call last):
  File "D:\github\calibre-web\vendor\flask\app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\github\calibre-web\vendor\flask\app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\github\calibre-web\vendor\flask\app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\github\calibre-web\vendor\flask\app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\github\calibre-web\vendor\flask\app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\github\calibre-web\vendor\flask_login.py", line 792, in decorated_view
    return func(*args, **kwargs)
  File "D:\github\calibre-web\cps\web.py", line 319, in inner
    return f(*args, **kwargs)
  File "D:\github\calibre-web\cps\web.py", line 1657, in edit_user
    content=content, downloads=downloads, title=_(u"Edit User %(nick)s", nick=content.nickname))
  File "D:\github\calibre-web\vendor\flask\templating.py", line 134, in render_template
    context, ctx.app)
  File "D:\github\calibre-web\vendor\flask\templating.py", line 116, in _render
    rv = template.render(context)
  File "D:\github\calibre-web\vendor\jinja2\environment.py", line 989, in render
    return self.environment.handle_exception(exc_info, True)
  File "D:\github\calibre-web\vendor\jinja2\environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "D:\github\calibre-web\cps\templates\user_edit.html", line 1, in top-level template code
    {% extends "layout.html" %}
  File "D:\github\calibre-web\cps\templates\layout.html", line 158, in top-level template code
    {% block body %}{% endblock %}
  File "D:\github\calibre-web\cps\templates\user_edit.html", line 104, in block "body"
    <a class="pull-left" href="{{ url_for('show_book', id=entry.id) }}">
  File "D:\github\calibre-web\vendor\flask\helpers.py", line 322, in url_for
    force_external=external)
  File "D:\github\calibre-web\vendor\werkzeug\routing.py", line 1756, in build
    rv = self._partial_build(endpoint, values, method, append_unknown)
  File "D:\github\calibre-web\vendor\werkzeug\routing.py", line 1671, in _partial_build
    append_unknown)
  File "D:\github\calibre-web\vendor\werkzeug\routing.py", line 1679, in _partial_build
    rv = rule.build(values, append_unknown)
  File "D:\github\calibre-web\vendor\werkzeug\routing.py", line 798, in build
    add(self._converters[data].to_url(values[data]))
  File "D:\github\calibre-web\vendor\werkzeug\routing.py", line 1016, in to_url
    value = self.num_convert(value)
UndefinedError: 'None' has no attribute 'id'

**Comment by OzzieIsaacs** [comment]
Did you change recently the used calibre library?
The error indicates this. Calibre-web tries to access books which are no longer accessible. To fix this you should delete the app.db and start calibre-web again.

**Comment by sbelongie** [comment]
Ok i will try this when I get a chance tomorrow

**Comment by OzzieIsaacs** [comment]
If you try the newest commit, the error should no longer occour

**Comment by sbelongie** [comment]
You are da man. That fixed it
