### ISSUE TITLE
With wrong permissions conversion .epub to .mobi fails without errormessage

### ISSUE THREAD

**Issue by Calimerorulez** [janeczku/calibre-web#952]
Hi,

First of all, thanks for the great work!

As a new user of calibre-web, I just finished installing and configuring.

When trying to send an .epub ebook to my Kindle, the conversion with ebook-convert (v3.44) fails:

```
[2019-06-29 12:43:21,580] {/home/calibre-web/calibre-web/cps/worker.py:262} INFO - Book id 47621 - target format of .mobi does not exist. Moving forward with convert.
[2019-06-29 12:43:22,240] {/home/calibre-web/calibre-web/cps/worker.py:323} DEBUG - 1% Converting input to HTML...
[2019-06-29 12:43:22,257] {/home/calibre-web/calibre-web/cps/worker.py:323} DEBUG - InputFormatPlugin: EPUB Input running
[2019-06-29 12:43:22,268] {/home/calibre-web/calibre-web/cps/worker.py:323} DEBUG - on /sharedfolders/ebooks/Rick Pastoor/Grip (47621)/Grip - Rick Pastoor.epub
[2019-06-29 12:43:22,286] {/home/calibre-web/calibre-web/cps/worker.py:323} DEBUG - Found HTML cover 0.xhtml
[2019-06-29 12:43:22,306] {/home/calibre-web/calibre-web/cps/worker.py:323} DEBUG - Parsing all content...
[2019-06-29 12:43:22,785] {/home/calibre-web/calibre-web/cps/worker.py:323} DEBUG - PropertyValue: Missing token for production Choice(ColorValue, Dimension, URIValue, Value, variable, MSValue, CSSCalc, function): (u'HASH', u'#black', 511, 12)
[2019-06-29 12:43:22,787] {/home/calibre-web/calibre-web/cps/worker.py:323} DEBUG - No content to parse.
[2019-06-29 12:43:22,790] {/home/calibre-web/calibre-web/cps/worker.py:323} DEBUG - PropertyValue: Unknown syntax or no value:  #black
[2019-06-29 12:43:22,791] {/home/calibre-web/calibre-web/cps/worker.py:323} DEBUG - CSSStyleDeclaration: Syntax Error in Property: color: #black
[2019-06-29 12:43:22,794] {/home/calibre-web/calibre-web/cps/worker.py:323} DEBUG - PropertyValue: Missing token for production Choice(ColorValue, Dimension, URIValue, Value, variable, MSValue, CSSCalc, function): (u'HASH', u'#black', 520, 12)
[2019-06-29 12:43:22,795] {/home/calibre-web/calibre-web/cps/worker.py:323} DEBUG - No content to parse.
[2019-06-29 12:43:22,796] {/home/calibre-web/calibre-web/cps/worker.py:323} DEBUG - PropertyValue: Unknown syntax or no value:  #black
[2019-06-29 12:43:22,798] {/home/calibre-web/calibre-web/cps/worker.py:323} DEBUG - CSSStyleDeclaration: Syntax Error in Property: color: #black
[2019-06-29 12:43:22,799] {/home/calibre-web/calibre-web/cps/worker.py:323} DEBUG - PropertyValue: Missing token for production Choice(ColorValue, Dimension, URIValue, Value, variable, MSValue, CSSCalc, function): (u'HASH', u'#black', 530, 12)
[2019-06-29 12:43:22,800] {/home/calibre-web/calibre-web/cps/worker.py:323} DEBUG - No content to parse.
[2019-06-29 12:43:22,802] {/home/calibre-web/calibre-web/cps/worker.py:323} DEBUG - PropertyValue: Unknown syntax or no value:  #black
[2019-06-29 12:43:22,803] {/home/calibre-web/calibre-web/cps/worker.py:323} DEBUG - CSSStyleDeclaration: Syntax Error in Property: color: #black
[2019-06-29 12:43:22,806] {/home/calibre-web/calibre-web/cps/worker.py:323} DEBUG - PropertyValue: Missing token for production Choice(ColorValue, Dimension, URIValue, Value, variable, MSValue, CSSCalc, function): (u'HASH', u'#black', 540, 12)
[2019-06-29 12:43:22,807] {/home/calibre-web/calibre-web/cps/worker.py:323} DEBUG - No content to parse.
[2019-06-29 12:43:22,808] {/home/calibre-web/calibre-web/cps/worker.py:323} DEBUG - PropertyValue: Unknown syntax or no value:  #black
[2019-06-29 12:43:22,811] {/home/calibre-web/calibre-web/cps/worker.py:323} DEBUG - CSSStyleDeclaration: Syntax Error in Property: color: #black
[2019-06-29 12:43:22,920] {/home/calibre-web/calibre-web/cps/worker.py:323} DEBUG - 34% Running transforms on e-book...
[2019-06-29 12:43:23,112] {/home/calibre-web/calibre-web/cps/worker.py:323} DEBUG - Merging user specified metadata...
[2019-06-29 12:43:23,114] {/home/calibre-web/calibre-web/cps/worker.py:323} DEBUG - Detecting structure...
[2019-06-29 12:43:23,176] {/home/calibre-web/calibre-web/cps/worker.py:323} DEBUG - Flattening CSS and remapping font sizes...
[2019-06-29 12:43:27,541] {/home/calibre-web/calibre-web/cps/worker.py:323} DEBUG - Source base font size is 12.00000pt
[2019-06-29 12:43:28,386] {/home/calibre-web/calibre-web/cps/worker.py:323} DEBUG - Removing fake margins...
[2019-06-29 12:43:28,444] {/home/calibre-web/calibre-web/cps/worker.py:323} DEBUG - Cleaning up manifest...
[2019-06-29 12:43:28,445] {/home/calibre-web/calibre-web/cps/worker.py:323} DEBUG - Trimming unused files from manifest...
[2019-06-29 12:43:28,487] {/home/calibre-web/calibre-web/cps/worker.py:323} DEBUG - Trimming u'0.xhtml' from manifest
[2019-06-29 12:43:28,488] {/home/calibre-web/calibre-web/cps/worker.py:323} DEBUG - Creating MOBI Output...
[2019-06-29 12:43:28,489] {/home/calibre-web/calibre-web/cps/worker.py:323} DEBUG - 67% Running MOBI Output plugin
[2019-06-29 12:43:28,541] {/home/calibre-web/calibre-web/cps/worker.py:323} DEBUG - Serializing resources...
[2019-06-29 12:43:29,030] {/home/calibre-web/calibre-web/cps/worker.py:323} DEBUG - Creating MOBI 6 output
[2019-06-29 12:43:29,123] {/home/calibre-web/calibre-web/cps/worker.py:323} DEBUG - Applying case-transforming CSS...
[2019-06-29 12:43:34,658] {/home/calibre-web/calibre-web/cps/worker.py:323} DEBUG - Rasterizing SVG images...
[2019-06-29 12:43:34,673] {/home/calibre-web/calibre-web/cps/worker.py:323} DEBUG - Converting XHTML to Mobipocket markup...
[2019-06-29 12:43:43,396] {/home/calibre-web/calibre-web/cps/worker.py:323} DEBUG - 
[2019-06-29 12:43:43,396] {/home/calibre-web/calibre-web/cps/worker.py:353} INFO - ebook converter failed with error while converting book
[2019-06-29 12:43:43,397] {/home/calibre-web/calibre-web/cps/worker.py:497} ERROR - Ebook converter failed with unknown error
```

When running the command manually (ebook-convert "Grip - Rick Pastoor.epub" "Grip - Rick Pastoor.mobi") no error occours:

```
1% Converting input to HTML...
InputFormatPlugin: EPUB Input running
on /sharedfolders/ebooks/Rick Pastoor/Grip (47621)/Grip - Rick Pastoor.epub
Found HTML cover 0.xhtml
Parsing all content...
PropertyValue: Missing token for production Choice(ColorValue, Dimension, URIValue, Value, variable, MSValue, CSSCalc, function): (u'HASH', u'#black', 511, 12)
No content to parse.
PropertyValue: Unknown syntax or no value:  #black
CSSStyleDeclaration: Syntax Error in Property: color: #black
PropertyValue: Missing token for production Choice(ColorValue, Dimension, URIValue, Value, variable, MSValue, CSSCalc, function): (u'HASH', u'#black', 520, 12)
No content to parse.
PropertyValue: Unknown syntax or no value:  #black
CSSStyleDeclaration: Syntax Error in Property: color: #black
PropertyValue: Missing token for production Choice(ColorValue, Dimension, URIValue, Value, variable, MSValue, CSSCalc, function): (u'HASH', u'#black', 530, 12)
No content to parse.
PropertyValue: Unknown syntax or no value:  #black
CSSStyleDeclaration: Syntax Error in Property: color: #black
PropertyValue: Missing token for production Choice(ColorValue, Dimension, URIValue, Value, variable, MSValue, CSSCalc, function): (u'HASH', u'#black', 540, 12)
No content to parse.
PropertyValue: Unknown syntax or no value:  #black
CSSStyleDeclaration: Syntax Error in Property: color: #black
34% Running transforms on e-book...
Merging user specified metadata...
Detecting structure...
Flattening CSS and remapping font sizes...
Source base font size is 12.00000pt
Removing fake margins...
Cleaning up manifest...
Trimming unused files from manifest...
Trimming u'0.xhtml' from manifest
Creating MOBI Output...
67% Running MOBI Output plugin
Serializing resources...
Creating MOBI 6 output
Applying case-transforming CSS...
Rasterizing SVG images...
Converting XHTML to Mobipocket markup...
Serializing markup content...
  Compressing markup content...
Generating MOBI index for a book
MOBI output written to /sharedfolders/ebooks/Rick Pastoor/Grip (47621)/Grip - Rick Pastoor.mobi
Output saved to   /sharedfolders/ebooks/Rick Pastoor/Grip (47621)/Grip - Rick Pastoor.mobi
```

What am I missing? :-)

**Comment by OzzieIsaacs** [comment]
I think it's not your fault, it's a problem with the book in combination with calibre-web. I tried some of my books all of them worked, but I don't have books producing errors like
> CSSStyleDeclaration: Syntax Error in Property: color: #black
> PropertyValue: Missing token for production Choice(ColorValue, Dimension, URIValue, Value, variable, MSValue, CSSCalc, function): (u'HASH', u'#black', 540, 12)
> No content to parse.

I think the fix for you could be doing a check of the book with sigil (https://sigil-ebook.com/). For a fix for everybody I need the book to check what's wrong (maybe return value is something I don't expect). If you are willing to send me the book to my email address listed on my Guthub profile page, I'll take a look at it.

**Comment by Calimerorulez** [comment]
I just mailed you two books as an example.

**Comment by OzzieIsaacs** [comment]
I got the book. From your post I assume you are using linux. For me it was working, so it#s not a problem with the book itself. I sould reproduce the error if the folder 
`/sharedfolders/ebooks/Rick Pastoor/Grip (47621)/` has only access permission: r-x (missing the write permission) for the user running calibre-web. 
Calibre reports the error on stderr:
``
Traceback (most recent call last):
  File "site.py", line 77, in main
  File "site-packages/calibre/ebooks/conversion/cli.py", line 401, in main
  File "site-packages/calibre/ebooks/conversion/plumber.py", line 1274, in run
  File "site-packages/calibre/ebooks/conversion/plugins/mobi_output.py", line 214, in convert
  File "site-packages/calibre/ebooks/conversion/plugins/mobi_output.py", line 251, in write_mobi
  File "site-packages/calibre/ebooks/mobi/writer2/main.py", line 61, in __call__
IOError: [Errno 13] Keine Berechtigung: u'????/Rick Pastoor/GRIP (361)/GRIP - Rick Pastoor.mobi'
``
Could you please check the access permissions for the folder? I'll try to find away to catch this error

**Comment by OzzieIsaacs** [comment]
And my calibre version is 3.44 (just in case the behaviour/output is different in different versions)

**Comment by Calimerorulez** [comment]
Yes, it has to do with permissions... Sorry for the confusion. I tested it with the correct permissions, and now it works...

**Comment by OzzieIsaacs** [comment]
Error message is now logged
