### ISSUE TITLE
Tasks page won't load when a task has been running for more than a day

### ISSUE THREAD

**Issue by Iristyle** [janeczku/calibre-web#954]
Running calibre-web in Docker based on SHA https://github.com/janeczku/calibre-web/commits/66283c542f256d441780c10ec1935f8c6e29b63e

When the runtime of a task exceeds a day, the parsing at https://github.com/janeczku/calibre-web/blob/master/cps/worker.py#L489 will fail:

```
[2019-06-28 22:37:50,052] ERROR in app: Exception on /tasks [GET]
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/python2.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/calibre-web/app/cps/web.py", line 1646, in get_tasks_status
    tasks=helper.global_WorkerThread.get_taskstatus()
  File "/calibre-web/app/cps/worker.py", line 225, in get_taskstatus
    datetime.now() - self.queue[self.current]['starttime'])
  File "/calibre-web/app/cps/worker.py", line 489, in _formatRuntime
    if int(v) > 0:
ValueError: invalid literal for int() with base 10: '1 day, 5'
::ffff:172.17.0.1 - - [2019-06-28 22:37:50] "GET /tasks HTTP/1.1" 500 411 0.011915
```

**Comment by OzzieIsaacs** [comment]
Indeed, I wasn't expecting a task to run longer than a few minutes, so this isn't handled (yet)

**Comment by OzzieIsaacs** [comment]
Should work now with the newest commit
