### ISSUE TITLE
When converting ePub to mobi, the tasks page generates a 500 error

### ISSUE THREAD

**Issue by Calimerorulez** [janeczku/calibre-web#959]
Hi,

I'm running the latest beta.

I'm trying to send a ePub to my Kindle. The tasks page generates a 500 (internal server) error. Sending to Kindle works correctly though.

```
Jul 11 20:01:27 lara python3[24820]: [2019-07-11 20:01:27,270] INFO in worker: Book id 42929 - target format of .mobi does not exist. Moving forward with convert.
Jul 11 20:01:27 lara python3[24820]: [2019-07-11 20:01:27,784] DEBUG in worker: 1% Converting input to HTML...
Jul 11 20:01:27 lara python3[24820]: [2019-07-11 20:01:27,784] DEBUG in worker: InputFormatPlugin: EPUB Input running
Jul 11 20:01:27 lara python3[24820]: [2019-07-11 20:01:27,785] DEBUG in worker: on /sharedfolders/ebooks/Shamash Alidina/Mindfulness voor Dummies (42929)/Mindfulness voor Dummies - Shamash Alidina.epub
Jul 11 20:01:28 lara python3[24820]: [2019-07-11 20:01:28,047] DEBUG in worker: Found HTML cover OEBPS/Text/Section0001.html
Jul 11 20:01:28 lara python3[24820]: [2019-07-11 20:01:28,064] DEBUG in worker: Parsing all content...
Jul 11 20:01:28 lara python3[24820]: [2019-07-11 20:01:28,915] DEBUG in worker: 34% Running transforms on e-book...
Jul 11 20:01:29 lara python3[24820]: [2019-07-11 20:01:29,100] DEBUG in worker: Merging user specified metadata...
Jul 11 20:01:29 lara python3[24820]: [2019-07-11 20:01:29,101] DEBUG in worker: Detecting structure...
Jul 11 20:01:29 lara python3[24820]: [2019-07-11 20:01:29,173] DEBUG in worker: Flattening CSS and remapping font sizes...
Jul 11 20:01:33 lara python3[24820]: [2019-07-11 20:01:33,266] DEBUG in worker: Source base font size is 12.00000pt
Jul 11 20:01:34 lara python3[24820]: [2019-07-11 20:01:34,651] DEBUG in worker: Removing fake margins...
Jul 11 20:01:35 lara python3[24820]: [2019-07-11 20:01:35,409] DEBUG in worker: Cleaning up manifest...
Jul 11 20:01:35 lara python3[24820]: [2019-07-11 20:01:35,410] DEBUG in worker: Trimming unused files from manifest...
Jul 11 20:01:35 lara python3[24820]: [2019-07-11 20:01:35,475] DEBUG in worker: Trimming u'OEBPS/Text/Section0001.html' from manifest
Jul 11 20:01:35 lara python3[24820]: [2019-07-11 20:01:35,601] DEBUG in worker: Creating MOBI Output...
Jul 11 20:01:35 lara python3[24820]: [2019-07-11 20:01:35,602] DEBUG in worker: 67% Running MOBI Output plugin
Jul 11 20:01:35 lara python3[24820]: [2019-07-11 20:01:35,722] DEBUG in worker: Serializing resources...
Jul 11 20:01:36 lara python3[24820]: [2019-07-11 20:01:36,594] DEBUG in worker: Creating MOBI 6 output
Jul 11 20:01:36 lara python3[24820]: [2019-07-11 20:01:36,682] DEBUG in worker: Generating in-line TOC...
Jul 11 20:01:36 lara python3[24820]: [2019-07-11 20:01:36,693] DEBUG in worker: Applying case-transforming CSS...
Jul 11 20:01:39 lara systemd[1]: Started Session 3268 of user root.
Jul 11 20:01:44 lara python3[24820]: [2019-07-11 20:01:44,777] DEBUG in worker: Rasterizing SVG images...
Jul 11 20:01:44 lara python3[24820]: [2019-07-11 20:01:44,810] DEBUG in worker: Converting XHTML to Mobipocket markup...
Jul 11 20:01:57 lara python3[24820]: [2019-07-11 20:01:57,970] DEBUG in worker: Serializing markup content...
Jul 11 20:01:58 lara python3[24820]: [2019-07-11 20:01:58,585] DEBUG in worker:   Compressing markup content...
Jul 11 20:02:01 lara python3[24820]: [2019-07-11 20:02:01,547] ERROR in app: Exception on /tasks [GET]
Jul 11 20:02:01 lara python3[24820]: Traceback (most recent call last):
Jul 11 20:02:01 lara python3[24820]:   File "/home/calibre-web/calibre-web/vendor/flask/app.py", line 2311, in wsgi_app
Jul 11 20:02:01 lara python3[24820]:     response = self.full_dispatch_request()
Jul 11 20:02:01 lara python3[24820]:   File "/home/calibre-web/calibre-web/vendor/flask/app.py", line 1834, in full_dispatch_request
Jul 11 20:02:01 lara python3[24820]:     rv = self.handle_user_exception(e)
Jul 11 20:02:01 lara python3[24820]:   File "/home/calibre-web/calibre-web/vendor/flask/app.py", line 1737, in handle_user_exception
Jul 11 20:02:01 lara python3[24820]:     reraise(exc_type, exc_value, tb)
Jul 11 20:02:01 lara python3[24820]:   File "/home/calibre-web/calibre-web/vendor/flask/_compat.py", line 36, in reraise
Jul 11 20:02:01 lara python3[24820]:     raise value
Jul 11 20:02:01 lara python3[24820]:   File "/home/calibre-web/calibre-web/vendor/flask/app.py", line 1832, in full_dispatch_request
Jul 11 20:02:01 lara python3[24820]:     rv = self.dispatch_request()
Jul 11 20:02:01 lara python3[24820]:   File "/home/calibre-web/calibre-web/vendor/flask/app.py", line 1818, in dispatch_request
Jul 11 20:02:01 lara python3[24820]:     return self.view_functions[rule.endpoint](**req.view_args)
Jul 11 20:02:01 lara python3[24820]:   File "/home/calibre-web/calibre-web/vendor/flask_login/utils.py", line 261, in decorated_view
Jul 11 20:02:01 lara python3[24820]:     return func(*args, **kwargs)
Jul 11 20:02:01 lara python3[24820]:   File "/home/calibre-web/calibre-web/cps/web.py", line 1647, in get_tasks_status
Jul 11 20:02:01 lara python3[24820]:     answer = helper.render_task_status(tasks)
Jul 11 20:02:01 lara python3[24820]:   File "/home/calibre-web/calibre-web/cps/helper.py", line 608, in render_task_status
Jul 11 20:02:01 lara python3[24820]:     task['runtime'] = format_runtime(task['formRuntime'])
Jul 11 20:02:01 lara python3[24820]: KeyError: 'formRuntime'
Jul 11 20:02:04 lara python3[24820]: ::ffff:192.168.100.156 - - [2019-07-11 20:02:01] "GET /tasks HTTP/1.1" 500 411 0.013245
```

**Comment by OzzieIsaacs** [comment]
Sorry I mismerged is from the development branch, please try the newest commit

**Comment by Calimerorulez** [comment]
Works great now, thanks :-)

**Comment by Calimerorulez** [comment]
Well, another problem now, maybe unrelated:

```
Jul 11 20:45:52 lara python3[24820]: The above exception was the direct cause of the following exception:
Jul 11 20:45:52 lara python3[24820]: Traceback (most recent call last):
Jul 11 20:45:52 lara python3[24820]:   File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
Jul 11 20:45:52 lara python3[24820]:     self.run()
Jul 11 20:45:52 lara python3[24820]:   File "/home/calibre-web/calibre-web/cps/worker.py", line 191, in run
Jul 11 20:45:52 lara python3[24820]:     self._convert_any_format()
Jul 11 20:45:52 lara python3[24820]:   File "/home/calibre-web/calibre-web/cps/worker.py", line 236, in _convert_any_format
Jul 11 20:45:52 lara python3[24820]:     filename = self._convert_ebook_format()
Jul 11 20:45:52 lara python3[24820]:   File "/home/calibre-web/calibre-web/cps/worker.py", line 352, in _convert_ebook_format
Jul 11 20:45:52 lara python3[24820]:     web.db.session.commit()
Jul 11 20:45:52 lara python3[24820]:   File "/home/calibre-web/calibre-web/vendor/sqlalchemy/orm/session.py", line 1027, in commit
Jul 11 20:45:52 lara python3[24820]:     self.transaction.commit()
Jul 11 20:45:52 lara python3[24820]:   File "/home/calibre-web/calibre-web/vendor/sqlalchemy/orm/session.py", line 498, in commit
Jul 11 20:45:52 lara python3[24820]:     t[1].commit()
Jul 11 20:45:52 lara python3[24820]:   File "/home/calibre-web/calibre-web/vendor/sqlalchemy/engine/base.py", line 1716, in commit
Jul 11 20:45:52 lara python3[24820]:     self._do_commit()
Jul 11 20:45:52 lara python3[24820]:   File "/home/calibre-web/calibre-web/vendor/sqlalchemy/engine/base.py", line 1747, in _do_commit
Jul 11 20:45:52 lara python3[24820]:     self.connection._commit_impl()
Jul 11 20:45:52 lara python3[24820]:   File "/home/calibre-web/calibre-web/vendor/sqlalchemy/engine/base.py", line 763, in _commit_impl
Jul 11 20:45:52 lara python3[24820]:     self._handle_dbapi_exception(e, None, None, None, None)
Jul 11 20:45:52 lara python3[24820]:   File "/home/calibre-web/calibre-web/vendor/sqlalchemy/engine/base.py", line 1466, in _handle_dbapi_exception
Jul 11 20:45:52 lara python3[24820]:     util.raise_from_cause(sqlalchemy_exception, exc_info)
Jul 11 20:45:52 lara python3[24820]:   File "/home/calibre-web/calibre-web/vendor/sqlalchemy/util/compat.py", line 399, in raise_from_cause
Jul 11 20:45:52 lara python3[24820]:     reraise(type(exception), exception, tb=exc_tb, cause=cause)
Jul 11 20:45:52 lara python3[24820]:   File "/home/calibre-web/calibre-web/vendor/sqlalchemy/util/compat.py", line 153, in reraise
Jul 11 20:45:52 lara python3[24820]:     raise value.with_traceback(tb)
Jul 11 20:45:52 lara python3[24820]:   File "/home/calibre-web/calibre-web/vendor/sqlalchemy/engine/base.py", line 761, in _commit_impl
Jul 11 20:45:52 lara python3[24820]:     self.engine.dialect.do_commit(self.connection)
Jul 11 20:45:52 lara python3[24820]:   File "/home/calibre-web/calibre-web/vendor/sqlalchemy/engine/default.py", line 503, in do_commit
Jul 11 20:45:52 lara python3[24820]:     dbapi_connection.commit()
Jul 11 20:45:52 lara python3[24820]: sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked
Jul 11 20:45:52 lara python3[24820]: (Background on this error at: http://sqlalche.me/e/e3q8)

```

**Comment by OzzieIsaacs** [comment]
Has nothing to do with the first one. The calibre-db is locked/write protected. Please try to stop calibre-web and start afterwards (maybe rebooting also could help). Could also be a problem with insufficient access rights to calibre-db (if it never worked before)

**Comment by Calimerorulez** [comment]
Ok, I will try to reproduce it. Thanks.
