### ISSUE TITLE
Conversion of epub -> mobi stuck at 67%

### ISSUE THREAD

**Issue by Iristyle** [janeczku/calibre-web#967]
Book conversions are getting stuck at 67% for multiple days for very small epub files.

Running `technosoft2000/calibre-web:latest` container (SHA `3d892b29bb3fd42e969f063cb92c81f40c8f6d8832675a876a73358ba2f3d6f6` / `v1.3.2`) with calibre-web source at https://github.com/janeczku/calibre-web/commits/b1cb712

Program library | Installed Version
-- | --
Sqlite | v3.26.0
lxml | v4.3.3.0
ImageMagick | ImageMagick 6.9.10-40 Q16 x86_64 2019-04-18 https://imagemagick.org
Wand | 0.5.2
Flask | v1.0.2
Babel | v2.6.0
pytz | v2019.1
PyPdf | v1.26.0
pySqlite | v2.6.0
Flask Login | v0.4.1
Iso 639 | v0.4.5
Python | 2.7.15 (default, Jan 24 2019, 16:32:39) [GCC 8.2.0]
Sqlalchemy | v1.3.3
Jinja2 | v2.10.1
Werkzeug | v0.15.2
Calibre converter | ebook-convert (calibre 3.40.1)
Requests | v2.21.0
Gevent | v1.4.0
Pillow | v6.0.0
Flask Principal | v0.4.0

<img width="1916" alt="Screen Shot 2019-07-19 at 9 17 45 AM" src="https://user-images.githubusercontent.com/394081/61551755-e29f5b00-aa0a-11e9-8092-ee16935e8bc2.png">

<img width="1145" alt="Screen Shot 2019-07-19 at 9 18 15 AM" src="https://user-images.githubusercontent.com/394081/61551750-dddaa700-aa0a-11e9-88ae-2ea04a678425.png">

<img width="860" alt="Screen Shot 2019-07-19 at 9 18 37 AM" src="https://user-images.githubusercontent.com/394081/61551746-d9ae8980-aa0a-11e9-908d-131f697ae5ad.png">

**Comment by PiDockMedia** [comment]
I have the same issue but I am using the linuxserver.io docker image and it is any conversion. It looks like it then crashes the server.

`[2019-07-22 22:51:46,792] INFO in worker: Book id 4916 - target format of .lit does not exist. Moving forward with convert.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/app/calibre-web/cps/worker.py", line 193, in run
    self._convert_any_format()
  File "/app/calibre-web/cps/worker.py", line 236, in _convert_any_format
    filename = self._convert_ebook_format()
  File "/app/calibre-web/cps/worker.py", line 352, in _convert_ebook_format
    web.db.session.commit()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 1027, in commit
    self.transaction.commit()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 498, in commit
    t[1].commit()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1716, in commit
    self._do_commit()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1747, in _do_commit
    self.connection._commit_impl()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 763, in _commit_impl
    self._handle_dbapi_exception(e, None, None, None, None)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1466, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/compat.py", line 398, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 761, in _commit_impl
    self.engine.dialect.do_commit(self.connection)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/default.py", line 505, in do_commit
    dbapi_connection.commit()
OperationalError: (sqlite3.OperationalError) database is locked
(Background on this error at: http://sqlalche.me/e/e3q8)
`

**Comment by OzzieIsaacs** [comment]
Thanks for the log-file. The error message "database is locked" points to a not write accessible calibre-db.
Are you using calibre-web in docker for a longer time? (Did this ever worked for you?)
Are other metadata change operations on the books working (changing title, author, uploading new books..)?
Are you accessing the calibre-database during conversion time with another tool (calibre itself)?
Is the calibre-database stored on the same computer where docker is running, or is it mounted via samba or something else?

**Comment by OzzieIsaacs** [comment]
Are there any news?
