### ISSUE TITLE
Error when starting calibre-web after updating

### ISSUE THREAD

**Issue by stumueller** [janeczku/calibre-web#968]
I've just updated Calibre-Web and now it wont start. I get hte following error message:

L:\Calibre-Web>cps.py
No handlers could be found for logger "cps.services"
Traceback (most recent call last):
  File "L:\Calibre-Web\cps.py", line 34, in <module>
    from cps import create_app
  File "L:\Calibre-Web\cps\__init__.py", line 68, in <module>
    config = config_sql.load_configuration(ub.session)
  File "L:\Calibre-Web\cps\config_sql.py", line 302, in load_configuration
    _migrate_database(session)
  File "L:\Calibre-Web\cps\config_sql.py", line 298, in _migrate_database
    _migrate_table(session, _Settings)
  File "L:\Calibre-Web\cps\config_sql.py", line 277, in _migrate_table
    session.execute(alter_table)
  File "L:\Python\lib\site-packages\sqlalchemy\orm\session.py", line 1139, in ex
ecute
    bind, close_with_result=True).execute(clause, params or {})
  File "L:\Python\lib\site-packages\sqlalchemy\engine\base.py", line 945, in exe
cute
    return meth(self, multiparams, params)
  File "L:\Python\lib\site-packages\sqlalchemy\sql\elements.py", line 263, in _e
xecute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "L:\Python\lib\site-packages\sqlalchemy\engine\base.py", line 1053, in _e
xecute_clauseelement
    compiled_sql, distilled_params
  File "L:\Python\lib\site-packages\sqlalchemy\engine\base.py", line 1189, in _e
xecute_context
    context)
  File "L:\Python\lib\site-packages\sqlalchemy\engine\base.py", line 1402, in _h
andle_dbapi_exception
    exc_info
  File "L:\Python\lib\site-packages\sqlalchemy\util\compat.py", line 203, in rai
se_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "L:\Python\lib\site-packages\sqlalchemy\engine\base.py", line 1182, in _e
xecute_context
    context)
  File "L:\Python\lib\site-packages\sqlalchemy\engine\default.py", line 470, in
do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) near "'ldap'": synta
x error [SQL: u"ALTER TABLE settings ADD COLUMN `config_ldap_schema` VARCHAR DEF
AULT u'ldap'"]

**Comment by OzzieIsaacs** [comment]
Should now work again

**Comment by stumueller** [comment]
Updated - Slightly different error now:
No handlers could be found for logger "cps.services"
Traceback (most recent call last):
  File "L:\Calibre-Web\cps.py", line 39, in <module>
    from cps.about import about
  File "L:\Calibre-Web\cps\about.py", line 43, in <module>
    Flask_Login=flask_login.__version__,
AttributeError: 'module' object has no attribute '__version__'

**Comment by OzzieIsaacs** [comment]
Okay, please try now

**Comment by stumueller** [comment]
Thats done it - thanks :-)

**Comment by pwr** [comment]
Sorry for commenting on a closed issue -- may I ask what flask-login version do you have?

**Comment by stumueller** [comment]
I'm not infront of my compter at the moment so I don't know, but I installed it as part of the requirements for calibre-web

**Comment by OzzieIsaacs** [comment]
The exposed version change from flask-login is in a commit from march 2017 (https://github.com/maxcountryman/flask-login/commit/d8c3a1c986c7f5cbd88f8246d7b67bb1075fd1ff), the latest release is 0.4.1 from december 2017 (which includes the version). So all release from before don't have this. My guess for the users version is 0.4 (or any version before)
