### ISSUE TITLE
error during download epub from opds catalog

### ISSUE THREAD

**Issue by minernet** [janeczku/calibre-web#98]
Hi,

I can download book from web interface. (url: https//sitename:port/calibre-web)

But I can't download by using opds catalog (OPDS catalogue url https://sitename:port/calibre-web/opds)

I had this error :

--------------------------------------------------
WARNING:tornado.access:401 GET //opds/download/3574/epub/ (::1) 0.92ms
[2017-01-30 23:33:08,449] ERROR in app: Exception on /opds/download/3574/epub/ [GET]
Traceback (most recent call last):
  File "/var/www/html/calibre-web/vendor/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/var/www/html/calibre-web/vendor/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/var/www/html/calibre-web/vendor/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/var/www/html/calibre-web/vendor/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/var/www/html/calibre-web/vendor/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/var/www/html/calibre-web/cps/web.py", line 197, in decorated
    return f(*args, **kwargs)
  File "/var/www/html/calibre-web/cps/web.py", line 315, in inner
    return f(*args, **kwargs)
  File "/var/www/html/calibre-web/cps/web.py", line 673, in get_opds_download_link
    response = make_response(send_from_directory(os.path.join(config.DB_ROOT, book.path), data.name + "." + format))
AttributeError: Config instance has no attribute 'DB_ROOT'
ERROR:cps.web:Exception on /opds/download/3574/epub/ [GET]
Traceback (most recent call last):
  File "/var/www/html/calibre-web/vendor/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/var/www/html/calibre-web/vendor/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/var/www/html/calibre-web/vendor/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/var/www/html/calibre-web/vendor/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/var/www/html/calibre-web/vendor/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/var/www/html/calibre-web/cps/web.py", line 197, in decorated
    return f(*args, **kwargs)
  File "/var/www/html/calibre-web/cps/web.py", line 315, in inner
    return f(*args, **kwargs)
  File "/var/www/html/calibre-web/cps/web.py", line 673, in get_opds_download_link
    response = make_response(send_from_directory(os.path.join(config.DB_ROOT, book.path), data.name + "." + format))
AttributeError: Config instance has no attribute 'DB_ROOT'
ERROR:tornado.access:500 GET //opds/download/3574/epub/ (::1) 8.74ms
---------------------------------------------------------------------------------

thank you for your help

**Comment by OzzieIsaacs** [comment]
Please do an update to the latest version, this is fixed meanwhile

**Comment by minernet** [comment]
resolved
