### ISSUE TITLE
500 Internal Server Error after initial login

### ISSUE THREAD

**Issue by jasehigh** [janeczku/calibre-web#983]
Trying to set-up calibre-web on a Mac running Python 2.7.10.

During the installation of the 'requirements.txt' I got the error:

```
ERROR: matplotlib 1.3.1 requires nose, which is not installed.
```

However, I can start there application, specify the location of my Calibre library, but when I log in (admin/admin123) I get the following errors displayed.

```
500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

File "/Users/admin/calibre-web/vendor/flask/app.py", line 2446, in wsgi_app response = self.full_dispatch_request()
File "/Users/admin/calibre-web/vendor/flask/app.py", line 1951, in full_dispatch_request rv = self.handle_user_exception(e)
File "/Users/admin/calibre-web/vendor/flask/app.py", line 1820, in handle_user_exception reraise(exc_type, exc_value, tb)
File "/Users/admin/calibre-web/vendor/flask/app.py", line 1949, in full_dispatch_request rv = self.dispatch_request()
File "/Users/admin/calibre-web/vendor/flask/app.py", line 1935, in dispatch_request return self.view_functions[rule.endpoint](**req.view_args)
File "/Users/admin/calibre-web/cps/web.py", line 1118, in login if user and check_password_hash(user.password, form['password']) and user.nickname != "Guest":
File "/Users/admin/calibre-web/vendor/werkzeug/security.py", line 221, in check_password_hash return safe_str_cmp(_hash_internal(method, salt, password)[0], hashval)
File "/Users/admin/calibre-web/vendor/werkzeug/security.py", line 153, in _hash_internal rv = pbkdf2_hex(password, salt, iterations, hashfunc=method)
File "/Users/admin/calibre-web/vendor/werkzeug/security.py", line 53, in pbkdf2_hex rv = pbkdf2_bin(data, salt, iterations, keylen, hashfunc)
File "/Users/admin/calibre-web/vendor/werkzeug/security.py", line 87, in pbkdf2_bin return hashlib.pbkdf2_hmac(hash_name, data, salt, iterations, keylen)
File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 171, in pbkdf2_hmac raise TypeError(hash_name)
```

All assistance greatly appreciated.

Jason.

**Comment by OzzieIsaacs** [comment]
Could you please check the logfile there should be one line more at the end of the error message, which could help to solve the mystery.
I assume you are not using docker?

**Comment by OzzieIsaacs** [comment]
And could you please post the context of the error message
`ERROR: matplotlib 1.3.1 requires nose, which is not installed.`

I think the error is related to one not installed dependency (maybe flask-login)

**Comment by OzzieIsaacs** [comment]
Looks like you are having the same issue as here: https://github.com/pallets/werkzeug/issues/1615.

So it's not flask-login. Could you please try to change line 1118 in web.py to:            
if user and check_password_hash(**str(**user.password**)**, form['password']) ...
(Please leave space in front and don't touch the rest of the string and check if it's working afterwards.

**Comment by jasehigh** [comment]
The installation error is as following:

```
Downloading https://files.pythonhosted.org/packages/d8/a6/f46ae3f1da0cd4361c344888f59ec2f5785e69c872e175a748ef6071cdb5/futures-3.3.0-py2-none-any.whl
Collecting MarkupSafe>=0.23 (from Jinja2>=2.5->Flask-Babel>=0.11.1->-r requirements.txt (line 2))
Downloading https://files.pythonhosted.org/packages/6d/d2/0ccd2c0e2cd93b35e765d9b3205cd6602e6b202b522fc7997531353715b3/MarkupSafe-1.1.1-cp27-cp27m-macosx_10_6_intel.whl
ERROR: matplotlib 1.3.1 requires nose, which is not installed.
Installing collected packages: pytz, Babel, MarkupSafe, Jinja2, itsdangerous, click, Werkzeug, Flask, Flask-Babel, Flask-Login, blinker, Flask-Principal, six, singledispatch, backports-abc, iso-639, PyPDF2, urllib3, certifi, chardet, idna, requests, SQLAlchemy, futures, tornado, Wand, unidecode
Successfully installed Babel-2.7.0 Flask-1.1.1 Flask-Babel-0.12.2 Flask-Login-0.4.1 Flask-Principal-0.4.0 Jinja2-2.10.1 MarkupSafe-1.1.1 PyPDF2-1.26.0 SQLAlchemy-1.3.6 Wand-0.5.5 Werkzeug-0.15.5 backports-abc-0.5 blinker-1.4 certifi-2019.6.16 chardet-3.0.4 click-7.0 futures-3.3.0 idna-2.8 iso-639-0.4.5 itsdangerous-1.1.0 pytz-2019.1 requests-2.22.0 singledispatch-3.4.0.3 six-1.12.0 tornado-5.1.1 unidecode-1.1.1 urllib3-1.25.3
```

and the calibre-web.log file contains:

```
[2019-07-28 19:47:07,478]  INFO {cps:89} Starting Calibre Web...
[2019-07-28 19:47:07,479]  WARN {cps.config_sql:259} invalidating configuration
[2019-07-28 19:47:07,691]  INFO {cps.server:149} Starting Tornado server on :8083
[2019-07-28 19:48:10,227]  INFO {cps.server:191} webserver stop (restart=True)
[2019-07-28 19:48:10,248]  INFO {cps.server:179} Performing restart of Calibre-Web
[2019-07-28 19:48:13,804]  INFO {cps:89} Starting Calibre Web...
[2019-07-28 19:48:13,974]  INFO {cps.server:149} Starting Tornado server on :8083
[2019-07-28 19:48:22,217] ERROR {cps:1891} Exception on /login [POST]
Traceback (most recent call last):
  File "/Users/admin/calibre-web/vendor/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/admin/calibre-web/vendor/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/admin/calibre-web/vendor/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/admin/calibre-web/vendor/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/admin/calibre-web/vendor/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/admin/calibre-web/cps/web.py", line 1118, in login
    if user and check_password_hash(user.password, form['password']) and user.nickname != "Guest":
  File "/Users/admin/calibre-web/vendor/werkzeug/security.py", line 221, in check_password_hash
    return safe_str_cmp(_hash_internal(method, salt, password)[0], hashval)
  File "/Users/admin/calibre-web/vendor/werkzeug/security.py", line 153, in _hash_internal
    rv = pbkdf2_hex(password, salt, iterations, hashfunc=method)
  File "/Users/admin/calibre-web/vendor/werkzeug/security.py", line 53, in pbkdf2_hex
    rv = pbkdf2_bin(data, salt, iterations, keylen, hashfunc)
  File "/Users/admin/calibre-web/vendor/werkzeug/security.py", line 87, in pbkdf2_bin
    return hashlib.pbkdf2_hmac(hash_name, data, salt, iterations, keylen)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 171, in pbkdf2_hmac
    raise TypeError(hash_name)
TypeError: sha256
[2019-07-28 19:50:28,775]  INFO {cps.server:191} webserver stop (restart=False)
[2019-07-28 19:50:28,776]  INFO {cps.server:176} Performing shutdown of Calibre-Web
```

I'm not using docker.

Hope this helps.

**Comment by OzzieIsaacs** [comment]
The error seems not to have effects. I think you are affected by the said problem. If the change helps, I'll include it in the code.

**Comment by jasehigh** [comment]
This changes fixed this issue. Many thanks indeed :-)

Jason.

> Looks like you are having the same issue as here: [pallets/werkzeug#1615](https://github.com/pallets/werkzeug/issues/1615).
> 
> So it's not flask-login. Could you please try to change line 1118 in web.py to:
> if user and check_password_hash(**str(**user.password**)**, form['password']) ...
> (Please leave space in front and don't touch the rest of the string and check if it's working afterwards.

**Comment by jasehigh** [comment]
All is working well, however, I have a similar issue when accessing the OPDS server. After entering my username and password I get the following error:

```
500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
File "/Users/admin/calibre-web/vendor/flask/app.py", line 2446, in wsgi_app response = self.full_dispatch_request()
File "/Users/admin/calibre-web/vendor/flask/app.py", line 1951, in full_dispatch_request rv = self.handle_user_exception(e)
File "/Users/admin/calibre-web/vendor/flask/app.py", line 1820, in handle_user_exception reraise(exc_type, exc_value, tb)
File "/Users/admin/calibre-web/vendor/flask/app.py", line 1949, in full_dispatch_request rv = self.dispatch_request()
File "/Users/admin/calibre-web/vendor/flask/app.py", line 1935, in dispatch_request return self.view_functions[rule.endpoint](**req.view_args)
File "/Users/admin/calibre-web/cps/opds.py", line 50, in decorated if not auth or not check_auth(auth.username, auth.password):
File "/Users/admin/calibre-web/cps/opds.py", line 291, in check_auth return bool(user and check_password_hash(user.password, password))
File "/Users/admin/calibre-web/vendor/werkzeug/security.py", line 221, in check_password_hash return safe_str_cmp(_hash_internal(method, salt, password)[0], hashval)
File "/Users/admin/calibre-web/vendor/werkzeug/security.py", line 153, in _hash_internal rv = pbkdf2_hex(password, salt, iterations, hashfunc=method)
File "/Users/admin/calibre-web/vendor/werkzeug/security.py", line 53, in pbkdf2_hex rv = pbkdf2_bin(data, salt, iterations, keylen, hashfunc)
File "/Users/admin/calibre-web/vendor/werkzeug/security.py", line 87, in pbkdf2_bin return hashlib.pbkdf2_hmac(hash_name, data, salt, iterations, keylen)
File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 171, in pbkdf2_hmac raise TypeError(hash_name)
```

**Comment by OzzieIsaacs** [comment]
Yes, correct. I changed the code there also, If you do an update to the newest commit, it should be solved

**Comment by jasehigh** [comment]
Updated to the news commit with the same fix in opds.py and the 500 internal server error is resolved.

However, when I connect via OPDS (using the Marvin app on an iPad (running iOS 12.3.1) I get an Oops message (Cannot downloaded feed).

The calibre-web.log shows the following error:

```
[2019-07-29 20:36:49,391] ERROR {tornado.application:55} Uncaught exception
Traceback (most recent call last):
  File "/Users/admin/calibre-web/vendor/tornado/http1connection.py", line 238, in _read_message
    delegate.finish()
  File "/Users/admin/calibre-web/vendor/tornado/httpserver.py", line 230, in finish
    self.request_callback(self.request)
  File "/Users/admin/calibre-web/vendor/tornado/wsgi.py", line 296, in __call__
    WSGIContainer.environ(request), start_response)
  File "/Users/admin/calibre-web/vendor/flask/app.py", line 2463, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/admin/calibre-web/cps/reverseproxy.py", line 78, in __call__
    return self.app(environ, start_response)
  File "/Users/admin/calibre-web/vendor/flask/app.py", line 2449, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/admin/calibre-web/vendor/flask/app.py", line 1878, in handle_exception
    server_error = handler(server_error)
  File "/Users/admin/calibre-web/cps/web.py", line 102, in internal_error
    instance=config.config_calibre_web_title
  File "/Users/admin/calibre-web/vendor/flask/templating.py", line 136, in render_template
    ctx.app.update_template_context(context)
  File "/Users/admin/calibre-web/vendor/flask/app.py", line 838, in update_template_context
    context.update(func())
  File "/Users/admin/calibre-web/vendor/flask_login/utils.py", line 368, in _user_context_processor
    return dict(current_user=_get_user())
  File "/Users/admin/calibre-web/vendor/flask_login/utils.py", line 335, in _get_user
    current_app.login_manager._load_user()
  File "/Users/admin/calibre-web/vendor/flask_login/login_manager.py", line 357, in _load_user
    return self._load_from_header(request.headers[header_name])
  File "/Users/admin/calibre-web/vendor/flask_login/login_manager.py", line 401, in _load_from_header
    user = self.header_callback(header)
  File "/Users/admin/calibre-web/cps/web.py", line 136, in load_user_from_header
    if user and check_password_hash(user.password, basic_password):
  File "/Users/admin/calibre-web/vendor/werkzeug/security.py", line 221, in check_password_hash
    return safe_str_cmp(_hash_internal(method, salt, password)[0], hashval)
  File "/Users/admin/calibre-web/vendor/werkzeug/security.py", line 153, in _hash_internal
    rv = pbkdf2_hex(password, salt, iterations, hashfunc=method)
  File "/Users/admin/calibre-web/vendor/werkzeug/security.py", line 53, in pbkdf2_hex
    rv = pbkdf2_bin(data, salt, iterations, keylen, hashfunc)
  File "/Users/admin/calibre-web/vendor/werkzeug/security.py", line 87, in pbkdf2_bin
    return hashlib.pbkdf2_hmac(hash_name, data, salt, iterations, keylen)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 171, in pbkdf2_hmac
    raise TypeError(hash_name)
TypeError: sha256
```

**Comment by OzzieIsaacs** [comment]
Sorry I say this piece of code, but didn't know anymore what's it for (I was nearly deleting it). Now the fix is applied also there, please update and (hopefully) enjoy the program

**Comment by jasehigh** [comment]
That's it... works perfectly. Thank you so much for all your help and super fast responses.

Calibre-web is amazing and just what I was looking for. Fantastic program.

**Comment by DennisYildirim** [comment]
Mine is giving the same error again and again....  Any ideas how to fix it ? 

Calibre-Web
Internal Server Error
500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
Traceback (most recent call last):
File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2073, in wsgi_app
response = self.full_dispatch_request()
File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1518, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1516, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1502, in dispatch_request
return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
File "/app/calibre-web/cps/usermanagement.py", line 38, in decorated_view
return login_required(func)(*args, **kwargs)
File "/usr/local/lib/python3.8/dist-packages/flask_login/utils.py", line 272, in decorated_view
return func(*args, **kwargs)
File "/app/calibre-web/cps/web.py", line 744, in index
return render_books_list("newest", sort_param, 1, page)
File "/app/calibre-web/cps/web.py", line 378, in render_books_list
entries, random, pagination = calibre_db.fill_indexpage(page, 0, db.Books, True, order[0],
File "/app/calibre-web/cps/db.py", line 713, in fill_indexpage
return self.fill_indexpage_with_archived_books(page, database, pagesize, db_filter, order, False,
File "/app/calibre-web/cps/db.py", line 720, in fill_indexpage_with_archived_books
randm = self.session.query(Books) \
File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/query.py", line 2759, in all
return self._iter().all()
File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/query.py", line 2894, in _iter
result = self.session.execute(
File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/session.py", line 1691, in execute
conn = self._connection_for_bind(bind)
File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/session.py", line 1532, in _connection_for_bind
return self._transaction._connection_for_bind(
File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/session.py", line 721, in _connection_for_bind
self._assert_active()
File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/session.py", line 601, in _assert_active
raise sa_exc.PendingRollbackError(
sqlalchemy.exc.PendingRollbackError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)
(sqlite3.OperationalError) database is locked
[SQL: DELETE FROM books_authors_link WHERE books_authors_link.book = ? AND books_authors_link.author = ?]
[parameters: (4249, 2589)]
(Background on this error at: https://sqlalche.me/e/14/e3q8) (Background on this error at: https://sqlalche.me/e/14/7s2a)
Please report this issue with all related information: [Create Issue](https://github.com/janeczku/calibre-web/issues/new?assignees=&labels=&template=bug_report.md&title=)

**Comment by payback007** [comment]
same error on my docker instance... I also tried to remove app.db, delete all config files, nothing changes. I always got the same error after the first sign-in.
