### ISSUE TITLE
No handlers could be found for logger "cps.services"

### ISSUE THREAD

**Issue by yunzhongci** [janeczku/calibre-web#987]
content
--
2019-07-30 05:35:07 | stderr | No handlers could be found for logger "cps.services"
2019-07-30 05:35:06 | stdout | [INFO] Launching Calibre-Web ...
2019-07-30 05:35:06 | stdout | > kindlegen link /calibre-web/app/vendor/kindlegen exists already and won't be recreated
2019-07-30 05:35:06 | stdout | [INFO] kindlegen (Amazon Kindle Generator) will be linked into /calibre-web/app/vendor
2019-07-30 05:35:06 | stdout | [INFO] Kindlegen application exists already in directory: /calibre-web/kindlegen
2019-07-30 05:35:06 | stdout | [INFO] The kindlegen directory exist already and will be used: /calibre-web/kindlegen
2019-07-30 05:35:06 | stdout | > Please check and modify the permissions of the directory
2019-07-30 05:35:06 | stdout | [WARNING] No write access at /books - new 'metadata.db' and books can't be stored at this directory
2019-07-30 05:35:06 | stdout | > The group calibre has no write access at /books
2019-07-30 05:35:06 | stdout | > Check if the group calibre has write access at /books
2019-07-30 05:35:06 | stdout | > The group : has no write access at /books
2019-07-30 05:35:06 | stdout | > Check if the group : has write access at /books
2019-07-30 05:35:06 | stdout | > The group calibre has no write access at /books
2019-07-30 05:35:06 | stdout | > Check if the group calibre has write access at /books
2019-07-30 05:35:06 | stdout | > Using permissions for checks: 0770
2019-07-30 05:35:06 | stdout | > Assigned owner ID: 1026
2019-07-30 05:35:06 | stdout | > Assigned owner: calibre
2019-07-30 05:35:06 | stdout | > Assigned group ID: 100
2019-07-30 05:35:06 | stdout | > Assigned group: users
2019-07-30 05:35:06 | stdout | > Permissions: 770
2019-07-30 05:35:06 | stdout | > Output is: 770 users 100 calibre 1026
2019-07-30 05:35:06 | stdout | [INFO] Checking permissions of the books directory: /books
2019-07-30 05:35:06 | stdout | [WARNING] No write access at /books - app.db and gdrive.db wont be linked into /books
2019-07-30 05:35:06 | stdout | > The group calibre has no write access at /books
2019-07-30 05:35:06 | stdout | > Check if the group calibre has write access at /books
2019-07-30 05:35:06 | stdout | > The group : has no write access at /books
2019-07-30 05:35:06 | stdout | > Check if the group : has write access at /books
2019-07-30 05:35:06 | stdout | > The group calibre has no write access at /books
2019-07-30 05:35:06 | stdout | > Check if the group calibre has write access at /books
2019-07-30 05:35:06 | stdout | > Using permissions for checks: 0770
2019-07-30 05:35:06 | stdout | > Assigned owner ID: 1026
2019-07-30 05:35:06 | stdout | > Assigned owner: calibre
2019-07-30 05:35:06 | stdout | > Assigned group ID: 100
2019-07-30 05:35:06 | stdout | > Assigned group: users
2019-07-30 05:35:06 | stdout | > Permissions: 770
2019-07-30 05:35:06 | stdout | > Output is: 770 users 100 calibre 1026
2019-07-30 05:35:06 | stdout | [INFO] Checking permissions of the config directory: /books
2019-07-30 05:35:06 | stdout | > due this the Calibre books directory /books will be used to store the configuration
2019-07-30 05:35:06 | stdout | [INFO] Config directory option is DEACTIVATED
2019-07-30 05:35:06 | stdout | 73bbffccaa66769204de818e349a69fea95d22a8
2019-07-30 05:35:06 | stdout | nothing to commit, working tree clean
2019-07-30 05:35:06 | stdout |  
2019-07-30 05:35:06 | stdout | Your branch is up to date with 'origin/master'.
2019-07-30 05:35:06 | stdout | On branch master
2019-07-30 05:35:06 | stdout | [INFO] ... git status after update is
2019-07-30 05:35:06 | stderr | fatal: unable to access 'https://github.com/janeczku/calibre-web.git/': Could not resolve host: github.com
2019-07-30 05:35:01 | stdout | [INFO] ... pulling sources
2019-07-30 05:35:01 | stdout | 73bbffccaa66769204de818e349a69fea95d22a8
2019-07-30 05:35:01 | stdout | nothing to commit, working tree clean
2019-07-30 05:35:01 | stdout |  
2019-07-30 05:35:01 | stdout | Your branch is up to date with 'origin/master'.
2019-07-30 05:35:01 | stdout | On branch master
2019-07-30 05:35:01 | stdout | [INFO] ... current git status is
2019-07-30 05:35:01 | stdout | [INFO] Autoupdate is active, try to pull the latest sources for Calibre-Web ...
2019-07-30 05:35:01 | stdout | [INFO] Checkout the latest Calibre-Web version ...
2019-07-30 05:35:01 | stdout | git version 2.20.1
2019-07-30 05:35:01 | stdout | [INFO] Current git version is:
2019-07-30 05:35:01 | stdout | [INFO] Change the ownership of /calibre-web (including subfolders) to calibre:calibre
2019-07-30 05:35:01 | stdout | [INFO] Container timezone is changed to: Asia/Shanghai
2019-07-30 05:35:01 | stdout | Tue Jul 30 13:35:01 CST 2019
2019-07-30 05:35:01 | stdout | [INFO] Current active timezone is CST
2019-07-30 05:35:01 | stderr | usermod: no changes
2019-07-30 05:35:01 | stdout | [WARNING] Assign non-unique user id 1026 to created user calibre
2019-07-30 05:35:01 | stderr | adduser: user 'calibre' in use
2019-07-30 05:35:01 | stdout | [WARNING] Create user calibre with temporary user id 999.
2019-07-30 05:35:01 | stdout | [WARNING] A user with id 1026 exists already [in use by calibre].
2019-07-30 05:35:00 | stdout | [WARNING] The group calibre will be renamed to calibre
2019-07-30 05:35:00 | stdout | [WARNING] A group with id 101 exists already [in use by calibre] and will be modified.
2019-07-30 05:35:00 | stdout | [INFO] Alpine Linux version: 3.9.0
2019-07-30 05:35:00 | stdout | [INFO] Docker image version: 1.3.2

**Comment by OzzieIsaacs** [comment]
This message is "right" for python2.

I can try to fix it this evening.

**Comment by muken** [comment]
Hi, I'm getting a similar message when trying to run cps.py for the first time after installation.
root@Plugins:/usr/local/calibre-web # python2.7 cps.py
No handlers could be found for logger "cps.services"
Traceback (most recent call last):
  File "cps.py", line 34, in <module>
    from cps import create_app
  File "/usr/local/calibre-web/cps/__init__.py", line 38, in <module>
    from .server import WebServer
  File "/usr/local/calibre-web/cps/server.py", line 33, in <module>
    from tornado.wsgi import WSGIContainer
  File "/usr/local/calibre-web/vendor/tornado/wsgi.py", line 51
    def to_wsgi_str(s: bytes) -> str:
                     ^
SyntaxError: invalid syntax

**Comment by OzzieIsaacs** [comment]
@pwr: How can we get rid of the message "No handlers could be found for logger "cps.services", it seems to confuse users. (You get it if you use python2, on python3 everything is okay)

**Comment by OzzieIsaacs** [comment]
@pwr thanks a lot for the fix

**Comment by pwr** [comment]
You're welcome.
