### ISSUE TITLE
Check for update fails

### ISSUE THREAD

**Issue by adilei** [janeczku/calibre-web#998]
Hi There, check for update fails with the following exception. I'm on 0.6.3.

Thanks!
```
[2019-08-03 20:55:49,971] {/usr/local/lib/python2.7/dist-packages/flask/app.py:1560} ERROR - Exception on /get_update_status [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/myuser/calibre-web/cps/web.py", line 349, in decorated_view
    return login_required(func)(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flask_login/utils.py", line 228, in decorated_view
    return func(*args, **kwargs)
  File "/home/myuser/calibre-web/cps/web.py", line 1187, in get_update_status
    return updater_thread.get_available_updates(request.method)
  File "/home/myuser/calibre-web/cps/updater.py", line 65, in get_available_updates
    return self._stable_available_updates(request_method)
  File "/home/myuser/calibre-web/cps/updater.py", line 425, in _stable_available_updates
    major_version_update = int(commit[i]['tag_name'].split('.')[0])
ValueError: invalid literal for int() with base 10: 'V0'
```

**Comment by OzzieIsaacs** [comment]
Thanks for reporting. Should be fixed now.
